### ISSUE TITLE
Keine Verbindung mit worker.php

### ISSUE THREAD

**Issue by xrking28** [Newcomer1989/TSN-Ranksystem#1]
Hallo, ich wollte mal nachfrage was ich machen kann wenn ich immer Connection Lost von der Worker.php bekomme?

**Comment by xrking28** [comment]
Ich bekomme immer Fehler 110, aber ich sende dir mal den Link in einer Pn dann siehst du es selbst

**Comment by Newcomer1989** [comment]
Der Fehler "Fehler 110: Connection timed out" deutet darauf hin, dass TeamSpeak Daten fehlerhaft sind. Bitte diese im Webinterface überpüfen.
Falls die Verbindung immer noch nicht funktioniert, obwohl die TS Daten eindeutig stimmen (Adresse und QueryPort), ist näher zu erforschen, warum die Verbindung vom Webspace zum TS nicht aufgebaut werden kann.
Da hier etliche Möglichkeiten in Frage kommen, bitte bei Bedarf mich kontaktieren, dann versuche ich gerne zu helfen.

**Comment by Newcomer1989** [comment]
https://github.com/Newcomer1989/TSN-Ranksystem/issues/1#
