### ISSUE TITLE
Doesn't start

### ISSUE THREAD

**Issue by am4nr** [Newcomer1989/TSN-Ranksystem#10]
When i start it using php worker.php start it says
`Starting the Ranksystem Bot. [OK]`

but when i use php worker.php status it says
`The Ranksystem does not seem to run.`

**Comment by Sqveeze** [comment]
Uhm, the bot connects automatically first time after you set the teamspeak ip,pass,serveradmin etc. After then you need to setup a cronjob and then it will check the status of the bot every 10 min, if the bot got dc or something, the cronjob rerun it and it will connect back. If its still on the server, then the cron does nothing.

**Comment by am4nr** [comment]
Yeah but it didn't start when i set it up and neither does it when i run php worker.php. it says "starting the ranksystem bot. [ok]" but nothing is happening

**Comment by Newcomer1989** [comment]
You checked the ranksystem logfile? Per default it lies in logs/ranksystem.log
Please post, what stands there.. perhaps there is the reason why it hasn't been able to connect to the TeamSpeak or why it stops.

**Comment by Newcomer1989** [comment]
Closed, due no reaction!
