### ISSUE TITLE
Install.php - Drop Database ?

### ISSUE THREAD

**Issue by Zignixx** [Newcomer1989/TSN-Ranksystem#101]
Maybe it would be good if you remove the drop database OR show a warning if you install it. Because of this "Drop Database", i lost my whole database. Why is it needed? Use a tsranking_ prefix or show at least a warning.

**Comment by Newcomer1989** [comment]
You want to clearly install the Ranksystem, it's important to be sure, there is no database or rest of a database. That is why it gets dropped at first.

In your case I think, you want to update the database. Then the install.php is the wrong way.

What you thought will happen, if you start to install the Rankystem and input an already existing database?

**Comment by Zignixx** [comment]
Well i used a database on our server which is for all the clan stuff. What i thought will happen? Install it over install.php without a drop. Other webinterfaces / cmd / forums can do this without a drop (custom table names as example).

**Comment by Newcomer1989** [comment]
Build for release 1.1.1:
There will come a warning message due instllation, if the database is already exisiting.

> ATTENTION: You are trying to install the Ranksystem, but there is already existing a database with the name \"DB-Name\".
Due installation this database will be dropped!
Be sure you want this. If not, please choose an other database name.
