### ISSUE TITLE
Reset weekly/monthly stats

### ISSUE THREAD

**Issue by juvcrafter** [Newcomer1989/TSN-Ranksystem#104]
Hey,
Can you make a function, which can reset weekly and monthly stats?

**Comment by Shad86** [comment]
It would be good if you could briefly describe why and for what you need this feature.

This also helps the dev and other people to understand your idea and make it easier to make Suggestions to your ideas

**Comment by juvcrafter** [comment]
We have given some users their online time back and because of this, the weekly/monthly stats are bugged.
Ist a good idea to add this Feature!

**Comment by Newcomer1989** [comment]
The stats will be calculated constantly so after one week/month the stats are "reset".

I think a reset to zero in this time would be not the best idea. I think it would be better to difference the given time.

But this feature will not be added before the function "to give user a new online time via the webinterface" comes back.

**Comment by Newcomer1989** [comment]
release 1.1.2 is out; this feature is part of the #94
