### ISSUE TITLE
Boost - removed all user out of servergroup

### ISSUE THREAD

**Issue by Sqveeze** [Newcomer1989/TSN-Ranksystem#11]
So i found out that if i create some group with boost and then i assign for like 5 people 10 hour boost that will increase the gain with 10, like:

282=>2=>3600,284=>3=>3600,285=>5=>3600,286=>7=>3600,287=>10=>3600,289=>10=>86400

So if i give group 289 for like 5 people at different time, eg: i give for one at 1:00PM and then the rest get the boost at 7:00PM

Well the boost works but, when the first one who got boost, get to the end of its 24H everyone get the boost removed. But the other 4 guy should still have it for 6 more hours. Is this a bug? Or i only need to apply the boost group on 1 people eg: myself and then everyone will level with boost?

**Comment by Newcomer1989** [comment]
I understand your problem. I have to check it.. For fist it looks like a problem with the boost function.

But I dont understand your last question!
So, it should be possible to add the group 289 to a different number of users. All of this user should boost for the specified time. BUT they only boost, if they are online/active (like configurated). The time (3rd parameter) will also elapse, if they are offline! And every user "boosts" for themselves.

**Comment by Sqveeze** [comment]
Yes but okey sorry for my english, i try to redescribe the problem. I configured the boost as you can see above. Then i gave 24 hour boost of 5 people but in different time. The time difference from the first boost to the last was like 9 hour. But then when the first guy got their 24H elapsed, the bot removed the boost from everyone. And you know the other 4 should have time left.

**Comment by YRisk** [comment]
Same Problem here.

**Comment by Newcomer1989** [comment]
should be solved with 1.0.1
