### ISSUE TITLE
Ranksystem [No Instances]

### ISSUE THREAD

**Issue by hellboy12332** [Newcomer1989/TSN-Ranksystem#110]
Hi, I can confirm that this issue is happening on php version 5.6.24 and 7.0.9, the database is working perfectly fine and same with the webUI this error happens even when running it via CMD and Taskscheduler, the only version that i have ever got to work was version 1.0.0 anything above from that i have these issues, some tips would be great. I am unable to provide any logs as it doesn't even get the the point of creating them sorry :/ 

This is on windows OS

Starting the Ranksystem bot .No Instance(s) Available. [Failed]

**Comment by Newcomer1989** [comment]
Please check you have installed the COM extension, which is needed since 1.0.2.

Also I already changed a few thing on the worker.php with version 1.1.1.
Please wait until 1.1.1 got released and then test your problem is still existing.. There is no ETA for 1.1.1 yet.

**Comment by Newcomer1989** [comment]
Release 1.1.1 is out. Please take an update and give us a feedback your problem still exists!?

**Comment by Newcomer1989** [comment]
Closed due no response. Reopen it, if you have still problems with it.

**Comment by hellboy12332** [comment]
Ok so here i am again, I have the current as of this post latest version installed of the rank system, i have made sure the php_com_dotnet.dll is in the my php/ext folder i have always made sure that extension=php_com_dotnet.dll is in my php.ini but still i get the above stated problem, this maybe due to my lack of knowledge but from the install instructions i have done everything it has stated.

**Comment by Newcomer1989** [comment]
I can offer you to help you via a remote session.

For this please join our public TS3 server (address: ts-n.net).

Search there for Newcomer1989 or Shad86.
