### ISSUE TITLE
Can't save the database configuration [chmod 0777]

### ISSUE THREAD

**Issue by LeonTaXz** [Newcomer1989/TSN-Ranksystem#111]
Servus wen ich meine Datenbank eintragen möchte kommt diese Fehler Meldung. (Ps. Ich versuche es auf einem Windows 2012 Server aufzusetzen)

`Can't save the database configuration! Please edit the 'other/dbconfig.php' with a chmod 0777 and try again after.
`
Liebe Grüße
Leon

**Comment by Shad86** [comment]
Für gewöhnlich eine Meldung für Linux.

Dennoch heißt das (oder sieht es wohl so aus) als ob auf Windowsebene hier die Berechtigung fehlt in diesem Ordner was zu verändern/schreiben.

Das mal überprüfen. Vielleicht spielt dir auch die UAC von Windows einen Streich bzw. funkt da eben dazwischen.

MfG

Shad86

**Comment by Newcomer1989** [comment]
Like Shad86 already described. You have to set the needed permissions to the folder/files.

chmod 0777  means in windows a full access.
