### ISSUE TITLE
list_rankup.php // Server groups

### ISSUE THREAD

**Issue by kecinotrab** [Newcomer1989/TSN-Ranksystem#112]
Hey, today i install ur ranksystem and have problem on list rankup. I select show server groups but when u go to list rankup u don't see any group icon .. idk why, thx for help :) (btw. i'm working on translate to my language :) )

http://imgur.com/a/mFyR3

ts3.hwns.pl/ranksystem/stats/list_rankup.php

**Comment by kecinotrab** [comment]
i have one more question, when i start bot, he work 5 sec and he off himself, idk why but in log is only one error.

> 2016-09-27 13:21:01.822593   ERROR     update_groups 6:('2', 'Admin Server Query', '500', ''),('3', 'Server Admin', '300', ''),('10', 'Server Admin', '582334931', '1474838534'),('11', 'Admin', '2766998993', '1474838534'),('12', 'HWNS MEMBER', '1830792522', '1474838534'),('13', 'HWNS FRIEND', '2023613318', '1474838534'),('29', 'GOLD NOVA I', '2910784082', '1474838534'),('30', 'GOLD NOVA II', '4202597190', '1474838535'),('31', 'GOLD NOVA III', '554494284', '1474838534'),('32', 'GOLD NOVA MASTER', '3410741069', '1474838534'),('33', 'MASTER GUARANDIAN I', '3587451302', '1474838535'),('34', 'MASTER GUARANDIAN II', '1371369749', '1474838534'),('35', 'MASTER GUARANDIAN ELITE', '3799467560', '1474838535'),('36', 'DMG', '221636005', '1474838533'),('37', 'LEGENDARY EAGLE', '107065407', '1474838533'),('38', 'LEGENDARY EAGLE MASTER', '1986299503', '1474838534'),('39', 'SUPREME', '1356566047', '1474838534'),('40', 'GLOBAL ELITE', '2404834277', '1474838534'),('42', 'BRONZ', '3394662609', '1474838534'),('43', 'SILVER', '1933837497', '1474838534'),('44', 'GOLD', '3525880661', '1474838535'),('45', 'PLATYNA', '2572488775', '1474838534'),('46', 'KRYSTAL', '3653207432', '1474838535'),('49', 'HOWNO', '1870265897', '1474838534'),('50', 'GAY', '685319600', '1474838533'),('51', 'TOXIC', '50853132', '1474838533'),('52', 'M4NY M4N', '4158464465', '1474838535'),('53', 'GRILL', '1237766804', '1474838534'),('54', 'DÝDŽEJ', '3558734792', '1474838535'),('55', 'ŘÍZEK', '2254284635', '1474838534'),('57', 'RANK LVL: 1', '808152662', '1474838711'),('58', 'RANK LVL: 2', '1814766304', '1474838711'),('59', 'RANK LVL: 3', '4230522134', '1474838711'),('60', 'RANK LVL: 4', '3556197433', '1474838711'),('61', 'RANK LVL: 5', '837566236', '1474838711'),('62', 'RANK LVL: 6', '2019913483', '1474838711'),('63', 'RANK LVL: 7', '668849155', '1474838711'),('64', 'RANK LVL: 8', '2155589841', '1474838711'),('65', 'RANK LVL: 9', '1178172676', '1474838711'),('66', 'RANK LVL: 10', '2843422655', '1474838711'),('67', 'RANK LVL: 11', '1574104159', '1474838711')1

`

**Comment by Newcomer1989** [comment]
Both described things are the same problem. Cause it can't save the groups, it can not show this on the stats page.

I already changed on this point some code for version 1.1.1.

Please wait until 1.1.1 got released and then test your problem is still existing.. There is no ETA for 1.1.1 yet.

**Comment by kecinotrab** [comment]
Okey, Thanks ! :)

**Comment by Newcomer1989** [comment]
Release 1.1.1 is out. Please take an update and give us a feedback your problem still exists!?

**Comment by Jo0Lz** [comment]
Thanks @Newcomer1989! The issue seems to be resolved on my end. Removed the complete directory and re-created the database, haven't seen anything that indicates this is still an issue.
Will monitor the logfiles. Thanks again!

**Comment by Newcomer1989** [comment]
@kecinotrab:
Could you have a look to the new version?
How far are you with the translation to polish? If you want I could give you an actual pre-release (version 1.1.2), where you will find he actual text lines.

**Comment by Newcomer1989** [comment]
Closed due no response. Should be solved 1.1.1.
