### ISSUE TITLE
Problem update_groups 6: - Download GroupIcons continuously

### ISSUE THREAD

**Issue by Jo0Lz** [Newcomer1989/TSN-Ranksystem#115]
I am having this exact same issue. Keeps downloading the ServerGroupIcon, and it keeps running into the same error.

http://pastebin.com/n3R21XTu

I am already running 1.1.0

#65

**Comment by Newcomer1989** [comment]
Your issue is also duplicate with https://github.com/Newcomer1989/TSN-Ranksystem/issues/112

Please pay attention for my answer there.

**Comment by Jo0Lz** [comment]
Ah, okay didn't see that post. I'll wait for the next release, thank you. :)
