### ISSUE TITLE
Fatal Error: undefined function password_hash() on install.php

### ISSUE THREAD

**Issue by ArchieGB** [Newcomer1989/TSN-Ranksystem#117]
Hey there,

I've been trying to install the latest version onto my shared hosting but every time I go to install it it asks for the database info then my login details, once it gets to step 2 though it gives me this error
`Fatal error: Call to undefined function password_hash() in /home/gamingbu/public_html/rank/install.php on line 233` 

I've tried a new database and completely reinstalling it but that doesn't work...

Hope you can help
Archie

**Comment by Newcomer1989** [comment]
That could happens, if your PHP version is to low. It must be 5.5.0 or higher. Please check this out.

To see the PHP version create a file like "info.php" on your webspace with the following content.
```
<?PHP
phpinfo();
?>
```

Open this file on your browser. On headline you will see the PHP version, which will be used on your system.

If it is under 5.5.0 you should update your PHP to solve the problem.

**Comment by ArchieGB** [comment]
Cheers, that's worked perfectly! Upgraded to version 7.0

**Comment by Newcomer1989** [comment]
Reopen this for other ppl.. Will be closed, if version 1.1.1 gets released.
