### ISSUE TITLE
i Have Big Problem in RankSystem

### ISSUE THREAD

**Issue by xCHeF** [Newcomer1989/TSN-Ranksystem#118]
Hi . 

I have Big big problem , like if i remove from my self level 1 don't level back :| 

if u don't understand like the bot not run automatic pls pls any one have help say ^^

**Comment by Newcomer1989** [comment]
Sorry, with this description I can't help you..
Please write first what you exactly did. Then describe the problem you have. Perhaps screenshots or logs could help to describe your problem...

**Comment by Newcomer1989** [comment]
Close this issue due no response.
