### ISSUE TITLE
Error 110: Connection timed out

### ISSUE THREAD

**Issue by ArchieGB** [Newcomer1989/TSN-Ranksystem#119]
Hi there,

I've entered all of the information needed for my TeamSpeak 3 server and made sure it is all correct but every time I go to start the bot I get an error and it doesn't connect to the teamspeak, i've tried the IP and also the domain but neither work...

`2016-10-02 18:48:33.453576   ERROR     Error 110: Connection timed out
2016-10-02 18:48:23.411555   INFO      Connect to TS3 Server (Address: "ts.gamingbusterz.co.uk" Voice-Port: "9987" Query-Port: "10011").
2016-10-02 18:48:23.411490   INFO        Ranksystem Version: 1.1.0
2016-10-02 18:48:23.411087   INFO        No newer version detected; Database check finished.
2016-10-02 18:48:23.411005   INFO      Check Ranksystem database for updates.
2016-10-02 18:48:23.405652   INFO      Initialize Bot...`

Hope you can help
Archie

**Comment by Shad86** [comment]
Be sure that you use the right queryport and if its 10011 that the port is reachable.

Also make sure that the public ip is white listed in the query_ip_whitelist.txt (its in the ts3-server folder)

regards

Shad86

**Comment by Newcomer1989** [comment]
We already had written on the ts3 server together.

Please make sure the connections details are correct. Also you can try to connect from your local device to the teamspeak server query to be sure for that.
Then the next step should be to make sure, that the Ranksystem doesn't get banned. https://github.com/Newcomer1989/TSN-Ranksystem/issues/96#issuecomment-244788612

If you are able to connect to the ts3 server query from your local device but not from the webhost, where the Ranksystem is running, then check your firewall / network between the webhost and the ts3 host.
