### ISSUE TITLE
Top User of Week/Month/All Issue

### ISSUE THREAD

**Issue by Corveeehh** [Newcomer1989/TSN-Ranksystem#12]
Hello!

First of all: Thank you for this awesome tool! I will donate some $$$ soon ;)

My Problem: In Top User of Week/Month/All time there are only my Musicbots listed, because they are playing music for 24/7. Can i delimit it somehow that Users with Servergroup ID 11 wont be in this ranking?

Thanks for your response =)

**Comment by Sqveeze** [comment]
First: http://prntscr.com/au6bnc

Second step: http://prntscr.com/au6bve

**Comment by Newcomer1989** [comment]
Yes, this is the right way. But I also got a bug report, that the servergroup exception doesn't matter for the top sites.
For the moment you can use the client exceptions, this works also on top sites.

I have to check, its rly a bug. But if the answer is yes, there will be a fix for the servergroup exception  next release.

**Comment by Corveeehh** [comment]
Yes i made the Server Group exceptions. Well then i will fix it with Client exceptions. Thanks for response!

**Comment by Newcomer1989** [comment]
should be emended with release 1.01
(enable the update check inside the webinterface to get notified when it gets published)
