### ISSUE TITLE
PHP Fatal error:  Call to a member function query() on null in */webinterface/index.php on line 59

### ISSUE THREAD

**Issue by Revanou** [Newcomer1989/TSN-Ranksystem#121]
Hi all,

Sorry for my english, this is not my native langage. I am working on a debian/apache/php 5.6 machine.

Here a sample the php code from the index.php (line 59 and 60) which is located in the /webinterface/ directory :
`if(($last_access = $mysqlcon->query("SELECT last_access,count_access FROM $dbname.config")) === false) {
	$sqlmsg .= print_r($mysqlcon->errorInfo());`

I use the install.php and follow the step, but, nothing happens to the next step. I can't acces the step 2 of the installation process.
When I check my apache logs, I get this error message : 

> [Wed Oct 05 14:26:29.867064 2016] [:error] [pid 522] [client 77.153.208.28:56940] PHP Fatal error:  Call to a member function query() on null in /home/ranksys/www/webinterface/index.php on line 59

When I am trying to access to the /webinterface/ directory from my web browser, I get a HTTP error 500. But when I remove the index.php from this directory, I can acces to the directory.

My <Directory> configuration from my vhost is set with this parameter :

> Options +Indexes +FollowSymLinks +MultiViews
> AllowOverride all
> Require all granted
> Allow from all

Do anyone have any idea of my current problem ? Moreover... because of the fact that I am not a truly expert in this kind of environment, do you need more elements from my current issue in order to be understood ?

Again, sorry for my english.

I would appreciate any support.

Thanks a lot.

**Comment by tooti312** [comment]
Are the files running with the right www user? 
It looks like he either can't access the config.php file or the database was not created. 
The "HTTP error 500" comes from php because he can't finish the script.
If you don't know your www user try "apachectl -S"

**Comment by Revanou** [comment]
You are right ! You let me fulfilled the complete installation.
My issue was because I did not create the database (Mysql wasn't installed in my environment).
So I did a full installation and configuration of Mysql and Phpmyadmin and then it worked.

Thanks for your post ! Your make me realise I was missing something.
