### ISSUE TITLE
ERROR     update_groups 6:

### ISSUE THREAD

**Issue by tooti312** [Newcomer1989/TSN-Ranksystem#125]
Still getting the "ERROR     update_groups 6" Error

> 2016-10-08 18:00:00.786292   ERROR     update_groups 6:('3', 'Server Admin', '300', ''),('555', 'Stammkunde', '743102498', '1475272611'),('554', 'Kunde', '646478300', '1475260585'),('486', 'Neukunde', '3160438482', '1474919431'),('492', 'Schnauze!', '3159600048', '1468269407'),('485', '#!/bin/bash', '2815481283', '1468269407'),('490', 'René', '2038318668', '1474922974')1
> 2016-10-08 18:00:00.785445 6IconID is 0 for (servergroup) 'Admin' (493)
> 2016-10-08 18:00:00.785118 6IconID is 0 for (servergroup) '⏩-----Admin Gruppen-----⏪' (489)
> 2016-10-08 18:00:00.784715 6IconID is 0 for (servergroup) '⏩-----Sonstige Gruppen-----⏪' (491)
> 2016-10-08 18:00:00.784384 6IconID is 0 for (servergroup) 'in progress #1' (556)
> 2016-10-08 18:00:00.784050 6IconID is 0 for (servergroup) 'in progress #2' (557)
> 2016-10-08 18:00:00.783764 6IconID is 0 for (servergroup) '⏩-----Normale Gruppen-----⏪' (488)
> 2016-10-08 18:00:00.783476 6IconID is 0 for (servergroup) 'Guest' (5)
> 2016-10-08 18:00:00.783188 6IconID is 0 for (servergroup) 'Normal' (4)
> 2016-10-08 18:00:00.782882 6IconID is 0 for (servergroup) 'Admin Server Query' (2)
> 2016-10-08 18:00:00.782560 6IconID is 0 for (servergroup) 'Guest Server Query' (1)
> 2016-10-08 18:00:00.782125   INFO      Download new ServerGroupIcon for group 'Dafuq' with ID: 490
> 2016-10-08 18:00:00.781722   INFO      Download new ServerGroupIcon for group '#!/bin/bash' with ID: 485
> 2016-10-08 18:00:00.781236   INFO      Download new ServerGroupIcon for group 'Schnauze!' with ID: 492
> 2016-10-08 18:00:00.780668   INFO      Download new ServerGroupIcon for group 'Neukunde' with ID: 486
> 2016-10-08 18:00:00.780249   INFO      Download new ServerGroupIcon for group 'Kunde' with ID: 554
> 2016-10-08 18:00:00.779748   INFO      Download new ServerGroupIcon for group 'Stammkunde' with ID: 555
> 2016-10-08 18:00:00.778064   INFO      Download new ServerIcon
>

**Comment by Newcomer1989** [comment]
Try to clean your table groups inside the Ranksystem database.
`DELETE FROM groups;`

**Comment by tooti312** [comment]
Database is already empty. Its not creating records.

In version 1.1.0 the ranksystem could not create records because the iconid was null.
I have not looked into version 1.1.1 yet.

**Comment by Newcomer1989** [comment]
The database is empty or only the table 'groups'?

From which version of the Ranksystem is the output above?

**Comment by tooti312** [comment]
Ups, yes, table groups is only empty.
The output above is drom version 1.1.1.

**Comment by Newcomer1989** [comment]
That can't be.. Your output must be from version 1.1.0.

Please update correct to version 1.1.1 and your problem should be solved.

On 1.1.0 the "update_groups 6" was the function to insert new servergroups (thats your log above). In version 1.1.1 the "update_groups 6" is the function to download of the group icon.

So if you have installed the version 1.1.1 please be sure all files are updated correctly otherwise update first to 1.1.1!

**Comment by tooti312** [comment]
You are right. i have downloaded the latest zip releases tab. It was still 1.1.0. Everything is working right now.
