### ISSUE TITLE
DDoS protection blocks RankSystem - Result: "RankSystem" dropped (connection lost)

### ISSUE THREAD

**Issue by bykidi** [Newcomer1989/TSN-Ranksystem#126]
2016-10-09 13:45:24.015862   INFO      Initialize Bot...
2016-10-09 13:45:24.020652   INFO      Check Ranksystem database for updates.
2016-10-09 13:45:24.020728   INFO        No newer version detected; Database check finished.
2016-10-09 13:45:24.020820   INFO        Ranksystem Version: 1.1.1
2016-10-09 13:45:24.020893   INFO      Connect to TS3 Server (Address: "superhiddenserverip" Voice-Port: "mydefaultport" Query-Port: "mysupernotdefaultport").
2016-10-09 13:45:24.045471   INFO        Connection to TS3 Server established.
2016-10-09 13:45:24.051447   INFO        Joined to specified Channel.
2016-10-09 13:45:24.051555   INFO      Bot starts now his work!
2016-10-09 13:46:09.105724   ERROR     calc_user -2:1
2016-10-09 13:46:09.105896   ERROR     calc_user -1:1
2016-10-09 13:46:09.105975   ERROR     calc_user 0:1

<13:48:48> "RankSystem" dropped (connection lost)

**Comment by Newcomer1989** [comment]
Please check the following issue.. Perhaps it helps you https://github.com/Newcomer1989/TSN-Ranksystem/issues/96#issuecomment-244788612

**Comment by bykidi** [comment]
Doesn't matter what slowmode i use.
BTW this happend after my ISP blocked all ports except of common ones that i use to protect me from DDoS.
Every other stuff like JTS3ServerMod (connected with 127.0.0.1:9987) works fine, but TS-N Ranksystem won't connect via domain or localhost or 127.0.0.1, only with real server IP. This might be the problem.

**Comment by Newcomer1989** [comment]
This seems to be a problem from your firewall configuration. Perhaps increase the level of allowed tcp packets on your firewall. In combination with the slowmode this should help! You only have to find out where the point is where the Ranksystem works without connection problems.

That the Ranksystem isn't able to connect via localhost could be a wrong configuration of your hosts file.
127.0.0.1 must be also a problem by your local network routing. On my and also on other systems it is working with that without any problems.

**Comment by bykidi** [comment]
127.0.0.1 localhost
127.0.1.1 ubuntu
# The following lines are desirable for IPv6 capable hosts
::1     localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters

this is my /etc/hosts

superroot@superserver:~# ping localhost
PING localhost (127.0.0.1) 56(84) bytes of data.
64 bytes from localhost (127.0.0.1): icmp_seq=1 ttl=64 time=0.023 ms
64 bytes from localhost (127.0.0.1): icmp_seq=2 ttl=64 time=0.019 ms
64 bytes from localhost (127.0.0.1): icmp_seq=3 ttl=64 time=0.020 ms
64 bytes from localhost (127.0.0.1): icmp_seq=4 ttl=64 time=0.024 ms
64 bytes from localhost (127.0.0.1): icmp_seq=5 ttl=64 time=0.018 ms
64 bytes from localhost (127.0.0.1): icmp_seq=6 ttl=64 time=0.025 ms
^C
--- localhost ping statistics ---
6 packets transmitted, 6 received, 0% packet loss, time 4996ms
rtt min/avg/max/mdev = 0.018/0.021/0.025/0.005 ms

**Comment by Newcomer1989** [comment]
Sorry it is not possible for me to search for errors on each other hostsystem! You have to find the error yoursef. I only give you a hint where you can start searching.

In your case it look obviously a problem of your hostsystem. After changing your firewall options you get a connection lost. 

The connection with localhost works on other machines without any problem, so at first I would say it can't be a problem with the Ranksystem.

Only one more idea what you can try. The Ranksystem also supports IPv6. Try to connect with your IPv6 address (::1)

**Comment by bykidi** [comment]
```
superroot@superserver:/var/www/html/ranks# telnet 127.0.0.1 10011
Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused
```

**Comment by bykidi** [comment]
I think i figured out why is that happend - query_ip= was set up to listen real IP instead of localhost

**Comment by bykidi** [comment]
Nope. This is weird, but problem was not related to what IP query was bounded.

**Comment by bykidi** [comment]
Another error when trying to connect via ipv6
`2016-10-19 23:53:47.762301   ERROR     Ошибка 0: php_network_getaddresses: getaddrinfo failed: Name or service not known
2016-10-19 23:53:47.726224   INFO      Connect to TS3 Server (Address: "::1" Voice-Port: "9987" Query-Port: "10011").`

**Comment by Newcomer1989** [comment]
Are you sure the ts3 server is listening to IPv6? 
You have to change your `ts3server.ini` in the teamspeak directory. On older ts3 servers the `, ::` will need to add manual!
`query_ip=0.0.0.0, ::`

**Comment by bykidi** [comment]
2016-10-20 11:12:36.346143|INFO    |Query         |   |listening on 0.0.0.0:10011, :::10011

**Comment by Newcomer1989** [comment]
Sorry, I do not administrate your system. Are you able to connect with other programms to your ts3 query with IPv6?

**Comment by bykidi** [comment]
Can't test it because i don't have IPv6 support by my ISP. But sooner i will try to test it with some other software. Until then i close this issue.

**Comment by bykidi** [comment]
Issue was fixed by just rebooting the entire server and adding IPv6 "::" addresses to ts3server.ini
