### ISSUE TITLE
[Idee] Teamspeak Viewer

### ISSUE THREAD

**Issue by PaDo90** [Newcomer1989/TSN-Ranksystem#127]
Hallo, man könnte doch noch einen Live-Viewer mit in die Seite einbauen,
dass man sieht wer sich gerade auf dem Server verbindet.

**Comment by Newcomer1989** [comment]
Ich warte dazu mal ab, wie viel thumbs up deinem Vorschlag gegeben werden.

Grundlegend fehlt mir da aber der Zusammenhang mit dem Ranksystem..

**Comment by Provokan** [comment]
Ich finde die Idee nicht produktiv, weil es soll ein Ranking sein und man sieht ja in der tabellarischen Auflistung wer online ist und wer nicht. 

Man sollte hier eine klare Linie verfolgen und nicht  mehr Richtung Teamspeak Verwaltungspanel gehen.

**Comment by Newcomer1989** [comment]
Scheint wohl mehrheitlich abgelehnt worden zu sein.. Ich schließe den Issue daher mal.
