### ISSUE TITLE
Can't enter ServerGroup Exceptions Numbers

### ISSUE THREAD

**Issue by GambarojaLP** [Newcomer1989/TSN-Ranksystem#128]
Hello There,
I'm having trouble with the Latest Version of the Ranksystem.

Somehow it won't let me enter the Numbers because i only shall enter Digits Seperated with an Comma.

Numbers: "82, 6, 91, 92"

Any Ideas?

**Comment by Newcomer1989** [comment]
That check was already implement with version 1.1.0.

This checks the syntax on entering the servergroup exceptions inside the webinterface.

Try to delete your whitespaces and then it should work.

**Comment by GambarojaLP** [comment]
#Closed / I did it wrong by myself
