### ISSUE TITLE
% Angabe

### ISSUE THREAD

**Issue by Shad86** [Newcomer1989/TSN-Ranksystem#13]
Hallo,

ich vermute du sprichst / schreibst auch deutsch? :)

Bei mir habe ich einen Fehler bei "Meine Statistiken" in der Errungenschafts anzeige. (Auch andere User schilderten dies.)

Bei "Zeit:" wird nur "% errreicht für Legendary" angezeigt. (im übrigen sehe ich auch gerade das da sogar noch ein Rechtschreibfehler drinn its -> "errreicht" :)

http://puu.sh/op9pc/50b6b67c59.png

Bei "Verbinungen:" wird es richtig angezeigt

Sehe ich es im übrigen richtig das ich diese beiden Errungenschaften derzeit nur in der my_stats.php bearbeiten kann? Also um die Zeit und/oder verbindungsanzahl zu erhöhen.

Wird das Webinterface (webinterface.php) eigentlich auch noch an das bootstrap design angepasst, ich persönlich fände es eben schön wenn alles einheitlich gleich wirkt.

Ansonsten Top update, gefällt mir echt gut!

**Comment by Shad86** [comment]
The Downvote is for waht?

**Comment by Newcomer1989** [comment]
> (im übrigen sehe ich auch gerade das da sogar noch ein Rechtschreibfehler drinn its -> "errreicht" :)
Thx fixed

> Bei "Zeit:" wird nur "% errreicht für Legendary" angezeigt. 
I will look for this and hopfully fix this with the next version

> Sehe ich es im übrigen richtig das ich diese beiden Errungenschaften derzeit nur in der my_stats.php bearbeiten kann? Also um die Zeit und/oder verbindungsanzahl zu erhöhen.
Yes, for the moment this are no variables. I think the option to define the values will come together with battle system.

> Wird das Webinterface (webinterface.php) eigentlich auch noch an das bootstrap design angepasst, ich persönlich fände es eben schön wenn alles einheitlich gleich wirkt.
Yes, its already on my todo list, like so much more^^

**Comment by Newcomer1989** [comment]
> Bei "Zeit:" wird nur "% errreicht für Legendary" angezeigt. 

should be emended with release 1.01
(enable the update check inside the webinterface to get notified when it gets published)
