### ISSUE TITLE
Error while downloading servergroup icon

### ISSUE THREAD

**Issue by snipxpro3** [Newcomer1989/TSN-Ranksystem#131]
hello thir i have Another problem 

Take a quick look at the following 

http://prntscr.com/cs6q7e

Please i hope a solution as soon as possible 

Thank's

**Comment by Newcomer1989** [comment]
The problem is the same of your last issue. Your query connection between your ts3 server and the webserver is bad. One possibilty is, you the Ranksystem got banned.

Please read the issue #96 and care about what I wrote there.

**Comment by Newcomer1989** [comment]
Closed due no response
