### ISSUE TITLE
Windows - starting Bot - No Instances available

### ISSUE THREAD

**Issue by KamoiChikubi** [Newcomer1989/TSN-Ranksystem#132]
Hello. Whenever I try to start the bot from CMD, I get this error

> D:\Website\ranksystem>"C:\Program Files\PHP\v7.0\php.exe" -f worker.php start
> Starting the Ranksystem Bot.No Instance(s) Available.
>  [Failed]

There is no log file or anything else to go with. I have tried starting from web browser as well but still no luck.

I'm using Windows 10 64bit, with PHP version 7 + MySQL. PDO and COM are both enabled and EXEC command is executable.

**Comment by Newcomer1989** [comment]
Which version of the Ranksystem are you using?

The error "No Instance(s) Available." comes from the COM module. Please check the user have the permission to run the wmic command.

**Comment by KamoiChikubi** [comment]
Hello. I ran the script from C:\ and for some reason it worked.

>C:\Program Files\PHP\v7.0>php -f D:\Website\ranksystem\worker.php check
Starting the Ranksystem Bot. [OK]

I think it had something to do with the spaces in Program Files. But thank you for the reply.

I now have another problem. I can see the bot logged into TS and working fine (i.e. assigning ranks to people), but on the /stats page it says that I'm not connected to Teamspeak server, which prevents me from accessing "My statistics" page. Here's a screenshot of what's happening:

http://puu.sh/rIN2M/5aee2dae17.png
http://puu.sh/rINia/6da9afeb82.png
http://puu.sh/rINje/7474ece727.png <-- This is what happens when I click on the My Statistics page.

**Comment by Newcomer1989** [comment]
> I now have another problem. I can see the bot logged into TS and working fine (i.e. assigning ranks to people), but on the /stats page it says that I'm not connected to Teamspeak server, which prevents me from accessing "My statistics" page. Here's a screenshot of what's happening:
> 
> http://puu.sh/rIN2M/5aee2dae17.png
> http://puu.sh/rINia/6da9afeb82.png
> http://puu.sh/rINje/7474ece727.png <-- This is what happens when I click on the My Statistics page.
> 
> Also in the /Webinterface, when I try to start/stop/restart the bot, it says that it has successfully done that but it actually doesn't happen.

You must open the homepage with the same ip address, you are connected to the TeamSpeak server! Also it must be the same ip protocoll (IPv4 / IPv6) or it isn't able to match you.

**Comment by KamoiChikubi** [comment]
Oh. Alright that has solved all my issues. Thank you so much! I really like the bot as well, keep up the good work.

**Comment by Newcomer1989** [comment]
Dieser Thread wird nicht mehr benötigt, da alle relevanten Punkte für Windows nun hier zusammen getragen wurden:

https://github.com/Newcomer1989/TSN-Ranksystem/issues/369
