### ISSUE TITLE
Problem: Meine Statistiken [GER]

### ISSUE THREAD

**Issue by SpliinTaX** [Newcomer1989/TSN-Ranksystem#133]
PHP Version: 5.5.38-1~dotdeb+7.1
Betriebssystem: Linux, Debian 7
Ranksystemversion: 1.1.1

Howdy,

vor kurzem habe ich mein Ranksystem auf Version 1.1.1 geupdatet, nun habe ich das Problem dass man bei der Stats Seite nicht mehr auf "Meine Statistiken" klicken kann, sprich er sagt das man nicht mit dem Teamspeak 3 verbunden ist, obwohl man auf dem Teamspeak eigentlich verbuden ist. 

Würde mich über eine Rückmeldung freuen!

Grüße

**Comment by Newcomer1989** [comment]
Die Antwort auf Englisch, da ich das Problem eben in issue #132 auch schon beantwortet hast.

You must open the homepage with the same ip address, you are connected to the TeamSpeak server! Also it must be the same ip protocoll (IPv4 / IPv6) or it isn't able to match you.

**Comment by SpliinTaX** [comment]
Howdy @Newcomer1989 ,

danke für die schnelle Rückmeldung, ob ich jetzt die URL mit der IP aufrufe oder der Domain funktioniert beides nicht.. Auf der Version 1.1.0 funktionierte das ganze ohne Probleme!

Würde mich über eine Rückmeldung freuen!

Grüße

**Comment by mightyBroccoli** [comment]
@SpliinTaX Gemeint ist, dass du mit der selben IP Adresse mit dem Teamspeak verbunden sein musst mit der du auch die Webseite öffnest. 
Beispiel: Der Serverläuft wird vom aktuellen Client verbunden da dieser nur IPv4 kann stellt er die verbunding her 123.456.789.1 ( Beispiel Adresse ) nun verbindest du dich mit deinem Browser zu der Webseite die womöglich IPv6 unterstützt da dein Browser das auch kann stellt er die Verbindung her mit einer IPv6 Adresse. Da IPv4 und Ipv6 nicht gleich sind erkennt der Bot nicht das du verbunden bist da die Ipv6 Adresse nach der der Bot schaut auf dem Server nicht verbunden ist.

**Comment by Newcomer1989** [comment]
Genau wie mightyBroccoli beschrieben hat.

Das sollte das Problem lösen bzw. zumindest deren Ursache erklären. 
Falls es dennoch zu Problemen kommt den Issue einfach wieder öffnen.

**Comment by Newcomer1989** [comment]
Wurde eben per Remote-Session behoben.

Problem war, dass die Webserver-Files nicht sauber upgedated wurden und teilweise noch auf einer alten Version hingen.
Update der Dateien wurde wiederholt, nun passt alles.
