### ISSUE TITLE
Problem: Server-News setzen nicht möglich

### ISSUE THREAD

**Issue by SpliinTaX** [Newcomer1989/TSN-Ranksystem#135]
PHP Version: 5.5.38-1~dotdeb+7.1
Betriebssystem: Linux, Debian 7
Ranksystemversion: 1.1.1

Howdy,

ich kann über das Webinterface keine Server-News Nachricht setzen, auf meinen Webspace konnte ich auch keine .php Datei dafür finden.

**Comment by Newcomer1989** [comment]
Die Server-News können nur noch über das Webinterface gesetzt werden. Die dazugehörige Datei auf dem Server entfällt demnach.

Was heißt Server-News kann nicht gesetzt werden? Meine hellseherischen Fähigkeiten haben gerade Urlaub...

**Comment by SpliinTaX** [comment]
Howdy @Newcomer1989 ,

wenn ich etwas über das Webinterface setze und speichert, die Seite dann wechsele ist mein Inhalt wieder gelöscht. >.<

**Comment by Newcomer1989** [comment]
Wird die Server-News denn trotzdem auf der /stats/ Seite (öffnen über Dropdown beim Nicknamen) angezeigt?

**Comment by SpliinTaX** [comment]
Nein

**Comment by Newcomer1989** [comment]
Ist ein Fehler in der Version 1.1.1.
Wird mit Version 1.1.2 bereinigt.

**Comment by Newcomer1989** [comment]
release 1.1.2 is out
