### ISSUE TITLE
starten des Bot's auf Windows

### ISSUE THREAD

**Issue by Assassinee** [Newcomer1989/TSN-Ranksystem#138]
Ich habe ein großes Problem mit dem Bot. Ich bekomme es einfach nicht hin Ihn auf Windows zu starten. wenn ich die "Worker.php" Seite öffne steht da, dass ich noch den Befehl "check" eingeben muss, aber ich weiß nicht wie. Ich hoffe das mir eine helfen kann und vielleicht auch eine Anleitung geben kann ich das hinbekomme.

**Comment by Newcomer1989** [comment]
Eine Anleitung existiert hier: http://ts-n.net/ranksystem.php

Bei welchem Schritt hängt es denn?

**Comment by Assassinee** [comment]
Erst ein mal danke für die schnelle Antwort. Ich habe den Bot installiert und er muss jetzt nur noch gestartet werden. (Bei der Installation ist, nachdem ich die Zugangsdaten für das webinterface erstellt habe nichts mehr gekommen. Vielleicht hängt das ja auch damit zusammen.) bei einer älteren Version ist es so abgelaufen das die worker.php mit einem Firefox Addon alle 5 min. Aufgerufen wurde. Jetzt funktioniert das ja wohl nicht mehr oder? Ich habe auch schon probiert eine "Aufgabe" zu erstellen und auch per Cmd versucht das zu starten aber ich habe immer Fehlermeldungen bekommen(nicht vom bot, sondern von Windows . Die Fehlermeldung könnte nichts mit dem Check anfangen was in der Anleitung steht.)

**Comment by Assassinee** [comment]
Ich habe mittlerweile alle benötigten Anforderungen eingestellt. Nun habe ich jedoch immer noch das Problem, dass der Bot nicht starten will. Ich habe jetzt auch eine Aufgabe in Windows eingestellt die ausgelöst wird sobald sich der Benutzer anmeldet. So sieht der Befehl aus.
(Auf die nötigsten werte begrenzt.)

![aktion](https://cloud.githubusercontent.com/assets/22969200/19628559/beda2c44-9960-11e6-8f28-222e46468f54.png)

Ist das denn jetzt richtig eingestellt? oder ist da noch ein Fehler drin?

**Comment by Newcomer1989** [comment]
Hast du denn mal versucht manuell über die Konsole den Bot zu starten?

Welche Meldungen erhälst du? Was steht in der log?

**Comment by Assassinee** [comment]
> Hast du denn mal versucht manuell über die Konsole den Bot zu starten?
Ja, dann öffnet sich kurz eine andere cmd Konsole und in dieser steht:"Starting the Ranksystem Bot." oder "Starting the Ranksystem Bot.Keine Instanzen verfügbar." aber nichts passiert. 

> Was steht in der log?
in dem Ordner Logs ist keine Datei vorhanden


Wenn ich den Befehl "get_loaded_extensions();" in einer php datei aufrufe bekomme ich folgende Antwort :[24] => PDO und [37] => com_dotnet (nur ein kleiner Auszug aus dem ganzen)

**Comment by Newcomer1989** [comment]
> "Starting the Ranksystem Bot.Keine Instanzen verfügbar."

Dann schau mal bitte hier -> https://github.com/Newcomer1989/TSN-Ranksystem/issues/132#issuecomment-253839792

**Comment by Assassinee** [comment]
Also ich habe jetzt den Bot mit der CMD Konsole gestartet mit dem Befehl "*\php.exe -f *\bot.php" und er ist dann auf den Ts gekommen und nach ca. 5 sec wieder runter gegangen. Ich habe dann mal einen Channel eingestellt wo der Bot rein soll und das macht er auch.

Das hier ist der output aus der Log datei:

2016-11-02 22:19:05.235184   INFO      Initialize Bot...
2016-11-02 22:19:05.244625   INFO      Check Ranksystem database for updates.
2016-11-02 22:19:05.245025   INFO        No newer version detected; Database check finished.
2016-11-02 22:19:05.246476   INFO        Ranksystem Version: 1.1.1
2016-11-02 22:19:05.246877   INFO      Connect to TS3 Server (Address: "127.0.0.1" Voice-Port: "9987" Query-Port: "10011").
2016-11-02 22:19:05.299233   INFO        Connection to TS3 Server established.
2016-11-02 22:19:05.301691   INFO        Joined to specified Channel.
2016-11-02 22:19:05.302234   INFO      Bot starts now his work!
2016-11-02 22:19:10.302673   INFO      Received signal to stop. Shutting down!

**Comment by Newcomer1989** [comment]
I think there are no write permissions for the logs folder.

Have a look, the "pid" file will be created (inside your logs folder). That will be created with starting the bot via the worker.php.
If the "pid" file is missed, the bot will stops 
2016-11-02 22:19:10.302673 INFO Received signal to stop. Shutting down!

**Comment by Assassinee** [comment]
> I think there are no write permissions for the logs folder.

Ich habe es gerade noch einmal nachgeguckt und überprüft. "jeder" hat in diesem Ordner Schreibzugriff und der Ordner ist auch nicht schreibgeschützt.

Es macht keinen Unterschied ob ich die Konsole "normal" über das Administrator Konto oder mit Rechtsklick als Administrator starten starte. Wenn ich aber mit der CMD Konsole eine Datei in dem logs Ordner erstellen möchte macht er das ohne Probleme.

Die "pid" Datei wird aber auch nicht erstellt, wenn ich den Bot starte.

**Comment by Newcomer1989** [comment]
Und wenn du die logs/pid zunächst manuell erstellst (Inhalt unrelevant) und dann wie oben beschrieben die jobs/bot.php manuell in der Konsole ausführst?

**Comment by Assassinee** [comment]
Jetzt läuft der Bot und er geht nicht direkt vom Ts. aber in dem Log kommt die ganze zeit "2016-11-03 18:28:49.499643   ERROR     calc_serverstats 8:1"

und in der Konsole steht:

![cmd](https://cloud.githubusercontent.com/assets/22969200/19977434/d1762b46-a1f3-11e6-8ae7-933515ea4ea3.png)

**Comment by Newcomer1989** [comment]
Magst du vielleicht mal bei mir auf den TS vorbei schauen. 
TS: ts-n.net

Wir könnten uns das dann einfach mal zusammen per Fernwartung anschauen.

**Comment by Newcomer1989** [comment]
Aufgrund fehlender Reaktion zunächst geschlossen.

**Comment by fabm3n** [comment]
Im endefekt mein Problem 
https://github.com/Newcomer1989/TSN-Ranksystem/issues/313
