### ISSUE TITLE
Fatal error: Call to a member function query() on null in /var/customers/webs/USERNAME/ranksystem/ranksystem/other/session.php on line 24 

### ISSUE THREAD

**Issue by Abcimwc** [Newcomer1989/TSN-Ranksystem#140]
I do not know how to fix this...

I am using:
- Nitrado Webspace
- Filezilla

My problem is i can't open the install.php cuz this is showing up befor anything.
I already tried to delete it, just to see what happens and the funny thing is i can see and open the install.php then BUT the same error shows up again just with another file. -.-'

**Comment by Newcomer1989** [comment]
Please check the requirements on our official Homepage:
http://ts-n.net/ranksystem.php

I think your PDO driver is missed or something is wrong with your PHP.
