### ISSUE TITLE
Problem with starting the bot - BOT NOT STARTING - Timezone?

### ISSUE THREAD

**Issue by pecagg** [Newcomer1989/TSN-Ranksystem#141]
Hi there! First of all, thank you for this great project you made! 

I am having some difficulties with starting the bot. I have installed everything according to the tutorial you have written on your website. But, the bot just did not want to start (neither from the web page, nor from the ssh access)

I am running **Ubuntu 15.04** with **apache2**, **PHP 5.6.27** and **mariaDB**.

When i want to start the worker.php process i just get:
`root@teamspeakubuntu:/var/www/html/ranks# php worker.php start
Starting the Ranksystem Bot. [OK]`

But then, I get nothing! When I want to see the status of **worker.php**, i get the information that the process is not running at all:
`root@teamspeakubuntu:/var/www/html/ranks# php worker.php status
The Ranksystem does not seem to run.`

Log file is completely empty, so I tried to troubleshoot by myself after I read a few forum posts.
When i try to run **bot.php** with enabled error reporting, i get this error message:

`root@teamspeakubuntu:/var/www/html/ranks/jobs# php bot.php`

`Fatal error: Uncaught exception 'Exception' with message 'DateTimeZone::__construct(): Unknown or bad timezone ()' in /var/www/html/ranks/jobs/bot.php:24`
`Stack trace:`
`#0 /var/www/html/ranks/jobs/bot.php(24): DateTimeZone->__construct('')`
`#1 /var/www/html/ranks/jobs/bot.php(55): enter_logfile(NULL, NULL, 5, 'Initialize Bot....')`
`#2 {main}`
`thrown in /var/www/html/ranks/jobs/bot.php on line 24`

In my **php.ini** files (both apache and cli), I have my date.timezone set to Europe/Paris
`date.timezone = Europe/Paris`

And this is the screenshot of phpinfo() regarding the time zone:
[screenshot](http://puu.sh/rRKse/9ca5690c6f.png)

I have also changed the timezone settings to Europe/Paris in the webpanel and checked it in mysql base, so there is no issue regarding that.

Am I doing something wrong? I'm not that much experienced with ssh and unix systems, I'm still learning. Please, help! 

Thank you very much!

**Comment by Newcomer1989** [comment]
What timezone is saved inside the database?
`select timezone from config;`

Perhaps also try to add an short echo inside the bot.php after the following line:
`require_once(substr(__DIR__,0,-4).'other/config.php');`  (near line 48)
add:
`echo "timezone: ".$timezone;`

You are sure, you have only one PHP installed? So you are sure the PHP 5.6.27 is really used for the Ranksystem? To clear this, add after the echo above the following to the bot.php
`echo "PHP version: ".phpversion();`

**Comment by pecagg** [comment]
Thank you for your answer.
Hmm, this is strange.

I have added the following scripts, and this is the result:

`root@teamspeakubuntu:/var/www/html/ranks/jobs# php bot.php`
**PHP version: 5.6.27 timezone:**
`Fatal error: Uncaught exception 'Exception' with message 'DateTimeZone::__construct(): Unknown or bad timezone ()' in /var/www/html/ranks/jobs/bot.php:24`
`Stack trace:`
`#0 /var/www/html/ranks/jobs/bot.php(24): DateTimeZone->__construct('')`
`#1 /var/www/html/ranks/jobs/bot.php(57): enter_logfile(NULL, NULL, 5, 'Initialize Bot....')`
`#2 {main}`
`  thrown in /var/www/html/ranks/jobs/bot.php on line 24`

(timezone is empty.)

I have also checked the location of php.ini file (with php --ini), and checked if i have date.timezone set in that ini file.

Is there any workaround?

**Comment by pecagg** [comment]
Ok, I have just realized that I actually apparently have 2 PHP installed.

phpinfo() is returning PHP Version 5.6.4-4ubuntu6
while php -v is returning PHP 5.6.27 (cli) (built: Oct 21 2016 18:26:29)

How do I fix that problem? sorry if that is the stupid question

**Comment by Newcomer1989** [comment]
I think the two PHP versions are not the problem.

The problem might be the connection to the database. Can you login into the webinterface? Are your database connections details inside the 'other/dbconfig.php' correct?

It seems, the bot get no config out of your database, thats why the $timezone is empty.

**Comment by pecagg** [comment]
I can login into the webinterface without any issues, and _other/dbconfig.php_ file is correctly set up.

**Comment by pecagg** [comment]
Is there any way I can fix this issue? I'm stuck, tried a lot of different things but nothing worked. Losing hope :(

**Comment by Newcomer1989** [comment]
You get any other information out of the config table? Try to echo the `$webuser`, same like already described for the `$timezone` above.

You tried to reinstall the Ranksystem?

For the database connection PDO is required.. Check this is available for the bot.

**Comment by Newcomer1989** [comment]
Closed due no response.
