### ISSUE TITLE
Question: Can I disable the counting for 2Bot's?

### ISSUE THREAD

**Issue by Bl4CkGuuN** [Newcomer1989/TSN-Ranksystem#143]
Hey,

I have two Musicbots and I dont want, that they are in the Top 10.

Can I disable the two bots?

http://rank.quantumroyal.org

Greetz Bl4CkGuuN

**Comment by JohnnyRme** [comment]
You can exclude the identity of a single teamspeak user or exclude a whole server group.

The option is inside the administration panel.

**Comment by Bl4CkGuuN** [comment]
Thanks alot!
