### ISSUE TITLE
Question: Can't see Servergroup Icons

### ISSUE THREAD

**Issue by Bl4CkGuuN** [Newcomer1989/TSN-Ranksystem#144]
Hey,
the Icons are downloaded from the Bot, but I don't see them on the Page.

https://rank.quantumroyal.org/stats/list_rankup.php

Greetz Bl4CkGuuN

**Comment by Shad86** [comment]
You are sure the Folder is readable from the (let me call it) "webspace user" or in most case from the "www-data" user?

**Comment by Bl4CkGuuN** [comment]
I think so

**Comment by Shad86** [comment]
okay and the chmod on the folder icons is also set to 0777?

**Comment by Bl4CkGuuN** [comment]
yes

**Comment by Shad86** [comment]
Well that i can see is.
https://rank.quantumroyal.org/icons/89.png
That the icon isnt reachable.

On my server i can usually reach the icon

**Comment by Bl4CkGuuN** [comment]
hm :/

**Comment by Bl4CkGuuN** [comment]
lel, yeah but why?^^

**Comment by Shad86** [comment]
The next question is are they icons in the folder and does icon 89.png exist?

**Comment by Bl4CkGuuN** [comment]
Yes

**Comment by SimonMattila** [comment]
I am also having this problem! :/ 
All icons exists and all permissions is correct

**Comment by SuperArmySoldiers** [comment]
Hey we fixed the issue.
We fixed this by putting the whole site into a subfolder. 

It could be that Apache/php is using the icons folder for something and is getting confused

for example 
C:\file path\xampp\htdocs\tsrank\worker.php

instead of
C:\file path\xampp\htdocs\worker.php


@Newcomer1989  you might want to add this to a future update?

**Comment by SimonMattila** [comment]
@SuperArmySoldiers How do I do that with Ubuntu? it doesnt work as smooth by just putting it in a subfolder

**Comment by SuperArmySoldiers** [comment]
Sorry not a linux user. No idea what the commands are to move a folder.
The bot works just fine for us in the subfolder

**Comment by SimonMattila** [comment]
I know how to move it, it's not that, its just that when moving it to a subfolder it bring up the "Archive", it doesnt automatically use the index.php for the subfolder to display

**Comment by SuperArmySoldiers** [comment]
To start the bot in windows we have to use the task schedular or a bat file. You must edit the path to the new location. If not it's not going to find the correct files

**Comment by Newcomer1989** [comment]
> @Newcomer1989  you might want to add this to a future update?

How should I update this? It is a local configuration problem of the webserver. I can't handle each webserver and/or each different configuration. You have to configurate it correct and then it will work ;-)

**Comment by SuperArmySoldiers** [comment]
Well its not a config error. Its a conflict of your program and php. If you change the icons folder to something else then there is no issue. 
But as a few people are coming across this you might want to make it work for all. We only worked it out after several hours of testing and googling. :)

**Comment by Newcomer1989** [comment]
For other ppl

On apache you will find on linux the following entry inside your /etc/apache2/mods-available/alias.conf:

`Alias /icons/ "/usr/share/apache2/icons/"`

Comment this line out, restarte the apache and it should show your icons on the website.
