### ISSUE TITLE
Translating the untranslated things

### ISSUE THREAD

**Issue by bykidi** [Newcomer1989/TSN-Ranksystem#145]
There is a lot of stuff that is still untranslated.
![default](https://cloud.githubusercontent.com/assets/1337953/19658410/81198bfe-9a30-11e6-9ace-5454485a8644.PNG)

![2](https://cloud.githubusercontent.com/assets/1337953/19658472/c520364a-9a30-11e6-8c32-5bab27de7c6c.PNG)

**Comment by bykidi** [comment]
Others - Другие
Active Time (In Days) - Активное время (В днях)
InActive Time (In Days) - Неактивное время (В днях)
dd/mm/yyyy - дд/мм/гггг
No, cause excepted - Нет, т.к. в исключениях

**Comment by bykidi** [comment]
BTW - can you create another tree for translation purposes?

**Comment by Newcomer1989** [comment]
I will add this with the next release.. Thx for report.

**Comment by Newcomer1989** [comment]
release 1.1.2 is out
