### ISSUE TITLE
Server group gone for a few people

### ISSUE THREAD

**Issue by KamoiChikubi** [Newcomer1989/TSN-Ranksystem#146]
Hello. I get this error in the logs and one person has his rank reset, but on the ranking list it says its rank is there:

>2016-10-16 21:10:38.496906   ERROR     calc_user 12:It happened a problem with the servergroup of the user 'clq' (unique Client-ID: +zb/rs4TJ5Scs7t9/wk9Dt7WW7g=; Client-database-ID 6280)!
2016-10-15 22:01:47.413279   ERROR     calc_serverstats 8:1
2016-10-15 21:43:27.987695   ERROR     calc_user 12:It happened a problem with the servergroup of the user 'Sama' (unique Client-ID: h7o7K1LxmxOrW92KdGGzo3Q+Sis=; Client-database-ID 5532)!
2016-10-15 21:43:25.943706   ERROR     calc_user 9:It happened a problem with the servergroup of the user 'Sama' (unique Client-ID: h7o7K1LxmxOrW92KdGGzo3Q+Sis=; Client-database-ID 5532)!

http://puu.sh/rXxkn/dec8069787.png <-- ranking

Also the bot won't stop trying to download an icon from the server:

>2016-10-27 19:24:08.982190   INFO      Download new ServerGroupIcon for group 'Wood Divison All Star' with ID: 68
2016-10-27 19:23:45.169563   INFO      Download new ServerGroupIcon for group 'Wood Divison All Star' with ID: 68
2016-10-27 19:23:21.320607   INFO      Download new ServerGroupIcon for group 'Wood Divison All Star' with ID: 68
2016-10-27 19:22:57.520586   INFO      Download new ServerGroupIcon for group 'Wood Divison All Star' with ID: 68

It keeps spamming this.

**Comment by SuperArmySoldiers** [comment]
The fix for the log file spamming might fix your first issue.
Log into the datebase and under 'group' delete all the server icons.
Save
Restart the PHP server/ Apache etc
Then restart the bot. Should work

**Comment by Shad86** [comment]
i also found out that it also works that you just have to delete the group what gets continuously downloaded while the ranksystem is running.

And because the ranksystem is running you can see in the log file if its still updating if not just restart once the renksystem to be sure all works fine.

And as always only work on a database if you'r knowing what you do ;)

regards

Shad86

**Comment by Newcomer1989** [comment]
> 2016-10-16 21:10:38.496906 ERROR calc_user 12:It happened a problem with the servergroup of the user 'clq' (unique Client-ID: +zb/rs4TJ5Scs7t9/wk9Dt7WW7g=; Client-database-ID 6280)!

This should be a problem with your TeamSpeak permissions. Please check the query user has enough power to send a private text message to the user.

> 2016-10-27 19:24:08.982190 INFO Download new ServerGroupIcon for group 'Wood Divison All Star' with ID: 68

Release 1.1.2 is out. This should fix the continuously download of the servergroup icons

**Comment by SuperArmySoldiers** [comment]
If the query user doesn't have the correct permissions the TS server needs to be reinstalled... you can't / should not ever change them :)

**Comment by Newcomer1989** [comment]
> If the query user doesn't have the correct permissions the TS server needs to be reinstalled... you can't / should not ever change them :)

That is only true, if your query user is "serveradmin". But it is also possible to create a separate query user. For sure you can edit the permissions there.
