### ISSUE TITLE
1.1.2 translations - russian part WIP

### ISSUE THREAD

**Issue by bykidi** [Newcomer1989/TSN-Ranksystem#148]
![default](https://cloud.githubusercontent.com/assets/1337953/19840871/2ccb0ae2-9f11-11e6-9f39-781ae72a0480.PNG)

> The entered online time will be considered for the rank up and should take effect immediately.

Введенное время активности учтется при повышении ранга и должно подействовать мгновенно.

**Comment by bykidi** [comment]
![default](https://cloud.githubusercontent.com/assets/1337953/19840894/d57068d6-9f11-11e6-82d5-b61aa6a6bb40.PNG)

**Comment by bykidi** [comment]
![default](https://cloud.githubusercontent.com/assets/1337953/19840904/1e838a80-9f12-11e6-9c0e-9276756a5b3f.PNG)

**Comment by bykidi** [comment]
![default](https://cloud.githubusercontent.com/assets/1337953/19840925/76d0a8da-9f12-11e6-8b86-6dcd442776dc.PNG)

Список пользователей (Режим Администратора)

**Comment by bykidi** [comment]
![default](https://cloud.githubusercontent.com/assets/1337953/19840928/9938bebc-9f12-11e6-9c98-88a825395ee4.PNG)

**Comment by Newcomer1989** [comment]
Will be translated with next version/release.
