### ISSUE TITLE
1.1.2 - user table is empty

### ISSUE THREAD

**Issue by SuperArmySoldiers** [Newcomer1989/TSN-Ranksystem#149]
Update would not work the the current database. 
Lost all the ranks ...

Error
SQL query:

CREATE TABLE `config` (
  `webuser` text CHARACTER SET utf8 COLLATE utf8_unicode_ci,
  `webpass` text CHARACTER SET utf8 COLLATE utf8_unicode_ci,
  `tshost` text CHARACTER SET utf8 COLLATE utf8_unicode_ci,
  `tsquery` int(5) NOT NULL DEFAULT '0',
  `tsvoice` int(5) NOT NULL DEFAULT '0',
  `tsuser` text CHARACTER SET utf8 COLLATE utf8_unicode_ci,
  `tspass` text CHARACTER SET utf8 COLLATE utf8_unicode_ci,
  `language` text CHARACTER SET utf8 COLLATE utf8_unicode_ci,
  `queryname` text CHARACTER SET utf8 COLLATE utf8_unicode_ci,
  `queryname2` text CHARACTER SET utf8 COLLATE utf8_unicode_ci,
  `grouptime` text CHARACTER SET utf8 COLLATE utf8_unicode_ci,
  `resetbydbchange` int(1) NOT NULL DEFAULT '0',
  `msgtouser` int(1) NOT NULL DEFAULT '0',
  `upcheck` int(1) NOT NULL DEFAULT '0',
  `uniqueid` text CHARACTER SET utf8 COLLATE utf8_unicode_ci,
  `updateinfotime` int(8) NOT NULL DEFAULT '0',
  `currvers` text CHARACTER SET utf8 COLLATE utf8_unicode_ci,
  `substridle` int(1) NOT NULL DEFA[...]
MySQL said: Documentation

#1046 - No database selected

Lots of errors as well
http://puu.sh/s1DsD/9de44fd14b.png
http://puu.sh/s1Dvg/8bbc4189ba.png

We are reverting back to 1.1.2 Alpha     minus our database... :(

**Comment by bykidi** [comment]
woah... you should always do backups for everything.

when i updated from 1.1.1 to 1.1.2 i just installed 1.1.2 to another database and after that i just edited dbconfig.php to use existed database. everything is ok for 24 hours, every function works fine, no errors (even my random calc_user, calc_serverstats errors are gone now)

**Comment by Newcomer1989** [comment]
How did you the update? What steps have you exactly done?

**Comment by SuperArmySoldiers** [comment]
Yeah I didnt do the update... not sure what happened with the back up of the database... our last one is 11 days old.

**Comment by Newcomer1989** [comment]
Ok, this does not help. You wrote first "Update would not work".. Then you wrote you didn't do the update.. What did you really???

I can't follow you! Which bugs should be in the release 1.1.2? Only for writing this it would not be possible for me to fix them.

Your posted error "SQL query: CREATE TABLE config ([..]" can't be from an update. This routine runs only on installation.
For me it looks you run instead of an update the install.php.. This is your misstake not a bug in the Ranksystem!

**Comment by SuperArmySoldiers** [comment]
I posted two screen shots of the errors. Please check my OP again.

**Comment by Newcomer1989** [comment]
You have made contradictory statements and have not clarified these despite my reference.
So I can not help!

**Comment by SuperArmySoldiers** [comment]
Not really. I have reported issues with the latest 1.1.2 release. See the screen shots.
We have gone back to the alpha version you sent me.

**Comment by Newcomer1989** [comment]
1) You did not described enough, that I can follow you. 
2) You ignored my question two times, what you exactly have done
3) In first post you wrote that the update did not work, posted screenshots with errors (where I interpret this comes after your update) and in your second post you wrote you didn't done an update
4) After my note to point 3 you ingored this and all other questions again

Result: This conversation is lost time for me -> Locked!
