### ISSUE TITLE
1.1.2 - Webinterface - no save possible

### ISSUE THREAD

**Issue by lucas19961** [Newcomer1989/TSN-Ranksystem#150]
After updating to 1.1.2 I can not save anything for example the admin ID and settings for the statistics

**Comment by lucas19961** [comment]
ok man kann auch auf deutsch schrieben :D

**Comment by Newcomer1989** [comment]
Welchen Fehler erhälst du denn beim Speichern?

**Comment by lucas19961** [comment]
Ich kann es zwar ganz normal speichern. Dann sagt er mir ich soll das ranksystem neustarten wenn ich das mache sind die einstellungen wie zuvor aber in der mysql datenbank wurde es angepasst. z-b wenn ich das menü auf der stats seite einschalte

**Comment by Newcomer1989** [comment]
> Dann sagt er mir ich soll das ranksystem neustarten

Soweit ist das auch normal. 

> wenn ich das mache sind die einstellungen wie zuvor

D.h. durch den Neustart des Ranksystems werden bei dir die Einstellungen im Webinterface zurückgesetzt? Oder sind sie schon direkt nach dem Speichern wieder wie zuvor?

>  in der mysql datenbank wurde es angepasst. z-b wenn ich das menü auf der stats seite einschalte

Wie sieht denn die config Tabelle in der Datenbank aus? Magst du uns diese mal hierein posten? Bitte aber zuvor Userdaten und Passwörter entfernen!

**Comment by lucas19961** [comment]
> D.h. durch den Neustart des Ranksystems werden bei dir die Einstellungen im Webinterface zurückgesetzt? Oder sind sie schon direkt nach dem Speichern wieder wie zuvor?

Ja ich klicke auf Speichern wechsle die seite z.b auf Kern und dann ist alles wieder weg d.h ich bekomme die Meldung das ich die Admin iD eintragen soll.

> Wie sieht denn die config Tabelle in der Datenbank aus? Magst du uns diese mal hierein posten? Bitte aber zuvor Userdaten und Passwörter entfernen!

tshost: localhost
tsquery: 10011
tsvoice: 9987
language: de
queryname: Ranksystem
queryname2: RankSystem
grouptime: 3600=>26,604800=>27,1209600=>28
resetbydbchange: 1
msgtouser: 1
upcheck: 1
uniqueid:
updateinfotime: 7200
currvers: 1.1.2
substridle: 0
exceptuuid:
exceptgroup: 14
dateformat: 	%a Tage, %h Stunde, %i Minuten, %s Sekunden
showexcld: 1
showcolcld: 1
showcoluuid: 1
showcoldbid: 1
showcolot: 1
showcolit: 1
showcolnx: 1
showclosg: 1
showcolrg: 1
showcolls: 1
slowmode: 1
cleanclients: 1
cleanperiod: 86400
showhighest: 1
boost: 0
showcolas: 1
defchid: 21
timezone: Europe/Berlin
logpath: /var/www/html/teamspeak/logs
advancemode: 0
count_access: 0
last_access: 1477675774
ignoreidle: 0
exceptcid:
rankupmsg: ...
boost_mode: 0
newversion: 1.1.2
servernews: ...
adminuuid: meine ID
nextupinfo: 1
nextupinfomsg1: ....
nextupinfomsg2: ...
nextupinfomsg3: ...
shownav: 1
showgrpsince: 1

**Comment by Newcomer1989** [comment]
Das sieht soweit gut aus.. Ist auch nur ein Eintrag vorhanden?
`select count(*) from config;`

**Comment by lucas19961** [comment]
jap nur eine config da

**Comment by Newcomer1989** [comment]
Hmm, das ist sehr suspekt. Das Ranksystem zieht sich die Informationen aus der Datenbank um sie im Webinterface anzuzeigen.
Demnach ist es eigentlich nicht möglich, dass das Ranksystem deine geänderten Informationen in der Datenbank speichert, sie aber nicht im Webinterface anzeigt. Bist du dir da sicher?
Betrifft das alle Felder?

Bitte werfe mal einen Blick auf deine other/dbconfig.php, ob dort die korrekten Datenbankinformationen hinterlegt sind.

**Comment by lucas19961** [comment]
> Bitte werfe mal einen Blick auf deine other/dbconfig.php, ob dort die korrekten Datenbankinformationen hinterlegt sind.

Sollte da die User ja auch eingespeichert werden

**Comment by Newcomer1989** [comment]
Der User ist dort erforderlich, ja.

**Comment by lucas19961** [comment]
nee meinte die ts user

**Comment by Newcomer1989** [comment]
Nein, die TS User stehen dort nicht drin!

**Comment by lucas19961** [comment]
Die Stehen doch auch in der Datenbank und wenn die falschen Daten in der dbconfig wären würden die ja nicht gesynct werden oder

**Comment by Newcomer1989** [comment]
Richtig.

Ist denn deine dbconfig nun in Ordnung?

**Comment by lucas19961** [comment]
Ja ist i.O

**Comment by lucas19961** [comment]
Egal was ich ändere es wird in die Datenbank geschrieben aber an der Webseite ändert sich nichts

**Comment by Newcomer1989** [comment]
Die einzige Idee wäre dann noch, dass die Files nicht sauber mit dem Update ausgetausch wurden. Bitte das noch einmal überprüfen. Insbesondere die Dateien im Unterordner webinterface.

**Comment by lucas19961** [comment]
Ok habs jetzt nochmal komplett gelöscht und jetzt geht es aufeinmal ohne probleme :D

**Comment by lucas19961** [comment]
Noch eine frage wäre es Möglich z.b das Webinterface bei der stats seite in die navbar mit reinzumachen ? mache das immer manuell :D

**Comment by Newcomer1989** [comment]
Das ist mit der Version 1.1.2 schon umgesetzt. Es ist aber nur für den Admin des Ranksystems möglich.

Voraussetzung ist, dass
1) die unique ID des Admins im Webinterface hinterlegt ist und
2) diese auch auf dem TS verbunden ist und
3) mit der gleichen IP der User auf der stats Seite ist.
