### ISSUE TITLE
1.1.2 - Bot disconnect silent after start

### ISSUE THREAD

**Issue by NeoX96** [Newcomer1989/TSN-Ranksystem#151]
Hey,
the Database and the Bot works perfectly and the Time of the users are also counted on the stats website but the Bot disconnect of the TeamSpeak after the Update. In the logs is no error but the bot is trying to reconnect every time

/stats/
https://i.gyazo.com/78dc0f24da864b12ff263500f15a40cb.png

/logs
https://i.gyazo.com/6949ffd763d50af15a74f680abe3a23b.png

**Comment by Newcomer1989** [comment]
How looks the table config?
`describe config;`

**Comment by Newcomer1989** [comment]
Have you the php-curl installed?

Try to install it:
`apt-get install php-curl`

After installation the bot still stops?

**Comment by Shad86** [comment]
Since no other answer from you was made i close this issue now because i am assuming that now everything works . 
If you still have a questions about this issue reopen this issue and tell us your question. 
If not make a new one.

greetings

Shad86
