### ISSUE TITLE
[BUG] - !nextup command shows every level.

### ISSUE THREAD

**Issue by GLARiven** [Newcomer1989/TSN-Ranksystem#154]
The bot returns every level with the same time for the next one.
![](http://i.imgur.com/XRSNL28.png)

But don't worry, it works fine.
It just returns too much information.
![](http://i.imgur.com/jTAOcD0.png)

**Comment by Newcomer1989** [comment]
This is a bug, correct!

It will be fixed with next release.

Also I will add this as feature in the next relase, if you want to get back the time for all higher ranks. So it will be selectable inside the webinterface.
For sure then it would gives back for each rank the correct time.

**Comment by Newcomer1989** [comment]
fixed with release 1.1.3 (was released a few minutes ago)
