### ISSUE TITLE
problem on ranksystem

### ISSUE THREAD

**Issue by kkaraIQ** [Newcomer1989/TSN-Ranksystem#155]
if i'll get start him from worker.php he will get start for 5sec and stop plz help me

**Comment by Shad86** [comment]
you can provide us a log? (it should be on in the ranksystem/logs folder)

**Comment by GLARiven** [comment]
Hey, did you install curl?

https://github.com/Newcomer1989/TSN-Ranksystem/releases/tag/1.1.2

! php-curl (package) is needed on the webserver - for linux "apt-get install php-curl"

**Comment by kkaraIQ** [comment]
oh thx its work but i have anuther problem the bot stop in 3 lvl or 4 he get from 1 to 4 in n normal but stop on 4 and i hava 50lvl what i can do 
thx for help
and sorry for my en

**Comment by Newcomer1989** [comment]
Have the bot the needed ts3 permissions to set the lvl 5 and higher?

Please post also the "rank up definition" from your core-settings out of the webinterface here. Perhaps you made a misstake in this definition.

**Comment by kkaraIQ** [comment]
u mean that [http://prnt.sc/d28jve](url)

**Comment by Shad86** [comment]
As i can see you exclude groups which usually participate in the rankup

**Comment by Shad86** [comment]
so as i can see you have to remove all groups on servergroup exception (because this groups didnt get obeserved from the ranksystem what means that people didnt get the rankups)

**Comment by Newcomer1989** [comment]
One problem is definitly found. Should be solved the issue.
