### ISSUE TITLE
Feature suggestion: sum of network traffic all time

### ISSUE THREAD

**Issue by mightyBroccoli** [Newcomer1989/TSN-Ranksystem#157]
I have an idea to possibly improve the statistics page. Normally the "Total bytes recieved/ sent" displays the data from the running instance since the last start.

Total bytes received	 304.66 MiB
Total bytes sent	 340.34 MiB

I would just propose the idea to change that just a little bit.

bytes received 304.66 MiB || Total 104 GiB
bytes sent	 340.34 MiB || Total 140 GiB

Or something more stylish that is just the basic idea.
What do you guys think about that?

**Comment by bykidi** [comment]
Great idea!
Having TeamSpeak built-in statistics is fine tho, but it resets during the time and does not save it anywhere else.

**Comment by Newcomer1989** [comment]
This informations comes from the ts3 server query.
Actual the informations comes from "connection_bytes_received_total" and "connection_bytes_sent_total".
There are no more informations of total bytes of a time before a server restart. Where should I get this informations?

**Comment by bykidi** [comment]
![default](https://cloud.githubusercontent.com/assets/1337953/20023553/df1cbb4e-a2f1-11e6-89b8-699753995a43.PNG)

**Comment by Newcomer1989** [comment]
The Bytes transferred are already known by the Ranksytem. And this is the value, which will be reset due a restart of the ts3 server.

Which value is here meaning especially?

**Comment by mightyBroccoli** [comment]
@Newcomer1989 I am not sure but couldn't you save the traffic like every 12 hours or so into the database. Just as a number and then just add to that number every time these x hours passed.

**Comment by Newcomer1989** [comment]
That would be hard to code. Let me explain on an example:

- Your TeamSpeak server has create 300 GB traffic. The Ranksystem knows this traffic (stored it in database).
- Then you restart your TeamSpeak server. It begins by zero. The Ranksystem still remember the 300 GB.
- After one hour your TeamSpeak server has 1 GB traffic. The Ranksystem still remember the 300 GB and add the 1 GB = 301 GB.
- After two hours your TeamSpeak server has 2 GB traffic. The Ranksystem remember 301 GB and add 2 GB (= 303 GB). -> No that would be wrong!

So I would need to remember also what traffic I had already noticed an which traffic comes on top. Also it would be **always** imprecise, cause it did not know the last value of traffic, before the TeamSpeak server shutdown/crashed.

My meaning is the benefit here is in no relation to the effort.
