### ISSUE TITLE
versions 1.1.3 php5-curl / php7-curl

### ISSUE THREAD

**Issue by kkaraIQ** [Newcomer1989/TSN-Ranksystem#158]
the new versions i have already install curl and tell me 
(PHP cURL is needed but seems not available. Install PHP cURL and try it again!)
?

**Comment by Shad86** [comment]
is curl enabled on your system? usually you can find that out with a info.php file - it should stand there that it is enabled

**Comment by Shad86** [comment]
on my info.php it looks like that
![curl](https://cloud.githubusercontent.com/assets/18570683/19950099/c1aea7ea-a155-11e6-984c-4ff3eb4be1ff.png)

**Comment by Shad86** [comment]
as little advise depends on you php version maybe you need an additional command:

apt-get install php5-curl or apt-get install php7-curl

**Comment by Shad86** [comment]
closed because of no answer
