### ISSUE TITLE
Update 1.1.3

### ISSUE THREAD

**Issue by Graushaus** [Newcomer1989/TSN-Ranksystem#159]
I have the new version on the server loaded and started. everything worked! But when I replaced the data: stats_user, user, and user_snapshot,comes the error code: calc_user 6: Array

what should I do?

LG Jan GER

# Full LOG

2016-11-03 01:44:41.066106   ERROR     calc_user 6:Array
2016-11-03 01:44:36.053855   INFO      Bot starts now his work!
2016-11-03 01:44:36.053770   NOTICE      No channel defined where the Ranksystem Bot should be entered.
2016-11-03 01:44:36.052266   INFO        Connection to TS3 Server established.
2016-11-03 01:44:36.031218   INFO      Connect to TS3 Server (Address: "multigameserver.net" Voice-Port: "6666" Query-Port: "10011").
2016-11-03 01:44:36.031151   INFO        Ranksystem Version: 1.1.3
2016-11-03 01:44:36.030914   NOTICE    Unnecessary file, please delete it from your webserver: install.php
2016-11-03 01:44:36.030821   INFO        No newer version detected; Database check finished.
2016-11-03 01:44:36.030688   INFO      Check Ranksystem database for updates.
2016-11-03 01:44:36.025123   INFO      Initialize Bot...

**Comment by Shad86** [comment]
sorry if im misunderstand you but on an update procedure you dont have to replace anything.

only thing you have to replace is your saved/backuped dbconfig

regards

Shad86

**Comment by Graushaus** [comment]
In the latest updates I have to keep the level of my user, simply always the 3 database entries deleted and replaced my old. This has always worked well and everyone could keep his level

The last 3 dates were always

http://img5.fotos-hochladen.net/uploads/forumranksystemlq5zd9uoaf.jpg

**Comment by Shad86** [comment]
the levels usually always been keept if you update in the right way (usually there is no need for it to make snaps)

The only time you lose is that time while you update your bot so in fact you will lose maybe 5min

If you follow these update instructions:

> How to UPDATE:
> 
> This HowTo is to update from 1.00, 1.0.1, 1.0.2, 1.1.0, 1.1.1 or 1.1.2 to version 1.1.3. If you still using 0.13-beta, you should first update to 1.00 and then update to the latest release.
> 
> 1. Download and unzip "ranksystem x.x.x.zip".
> 
> 2. Backup the "other/dbconfig.php" on your websever. We recommend to backup the whole webspace, the TeamSpeak server and also the database!
> 
> 3. Stop the sheduler (cron/task) for the worker.php and also stop the Bot (php worker.php stop). Be sure, there is no TSN Ranksystem connected to your TeamSpeak!
> 
> 4. Upload the whole unzipped folder to the your webspace and grant permissions to the webuser (i.E. chown -R www-data /var/www/Ranksystem).
> 
> 5. Restore the saved "other/dbconfig.php".
> 
> 6. Check php-curl is installed on your webserver (linux: apt-get install php-curl)!
> 
> 7. Reactivate the sheduler (cron/task) for the worker.php (see installation point 4).

you shouldn't get any problems i do it in that way since let me think version 1.0.0 and I didnt lost any rank of any user.

Maybe you forgot to save the dbconfig.php?

I think you have a backup of all your files so if you want i can come on the ts-n.de teamspeak if you need help.

regards

Shad86

**Comment by Graushaus** [comment]
That would be really nice if you could help me. I'm just on the teamspeak id = Jan

**Comment by Shad86** [comment]
im there channel is meins pw is 123

**Comment by Shad86** [comment]
Okay nach einem update nach Anleitung ging alles nun
