### ISSUE TITLE
problem with stats/index.php

### ISSUE THREAD

**Issue by XnIcRaM** [Newcomer1989/TSN-Ranksystem#16]
It's look like all work correctly, but when I try open stats/index.php then browser show me error 500 and in my http server error log file I found `PHP Parse error:  syntax error, unexpected T_OBJECT_OPERATOR in /var/www/ranksystem/stats/index.php on line 253`

**Comment by Newcomer1989** [comment]
Try to set the timezone about the webinterface.

If that do not work, pls send me what stands in your database
`select timezone from config;`

**Comment by XnIcRaM** [comment]
`select timezone from config;`
give me:
`Europe/Warsaw`

I try set diffrent timezone but still stats/index.php doesn't work (I check in database, timezone always change if I change it through webinterface)

**Comment by Newcomer1989** [comment]
> I try set diffrent timezone but still stats/index.php doesn't work (I check in database, timezone always change if I change it through webinterface)

Thats a known problem
https://github.com/Newcomer1989/TSN-Ranksystem/issues/8

Please connect short on my ts (address: ts-n.net). Then we can look together for your problem with the stats/index.php

**Comment by XnIcRaM** [comment]
You probably don't understand me :) Maybe my english is too bad :(

I don't have problem with changing timezone in webinterface, when I change it in webinterface then it also change in database

I can join to your TS, but dunno if my english is communicative :)

**Comment by Newcomer1989** [comment]
which PHP Version you are using?

**Comment by XnIcRaM** [comment]
I don't change `dateformat` and it is `%a days, %h hours, %i mins, %s secs`

PHP 5.3.3

**Comment by Newcomer1989** [comment]
ok.. if it is possible, try to upgrade to PHP 5.4 or above.
I know, its not in the requirements, but it should solve your problem.

**Comment by Newcomer1989** [comment]
should be emended with release 1.01
(enable the update check inside the webinterface to get notified when it gets published)
