### ISSUE TITLE
TS user & password

### ISSUE THREAD

**Issue by XnIcRaM** [Newcomer1989/TSN-Ranksystem#162]
how/where I can change TS username and password for bot?

**Comment by Newcomer1989** [comment]
inside the webinterface

**Comment by XnIcRaM** [comment]
If you have on mind webpage not php file then I can't do that. When I open webinterface then in top left corner I see message "Not Connected To TS3" and I don't know how to get connected

**Comment by Newcomer1989** [comment]
This is the stats page, where you are.

Please take attention on our official webpage -> http://ts-n.net/ranksystem.php

**How to use:**
_worker.php_
This file starts and stops the Bot and also scans the Bot is still running (restart it automatically, if crashed). So its like a startscript.

_/webinterface/_
Here you can config the main core of the TSN Ranksystem and also the style of part of the TSN Ranksystem (especially the list_rankup.php).

_/stats/_
Some stats about your server and round about the TSN Ranksystem. On this section you find also a list, which shows the nex rankups.

**Comment by XnIcRaM** [comment]
Maybe I have old version because I don't have file ranksystem.php in main folder are: update_1-00.php, webinterface.php and worker.php

**Comment by Shad86** [comment]
Thats right, the new versions from the ts-n ranksystem triggers on ranksystem/webinterface (if you need to login on your "admin" Webinterface)

**Comment by XnIcRaM** [comment]
Is there a way to update without lost all data, maybe could I replace all files without other/config.php?

**Comment by Shad86** [comment]
which version do you have now?

**Comment by XnIcRaM** [comment]
in mysql db table config I see "currvers 1.00"

**Comment by Shad86** [comment]
sorry for my late answer.

Then it should be possible to update like on the ts-n.ne side stands:

1. Download and unzip "ranksystem x.x.x.zip".

2. Backup the **"other/dbconfig.php"** on your websever. We recommend to **backup** the whole **webspace**, the **TeamSpeak server** and also the **database**!

3. Stop the **sheduler (cron/task)** for the **worker.php** and also stop the Bot (`php worker.php stop`). Be sure, there is no TSN Ranksystem connected to your TeamSpeak!

4. Upload the whole unzipped folder to the your webspace and **grant permissions to the webuser** (**i.E. chown -R www-data /var/www/Ranksystem**).

5. Restore the saved **"other/dbconfig.php"**.

6. Check **php-curl** is installed on your webserver (linux: `apt-get install php-curl`)!

7. Reactivate the **sheduler (cron/task)** for the **worker.php** (see installation point 4).
7.4 (Installation crontab) -> 4. Create a cronjob (here described for debian/ubuntu) for the worker to **keepalive the TSN Ranksystem Bot:**
Login in to your server via ssh.
**Enter the command "crontab -e" (In vim you have to press "i" to be able to edit the text)**
Paste the following line in a new line (you have to **edit** the **path**):
`*/10 * * * * sudo -u www-data php /path/to/your/websever/path/to/Ranksystem/worker.php check >/dev/null 2>&1`
**If needed Replace www-data with your webuser!** 
If you want, you can edit the interval. Here it is every 10 minutes.
Save and quit the crontable.


As an additional hint maybe you need a specific curl version(depends on how you installed it and which php version you are using):

apt-get install php5-curl or apt-get install php7-curl

**Comment by Newcomer1989** [comment]
Please take attention for step 2.. For an old version like you have, it is very important to make a backup of all!

Backup the "other/dbconfig.php" on your websever. We recommend to backup the whole **webspace**, the **TeamSpeak** server **and** also the **database**!
