### ISSUE TITLE
PHP 7 is installed but Bot complains about Php 5.4

### ISSUE THREAD

**Issue by Viper830** [Newcomer1989/TSN-Ranksystem#164]
my problem is that i want to start the bot and i become the error

Your PHP version (5.4.45-0+deb7u2) is below 5.5.0. Update of PHP needed! Shuttin down!

but as you can see here

http://noriskmultigaming.de/ranksystem/info.php
my php version is  7.0.12 how can i fix that

(sry for my bad english) PS. Bin mir nicht sicher ob du Deutsch sprichst wenn ja kannst du mir auch so antworten 

Regard Viper

**Comment by Shad86** [comment]
Dann hast du noch eine 2.te php version auf dem system - bitte bereinigen.

**Comment by Shad86** [comment]
Wenn php 5 drauf bleiben muss, warum auch immer, könntest du auch das hier versuchen:

a2dismod php5
a2enmod php7.0
service apache2 restart

MfG

Shad86

**Comment by Shad86** [comment]
Short in english:

or disable php5 with:

a2dismod php5
a2enmod php7.0
service apache2 restart

But here CAREFUL before you restart apache2 one php version MUST be ENabled (a2enmod php7.0 or a2enmod php5) because if not it is possible to download sensible data.

regards

Shadow86

**Comment by Viper830** [comment]
Ich lass das gerade mal von meinem Anbieter testen da ich selber da leider keinen Zugriff drauf habe

**Comment by Viper830** [comment]
ich schätze ich hab ein Problem da ich folgende Antwort bekommen habe

Hallo Tobias,
  
wie bereits gesagt nutzen wir Plesk.
Auf diesem Webhost auf dem Sie sich befinden arbeiten über 250 Kunden, daher werden wir keine Systemkonfigurationen die so tiefgehend sind vornehmen.
Davon abgesehen dass andere Kunden mit PHP 5 arbeiten.
Ihr Webspace nutzt KORREKT PHP 7, wie bereits gesagt sehen Sie das auch in der PHP Info Datei.

**Comment by Shad86** [comment]
Dann wäre es eventuell hilfreich wenn zumindest die php5 version im - ich nenne es mal background - up to date wäre.

Php 5.4 hat end of life support im Januar 2016 gehabt. (heißt es gibt dafür keine updates mehr = unsicher)

Die einzige php5 version die noch updates erhält ist 5.6

auch hier nachzulesen:

http://php.net/supported-versions.php

mit freundlichen Grüßen

Shad86

**Comment by Shad86** [comment]
Hab nochmal ein paar Dinge dazu editiert - deshalb nochmal eine Nachricht als Hinweiß - Ich denke ausführlicher muss es nicht sein

**Comment by Shad86** [comment]
Wenn du allerdings php 7 nutzt musst du mal noch nach den passenden paketen schauen, weil bis dato ich davon ausgegangen bin das du php 5 nutzt

**Comment by Viper830** [comment]
Ich weis nur nicht genau wie ich das bearbeiten soll da mein Anbieter mir nicht wirklich Rechte dafür gibt (leider)

**Comment by Shad86** [comment]
Ist schwierig und müsste sich dann mal @Newcomer1989  anschauen ob man bei dir mal im speziellen drüber schaut, an welchem Punkt er die php 5.4 version abgreifen will und warum er das tut obwohl du laut Aussage des Hosters nur php7 nutzt

**Comment by Viper830** [comment]
Ich hab auch laut meinem Anbieter mal die Datei erstellt 
http://noriskmultigaming.de/ranksystem/info.php
da steht auch PHP 7

**Comment by Shad86** [comment]
was sagt denn `php -v`

**Comment by Viper830** [comment]
Sry bin gerade voll Brain AFK ich weis gerade mit der Aussage nix anzufangen

**Comment by Shad86** [comment]
hm... du hast keinen Konsolen Zugriff nehme ich an? (fällt mir grade so ein - da du das ganze ja von einem hoster hast)

**Comment by Shad86** [comment]
Nur mal ganz doof gefragt, der teamspeak ist auch gehostet oder liegt der auf einem einem eigenen v-server?

**Comment by Viper830** [comment]
Der is von nem Partner von uns da bekomm ich aber soweit jeden zugriff wegen der Partnerschaft also auch von dem hoster

**Comment by Shad86** [comment]
Wie gesagt muss mal der Owner schauen ob er dir helfen kann. Heißt für dich erstmal warten leider abwarten - wie gesagt 2.te Sache wäre ihn mal auf das hinzuweißen was ich schon geschrieben hatte.

Outdatet seit Oktober/November - naja siehe weiter oben

**Comment by Newcomer1989** [comment]
Mal ganz doof gefragt, wie startest du den Ranksystem Bot denn eigentlich?

**Comment by Viper830** [comment]
Wenn du mit einfach starten im sinne von verbinden meinst mach ich das über das Interface von euch nachdem ich alles eingetragen habe

**Comment by Newcomer1989** [comment]
Der Ranksystem Bot wird mittels exec Befehl gestartet. D.h. es wird die PHP Version gezogen, die hinter dem Befehl `php` steckt. Bei deinem Anbieter ist das wohl PHP 5.4.45.
Merkwürdig ist das schon etwas, da im Webinterface ja wohl die PHP Version 7 genutzt wird (zumindest lt. deiner phpinfo).

Wenn dir bekannt ist, wo die PHP 7 Version installiert ist (Pfad der Installation), könnte man die worker.php entsprechend anpassen, sodass die andere PHP Version gezogen wird.

**Comment by Viper830** [comment]
.:/opt/plesk/php/7.0/share/pear (Standard)

/var/lib/php5 (Standard)

Das hab ich gerade in dem Interface von Plesk gefunden ich befürchte nur das ich da nicht rankomme wenn das die richtigen Pfade sind

**Comment by Viper830** [comment]
ich frage gerade mal beim Anbieter nach ob ich zugriff  darauf habe wo php 7 installiert ist

**Comment by Newcomer1989** [comment]
Das sieht mir nicht nach den richtigen Pfaden aus.

In der Regel liegen diese in "/usr".. Es könnte so bei dir aussehen:
/usr/bin/php  <-php 5.4.45
/usr/bin/php7.0 <- php 7.0

**Comment by Viper830** [comment]
Gerade die Antwort bekommen

Hallo Tobias,
  
der Pfad wäre /opt/plesk/php/7.0/bin/php
 
Vielen Dank und mit freundlichen Grüßen,
Ihr Server-Provider.com Team

**Comment by Newcomer1989** [comment]
Alternativ kann ich dir anbieten das Ranksystem zu hosten, sofern du mit deinem Anbieter nicht klar kommst.
Bei Bedarf bitte über das Kontakt-Formular eine Anfrage stellen (https://ts-n.net/contact.php)

**Comment by Viper830** [comment]
Ich werde gleich das Formular ausfüllen 
Müsste ich dann die IP von deinem Server in die TS Whitelist eintragen

**Comment by Newcomer1989** [comment]
In der **worker.php** wäre in deinem Fall folgender Eintrag zu ändern.

Sollte ca. in Zeile 110 sein.

Bisher:
`exec("php ".dirname(__FILE__)."/jobs/bot.php >/dev/null 2>&1 & echo $! > ".$GLOBALS['pidfile']);`

Ändern auf:
`exec("/opt/plesk/php/7.0/bin/php ".dirname(__FILE__)."/jobs/bot.php >/dev/null 2>&1 & echo $! > ".$GLOBALS['pidfile']);`

**Comment by Viper830** [comment]
ok

**Comment by Viper830** [comment]
Danke jetzt konnte er verbinden 

(in einer nicht komischen Weise) Ich liebe dich dafür

**Comment by Viper830** [comment]
Der Bot hat sich wieder beendet diesesmal mit ner Fehlermeldung 2017-01-01 18:27:01.097883   ERROR     Error 1024: invalid serverID ich hab aber nichts irgendwie umgestellt
