### ISSUE TITLE
rank up definiton

### ISSUE THREAD

**Issue by Bl4CkGuuN** [Newcomer1989/TSN-Ranksystem#165]
Hey,

All on my Teamspeak should get every 35 hours a uprank, but thats not working for me...

The 1st rank for 1 hour 3600seconds, 35x3600=126000 the 1st two ranks r working I think but for rank 4 i need over 50hours or so.

3600=>89,126000=>90,252000=>91,504000=>92,1008000=>93,2016000=>94

Greetz Bl4CkGuuN

**Comment by Newcomer1989** [comment]
I translate you, what you have done

yours in seconds
3600=>89,126000=>90,252000=>91,504000=>92,1008000=>93,2016000=>94

yours in hours
1=>89,35=>90,70=>91,140=>92,280=>93,560=>94


If you want it each 35 hours each step:
3600=>89,126000=>90,252000=>91,378000=>92,504000=>93,630000=>94

**Comment by Bl4CkGuuN** [comment]
oh, yeah...

thanks :D
