### ISSUE TITLE
[1.1.3] Cosmetic change to Top10 pages - Auto change fontsize in case if name doesn't fit

### ISSUE THREAD

**Issue by bykidi** [Newcomer1989/TSN-Ranksystem#166]
![default](https://cloud.githubusercontent.com/assets/1337953/20022024/a48d5c2a-a2e9-11e6-9e52-be2066e4112b.PNG)

I'm talking about №3 and №7. №3 is fine but 7th name doesn't fit.

**Comment by Newcomer1989** [comment]
An autofit is oversized in my opinion. If you want to code this, feel free to make a pull request.

With the next release I will decrease the font size a little bit. So for the most names this should be enough to be fully readable.

**Comment by bykidi** [comment]
I hope so too.
Gonna wait for next release.
