### ISSUE TITLE
BOT never starts

### ISSUE THREAD

**Issue by Bm8tower** [Newcomer1989/TSN-Ranksystem#169]
Hello guys.
Hope you can help please.
I have tried to install it like 10 times but no luck. 
I have done all configuration and next step is to press ''Restart Bot'' or ''Start Bot'' after that nothing happens, its just keep loading forever.

Then I found ''error.log'' inside ''webinterface'' folder where it says:
[07-Nov-2016 16:33:21 UTC] PHP Warning:  session_start(): Cannot send session cache limiter - headers already sent (output started at /home/bm8clan/public_html/ts3/webinterface/core.php:1) in /home/bm8clan/public_html/ts3/webinterface/core.php on line 2
[07-Nov-2016 16:33:26 UTC] PHP Warning:  session_start(): Cannot send session cache limiter - headers already sent (output started at /home/bm8clan/public_html/ts3/webinterface/other.php:1) in /home/bm8clan/public_html/ts3/webinterface/other.php on line 2
[07-Nov-2016 16:33:56 UTC] PHP Warning:  session_start(): Cannot send session cache limiter - headers already sent (output started at /home/bm8clan/public_html/ts3/webinterface/other.php:1) in /home/bm8clan/public_html/ts3/webinterface/other.php on line 2
[07-Nov-2016 16:34:08 UTC] PHP Warning:  session_start(): Cannot send session cache limiter - headers already sent (output started at /home/bm8clan/public_html/ts3/webinterface/stats.php:1) in /home/bm8clan/public_html/ts3/webinterface/stats.php on line 2
[07-Nov-2016 16:34:14 UTC] PHP Warning:  session_start(): Cannot send session cache limiter - headers already sent (output started at /home/bm8clan/public_html/ts3/webinterface/bot.php:1) in /home/bm8clan/public_html/ts3/webinterface/bot.php on line 2

Im not sure if that my main issue or there is something else

Any ideas?
Thanks

**Comment by Newcomer1989** [comment]
Which system are you using?
Which database, which PHP version, which webserver?
Have you checked the requirements for the Ranksystem?
Which version of the Ranksystem you tried to install?

**Comment by Bm8tower** [comment]
-Linux
-MySQL Database
-yes i meet all requirements
1.1.3

Hope i didn't miss understand your questions

**Comment by Newcomer1989** [comment]
Is there a ranksyste.log inside the logs folder?
If yes, what is inside?

You can also try to debug the Ranksystem to get the error.
1) Go to file jobs\bot.php and comment the line `error_reporting(0);` out (change to `//error_reporting(0);`)
2) Open a command line and run the jobs\bot.php manual
`php jobs\bot.php`
3) Post the output here...

**Comment by Bm8tower** [comment]
Thanks for response

-rankstyle.log is created after i press start/restart button and has only one line:
2016-11-08 21:52:25.410713   CRITICAL  Request to start the Ranksystem from 81.133.45.51. It seems the request came not from the command line! Shuttin down!

-I can change the code but sorry i dont know how to Open a command line on: cpanel accelerated 2

**Comment by Newcomer1989** [comment]
> 2016-11-08 21:52:25.410713 CRITICAL Request to start the Ranksystem from 81.133.45.51. It seems the request came not from the command line! Shuttin down!
This message comes, when you start the bot.php via the website.

When I hear cpanel... You are sure the exec command is available? I think this is the problem. Thats why it does not react on pressing the start button inside the webinterface.

**Comment by Newcomer1989** [comment]
closed due no response

**Comment by Bm8tower** [comment]
Sorry.
Support is very slow on other end.
Do i need to exec this path?:  ts3/jobs/bot.php and then its wil write line in error log?

Thanks

**Comment by Newcomer1989** [comment]
http://php.net/manual/en/function.exec.php

**Comment by Bm8tower** [comment]
Thats like bible :)
What am I looking for?

**Comment by Bm8tower** [comment]
Newcomer can yo please explain bit more this?:
Point 2 of installation (e.g. chown -R www-data /var/www/Ranksystem). For me its says nothing :) And i just keep skipping this step, maybe thats the problem?

Regards,
tower

**Comment by Bm8tower** [comment]
And i found a new error.
Does thats say something?:
[28-Nov-2016 18:45:15 UTC] PHP Fatal error:  Call to a member function query() on null in /home/bm8clan/public_html/ts3/other/session.php on line 24

**Comment by Newcomer1989** [comment]
> Thats like bible :)
> What am I looking for?

PHP have different functions. "Exec" is a function to execute commands on your system (shell) in the background. This is needed for the Ranksystem to start it via php command. 
Like documentated on the posted page, you can allow the exec command about the php.ini.


> Newcomer can yo please explain bit more this?:
> Point 2 of installation (e.g. chown -R www-data /var/www/Ranksystem). For me its says nothing :) And i just keep skipping this step, maybe thats the problem?

This are linux basics. You have to set the correct file permissions to the ranksystem folder. Your webuser (user with this your webserver runs) needs the access to the webfolder of the ranksystem.
For more about the permissions I would recommend to learn something about. Perhaps this site helps you a bit: https://www.linux.com/learn/understanding-linux-file-permissions


> [28-Nov-2016 18:45:15 UTC] PHP Fatal error: Call to a member function query() on null in /home/bm8clan/public_html/ts3/other/session.php on line 24

That comes from the database. There are a few options/things you should check:
1. Is the Ranksystem already fully installed, configurated and started?!
2. Your PHP need the PDO support. ([requirements](http://ts-n.net/ranksystem.php#requirements))
3. The database wasn't reachable at this point (perhaps is/was offline).

**Comment by Bm8tower** [comment]
You have done very good work and I really would love to see it working but seems like this is out of my league.
Would it be possible that you could try to install it for me if I give you full access?

**Comment by Newcomer1989** [comment]
It is possible to get the Ranksystem hosted.
Please take attention for this http://ts-n.net/ranksystem.php#support

**Comment by Bm8tower** [comment]
What would the link look like? Can you give me link for for some server stats what is hosted on your server?

Thanks

**Comment by Newcomer1989** [comment]
The link to the hosted system would look like
https://ts-n.net/host/rs/customer/XX/

Here a link to the public server, which are hosted on the same machine:
http://ts-n.net/ranksystem_dev/stats/

**Comment by Shad86** [comment]
Since no other answer from you was made i close this issue now because i am assuming that now everything works. 

If you still have questions open a **new** issue (if your question belongs to this issue you can refer/link to this thread with #issuenumber)

regards

Shad86
