### ISSUE TITLE
[Vorschlag] nextup als Channel Nachricht

### ISSUE THREAD

**Issue by simon1806** [Newcomer1989/TSN-Ranksystem#170]
Es wäre schön wenn die Funktion "nextup" auch als Channel Nachricht geht. So muss der User einfach in den Raum gehen in dem sich der Bot befindet.

**Comment by mightyBroccoli** [comment]
Problematisch wäre es dann wenn 2 User gleichzeitig im Channel sind.
Möglichkeit 1 die Channelbeschreibung zeigt etwas wie User 1 :  1 Tag 2 Stunden User 2 : 2 Tage 4 Stunden
oder was schlechter wäre der Bot hängt sich auf. Ich denke da ist anschreiben doch effizienter. Wenn auch die Query Natur des Bots da etwas Probleme macht.

**Comment by Shad86** [comment]
An und für sich antwortet der Query ja immer dem "Absender" ergo sollte immer die richtige Antwort bei der jeweiligen Person ankommen (der bot weiß ja von wem die Nachricht kam und wo sie wieder hin muss).

Das einzig wichtige ist nur, das der Query nicht im Channel antwortet sondern der jeweilige Person privat die Nachricht/Antwort zusendet.

**Comment by simon1806** [comment]
> Das einzig wichtige ist nur, das der Query nicht im Channel antwortet sondern der jeweilige Person privat die Nachricht/Antwort zukommen lässt.

So habe ich das auch gemeint und kenne es auch von anderen Bots.

**Comment by Newcomer1989** [comment]
> Sollte also denke ich durchaus machbar sein das der query auf den channel "lauscht" und privat zurück antwortet.

Wird genau so gemacht... Kommt dann mit dem nächsten Release.

**Comment by Newcomer1989** [comment]
Release 1.2.0 is out.
