### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by NothingTV** [Newcomer1989/TSN-Ranksystem#172]
Hello, since the last update the bot has a very high cpu usage.

If the Bot runs the CPU Usage of mysql goes up to 98-100%.

My VPS runs with Ubuntu 16.04 on a singlecore Prozessor with 1GB RAM.

**Comment by Newcomer1989** [comment]
Please use on little machines the slowmode on "high delay". This should solve your problem!

**Comment by NothingTV** [comment]
solved, thanks!
