### ISSUE TITLE
[Ger]Log nicht vorhanden - 

### ISSUE THREAD

**Issue by simon1806** [Newcomer1989/TSN-Ranksystem#173]
Ich habe das Problem das bei mir keine Logs geschrieben werden. Ich habe immer folgende Meldung im 

> Ranksystem Log (Auszug):
> 
> > The logfile will be created with next startup.
> > No log entry found...

Deswegen ist bei mir auch kein Update auf 1.1.3 möglich wegen der neuen Funktion:
+ added check on startup if logpath exists and is writeable

**Comment by Shad86** [comment]
Dann überprüfe bitte ob der Pfad zum log existiert und setze den logs Ordner auf 0777

**Comment by simon1806** [comment]
Danke es lag an dem Pfad der nicht richtig war. Hätte ich auch selber drauf kommen können 😄.
