### ISSUE TITLE
Timed out! Free webhost

### ISSUE THREAD

**Issue by Dinip12** [Newcomer1989/TSN-Ranksystem#177]
I'm trying to run ranksystem on x10hosting.
Everything went well, the interface is fully installed but i'm getting timed out! It is a "problem" cause i'm running on x10hosting? Does anyone know?
Sry for bad english, from Portugal :)

2016-11-11 23:32:58.595211   ERROR     Error 110: Connection timed out
2016-11-11 23:32:48.578240   INFO      Connect to TS3 Server (Address: "xxx.xxx.xxx.xx" Voice-Port: "9987" Query-Port: "10011").
2016-11-11 23:32:48.578149   INFO        Ranksystem Version: 1.1.3
2016-11-11 23:32:48.577408   INFO        No newer version detected; Database check finished.
2016-11-11 23:32:48.577308   INFO      Check Ranksystem database for updates.
2016-11-11 23:32:48.571677   INFO      Initialize Bot...

**Comment by Shad86** [comment]
if the bot times out - be sure that you whitelisted the ip from the webspace on the ts3-server (in the ts3-server folder -> Query_IP_Whitelist.txt)

**Comment by Newcomer1989** [comment]
Like Shad86 said, it could be the bot get banned from the TS3 server.

Please check the following things:

1) **Whitelist** the IP address of your webhost (where the webserver/PHP runs) to your TS3 server. You should find a `query_ip_whitelist.txt` inside the TS3 server root directory. Add the IP of the webhost here.

2) Be sure your query user is not restricted with command limitation. Give the query user the TS3 permission **b_client_ignore_antiflood**. This should prefer a blocking due flood protection.


If you are not be able to change the two points above, you can try to use the **Slowmode**. This function you can activate inside the webinterface inside the TeamSpeak options. In this case use the "High delay (1,0 seconds)".
For this stop the Bot, activate the slowmode and wait 10-15 min. before restarting the Bot.

**Comment by Newcomer1989** [comment]
closed due no response
