### ISSUE TITLE
PHP Wrong Version

### ISSUE THREAD

**Issue by Pepreal** [Newcomer1989/TSN-Ranksystem#179]
For some reason the Ranksystem is seeing the incorrect version of PHP, its says that it is PHP 5.3.3 when it is 7.0.13 and the bot wont start.

> 2016-11-12 15:23:54.261476   CRITICAL  Your PHP version (5.3.3) is below 5.5.0. Update of PHP needed! Shuttin down!

Here is the proof that it is 7.0.13 http://ts-fc4a.nl/tsrank/version.php

**Comment by Newcomer1989** [comment]
There will be obviously used two different versions on your system.

Your webserver uses PHP 7.0.x but the local command "php" used 5.3.x and is to low for the Ranksystem.

Try the command `php -v` on your console to see with version will be used there.

You need to change, that your php command uses PHP 7.0.x and not 5.3.x!

**Comment by Pepreal** [comment]
Unfortunately i cannot change this because this is a webhost with multiple PHP versions so what id is change this

>   \tsrank\jobs\bot.php
> 	Line 35: 			$oExec = $WshShell->Run("cmd /C php70 ".substr(__DIR__,0,-4)."worker.php start", 0, false);
> 	Line 39: 			exec("php70 ".substr(__DIR__,0,-4)."worker.php start");
>   \tsrank\jobs\handle_messages.php)
> 	Line 99: 			exec("php70 ".$path."worker.php stop");
> 	Line 117: 				exec("start php70 ".$path."worker.php restart");
> 	Line 119: 				exec("php70 ".$path."worker.php restart > /dev/null 2>/dev/null &");
>   \webinterface\bot.php
> 	Line 127: 			$oExec = $WshShell->Run("cmd /C php70 ".substr(__DIR__,0,-12)."\worker.php start", 0, false); 
> 	Line 129: 			exec("php70 ".substr(__DIR__,0,-12)."worker.php start");
> 	Line 141: 		$oExec = $WshShell->Run("cmd /C php70 ".substr(__DIR__,0,-12)."\worker.php stop", 0, false); 
> 	Line 143: 		exec("php70 ".substr(__DIR__,0,-12)."worker.php stop");
> 	Line 157: 			$oExec = $WshShell->Run("cmd /C php70 ".substr(__DIR__,0,-12)."\worker.php restart", 0, false); 
> 	Line 159: 			exec("php70 ".substr(__DIR__,0,-12)."worker.php restart");
>   \tsrank\webinterface\changepassword.php
> 	Line 32: 			$oExec = $WshShell->Run("cmd /C php70 ".substr(__DIR__,0,-12)."worker.php start", 0, false);
> 	Line 36: 			exec("php70 ".substr(__DIR__,0,-12)."worker.php start");
>   \tsrank\webinterface\index.php
> 	Line 32: 			$oExec = $WshShell->Run("cmd /C php70 ".substr(__DIR__,0,-12)."worker.php start", 0, false);
> 	Line 36: 			exec("php70 ".substr(__DIR__,0,-12)."worker.php start");
>   F\tsrank\webinterface\resetpassword.php
> 	Line 32: 			$oExec = $WshShell->Run("cmd /C php70 ".substr(__DIR__,0,-12)."worker.php start", 0, false);
> 	Line 36: 			exec("php70 ".substr(__DIR__,0,-12)."worker.php start");
>   \tsrank\worker.php
> 	Line 90: 				$oExec = $WshShell->Run("cmd /C php70 ".__DIR__."\jobs\bot.php", 0, false);
> 	Line 114: 			exec("php70 ".dirname(__FILE__)."/jobs/bot.php >/dev/null 2>&1 & echo $! > ".$GLOBALS['pidfile']);
> 

The only problem is that if you bring an update, i have to do this all over again, maybe you can make this as an enhancement

**Comment by Newcomer1989** [comment]
If your hoster will not update his base PHP, you can also get the Ranksystem hosted from us.

Note this:
http://ts-n.net/ranksystem.php#support
