### ISSUE TITLE
PHP Multiple Versions

### ISSUE THREAD

**Issue by Pepreal** [Newcomer1989/TSN-Ranksystem#180]
Changes some of the files so it will work on a webhost which has multiple PHP versions, to get it to work i change the lines and files below

    \tsrank\jobs\bot.php
    Line 35: $oExec = $WshShell->Run("cmd /C php70 ".substr(DIR,0,-4)."worker.php start", 0, false);
    Line 39: exec("php70 ".substr(DIR,0,-4)."worker.php start");
    \tsrank\jobs\handle_messages.php)
    Line 99: exec("php70 ".$path."worker.php stop");
    Line 117: exec("start php70 ".$path."worker.php restart");
    Line 119: exec("php70 ".$path."worker.php restart > /dev/null 2>/dev/null &");
    \webinterface\bot.php
    Line 127: $oExec = $WshShell->Run("cmd /C php70 ".substr(DIR,0,-12)."\worker.php start", 0, false);
    Line 129: exec("php70 ".substr(DIR,0,-12)."worker.php start");
    Line 141: $oExec = $WshShell->Run("cmd /C php70 ".substr(DIR,0,-12)."\worker.php stop", 0, false);
    Line 143: exec("php70 ".substr(DIR,0,-12)."worker.php stop");
    Line 157: $oExec = $WshShell->Run("cmd /C php70 ".substr(DIR,0,-12)."\worker.php restart", 0, false);
    Line 159: exec("php70 ".substr(DIR,0,-12)."worker.php restart");
    \tsrank\webinterface\changepassword.php
    Line 32: $oExec = $WshShell->Run("cmd /C php70 ".substr(DIR,0,-12)."worker.php start", 0, false);
    Line 36: exec("php70 ".substr(DIR,0,-12)."worker.php start");
    \tsrank\webinterface\index.php
    Line 32: $oExec = $WshShell->Run("cmd /C php70 ".substr(DIR,0,-12)."worker.php start", 0, false);
    Line 36: exec("php70 ".substr(DIR,0,-12)."worker.php start");
    F\tsrank\webinterface\resetpassword.php
    Line 32: $oExec = $WshShell->Run("cmd /C php70 ".substr(DIR,0,-12)."worker.php start", 0, false);
    Line 36: exec("php70 ".substr(DIR,0,-12)."worker.php start");
    \tsrank\worker.php
    Line 90: $oExec = $WshShell->Run("cmd /C php70 ".DIR."\jobs\bot.php", 0, false);
    Line 114: exec("php70 ".dirname(FILE)."/jobs/bot.php >/dev/null 2>&1 & echo $! > ".$GLOBALS['pidfile']);

The only problem is that if you release an update, i have to do this all over again, maybe you can make this as an enhancement so it will work on webhost with multiple PHP versions
http://ts-fc4a.nl/tsrank/stats/index.php

**Comment by Newcomer1989** [comment]
This will work in your case.. But other ppl has other PHP versions.
Also on linux it will work different. And the most user are using linux.

So I can't add it to the next version, cause I cannot guess which version you have installed on your system and where this is locate!

**Comment by Pepreal** [comment]
My webhost is also using linux, but why not make it as so that it will see the different version on an multiple PHP server. most webhost are using multiple PHP versions. on a webhost were thousands of site are running you cannot simply update PHP that will break a lot of site that are using an older PHP versions. Thats why lot of webhost are using multiple version. Also my webhost has contacted a few collage to see if they can run this script with multiple PHP versions but it is also giveing the same problems. Maybe by adding a rule in the dbconfig.php can solve a lot of problems and make it more universal.

**Comment by Pepreal** [comment]
Maybe by adding this rulse $path_to_binary="/usr/bin/php"; i think with this you can choose which version of PHP you can use and where it is located, also think this should work in Linux or windows

**Comment by Newcomer1989** [comment]
I am to good for this world.. I will add this as feature with the next version.
There you will find in other/phpcommand.php a way to set an other command, like in your way.

**Comment by Pepreal** [comment]
Thanks for that, i'm very happy to see this, it will also help a lot of other people also using webhost

**Comment by Newcomer1989** [comment]
Release 1.2.0 is out.
