### ISSUE TITLE
[Ger]Errungenschaften und Login

### ISSUE THREAD

**Issue by cr0co** [Newcomer1989/TSN-Ranksystem#182]
Hallo

1.)
Bei mir werden bei Errungenschaften 8/8 angezeigt,
auf der rechten seite allerdings nur 2 aufgeführt.

in der datei my_stats.php finde ich auch nur variablen für time und connects. 
wie und was kann ich da noch alles hinzufügen?

2.)
Wie funktioniert der Login?
bin ein bisschen verblüfft als ein user meinte er konnte sich ohne passwort einloggen,
um seine "Meine Statistiken" zu sehen.

Gruss und Danke für das tolle Programm

**Comment by Shad86** [comment]
Hallo,

**Zu erstens:**

Auf der rechten Seite sollten eigentlich "3" Errungenschaften sein. (Du hast das latest release? -> 1.1.3)

Nächste Servergruppe / Zeit / Verbindungen

Hinzufügen kann man nichts die 8/8 Errungenschaften existieren bereits im Webinterface. 
Dazu kann ich dir aber gerade nichts genaueres sagen, wie sich das genau aufteilt.

Ich kann nur soviel dazu sagen, dass die ganze "Errungenschaft Geschichte" mehr zu einem späteren Feature gehört und derzeit noch keine so große Relevanz hat.

_Falls du dazu mehr wissen möchtest kannst du gerne Newcomer1989 makieren mit einem @ vor seinem namen._

**Zu zweitens:**

Für user gibt es keinen Login diese können per "ranksystem/stats" deren eigene mystats Seite einsehen und nun kommen wir zu dem Punkt "Wenn sie auf dem entsprechenden Teamspeak server sind" - heißt also man könnte das verbunden sein auf dem TS3 als einen "login" sehen.

Den einzigen richtigen Login den es gibt ist der für die Einstellungen des Ranksystems unter "ranksystem/webinterface".


Mit freundlichen Grüßen

Shadow86

**Comment by Newcomer1989** [comment]
zu 1) Es sind genau genommen zwei Errungenschaften, die jeweils 4 "Fortschritte" haben. Daher kommen die 8 von 8. Das ist etwas ungenau formuliert und derzeit auch noch nicht beschrieben.
Wie schon erwähnt, wird das Feature in späterer Zukunft noch eine Rolle spielen und dann auch noch einmal angepackt. Zum einen sollen die Errungenschaften variabel definierbar werden. Zum Anderen wird es dann sicherlich noch sauberer "benannt".

**Comment by cr0co** [comment]
ah okay vielen dank
