### ISSUE TITLE
Problems with webinterface login

### ISSUE THREAD

**Issue by JohnnyRme** [Newcomer1989/TSN-Ranksystem#183]
Hi,

i have a problem when i try to login to the administration webinterface.

After the login my webserver forwards me i got a blank site which contains "No input file specified."
I think my Nginx is causing this Problem.

My current Nginx config for the ranksystem looks like this:

```
    root /var/www/ranksystem;

    index index.php;

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        #try_files $uri $uri/ =404;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_param HTTPS on;
        fastcgi_param modHeadersAvailable true; #Avoid sending the security headers twice
        fastcgi_pass php-handler;
        fastcgi_intercept_errors on;
    }
```

I also tried to add a location bracket for the webinterface folder, but nothing happend.

Does someone has an Nginx config for me? Or knows what i have to change here. I really don't think this is a problem within the ranksystem itself.

**Comment by Newcomer1989** [comment]
try to define teh fastcgi_index

```
    root /var/www/ranksystem;

    index index.php;

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        #try_files $uri $uri/ =404;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        **fastcgi_index index.php;**
        fastcgi_param HTTPS on;
        fastcgi_param modHeadersAvailable true; #Avoid sending the security headers twice
        fastcgi_pass php-handler;
        fastcgi_intercept_errors on;
    }
```

**Comment by JohnnyRme** [comment]
I defined the fastcgi_index in my config nothing changed, so the problem still exists.

My fastcgi_params contains the following options:

```
fastcgi_param  QUERY_STRING       $query_string;
fastcgi_param  REQUEST_METHOD     $request_method;
fastcgi_param  CONTENT_TYPE       $content_type;
fastcgi_param  CONTENT_LENGTH     $content_length;

fastcgi_param  SCRIPT_NAME        $fastcgi_script_name;
fastcgi_param  REQUEST_URI        $request_uri;
fastcgi_param  DOCUMENT_URI       $document_uri;
fastcgi_param  DOCUMENT_ROOT      $document_root;
fastcgi_param  SERVER_PROTOCOL    $server_protocol;
fastcgi_param  REQUEST_SCHEME     $scheme;
fastcgi_param  HTTPS              $https if_not_empty;

fastcgi_param  GATEWAY_INTERFACE  CGI/1.1;
fastcgi_param  SERVER_SOFTWARE    nginx/$nginx_version;

fastcgi_param  REMOTE_ADDR        $remote_addr;
fastcgi_param  REMOTE_PORT        $remote_port;
fastcgi_param  SERVER_ADDR        $server_addr;
fastcgi_param  SERVER_PORT        $server_port;
fastcgi_param  SERVER_NAME        $server_name;

# PHP only, required if PHP was built with --enable-force-cgi-redirect
fastcgi_param  REDIRECT_STATUS    200;
```

Just the default configuration I didn't changed anything here.

**Comment by Newcomer1989** [comment]
Add this in your fastcgi_params

`fastcgi_param  SCRIPT_FILENAME    $document_root/$fastcgi_script_name;`

**Comment by JohnnyRme** [comment]
After adding this line I still got the same error message.

**Comment by Newcomer1989** [comment]
I am no master of the nginx configuration, but I am sure your problem has to be the missed SCRIPT_FILENAME param.
Please try out yourself some variants of it. Also google would be your friend.

**Comment by JohnnyRme** [comment]
After a long time i figured out that it was indeed the SCRIPT_FILENAME param.

I had to insert `fastcgi_param  SCRIPT_FILENAME    $document_root$fastcgi_script_name;` in the /etc/nginx/fastcgi_params above SCRIPT_NAME.

First i inserted it at the end but this didn't worked.
