### ISSUE TITLE
Root permissions?

### ISSUE THREAD

**Issue by Hedius** [Newcomer1989/TSN-Ranksystem#185]
I haven't updated to 1.2.0 yet, because the install guide suggests to run the worker with root permissions.
Why does the script need root perms?
Am I able to run 1.2.0 without using root?

**Comment by Newcomer1989** [comment]
Which guide you mean? This one http://ts-n.net/ranksystem.php#install ?

**Comment by Hedius** [comment]
Yes

**Comment by Newcomer1989** [comment]
You should not run the Ranksystem with root privileges. There is also a check that you should not use root privileges!

It is recommended to run the Ranksystem with your webuser.

**Comment by Hedius** [comment]
Ah sorry i overlooked the -u parameter in the cron job... Sorry... My fault ^^ Well time to upgrade 👍 
Anyway thanks for your answer :)
