### ISSUE TITLE
No installation possible Version 1.2.0

### ISSUE THREAD

**Issue by Speddy** [Newcomer1989/TSN-Ranksystem#186]
If I call install and the db enter and click on install always comes

ATTENTION: You are trying to install the Ranksystem, but there is already existing a database with the name "ts3_ranksystem".
Due installation this database will be dropped!
Be sure you want this. If not, please choose an other database name.

See Attachment

https://gameserversupport.de/bilderhosting/images/ts3ranksystem.JPG

**Comment by Newcomer1989** [comment]
That means, the Ranksystem database is still there.

If you haven't run the Ranksystem before you need only click a second times on install.
When you have a running Ranksystem be sure you want to overinstall your old Ranksystem. If yes, same as above. If no, choose an other db name.

**Comment by Speddy** [comment]
On the server is No Ranksystem Installed I have to create a database itself and not through because Installer that is unfortunately not possible because I use imscp.

**Comment by Speddy** [comment]
Has done itself after the 10 times went the installation to the database and could create because Admin user.
