### ISSUE TITLE
Teamspeak Client not detected on Linux

### ISSUE THREAD

**Issue by Floflobel** [Newcomer1989/TSN-Ranksystem#188]
Hi,

I run my teamspeak client on my fedora (Linux) but it's not detected by the website.

**Comment by Shad86** [comment]
how do you mean that "its not detected" - it doesn't recognize you on the site?

**Comment by Floflobel** [comment]
At top of my Browser I have "(You are not connected to the TS3!) ". On my windows it work perfectly but on my fedora doesn't work.

**Comment by Newcomer1989** [comment]
Then it is possible you are using different internet connections or at least a different ip protocol (ipv4/ipv6).

If you are connected, will be matched via the ip address. The protocoll needs to be the same, cause it is not possible to resolve from your ipv4 to your ipv6 or reverse.

**Comment by Floflobel** [comment]
Ok I will try tomorrow and I report if not work.

Thank's for your reactivity

**Comment by Floflobel** [comment]
After retry, it's ok ! Thank's
