### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by Shadowoli** [Newcomer1989/TSN-Ranksystem#189]
Hey I just updatet my Rankingsystem to 1.2.0 and added SSL (HTTPS) to my server but now the CSS sheet doesn't work annymore and I don't konw the reasson can you help me ? 
When you want to see it yourself: https://shadowlp.hopto.org/rank/stats/

**Comment by Shad86** [comment]
I updated 2 different ranksystems, worked well also with https.

i suggest that you may try a reinstall of the Webinterface things.

regards

Shad86

**Comment by Shad86** [comment]
what i also saw is that it doesn't redirect from https://shadowlp.hopto.org/rank/ to https://shadowlp.hopto.org/rank/stats/

maybe thats also an issue from your side

regards

Shad86

**Comment by Newcomer1989** [comment]
The problem are the permissions on your webserver. Please check you did step 2 correct -> http://ts-n.net/ranksystem.php#install

If the file permissions are not the problem, you should check your config of your webserver self...

view-source:https://shadowlp.hopto.org/rank/libs/bootstrap/css/custom.css

> <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
> <html><head>
> <title>403 Forbidden</title>
> </head><body>
> <h1>Forbidden</h1>
> <p>You don't have permission to access /rank/libs/bootstrap/css/custom.css
> on this server.<br />
> </p>
> </body></html>

**Comment by Shadowoli** [comment]
Thank you very much i know th Problem know forgot to Remove the password Protection from the lib file
