### ISSUE TITLE
Connections

### ISSUE THREAD

**Issue by Pepreal** [Newcomer1989/TSN-Ranksystem#190]
Its more an question, is it true with the new version that it makes more sql connections then before.
I can make 5 connections at the same time, now with the new version i get sometimes connections errors.
Run 2 site beside TSrank and its sometimes enyoing

**Comment by Newcomer1989** [comment]
In short no. With the update was nothing special changed on the SQL connection or there were much more things, which the database have to do.

The Ranksystem opens one persistent connection to the database and works sequential the things off. So there are not more connections needed.

An idea, what could be in your case: The stats page opens a different connection to the database to read the stats out of them. This will be done for each user, which visits this site. So perhaps the count of your visitor increased...

**Comment by Pepreal** [comment]
Oke thanks for the info, maybe thats the case id.
