### ISSUE TITLE
Mehrere Instanzen

### ISSUE THREAD

**Issue by simon1806** [Newcomer1989/TSN-Ranksystem#191]
Als würde mir wünschen, wenn es möglich wäre, das über ein System mehrere Instanzen laufen würden. So muss man das Ranksystem nicht mehrmals installieren, wenn man mehrere Teamspeak hat.

**Comment by majoess** [comment]
Klar geht das auch für mehrere Server, musst du nur ein klein wenig umschreiben

**Comment by Newcomer1989** [comment]
Magst du das umsetzen majoess?

**Comment by majoess** [comment]
@Newcomer1989 könnte mich die nächsten Tage an ein Merge ransetzen

**Comment by Shad86** [comment]
Ich wollte mal eben nachfragen ob du bereits an dem Merge sitzt, denn es sind ein paar Datenbank Optimierungen/Änderungen geplant und es wäre vermutlich ratsam dieses update noch abzuwarten.

Falls du dennoch schon an dem Merge sitzen solltest wäre es eventuell gut wenn man sich zusammensetzen könnte, so dass deine Arbeit nicht umsonst war oder du eben den Merge anpassen kannst.

MfG

Shad86

**Comment by majoess** [comment]
@Shad86 ich habe noch nicht angefangen, sag mir Bescheid wenn es los gehen kann!

**Comment by Newcomer1989** [comment]
Version 1.2.1 ist veröffentlicht. Darin sind die Änderungen an der Datenbank berücksichtigt.

Demnach: Bescheid

**Comment by majoess** [comment]
Okay, ich weiß noch nicht wann ich anfange, da ich derzeit viel mit Node.js beschäftigt bin.

**Comment by Shad86** [comment]
Ich wollte mal noch Ende diesen Jahres fragen, ob du schon daran arbeitest.

**Comment by majoess** [comment]
@Shad86 bin derzeit im Urlaub und warte auf mein neuen MacBook, dann arbeite ich daran wohl

**Comment by Shad86** [comment]
Ich wollte mal wieder nachfragen, wie es ausschaut :) - und ich hoffe du hattest einen schönen und erholsamen Urlaub.

**Comment by majoess** [comment]
Danke, bin dabei

**Comment by Newcomer1989** [comment]
Zur Info 1.2.2 ist nun draußen. Bitte die SQL Änderungen berücksichtigen für das Instanzen-System!

**Comment by Newcomer1989** [comment]
Wie sieht es denn aus? Wie weit bist du denn mit der Instanzen-Unterstützung?

**Comment by majoess** [comment]
Ich bin nicht wirklich weit gekommen, ich denke morgen ist der Fork online, aber natürlich nicht fertig

**Comment by Newcomer1989** [comment]
> nur ein klein wenig umschreiben

Ist wohl doch nicht so einfach, wie du es zu Anfang beschrieben hast ;-)

**Comment by monster010** [comment]
@Newcomer1989 wenn du nichts dagegen hast, würde ich die Instanzen-Unterstützung rein hauen, würde aber im gleichen Zug das Ranksystem mit CodeIgniter umsetzen.

**Comment by Shad86** [comment]
Das klingt auf jeden fall interessant, wenn du das Instanzen-system umsetzen könntest wäre das Klasse, da doch einige sich darüber freuen würden!

**Comment by monster010** [comment]
@Shad86 ich würd mich selbst sehr drüber freuen =D

**Comment by Shad86** [comment]
Dann bereite doch uns und dir eine Freude und wie sagte einst jemand "just do it" ;D

**Comment by monster010** [comment]
Ja, nur ich weiß halt nich ob ihr mit nem MVC Model zurecht kommt bzw ob @Newcomer1989 damit zurecht kommt, deswegen warte ich auf seine Antwort

**Comment by Shad86** [comment]
Er hat derzeit wenig Zeit, die Antwort könnte sich also etwas verzögern [Studium(Lernen+Klausuren),Arbeit]

**Comment by monster010** [comment]
@Shad86 is ja nich schlimm ^^, so hab ich auch noch Zeit mich um anderes zu kümmern

**Comment by Newcomer1989** [comment]
@monster010 Klar, kein Problem. Mit MVC komme ich klar. Bin dann mal sehr gespannt, wie es sich auf die Performance auswirkt.
Bitte setze dich vorab mit uns in Verbindung, um die aktuellste Pre-Version zu erhalten.

**Comment by monster010** [comment]
@Newcomer1989 wie soll ich mich denn mir euch in Verbindung setzen? =D

**Comment by Shad86** [comment]
Einfach hier hin schreiben -> https://ts-n.net/contact.php

Die Felder können leer gelassen werden:
> Server-Port /
> Channel-Nr. /
> Customer-ID:

**Comment by Shad86** [comment]
Hallo @monster010  oder auch @majoess arbeitet ihr noch an dem Instanzensystem?

Newcomer ist zwar irgendwie away, aber gut wäre die Sache ja dennoch.

**Comment by monster010** [comment]
Sagen wir ma so, da NewComer mir eigentlich ne SQL senden wollte, aber da wohl nich mehr zu kam, nich wirklich.

**Comment by monster010** [comment]
@Shad86 kann ich dich irgendwie errreichen? Also außerhalb von Github?

**Comment by Shad86** [comment]
Sorry hatte den Kommentar hier i-wie übersehen, falls du noch mit mir in Kontakt treten willst schreib mir hier nochmal

**Comment by Newcomer1989** [comment]
Ist ja nicht wirklich was aus den pull-requests geworden.

Von meiner Seite werde ich keine Zeit in ein Instanz-System investieren. Primär vereinfacht das den Weg für (kommerzielle) Hoster noch mehr. Das ist auch völlig legitim (da GPLv3), aber ich werde es kommerziellen Hosters nicht noch einfacher machen. Wenn sollen die selbst die Zeit für einen Hostingbetrieb aufwenden müssen :-P.

Außerdem sind noch einige andere Dinge geplant, die wohl in den meisten Fällen die Erforderlichkeit  von zusätzlichen Instanzen abfangen werden. Die betrifft dann die Konstellation 1 TS Server, mehrere Ranksysteme.
Ob dann noch einige wenige (Sonder)Fälle existieren, die dann noch eine zusätzliche Installation erfordern, müssen wir zu gegebener Zeit dann mal schauen.

Daher: Feature -> declined
