### ISSUE TITLE
Issue with install.php

### ISSUE THREAD

**Issue by JoniVR** [Newcomer1989/TSN-Ranksystem#192]
Hi, 
So first of all, thanks for the great work on this, really appreciate it!
Ok, so this might sound a little bit weird, I'll try to be as clear as possible.. 

I installed this on my server (running Debian Wheezy), configured SSL, gave all the permissions,... But I had some issues with the first step of the install.php process (Install database):
1. It kept saying that my php version was too low, needed to be 5.5+, and I checked and it was above that (5.6.28-1) furthermore, I also had php-cli installed,... 
2. There was a notification about the "update" folder that needed me to change permissions (chmod), however, I was unable to find the folder in any possible way.. so after giving everything with the word "update" in it those permissions, I reverted back the permissions because that didn't work.

How I solved this? A bit of a dirty way, went into the code and removed the "if clauses" for those 2 issues in the install.php file. (I'm sorry, got desperate lol).

So after that, I got to the next steps, and was able to setup the db (step 2/3), but then on step 3. ("Configurate Webinterface") I just got a blank page.. 

I've checked the sql tables manually and they are empty, although there is no problem with the permissions in SQL.. I even tried inserting some username and password in the config column, and logging into the webinterface admin panel that way, but without success.. 

Any ideas on what I'm doing wrong here? I hope this was explained well enough.. Thanks for everything.

**Comment by Shad86** [comment]
Hello,

if you really got that your php version is to low, then there is another lower php version on your system.

sometimes it is helpful to create an phpinfo.php file on your webspace with:

`<?php
phpinfo();
?>`

and then check about that case.

If you really cant get rid of the second php version you can try it with the new phpfile under "other" called "phpcommand.php"

I think with that inforamtion you should get it to work.

regards

Shad86

**Comment by JoniVR** [comment]
Thanks a lot for your great response!

So, I did manage to fix the php issue.
I think you were right about running 2 versions, it's just one now (5.6.28-1).
Now, I still have the same problem I think, only just a little bit different..
I re-downloaded the entire folder, just to get a clean start, (did all the permissions, got php error to go away,...)
Still had the notification about the "update" folder not having the right permissions 
(since I'm unable to find it I can't really change it) but I got around that as I did before, by removing the "if clause" in install.php .

Now the big issue here still persists, when I ran install.php in the browser, I used to get through the first 2 steps and get a bank page at step 3. (Configurate Webinterface, does actually load css file I think, background is gray and language button is there, etc etc..) the big difference now is that I already get the problem at step 2. (Create Webinterface-User) does this have anything to do with some other permissions on files? I'm not really sure what I'm missing here..

**Comment by Shad86** [comment]
Hm i checked the links and it seems you'r right on github version this folder is missing but on the ts-n.net site its there:

http://ts-n.net/downloads/ranksystem_1.2.0.zip

I Hope this will help you finally get it to work

**Comment by JoniVR** [comment]
No problem, glad that's sorted out then! Hope that helps other people too then :) 
Still have the issue of not having the page on the 2nd step of install.sh show up, but I'll look into it some more myself too. Thanks a lot! :)

**Comment by JoniVR** [comment]
So, still haven't been able to fix the problem, been trying all kinds of things. :(
I just downloaded the entire thing again, set permissions, did not modify any files in this test. 
Also tried multiple browsers (to test), checked sql permissions, ...

So here are some screens about what happens when I enter dbname and dbpass in step 1. it goes to step 2., but doesn't show anything, also, the database is not created in mysql.   

**Thanks a lot for everything so far. :)**

![step 1](https://cloud.githubusercontent.com/assets/7591717/20794694/ceb8084e-b7cd-11e6-97d2-ac6775705335.jpeg)
![step 2](https://cloud.githubusercontent.com/assets/7591717/20794693/ceb69b08-b7cd-11e6-9f8e-ddb7125b3350.jpeg)
![db](https://cloud.githubusercontent.com/assets/7591717/20794692/ce9e4314-b7cd-11e6-97e3-207a1fb3c826.jpeg)

**Comment by JoniVR** [comment]
So after debugging in the browser, I noticed that 3 files where missing:

![bugs](https://cloud.githubusercontent.com/assets/7591717/20795519/de874fce-b7d1-11e6-9734-656910c65084.jpeg)

Could this have anything to do with it? If I go look for the files in the directory, they don't seem to be present or are they named differently?

Hope this helps you too haha spent a lot of time trying to figure out why it's not working. :)

**Comment by Shad86** [comment]
Hello,

on your picture i see you database should be named tsn_ranksystem but in your database picture there is no such database.

that would at least explain why it looks like nothing got wrote into the database.

Just to be sure.

The mysql or mariadb infos you enter are already existent!

"Step 1. Install database" -> asks which database he should use.

regards

Shad86

**Comment by JoniVR** [comment]
I know about that, I did enter it, that's what I mean. 
When I enter the credentials, and fill in everything, then click "install database", it goes on to the second step, but does not actually create that database, also just shows me a blank page. :(

I also tried creating the database itself already beforehand, but that doesn't help either.

**Comment by Shad86** [comment]
maybe you have an issue with resolving or its disabled in the mysql config - so maybe try 127.0.0.1 instead of localhost.

regards

Shad86

**Comment by JoniVR** [comment]
Doesn't seem to be the solution, tried this before too haha :) I did some more debugging in browser and noticed that the POST doesn't seem to get a full response from the server when I click on "install database" in the first step.. I get an 500 Internal Server error on the install.php file, doesn't seem to load the entire file. It's not something with permissions, pretty sure I configured those right.. Unless I'm missing something.. 

![issue](https://cloud.githubusercontent.com/assets/7591717/20829348/faaa79c4-b87b-11e6-99c3-e250ad0be76e.jpeg)

![issue2](https://cloud.githubusercontent.com/assets/7591717/20829498/97830d1a-b87c-11e6-89bb-b3134d868b2b.jpeg)

**Comment by Newcomer1989** [comment]
Please check, your database user has the permissions to create the database.

If nothing helps you can try to set full permissions:
grant all privileges on ts3_ranksystem.* to '_database_user_'@'localhost';

**Comment by Newcomer1989** [comment]
Are you using the italian translation?

**Comment by JoniVR** [comment]
no translation being used, I don't think database permissions should be the problem either, been testing as mysql root user, didn't work, also tested creating a database manually, works too. And I'm not using any translation, just default.. I'm really out of ideas, will try a clean install again later, grant all privileges.
Again, thanks for investing your time here, hope it can be solved, really would like to try this out :)

**Comment by Newcomer1989** [comment]
I can offer you to help you via a remote session.

For this please join our public TS3 server (address: ts-n.net).

Search there for Newcomer1989 or Shad86.

**Comment by JoniVR** [comment]
Hi, thanks for offering the help, I had a pretty busy weekend and didn't really have the time.. So I figured out in the browser debugger that when I click the "install database" button on the first step, it gave me a 500 internal server error in the debugger, so I enabled 'display_errors' in php.ini, and now I'm getting the following error message: 

![issue](https://cloud.githubusercontent.com/assets/7591717/20922173/75cfe20a-bba7-11e6-9bce-4c6b000e2049.jpeg)

Any idea on how to fix this? As always thanks for your help here :)

**Comment by Shad86** [comment]
Pls make sure that you:

1. have PDO installed / available
2. that you choose the right Sql database (so in your case make sure that you really use mysql)

regards

Shad86

**Comment by JoniVR** [comment]
You were right! PDO for myqsl was not installed yet! 
Fixed it with apt-get install php5-mysql!

Thanks a lot, very happy now!! :)
