### ISSUE TITLE
Issue bot not connecting to Teamspeak

### ISSUE THREAD

**Issue by JoniVR** [Newcomer1989/TSN-Ranksystem#194]
Hi, 

I almost have everything set up, however, I ran into a small issue.

The bot didn't seem to be able to start, I tried several ways, checked all plugins again,....
Today I somehow managed to get the log to show up, which really helped me pinpoint the problem, it has something to do with the permissions, I did set them up as described (I think).

Screenshots: 

![naamloos](https://cloud.githubusercontent.com/assets/7591717/20959995/5bdea0ea-bc5e-11e6-8753-f2eeef534db6.jpeg)

![naamloos2](https://cloud.githubusercontent.com/assets/7591717/20959997/5e0eb7d8-bc5e-11e6-8cbe-8b51fd3f31c6.jpeg)

**Comment by JoniVR** [comment]
So, I did get it to work by using the "sudo php bot.php" but I can't seem to launch it when I use the "worker.php".. Any ideas on what I could be doing wrong?

Thanks again :)

**Comment by Shad86** [comment]
try it with

cd /var/www

then

chown www-data:www-data ranksystem/ -Rf

after that check again if it works with the worker.php

if its again not writeable check the rights on the specific folders

regards

Shad86

**Comment by majoess** [comment]
Try 
`chown www-data:www-data /var/www/ranksystem`
or
`chmod 0755 /var/www/ranksystem/*`

**Comment by JoniVR** [comment]
Doesn't seem to work, I've checked all the permissions, I don't think they are the problem.. It does work when I execute the bot.php file, but it stops working after some time.. 

If I try to launch using the worker.php (I've tried many ways of launching it lol), it just fails instantly.
So I just get:

Starting the Ranksystem Bot. [Failed]

Nothing gets written in the logs, the logs only change when I run bot.php

Any other ideas?
Thanks a lot for the suggestions btw, appreciate :)

**Comment by JoniVR** [comment]
Fixed it! Had to modify a line in phpcommand.php! Thanks for the help guys :)

**Comment by Newcomer1989** [comment]
> So, I did get it to work by using the "sudo php bot.php" but I can't seem to launch it when I use the "worker.php".. Any ideas on what I could be doing wrong?

Please do not run the command with root permission! You can use sudo, but then in this way -> `sudo -u www-data worker.php start`.

**Comment by JoniVR** [comment]
Yes I know haha that was just the only way to get it working before, I'm using the proper way now ;) Thanks again :)
