### ISSUE TITLE
A lot of Errors

### ISSUE THREAD

**Issue by SupremeJoker** [Newcomer1989/TSN-Ranksystem#195]
Why do I get so much errors ?

ERROR     Fehler 0: invalid reply from the server
ERROR     update_groups 10:1
ERROR     update_groups 2:0: Error while getting servergrouplist: connection to server '  ' lost
ERROR     update_groups 1:0: Error while getting servergrouplist: connection to server '   ' lost
ERROR     get_avatars 1:3331: Error while getting avatarlist: flood ban

**Comment by Shad86** [comment]
> ERROR get_avatars 1:3331: Error while getting avatarlist: flood ban

The Ip of the ranksystem has to be whitelisted on the TS3-Server (in the TS3-Server Folder is a file called "Query_IP_Whitelist.txt)

If that isnt possible go to the webinterface and under "Teamspeak" set slowmode on "High delay"

regards

Shad86

**Comment by Shad86** [comment]
Since you have not responded to it, I assume that all is ok now.

*closed*
