### ISSUE TITLE
php

### ISSUE THREAD

**Issue by kecinotrab** [Newcomer1989/TSN-Ranksystem#196]
Hey, i have problem with new relase of ranksystem. It's says: 

> PHP cURL is needed but seems not available. Install PHP cURL and try it again!
> PHP Zip is needed but seems not available. Install PHP Zip and try it again!

i search something on google but it doesn't work, so i write here. Here is my server:

Ubuntu 16.04.1 LTS (GNU/Linux 4.4.0-47-generic x86_64)

thanks for help.

**Comment by mightyBroccoli** [comment]
could you tell which php extensions you have installed?
`dpkg --get-selection php*`

**Comment by kecinotrab** [comment]
`root@251-248-203-89:~# dpkg -l | grep 'ii  php5\?-'
ii  php-common                         1:35ubuntu6                     all          Common files for PHP packages
ii  php-gd                             1:7.0+35ubuntu6                 all          GD module for PHP [default]
ii  php-gettext                        1.0.11-2build1                  all          read gettext MO files directly, without requiring anything other than PHP
ii  php-mbstring                       1:7.0+35ubuntu6                 all          MBSTRING module for PHP [default]
ii  php-mcrypt                         1:7.0+35ubuntu6                 all          libmcrypt module for PHP [default]
ii  php-mysql                          1:7.0+35ubuntu6                 all          MySQL module for PHP [default]
ii  php-pear                           1:1.10.1+submodules+notgz-6     all          PEAR Base System
ii  php-phpseclib                      2.0.1-1build1                   all          implementations of an arbitrary-precision integer arithmetic library
ii  php-tcpdf                          6.0.093+dfsg-1ubuntu1           all          PHP class for generating PDF files on-the-fly
ii  php-xml                            1:7.0+35ubuntu6                 all          DOM, SimpleXML, WDDX, XML, and XSL module for PHP [default]
root@251-248-203-89:~# dpkg -l | grep 'ii  php\?-'
ii  php-common                         1:35ubuntu6                     all          Common files for PHP packages
ii  php-gd                             1:7.0+35ubuntu6                 all          GD module for PHP [default]
ii  php-gettext                        1.0.11-2build1                  all          read gettext MO files directly, without requiring anything other than PHP
ii  php-mbstring                       1:7.0+35ubuntu6                 all          MBSTRING module for PHP [default]
ii  php-mcrypt                         1:7.0+35ubuntu6                 all          libmcrypt module for PHP [default]
ii  php-mysql                          1:7.0+35ubuntu6                 all          MySQL module for PHP [default]
ii  php-pear                           1:1.10.1+submodules+notgz-6     all          PEAR Base System
ii  php-phpseclib                      2.0.1-1build1                   all          implementations of an arbitrary-precision integer arithmetic library
ii  php-tcpdf                          6.0.093+dfsg-1ubuntu1           all          PHP class for generating PDF files on-the-fly
ii  php-xml                            1:7.0+35ubuntu6                 all          DOM, SimpleXML, WDDX, XML, and XSL module for PHP [default]
`

u can check this: http://ts3.hwns.pl/php.php

**Comment by kecinotrab** [comment]
http://pastebin.com/Rp6XGnA7
http://ts3.hwns.pl/php.php

**Comment by Shad86** [comment]
sudo apt-get install php7.0-curl
and
sudo apt-get install php7.0-zip

**Comment by kecinotrab** [comment]
Thank you so much.
