### ISSUE TITLE
[1.2.0/1] /stats/my_stats.php Undefined variable: nextgrp

### ISSUE THREAD

**Issue by bykidi** [Newcomer1989/TSN-Ranksystem#198]
Notice: Undefined variable: nextgrp in /path/to/ranksystem/stats/my_stats.php on line 38
Notice: Undefined variable: nextgrp in path/to/ranksystem/stats/my_stats.php on line 41

![default](https://cloud.githubusercontent.com/assets/1337953/21288856/3394b7ac-c49f-11e6-95c7-c2ab36d1f65e.png)

PHP 7.0.14-2+deb.sury.org xenial+1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.14-2+deb.sury.org~xenial+1, Copyright (c) 1999-2016, by Zend Technologies

**Comment by majoess** [comment]
The problem?

**Comment by bykidi** [comment]
@majoess The problem.

**Comment by bykidi** [comment]
bumping, since this git seems to feel like lost

**Comment by Newcomer1989** [comment]
I will have a look on it, if I have the time.. it is not lost, so long it is open

**Comment by Newcomer1989** [comment]
fixed with release 1.2.2
