### ISSUE TITLE
Ausgeschlossene Gruppen / Clients

### ISSUE THREAD

**Issue by monster010** [Newcomer1989/TSN-Ranksystem#199]
moin,

es wäre toll, wenn ausgeschlossene Clients auch nicht in der Datenbank aufgeführt werden.

mfg
monster010

**Comment by Shad86** [comment]
Das Problem hierbei ist das es auch eine Pausieren Funktion beim ausschließen gibt, wo es wiederum notwendig ist den User in der Datenbank abzulegen.

Auch wäre gut zu wissen welchen Nutzen du dir daraus erhoffst das ausgeschlossene Nutzer/ Gruppen nicht in der Datenbank gelistet werden.

Denn irgendwo muss ich ja dem Ranksystem sagen welche Nutzer er ignorieren soll - ergo müssen diese in irgendeiner Weiße gelistet sein.

**Comment by monster010** [comment]
> Denn irgendwo muss ich ja dem Ranksystem sagen können welche Nutzer er ignorieren soll - ergo müssen diese in irgendeiner Weiße gelistet sein.

Das Ergo gib keinen richtigen Sinn in meinen Augen, klar muss ich dem Ranksystem sagen welche Nutzer es ignorieren soll, aber d.h. nich das sie in der Datenbank stehen müssen, außer in der Config.

Eventuell hab ich mich auch falsch ausgedrückt, ich hätte eher schreiben sollen "es wäre toll, wenn ausgeschlossene Clients nicht in der Rank-Liste auftauchen, bzw. das man dies einstellen kann.", dann is nämlich auch das Problem mit der Pausieren Funktion nicht gegeben.

**Comment by Newcomer1989** [comment]
> dann is nämlich auch das Problem mit der Pausieren Funktion nicht gegeben.

Welches Problem du bei der Funktion siehst, erschließt sich mir durch die bloße Erwähnung dessen nicht. Die Pausieren Funktion ist von einigen Usern explizit gewünscht. Sei es z.B. für eine Strafgruppe, welche für den Zeitpunkt des Innehabens dieser Gruppe keine Zeiten wertet. Fehler/Probleme hierbei sind nicht bekannt.

> "es wäre toll, wenn ausgeschlossene Clients nicht in der Rank-Liste auftauchen

Das ist bereits möglich. Im Webinterface über die "Statistik Seite" gibt es eine Option "ausgeschl. Clients". Ohne eine nähere Beschreibung, was genau du bezwecken möchtest, ist es aber natürlich schwer einzuschätzen, ob das wirklich genau das ist, was du auch suchst.

Wir können dir nur soweit helfen, wie du uns auch Input lieferst.
