### ISSUE TITLE
Reaching max level keep adding max level

### ISSUE THREAD

**Issue by Sqveeze** [Newcomer1989/TSN-Ranksystem#2]
Hello,

Using this rank system since a long time, its really amazing, can't wait for the next version, however the first user was just reached the max level on my server and just noticed that user keep getting the lv 100 rank removed and added each time the cron job runs. Just fixed it with a temporary 31 million year rank, that user never can reach, but then in the list_rankup the "max rank reached" gone.

Any quick fix for this?

**Comment by Newcomer1989** [comment]
> and just noticed that user keep getting the lv 100 rank removed and added** each time **the cron job run
How is it possible that he get removed one servergroup twice a time? You give the lvl 100 rank manually to the user?

How looks your configuration "rank up"? Please post it here.

The last level (highest rank) is tested and works fine in the test scenarios. And I also see it runs correctly on other server.

**Comment by Sqveeze** [comment]
60=>76,300=>7,600=>77,900=>78,1200=>79,1600=>80,2000=>81,2800=>82,3600=>87,5400=>88,7200=>83,10800=>84,14400=>85,18000=>86,21600=>89,25200=>90,28800=>91,32400=>92,36000=>93,54000=>94,72000=>95,90000=>96,108000=>97,126000=>98,144000=>99,162000=>100,180000=>101,198000=>102,216000=>103,234000=>104,252000=>105,270000=>106,288000=>107,306000=>108,324000=>109,342000=>110,360000=>111,378000=>112,396000=>113,414000=>114,432000=>115,468000=>116,504000=>117,540000=>118,576000=>119,612000=>120,648000=>121,684000=>122,720000=>123,756000=>201,792000=>202,828000=>203,864000=>204,900000=>205,936000=>206,972000=>207,1008000=>208,1044000=>209,1080000=>210,1116000=>211,1152000=>212,1188000=>213,1224000=>214,1260000=>215,1296000=>216,1332000=>217,1368000=>218,1404000=>219,1440000=>220,1476000=>221,1512000=>222,1548000=>223,1584000=>224,1620000=>225,1656000=>226,1692000=>227,1728000=>228,1764000=>229,1800000=>230,1836000=>231,1872000=>232,1908000=>233,1944000=>234,1980000=>235,2016000=>236,2052000=>237,2088000=>238,2124000=>239,2160000=>240,2196000=>241,2232000=>242,2268000=>243,2304000=>244,2340000=>245,2376000=>246,2412000=>247,2448000=>248,2484000=>249,2520000=>250

**Comment by Newcomer1989** [comment]
that are only 99 rows.. so you have 99 ranks? I ask, cause you tell something about rank 100.

**Comment by Sqveeze** [comment]
Yes the lv 1 is the default group that the server assign you when you first connect

**Comment by Newcomer1989** [comment]
Ok, the config looks fine.
Can you answer the other question?

-> How is it possible that he get removed one servergroup twice a time? You give the lvl 100 rank manually to the user?

**Comment by Sqveeze** [comment]
No i didn't. he was spend that 28 day on the server and reached the max level, and then this happened

**Comment by Newcomer1989** [comment]
Ok, but then its only possible to remove the servergroup once a time.. Not with each cronjob. Removed is removed ;-)

Try to use the posted configuration. Then remove all ranked groups from the concerned user (manual on ts3 server). Wait for next cronjob and look what happens.

**Comment by Sqveeze** [comment]
<18:12:51> "User" was removed from server group "LV100" by "Şqveeze ツ".
<18:12:59> "User" was added to server group "LV100" by "GeTraNk!".

1min later

<18:13:59> "User" was removed from server group "LV100" by "GeTraNk!".
<18:13:59> "User" was added to server group "LV100" by "GeTraNk!".

**Comment by Newcomer1989** [comment]
How looks the row for this user on the database, table "user"?

**Comment by Sqveeze** [comment]
uuid	cldbid	count	ip	name	lastseen	grpid	nextup	idle	cldgroup	online
zfjBt6FLYyGsqQM4o5P0X31an1c= 3305 2590794 1409460406 User 1455471661 250 0 901530 32,71,250,273 1

**Comment by Newcomer1989** [comment]
ok, its noticed. I will test this situation with the next release version and fix a possible problem.

**Comment by Sqveeze** [comment]
Thanks, any ETA when the next version come? Or its forbidden to ask that? Will it contain the "Boost" feature mentioned on the website?

**Comment by Newcomer1989** [comment]
No, sorry there is no precise ETA for the moment. But if the update-check is enabled, you get informed^^
And yes, the boost feature will be contained in the next release.

**Comment by Sqveeze** [comment]
Alright, thanks!

**Comment by Newcomer1989** [comment]
Ok tested your problem with following options under version 1.00 (still not released).
config for rankup: 300=>4172,400=>4173,450=>4174
4172 = rank1
4173 = rank2
4174 = rank3

rank3 is the last group (see config above).

**Comment by Sqveeze** [comment]
Looks like this bug is only at me or you fixed it in 1.00 while you didn't knew this is exist.
Still can't wait for 1.00, hope you will release it soon!
