### ISSUE TITLE
 !!!! Logs folder is not writable !!!!

### ISSUE THREAD

**Issue by okanozdemir** [Newcomer1989/TSN-Ranksystem#200]
![logs](https://cloud.githubusercontent.com/assets/6042324/21376171/84be9a00-c73b-11e6-9c5b-614b2b64abfa.jpg)

I moved the files to another folder and bot isn't working.
Folder-> "**/var/www/ranksystem.blabla.com/public_html**"
Owner-> "**www-data**"
chmod(avatars,logs,icons)-> **777**
start command -> "**sudo -u www-data php /var/www/ranksystem.blabla.com/public_html/worker.php start**"

PHP info:
![php](https://cloud.githubusercontent.com/assets/6042324/21376174/89d91218-c73b-11e6-9d3d-6944f7f3816b.jpg)
System info:
![system](https://cloud.githubusercontent.com/assets/6042324/21376257/3b393434-c73c-11e6-8793-b395a32779fd.png)
Apache info:
![apache](https://cloud.githubusercontent.com/assets/6042324/21376280/6b1898ca-c73c-11e6-8a6c-ae4ce3a1a99f.png)

**Comment by Shad86** [comment]
take a look into your webinterface under "other" and make sure the path to your logs folder is correct

regards

Shad86

**Comment by okanozdemir** [comment]
You're right, I forgot about it. 

I recreated the old path for to run it and I entered the new path.

Thank you @Shad86.
