### ISSUE TITLE
Possible some small translation errors

### ISSUE THREAD

**Issue by Pepreal** [Newcomer1989/TSN-Ranksystem#201]
Channel exception help

>Stay users in one of the listed channels, the time there will be completely ignored. There is neither the online time, yet the idle time counted. 
Sense does this function only with the mode 'online time', cause here could be ignored AFK channels for example.

Think sense should be hence

> Be a user in an excluded channel, it is noted for this period as 'excluded from the Ranksystem'. The user dows no longer appears in the list 'stats/list_rankup.php' unless excluded clients should not be displayed there (Stats Page - excepted client). 

think dows should be does

**Comment by Newcomer1989** [comment]
thx, I noted it.. Will be correct with the next release 1.2.2.

**Comment by Pepreal** [comment]
Oke np
