### ISSUE TITLE
Problem mit Anmeldung

### ISSUE THREAD

**Issue by tobipunkt** [Newcomer1989/TSN-Ranksystem#202]
Nach erfolgreicher Verbindung mit der Datenbank, erstellte ich einen Test-Benutzeraccount mit den Anmeldedaten "admin"+"password".  Nach der Anmeldung mit den Benutzerdaten erhielt ich wieder das Anmeldefenster. Die Daten sind zu 100% korrekt. Wie komme ich ins Interface?

[Hier](http://puu.sh/sXC0Z/0754219c3f.gif) dazu ein GIF.

**Comment by Newcomer1989** [comment]
Du müsstet deine TS3 unique ID in die Datenbank per SQL Befehl übernehmen.

`UPDATE config set adminuuid='_your_ts3_unique_ID_';`

Danach kannst du dein Passwort über die Reset Funktion zurücksetzen.

**Comment by Shad86** [comment]
tobi kam heute noch auf das teamspeak und wir haben festgestellt, das er momentan noch auf einer älteren version hängt, nach einem update haben wir dann oben genannten Vorschlag umgesetzt und alles hat funktioniert.
