### ISSUE TITLE
Icon folder conflicts with Apache.

### ISSUE THREAD

**Issue by Tune389** [Newcomer1989/TSN-Ranksystem#203]
I installed the ranking system on a "subdomain" root folder. The Icons blocked by default (https://www.electrictoolbox.com/apache-icons-directory/). You should move the resources (avatars/logs/icons) to a seperate folder. Maybe: storage/icons. Another advantage - you have only a single "project" folder with 777 rights (subfolders autogenerated?).

**Comment by Shad86** [comment]
Fixed in the Experimental -> 

Info (whats in there): https://github.com/Newcomer1989/TSN-Ranksystem/issues/273

Download: https://github.com/Newcomer1989/TSN-Ranksystem/tree/Experimental
