### ISSUE TITLE
Ranksystem beendet sich ohne Fehler/Hinweis - Webhost

### ISSUE THREAD

**Issue by Viper830** [Newcomer1989/TSN-Ranksystem#204]
Ich habe momentan das Problem das das System bei mir einfach nach einer Zeit keine Ränge mehr vergibt und wenn ich dann in die Liste schaue wo die nächsten Rankups stehen steht da das ich nicht verbunden bin egal ob ich aufm TS bin oder nicht. Momentan behebe ich den Fehler indem ich den Bot neustarte und nachach oben rechts auf aktualisieren gehe aber ich glaube so is das nicht ganz richtig

**Comment by Shad86** [comment]
Welche Version des Ranksystems nutzt du?

Welche Betriebsystem nutzt du? Linux oder Windows?

Mit freundlichen Grüßen

Shad86

**Comment by Newcomer1989** [comment]
Hast du denn Schritt 4 der Installation beachtet?
https://ts-n.net/ranksystem.php#install

Ansonsten ist natürlich die Frage, warum das Ranksystem sich beendet. Hier bitte mal die ranksystem.log beachten und ggfs. hier posten.

**Comment by Viper830** [comment]
Schritt 4 hab ich warscheinlich übersehen aber in der Log steht nichts die hört dann einfach auf bis ich den Bot neustarte

**Comment by Newcomer1989** [comment]
Wie lange läuft der Bot denn, bevor er sich beendet?

**Comment by Viper830** [comment]
Da nichts in der Log steht bemerke ich das nur wenn ich direkt nachschaue aber meistens nach 2 / 3 Stunden

**Comment by Newcomer1989** [comment]
Dann vielleicht den Bot mal wie folgt beschrieben in der Shell starten und dort beobachten.

https://github.com/Newcomer1989/TSN-Ranksystem/issues/169#issuecomment-259252675

Er sollte dann vermutlich mit einem Fehler beendet werden, den er direkt in der Shell ausgibt.

**Comment by Viper830** [comment]
Jetzt hab ich leider mein übliches Problem wieder das ich keinen Zugriff auf irgendwelche sachen die irgendwas direkt auf dem Server ausführen habe

**Comment by Viper830** [comment]
bis auf Plesk webinterface und FTP

**Comment by Newcomer1989** [comment]
Dann kann aber auch das die Ursache sein. Bist du bei einem Hoster? Evtl. beendet dieser automatisiert den  Prozess.

Falls du bei einem Hoster bist bitte auch unbedingt den Slowmode einschalten (Webinterface - TeamSpeak).

**Comment by Viper830** [comment]
Also wegen whitelist aufm teamspeak dürfte ich keine Probleme haben da haben sie mich eingetragen aber ich stell mal Testweise um

**Comment by Newcomer1989** [comment]
beantwortet aber leider nicht meine Frage.. Bist du bei einem Webhoster oder hast du einen eigenen V-Server, auf dem du selbst Plesk eingerichtet hast?

**Comment by Viper830** [comment]
Ich bin bei einem Hoster

**Comment by Newcomer1989** [comment]
Dann bitte auf jeden Fall den Slowmode aktivieren. Wie bereits erwähnt, beendet der Hoster den Prozess evtl, da er zu viel CPU Zeit benötigt.

**Comment by Viper830** [comment]
Hab ich gerade gemacht ich werde mich nochmal melden ob das Problem weiterhin besteht

**Comment by Newcomer1989** [comment]
Ansonsten sollte zumindest der Cronjob helfen, dass das Ranksystem wieder neu gestartet wird.

Ist das alles nichts, kann ich nur die Hosted Variante empfehlen.

**Comment by Viper830** [comment]
Ich hab gerade beim Anbieter mal ein Ticket geschrieben wegen dem Cronjob da ich den anscheinend nicht selber machen kann, ich hoffe die machen das ansonsten werde ich darauf zurückkommen

**Comment by Viper830** [comment]
bis jetzt hab ich keine weiten Probleme mehr

**Comment by Newcomer1989** [comment]
Ich gehe dann mal davon aus, das der Slowmode geholfen hat um die CPU Zeit zu reduzieren und damit das Ranksystem nicht mehr von deinem Hoster beendet wird.
Endgültig kann diese Fragestellung natürlich nur dein Hoster beantworten.

Ich sehe den Issue damit als geschlossen. Wenn er sich immer wieder beendet, besteht wie gesagt die Möglichkeit des Hostings unsererseits.
Sollten weitere Probleme auftreten bitte einen neuen öffnen.

**Comment by Viper830** [comment]
Der Bot hat sich wieder beendet diesesmal mit ner Fehlermeldung 2017-01-01 18:27:01.097883 ERROR Error 1024: invalid serverID ich hab aber nichts irgendwie umgestellt
