### ISSUE TITLE
ERROR get_avatars 2:0:

### ISSUE THREAD

**Issue by IMmmKI** [Newcomer1989/TSN-Ranksystem#206]
Hi, 

I see this error in our logs: 

ERROR     get_avatars 2:0: Error while downloading avatar: incomplete file download (0 of xxx bytes).

What does this mean? 
I can attach the whole log if needed. 

Thanks!!

**Comment by Newcomer1989** [comment]
That is problem during getting the avatar from the ts3 server.

It happens once a time or you get this often times? When you get it often times, it is every time on the same icon(s)?

**Comment by IMmmKI** [comment]
Here we go. It seems to happen most times. ``
[ranksystem (2).txt](https://github.com/Newcomer1989/TSN-Ranksystem/files/678734/ranksystem.2.txt)

**Comment by Newcomer1989** [comment]
It seems to be the same avatar.. perhaps it is a bot, which is changing the avatar continuously.

I think the problem could be here, the Ranksystem tries to download there avatar file before the avatar was uploaded full from the other bot.
With the next version there comes an function to delay the avatar download. I think this will solve your problem. Please wait for the next release and have a look, if it is then still there..

**Comment by IMmmKI** [comment]
Thank you so much.  I do have 6 music bots on my server.  I am guessing that is what it's picking up.

Can't wait and thanks for all your hard work.  Definitely will donate!!

On 30 Dec 2016 19:50, Newcomer1989 <notifications@github.com> wrote:

It seems to be the same avatar.. perhaps it is a bot, which is changing the avatar continuously.

I think the problem could be here, the Ranksystem tries to download there avatar file before the avatar was uploaded full from the other bot.
With the next version there comes an function to delay the avatar download. I think this will solve your problem. Please wait for the next release and have a look, if it is then still there..

**Comment by Newcomer1989** [comment]
release 1.2.2 is out now
