### ISSUE TITLE
The Bot picks up the wrong php version

### ISSUE THREAD

**Issue by Joele25** [Newcomer1989/TSN-Ranksystem#208]
Hi every body.
My server was running the 5.3.3 version of PHP. I did install 5.5 and 7.0 and enable the 5.5 in the plesk panel for my domain. The setup pannel start working fine but the script keep find the old version.
How Can I resolve this?

Screen here: http://i.imgur.com/Pg4hboA.png
2016-12-30 19:49:39.450655   CRITICAL  Your PHP version (5.3.3) is below 5.5.0. Update of PHP needed! Shuttin down!

**Comment by Joele25** [comment]
Even If I do this
http://i.imgur.com/ile5Ahg.png

**Comment by Shad86** [comment]
If you use the latest Version take a look in the folder "other" -> "phpcommand.php" this should help you.

regards

Shad86

**Comment by Joele25** [comment]
Thx. Changed from "$phpcommand = "php";" to "$phpcommand = "/opt/plesk/php/5.5/bin/php";"

Now It work again <3
