### ISSUE TITLE
Auto reconnect

### ISSUE THREAD

**Issue by IMmmKI** [Newcomer1989/TSN-Ranksystem#209]
Hi, 

Would you be able to add a auto reconnect for the bot as sometimes it loses connection and I need to manually restart it and connect it.

**Comment by eNNercY1337** [comment]
i think if you have installed the cronjob it does that already, correct me if i'm wrong.
otherwise you could've simply re-form the cronjob to restart the bot all x minutes.

`*/10 * * * * sudo -u www-data php /path/to/your/websever/path/to/Ranksystem/worker.php check >/dev/null 2>&1`

**Comment by IMmmKI** [comment]
@eNNercY1337 Thank you so much!!

**Comment by eNNercY1337** [comment]
cheers buddy 😄
