### ISSUE TITLE
Der Bot Beendet sich wieder

### ISSUE THREAD

**Issue by Viper830** [Newcomer1989/TSN-Ranksystem#210]
Der Bot hat sich wieder beendet diesesmal mit ner Fehlermeldung 2017-01-01 18:27:01.097883 ERROR Error 1024: invalid serverID ich hab aber nichts irgendwie umgestellt nach dem neustart verbindet er wieder

**Comment by Viper830** [comment]
Ist Webhoster ich hatte ja letztens deswegen schon ein Ticket geöffnet und das einzigste was in der Log steht ist die Fehlermeldung oben das System ist Linux und die Version ist 1.2.1

**Comment by Viper830** [comment]
Ich hab gerade nochmal nachgefragt ob sie ihn angelegt haben (Support), ich weis nicht genau wie oft es kommt da die Error Meldung das erste mal dasteht vorher hab ich das immer dann gemerkt wenn ich die rankup liste geöffnet habe und oben rechts steht das es nicht verbunden ist

**Comment by Shad86** [comment]
Müsste sich @Newcomer1989 Newcomer vermutlich mal anschauen, was aber schwierig wird, das es ein Webhoster ist :/ - wir hatten so einen Fehler bisher nur einmal reported bekommen im Issue #107 leider nie eine Info bekommen.

Ansonsten, wäre die einzige Lösung das du es von newcomer gehostet bekommen könntest

**Comment by Viper830** [comment]
Ich hoffe wenns bei mir das gleiche ist das ich dann weiterhelfen kann

**Comment by Viper830** [comment]
Momentan beendet er sich wieder ohne Meldung aber schon nach so 10 Minuten

**Comment by eNNercY1337** [comment]
Problem dann mit deinem Hoster.
Bei mir läuft es mit und ohne Plesk ohne Probleme.

**Comment by Viper830** [comment]
Ich weis nurnicht warum am Anfang lief alles normal und irgendwann hat das Angefangen weder bei einer änderung von mir noch vom Hoster

**Comment by eNNercY1337** [comment]
Womöglich hat dein Host festgestellt dass das Skript massiv CPU Leistung zieht. (mal davon abgesehen ist die Realisierung des Bots via PHP Skript sowieso ineffizient und eine große Sicherheitslücke - hoffe das da mal n Update kommt auf Python/Node.js Basis oder dergleichen)

Entweder du holst dir einen eigenen V-Server oder du kannst das Ranksystem nicht nutzen bzw. nur eingeschränkt.

Kann auch verursacht werden wenn div. Dienste automatisiert neugestartet werden/geupdated werden durch deinen Hoster.

**Comment by Shad86** [comment]
Hallo,

@eNNercY1337 
wenn du Sicherheitslücken gefunden hast, dann wäre es gut diese zu melden.

Ansonsten (wenn nicht) würde ich dich bitten von solchen Aussagen Abstand zu nehmen.

Bezüglich Ineffizienz, das ganze hier ist opensource, wenn du also eine effizientere Lösung hast und diese Umsetzen willst, und damit das Projekt unterstützen willst, kannst du dies gerne tun.

**Comment by Shad86** [comment]
@Viper830 hast du auch sicher gestellt, das der bot gewhitelisted ist (also die Ip vom Webserver)?

Das andere ist eben, schon wie gesagt reine Hostersache, augenscheinlich ändert der Hoster zwar nichts aber es müssen nur eben relevante background Dienste neugestartet werden und schon hast du eben eventuell ein Problem.
Viele Hoster haben dazu noch keinen Cronjob, was das "Dienste neustarten" Problem beheben würde.

(Ich selber habe mein Ranksystem auch am laufen und habe tatsächlich den Cronjob nie gebraucht, es sei denn es kam ein update - weshalb man ja so oder so seit den neueren Versionen einen Cron oder Task scheduler haben sollte - Siehe auch nochmals hier -> http://ts-n.net/ranksystem.php#requirements)

Das nächste ist eben das Hoster limitieren müssen, heißt Prozesse ab einer gewissen Leistungsgrenze eben gekillt werden, weil sonst könnte man den Webserver ja unendlich hoch belasten, was wirtschaftlich einfach nicht tragbar wäre für den webhoster.

Ich sage das zwar nur ungern aber zu sagen früher ging es doch auch, ist immer so eine Sache, wenn eben schon seit Anbeginn gewisse requirements nicht erfüllt werden können.

Nichtsdestotrotz, solltest du also weiterhin solche Probleme haben mit deinem Webhost empfehle ich dir entweder einen eigenen kleinen v-server anzumieten, oder dir das ganze von Newcomer hosten zu lassen.

Mit freundlichen Grüßen

Shad86

**Comment by Viper830** [comment]
Wie genau kann ich mir das denn Hosten lassen ich glaube das wäre in dem Fall die beste Lösung

**Comment by Shad86** [comment]
Entweder du versuchst es abends auf dem Teamspeak (Newcomer) oder du schreibst ihm per Kontaktformular:

http://ts-n.net/en/contact.php

**Comment by Viper830** [comment]
was genau ist mit "serverport or channelnumber" gemeint

**Comment by Viper830** [comment]
okay
