### ISSUE TITLE
Windows (Plesk) - Bot Startet nicht

### ISSUE THREAD

**Issue by Shadow329** [Newcomer1989/TSN-Ranksystem#211]
Hey Community,

Ich hab das Problem das der Bot weder Connectet noch startet. Wenn ich auch den Button "Bot Starten" klicke werd das Bild grau und weiter passiert nichts. 
Weder sehe ich im TS anhand von Aktuelle Queries das der Bot connectet ist noch im Webinterface wie gesagt das bild bleibt Grau. 

Habe schon andere Versionen des Bot´s probiert überall der gleiche Fehler, und über die direkte IP. (habe es sonst über die Domain probiert)

nun noch ein paar Infos die vielleicht helfen.
- Dedizierter Server
- Windows Server 2012
- PHP Version 5.5.38
- MySQL Datenbank Version 5.1.73

Habe das ganze Über Plesk laufen Version 12.5

hat jemand eine Idee worann das liegen kann ? Danke für eure hilfe und euren Support ;) 
wer keine Lust hat zu schreiben kann mich auch gerne auf meinem TS ansprechen http://www.teamspeak.com/invite/ts3.phoenix-force.de oder unter ts3.phoenix-force.de ich hoffe sowas ist erlaubt :D wenn nicht Sorry :D

Edit: 
Ich hab nochmal in den Logfiles geschaut leider habe ich keine bzw. wurden noch keine erstellt, also kann ich damit leider nicht dienen.

**Comment by Shad86** [comment]
Dazu müsstest du mal abends auf dem ts3 vorbeischauen und nach Newcomer ausschau halten.

Grade Windows und Plesk verursachen gerne Probleme.

MfG

Shad86

**Comment by Shadow329** [comment]
Dank Newcomer1989 Funktionert nun alles vielen Dank nochmal für deinen Super Support!

PS: kann ich hier keine 10 von 5 Sterne geben ? :D

**Comment by Newcomer1989** [comment]
Die Probleme wurden per Fernwartung gelöst. Nun funktioniert es in vollem Umfang und ohne Probleme.

1) Es waren aufgrund von Plesk mehrere PHP Versionen im Einsatz. Es musste in der `other/phpcommand.php` der genaue Pfad zur aktuellen PHP Version gesetzt werden.

2) In Plesk musste die aktuelle Version ausgewählt (unter "Websites & Domains" -> "PHP Einstellungen") und übernommen werden.

3) In der dann verwendeten PHP Version fehlte die COM extension. Bitte in der `php.ini` prüfen, ob `extension=php_com_dotnet.dll` auch aktiviert ist.

4) Dateizugriffe für das vollständige Webverzeichnis für das Ranksystem mussten **rekursiv** gesetzt werden (Rechtsklick auf das Verzeichnis - "Eigenschaften" -> "Freigabe" -> Button "Freigabe" dort den User suchen und auf Lesen und Schreiben setzen). Der User für Plesk fängt wohl an mit "IWPG_".

**Comment by Newcomer1989** [comment]
Dieser Thread wird nicht mehr benötigt, da alle relevanten Punkte für Windows nun hier zusammen getragen wurden:

https://github.com/Newcomer1989/TSN-Ranksystem/issues/369
