### ISSUE TITLE
The bot doesn't start

### ISSUE THREAD

**Issue by iRelease** [Newcomer1989/TSN-Ranksystem#213]
Hello! Sorry for my bad English,

I have install the bot in a webserver host by OVH.

I give all information but the bot doesn't start and there is no log files written, he just continue to load.

![image](https://cloud.githubusercontent.com/assets/15753514/21654494/0a7e5448-d2b6-11e6-9758-c8d1c03d1d41.png)

![image](https://cloud.githubusercontent.com/assets/15753514/21654549/3b70f5e2-d2b6-11e6-976f-3c0ff3340ba0.png)

Can u help me to start the bot please?

**Comment by Shad86** [comment]
Hello,

you made sure that you fulfill the requirements?

http://ts-n.net/ranksystem.php#requirements

best is to check it with an "phpinfo file"

Create a file that is called info.php

Put in:

<?php
phpinfo();
?>

save it and put it on your webserver so that you can acces the file and check if all things are available.

or ask you Hoster if you dont know how to check it.

regards

Shad86

**Comment by Newcomer1989** [comment]
Which system are you using? windows, linux? which release?

**Comment by iRelease** [comment]
I am using Windows but i don't know the system OVH use, the release 1.2.1

I create a php info:

http://ts.unskilled-gaming.fr/phpinfo.php

Can u check it, i think i have all the requirements

**Comment by Newcomer1989** [comment]
Have you had a look here?

https://github.com/Newcomer1989/TSN-Ranksystem/issues/211#issuecomment-270214623

**Comment by iRelease** [comment]
I'm not a pro, how i can install it on OVH?

**Comment by Newcomer1989** [comment]
You can enable the COM extension inside the php.ini (it is a config file for PHP) with entering this:
`extension=php_com_dotnet.dll`

Search inside the php.ini file for other extensions and place it in the near of them. Also be sure, you have the `ext/php_com_dotnet.dll` inside you PHP folder.

**Comment by iRelease** [comment]
I didn't have access to php.ini in the OVH Website, i can't  install it, another way to fix my problem?

**Comment by iRelease** [comment]
Ok i will try it, i  will give you the information tomorrow!

Thank you wery much!

**Comment by Newcomer1989** [comment]
If OVH can't help you, it is also possible to get the Ranksystem hosted for free.
If you are interested you need only to write us a short message about our contact form https://ts-n.net/en/contact.php

**Comment by iRelease** [comment]
Hello Newcomer1989, Shad86. 

It seems that the OVH website hosting servers are actually on Linux, so if I understand correctly I do not need the COM extension?

![image](https://cloud.githubusercontent.com/assets/15753514/21673907/9cc134e0-d32b-11e6-8717-eabccdfb91b8.png)

**Comment by Newcomer1989** [comment]
> It seems that the OVH website hosting servers are actually on Linux, so if I understand correctly I do not need the COM extension?

Yes, on linux you do not need the COM extension.

But the other requirements are still needed. Please check each of it. You have to be 100% sure, each of it are enabled..

**Comment by Shad86** [comment]
closed because user have now a hosted solution from ts-n.net
