### ISSUE TITLE
Logs file not writeable / Nav bar not showing

### ISSUE THREAD

**Issue by ryanmemer** [Newcomer1989/TSN-Ranksystem#214]
I have the correct log path selected on my web interface. In my case it is "/var/www/vhosts/serverofmanykeks.online/httpdocs/rank/logs/".

I have ran the command "chown -R somk /var/www/vhosts/serverofmanykeks.online/httpdocs/rank/" and then set chmod to 777 for icons, avatars and logs folders. 

The nav bar on the webpage is not there also, could this be because the worker.php is not running? I'm assuming so anyway. 

I am also getting "Array ( [0] => 42S22 [1] => 1054 [2] => Unknown column 'adminuuid' in 'field list' )" when I try to set the Admin ID.

All of these issues are from me updating the software. So this is the very latest version.

**Comment by ryanmemer** [comment]
Ok so the reason why I am having the log path not writable issue is because of the following:

- It is forcing me to set my Admin ID, of course because the column doesn't exist in the DB it is not posting an entry. 
- I cannot edit my logpath without specifying an Admin ID. So that is why I am having the Log path not writable issue when trying to launch the ranksystem.

Can you give me the SQL I would need to add this new column to the db so it's recognised by your system?

**Comment by ryanmemer** [comment]
Hard edited the database to change my old logpath to my current one. It now starts but it errors. Error in logs shown below.

2017-01-05 18:56:11.909881   CRITICAL  PHP Zip is missed. Installation of PHP Zip is needed! Shuttin down!

**Comment by Shad86** [comment]
then i recommend to activate zip or even install it on the system for php

see requirements:

http://ts-n.net/ranksystem.php#requirements

**Comment by ryanmemer** [comment]
Downloaded and fixed. Maybe you should not make it a requirement to provide the Admin ID unless you have the rank system successfully running. That would solve every problem I encountered above, surely?

Anyway, thanks for the help haha...

**Comment by Shad86** [comment]
from which Version did you updated the ranksystem Version x to version?

**Comment by Newcomer1989** [comment]
> I have ran the command "chown -R somk /var/www/vhosts/serverofmanykeks.online/httpdocs/rank/" and then set chmod to 777 for icons, avatars and logs folders.

You missed other/dbconfig.php and the update folder..

> The nav bar on the webpage is not there also, could this be because the worker.php is not running? I'm assuming so anyway.

Which page, the stats page or the webinterface?

> I am also getting "Array ( [0] => 42S22 [1] => 1054 [2] => Unknown column 'adminuuid' in 'field list' )" when I try to set the Admin ID.

That comes, if you update from an older version. After changing/replacing the webserver files, you need first to start the Ranksystem before you can enter the admin ID. The permissions for the logpath should be set like before your update. I suppose before you update the Ranksystem it runs also with this logpath..

**Comment by Newcomer1989** [comment]
closed due no response on our post
