### ISSUE TITLE
Error while getting servergrouplist

### ISSUE THREAD

**Issue by Ultrashadow** [Newcomer1989/TSN-Ranksystem#216]
Well, the ranksystem generally working fine but after changing something on the rank-up definition it constantly spams the logfile with this error message
update_groups 1:2052: Error while getting servergrouplist: file input/output error

Some advise about it would be nice :).

**Comment by Newcomer1989** [comment]
This is a TS3 error. Be sure you have the TS3 permissions set to your query user.

**Comment by Ultrashadow** [comment]
I tried with server-query admin but the same error appears

**Comment by Shad86** [comment]
be sure, if its external that the filetransfer port is available.

this are the default ports:

Default voice port (UDP in): 9987
Default filetransfer port (TCP in): 30033
Default serverquery port (TCP in): 10011
Default tsdns port (TCP in): 41144
Default weblist port (UDP out): 2011-2110 (first available port in given range)

**Comment by Ultrashadow** [comment]
It is internal, connected via local subnet, but anyway, all ports should be reachable

**Comment by Shad86** [comment]
then recheck your rankup definition (because after your changed it you got this error) and as said before check that the rights are set.

> i_ft_file_browse_power
> i_ft_file_download_power
> b_virtualserver_servergroup_list

**Comment by Ultrashadow** [comment]
Uhh, eeehm well I found the issue now. Thing is, apache blocks the /icons/ folder for whatever reason and I'm not quite sure how to deactivate this, so I decided to change the path in all files to /icon/
but: 		$iconlist = $ts3->channelFileList($cid="0", $cpw="", $path="/icon/"); produces the error
		$iconlist = $ts3->channelFileList($cid="0", $cpw="", $path="/icons/"); not.
I don't think it likes that. 
Created a symlink now and the issue is gone.
Don't thought this could produce the issue since it is just a changed path. Anyway, thanks for your support!

**Comment by Newcomer1989** [comment]
Then it is a selfmade error due changing the script on the wrong permission.

I recommend not to modify the script, if the effects are unkown.

Change it back and you should not get the error anymore.

For your apache problem this https://github.com/Newcomer1989/TSN-Ranksystem/issues/144#issuecomment-259507103 should help you.
