### ISSUE TITLE
TS3 Server stürzt ab wenn ich den Bot starte.

### ISSUE THREAD

**Issue by Tobiasnick** [Newcomer1989/TSN-Ranksystem#217]
Wenn ich meinen Bot starte und ihn auf meinem TS3 Server verbinden will, dann stürzt in wenigen Minuten mein TS3 Server ab. 
Die RAM kann es nicht sein. Auf meinem V-Server wird angezeigt das die RAM nicht überlastet ist.

Ich hoffe hier kann mir jemand weiterhelfen.

Mit freundlichen Grüßen

Tobiasnick

**Comment by Newcomer1989** [comment]
Wie ist denn die CPU Auslastung auf deinem V-Server?

Probiere es evtl. mal mit dem Slowmode (Webinterface - Teamspeak). Stelle diesen auf "high delay". Mehr Infos siehe auch in der online Hilfe im Webinterface.

**Comment by Tobiasnick** [comment]
Dies hat leider nichts geholfen.

Mein TS3 Server stürzt trotzdem ab.
Ich wüsste jetzt auch nicht woran es liegen könnte. Wenn der Bot nämlich nicht auf meinem TS3 Server ist dann stürzt der TS3 Server nicht ab.

**Comment by Shad86** [comment]
Was sind den deine Server Spezifikationen?

(Ich gehe mal davon aus das es ein Linux system ist)

free -m (für Ram)

cat /proc/cpuinfo (für cpu) [hier wäre es Sinnvoll das in einen pastebin (unlisted) zu packen aufgrund der Größe (http://pastebin.com/)]

Welcher Anbieter?

MfG

Shad86

**Comment by Tobiasnick** [comment]
Ich habe 2 GB RAM auf meinem V-Server.

Hier sind die Infos für die CPU:
[http://pastebin.com/Hia2RSnr]

Ich hoste meinen V-Server auf signaltransmitter. [https://signaltransmitter.de]

**Comment by Shad86** [comment]
Okay,

hast du mal geschaut wie sich die cpu verhält, wenn du das ranksystem startest

2x 1,6 Ghz sollten eigentlich machbar sein (abhängig natürlich davon wie viele User du hast)

und

hast du teamspeak in eine mariadb eingebunden oder läuft das nur standartgemäß mit der sql im Ordner

Also nutzt nur das ranksystem die mysql / mariadb oder auch teamspeak?


Wirft denn auch das ranksystem irgendwelche Fehler?

Welche Php version nutzt du derzeit?

Sorry für die vielen Fragen aber dein Problem ist erstmal recht neu und so in der Art nicht vorgekommen

MfG

Shad86

**Comment by Tobiasnick** [comment]
Kein Problem.

Wenn ich das Ranksystem starte habe ich eine maximale CPU Auslastung von 12%. Der Slowmode ist deaktiviert. Ich habe ihn auch mal aktiviert dies hat aber nichts geholfen.
Die Datenbank habe ich halt per phpmyadmin erstellt. Das Ranksystem müsste über Mysql laufen, weil ich  nix mit mariadb gemacht habe.

Hier ist noch der Log vom Ranksystem:
http://pastebin.com/z8axJgP3

Ich benutze derzeit keine Php und benutze vom Ranksystem die Version 1.1.0.
Die neuste Version vom Ranksystem hat bei mir nicht geklappt, weil ich nicht auf meinem V-Server irgendwie Php installieren konnte.

MFG

Tobiasnick

**Comment by Shad86** [comment]
Für ältere Versionen geben wir keinen Support, solltest du Hilfe brauchen um die aktuellste Version nutzen zu können, so komme doch bitte auf unseren Support TS -> ts-n.net

Das Ranksystem selbst, funktioniert nur mit php, ergo muss eine php Version installiert sein (da PHPmyadmin dieses ja auch benötigt - wie der name schon sagt)

Ich bin auf jeden fall noch 1-2 Stündchen da.

MfG

Shad86

**Comment by Tobiasnick** [comment]
Dann werde ich morgen auf dem Support TS kommen.

MFG

Tobiasnick

**Comment by Shad86** [comment]
Ich wollte mal fragen, ob sich für dich das Problem erledigt hat oder ob wir uns einfach verpasst haben, weil dann können wir auch gerne mal eine Zeit ausmachen.

MFG

Shad86

**Comment by Tobiasnick** [comment]
Ich war heute im Support TS aber leider war niemand da.
Ich werde es dann morgen nochmal versuchen.

MFG

Tobiasnick

**Comment by Shad86** [comment]
Es wäre dann gut zu wissen, wann du in etwa da bist, bevor du noch 5 mal auf den TS3 kommen musst. ;)

**Comment by Tobiasnick** [comment]
Morgen bin ich dann um 18 Uhr auf dem Support TS. Wäre das möglich ?

**Comment by Shad86** [comment]
Jup bin dann da :)

**Comment by Tobiasnick** [comment]
Vielen Dank
