### ISSUE TITLE
remove online time from user

### ISSUE THREAD

**Issue by Shadow329** [Newcomer1989/TSN-Ranksystem#218]
Hey Community, 

Ich bin seit einer Woches stolzer besitzer/user des Ranking bot´s danke nochmal für den Support :D 

Nun habe ich ein RIEEEEESEN fehler gemacht und meiner Community die Statistik seite gezeigt, nun ging es Los.

Person 1: Hahahahhaha ich bin erster! 
Person 2: Nicht mehr lange ich habe Ferien.
Person 1: Ja und ich hab nächste woche auch Urlaub dann bin ich wieder erster. 

An sich ja ganz gut mir ging es aber nach einiger zeit so auf die nerven das ich mir gedacht habe so ihr kleinen ***** und hab mir einfach mal 500Tage dazugegeben :D jetzt zu meiner Idee wie wärs wenn man über das Webinterface nicht nur Zeit hinzufügen kann sondern auch abziehen könnte.
 Ich würde gerne von meinen 500Tagen wieder runterkommen, :D (ich weiß geht auch über die Datenbank(ich mach da nichts drann bin froh das es läuft)) zusätzlich könnte man wenn sich ein User nicht an die Regeln hält ihn nicht direkt Kicken/Bannen sondern einfach Zeit abziehen. Vorrausgesetzt auf anderen Servern battlen sich die User auch darum. Bringt ja nichts wenn es den Usern eh nicht juckt was sie für einen Rang haben. 

mfg ein überglücklicher Rankbot nutzer Shadow ;)

**Comment by Shad86** [comment]
Das mit der Zeit Berichtigung / abziehen ist meines Wissenstandes schon auf der todo.

Nur sind die letzten Wochen / Monate so viele neuen Features hinzugekommen, dass wir demnächst erstmal etwas langsamer machen wollen und uns dazu Gedanken machen wie wir es einsteigern vereinfachen (einfach weil es schon viele Einstellungsmöglichkeiten gibt und ein feature ist auch noch in arbeit).

Vielleicht hat ja aber ein User Zeit sich dessen anzunehmen und die "abzugsvariante" uns per "pull request" zur Verfügung zu stellen.

mfg

Shad86

**Comment by Shad86** [comment]
Zu deinem derzeitigen Problem:

Zeit berichtigen geht mit einem sql commando (auch per phpmyadmin absetzbar) [das Ranksystem muss ausgeschaltet sein + cronjob]

UPDATE `datenbankname`.`user` SET `count` = '864000' WHERE `user`.`uuid` = 'UniqueID';

**Zum Beispiel:**

UPDATE `rank`.`user` SET `count` = '864000' WHERE `user`.`uuid` = 'GFhfffhsHFiuiefofhfsiun=';

Wenn du dennoch Hilfe brauchst beim Zeit anpassen, kannst du gerne nochmals vorbei kommen und ich schau es mir dann an.

MfG

**Comment by Newcomer1989** [comment]
Lange hat es gedauert...

Mit 1.2.9 ist die gewünschte Funktion nun auch auf einem offiziellenm Weg enthalten.
