### ISSUE TITLE
Old Level gets removed, new Level failed

### ISSUE THREAD

**Issue by DrTeamspeak** [Newcomer1989/TSN-Ranksystem#22]
The Level 1 is given to everybody who talked the time but when he should get level 2 he dont get the 2. Level but the system removes level 1.

So short in better english ...

The Script counts the time ----> Level 1 ..... counting ...... Time for level 2 is done....... Removing level 1 
BUT dont give the user level 2

I hope you understand me... SORRy i am german...

**Comment by Newcomer1989** [comment]
How looks your rankup configuration?
Please check also the ranksystem.log for errors.
