### ISSUE TITLE
Error 3329: connection failed, you are banned (you may retry in 599 seconds)

### ISSUE THREAD

**Issue by pecagg** [Newcomer1989/TSN-Ranksystem#221]
Hi there. I have finally managed to make Ranksystem work (I had previous issues with starting the bot, but I managed to run it with php5 command instead of using php command).

Now, I have a problem keeping the bot on server. I am constantly getting error 3329.

My whitelist file is properly set up with the exception for localhost (server and ranksystem are hosted on the same machine). I am not having any issues with other bots using serveradmin query. 

This is the log from Ranksystem:

> 2017-01-18
> 
>  03:52:09.105330   ERROR     Error 3329: connection failed, you are banned (you may retry in 599 seconds)
> 2017-01-18 03:51:46.008534   NOTICE      There were nothing to delete...
> 2017-01-18 03:51:46.008472   NOTICE      Clients in the Ranksystem database: 96
> 2017-01-18 03:51:46.008311   NOTICE      Clients found in the TeamSpeak database: 96 (of 736)
> 2017-01-18 03:51:42.471015   NOTICE    Scan for clients, which have to delete...
> 2017-01-18 03:51:26.410589   INFO      Download avatar: /avatar_lgneicbhednmaolppnfadngahhkngikaohnmjbik
> 2017-01-18 03:51:25.408626   INFO      Download avatar: /avatar_bdjpmomajmmpaalddggkbgenedmmiicgphgcenjl
> 2017-01-18 03:51:22.397554   INFO      User 'TWTWTWTW' (unique Client-ID: 5CJcS/j+/bDl+eSikh1/aIJ5+k4=; Client-database-ID 48) is unknown -> added to the Ranksystem now.
> 2017-01-18 03:51:22.397004   INFO      User 'lancececemiimmimicheater' (unique Client-ID: YIrwOHAWoJuLs7gC3YA9V+nGqB8=; Client-database-ID 503) is unknown -> added to the Ranksystem now.
> 2017-01-18 03:51:21.394953   NOTICE    Much time gone since last scan.. reset time difference to zero.
> 2017-01-18 03:51:14.384018   INFO      Bot starts now his work!
> 2017-01-18 03:51:14.383891   INFO        Joined to specified Channel.
> 2017-01-18 03:51:10.380257   INFO        Connection to TS3 Server established.
> 2017-01-18 03:51:10.360212   INFO      Connect to TS3 Server (Address: "localhost" Voice-Port: "9987" Query-Port: "10011").
> 2017-01-18 03:51:10.360151   INFO        Ranksystem Version: 1.2.1
> 2017-01-18 03:51:10.360050   INFO        Check files permissions [done]
> 2017-01-18 03:51:10.354545   INFO        Check files permissions...
> 2017-01-18 03:51:10.354297   INFO        No newer version detected; Database check finished.
> 2017-01-18 03:51:10.354191   INFO      Check Ranksystem database for updates.
> 2017-01-18 03:51:10.348135   INFO      Initialize Bot...

**Comment by bykidi** [comment]
add this to your query_ip_whitelist.txt

`127.0.0.1
<YourIPv4>
<YourIPv6>` (if you have it)

**Comment by Shad86** [comment]
Since no other answer from you was made i close this issue now because i am assuming that now everything works.

If you still have questions open a new issue (if your question belongs to this issue you can refer/link to this thread with #issuenumber)

regards

Shad86
