### ISSUE TITLE
vServer (Windows) + Plesk | Bot startet nicht und andere Fehler

### ISSUE THREAD

**Issue by DAmNRelentless** [Newcomer1989/TSN-Ranksystem#222]
Hallo,

mein Problem ist genau das gleiche, wie in diesem Bugreport: https://github.com/Newcomer1989/TSN-Ranksystem/issues/211

Allerdings wurde dem User dort privat geholfen und selbst wenn ich die Schritte befolge, die Newcomer als Lösung vorgeschlagen hat, läuft es bei mir trotzdem noch nicht rund. Es wäre nett, wenn mir da auch geholfen werden könnte.

Zur näheren Problembeschreibung: wenn ich alles auf den Webspace hochgeladen habe und die "install.php" ausführe und sich das Webinterface öffnet, lasse ich die Datenbankeintragungen gleich, denn den Datenbanknamen finde ich ganz gut. Dann trage ich den DB-User + Passwort ein, allerdings, wenn ich dann auf erstellen drücke, werden mir Fehlermeldungen angezeigt, dass die ganzen Tables der Datenbank nicht erstellt werden konnten. Und ja, ich habe dem User alle Rechte für die Datenbank gegeben. Das ist ja das komische daran. Dann habe ich mir gedacht, erstelle ich die Datenbank einfach selbst. Das hat auch funktioniert und dann komme ich ins Webinterface und konnte meine Einstellungen vornehmen. Das Problem war dann aber, dass ich den Bot nicht starten konnte. Wenn ich auf den Button "Bot starten" drückte, dann ist das Webinterface verschwunden und nichts ist passiert. Ja, das ist so mein Problem. 

Danke im Voraus!

**Comment by Newcomer1989** [comment]
Solch ein Support ist zu zeitintensiv. Solltest du die Installation nicht hinbekommen, beantrage bitte ein gehostetes Ranksystem https://ts-n.net/ranksystem.php#support
