### ISSUE TITLE
CRITICAL  Request to start the Ranksystem 

### ISSUE THREAD

**Issue by AlFcl** [Newcomer1989/TSN-Ranksystem#223]
i have problem here pls help

**Comment by Shad86** [comment]
Well, then tell us what your problem is ;)

Necessary informations:

Where is the ranksystem Hosted

Which OS? Linux / Windows 

Logs

regards

Shad86

**Comment by Newcomer1989** [comment]
Closed due no response. Feel free to reopen it with some more information about your problem.
At the moment we are not able to help you!
