### ISSUE TITLE
[1.2.2] Blank pages everywhere

### ISSUE THREAD

**Issue by bykidi** [Newcomer1989/TSN-Ranksystem#224]
apache-error.log

[Sun Jan 22 12:18:45.192677 2017] [php7:notice] [pid 24296] [client superhiddenip:11684] PHP Notice:  Undefined variable: mysqlcon in /var/www/html/ranks/webinterface/index.php on line 60
[Sun Jan 22 12:18:45.192726 2017] [php7:error] [pid 24296] [client superhiddenip:11684] PHP Fatal error:  Uncaught Error: Call to a member function query() on null in /var/www/html/ranks/webinterface/index.php:60\nStack trace:\n#0 {main}\n  thrown in /var/www/html/ranks/webinterface/index.php on line 60

**Comment by Newcomer1989** [comment]
You already started the Ranksystem after the update?

If yes, pls show us the log of it.

**Comment by bykidi** [comment]
no. even if i upload the fresh installation of ranksystem i get this message

**Comment by bykidi** [comment]
few days ago (i think) there was minor update for php 7.1, maybe it caused the error. try to update on your machine

PHP 7.1.1-1+deb.sury.org~xenial+1 (cli) (built: Jan 20 2017 09:20:20) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.1-1+deb.sury.org~xenial+1, Copyright (c) 1999-2017, by Zend Technologies

**Comment by bykidi** [comment]
and the list of installed packages

![default](https://cloud.githubusercontent.com/assets/1337953/22181633/063de1d4-e0a1-11e6-8c12-b62d22ee83dd.png)

**Comment by Newcomer1989** [comment]
Did I overlook the log of the Ranksystem?

**Comment by bykidi** [comment]
again... step by step.

cd /var/www/html
mkdir ranks
cd ranks
wget https://github.com/Newcomer1989/TSN-Ranksystem/archive/master.zip
unzip master.zip

and after that

https://mysite.noname/ranks/TSN-Ranksystem-master/
Blank page appears.
apache-error.log

```
[Sun Jan 22 12:18:45.192677 2017] [php7:notice] [pid 24296] [client superhiddenip:11684] PHP Notice: Undefined variable: mysqlcon in /var/www/html/ranks/webinterface/index.php on line 60
[Sun Jan 22 12:18:45.192726 2017] [php7:error] [pid 24296] [client superhiddenip:11684] PHP Fatal error: Uncaught Error: Call to a member function query() on null in /var/www/html/ranks/webinterface/index.php:60\nStack trace:\n#0 {main}\n thrown in /var/www/html/ranks/webinterface/index.php on line 60
```

**Comment by Newcomer1989** [comment]
thats true.. follow the instructions step by step

https://ts-n.net/ranksystem.php#install

**Comment by bykidi** [comment]
So for now even if i wipe entire ranksystem folder, put the new one, replace database config file with my own one = its not working anymore?

**Comment by Shad86** [comment]
Just as a hint for the future do not just upgrade "mainsoftware" on your system without looking if your running programms/scripts are still supporting it.

Your lucky that only our ranksystem "crashed" away but that can happen with every other script/programm too.

Thats why i personally always make a "side by side" installation like having both versions (in our case php.7.0 and php 7.1) [old and new one] installed and then i can switch between the versions so that i can see if there is any behavior with any software that im using.

Thats usually a standart linux thing if you'r about to use always the newest from the newest on your system.

Because every software is usually a little bit behind the newest version, just because (in our case) the php Version isnt available until its released.

kind regards

Shad86

**Comment by Newcomer1989** [comment]
It is like described in the Changelog. The support for PHP 7.1 comes first time with the version 1.2.2. not with version 1.2.1!

So for all other: First update the Ranksystem to 1.2.2 (which happens automatically) and till then do not update your PHP 7.1. With an already running version 1.2.2 it is no problem to update your PHP to 7.1. This is the only right way. All other ways are not official supported!

**Comment by Artapel** [comment]
> That's true. It is not an error of the Ranksystem. Follow the instructions step by step.

> https://ts-n.net/ranksystem.php#install

I cannot see anything on this link. Is it just my browser are the info missing on the website?
