### ISSUE TITLE
Addon assign servergroups bug (if notification is disabled)

### ISSUE THREAD

**Issue by Nisutec** [Newcomer1989/TSN-Ranksystem#225]
My Users can't get any groups.
The Webinterface says "Please choose at least one new group."
but i have a group selected.

**Comment by Shad86** [comment]
I Checked it - and it works without any issues. 

You get this message only if you already have all the groups what are currently assigned.

So if you select a group what you already have, sure it says you have to choose because the assigner knows if you have the group or not.

**Comment by Nisutec** [comment]
Ich habe gesehen das du deutsch kannst also können wir ja auch auf deutsch schreiben. Und es geht nicht auch wenn man keine der Server Gruppen besitzt. Wenn du möchtest kannst du dir das gerne mal ansehen
http://134.255.231.248/ranksystem/stats/assign_groups.php

**Comment by Shad86** [comment]
Aktuell ist da wohl tatsächlich ein Bug - Wenn die Benachrichtigungen aus sind, funktioniert der Assigner für die Vergabe der Gruppen nicht.

Lösung:

Benachrichtigung anschalten.

Currently there is a bug, if "Rank up notification" (under Messages) is disabled you cant give Servergroups over the assigner.

Solution:

Enable "Rank up notifications"

**Comment by mamayer** [comment]
Ich habe das Problem auch, es scheint an folgenden Zeilen zu liegen:

```
<?PHP if(in_array($allowed_group, $cld_groups)) {
    echo '<input id="switch-animate" type="checkbox" checked data-size="mini" name="',$allowed_group,'" value="',$msgtouser,'">';
} else {
    echo '<input id="switch-animate" type="checkbox" data-size="mini" name="',$allowed_group,'" value="',$msgtouser,'">';
} ?>
```
ich  bin noch nicht lange im Code des Systems unterwegs, aber mir erschließt sich nicht, warum der `value` $msgtouser sei sollte und nicht einfach "1".
Vermutlich ein Copy'n'paste-Fehler des Buttons aus msg.php.

Korrekt wäre demnach:
```
<?PHP if(in_array($allowed_group, $cld_groups)) {
    echo '<input id="switch-animate" type="checkbox" checked data-size="mini" name="',$allowed_group,'" value="1">';
} else {
    echo '<input id="switch-animate" type="checkbox" data-size="mini" name="',$allowed_group,'" value="1">';
} ?>
```

Ich mache mal einen Pullrequest dazu...

**Comment by Shad86** [comment]
Nicht notwendig, dennoch danke

-> https://ts-n.net/ranksystem.php#changelog

**Comment by mamayer** [comment]
Ah Danke, da ist auch mein anderes Problem gelöst... "/icons" - musste erstmal die Apache-Config anpassen und den Alias rauslöschen -.-

**Comment by Shad86** [comment]
Ja apache managed das ganze recht seltsam, weil für gewöhnlich Leute ohne subdomain nicht in dieses problem laufen, apache aber wohl bei subdomains die Ordner anders verwaltet...

**Comment by Newcomer1989** [comment]
Will be fixed with the next official release 1.2.3

**Comment by Newcomer1989** [comment]
Release 1.2.3 is published. The problem should be fixed. Please reopen this issue, if you should still have problems!
