### ISSUE TITLE
Assign serversgroups - servergroups/time as requirement

### ISSUE THREAD

**Issue by SpliinTaX** [Newcomer1989/TSN-Ranksystem#228]
Howdy,

ich habe einen kleinen Vorschlag, und zwar finde ich es ein wenig schade das man nicht die Möglichkeit hat anzugeben wann man diese Funktion benutzen darf. Zum Beispiel wenn man erst ab ein bestimmtes Level diese Funktion nutzen zu dürfen. 

Meines Wissens nach können ja auch Leute die nicht berechtigt sind am Levelsystem teilzunehmen, sich Gruppen da durch vergeben. Ist das so gewollt?

mfg

**Comment by Shad86** [comment]
Du willst sozusagen eine Abhängigkeit haben.

Erlaube Servergruppen setzen nur wenn user Gruppe x besitzt?

**Comment by SpliinTaX** [comment]
Richtig, um es noch mal verständlicher zu machen. 

Wir sind eine Multigaming Community und sobald man den Rang **Mitglied** hat ist man berechtigt am Levelsystem teilzunehmen. Dementsprechend sollte man sich dann die jeweiligen Gruppen setzen können. 

Wenn dieser Vorschlag den Sinn macht, ich weiß nicht wie die Nachfrage danach ist.

**Comment by Shad86** [comment]
Doch macht eig. schon Sinn, weil man ja damit Nutzer auch vom groupassigner ausschließen kann, was ja so derzeit dann nicht gehen würde.

verstehe auch zeitgleich den Sinn dahinter, das eben ein Member dann mehr "kann" und sich deshalb auch Gruppen zuweißen können soll.

**Comment by SpliinTaX** [comment]
Also wäre es ggf möglich diesen Vorschlag umzusetzen?

**Comment by Shad86** [comment]
Wenn es die Zeit erlaubt, vermutlich ja, entweder es macht jemand einen pull request dafür, wenn nicht wird es höchstwahrscheinlich etwas länger dauern, da newcomer derzeit kurz vor seinen Klausuren steht und daher derzeit wenig Zeit hat.

**Comment by SpliinTaX** [comment]
Dann wünsch ich ihn mal viel Glück, falls er das lesen sollte.

**Comment by SpliinTaX** [comment]
Wie schaut's aus?

**Comment by Shad86** [comment]
Newcomer ist noch immer vom Erdboden verschwunden und das sei bereits 3 Monaten

**Comment by Newcomer1989** [comment]
Um mal einen Sachstand zu geben. Dieser Punkt steht auch so schon auf meiner ToDo Liste. Die derzeitige Variante war ja nur ein erstes ausliefern der Kernfunktion.

Evtl. dann in der Version 1.2.4 oder zumindest in eine der nachfolgenden, wird es das dann auch geben. Sprich eine Abhängigkeit einer Zeit oder Gruppe, damit bestimmte Gruppen überhaupt gesetzt werden können. Dann schließt sich auch der Kreis, dass es für ein Ranksystem Sinn macht ;-)

**Comment by Shad86** [comment]
Wir haben "Servergruppen - Ausnahmen hinzugefügt.

Vielleicht wird es in Zukunft auch eine Whitelist geben aber für den Moment sollte es zumindest davor schützen, dass Nutzer nicht ohne Berechtigung, das Ganze nutzen können.
