### ISSUE TITLE
How to change password on TSN Ranksystem - Webinterface   ???

### ISSUE THREAD

**Issue by PascaLCZ** [Newcomer1989/TSN-Ranksystem#232]
IMG: http://www.saveimg.com/images/2017/01/26/VLmihlH.png

**Comment by Shad86** [comment]
seems you have an old Version of the ranksystem password reset is only available in the newer versions of the ranksystem

**Comment by Shad86** [comment]
take this release first -> https://github.com/Newcomer1989/TSN-Ranksystem/archive/1.1.3.zip

update it on the usual way

after that it should be possible to set your unique id in the confic table
![phpmyadmin01](https://cloud.githubusercontent.com/assets/18570683/22345973/97df3868-e402-11e6-900e-938db42f708f.png)

adminuuid

after that update to the latest version

regards

Shad86

**Comment by Newcomer1989** [comment]
An update will solve the problem, you have. I think we can close this issue. If you have still problems feel free to reopen it.
