### ISSUE TITLE
Vote for the next feature... (2)

### ISSUE THREAD

**Issue by Newcomer1989** [Newcomer1989/TSN-Ranksystem#233]
Which feature do you wish for the next version(s) of the TSN Ranksystem?

**[click here for voting](https://goo.gl/F1QW1e)**

**Comment by SpliinTaX** [comment]
Wieso ist folgender Vorschlag nicht mit Inbegriffen? https://github.com/Newcomer1989/TSN-Ranksystem/issues/228

**Comment by Newcomer1989** [comment]
Wir haben eine riesen Liste an ToDo's für das Ranksystem. Daraus können wir uns immer nur einen kleinen Ausschnitt heraus suchen, welcher für die Community interessant scheint.
Aber es kommen ja nicht nur die Dinge die gevotet werden. Dazu vergleiche doch einfach mal die Changelog der letzten drei Versionen in Verbindung mit dem Ergebnis des letzten Votings.
Das Voting dient für uns lediglich als Priorisierung.

**Comment by bykidi** [comment]
What about auto-channel sorting? :D

**Comment by Newcomer1989** [comment]
That's to much work. Instead of the auto-channel sorting we are able to bring five other features in.

Feel free to code it and make a pull request for this feature.

**Comment by Newcomer1989** [comment]
The topic was the voting. All things are done -> closed.
