### ISSUE TITLE
apache's error log spammed by list_rankup.php warns

### ISSUE THREAD

**Issue by bykidi** [Newcomer1989/TSN-Ranksystem#235]
![default](https://cloud.githubusercontent.com/assets/1337953/22414793/7c5213e4-e6d3-11e6-8390-b0c0492128eb.PNG)

My error.log file is now over 600MBs.
It's Yandex Bot (russian search engine) somehow figured out where is my ranksystem stored and causing this errors all over my disk. I also have PHP error logging enabled both on pages and in log file.

**Comment by eNNercY1337** [comment]
i can confirm this, several ips are accessing that php file.
endless list with always changing numbers and user ids.

> ?sort=name&order=desc&seite=2&user=69&search=filter:lastseen:%3E:1485012171

**Comment by Newcomer1989** [comment]
@bykidi are it the same addendum for you as eNNercY1337 posted it?

**Comment by bykidi** [comment]
@Newcomer1989 ''addendum''?

**Comment by Newcomer1989** [comment]
?sort=name&order=desc&seite=2&user=69&search=filter:lastseen:%3E:1485012171

**Comment by bykidi** [comment]
@Newcomer1989 honestly - no idea... i have disabled php error logging because it spams with errors for like 2 gigabytes per day

**Comment by bykidi** [comment]
Seems to be fixed in pre-1.2.3
Closing...
