### ISSUE TITLE
500 Server Error

### ISSUE THREAD

**Issue by BlackFishMaker** [Newcomer1989/TSN-Ranksystem#237]
Hey i installed your bot and i put in all the info and everything but once i try to start it it takes a really really long time to load and just shows me a grey background after i try to reload the page i get a 500 server error. After some time i can reload the page and it works again but i still cant start the bot. I feel like it might be a permission problem but i dont know which of the folders need what permissions.

**Comment by Shad86** [comment]
Hello,

you usually should start the ranksystem with the right webuser and not as root.  On apache2 mostly the standart user is www-data.

Then you usually get on the install process the needed rights for the folders, they are:

`chmod 777 -R avatars/ icons/ logs/ update/ other/dbconfig.php`

regards

Shad86

**Comment by BlackFishMaker** [comment]
I redid all the folder permissions but it still doesnt work but what do you mean with webuser? I log into the webinterface with the user i create after the installing process right?

**Comment by Shad86** [comment]
Thats correct but the folders need rights for the webuser as said above and also as described here:

https://ts-n.net/ranksystem.php#install

**Comment by BlackFishMaker** [comment]
Alright so i gave permissions to the default webuser and reinstalled the whole thing gave all folders permissions again and set everything up again but its still not working :(

**Comment by bykidi** [comment]
@BlackFishMaker try to run using root just for test

**Comment by BlackFishMaker** [comment]
it says "operation not permitted" im using namecheap to host it and they also replaced the www-data by another variable but i changed it to what they said would be the equivalent maybe that could be the problem?

**Comment by bykidi** [comment]
@BlackFishMaker seems like your hoster is not allowing you to execute the php files for some security reasons...

**Comment by BlackFishMaker** [comment]
i specifically checked they do allow all the permissions that are listed as requirements. but i guess that will probably be the problem, can you recommend any hosters? i only need to host the bot on it nothing else

**Comment by Shad86** [comment]
If you have to much troubles, you can ask for a sponsored hosting directly from the owner:
https://ts-n.net/ranksystem.php#support

Today he is already offline, so you just could contact him over the contact form.

regards

Shad86

**Comment by BlackFishMaker** [comment]
Oh thanks i didnt even see that i thought they would only sponsor with 40 or more active users ill contact him tomorrow for sure thanks for all the help!

**Comment by bykidi** [comment]
@BlackFishMaker good luck!
