### ISSUE TITLE
worker.php not starting

### ISSUE THREAD

**Issue by Saengerkrieg12** [Newcomer1989/TSN-Ranksystem#24]
worker.php not starting
Code: 
```
root@gamestar-clan:~# /var/www/ranksystem/worker.php start
/var/www/ranksystem/worker.php: line 1: ?php: No such file or directory
/var/www/ranksystem/worker.php: line 2: syntax error near unexpected token `__DIR__.'/other/config.php''
/var/www/ranksystem/worker.php: line 2: `require_once(__DIR__.'/other/config.php');'
```

**Comment by Newcomer1989** [comment]
Your command itself is the problem, not the Ranksystem.

Please do not start the Ranksystem with the user root! There you got security and permission problems!

Try this one
`sudo -u www-data php worker.php start`

Or for you example out of the root directory
`sudo -u www-data php /var/www/ranksystem/worker.php start`
