### ISSUE TITLE
Help the bot is not starting #Closed

### ISSUE THREAD

**Issue by CreeperHD** [Newcomer1989/TSN-Ranksystem#245]
If I start my bot then comes that
Fatal error: Class 'COM' not found in C: \ xampp \ htdocs \ Ranking \ webinterface \ bot.php on line 136
Pls help me

sry for my bad english

**Comment by Shad86** [comment]
> with "COM" extension for PHP (for Windows only)

https://ts-n.net/ranksystem.php#requirements

-> http://php.net/manual/en/book.com.php

regards

Shad86

**Comment by CreeperHD** [comment]
how do i fix this ?

**Comment by Shad86** [comment]
you need this extension on your system...

**Comment by CreeperHD** [comment]
and how i add this

**Comment by Shad86** [comment]
Sorry we'r not here for Server Support - pls get someone who can help you with this or try to find it over google search
