### ISSUE TITLE
Help The bot is not starting

### ISSUE THREAD

**Issue by CreeperHD** [Newcomer1989/TSN-Ranksystem#247]
Hello I am trying to start my bot all the time but it does not happen it is nothing in the log it is not even a created in the webinterface please help

**Comment by Shad86** [comment]
If you really cant get it to work i can suggest you to use our Sponsored hosted solution
https://ts-n.net/ranksystem.php#support

**Comment by Newcomer1989** [comment]
you really solved the knowm problem?
https://github.com/Newcomer1989/TSN-Ranksystem/issues/245
