### ISSUE TITLE
Bot error (out of date)

### ISSUE THREAD

**Issue by Pepreal** [Newcomer1989/TSN-Ranksystem#248]
Found out that my bot whas out of date for 4 hours, and the log is giving me this error. A restart in the admin panel did fix it but stil dont now why this happend or what it is.

2017-02-07 20:22:26.178367   ERROR     load_addons_config 0:Array
(
    [0] => HY000
    [1] => 2006
    [2] => MySQL server has gone away
)

**Comment by Shad86** [comment]
Then usually the ranksystem wasnt able to reach your mysql server or lost the connection to it.

Or its also maybe an issue see issue #178

**Comment by Pepreal** [comment]
Oke thanks, think it lost the connection then
