### ISSUE TITLE
Improve Rank Listing

### ISSUE THREAD

**Issue by joshua2504** [Newcomer1989/TSN-Ranksystem#25]
Hi,

Please add an option to choose what to display on the all time/weekly/monthly sites and the List Rankup (active time, inactive time, etc)

Also, the "Rank Number" should be calculated based on the choosen value.

greets

**Comment by MadMarco97** [comment]
In the Webinterface ( IP.OF.YOUR.SERVER/ranksystem/webinterface.php ) -> Style Settings

There you can set what to display on the "Rank-List" Site.

**Comment by Newcomer1989** [comment]
> Also, the "Rank Number" should be calculated based on the choosen value.
comes with release 1.0.2
