### ISSUE TITLE
[Feature request] Log previous names of client

### ISSUE THREAD

**Issue by mamayer** [Newcomer1989/TSN-Ranksystem#250]
Clients sometimes switch their names. It would be nice, if the system would show an indicator besides the name of an user, if he had other names and would provide a list of them. If there are too many, they might be sorted by usage and older or least used ones might be dropped/hidden.

**Comment by Shad86** [comment]
Hm i think ~70% of the ranksystem users are only focused on the teamspeak and there ranks.

not so much on the website.

Next things is the database would "explode" if you have for example 200-500 people per day with switching names.

I personally see a huge performance issue with that (saving 3 different names for users for example)

**Comment by mamayer** [comment]
That's true, I didn't concider that they might change their names more than occasionally. Therefore, dropping old entries is important.

The idea came up from an admin-perspective, as users couldn't be identified in the ranking list anymore because of changed names.
But I understand, that this is not a feature for the general public and might only be an option for a custom addon.

**Comment by Newcomer1989** [comment]
The user are 100 % identifiable on their unique client id. You can activate that column for the site `stats/list_rankup.php`.
Also the search field on this side will help you to find user about the unique client id. Take a note to the "i" at top left near of the search bar.

To save changed names should be the job of TeamSpeak not of a third party application. In my opinion they have done it about the serverlog. That's not much comfortable but it is possible.
I think also in most cases you will not need the old name, cause only the actual one will matter. Perhaps you can explain your use-case, that we can understand why you need a function like this.
I am willing to code a function like this, but for this I want to understand it is really necessary. Perhaps there is still an other way, which does the same job.

**Comment by Newcomer1989** [comment]
Closed.. Feel free to reopen it and give use an use-case, where is function is useful.
