### ISSUE TITLE
SimpleXML is needed but seems not available. Install simpleXML and try it again!

### ISSUE THREAD

**Issue by XnIcRaM** [Newcomer1989/TSN-Ranksystem#252]
It doesn't work without SimpleXML?
I try to add it (SimpleXML) to my php 5.6.30 but probably there is no way to add this extension or I can find solution :/
Can someone help me in any way?

**Comment by Shad86** [comment]
I think you'r using linux?

Debian/Ubuntu:

apt-get install php5.6-xml 

Centos(not 100% sure):

yum install php-xml
or
yum install php5.6-xml

regards

Shad86

**Comment by XnIcRaM** [comment]
it's work's thakns you!

I work on CentOS and yum install php-xml works perfect, after restart apache I can install TSN-Ranksystem.
