### ISSUE TITLE
The bot doesn't start and don't have logs

### ISSUE THREAD

**Issue by wesleyjp** [Newcomer1989/TSN-Ranksystem#253]
Hello, i been having trouble when i try to start the bot, nothing happens, and there is no logs too.
Thank you for supporting.

Screenshots:
![fulls](https://cloud.githubusercontent.com/assets/14878939/22941321/3411b2b0-f2cc-11e6-8ced-be79d4998f7f.PNG)

![fulls2](https://cloud.githubusercontent.com/assets/14878939/22941329/3b683188-f2cc-11e6-9063-3ecf2c1f8208.PNG)

My system:
![capture](https://cloud.githubusercontent.com/assets/14878939/22941301/1d09c54e-f2cc-11e6-87f2-50b5dee86cdd.PNG)

![2017-02-14](https://cloud.githubusercontent.com/assets/14878939/22941340/46574e12-f2cc-11e6-8707-a8e93570f65f.png)

All system riquirements checked:
![riquerements](https://cloud.githubusercontent.com/assets/14878939/22941423/7fe2cd14-f2cc-11e6-88d3-94bdbaa3a34e.PNG)

**Comment by Newcomer1989** [comment]
Please check this thread https://github.com/Newcomer1989/TSN-Ranksystem/issues/211#issuecomment-270214623

It has to be a requirement, which is missed. We have tested it on serveral windows servers. If all requirements are fullfilled the restart function works without problems.

**Comment by DerJanikGurke** [comment]
Same problem :(
