### ISSUE TITLE
[Update request] ClientCleaner

### ISSUE THREAD

**Issue by bykidi** [Newcomer1989/TSN-Ranksystem#254]
https://ts-n.net/clientcleaner.php
Tested using latest php framework - working fine.

**Comment by Newcomer1989** [comment]
Wrong placement.. The ClientCleaner is a different tool.
This section is only for the Ranksystem!

**Comment by bykidi** [comment]
Well, you don't have a repository for clientclear, so...

**Comment by Shad86** [comment]
Well you can comment on the site directly -> https://ts-n.net/clientcleaner.php or it also exist an contact form -> https://ts-n.net/contact.php - So there are enough possibilities to post the information on the right place.

**Comment by bykidi** [comment]
![default](https://cloud.githubusercontent.com/assets/1337953/23008919/000061de-f424-11e6-8d29-80fa2de0d125.PNG)
the german variant is working fine

**Comment by Shad86** [comment]
thanks, this site is so or so in English, but as i said thanks.
