### ISSUE TITLE
Icons werden nicht angezeigt

### ISSUE THREAD

**Issue by PhilvanGaat** [Newcomer1989/TSN-Ranksystem#256]
Hallo,

ich habe das Ranksystem auf einer Subdomain installiert und per SSL verschlüsselt. Beim ersten Start des Bots, lädt er die ganzen Servericons runter und speichert sie im Ordner icons. Alles soweit so gut, nur werden mir die Icons auf der Statistikseite nicht angezeigt. Klicke ich im Firefox mit rechts drauf und dann Grafik anzeigen, sagt er mir, dass die URL nicht gefunden wurde obwohl die Datei im Ordner existiert und der Ordner der richtige ist.

![groupicon_ts](https://cloud.githubusercontent.com/assets/23066400/23088611/608a4a0a-f57e-11e6-89cc-20ee666ba297.png)

![groupicon_ts_2](https://cloud.githubusercontent.com/assets/23066400/23088623/75840c5c-f57e-11e6-9255-201038c2bc4e.png)

**Comment by Shad86** [comment]
Wird in der kommenden Version behoben.

https://ts-n.net/ranksystem.php#changelog

> * changed location "icons" to "tsicons" due problems with default apache config

**Comment by bykidi** [comment]
That's not the point.
If you somehow delete the icon in the ranksystem folder - to force it to re-download the icon you need to remove icon from group on the server (or change it to some different icon), wait for some time and change it back. That's the only way to repair the 404 icon in RS folder.
(ofc, if you using 1.2.2 stable version)

**Comment by Shad86** [comment]
Actually it is, apache has on default some specials configs for subdomains they get handled in a other way as normal domains especially the "icons" thing, that's why he didn't get icons because they get redirected in a other way if your use subdomains.

regards

Shad86

**Comment by Shad86** [comment]
Fixed in the Experimental -> 

Info (whats in there): https://github.com/Newcomer1989/TSN-Ranksystem/issues/273

Download: https://github.com/Newcomer1989/TSN-Ranksystem/tree/Experimental
