### ISSUE TITLE
Bot Stop at update icons

### ISSUE THREAD

**Issue by bit2gb** [Newcomer1989/TSN-Ranksystem#257]
I install tsn bot, all fine but after start bot make icons update and it reaches to admin query he was stops. What to do? Error are:
2017-02-19 11:27:14.461148   ERROR     calc_serverstats 1:Array
2017-02-19 11:27:14.374429   INFO      Download new ServerGroupIcon for group '.::HUNTERS::.' with ID: 40
2017-02-19 11:27:14.260301   ERROR     update_groups 8:Array
2017-02-19 11:27:14.260155   ERROR     update_groups 7:('1', 'Guest Server Query', '0', '0'),('2', 'Admin Server Query', '1096522026', '1485043654'),

Please help

**Comment by Shad86** [comment]
pls always give us the full log, so that we'r able to see the whole procedure and not only 1-2 pieces of it.

calc and update errors are in most case an issue with the mysql/maria database (for example not reachable anymore).

Next question is, you only installed it fresh or it was an update?

regards

Shad86

**Comment by bit2gb** [comment]
Am instalat botul de la 0 , nu este update
Here is full log for bot!
http://tspanel.2gb.ro/test/logs/ranksystem.log

**Comment by Shad86** [comment]
> 2017-02-19 11:53:29.276427   ERROR     calc_serverstats 1:Array
> (
>     [0] => HY000
>     [1] => 2006
>     [2] => MySQL server has gone away
> )

see issue #178

**Comment by bit2gb** [comment]
ok but what is the solution?

**Comment by bit2gb** [comment]
i set max_allowed_size to 500M but same problem

**Comment by Shad86** [comment]
Well as said before take a look on issue #178, there are 2 suggestion how you may can fix it.

be sure that your MySQL data are correct and that your MySQL-Server is reachable.

Because "MySQL server has gone away" usually means that your service isn't reachable (no connection or Or incorrect input of your mysql data)

If both doesn't help try a reinstall of the ranksystem.

**Comment by bykidi** [comment]
@bit2gb can you please show us your full my.cnf?
pastebin, ofc

**Comment by bit2gb** [comment]
i try that 2 suggestion but no effect.
ts3 server is on same machine like tsn bot so i dont think is problem with connection... 

my.cnf is:
`[mysqld]
datadir=/var/lib/mysql
socket=/var/lib/mysql/mysql.sock
symbolic-links=0

skip-external-locking
key_buffer_size = 256M
max_allowed_packet = 32M
table_open_cache = 256
sort_buffer_size = 1M
read_buffer_size = 1M
read_rnd_buffer_size = 4M
myisam_sort_buffer_size = 64M
thread_cache_size = 8
query_cache_size= 16M
thread_concurrency = 8

#innodb_use_native_aio = 0
innodb_file_per_table

max_connections=200
max_user_connections=50
wait_timeout=10
interactive_timeout=50
long_query_time=5

#slow_query_log=1
#slow_query_log_file=/var/log/mysql-slow-queries.log


[mysqld_safe]
log-error=/var/log/mysqld.log
pid-file=/var/run/mysqld/mysqld.pid

#
# include all files from the config directory
#
!includedir /etc/my.cnf.d
`

**Comment by bykidi** [comment]
How much RAM do you have?

**Comment by bit2gb** [comment]
i have 9GB ram ddr3

**Comment by bit2gb** [comment]
And now i create other VPS and i install vestacp with mariadb and i have same problem, why?

**Comment by bit2gb** [comment]
I have a problem with grpid, in database all grpid is 0, why is not update?

**Comment by bykidi** [comment]
try to --purge your mariadb-client mariadb-server, wipe away your config folder, add latest mariadb ppa to sources.list, update and install the mariadb again. if the problem persists - it's not problem with mysql

**Comment by bit2gb** [comment]
i reinstall mariadb but i donțt understand what is de problem, why group id is not imported into DB.
Link to site is: http://89.34.25.136/

**Comment by Shad86** [comment]
it really looks like you messed up something. (i can clearly see that you edited things on it)

pls download the latest version -> https://ts-n.net/downloads/ranksystem_1.2.2.zip

and try a reinstall.

**Comment by bit2gb** [comment]
i have the latest version but now i fix it so it is ok:)

**Comment by bykidi** [comment]
@bit2gb beta? omg... how did you even managed to start it on latest php?
