### ISSUE TITLE
Contact From someone

### ISSUE THREAD

**Issue by bit2gb** [Newcomer1989/TSN-Ranksystem#258]
Hello, i want an skype id or ts3 or mail, because i make some cheanges and if you want to use is my pleasure

**Comment by Shad86** [comment]
If you made changes on it, pls make a pull request, because there can be seen the changes / differences between the versions.

**Comment by bit2gb** [comment]
put all files or only new page and modify page?

**Comment by bykidi** [comment]
@bit2gb fork repository, make changes and commit, send pull request.

**Comment by bit2gb** [comment]
I don't understand how can post with commit visit http://http://tracker.fragcs.ro/stats/profil.php?id=1243
this is one of modification.
Use search button from index/profil page.
I add avatar for all profile not only for my profile

**Comment by Shad86** [comment]
hey,

i did a little tutorial, for me that was the simplest way because the program also guide you a little bit through the things and shows you directly what you changed.

See #259

i hope that helps you.

regards

Shad86

**Comment by bit2gb** [comment]
Ok i read your tutorial, but my changes are interesting?

**Comment by Shad86** [comment]
1. Grades Assigned on Server: 
2. Grades Assigned By Tracker: 

what kind of difference is this?

Is it like:

1. Groups given by users
2. Groups given from ranksystem

i hope i understand this site right

**Comment by bit2gb** [comment]
yes, on server is asigned by admins on server for that user and by tracker group assigned by ranksistem

**Comment by Shad86** [comment]
Hm...

okay the only thing what will be confusing then, would be the double search entry here:

http://tracker.fragcs.ro/stats/list_rankup.php


**Next thing i saw:**

http://tracker.fragcs.ro/stats/info.php

The replacing of our copyright through another is not allowed.

You may remove the copyright on the info page (which is not really kind but allowed) but that was it.

The exchange of a copyright or the exchange against another infringes the copyright and I would kindly ask you to adjust this.

**Comment by bit2gb** [comment]
Ok today or tomorow i desactived "my search" on this page :)
OOk replace your info page and eventualy i add some information from me.
On the other hand i edit some things on list_rankup now.
My big dilema is  how post a pull. I atache a link with a screenshot but from this point i don't understand what can i do to post this on web.
https://1drv.ms/i/s!As-SKSgYvKSKkclvrJT9COKOoLl7aw

**Comment by Shad86** [comment]
You cent do a pull request you can see the button on the right side on the top

**Comment by bit2gb** [comment]
Send pull request is blocked, why? photo link : https://1drv.ms/i/s!As-SKSgYvKSKkclwpZr5T9Crsen2uQ

**Comment by Shad86** [comment]
Okay i missed something very important or better to say i made a mistake on the steps

**Comment by Shad86** [comment]
#259 Is now correct - pls take a look on Step 2 :)

**Comment by bit2gb** [comment]
hehe :) in final i discover a new planet :))
Big succes :P 
https://github.com/bit2gb/TSN-Ranksystem/commit/97d2b66b197e9d0223ab14c6a3244966cafa14ad

**Comment by bit2gb** [comment]
if i want to publish new poll how i do that?
