### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by batizisanya** [Newcomer1989/TSN-Ranksystem#262]
Hello, is there any chance or option to update from 1.0.2 to 1.2.2? 
I realy don't want to lose all user stats and ranks.

**Comment by Shad86** [comment]
Sure just backup all of your files (database from the ranksystem) and the take the latest Version from git, because unfortunately, the site seems to be down at the moment.

regards

Shad86

**Comment by batizisanya** [comment]
And than just inport to the new database?

**Comment by Shad86** [comment]
usually you pull it over the "old one" and the database update it to the newest - thats why you should update, so that you have a backup of it in case something gets corrupted
