### ISSUE TITLE
TS-N Site partially broken

### ISSUE THREAD

**Issue by Shad86** [Newcomer1989/TSN-Ranksystem#263]
Hey,

@Newcomer1989  the site is partially broken and because i didn't know if you still get e-mails i let you this hint here on Github.

regards

Shad86

**Comment by KamoiChikubi** [comment]
http://ts-n.net/ranksystem.php

This page is not being loaded. I just need the instructions on how to make the bot run again. Recently reinstalled it and it's not working.

**Comment by Shad86** [comment]
needed packages are:

php-zip php-curl php-libapache2-mod-php5.6

or for php7

php7.0-zip php7.0-curl "php7.0-xml or if its not working php7.0-libapache2-mod-php7.0"

for windows:

php com extension

**Comment by KamoiChikubi** [comment]
Ah yes I was missing com. Thank you!
