### ISSUE TITLE
Bot läst sich nicht starten

### ISSUE THREAD

**Issue by neomlt** [Newcomer1989/TSN-Ranksystem#265]
Hallo erstmal 
Betriebsystem: Winserver 2008 R2
Webserver: Xampp ( COM extention hinzugefügt )

Ordner Ranksytem hat ( Cmod 777 und ist Freigegeben wie in post 211 beschrieben )
Wenn ich jetzt versuche denn Bot über das webinterface zu starten passiert einfach nix kein log kein start.

Ich habe jetzt schon 30 min mit dem lieben Shad86 rumprobiert aber es geht irgendwie nicht bitte um Hilfe

Grüße Neo

TS: 136.243.20.162  ( Ansprechspartner NEOMlT / Jan )

**Comment by bit2gb** [comment]
I help you but please write in english your problem or question

**Comment by neomlt** [comment]
have you time for temaspeak

**Comment by neomlt** [comment]
Hello 

Okay i try it becaus my english ist bad

I have a Dedicated Rootserver with Windowsserver 2008 R2 and a webserver with xampp ( i addet the COM extension )

With Filezila i have add the Cmod to 777 for the folder ranksystem and give it free for the network see post https://github.com/Newcomer1989/TSN-Ranksystem/issues/211

When is start now the bot with the webinterface it dosent sart and dont have a log !
When is start it whit cmd it gives my this error http://www.bilder-upload.eu/show.php?file=cf7630-1488192664.png

best regards
 Neo

**Comment by bit2gb** [comment]
Ok from your print screen i can see an error. Pear package is not instaled on your xampp configuration so read this article
http://pear.php.net/manual/en/installation.getting.php

**Comment by neomlt** [comment]
I have luck at my xampp folder and found a pear folder,
I think it is installed

**Comment by bit2gb** [comment]
You make all steps from link gived to you in my last post?

**Comment by neomlt** [comment]
Ok i have it 
the error was in xampp php.ini

;;;;;;;;;;;;;;;;;;;;;;;;;
; Paths and Directories ;
;;;;;;;;;;;;;;;;;;;;;;;;;

; UNIX: "/path1:/path2"
#include_path=C:\xampp\php\pear\
;
; Windows: "\path1;\path2"
include_path = ".;c:\php\includes"
;

i have change it and it works 

Thanks for you Help 

And Thanks to MƠƝƧƬЄƦ010
