### ISSUE TITLE
Bot Funktionen

### ISSUE THREAD

**Issue by neomlt** [Newcomer1989/TSN-Ranksystem#266]
Hallo

Ist es möglich bei 3000sec 2 Server gruppen zugeben und nur eine wird bei 3100 geändert ?

Z.b.   3000sec level 4 und communitymitglied und bei 3100sec level 5 

Grüße Neo

**Comment by Shad86** [comment]
Leider muss man derzeit dafür ein 2.tes ranksystem anlegen, da immer nur eine Gruppe vergeben werden kann

**Comment by bit2gb** [comment]
In future please post in english your problem if you wont support from all people because in german is dificult for some users!
And no, is not posible to set 2 different group
