### ISSUE TITLE
Experimental and whats in there

### ISSUE THREAD

**Issue by Shad86** [Newcomer1989/TSN-Ranksystem#273]
**Since 25 Feb 17, newcomer doesn't respond anymore anywhere, so i try to keep it updated as best as possible in a separate Branch: https://github.com/Newcomer1989/TSN-Ranksystem/tree/Experimental**

These are changed things since he disappear:

- Allow verification via direct link, german translation, fix assign groups, restart button #244
- Added 2 seconds delay to ts.php for low-end servers #255
- fixed config.tsvoice type #268 (Added UNSIGNED to field config.tsvoice so it can handle ports > 32767.)
- changed icons to tsicons (icons got sometimes redirected to a wrong internal folder)
- fixed missing/wrong redirects for list_rankup and assigner addon "icons -> tsicons" (april 06'17)
- fixed icons checks to tsicons checks (april 07'17)

**Comment by Shad86** [comment]
- fixed missing/wrong redirects for list_rankup and assigner addon "icons -> tsicons"

**Comment by Shad86** [comment]
- fixed icons checks to tsicons checks

**Comment by Shad86** [comment]
- fixed redirect for Nederland

**Comment by Newcomer1989** [comment]
Closed due the most things are inside the 1.2.3 release version.
