### ISSUE TITLE
upgrade to latest version 

### ISSUE THREAD

**Issue by makkawy** [Newcomer1989/TSN-Ranksystem#274]
hello ..
i'm on :
current version: 1.0.2
how can i upgrade to new version: 1.2.2

i see website is broken and i cant see steps for upgrade can any one explain it ? 

thank you

**Comment by bykidi** [comment]
Do a folder backup, database backup, get latest version from here https://github.com/Newcomer1989/TSN-Ranksystem/archive/master.zip
and start the experiments.
