### ISSUE TITLE
Der Bot startet nicht und keine Logs

### ISSUE THREAD

**Issue by DerJanikGurke** [Newcomer1989/TSN-Ranksystem#276]
Hallo ich habe ein Problem mit dem Starten von dem Bot! Ich habe Windows (Plesk) und ich kapiere die Anweisungen in #211 nicht nachvollziehen!

Danke im Vorraus!

**Comment by Shad86** [comment]
Für Windows kann ich leider keine Hilfe anbieten, wenn dir kein anderes OS zur Verfügung steht, kann ich anbieten es dir zu hosten, dazu kannst du mich gerne auf dem ts-n.net teamspeak kontaktieren "Shad86"
