### ISSUE TITLE
Statistik - keine aktive zeit

### ISSUE THREAD

**Issue by Komakalle** [Newcomer1989/TSN-Ranksystem#278]
wie man auf dem folgenden bild sieht, wird auf der stats seite keine aktive zeit angezeigt, ich weiß aber nicht warum nicht. hoffe ihr könnt mir helfen. 
https://i.gyazo.com/741072e83ff24c9b1380b1ac6f9acb68.png

At the stat page there is no active time shown, no idea why.

**Comment by Shad86** [comment]
Die Frage wäre, welche Version des Ranksystems du nutzt - denn in meiner letzten Version wird aktive Zeit "generiert"

**Comment by Komakalle** [comment]
Ganz vergessen, hat sich erledigt, nach der Zeit X gings dann...
