### ISSUE TITLE
Kann ich nicht https://ts-n.net/

### ISSUE THREAD

**Issue by Bl4CkGuuN** [Newcomer1989/TSN-Ranksystem#279]
Hey,

ich kann seit geräumiger Zeit nicht mehr auf die Homepage bzw. wird da nichts mehr angezeigt..

Woran liegt das?

Greetz

**Comment by monster010** [comment]
Das kann dir niemand wirklich sagen, wie alle weiß ich nur das NewComer aktuell nich zu erreichen ist, weswegen wir tippen das auch die Homepage nicht funktioniert.

**Comment by Bl4CkGuuN** [comment]
Achso ok, danke!

Mein Bot schmiert die ganze Zeit ab und ich brauche den Cronjob, hast du den vielleicht? :D 

Greetz

**Comment by mightyBroccoli** [comment]
```
@reboot php /path/to/ranksystem/worker.php start >/dev/null 2>&1 
*/15 * * * * php /path/to/ranksystem/worker.php check >/dev/null 2>&1
```

I am using these two cronjobs. The first one is starting the bot after a reboot occured and the second one is cheching the bot every 15 mins.
The /dev/null 2>&1 at the end is just to mute the output you could mail the output to yourself but in most cases it is not worth it.

**Comment by Bl4CkGuuN** [comment]
Cool, thank you :)
