### ISSUE TITLE
Next Rank Up time 0

### ISSUE THREAD

**Issue by mobzftw** [Newcomer1989/TSN-Ranksystem#28]
I updated to version 1.0.0 and I'm having a few issues. One of them is the "Next Ranks Up" time showing 0 instead of the proper format (0 days, 0 hours, 0 mins). 

Any ideas?

Image: http://puu.sh/oAm0m/f8eeeda2e6.png

Page: http://ranks.mobz.ws/list_rankup.php

**Comment by Newcomer1989** [comment]
That are two problems.. Please open for the second problem another issue. After it I will answer you.
