### ISSUE TITLE
 Error 0: php_network_getaddresses: getaddrinfo failed: Name or service not known

### ISSUE THREAD

**Issue by Artapel** [Newcomer1989/TSN-Ranksystem#280]
Hi Guys

Thank you very much for your awesome RankSystem! Id love to start using it.
ive got the site running and everything seems good. All my settings are configure but the bot wont start yet.

I get the following error when starting the bot (IP address changed to a bunch of 0`s)

2017-03-16 21:20:09.261546   ERROR     Error 0: php_network_getaddresses: getaddrinfo failed: Name or service not known
2017-03-16 21:20:09.197410   INFO      Connect to TS3 Server (Address: "000.000.000.000" Voice-Port: "9999" Query-Port: "10011").
2017-03-16 21:20:09.197379   INFO        Ranksystem Version: 1.2.1
2017-03-16 21:20:09.197318   INFO        Check files permissions [done]
2017-03-16 21:20:09.193789   INFO        Check files permissions...
2017-03-16 21:20:09.192677   INFO        No newer version detected; Database check finished.
2017-03-16 21:20:09.192614   INFO      Check Ranksystem database for updates.
2017-03-16 21:20:09.188502   INFO      Initialize Bot...

I have another basic bot running from this server that works fine. I can telnet to the server on port 10011 and dish out commands without hassle.

Running on 3.10.0-327.18.2.el7.x86_64 GNU/Linux CentOS
Other services on the server also runs fine.

I also tail -f the teamspeak logs to check for a login, but it does not seem to hit the teamspeak server.
Although my other bot (On the same webserver) polls my teamspeak server just fine. (Using the same ip src ipaddress, dst ipaddress, query port and UDP port)

**Comment by Artapel** [comment]
Just to show some testing 

[fatty@localhost htdocs]# telnet 000.000.000.000 10011
Trying 000.000.000.000...
Connected to 000.000.000.000.
Escape character is '^]'.
TS3
Welcome to the TeamSpeak 3 ServerQuery interface, type "help" for a list of commands and "help <command>" for information on a specific command.

I did this on the CLI, but the error i copied was taken from the webinterface

**Comment by Shad86** [comment]
Hello,

Name or service not known = not reachable

check your host file and also nameservers if you connect on the public ip.

If your teamspeak and ranksystem is on the same system i would recommend to use 127.0.0.1

regards

Shad86

**Comment by Artapel** [comment]
I am using the IP address. not DNS
Hostfile although i did use the DNS name in earlier testing and i did do a manual entry into the hosts file.
Pointless posting the /etc/hosts here as i have to start out all the relevent info. 

DNS1="192.168.0.254" (My local DNS)
DNS2="8.8.8.8"

**Comment by Artapel** [comment]
TS and Rank system is on two different machines

**Comment by Artapel** [comment]
Does anyone have any suggestions please?
@Newcomer1989

**Comment by Artapel** [comment]
Oky so in the meantime i tried it on another server CentOS 7.2 with php55w (including all the needed php packages) but im still getting the same message/problem. Still using the IP address.

Can you share your exact environment where the  the rankbot runs fine in? 
Stuff like linux version, exact php modules. Exact apache, httpd packages. etc...
 
o also delete and reconfigure everything on both my linux servers. Im sure it has something to do with php, but i cannot figure out what.

**Comment by Shad86** [comment]
Minimal requ. Is PHP 5.6 with pdo Support.
Other needed php modules: curl,zip,xml,cli

and as already said:
Name or Service Not know means that your Service isnt reachable

The dev (newcomer) which usually made it isnt available since 3-4 weeks

**Comment by Artapel** [comment]
Oky so i upgraded php to 5.6

 php -v
PHP 5.6.30 (cli) (built: Jan 19 2017 22:31:39)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies

Same thing. My other bot on the same server works perfectly still. Just the TSN Rankbot with the same problem 

Package curl-7.29.0-35.el7.centos.x86_64 already installed and latest version
Package zip-3.0-11.el7.x86_64 already installed and latest version
yum list installed | grep php
php56.x86_64                       2.1-5.el7.remi                     @remi-safe
php56-php-cli.x86_64               5.6.30-1.el7.remi                  @remi-safe
php56-php-common.x86_64            5.6.30-1.el7.remi                  @remi-safe
php56-php-pear.noarch              1:1.10.3-1.el7.remi                @remi-safe
php56-php-pecl-jsonc.x86_64        1.3.10-1.el7.remi                  @remi-safe
php56-php-pecl-zip.x86_64          1.13.5-1.el7.remi                  @remi-safe
php56-php-process.x86_64           5.6.30-1.el7.remi                  @remi-safe
php56-php-xml.x86_64               5.6.30-1.el7.remi                  @remi-safe
php56-runtime.x86_64               2.1-5.el7.remi                     @remi-safe
php56w.x86_64                      5.6.30-1.w7                        @webtatic
php56w-cli.x86_64                  5.6.30-1.w7                        @webtatic
php56w-common.x86_64               5.6.30-1.w7                        @webtatic
php56w-gd.x86_64                   5.6.30-1.w7                        @webtatic
php56w-mysql.x86_64                5.6.30-1.w7                        @webtatic
php56w-pdo.x86_64                  5.6.30-1.w7                        @webtatic
php56w-xml.x86_64                  5.6.30-1.w7                        @webtatic
php56w-xmlrpc.x86_64               5.6.30-1.w7                        @webtatic

**Comment by Shad86** [comment]
excuse me if im blind but cant see th php-curl package (only normal curl) the php-curl is also needed

**Comment by Shad86** [comment]
next thing is.

try the both ways:

try to connect to your ts3 with your domain (for example ts3-domain.com) and if this isn't working try to connect with the ip (for example "1.2.3.4")

and always be sure the given ports are right and that you may not limited from your firewall in anyway.

regards

**Comment by Shad86** [comment]
Also important if your port is higher then 32767 you need the experimental branch.

So be sure that all that things fit and are correct and oh yes be sure you use the latest version..

**Comment by Artapel** [comment]
zip and curl are part of php56w-common

php56w-common	php-api, php-bz2, php-calendar, php-ctype, php-curl, php-date, php-ereg, php-exif, php-fileinfo, php-filter, php-ftp, php-gettext, php-gmp, php-hash, php-iconv, php-json, php-libxml, php-openssl, php-pcre, php-pecl-Fileinfo, php-pecl-phar, php-pecl-zip, php-reflection, php-session, php-shmop, php-simplexml, php-sockets, php-spl, php-tokenizer, php-zend-abi, php-zip, php-zlib

Kwl

Ports are all default and are effeminately accessible. 
Im using TSN Ranksystem - Webinterface 1.2.2

Im still scratching around to see what else i can see out of place

**Comment by Artapel** [comment]
Can someone please share a link to the minimum requirements.
Also can someone please share the original install instructions

**Comment by Shad86** [comment]
As posted already but here as a picture...

Even if there stands 5.5 as minimal req you should use at least 5.6 - Because 5.5 has no support at all (eol) (security risk) -> http://php.net/supported-versions.php

![minimal-requ](https://cloud.githubusercontent.com/assets/18570683/24167940/e968d644-0e78-11e7-83aa-15e2dc2bfc6e.PNG)

**Installation is relative simple:**

_download it_

_move it on an webspace_

_untar/unzip it_ (if you didn't already)

_give_ "`chmod 777`" _on the following folders/data ->_ other/dbconfig, update, avatars, icons, logs

_use chown to give the ranksystem the right webuser usually the standart is www-data_

_so as an example:_ `chown www-data:www-data /var/www/html/ranksystem -Rf`

_create a mysql or maria_ (mariadb is only support up to 10.0 on higher versions you may run into troubles) _database access_ (if you don't have anyone yet)

_got to your browser and go to_ http://yourdomain.com/path/to/ranksystem/install.php

_follow the instructions._

_now you can login and setup all the other needed things._

**optional:**

create a cronjob 

As an example(check every 10min if the ranksystem is running):

*/10 * * * * sudo -u www-data php /var/www/html/ranksystem/worker.php check >/dev/null 2>&1

regards

**Comment by Artapel** [comment]
Yea my installation was done to the book. I did not see the instructions before now, but just did as it as i thought best.
Can i ask where you got the "Requirements" screenshot/photo from?

P.S no luck yet. I installed it on two different linux server. I connected to two different teamspeak servers. And i used DNS and the IP address. I even created more Teamspeak Virtual Server on different ports, just for testing purposes.

**Comment by Shad86** [comment]
was on some github post here.

I dont know what is going on with your system, never had any issues on a linux system.

**Comment by Artapel** [comment]
Note sure if im going backwards or making progress. Ive not gotten to the point where my apache logs shows the following 

[Sun Mar 26 13:44:52.832392 2017] [:error] [pid 130143] [client ipaddress:21023] PHP Notice:  Undefined variable: mysqlcon in /htdocs/webinterface/index.php on line 60
[Sun Mar 26 13:44:52.832674 2017] [:error] [pid 130143] [client ipaddress:21023] PHP Fatal error:  Call to a member function query() on a non-object in /htdocs/webinterface/index.php on line 60

here is my PHP installed packages. I did restart apache a few times after replaceing php 5.6 with php 7

yum list installed | grep php
php70.x86_64                       1.0-5.el7.remi                     @remi-safe
php70-php.x86_64                   7.0.17-1.el7.remi                  @remi-safe
php70-php-cli.x86_64               7.0.17-1.el7.remi                  @remi-safe
php70-php-common.x86_64            7.0.17-1.el7.remi                  @remi-safe
php70-php-dba.x86_64               7.0.17-1.el7.remi                  @remi-safe
php70-php-json.x86_64              7.0.17-1.el7.remi                  @remi-safe
php70-runtime.x86_64               1.0-5.el7.remi                     @remi-safe
php70w-cli.x86_64                  7.0.16-1.w7                        @webtatic
php70w-common.x86_64               7.0.16-1.w7                        @webtatic
php70w-gd.x86_64                   7.0.16-1.w7                        @webtatic
php70w-mbstring.x86_64             7.0.16-1.w7                        @webtatic
php70w-mcrypt.x86_64               7.0.16-1.w7                        @webtatic
php70w-mysql.x86_64                7.0.16-1.w7                        @webtatic
php70w-pdo.x86_64                  7.0.16-1.w7                        @webtatic
php70w-xml.x86_64                  7.0.16-1.w7                        @webtatic
php70w-xmlrpc.x86_64               7.0.16-1.w7                        @webtatic

Any ideas?

**Comment by Shad86** [comment]
I come more and more to the point that the Server itself is messed up.

i did 3 installations in the last time and there wasn't any errors or problems. But well i also had only Debian systems, so i don't know if its a main centos issue (which isn't resolvable then) or if only your Server setup is messed up.

regards

**Comment by Artapel** [comment]
On Which OS did you do the installation?

I’ve actually spun up a new CentOS7.2 VPS. So it seems the only problem I’ve now got is that last error I’ve sent.

Also I see that the http://ts-n.net/ranksystem.php install instructions page is broken. So I can’t follow that. P.S I know about the issue that you open regarding this. Waiting for Newcomer to help.

Regards

**Comment by Shad86** [comment]
I did the installation on a Debian 8 system

**Comment by Artapel** [comment]
Thank you for your help thus far. I do appreciate your effort!

Il just boot up a copy of Ubuntu and do it with that. Hope i can get it to work on there. 
I really hope he is coming back. This is a awesome project and ive got some ideas that might help it forward.

**Comment by Shad86** [comment]
With Ubuntu i can definitely help you, if it comes to trouble.

If you can code, then you always can make a pull request into the "Experimental Branch" because i still can merge things, but i don't want to merge new things into the stable.

**Comment by Shad86** [comment]
If you have again any problems feel free to open a new issue thread, this one is already really long, so it is better to make a new issue, if it comes to trouble-

regards

Shad86

**Comment by Artapel** [comment]
I would like to update this.

I managed to get the bot working after 5 months worth of fighting it.
The error message has nothing at all to do with the problem.

The problem is that the server query password was to long and it seems the rankbot refused to accept it but did not display a error referring to this.

Changing the password to a shorter password resolved the issue.
