### ISSUE TITLE
Bot no remove grades and recalc stats for some users

### ISSUE THREAD

**Issue by bit2gb** [Newcomer1989/TSN-Ranksystem#284]
Hello guy, i have a problem with bot.
1. I put a backup to ts3 server and after that for players who are conected in moment of ts3 restart total stats was been recalc
2. If i have grad x recive at 1h and i give me from ts3 server grade y who is for 2h , bot dont remove y grade but i dont understand why!

And for example i have lines like this
User 'BIT' (unique Client-ID: AyGsA2fpPpxoLUJ+AeJLpuCIsUo=) got a new TeamSpeak Client-database-ID (6088). Update the old Client-database-ID (1243) and reset collected times!

**Comment by Shad86** [comment]
thats correct.

If you wont do fullbackups of your teamspeak or your backupsystem wont backup the database-ID and users get a new database-id, then the ranksystem on his standart settings resets them.

If there is no other way of doing a backup then you have to disable the reset of database-id if users get a new one under core
![database-id](https://cloud.githubusercontent.com/assets/18570683/24333985/76d739e8-1262-11e7-9737-625150cadc25.png)

**Comment by bit2gb** [comment]
ok i disable that and i restart but if i assign for me an grade for 100h but i have only 5 , bot dont do anything

**Comment by Shad86** [comment]
So you tried to add time to yourself?

Be sure that the unique-id on the ranksystem is the same you have on teamspeak.

**Comment by bit2gb** [comment]
Is possible for bot to have problem for ts3 permision? Because I set for bot other ts3adress all work fine

**Comment by Shad86** [comment]
Can be, sometimes the query rights brake. 

Also always be aware, if you remove Server Admin from the User which made the query login the query rights get revoked.

here i found an pic about the ts3 rights.

![minimal-requ](https://cloud.githubusercontent.com/assets/18570683/24167940/e968d644-0e78-11e7-83aa-15e2dc2bfc6e.PNG)

regards

Shad86
