### ISSUE TITLE
!!!! Logs folder is not writable !!!! (Froxlor)

### ISSUE THREAD

**Issue by Bl4CkGuuN** [Newcomer1989/TSN-Ranksystem#286]
Hey,

I tried to move to ranksystem to an other Server and I get the error that the Logs folder not writable is..
(ofc I did chmod 777 logs and checked it in winscp, it should be writable)
But only if I import my old table for the stats.
If I do an clean installation they say that there is missing cURL, idk why... it is installed.
If I want to install php5-curl, I get the message that it is already on the newest version.

I'm using debian 8
I can't fix it, so I need your help!

Greetz

**Comment by Shad86** [comment]
be sure the folders have also the webuser set, because over the webinterface it gets started from the common webuser.

Also be sure the path to the logfolder is the same and you didnt choosed another folder path on your old server.

about curl be sure you'r using the right php version.

`php -v` should give you the output witch php you'r currently using.

regards

Shad86

**Comment by Bl4CkGuuN** [comment]
How can I set the folders to the webuser?
On my old server I installed it over PLESK,
now I use froxlor and it is ofc in an other path, but only to the ranksystem.
before: /rank
now: /var/customers/webs/rank

I'm using PHP 5.6.30 (cli) (built: Mar 13 2017 17:16:26)

Greetz

**Comment by Shad86** [comment]
then check your logpath under in your webinterface under "other" or "anderes" -> i think that one should be the right one:
`/var/customers/webs/rank`

be sure that the logs folder is writable chmod 777 logs/

same for (chmod 777) the folders

avatars -- icons or tsicons -- update -- other/dbconfig.php

about the webuser - i do not know what kinda standart webuser froxlor is using but usually and if the ranksystem is really using that one:

but the mostly "www-data" is a common standart webuser

chown www-data:www-data rank/ -Rf (if its www-data)

regards

Shad86

**Comment by Shad86** [comment]
Edit some things, you may have to re-read it

**Comment by Bl4CkGuuN** [comment]
Okay, there was the wrong logpath...

It's creating this log now: "CRITICAL  PHP cURL is missed. Installation of PHP cURL is needed! Shuttin down!"
So i tried again to install PHP cURL with "apt-get install php5-curl", but it says to me again, that php5-curl is already on the newest version...

**Comment by Shad86** [comment]
hm..
usually uncommon but you also tried:

apt-get install php5.6-curl

and as i said above after installing it you also restarted your webserver?

Also make sure you if you may have to activate it over config (not quite sure how froxler manages extensions)

**Comment by Shad86** [comment]
you may also try to install only curl -> sudo apt-get install curl

then

`sudo service apache2 restart`
or
`service apache2 restart`

**Comment by Shad86** [comment]
if that also not helps take a look into the phpcommand.php and set the right path to your php5.6 location

**Comment by Shad86** [comment]
> ## Uncomment the command you need to run PHP
> ## This are only examples
> ## If you miss one, feel free to add it
> ## Only one command should be active at the same time!
> $phpcommand = "php";
> #$phpcommand = "php56";
> #$phpcommand = "php70";
> #$phpcommand = "/usr/bin/php5";
> #$phpcommand = "/usr/bin/php";
> #$phpcommand = "C:\PHP5\php.exe";
> #$phpcommand = "C:\PHP7\php.exe";
> #$phpcommand = "c:\wamp\bin\php\php.exe";

If you want to change things on it then maybe like:

## Uncomment the command you need to run PHP
## This are only examples
## If you miss one, feel free to add it
## Only one command should be active at the same time!
'$phpcommand = "php";
#$phpcommand = "php56";
#$phpcommand = "php70";
$phpcommand = "/my/Path/to/php5";
#$phpcommand = "/usr/bin/php";
#$phpcommand = "C:\PHP5\php.exe";
#$phpcommand = "C:\PHP7\php.exe";
#$phpcommand = "c:\wamp\bin\php\php.exe";

**Comment by Bl4CkGuuN** [comment]
Yep, I restartet the webserver.


E: Unable to locate package php5.6-curl
E: Couldn't find any package by regex 'php5.6-curl'

apt-get install curl didn't worked either

With froxlor I installed an ebot and a teamspeak interface, without any changes in config from froxlor.
The ebot uses php5-curl

**Comment by Bl4CkGuuN** [comment]
I will try this

**Comment by Bl4CkGuuN** [comment]
There a some more writeable errors ~15
`WARNING       File is not writeable /var/customers/webs/rank/other/session.php`
Is that normal?  So then I would give them the permissions :P

**Comment by Shad86** [comment]
what user does that folder have? - because the rest of it should work without any chmod changes

**Comment by Shad86** [comment]
if you want, you also can visit the ts3 -> ts-n.net

regards

Shad86

**Comment by Bl4CkGuuN** [comment]
I created a 'tsn' user for that /var/customers/webs/rank is the homedirectory

**Comment by Bl4CkGuuN** [comment]
How I fixed it:
changed the logpath in the webinterface to: `/path/to/the/ranksystem/logs/` ex. `/var/customers/webs/rank/logs/`

placed in other/phpcommand.php  a '#' in front of `$phpcommand = "php";` and removed the '#' there : `#$phpcommand = "/usr/bin/php5";`

at least: `chown www-data:www-data /path/to/the/ranksystem/ -Rf`

Thanks for the help @Shad86

**Comment by Shad86** [comment]
deleted some unneeded comments.

your welcome @Bl4CkGuuN 

regards

Shad86

**Comment by FreakyFP** [comment]
Hier das selbe problem nur mir plesk lässt sich nicht fixen

**Comment by Newcomer1989** [comment]
I think all is done here. If not feel free to reopen this issue!
