### ISSUE TITLE
Bot start problem with wamp

### ISSUE THREAD

**Issue by NimaGame** [Newcomer1989/TSN-Ranksystem#287]
Hi.
I have a problem with rank bot system.
It doesn't get started and it has no logs.
But it works when I use it from jobs/bot.php
Can you please help me?
Thank you.
And sorry for my bad english.

**Comment by Shad86** [comment]
Be sure the `php_com_dotnet.dll` is added (ext folder) / activated (php.ini).

Next things is, take a look at here: #265

Last but not least, for Windows isn't really a support available, unfortunately you have to get it on your own.

regards

Shad86

**Comment by NimaGame** [comment]
Hi, thanks for you answer.
No I use xampp too but it doesn't works like wamp.
