### ISSUE TITLE
Cannot send session cookie

### ISSUE THREAD

**Issue by Taxick** [Newcomer1989/TSN-Ranksystem#289]
Hi.

First, i want to say thanks for the nice script. 

I have a problem when I log in to the web interface! (Not the front page)

**I get this error when I log into the web interface and go to the "core" tab**

```
Warning: session_start() [function.session-start]: Cannot send session cookie - headers already sent by (output started at /var/www/halfdaner.dk/rank/webinterface/core.php:1) in /var/www/halfdaner.dk/rank/webinterface/core.php on line 2

Warning: session_start() [function.session-start]: Cannot send session cache limiter - headers already sent (output started at /var/www/halfdaner.dk/rank/webinterface/core.php:1) in /var/www/halfdaner.dk/rank/webinterface/core.php on line 2

Warning: Cannot modify header information - headers already sent by (output started at /var/www/halfdaner.dk/rank/webinterface/core.php:1) in /var/www/halfdaner.dk/rank/webinterface/core.php on line 36
```
If i go to this /webinterface/other.php, /webinterface/bot.php,/webinterface/stats.php,  /webinterface/admin.php -> the same errors show, but just with the other names (The line numbers are the same)

Any ide whats is wrong???

I'm using PHP 7, MySQL 5.5

// Taxick

**Comment by Shad86** [comment]
Its a warning but as long as newcomer is away (currently he was/is away since 4-5weeks), you have to try to fix it by your own

**Comment by Taxick** [comment]
Ok, I will have to wait then. I have try to fix it, but I can't...

**Comment by Newcomer1989** [comment]
Sorry, a very long time is gone, but I want to come back to your question.

The Ranksystem starts a session. Thats a normal functions on PHP, which is needed to authenticate and secure an login area. The session will be build on serverside and after that send to the client.

On each site the session is needed, the session needs to check `session_start();`. Be sure you have nothing changed on that position. The `session_start();` needs to be the first thing after `<?PHP`. It is important there is nothing else in front, not even a simple space. Only the `<?PHP` and line breaks are allowed.

For best case try to download and install the Ranksystem again. At least change all files inside the folder "webinterface" with the official ones from the fresh download.

**Comment by Taxick** [comment]
Hi @Newcomer1989 

First. Thanks for your reply and then welcome back. Hope you are ok!

A fresh download fixed the problem :)
