### ISSUE TITLE
Connection Lost - 97% CPU Usage

### ISSUE THREAD

**Issue by MadMarco97** [Newcomer1989/TSN-Ranksystem#29]
I dont know, but probably this is the reason for the connection losts of the bot.

Look at this:

https://www.dropbox.com/s/ydzsmyy8ulphyzy/Screenshot%202016-04-30%2012.31.31.png?dl=0

I watched the Bot in the last few days, and i noticed that if the CPU usage recht almost 100% it disconnects.

Probably it helps you for some Bugs to be fixed. Just sayin' ;)

MFG Marco

**Comment by Newcomer1989** [comment]
Inside the webinterface you have an option for a slowmode.

Change this to a high delay to prevent a high cpu usage.
After this, there are also for a longer time that high cpu usage?

**Comment by MadMarco97** [comment]
I'll gonna test this... brb

**Comment by MadMarco97** [comment]
Seems to be good for now.

It stays at 0.3% CPU Usage

**Comment by MadMarco97** [comment]
The bot is now longer online, but goes up to ~50% CPU an then "connection lost"
