### ISSUE TITLE
PHP Fatal Error Function mime_content_type()

### ISSUE THREAD

**Issue by fabm3n** [Newcomer1989/TSN-Ranksystem#290]
Hallo
Ich habe meinen Webserver von Linux auf Windows umgezogen. Nun bekomme ich im Apache Error Log Immer wenn ich die stats index seite aufrufe folgenden fehler: PHP Fatal error:  Call to undefined function mime_content_type() in C:\\Users\\Applikationen\\Documents\\webspace\\apache2\\htdocs\\stats\\index.php on line 391

Außerdem werden die Stats nicht mehr richtig angezeigt siehe Bild: https://puu.sh/vjXmh/25c0743d14.png

Außerdem gibt es noch folgenden Fehler im Error log
PHP Notice:  Undefined offset: 3330 in C:\\Users\\Applikationen\\Documents\\webspace\\apache2\\htdocs\\stats\\list_rankup.php on line 386
da ändert sich immer mal wieder die ofset nummer und die line wechselt manchamle zu 389.

Danke für eure Hilfe im voraus.

**Comment by monster010** [comment]
Aktivier die PHP Erweiterung fileinfo dann sollte es gehn

**Comment by fabm3n** [comment]
Jop danke. Das geht. Jetzt habe ich immer noch das Problem mit dem PHP Notice

**Comment by Shad86** [comment]
Wird die Statistik nun aber Dargestellt? Oder ist diese auch weiterhin nicht verfügbar?

Denn ab mariadb 10.1 oder höher (laut meinem letzten Wissenstand) kann es genau zu diesem Problem kommen, das gewisse Statistiken nicht mehr dargestellt werden.

Kann inzwischen auch wieder behoben sein durch mariadb updates aber damals war es ab einer gewissen mariadb version so das Statistiken nicht mehr angezeigt wurden (zumindest die Servernutzung, war damals dann gebrochen)

**Comment by fabm3n** [comment]
Wird wieder alles angezeigt und es wird mysql verwendet. Der Fehler ist ja nur im Apache Error Log

**Comment by monster010** [comment]
Der Fehler kommt daher, dass er versucht die Gruppen ID eines Users in einem Array zu findet, diese aber nicht im Array existiert.

**Comment by fabm3n** [comment]
Und wie kann ich das beheben?

**Comment by Shad86** [comment]
hm.. bei einem Snapshot ändern sich glaube ich die ID's das wäre also eventuell möglich

**Comment by monster010** [comment]
nein, da beim ts umzug auch die datenbank mitgenommen wurde

**Comment by fabm3n** [comment]
Die Teamspeak Client DB wurde nicht mitgenommen. Es wurde auf einen frischen TS gewechselt.

**Comment by monster010** [comment]
dann kann es sein, das er die id nich findet

**Comment by Shad86** [comment]
@monster010, falls du Zeit hast schau mal in dein Github postfach

Grüße

Shad86

**Comment by fabm3n** [comment]
Jop habe ich ausgeschalltet. So hatte @Newcomer1989 es mir erklärt. Ich schließe dann das issue mal.
