### ISSUE TITLE
Getting "Write permission failed on folder update" even though it's 777.

### ISSUE THREAD

**Issue by Helyux** [Newcomer1989/TSN-Ranksystem#292]
I'm getting following error:
![image](https://cloud.githubusercontent.com/assets/10271600/25283115/f4cea4e4-26b2-11e7-934c-77aa38478715.png)

Even though as you also can see below i chmod 777 the complete Folder + Subfolders.
![image](https://cloud.githubusercontent.com/assets/10271600/25283298/92cf481a-26b3-11e7-9216-08c663767b5a.png)

I restartet the apache service but it didnt help, i'm still getting the mentioned error.
What to do to clear things up?

**Comment by Shad86** [comment]
how did you start the whole thing?

**Comment by Helyux** [comment]
as described under "Installation Linux":
1. Downloaded the zip to my Windows 7 PC
2. Uploaded the content of the zip to my Server 
3. Gave the Webuser ownership with "chown -R www-data /var/www/html/elisium/tsrank"
4. Visited install.php in my Browser.

Version 1.2.2

**Comment by Shad86** [comment]
So you never got over the install process? Because i asked how you started it.

**Comment by Shad86** [comment]
you also did  strg+F5 / ctrl+F5 on your Internet browser to be sure that it isn't a cache issue on your browser.

you also can come onto the ts-n.net teamspeak if you want, then i can take a closer look on it

**Comment by KILLERMANTV** [comment]
> So you never got over the install process? Because i asked how you started it.
> 
> and also try again
> 
> `chmod 777 update/ -Rf`
> 
> and
> 
> `chown www-data:www-data update/ -Rf`





> you also did strg+F5 / ctrl+F5 on your Internet browser to be sure that it isn't a cache issue on your browser.
> 
> you also can come onto the ts-n.net teamspeak if you want, then i can take a closer look on it

Didn't work.

**Comment by Newcomer1989** [comment]
This issue is closed. Please open a new issue and share us information about your environment.
