### ISSUE TITLE
Some scripts & fonts blocked by uBlock Origin

### ISSUE THREAD

**Issue by bykidi** [Newcomer1989/TSN-Ranksystem#294]
Must be mistake from uBlock, but i think that paths/names for scripts/fonts should be changed to avoid blocking.
![default](https://cloud.githubusercontent.com/assets/1337953/25434292/63f47ea4-2a94-11e7-9a0e-a16464d7b916.PNG)

**Comment by Shad86** [comment]
Sorry, but that's a thirdparty problem not a problem of the ranksystem.
