### ISSUE TITLE
Problem with the servergroups 

### ISSUE THREAD

**Issue by reyollc** [Newcomer1989/TSN-Ranksystem#295]
Do not know what to do. Everytime i started the bot or reinstall the bot i become this issue.
2017-04-28 11:52:35.270685   ERROR     calc_user 10:Es ist ein Problem mit den Servergruppen des Users 'BlackStar24' (eindeutige Client-ID: nmbVrxT+yBVFPMoTt6qL77lYVKE=; Client-Datenbank-ID 6) aufgetreten!
and this is not the only user who hase the Problem 

![unbenannt](https://cloud.githubusercontent.com/assets/28141191/25524392/ad395266-2c0a-11e7-8f80-1ba9a9a029a5.PNG)

**Comment by reyollc** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/28141191/25524472/fda39338-2c0a-11e7-9a1e-24b2341d2625.PNG)

**Comment by Shad86** [comment]
Kontrolliere mal ob die Servergruppen tatsächlich existieren / vergebbar sind.

**Comment by reyollc** [comment]
Hat ja damals auch geklappt

**Comment by reyollc** [comment]
Ich schau gleich nocmals drüber

**Comment by reyollc** [comment]
Oke glaub hab den fehler gefunden habe die zeit und die gruppe falsch rum geschrieben so ein Anfänger fehler -.-

**Comment by Shad86** [comment]
Kein Thema, dann freut es mich ja das ich doch irgendwie helfen konnte :)
