### ISSUE TITLE
List rankup only showing one entry

### ISSUE THREAD

**Issue by ThomasBecker84** [Newcomer1989/TSN-Ranksystem#297]
Hey guys,

the project is very awesome.
Allthough i got an issue in the last days.

It worked before, as i want to point out, but im not sure what lead to this bug:
![fehler](https://cloud.githubusercontent.com/assets/28434934/25740537/3952c3b4-3187-11e7-947e-4593ab247e31.png)

The Rank List is only showing one entry on each side. But not all that should be there. We have over 130 users actually.

**Comment by Shad86** [comment]
Sorry no help for modified ranksystems.

**Comment by Shad86** [comment]
Oh i see it now i though on the right side is also a searchbar xD - but you only hide it.

Well, never had such an issue, would be good to know which ranksystem version you use.

regards

Shad86

**Comment by ThomasBecker84** [comment]
Lol, ye its just to blank out my username.

im using Ranksystem Version: 1.2.2

and when i installed it yesterday, everything was working properly

**Comment by Shad86** [comment]
As i always like to say, something wont just stop working if nothing changes.

So at first to be sure you wont have cache issue (press ctrl+ F5) if it still persists
check if you changed something between yesterday and today on your server

(any relevant configs, apt-get update / upgrade,....)

because from itself an issue wont come up, if you don't change anything.

**Comment by ThomasBecker84** [comment]
i found out the problem, and yes i knew i made a change which cause the bug, as i pointed out above.

nevermind. the problem is the following:

i wasent sure if deactivating the "Assign Servergroup" addon would prevent the rankystem from giving sevrergroups by itself.
so i put the rank up times extremly high...

315360000000000000000=>47,31536060000000000000000=>50

i perhaps went a bit too high and got some Datetype problem.
As i put it back low, all went normal
