### ISSUE TITLE
Website lädt lange

### ISSUE THREAD

**Issue by jancodet** [Newcomer1989/TSN-Ranksystem#298]
Lädt das Ranksystem alle Daten aus der Datenbank asynchron oder synchron?
Leider lädt meine Website sehr lange wenn man sie aufrufen möchte, wenn man sie dann einmal aufgerufen hat und sie im Cache gespeichert ist, kann man sie ca. 2 Stunden lang öffnen ohne dass sie 15 Sekunden oder länger lädt. Woran könnte das liegen?

PS: Website ist in meinem Profil.

**Comment by Shadowoli** [comment]
Kann ich bestätigen! Mein Bot läuft schon eine ganze Weile und dementsprechend ist die Datenbank recht voll. Da kann die Statistik Seite schon bis zu 2-3 Minuten laden.

**Comment by Shadowoli** [comment]
Zudem glaube ich das die Ladezeiten nicht mit der Anzahl an Usern in der Datenbank zu tun hat. Z.B wenn 200 Nutzer(Meine Datenbank -3min) in der DB sind oder 2000(Die von @jancodet -15sec) macht keinen Unterschied in den Ladezeiten vielmehr hängt da damit zusammen wie lange das ranksystem allgemein schon läuft.

**Comment by jancodet** [comment]
Ist irgendwie komisch. Vielleicht könnten die Developer Performance Technisch daran irgendwas fixen/verbessern?:)

**Comment by Shad86** [comment]
Dieser ist seit 1-2 Monaten nicht mehr zu erreichen.

Da müsstet ihr also leider selbst schauen woran das liegt.

**Comment by jancodet** [comment]
Ok. Danke:)
