### ISSUE TITLE
PATH_TRANSLATED error

### ISSUE THREAD

**Issue by cr0co** [Newcomer1989/TSN-Ranksystem#3]
Hello

Im getting many errors from this:
PHP Notice:  Undefined index: PATH_TRANSLATED in worker.php on line 452
in the error_log file, how can it be fixxed?

**Comment by Newcomer1989** [comment]
Which Webserver are you using? Which version has the webserver.
And please report also the version of PHP you are using!

The String $_SERVER['PATH_TRANSLATED'], which is used in line 452 and also in 421, is a server side parameter. I recommend you to check your webserver and php configurations.

**Comment by cr0co** [comment]
Hello

i use
mysql: 5.5.47
php: 5.4.45

**Comment by Newcomer1989** [comment]
I missed the info about the webserver.. And you also checked my hint for the weserver configuration? What was the result of it? Is this Parameter active on you?

**Comment by Newcomer1989** [comment]
The Problem still existing?
If yes, can you answer my questions?!

**Comment by cr0co** [comment]
Yeah i fixxed it by changing PATH_TRANSLATED to $_SERVER['SCRIPT_FILENAME']
