### ISSUE TITLE
Idea for icons

### ISSUE THREAD

**Issue by Finch29** [Newcomer1989/TSN-Ranksystem#30]
Hello,
Can you disable the download of icons if the group is temporary ?

**Comment by Newcomer1989** [comment]
should be possible..

but why is this a problem?

**Comment by Finch29** [comment]
it's not a really problem but i use a lot the temporary group :s and your system download all icon but he don't check if the group exist :s 

PS : i'm on the translation to french

**Comment by Newcomer1989** [comment]
But the Ranksystem does this only once. Only if you change the icons, it will be downloaded again.

I don't see any benfit in this.
