### ISSUE TITLE
CRITICAL  Request to start the Ranksystem

### ISSUE THREAD

**Issue by renstjhuu** [Newcomer1989/TSN-Ranksystem#300]
Hello,

RITICAL  Request to start the Ranksystem from *IP*  .It seems the request came not from the command line! Shuttin down!

Does anyone know how to fix this? Also, I am not getting my cronjob working somehow. Maybe that is why?

**Comment by renstjhuu** [comment]
I am currently using CentOS 7.0 -

**Comment by Shad86** [comment]
How do you start the ranksystem?

Cornjob should look like this:

```
Enter the command "crontab -e" (In vim you have to press "i" to be able to edit the text)

Paste the following line in a new line (you have to edit the path or/and also the user but www-data is mostly the common standart webuser):

*/10 * * * * sudo -u www-data php /path/to/your/websever/path/to/Ranksystem/worker.php check >/dev/null 2>&1
```

**Comment by renstjhuu** [comment]
I have that in my crontab but im not sure what my www-data (user) is, could it be root? I am using cPanel on my server since I have multiple users using it.

**Comment by bykidi** [comment]
I was getting this error few months ago. Figured out that my cron task should be runned automatically (during some time), but if i start the ranksystem using Webmin (Start cron now) - i get this error.
Super weird, but yeah.

**Comment by renstjhuu** [comment]
Okay, I found a solution : on CentOS 7.0 im using: 	/usr/bin/php -q /home/*******/public_html/rankings/worker.php start   I added start to it, it is working now so im using this for now.

Also I had a flood problem solved it with editing the instance
serverinstance_serverquery_flood_commands=2000
serverinstance_serverquery_flood_time=5

Is it good like this? also security wise?

**Comment by Shad86** [comment]
well if the ts3 and ranksystem is on the same system, you could connect over 127.0.0.1 that is usally already whitelisted in the Query_IP_Whitelist.txt

if they are on different servers whitelist the ip from the ranksystem on your ts3 server in the Query_IP_Whitelist.txt
