### ISSUE TITLE
Users are loosing their statistics

### ISSUE THREAD

**Issue by juvcrafter** [Newcomer1989/TSN-Ranksystem#301]
Hey there,

Sometimes some users of the ranking System are loosing their active time, so the rank would be gone.
Is this normal??? Or could the Problem probaply be fixed?

- JUV -

**Comment by Shad86** [comment]
Users only lose there statistics if you remove them out of the ts3-database - if you don't want this go to Core and disable "clean clients"

regards

**Comment by Shad86** [comment]
Or if you move your teamspeaks - snapshots also can kill the statistic, if users get new database ids, then you have to disable also "Client-database-ID reset"

**Comment by juvcrafter** [comment]
Okay, I disabled both. If the Problem Comes again, I will answer here again.
Thanks for help!
