### ISSUE TITLE
Message for ts-n.net staff

### ISSUE THREAD

**Issue by jorker212** [Newcomer1989/TSN-Ranksystem#302]
Hello,

I tried to send this mail from the contact form in your site but it show me this error:
> An error occurred.. Please inform an admin on our public TeamSpeak 3 server (IP: ts-n.net) and give this one the follwing message:
> Incorrect integer value: '' for column 'id' at row 1
> 

I tried too to enter into your TS3 server but it's offline (?)

--------------------------------------------------

> Dear ts-n.net staff,
> 
> 
> I'm writing to you in order to have further information about your script, the TSN Ranksystem.
> 
> I have seen that some TS servers have the TSN Ranksystem installed, I asusme, in your space. (https://ts-n.net/host/rs/customer/4/stats/)
> 
> I would like to know how I can obtain a space for TSN Ranksystem for my TS community.
> 
> 
> If you require any further information, please feel free to contact me.
> 
> 
> Thanking you in advance...
> 
> Kind regards

**Comment by Shad86** [comment]
TS-N Stuff seems to be not available anymore. IT seems he pause his project, because there are no answers from him since 1-2 Months
