### ISSUE TITLE
Ranks werden nicht mehr zugewiesen nach Snapshot einspielung auf dem Ts

### ISSUE THREAD

**Issue by Ordust** [Newcomer1989/TSN-Ranksystem#306]
Hey !

ich habe auf meinem Server einen Snapshot über YATQA eingespielt, wodurch sich vermutlich die UUID des Servers geändert hat. 

Nun bekommen jedoch die User nicht mehr ihre alte Zeit gutgeschrieben, sondern fangen alle wieder bei 0 an. 

Ist es möglich dass die Irgendwie wieder ihre alten Zeiten bekommen ? Deren UUID hat sich ja nicht geändert.. 

Wäre mir wirklich wichtig dass das klappt. 

Danke!

**Comment by Shad86** [comment]
Hallo,

ist nur möglich wenn du noch ein Backup hast, dann ranksystem aus machen, backup einspielen und im dann im Webinterface, gibt es unter "Kern" diese Einstellung ->"Client-Datenbank-ID Reset" diese auf off stellen.

Wenn du es dann startest sollten alle ihre Rechte / Ränge behalten.

Bei Yatqa hab ich das schon öfters erlebt das sich die id's ändert, genauer gesagt, hierbei ändert sich meist die datenbank-id des Nutzers.

MfG

Shad86

**Comment by Ordust** [comment]
Oh nein.. ich habe natürlich kein Backup gemacht, typisch.. ist es irgendwie möglich die datenbank wiederherzustellen ? Kann auch eine dirty lösung sein.. Das Ranksystem läuft schon mindestens ein Jahr auf meinem Server, wenn alle zeiten weg sind ist das echt bescheiden.. 

Ich hoffe es gibt eine Lösung.. 

Danke für deine Antwort !

**Comment by Shad86** [comment]
Der Ordner Selbst beinhaltet keine informationen über rankups von deinen Nutzern, wie gesagt alle infos dazu liegen in der Mysql-Datenbank.

Die Einzige Idee die ich noch hätte, wäre, hast du damals noch das Ranksystem updaten lassen?

Dann müsste ein letztes backup vor dem letzten Update noch vorhanden sein (das ist vermutlich auch schon weit zurückliegend aber es wäre zumindest ein Großteil gerettet).

falls du phpmyadmin nutzt sollten dort tables mit:

"bak_config" usw. drin sein.

**Comment by Shad86** [comment]
Sollte das vorhanden sein exportiere "bak_user" und "bak_user_snapshot"

Dann musst bei beiden Dateien (am besten mit notepad++) den Inhalt bearbeiten und alle "bak_user" durch "user" ersetzen und in der anderen Datei alle "bak_user_snapshot" durch "user_snapshot" ersetzen.

Dann noch beide Dateien selbst umbenennen in "user" und "user_snapshot".

**Wie immer darauf achten das während diesem Vorgang das Ranksystem abgeschaltet sein sollte. Hierbei auch den Cronjob nicht vergessen**

**Comment by Ordust** [comment]
Hey, 

ja ich habe das Ranksystem damals updaten lassen, jedoch habe ich keine bak_ tables -> http://prntscr.com/fbfhdk

Sehr schade.. ich denke ich werde dann einfach versuchen das ganze über den Boost wieder einigermaßen gut zu machen.. 

Danke dir trotzdem für deine Mühe !
