### ISSUE TITLE
Dutch language is italian

### ISSUE THREAD

**Issue by MojoW045** [Newcomer1989/TSN-Ranksystem#308]
I have notices that whenever i choose dutch it shows the italian language.
Well it links to the italian language but if i manually do lang=nl it works.

And i have another issue that i've been struggling with.
When i use my ts dns adress or domain it will give me a:
ERROR Error 110: Connection timed out

When i use localhost as ip it works fine ... why can i not use my ts domain?
Because it show the sub-domain for ranksystem as join link instead of the sub-domain for teamspeak.
It has done this on 2 different servers because i installed this before a migration to a different cloud.
Both ip's are whitelisted.

**Comment by Shad86** [comment]
> I have notices that whenever i choose dutch it shows the italian language.
> Well it links to the italian language but if i manually do lang=nl it works.

Got fixed in the experimental branch:
https://github.com/Newcomer1989/TSN-Ranksystem/tree/Experimental

Whats in it:
https://github.com/Newcomer1989/TSN-Ranksystem/issues/273

> ERROR Error 110: Connection timed out

it could be still a whitelist issue 
OR
an Port issue (like port is closed from outside / not reachable) 
OR 
your system doesn't know itself (you can test it by putting a file on your vps in your webserver folder and try to download it on the same server/vps again with wget over ssh / putty).

regards

Shad86

**Comment by MojoW045** [comment]
I double checked all it all.
Only the ip of the server in use is whitelisted.
All ports for teamspeak are open ingress and egress in both my cloud panel and UFW.
And i can download anything from any of my sites with wget.(or did i need to test that different?)

**Comment by Shad86** [comment]
> And i can download anything from any of my sites with wget.(or did i need to test that different?)

Let me say this -> O <- is your server where you have current your problem then put a file on the webspace (for example filexyz.txt) login on to this Server -> O <- and download this filexyz.txt on the same server -> O <- with wget link.com/download/filexyz.txt

**Comment by MojoW045** [comment]
Yes i put an image in all of my sites main folder and then downloaded them with wget to the main folder of my user that i login with.
That worked fine.

**Comment by Shad86** [comment]
only idea i have, that he may try to go over ipv6 on the newest Server versions as i know it is also possible to whitelist an ipv6 adsress.

But then i don't have any new ideas.
