### ISSUE TITLE
Daily Stats

### ISSUE THREAD

**Issue by lucas19961** [Newcomer1989/TSN-Ranksystem#310]
Can you implement daily stats ? Daily Connections, Time , ...

**Comment by Shad86** [comment]
Daily Conntections are already in, 
![daily](https://cloud.githubusercontent.com/assets/18570683/26756326/fb697d4c-489f-11e7-8cb4-5a6b1947bf8d.png)

implemention for the rest - i dont know as already said  newcomer is not available since February.

So this Project is currently more or less on ice

the rest of you suggestions are not really precisely

**Comment by lucas19961** [comment]
i mean daily connections for each user

Ich meinen Stats für jeden benutzer habe schon versucht das selbst mit reinzubringen hat aber nicht ganz geschaft

**Comment by Shad86** [comment]
So you want to extend the "My Statistics" site?

Willst du also die "Meine Statistiken" Seite erweitern mit täglicher Verbindung?
![meine statistiken](https://cloud.githubusercontent.com/assets/18570683/26756491/d78bdd94-48a3-11e7-94ea-e4bac4fc463d.png)

weil wie schon gesagt, Tageverbindungen gibt es bereits und unter list_rankup.php siehst du auch, wann jemand zuletzt da gewesen ist.

**Comment by Shad86** [comment]
Sollte ich es irgendwie missverstehen, würde ich dich eben nochmal bitten genau zu erklären, wo, was an welcher Stelle sein soll, sonst kann ich dir bei deiner Idee, nicht wirklich behilflich sein.

Für mich geht zumindest bis jetzt nicht 100% hervor wo du die Info genau haben willst und was diese tatsächlich alles beinhalten soll.

Da die Idee ja auch nicht ausformuliert wurde;

> Can you implement daily stats ? Daily Connections, Time , ...

Ich sag immer so schön: Ich kann leider nicht hellsehen :D.

Nicht böse gemeint aber wenn du eine Idee hast nimm dir bitte auch die Zeit deine Idee mit folgenden Punkten ausführlich zu beschreiben, nur so kann ich oder jemand anderes dir eventuell dabei helfen, dies umzusetzen:

- was macht deine Idee (Bitte jeden Punkt einzeln beschreiben) (Daily Connections: macht/zeichnet auf, ..... Time: macht/zeichnet auf,....)
- wo soll es veranschaulicht werden (also auf welchem Teil der Seite (deiner Meinung nach) sollte es mit integriert werden)

MfG

Shad86

**Comment by lucas19961** [comment]
Es sollte eine Extra Seite sein wo man sehen kann wie viele Verbindungen zum Server Heute stattgefunden haben (von jedem einzelnen User). Es kann auch gerne unter /stats/list_rankup.php mit beistehen.

**Comment by lucas19961** [comment]
So würde ich das gerne haben wollen. Bekomme es leider nicht hin. Wenn also jemand eine Idee hat wie es gehen könnte bitte melden 👍 


![chrome_2017-06-04_22-55-38](https://cloud.githubusercontent.com/assets/17136546/26765274/03798a02-4979-11e7-8c94-95e910212d65.png)

**Comment by Newcomer1989** [comment]
Sind damit nun die Anzahl der Verbindungen von Heute gemeint oder die Zeit, welche Heute auf dem TS verbracht wurde?

In deinem Post vom 3. Juni verstehe ich es so, dass die Anzahl der Verbindungen von Heute gemeint sind. Welchen Sinn sollen diese denn haben? Ich kann mich mehrmals an einem Tag zum TS verbinden. Gerade bei Verbindungsproblemen kann dies auch gerne mal mehrere zwei- oder sogar dreistellig werden. Verstehe leider nicht die Aussagekraft hinter so einer Zahl. Vielleicht magst du uns den Zweck näher erläutern ;-)

**Comment by Newcomer1989** [comment]
Ich schließe den Issue erst einmal. Öffne ihn einfach wieder, wenn du uns noch den tieferen Sinn dahinter erläutern magst ;-)
