### ISSUE TITLE
Command version no response

### ISSUE THREAD

**Issue by fabm3n** [Newcomer1989/TSN-Ranksystem#311]
If I chat the bot with "version" it doesn't response anything. Maybe something like "No Update found." or "Can't reach the Update Check Server".

Wenn ich den Bot "version" als Nachricht schicke bekomme ich keine Rückantwort. Vielleicht würde eine Antwort wie oben sehr hilfreich damit man bescheid weiß.

**Comment by Shad86** [comment]
Sicher das du den command richtig nutzt?

!version
gibt mir die aktuelle version aus.
mit 
!help
bekommst du alle commands gelistet

MfG

Shad86

**Comment by fabm3n** [comment]
Ah okay. Mit ! geht es. die anderen commands gehen auch ohne ! (also der info befehl).
Dann wäre es gut wenn man in dem Info Text ein ! davor macht.

Danke für die Schnelle info.

fabm3n

PS: in der nachricht "eigesetzte Version: 1.2.2" sollte man das e groß machen ;)
