### ISSUE TITLE
ERROR     calc_serverstats 2:Array

### ISSUE THREAD

**Issue by Nogi19** [Newcomer1989/TSN-Ranksystem#312]
Hallo musste heute das Rankssystem neu aufsetzen und hatte das ranksystem die datenbank exportiert und nach der neuen installation auch wieder importiert.
Nun startet der bot kurz ca 3 sek und danach verliert er die verbindung und im log steht folgende meldung:

ERROR     calc_serverstats 2:Array

nach dieser meldung ist das ranksystem wieder offline
woran könnte dies liegen ?

**Comment by Shad86** [comment]
Hm... würde erstmal alle Settings und Berechtigungen überprüfen. 
Wenn da alles okay ist und es trotzallem nicht geht, nochmal neu installieren.

**Comment by Shad86** [comment]
Auf Grund keiner weiteren Antwort geschlossen.
