### ISSUE TITLE
Bot nicht Startbar

### ISSUE THREAD

**Issue by fabm3n** [Newcomer1989/TSN-Ranksystem#313]
Habe den Windows Server gewechselt und jetzt startet der bot nicht mehr. Den log liest er zwar ein aber bei neustarten erscheint nichts im log. Aufgabe ist auch erstellt.

**Comment by Shad86** [comment]
Bei Windows kann ich dir leider nicht behilflich sein, hab ich so nie genutzt.

Was du mal Probieren könntest:

> You can also try to debug the Ranksystem to get the error.
> 1) Go to file jobs\bot.php and comment the line `error_reporting(0);` out (change to `//error_reporting(0);`)
> 2) Open a command line and run the jobs\bot.php manual
> `php jobs\bot.php`
> 3) Post the output here...

MfG

Shad86

**Comment by fabm3n** [comment]
Es kommt kein output...
Habe die PHP mal angeschaut und vermute den exec command bei windows. ich melde mich wenn ich was finde

**Comment by fabm3n** [comment]
Ah der Log ist auch in der Log file -_-

2017-06-09 21:34:54.966120   INFO      Received signal to stop. Shutting down!
2017-06-09 21:34:49.962552   INFO      Bot starts now his work!
2017-06-09 21:34:49.954752   INFO        Joined to specified Channel.
2017-06-09 21:34:45.892404   INFO        Connection to TS3 Server established.
2017-06-09 21:34:45.803341   INFO      Connect to TS3 Server (Address: "removed" Voice-Port: "removed" Query-Port: "removed").
2017-06-09 21:34:45.800937   INFO      Loading addons [done]
2017-06-09 21:34:45.798014   INFO        Addon: 'assign_groups' [OFF]
2017-06-09 21:34:45.794932   INFO      Loading addons...
2017-06-09 21:34:45.792504   INFO        Ranksystem Version: 1.2.2
2017-06-09 21:34:45.789569   INFO        Check files permissions [done]
2017-06-09 21:34:45.349426   INFO        Check files permissions...
2017-06-09 21:34:45.345481   INFO        No newer version detected; Database check finished.
2017-06-09 21:34:45.342448   INFO      Check Ranksystem database for updates.
2017-06-09 21:34:45.333591   INFO      Initialize Bot...

**Comment by fabm3n** [comment]
@Shad86 kann es sein das php oder apache extra freigaben in der firewall brauchen?
apache hat halt ausgehend den webserver port meht nicht,

**Comment by Shad86** [comment]
eig. nicht :/ - geht es nun oder warum hast es geschlossen?

**Comment by fabm3n** [comment]
geschlossen habe ich es nicht. es geht immer noch nicht

**Comment by Shad86** [comment]
okay :/ - I'm sorry kann dir da wirklich nicht helfen.

**Comment by fabm3n** [comment]
Wie kann ich folgende sachen testen?
Webspace (webserver):
PHP 5.5.0 or higher with PDO support; PHP 7 is supported!
with privileges for PHP command "exec"
with "cURL" extension for PHP
with "Zip" extension for PHP
with "COM" extension for PHP (for Windows only)
Query connection to the TeamSpeak server on TCP (default port 10011)
Connection to ts-n.net on TCP port 80 (for Update check)

**Comment by Shad86** [comment]
müssten zum einen in der Config zu finden sein und du kannst eine info.php mit folgendem Inhalt erstellen und sie auf deinen webserver legen und aufrufen:

```
<?php
// Show all information, defaults to INFO_ALL
phpinfo();
?>
```

**Comment by fabm3n** [comment]
Also nach dem neu aufsetzten des Webservers geht es jetzt so halb. Ich habe die jobs/bot.php per hand gestartet weil es über das webinterface nicht geht. Meine vermutung ist, dass exec nicht richtig funktioniert / freigegeben ist

**Comment by fabm3n** [comment]
Okay habe exec eben lokal mit ner kleinen php datei getestet, das funktioniert.

**Comment by HaxXorHardy** [comment]
Eventuell falscher Benutzer oder falsche/zu wenige Rechte? Datenbank Verbindung OK?

_Sent from my Samsung SM-G800F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by fabm3n** [comment]
Der bot funktioniert in dem ich per CMD die php datei aufrufe, also DB Verbindung okay.
Rechte sind so, das jeder user an dem ordner was ändern könnte.

**Comment by Newcomer1989** [comment]
Meist ist das ein Rechteproblem. Bitte also die Dateirechte von Windows prüfen. Speziell müssen die Verzeichnisse avatars, logs und updates volle Lese- und Schreibrechte bekommen, sodass der entsprechende User (mit dem das Ranksystem gestartet wird) dort Zugriff hat.

Weiterhin kann es auch ein Problem des PHP Aufrufs sein. Hier einfach mal in einem Eingabeaufforderungsfenster den Befehl `php -v` eingeben. Damit solltest du die PHP Version erhalten. Kommt hier nichts, so müsstest du prüfen, wie du PHP installiert hast und es folglich aufgerufen wird. Der nötige Aufruf kann als Parameter dann in der `other/phpcommand.php` definiert werden. Beispiele sind dort bereits beschrieben.

**Comment by fabm3n** [comment]
Nutze das System mittlerweile nicht mehr, habe ein eigenes System per python entwickelt. Kann deshalb da nicht mehr weiterhelfen.

PS. Trotzdem schön das du wieder da bist.

**Comment by Newcomer1989** [comment]
Ok, thx für die Info.

Für den Fall, dass du damit noch einmal unter Windows in Berührung kommen solltest, kannst du es dir ja mal im Hinterkopf behalten. Ich werde den Thread aber vorerst schließen.
