### ISSUE TITLE
The Bot has Stop 

### ISSUE THREAD

**Issue by kkaraIQ** [Newcomer1989/TSN-Ranksystem#314]
the bot stop in all servers i know it and in my server to what the problem ?

**Comment by HaxXorHardy** [comment]
Can you Please write more details? Like log, how much Servers, win vor Linux, first install or existing and so on..

**Comment by kkaraIQ** [comment]
i log no thing special how mush server maybe 6-8 linux  and existing  all of themold servers

**Comment by Shad86** [comment]
as said before, the ranksystem has a logfile, that would really help to understand, what was happening.

or you also may check your Serverlogfiles or Apache logfiles.

Because the ranksystem usually doesn't quit from itself.

But With your current information we can't help you.

**Comment by Shad86** [comment]
Because of no new answers since 8 days i close it.
