### ISSUE TITLE
(You are not connected to the TS3!)

### ISSUE THREAD

**Issue by jorker212** [Newcomer1989/TSN-Ranksystem#319]
I am connected to the TS3 server but on TS-N.NET Ranksystem says (You are not connected to the TS3!)

The settings are OK, the script are connected to the TS3 server.

How can I fix this issue?

**Comment by Shad86** [comment]
Seems you'r connecting over ip4 on the TS3 and over ipv6 on the site or vice versa, so he can't acknowledge you.

**Comment by jorker212** [comment]
What should I do to control this?

**Comment by Shad86** [comment]
well, make sure that you connect on both "services" with the same ip, how that is be done -> google.de ;)

**Comment by jorker212** [comment]
So the script can not work if it is in a web space other than that of the ts3 server?

**Comment by Shad86** [comment]
I never said that.

But the ranksystem compares your ip on the Website with the ip on the TeamSpeak if theres no match, it wont find you.

So as said, be sure you access the website and the TeamSpeak with the Same ip adress

*closed*
