### ISSUE TITLE
worker crashes?

### ISSUE THREAD

**Issue by mobzftw** [Newcomer1989/TSN-Ranksystem#32]
When I type "php worker.php status" and it replies saying that the service is running, but the "bot" is not connected to the server. I type "php worker.php restart" and I get the following:
Stopping the Ranksystem Bot.
Wait until Bot is down...... [Failed]
Starting the Ranksystem Bot. [OK]
The bot then reconnects to the server and begins to read time again.

Any ideas?

**Comment by Newcomer1989** [comment]
Its possible that the Bot "crashes".
1) The TeamSpeak server was offline,
2) connection from Bot to TeamSpeak server was lost/forbidden   or
3) the Ranksystem have had a problem.

What does the log says?

But for this szenario you should use the cronjob. More read here: https://github.com/Newcomer1989/TSN-Ranksystem/issues/9
