### ISSUE TITLE
Frage

### ISSUE THREAD

**Issue by Nisutec** [Newcomer1989/TSN-Ranksystem#322]
Hallo,
Ich wollte mal fragen ob das Projekt noch weiter entwickelt wird oder ob die Entwicklung still steht.

**Comment by Shad86** [comment]
steht momentan, seit ende Februar still

**Comment by Nisutec** [comment]
gibt es den ein Statement der devs ob es endgültig vorbei ist , oder nur temporär ?

**Comment by Shad86** [comment]
Seit Februar gab es keine Rückmeldung des devs, somit gibt es bis dato dazu keine Info.

**Comment by xopez** [comment]
Also, auch wenns steht. Habe es soeben erst entdeckt, da ich was brauchte um gruppen automatisch zu vergeben nach X Zeit.
Läuft bei mir einwandfrei. 
Habe nur das Problem, dass mir im Firefox keine Grafiken angezeigt werden
https://www2.pic-upload.de/img/33418781/Unbenannt.png

**Comment by HaxXorHardy** [comment]
Deaktiviere ublock origin für deine Seite. Das war die Lösung für mich!

_Gesendet von meinem Samsung SM-G800F mit [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
