### ISSUE TITLE
uBlock Origin blockt Grafiken

### ISSUE THREAD

**Issue by xopez** [Newcomer1989/TSN-Ranksystem#323]
Falls mal wieder nach langer Zeit entwickelt wird.

uBlock Origin blockiert Grafiken. Der AdBlock ist bei mir auf Standardeinstellungen.

https://www2.pic-upload.de/img/33418781/Unbenannt.png

**Comment by HaxXorHardy** [comment]
Ist bekannt und steht schon unter issues.

_Gesendet von meinem Samsung SM-G800F mit [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by xopez** [comment]
weiß ich, habe ich nach dem Report gesehen.
Wird von EasyPrivacy​​​​​​​​​ blockiert. Habe da einfach den Haken entnommen, und siehe da, es klappt.
