### ISSUE TITLE
How can I wipe the database without reinstalling?

### ISSUE THREAD

**Issue by Joele25** [Newcomer1989/TSN-Ranksystem#324]
How can I wipe the database without reinstalling?

**Comment by Shad86** [comment]
If im Correct, it should be enough if you truncate the following table:

user
user_snapshot

**As I always say, before you change something, pls stop the bot (don't forget the cron too) and then do a Backup before you start with "editing"**

**Comment by Joele25** [comment]
I truncate almost every table and it worked fine, thx
