### ISSUE TITLE
Sortierung in der Rank-Liste

### ISSUE THREAD

**Issue by xopez** [Newcomer1989/TSN-Ranksystem#327]
Kein Plan warum, meine Sortierung ist kaputt.
Zumindest glaube ich das, da die Seite list_rankup.php sehr willkürlich aussieht.
Kann natürlich auch sein, dass es da nie eine gab.
Hier zu erreichen:
https://mightful-noobs.de/ts3ranks/stats/list_rankup.php
Jemand ne Idee wie ich es hinbekomme, dass PLatz 1 oben ist?

EDIT:
Ränge sind bei mir 5,3,4,6,1,2,8,7,9,10,11,12,13,14,15
sprich erst ab 9 sortiert.

**Comment by Shad86** [comment]
2 mal auf "Rang" drücken und es ist nach Rang sortiert
