### ISSUE TITLE
Wrong Update notification - already updated

### ISSUE THREAD

**Issue by oalaro** [Newcomer1989/TSN-Ranksystem#33]
Even though I updated, bot still gives me notifications to update. Web interface shows that I have the new version.
http://i.imgur.com/w5IEdfM.png 
http://i.imgur.com/JsWuwSN.png 
Not that annoying since it does it like every 4h or so

**Comment by Newcomer1989** [comment]
You stopped the bot before you updated?

**Comment by oalaro** [comment]
I'm 99% sure I did. I stopped the bots. Cleared crontab. Checked on htop if there were any instances running and  updated. Started the bots

I restarted the bots again today. Made sure no instances were running before starting again. Will report back if I still get the notifications.

**Comment by oalaro** [comment]
Seems like i started to bot too early. Restart solved the problem.

**Comment by Newcomer1989** [comment]
You are right.. On first start with new version this problem will happens.
A restart fix it!

A Bugfix will come with Release 1.0.2
