### ISSUE TITLE
Error 1024: invalid serverID

### ISSUE THREAD

**Issue by Acordi** [Newcomer1989/TSN-Ranksystem#330]
Good Day

So i moved my Teamspeak server now it has a different server ID although it is the same ip still so i didn't reinstall anything.

I want to know where in the config files can i edit the server ID to the new one

Regards
Francois

**Comment by Shad86** [comment]
Usually, if you move your teamspeak server, the Server ID should also stay the same.

I don't have so much time at the moment, but on the first sight i didn't was able to find that information.

So the best way what stucks in my head for the moment, would be to correct the Server ID, whats should be possible over Yatqa.

As Reminder: Before you change something pls do a Backup and stop all relevant bots, which are communicating with teamspeak.

regards

Shad86
