### ISSUE TITLE
Cant send private Messages

### ISSUE THREAD

**Issue by m4r1vs** [Newcomer1989/TSN-Ranksystem#332]
I just installed the bot and set it up. But when trying to send a private message to it, I just get an error:  "insufficient client permissions (gescheitert an i_client_needed_private_textmessage_power)". But I have the permissions high enough. But when sending one via YaTQA I get following error: invalid ClientID. The Bot uses the initial serveradmin Password because I already have a Bot which uses the normal Server Query Login. So is there a way for me to get around this issue?

**Comment by maxlxl** [comment]
You can only send messages to real clients, but not to querys. Possibly you should check your permissions for sending and receiving private textmessages again. Don't forget to check even the channel and client perms. There is also a function in YaTQA that my be helpful: check permissions.
The problem have to do with permissions in Teamspeak as the error reports.
