### ISSUE TITLE
i can't add my voice port 

### ISSUE THREAD

**Issue by eljouhan1** [Newcomer1989/TSN-Ranksystem#333]
when i try to add my voice port (50977) in the web interface i reload the page end i find it back to other port (32767) 
I cant fix that problem pls help Guys

**Comment by maxlxl** [comment]
Did you saved the settings and restarted the bot afterwards? Maybe that's your problem.

**Comment by Shad86** [comment]
it seems you use an older Version because this is an issue before Version 1.2.2 (2017-01-21) was released.

> 1.2.2 (2017-01-21)
> .....
> - fixed database field for TS3 query port; the field was not unsigned, so there was 32767 as highest value possible (now is the highest value 65535)
