### ISSUE TITLE
Bot Not Start + NO LOG

### ISSUE THREAD

**Issue by EscuderoKevin93** [Newcomer1989/TSN-Ranksystem#336]
The bot not start...
No show any stats nothing ing logs.

Online file pid with numer and nothing more.

Whats happend (?

I run bot in centos 6 with php 5.6

**Comment by maxlxl** [comment]
There have to be a log or something like an error message. Please look in your syslog and apache/nginx log first or even the php-log. Maybe there you can find more information for us to help you or maybe you can resolve the problem by yourself.

**Comment by EscuderoKevin93** [comment]
Te problem its when í set time zone. 


Enviado desde mi smartphone Samsung Galaxy.
-------- Mensaje original --------De: maxlxl <notifications@github.com> Fecha: 26/7/17  3:18 AM  (GMT-03:00) A: Newcomer1989/TSN-Ranksystem <TSN-Ranksystem@noreply.github.com> CC: EscuderoKevin93 <escuderokevin93@gmail.com>, Author <author@noreply.github.com> Asunto: Re: [Newcomer1989/TSN-Ranksystem] Bot Not Start + NO LOG (#336) 
There have to be a log or something like an error message. Please look in your syslog and apache/nginx log first or even the php-log. Maybe there you can find more information for us to help you or maybe you can resolve the problem by yourself.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Newcomer1989/TSN-Ranksystem","title":"Newcomer1989/TSN-Ranksystem","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Newcomer1989/TSN-Ranksystem"}},"updates":{"snippets":[{"icon":"PERSON","message":"@maxlxl in #336: There have to be a log or something like an error message. Please look in your syslog and apache/nginx log first or even the php-log. Maybe there you can find more information for us to help you or maybe you can resolve the problem by yourself."}],"action":{"name":"View Issue","url":"https://github.com/Newcomer1989/TSN-Ranksystem/issues/336#issuecomment-317959052"}}}

**Comment by Newcomer1989** [comment]
Can you share us a little bit more information?

What are you exactly doing? On which step you got an error or on which step it ends?
What are you meaning with the timezone? Sorry, but I am not be able to understand it for now.

**Comment by Newcomer1989** [comment]
Closed due no response. Sure reopen it, if you still have problems.
