### ISSUE TITLE
Windows Plesk (Onyx) Bot startet nicht.

### ISSUE THREAD

**Issue by jyrixx** [Newcomer1989/TSN-Ranksystem#337]
Hey Community,

Ich hab das Problem das der Bot weder Connectet noch startet. Wenn ich auch den Button "Bot Starten" klicke werd das Bild grau und weiter passiert nichts.
Weder sehe ich im TS anhand von Aktuelle Queries das der Bot connectet ist noch im Webinterface wie gesagt das bild bleibt Grau.

Habe schon andere Versionen des Bot´s probiert überall der gleiche Fehler, und über die direkte IP. (habe es sonst über die Domain probiert)

nun noch ein paar Infos die vielleicht helfen.

    Dedizierter Server
    Windows Server 2012
    PHP Version 5.5.38
    MySQL Datenbank Version 5.1.73

Habe das ganze Über Plesk Onyx laufen

Ich hoffe jemand kann mir helfen.

**Comment by Shad86** [comment]
Ich hab leider keine Erfahrung mit Windows aber hast du dir mal die "Plesk Issues" durchgesehen ob diese dir helfen können?

https://github.com/Newcomer1989/TSN-Ranksystem/issues?utf8=%E2%9C%93&q=Plesk

mfg

Shad86

**Comment by jyrixx** [comment]
Hallo Shad86

Habe mir alle möglichen durchgelesen, es hilft aber alles leider nichts. 

mfg 

Jyrixx

**Comment by Newcomer1989** [comment]
Meist ist das ein Rechteproblem. Bitte also die Dateirechte von Windows prüfen. Speziell müssen die Verzeichnisse avatars, logs und updates volle Lese- und Schreibrechte bekommen, sodass der entsprechende User (mit dem das Ranksystem gestartet wird) dort Zugriff hat.

Weiterhin kann es auch ein Problem des PHP Aufrufs sein. Hier einfach mal in einem Eingabeaufforderungsfenster den Befehl php -v eingeben. Damit solltest du die PHP Version erhalten. Kommt hier nichts, so müsstest du prüfen, wie du PHP installiert hast und es folglich aufgerufen wird. Der nötige Aufruf kann als Parameter dann in der other/phpcommand.php definiert werden. Beispiele sind dort bereits beschrieben.

**Comment by Newcomer1989** [comment]
Bitte auf den folgenden Thread beachten. Hier haben wir noch einmal übersichtlich und hoffentlich verständlich alle Schritte zusammengetragen.

https://github.com/Newcomer1989/TSN-Ranksystem/issues/369

**Comment by Newcomer1989** [comment]
Release 1.2.3 ist veröffentlicht. Hier sind in der install.php noch einmal weitere Checks aufgenommen worden, um sicherzustellen, dass die Anforderungen auch erfüllt werden.
