### ISSUE TITLE
Servergruppen Icons werden nicht angezeigt Server Icon wird jedoch angezeigt.

### ISSUE THREAD

**Issue by RoVCloudStrife** [Newcomer1989/TSN-Ranksystem#338]
Die oben schon steht habe ich das Problem das meine Servergruppen Icons nicht angezeigt werden.
Das Server Icon wird jedoch angezeigt und alle Icons sind im Ordner "Icons" vorhanden.
Kann mir jemand da ein Tipp geben wie ich es schaffe das diese angezeigt werden?

![iconsproblem](https://user-images.githubusercontent.com/30746133/28994147-93374264-79c7-11e7-8fe3-d4b8fef491fc.png)
![server icon wird geladen](https://user-images.githubusercontent.com/30746133/28994148-96699cc0-79c7-11e7-92ad-cfabd935f4f6.png)

**Comment by Shad86** [comment]
Wenn du eine subdomain verwendest, könnte dass das Problem sein, da dies in der Stable variante noch nicht behoben wurde müsstest du dir diese Version holen (Diese wird sofern leute Pull request machen auch von mir weiterhin gepflegt) -> #273

**Comment by RoVCloudStrife** [comment]
Hi vielen Dank erst einmal für die Rückmeldung.
Jedoch ist es keine Subdomain auf der das Ranksystem läuft.

**Comment by Shad86** [comment]
ansonsten stoppe das ranksystem, gehe in die mysql datenbank und leere den table "groups" (nur leeren, nicht löschen) und dann das ranksystem wieder starten. 

Sollte das nicht helfen, mal die experimental version versuchen.

**Comment by RoVCloudStrife** [comment]
Danke dies war aber nicht der fheler.
Habe den Fehler gefunden ich musste eine Zeile ( Alias /icons/ "/usr/share/apache2/icons/"
 ) in der alias.conf Löschen unter apache2.
