### ISSUE TITLE
Website no response

### ISSUE THREAD

**Issue by kecinotrab** [Newcomer1989/TSN-Ranksystem#339]
Hey guys, i have a question about ranksystem. I had domain name what ends .pl, ranksystem was fine and now i changed to .cz domain and when i go to the browser. go to the my web {ts3.hwns.cz} it"s fcking delay and i don't know why ? can anyone tell me how to fix that ? thanks :***

**Comment by Shad86** [comment]
unfortunately no, i also saw that but i don't know why that happen.

**Comment by Newcomer1989** [comment]
You only changed the domain or within also the webhost, IP or anything else?

Is ts3.hwns.cz the address of the ranksystem? I cannot reach it now (timeout).

**Comment by Newcomer1989** [comment]
Closed due no response.
