### ISSUE TITLE
Bot loops on update_groups

### ISSUE THREAD

**Issue by pwnyprod** [Newcomer1989/TSN-Ranksystem#340]
Bot-Log says:

`ERROR     update_groups 7:('0', 'ServerIcon', '0', '')Array`

and stuck in loop on this error.

**Comment by Shad86** [comment]
Hello,

stop your ranksystem (and maybe cronjob) and go to your mysql databse and clear the table "groups" (Clear, NOT delete) afterwards start the ranksystem again.

After that it should work fine usually.

**Comment by pwnyprod** [comment]
Doesn't work for me either.

Logfile says the input in the script is false:

```
ERROR     update_groups 7:('0', 'ServerIcon', '0', '')Array
(
    [0] => HY000
    [1] => 1366
    [2] => Incorrect integer value: '' for column 'icondate' at row 1
)
```

**Comment by Shad86** [comment]
Then may try a reinstall of the ranksystem, seems something is broken, because usually truncate the groups table should fix the "Icon-Problem".
