### ISSUE TITLE
 ERROR     handle_messages 8:2568: insufficient client permissions (failed on sendtextmessage 215/0xD7)

### ISSUE THREAD

**Issue by Artapel** [Newcomer1989/TSN-Ranksystem#341]
Hi Guys. Im getting this Message on my logs

 ERROR     handle_messages 8:2568: insufficient client permissions (failed on sendtextmessage 215/0xD7)

What permissions am i missing ?

**Comment by Shad86** [comment]
Hello,

i think it should be "i_client_private_textmessage_power"

**Comment by Artapel** [comment]
mmm. i have that configured. il scratch around some more
