### ISSUE TITLE
Bot not starting correctly, no log?

### ISSUE THREAD

**Issue by E-v-o** [Newcomer1989/TSN-Ranksystem#342]
Hey there,

I'm running on Windows server 2016 but am having issues start the bot. It claims to be "starting bot" if I try via the cmd but doesn't actually start it.

On the web interface nothing happens it just goes to a grey screen when you click start. It also doesn't connect to the TS3 server? The only time it connects is when trying to reset password.

**Comment by Shad86** [comment]
I think you also wrote on r4p3? (https://r4p3.net/threads/teamspeak-3-rank-level-up-system.4607/) so as i can see there you fixed it.

So far i will close it, if not feel free to write just again and i will reopen it.
