### ISSUE TITLE
Frage: Mehrere Booster gleichzeitig

### ISSUE THREAD

**Issue by fabm3n** [Newcomer1989/TSN-Ranksystem#343]
Nur kurze frage, kann das Levelsystem mehrere Booster gleichzeitig bei einem Clienten nutzen? D.h. ein booster mit 2x und einer mit 5x mal oder so.

**Comment by Shad86** [comment]
Nein es ist immer nur 1 boost möglich.

**Comment by Shad86** [comment]
Nur noch zur Richtigstellung, du kannst mehrere einrichten, ja - aber ein User selbst darf immer nur einen Boost zur gleichen Zeit haben.
