### ISSUE TITLE
Bot startet nicht 

### ISSUE THREAD

**Issue by Viper830** [Newcomer1989/TSN-Ranksystem#344]
Ich hab den Bot gerade gestartet bzw das sollte er oben steht dann auch 
Ranksystem Bot should be started. Check the log below for more information!

aber in der Log steht nur 
The logfile will be created with next startup.
No log entry found...

**Comment by Shad86** [comment]
Windows oder Linux?

Welche version vom Ranksystem nutzt du?

**Comment by Viper830** [comment]
Linux und 1.2.2

**Comment by Shad86** [comment]
hast du mal geschaut was der syslog und auch die apache logs durchgeschaut, was die sagen sobald du das ganze starten willst?

Denn auf Debian 8 + 9 sollte es eig. von Grund auf gehen und bei Ubuntu meines Wissens auch (nur bei der neusten Ubuntu version bin ich mir nicht 100% sicher)

**Comment by Viper830** [comment]
Hab gerade das gefunden 
https://pastebin.com/U34utuwc

**Comment by Shad86** [comment]
[Sat Aug 19 17:23:38.413698 2017] [:error] [pid 23933] [client 46.92.192.95:52133] PHP Fatal error:  Call to a member function query() on null in /var/www/html/rangsystem/other/load_addons_config.php on line 3

Fatal erros sind meist nicht so gut, woher der genau kommt erschließt sich mir aber so aus den vorhandenen Dingen nicht.

Eventuell mal die Rechte überprüfen auf dem webserver und oder das Ranksystem mal neu laden und nochmal frisch installieren.

**Comment by Viper830** [comment]
Okay ich hab gerade mal das System neu installiert allerdings ohne erfolg

**Comment by Shad86** [comment]
okay, ich denke dann wäre es mal clever , wenn wir uns mal zusammensetzen. Wann hast du denn so pauschal Zeit

**Comment by Viper830** [comment]
Ich bin Samstag gegen Mittag wieder Zuhause ab da könnte ich.

**Comment by Shad86** [comment]
Am Samstag, bin ich leider nicht zu Hause.

**Comment by Viper830** [comment]
Dann schreib mir am besten wenn du da bist und dann finden wir schon was, ich hab eigentlich immer Zeit

**Comment by Shad86** [comment]
Ich wäre heute da bis in den späten Abend hinein

**Comment by Viper830** [comment]
Ich hätte jetzt Zeit

**Comment by Shad86** [comment]
oh okay, dann komm mal eben auf mein TS3 -> hdf-multigaming.de

**Comment by Viper830** [comment]
Okay ich glaube wir müssen nochmal verschieben hab gerade folgendes vom Anbieter erhalten 
Ihr Server ist auf dem Hostsystem nicht vorhanden, dies kann daran liegen das sich ihr Server gerade in einer Installation oder in einem Backupvorgang befindet.

Ich weis nur nicht wie lang das jetzt dauert

**Comment by Shad86** [comment]
Okay, kommt auf deren system an, aber normalerweise sollten Installationen und Backups nicht länger als 10-15min dauern. (davon ausgehend das es ein V- oder KVM-Server ist) - Bin jedenfalls noch etwas da.

Kommst einfach auf meinen TS und in Warte auf Support, dann bekomm ichs auch mit das jemand da ist :D - falls du noch im verlauf der nächsten 1-2 Stunden kommst.

**Comment by Shad86** [comment]
Ich war nun bei im persönlich drauf und hatten festgestellt, das bei Php7.0 einfach das mysql Paket (php7.0-mysql) gefehlt hatte.
