### ISSUE TITLE
TSN ADDONS

### ISSUE THREAD

**Issue by TomDieLoK** [Newcomer1989/TSN-Ranksystem#345]
Hallo ist es möglich wenn ja wie!

Die beiden anderen tools TSN Channeldeleter & TSN ClientCleaner als addon in ein vorhandenens TSN Ranksystem zu integrieren?
Mom ist ja ein Addon im Ranksystem aktiv das Servergruppen zuweisen!

gruss

**Comment by Shad86** [comment]
Das ganze Projekt, ist derzeit auf Eis, da müsste wenn man das will sich selbst rein arbeiten.

Wie gesagt Newcomer ist seit Februar abwesend und ich habe bis dato keine neuen Infos

**Comment by TomDieLoK** [comment]
ok danke für die infos.
