### ISSUE TITLE
php problem with this panel

### ISSUE THREAD

**Issue by fabri2000779** [Newcomer1989/TSN-Ranksystem#346]
well im trying to install this on my dedicate server and when i go to my domain.com/install.php i got a message PHP exec function need to be enabled but seems to be disabled. Please enable the PHP exec function and try it again!
of course i already edited the php.ini so at this point idk what to do now
this message still showing im using ubuntu 16.04 and apache2

**Comment by Shad86** [comment]
Be sure you edited the correct php.ini (especially if you have more then one installed php version)

After editing also don't forgett to restart the apache2 Service once so that the php.ini gets loaded with the new setups

Regards

Shad86

**Comment by fabri2000779** [comment]
yeah i did i have php 7.1 only that version the file location is on /etc/php/7.1/apache2php.ini
i edited and the line look like this:
disable_functions=pcntl_alarm,pcntl_fork,pcntl_waitpid,pcntl_wait,pcntl_wifexited,pcntl_wifstopped,pcntl_wifsignaled,pcntl_wifcontinued,pcntl_wexitstatus,pcntl_wtermsig,pcntl_wstopsig,pcntl_signal,pcntl_signal_get_handler,pcntl_signal_dispatch,pcntl_get_last_error,pcntl_strerror,pcntl_sigprocmask,pcntl_sigwaitinfo,pcntl_sigtimedwait,pcntl_getpriority,pcntl_setpriority,pcntl_async_signals,

and yeah i restarted apache multiple times and nothing

**Comment by Shad86** [comment]
to be sure the ranksystem really is using php7.1 to the webspace from the
ranksystem under other there is a file called phpcommand.php there you can
also set a direct path to php.

Don't forgett that only one should be enabled all other should be disabled
with a # in front
fabri2000779 <notifications@github.com> schrieb am Do. 31. Aug. 2017 um
23:51:

**Comment by fabri2000779** [comment]
ok i think that is the issue i did this:

$phpcommand = "/etc/php/7.1/";

but idk if that is good? i tested like this and it keep showing me the message

**Comment by Shad86** [comment]
without / at the end it that is really your path:

`"/etc/php/7.1";`

regards

Shad86
