### ISSUE TITLE
Charts

### ISSUE THREAD

**Issue by peralta00** [Newcomer1989/TSN-Ranksystem#347]
Hey, im having some issues with ranksystem. For some reason the charts on my panel are not working and the server uptime is always 00:00:00.

ranksystem version: Latest
php version: 5.6

!! EDITED !!: charts only working under "top users" Tab.

**Comment by bykidi** [comment]
seems like an uBlock problem. add your site to exception list.

**Comment by peralta00** [comment]
i dont have uBlock installed on chrome

**Comment by bykidi** [comment]
permission problem? show us your ranksystem.log file

**Comment by peralta00** [comment]
https://pastebin.com/AYq4Xgw4

**Comment by Shad86** [comment]
What OS (Ubuntux.x , Debianx,...) are you using and what DB? (mysql or mariadb)

**Comment by peralta00** [comment]
OS: Not sure the webhoster doesn't share that info.
DB: MariaDB

**Comment by Shad86** [comment]
the last time i talked with the owner of the script, he said there is may an issue with some versions of newer mariadb, so this may happen to you :/.

**Comment by peralta00** [comment]
MariaDB users will get a fix for this issue on the next ranksystem update ?
Is it ranksystem's or SB admin fault ?

Thanks for the help ! ;)

**Comment by Shad86** [comment]
The owner is away since february '17 - so there will not really an update atm for this.

As soon as i can find someone, which can look for me over the code, there may come a fix.

But i can't say if and when it comes.

I still have a little bit free space on my system, so i could may host it for you.

**Comment by peralta00** [comment]
thank you but i cant really do it i have ranksystem under a subdomain with another script to create ts3 channels

**Comment by Newcomer1989** [comment]
There is no problem with the database MariaDB in version 1.2.2. All should be fine.
In your ranksystem.log I can see, that the bot restarts every 15 mins. That seems to be the cronjob, what is ok. But what is not good, that it need to be started so much often.
Can you check how long the bot is connected to the TeamSpeak server after a restart?
I think it will be stopped in background, perhaps by your webhoster. Also be sure (ask them), that scripts like the Ranksystem are allowed on there machine. The exec command for php seems to be allowed, thats good. I am not sure, if your hoster have any limit/restrichtion for scripts and kill them...
That could be the reason, why the Ranksystem is not be able to collect the stats.

**Comment by Newcomer1989** [comment]
Closed due no response.
