### ISSUE TITLE
Statistik Login

### ISSUE THREAD

**Issue by Shirobaka** [Newcomer1989/TSN-Ranksystem#349]
Tach,
seit einigen Tagen bekomme ich und auch alle anderen User die versuchen auf die Stats Seite zu kommen die Aufforderung für einen Login, ich verstehe nicht warum, die Servergruppen werden nach wie vor zugewiesen wie es eigentlich sein sollte, lediglich die Stats Seite ist nicht mehr aufrufbar...
Jemand eine Idee warum?

**Comment by Shad86** [comment]
gibt es dazu eventuell einen screenshot, so das ich mir ein Bild davon machen kann, wie sich das mit dem Login genau äußert?

MfG

Shad86

**Comment by Shirobaka** [comment]
![chrome_2017-09-09_17-28-36](https://user-images.githubusercontent.com/8634317/30241478-753dc89a-9584-11e7-812c-9cd02f9c32a3.png)

**Comment by Shad86** [comment]
Das müsste apache seitig sein, heißt du hast irgendwas auf deinem webserver mit einem Passwortschutz versehen/eingerichtet.

Vom Ranksystem selbst kommt das nicht.

**Comment by Shirobaka** [comment]
Ich habe keine .htaccess im Verzeichnis, habe auch keine Änderungen am Server vorgenommen.
![winscp_2017-09-09_18-24-12](https://user-images.githubusercontent.com/8634317/30241897-6c2ff112-958c-11e7-8442-557a060cd9c8.png)

**Comment by Shad86** [comment]
Wie gesagt, einfach so kommt da nicht eine passwort abfrage zustande. Es muss etwas auf dem Server verändert worden sein.

Mal die configs vom Apache abklappern und durchforsten.

Wie gesagt, vom Ranksystem selbst kann das nicht kommen und schon gar nicht von heute auf morgen sich verändern ohne das was verändert wird.

Im übrigen da du ja (so wie ich das verstanden habe ) nur bei der statts seite die passwortabfrage bekommst auch mal den Inhalt des "stats" Ordners überprüfen.

MfG

Shad86

**Comment by Shirobaka** [comment]
Im Stats Ordner befindet sich ebenfalls keine .htaccess, das Problem habe ich seit etwa 2 Tagen, die Webinterfaceseite geht ohne Problem, auch jede andere Website ist problemlos aufrufbar, nur die Stats Seite nicht

**Comment by Shad86** [comment]
Damit habe ich noch nicht gearbeitet. Vielleicht sind da irgendwelche Einstellungen zu finden.

**Comment by Shirobaka** [comment]
Hab gerade mal nachgeschaut, habe dort keinen Verzeichnisschutz aktiviert, wüsste nicht was da der Fehler sein sollte...

**Comment by Shad86** [comment]
öhm hast du das ganze bei ts.n.net gehosted?

**Comment by Shirobaka** [comment]
Nee, meinte damit das ich gesehen habe das deren Seite nen MySQL Fehler hat und ob es evtl. daran liegen kann, weis ja nicht wie lange die das Problem schon haben

**Comment by Shad86** [comment]
Wie sollte ein defekt auf einer anderen Seite/System, dich auf einem völlig anderen system beeinflussen? Das entzieht sich mir jedweder Logik

**Comment by Shirobaka** [comment]
Ich weis ja nicht wie das ganze geschrieben wurde, z.B. Wenn die Versionsüberprüfung fehlschlägt weis ich ja nicht wie das ganze System reagiert^^
War ja nur ne Idee gewesen da ich wie bereits beschrieben absolut keinen Fehler bei mir finden kann

**Comment by Shad86** [comment]
Die Seite ist schon seit Februar immer wieder fehlerhaft, da zudem der Dev seit Februar nicht mehr zu sehen war.

Wie gesagt zu dem passwort Problem müsstest du mal google befragen ob du da was findest. Zudem du ja auch sagtest, das es auf einmal passierte und Dinge passieren an sich "nicht einfach so aus dem nichts" Es muss was Server seitig bei dir verändert worden sein.

Denn wenn es erst ohne Passwort ging und auf einmal auftauchte muss ja eine Änderung stattgefunden haben.

Wie gesagt vielleicht weiß ja google mehr zu imscp und solchen passwort Problemen.

MfG

Shad86

**Comment by maxlxl** [comment]
Falls hier noch Hilfe bezüglich Apache gebraucht wird, kann ich mich anbieten mir das ganze mal genauer anzuschauen. Dazu bitte einfach auf meinem TS (ts.maxlxl.de) vorbeischauen, oder hier antworten ;)

**Comment by Shirobaka** [comment]
Ich habe den Grund gefunden, das Problem lag wirklich an i-MSCP bzw. um genauer zu sein an AWStats, der sorgte dafür das automatisch bei der Eingabe von www.domain.de/stats/ eine Passwortabfrage kommt um dort die Statistik der Website abrufen zu können, allerdings denke ich das es sich hier um einen Fehler von i-mscp handelt da dieser vor dem Update zu 1.5.1 noch nicht war.
Ich habe nun erstmal die /stats/ Seite den Ranksystem's in /statistics/ geändert, damit ist das Problem behoben.

**Comment by Shad86** [comment]
Okay, ja so ist das mit den progrämmchen :D ein update und zack schleicht sich wo was ein :). Schön das du den "Fehler" gefunden hast und nun alles wieder geht.
