### ISSUE TITLE
Problem with install / setup 

### ISSUE THREAD

**Issue by solding** [Newcomer1989/TSN-Ranksystem#350]
running it on windows. fixed the webinterface and db / query login etc everything fixed. but the bot dont start and I get no log file / error.. 

But after some searching i found this, need to make some windows task ? tried it but simply dont understand exactly how to create this task so it works. anyone that can help me explain :)

![ranksys_install](https://user-images.githubusercontent.com/7951072/30350278-577676d8-9816-11e7-8d74-9033d2714424.PNG)

**Comment by Hunt3red** [comment]
Same exact thing happens to me

**Comment by Newcomer1989** [comment]
In most cases it is a permissions problem. Please check you have set the file permissions correct for windows. Especially the folders avatars, logs and updates needs read and write permissions for the user (which is executing the ranksystem).

Also it could be a problem with the execution of PHP. Here please open a console and execute the command `php -v`. With that command you should get your PHP version.
When you got here no result, you have to check how PHP is installed and how you can run PHP on your machine. This way you can define in the `other/phpcommand.php`. Examples are already inside.

Please give us a short feedback all is working with this hints or if you still have problems, where it appears.

**Comment by Newcomer1989** [comment]
Please also take note aboute the following thread. We have tried to describe summary all needed steps there.

https://github.com/Newcomer1989/TSN-Ranksystem/issues/369

**Comment by Newcomer1989** [comment]
Release 1.2.3 is pusblished. There are added a few more checks to the install.php, which should ensure all requirements are met or otherwise give you a detailed report on what is missing.
