### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by HaxXorHardy** [Newcomer1989/TSN-Ranksystem#351]
where to find install install instructions?
this link does not work anymore. https://ts-n.net/ranksystem.php#install

**Comment by Shad86** [comment]
Here are the requierments:

![minimal-requ](https://user-images.githubusercontent.com/18570683/30435167-65e67930-9969-11e7-99e7-d797c213ec7d.PNG)

**Comment by Shad86** [comment]
i think that should make it clear what you need for it.

installation is quite simple:

put it on your webspace, be sure the things get executed as the webuser and go to the install.php, this will mainly guide you through the installation.

dont forgett to setup a cronjob after you finish that executes every 10 min the worker.php with check.

for example:

*/10 * * * * sudo -u www-data php /path/to/your/ranksystem/worker.php check >/dev/null 2>&1

**Comment by bykidi** [comment]
I highly suggest you to use Webmin to manage cronjobs.
It's point&click easy to use that
1. click add
2. choose user
3. choose command
4. choose how to execute (when/how often)
5. save
6. done

**Comment by fabm3n** [comment]
@Shad86 are you able to edit the Wiki? A install page would be helpfull.

**Comment by Shad86** [comment]
Yeah, i will do it asap.

**Comment by Hunt3red** [comment]
This looks so unbelievably advanced, so I'll give you guys a simpler method.

Step 1 (Webspace): Install wamp or xampp. It has a mysql server with the plugins you need. And it has an apache server. (The 2 last points on webspace, I have no idea how to do)

Step 2 (Database): Wamp fixed this whole step. All you need to do is for example download HeidiSQL to make a new database called ts3_ranksystem (This database name can be changed when you're installing the web interface)

Step 3 (TS3 Query account): As far as I know, all you have to do is just open go to your TS3 server, click Tools > ServerQuery Login. And just create an account and write down the password and username. You have to be logged on a server admin account or at least have the permissions written in the requirements.

Other steps: The web interface requires you to have a mysql password. To create one with wamp, just left click the wamp icon on the taskbar > MySQL >MySQL console. Then you can write:
SET PASSWORD for 'root'@'localhost' = password('enteryourpassword');
and
SET PASSWORD for 'root'@'localhost' = password('enteryourpassword');
and
SET PASSWORD for 'root'@'localhost' = password('enteryourpassword');

Job scheduler I have no idea how to do

Info: Wamp doesn't have https support, but everything seems to work fine anyways. I just get a warning for saying it's not so secure without https.

Also, Shad86, my bot isn't starting. Do you know how I can fix it? And how do I set up a cronjob, and where do I do that?

**Comment by Shad86** [comment]
I've never had a Windows server before, so I can't help you in this case. :/

**Comment by fabm3n** [comment]
I also have problems on windows so use Linux @hunt3red

**Comment by Hunt3red** [comment]
Hey guys, update here. Using linux now. I still can't get the bot to start :/ Using xampp for webserver and mysql. Maybe @Shad86 you could make a guide on how to install a web server and other software with all the addons you need? I know there's a lot of tutorials out there, but they aren't for this rankup bot, and I need to know how to tie everything together

**Comment by Hunt3red** [comment]
I went to x.x.x.x/folder/jobs/bot.php and this is the error it gave me:

**Comment by Shad86** [comment]
The requirements are already listed in this topic.

Your answer and its output from bot.php has probably been removed from you.
So I can't really help you.

How to install a web server on Linux (for example)-> http://www.itzgeek.com/how-tos/linux/debian/how-to-install-lamp-server-on-debian-9-stretch.html

Personally, I don't use third-party software like xamp, plesk, etc. because it mostly only causes more problems than it helps.

With these packages, you should have everything you need:

As a suggestion for a Debian9 system:

`apt-get install mariadb-server mariadb-client`

`apt-get install apache2`

`apt-get install php7.0-zip php7.0-curl php7.0-xml php7.0-mysql php7.0-common`

`apt-get install phpmyadmin`

If I forgot something, the web interface will inform you about it during the installation process anyway.

**Comment by Shad86** [comment]
Done https://github.com/Newcomer1989/TSN-Ranksystem/wiki/Install-Requierements-and-Instructions

all non relevant threads got deleted, if you still have issues open an own issue - thanks!
