### ISSUE TITLE
Beendet sich um 2:53

### ISSUE THREAD

**Issue by creativefx** [Newcomer1989/TSN-Ranksystem#353]
Moin,
gibt es die möglichkeit den Bot automatisch per crontab zu starten? bzw neu zu starten?

Gruß
Ole

**Comment by Shad86** [comment]
`*/10 * * * * sudo -u www-data php /path/to/your/ranksystem/worker.php check >/dev/null 2>&1`
(Pfad muss angepasst werden und user eventuell auch wenn hier ein anderer webuser verwendet wird)

Hiermit würde er alle 10min überprüfen ob das ranksystem noch läuft

**Comment by Shad86** [comment]
Ich vermute, dein problem ist hiermit gelöst (da keine Antwort mehr darauf erfolgte) *closed*
