### ISSUE TITLE
the bot dont contect into channel

### ISSUE THREAD

**Issue by AlFcl** [Newcomer1989/TSN-Ranksystem#354]
the system works perfectly. The only problem that does not connect the bot to the indicated channel. I would also like to know how I can edit groups that represent levels.

**Comment by Shad86** [comment]
So the bot at least connect to your ts3-server but doesn't switch to the channel you setup?

>  I would also like to know how I can edit groups that represent levels.

under /webinterface and there you login and then under "core" you can setup your groups.

you can also click on the word "**rank up definition**" for getting an explanation how it works.

**Comment by AlFcl** [comment]
thx for the help
