### ISSUE TITLE
[SOLVED] Bot startet, aber wird nicht via TeamSpeak3 erkannt bzw gibt keine Ranks

### ISSUE THREAD

**Issue by ZeitZumKiffen** [Newcomer1989/TSN-Ranksystem#355]
So, ich komm nicht mehr weiter und weiß auch nicht ganz genau woran das Problem liegen könnte. Mein Ranking Bot reagiert seit 2-3 Tagen nicht mehr bzw er sagt mir via Stats Panel "Die Informationen auf dieser Seite scheinen veraltet! Es scheint, das Ranksystem ist nicht mehr mit dem TS3 verbunden." was ich aber bin. Laut der Start Log vom Bot: 
`2017-10-08 13:48:38.415163   INFO      Bot starts now his work!
2017-10-08 13:48:38.415082   INFO        Could not join specified channel.
2017-10-08 13:48:38.412320   INFO        Connection to TS3 Server established.
2017-10-08 13:48:38.386725   INFO      Connect to TS3 Server (Address: "ts.zeitzumkiffen.de" Voice-Port: "9987" Query-Port: "10011").
2017-10-08 13:48:38.386666   INFO      Loading addons [done]
2017-10-08 13:48:38.386601   INFO        Addon: 'assign_groups' [OFF]
2017-10-08 13:48:38.386292   INFO      Loading addons...
2017-10-08 13:48:38.386215   INFO        Ranksystem Version: 1.2.2
2017-10-08 13:48:38.386080   INFO        Check files permissions [done]
2017-10-08 13:48:38.372001   INFO        Check files permissions...
2017-10-08 13:48:38.371713   INFO        No newer version detected; Database check finished.
2017-10-08 13:48:38.371578   INFO      Check Ranksystem database for updates.
2017-10-08 13:48:38.365705   INFO      Initialize Bot...`

ist er erfolgreich gestartet, ohne Probleme.

Kann man irgendwie mehr als nur die Log File sehen? Will nicht die ganzen Ranks reseten und neu einspielen, auch via TeamSpeak3 Server in der Blacklist steht nix :/ Hoffe ich hab das im passenden Thread gepostet und bitte um entschuldigung wenn es falsch ist. 

Server:  Linux Server mit Debian 8 & Plesk 

EDIT: Wie es aussieht, connectet er am Anfang auch, aber 2 Sekunden später ist er wieder runter vom TeamSpeak3 Server ohne jede Fehlermeldung

Mit freundlichen Grüßen

**Comment by Shad86** [comment]
Hallo,

gerade bei Plesk liegt das problem bei der php version und das im Standart php5.4 hinterlegt ist, was nicht vom ranksystem unterstützt wird.

Unterstütze Versionen php5.5-php7.1

Um das auszuschließen bitte einmal in den ranksystemordner gehen und unter "other" phpcommand.php mit einem editor öffnen (z.B. notepad++) dort $phpcommand = "php"; auskommentieren -> #$phpcommand = "php"; und dann den Pfad zu php5.6 oder 7.0 oder 7.1 suchen und in der phpcommand.php angeben.

Das ganze könnte dann so aussehen:

> <?PHP
> ## Uncomment the command you need to run PHP
> ## This are only examples
> ## If you miss one, feel free to add it
> ## Only one command should be active at the same time!
> #$phpcommand = "php";
> #$phpcommand = "php56";
> #$phpcommand = "php70";
> $phpcommand = "/path/to/plesks/php7";
> #$phpcommand = "/usr/bin/php";
> #$phpcommand = "C:\PHP5\php.exe";
> #$phpcommand = "C:\PHP7\php.exe";
> #$phpcommand = "\"C:\Program Files (x86)\PHP\php.exe\"";  // on blanks you need special marks \"
> #$phpcommand = "c:\wamp\bin\php\php.exe";
> ?>

**Comment by ZeitZumKiffen** [comment]
Hallo Shad86, Danke erstmal für deine Antwort bzw Tipp. Hab das mal gemacht, nun wird mir keine Log mehr angezeigt und der Bot startet so auch nicht^^

Das ganze sieht dann jetzt so aus
#$phpcommand = "php";
#$phpcommand = "php56";
#$phpcommand = "php70";
$phpcommand = "/opt/plesk/php/7.0";
#$phpcommand = "/usr/bin/php";
#$phpcommand = "C:\PHP5\php.exe";
#$phpcommand = "C:\PHP7\php.exe";
#$phpcommand = "\"C:\Program Files (x86)\PHP\php.exe\"";  // on blanks you need special marks \"
#$phpcommand = "c:\wamp\bin\php\php.exe";

Schon komisch das er es einfach so gemacht hatte, keiner hatte Zugriff auf dem Bot außer ich und ich hatte seit ca paar Monaten nix dran gemacht. Was könnte das Problem sein?

**Comment by Shad86** [comment]
Ich bin an und für sich nur aufm TS3 unterwegs -> hdf-multigaming.de

**Comment by ZeitZumKiffen** [comment]
Okay, sonst haben sie auch keine Ahnung woran es liegen könnte das auf einmal das Ranking System nicht mehr aus diesen Gründen (oben beschrieben) geht. Es ist schon komisch nach dem er connectet ist er ca 5 Sekunden drauf, danach geht er^^

Meine User fragen nämlich schon was mit dem RankingSystem los ist^^

**Comment by Shad86** [comment]
nein leider so erstmal nicht, muss ich mir mal genauer anschauen

**Comment by ZeitZumKiffen** [comment]
CRITICAL  Request to start the Ranksystem from 66.102.9.4. It seems the request came not from the command line! Shuttin down!

Bin bissen weiter gekommen (denke ich) nun sagt er mir das

**Comment by Shad86** [comment]
Wie startest du denn das Ranksystem?

**Comment by ZeitZumKiffen** [comment]
Über das Webinterface, Domain liegt auch drauf^^

**Comment by Shad86** [comment]
ich wäre noch 5min. weg und dann würde ich sagen, kommst ma eben auf'm TS3-Server vorbei sonst schreiben wir wohl noch bis morgen früh hier hin und her :D

**Comment by ZeitZumKiffen** [comment]
Problem ist gelöst, einfach komplett neuinstalliert danach Datenbank eingespielt und Tada es ging.

Ein Danke geht nochmal an Shad86 der auch versucht hat das Problem zu finden :D (so easy)  kann geschlossen werden.
