### ISSUE TITLE
[SOLVED] Webpage displays only text

### ISSUE THREAD

**Issue by Hunt3red** [Newcomer1989/TSN-Ranksystem#356]
I started with a fresh server and followed the new installation guide. Didn't get far, as the website displayed the pages as pure text. Tried a lot of things, but to no help.

Is there something you forgot to add to the guide?
Using Linux Mint 18.2, trying to install Debian9(Stretch) tomorrow.

**Comment by bykidi** [comment]
website is almost dead

here https://github.com/Newcomer1989/TSN-Ranksystem/wiki/Install-Requierements-and-Instructions

**Comment by Hunt3red** [comment]
I finally found a fix to the problem!

`sudo apt-get install php libapache2-mod-php php-mcrypt php-mysql`

**Comment by Hunt3red** [comment]
Also maybe doing only `chmod 777 index.php install.php webinterface/` might be enough to get into address.com/foldername/install.php and install the whole thing

**Comment by bykidi** [comment]
oh, you mean the installation itself.
ok.
