### ISSUE TITLE
Time left for next rankup timer is going up or doesen't change (more or less)

### ISSUE THREAD

**Issue by PoW3rKj** [Newcomer1989/TSN-Ranksystem#357]
The time left for next rankup for each user go 1 sec up and 2 down.. so the time is not truthful.

chronological order:
http://prntscr.com/h658p0
http://prntscr.com/h658qu

**Comment by Shad86** [comment]
That can be, because you generate "active time" and "idle time" so the time differs a little bit.

The value from active / online time and idle time gets compared every round it makes, so it could be that the time may moves up, but the ranksystem gets the times.

**Comment by PoW3rKj** [comment]
I've been online for 5 or more hours today but now the rank system shows only 1,5h

Thanks for your help

**Comment by Shad86** [comment]
you sure about that you use online time and not active time? because active time only counts "talk time" (time where you not idle)

**Comment by PoW3rKj** [comment]
Can't believe it, i thought "active tive" means the time when you are not muted or you are not speaking for a long time

**Comment by Shad86** [comment]
depends on how you set it up in the webinterface. Under "core" there is a field with "ignore idle" there you can set how long the idletime will be ignored until it gets count as "real idle time"

> Define a period, up to which the idle time of an user will be ignored.
