### ISSUE TITLE
Root password change

### ISSUE THREAD

**Issue by enioli98** [Newcomer1989/TSN-Ranksystem#358]
Hey I changed my root password recently and don't know where to switch it in the configs of the bot. Can anyone help me? Thanks :)

**Comment by Shad86** [comment]
The bot itself doesn’t need at any time your root password from your VPS/Dedicated Server.

You may mean query login? That can be set in the Webinterface.

(„YourHp.com/ranksystem/webinterface.php“)

Regards

Shad86

**Comment by enioli98** [comment]
nope that's not what i meant... the bot doesn't seem to be able to work anymore so i thought it was bc of the pw change, but it seems to be more difficult... damn
