### ISSUE TITLE
Error 520

### ISSUE THREAD

**Issue by enioli98** [Newcomer1989/TSN-Ranksystem#359]
Always get the error 520: "invalid loginname or password". How can I fix this?

**Comment by Shad86** [comment]
Where do you get this? You may have a screenshot?

**Comment by enioli98** [comment]
Das steht in der Konsole vom Webinterface... Leider kann ich im Moment grade keinen Screenshot machen. 
-- 
Sent from my Android phone with GMX Mail. Please excuse my brevity.On 08/11/2017, 19:21 Shad86 <notifications@github.com> wrote:
Where do you get this? You may have a screenshot?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Newcomer1989/TSN-Ranksystem","title":"Newcomer1989/TSN-Ranksystem","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Newcomer1989/TSN-Ranksystem"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Shad86 in #359: Where do you get this? You may have a screenshot?"}],"action":{"name":"View Issue","url":"https://github.com/Newcomer1989/TSN-Ranksystem/issues/359#issuecomment-342908849"}}}

**Comment by Shad86** [comment]
Also du hast die Loginseite von z.b. link-zur-seite.de/ranksystem/webinterface.php und gibst da deine Logindaten ein und bekommst dann den 520 error?

**Comment by enioli98** [comment]
Nein, wenn ich den Bot starte steht dann in der Konsole des Bots dass die Logindaten nicht korrekt sind. 
-- 
Sent from my Android phone with GMX Mail. Please excuse my brevity.On 09/11/2017, 20:58 Shad86 <notifications@github.com> wrote:
Also du hast die Loginseite von z.b. link-zur-seite.de/ranksystem/webinterface.php und gibst da deine Logindaten ein und bekommst dann den 520 error?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Newcomer1989/TSN-Ranksystem","title":"Newcomer1989/TSN-Ranksystem","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Newcomer1989/TSN-Ranksystem"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Shad86 in #359: Also du hast die Loginseite von z.b. link-zur-seite.de/ranksystem/webinterface.php und gibst da deine Logindaten ein und bekommst dann den 520 error?"}],"action":{"name":"View Issue","url":"https://github.com/Newcomer1989/TSN-Ranksystem/issues/359#issuecomment-343273692"}}}

**Comment by Shad86** [comment]
Dann wären 3 Sachen Interessant was benutzt du? 

Webspace oder V-Server?

Falls V-Server oder Server im Allgemeinen. Windows oder Linux?

Wie startest du das ganze?

**Comment by Shad86** [comment]
Da keine weitere Antwort erfolgte, schließe ich das issue hiermit vorerst, sollten doch noch Fragen sein, einfach antworten.
