### ISSUE TITLE
Text nachricht vom Ranksystem ändern

### ISSUE THREAD

**Issue by ReacTElekTRiXx** [Newcomer1989/TSN-Ranksystem#36]
Hallo, ich habe mir vor kurzem das ranksystem geholt und habe es eingestellt und es hat alles funktioniert Und jetzt habe ich gesehen das ich nirgendwo die Nachricht einstellen kann wen man ein rankup bekommt. Ich hoffe ihr könnt mir helfen .

MFG ReacTElekTRiXx

**Comment by Newcomer1989** [comment]
You can edit the Rankup Msg inside the language files (i.e. core_en.php).
There you found two different messages:
$lang['usermsgactive'] for active time (if parameter idletime is on)
$lang['usermsgonline'] for online time (if parameter idletime is off)
