### ISSUE TITLE
Bot reagiert nicht + Keine Logs

### ISSUE THREAD

**Issue by TimDardy** [Newcomer1989/TSN-Ranksystem#360]
Hey Leute warum auch immer kann sich mein Bot anscheinend nicht mit dem TS verbinden...
Hab alle LoginDaten überprüft etc.
Dazu kommt da er mir einfach keine Logs ausspucken will...
Im Logs Ordner finde ich nur eine Textdatei (Zumindest das Symbol davon) aber diese Trägt keinen Namen und in der Datei steht nur: *!.gitignore

Sowie im Webinterface steht nichts...

**Comment by Shad86** [comment]
Worauf läuft das ganze? Webserver oder Vserver? Linux oder Windows?  Welches Betriebsystem?

**Comment by Shad86** [comment]
Da keine weitere Antwort erfolgte, schließe ich das issue hiermit vorerst, sollten doch noch Fragen sein, einfach antworten.
