### ISSUE TITLE
Server offline but bot online and working

### ISSUE THREAD

**Issue by elam023** [Newcomer1989/TSN-Ranksystem#361]
I installed the ranksystem on a VPS with Debian 8.
The bot working well but not the webinterface, it show that the server is offline. It not show also the stats graphics.
The list of ranks show the users but not the icons of relative server-group assigned.

I tried also to reinstall the ranksystem but nothing.

**Comment by Shad86** [comment]
What type of DB you'r using?
Which Php version is in use?

**Comment by elam023** [comment]
mysql  Ver 14.14 Distrib 5.5.58, for debian-linux-gnu (x86_64) using readline 6.3

PHP Version 5.6.30-0+deb8u1

**Comment by Shad86** [comment]
looks fine, from that point.

could you provide me a link, so that i can see exactly whats happening on your site?

If you dont want to send it public you can also send it through mail -> rank@hdf-multigaming.de

regards

Shad86

**Comment by elam023** [comment]
I sent you the details via mail

**Comment by Shad86** [comment]
I'm not 100% sure but there could be one of two probelms:

1. It could be a rights Problem (so not everything is write/readable)

As i don't know how or which webspace you use.

If its standart apache / php then pls do 

`cd /var/www/html`
`chown www-data:www-data tsn-ranksystem/* -Rf`

If its still not working it may could be:

2. Files are corrupted (so may redownload it and reinstall it)

If both is'n working i could offer you to help over teamviewer or i could offer to host it for you.

regards

Shadow86

**Comment by Newcomer1989** [comment]
Also the logs/ranksystem.log would be interessting to solve your problem. You sent this already to Shad86? Perhaps one of you could send me this too (admin@ts-n.net)? Then I would have a look to that.

**Comment by bykidi** [comment]
Nice to see that you are back, officially :)

**Comment by Newcomer1989** [comment]
The ranksystem.log says you the problem.

> 2017-12-18 12:40:29.413004   ERROR     calc_serverstats 1:Array
> (
>     [0] => HY000
>     [1] => 2006
>     [2] => MySQL server has gone away
> )

Everytime the Ranksystem tries to save the servergroups to the database, it got an error. Perhaps it is to much for your database (which should be a missconfiguration of the database).

Please try to contact me on our TS server (ts-n.net). We can have a look about remote session it is really a database problem. Perhaps we can fix it.

**Comment by Newcomer1989** [comment]
Solved via remote session.

The problem is, that the size of the parameter for a single query update/insert is to small. It need to be increased, that the full query command could sent to the database.

Here you'll find more information how to check/configurate your database:
https://dev.mysql.com/doc/refman/5.7/en/packet-too-large.html
