### ISSUE TITLE
update_groups 3:Array

### ISSUE THREAD

**Issue by AgendZero** [Newcomer1989/TSN-Ranksystem#363]
Hallo ich habe folgendes Problem. Der Bot crasht immer um 1 Uhr nachts und der Cronjob kann diesen auch nicht mehr starten, bzw. Wenn ich manuell die worker.php über bitvise ausführen mit "check" erhalte ich ebenfalls einen Fehler.

`2017-11-29 01:00:02.239413   ERROR     update_groups 3:Array`

und über Bitvise erhalte ich folgenden Fehler:

`: No such file or directory
./worker.php: line 2: syntax error near unexpected token `0'
'/worker.php: line 2: `error_reporting(0);`

Kann mir das jemand erklären?

**Comment by Shad86** [comment]
Wie startest bzw. wie führst du die worker.php aus?

**Comment by AgendZero** [comment]
Eigener V-Server
Den Cronjob habe ich wie beschrieben eingetrage im crontab.
Und manuell führe ich in im entsprechendem verzeichnis mit "./worker.php check" aus.

**Comment by Shad86** [comment]
Dachte ich mir schon.

Die Worker.php ist keine sh datei sondern eine php datei und muss dementsprechend, wie der crontab ausgeführt werden.

z.B.:

sudo -u www-data php /var/www/html/ranksystem/worker.php check

Das nächste ist, wenn du den Cronjob wie beschrieben anlegst, sollte ein manuelles ausführen eigentlich nicht mehr notwendig sein, denn der Cronjob überprüft ja genau das und startet (sollte der prozess nicht mehr laufen) das ganze erneut.

Eventuell mal die Berechtigungen überprüfen ob der "tsn ordner" auch den standart webuser gesetzt hat, so das der cronjob auch das ganze überhaupt neustarten kann.

Ich habe die Wiki auch nochmal etwas überarbeitet:
https://github.com/Newcomer1989/TSN-Ranksystem/wiki/Install-Requierements-and-Instructions

Sollte es wiedererwartend nicht gehen, kann ich gerne auch mal mit dir drüber schauen.

MfG

Shad86

**Comment by AgendZero** [comment]
Ich habe das Problem, dass mein System den Befehl "sudo" nicht kennt?

**Comment by Shad86** [comment]
Sollte mit `apt-get install sudo` gelöst werden können.

**Comment by AgendZero** [comment]
Ich habe es mal versucht. Gebe morgen Feedback ob es alles so funktioniert.

**Comment by Shad86** [comment]
und wie schauts aus? Läuft es oder nicht? :)

**Comment by AgendZero** [comment]
Ich habs gebacken bekommen. Es scheint zu laufen.
