### ISSUE TITLE
 CRITICAL  Your PHP version is below 5.5.0.

### ISSUE THREAD

**Issue by MonsterrockyXxX** [Newcomer1989/TSN-Ranksystem#364]
Guten Tag, 
Habe versuch es auf meinem Server zu installieren doch angeblich ist meine php Version unter 5.5.0 (5.4.45-0+deb7u11) . Ich habe Plesk installiert und habe aber php 5.6.32 installiert trotzdem gibt er mir diesen Fehler

**Comment by MonsterrockyXxX** [comment]
sobald ich phpcommand anderen pfad angebe gibt er keinen log eintrag mehr raus

**Comment by Shad86** [comment]
Plesk hat meist mehrere Versionen von php "inklusive" dabei.

Denk bitte daran, wenn du die phpcommand abänderst das nur eine Zeile aktiv ist, alle anderen Zeilen sollten mit # angeführt sein.

Zu guter letzte stelle natürlich sicher, das die Angaben richtig sind.

**Comment by MonsterrockyXxX** [comment]
php info gibt mir 5.6.32 raus . ich habe extra in plesk 5.4.45 deinstalliert. sobald ich einen anderen eintrag wähle geht es nicht ich setze die raute um und die log schreib nicht mal mehr falsche version

**Comment by Shad86** [comment]
Kannst du mal folgendes tun:

gehe in den Ordner "jobs/" und kommentiere in der Datei "bot.php" folgende Zeile aus:

`error_reporting(0); / (ändern zu //error_reporting(0);)` (sollte in Zeile 6 sein)

in putty dann einmal manuell die jobs/bot.php ausführen

`php jobs/bot.php`

Die Ausgabe davon bitte hier einmal posten.

**Comment by MonsterrockyXxX** [comment]
Wenn ich den Befehl so ausführe kommt gar nichts springt einfach in neue eingabe

**Comment by Shad86** [comment]
Dann sollte er eig. korrekt starten. (Wenn du Querys auf deinem Teamspeak siehst, solltest du auch sehen das er kurzzeitig verbindet) Zudem sollte auch ein logeintrag nun vorhanden sein.

Wenn dem so ist, vermute ich einfach das es ein Berechtigungsproblem ist.

Also auch mal sicherstellen das die Ordner den richtigen webuser haben und der crontab auch mit etwaigem webuser angelegt wird.

Das einzige was noch sein könnte, wäre das wenn du auf start drückst, das er auf den systemeigenen webuser versucht zuzugreifen, was meist www-data ist. (da bin ich mir nicht 100% sicher)

Heißt du müsstest ihn eventuell manuell per console einmalig starten, danach würde es ja der cronjob überprüfen.

beispiel:

`sudo -u deinwebuser /var/www/pfad/zu/ranksytem/und/worker.php check`

sollte sudo nicht installiert sein:

`apt-get install sudo`

MfG

Shad86

**Comment by MonsterrockyXxX** [comment]
in der Console steht nun Starting the Ranksystem Bot. [OK]
aber in der Log wieder 
2017-12-05 13:41:01.712085   CRITICAL  Your PHP version (5.4.45-0+deb7u11) is below 5.5.0. Update of PHP needed! Shuttin down!

**Comment by Shad86** [comment]
kannst du mir mal einen screenshot von deiner derzeitigen phpcommand.php schicken?

**Comment by MonsterrockyXxX** [comment]
![phpcommand](https://user-images.githubusercontent.com/1352923/33610920-09dc02f0-d9cd-11e7-82e9-5c45cdfe41d2.jpg)
wenn ich zeige 9 aktiviere schreibt er keinen Eintrag mehr in die log  und macht nichts

**Comment by Shad86** [comment]
Du bist dir sicher das php5.6 genau da drin liegt?

Sieht mir sehr nach einem allgemeinen Pfad aus wo dann die unterversionen noch aufgeteilt sein könnten.

ansonsten auch mal Zeile 7 ausprobieren.

**Comment by MonsterrockyXxX** [comment]
Da hab ich nur noch einen unter ordener 5.6 und 7.0. Zeile 7 gleiches resultat

**Comment by MonsterrockyXxX** [comment]
![php info](https://user-images.githubusercontent.com/1352923/33611447-b6911cc8-d9ce-11e7-99c6-9dad1300448c.jpg)

**Comment by Shad86** [comment]
dann leite mal auf den unterordner 5.6 also "opt/plesk/php/5.6" in zeile 9

**Comment by MonsterrockyXxX** [comment]
gibt keinen logeintrag durch putty aber Starting the Ranksystem Bot. [Failed]

**Comment by Shad86** [comment]
schau mal jetzt mit dem eintrag, da du ja failed bekommst was er mit dem starten der bot.php sagt

**Comment by Newcomer1989** [comment]
Wenn  du in der Konsole den Befehl `php -v` eingibst, welche Version erscheint dort?

Vermutlich wird dies die PHP 5.4.* sein. Das würde dann zeigen, dass als default eine uralte Version hinterlegt ist.
Damit hast du zwei Möglichkeiten:
1) In der phpcommand.php den Pfad zum Aufruf einer aktuellen PHP Version hinterlegen. Beispiele sind definiert. Der Aufruf kann mit Param `-v` in der Konsole zuvor getestet werden.
2) Wohl der sinnvollere Weg.. Für den Standardaufruf von PHP auf deinem Server eine aktuelle PHP Version hinterlegen. Google ist dein Freund hierfür ;-)

**Comment by Newcomer1989** [comment]
Wir schließen den Issue mal. Es sollte mit vorgenannter Nachricht behebbar sein. Falls es wider Erwarten noch Probleme geben sollte, bitte einfach wieder öffnen.
