### ISSUE TITLE
enable the PHP exec function and try it again!

### ISSUE THREAD

**Issue by TheErrorDE** [Newcomer1989/TSN-Ranksystem#365]
ich habe nur ein webspace bei nitrado wie kann ich das machen damit es geht "PHP exec function need to be enabled but seems to be disabled. Please enable the PHP exec function and try it again!"

**Comment by Shad86** [comment]
Bei Nitrado nachfragen ob sie das in Erwägung ziehen, zu aktivieren. Nicht jeder hoster hat alle module aktiv oder aktiviert diese.

Solltest du erfolglos sein kann ich dir allerhöchstens noch anbieten, das ganze bei mir für dich zu hosten.

**Comment by Shad86** [comment]
Ich schließe den Thread hiermit, da keine weitere Antwort von dir erfolgte.
