### ISSUE TITLE
BOT STARTET NICHT KEINE LOGS ETC

### ISSUE THREAD

**Issue by Blacky1326** [Newcomer1989/TSN-Ranksystem#366]
Hey Leute warum auch immer kann sich mein Bot anscheinend nicht mit dem TS verbinden...
Hab alle LoginDaten überprüft etc.
Dazu kommt da er mir einfach keine Logs ausspucken will...
Im Logs Ordner finde ich nur eine Textdatei (Zumindest das Symbol davon) aber diese Trägt keinen Namen und in der Datei steht nur: *!.gitignore

Sowie im Webinterface steht nichts...

**Comment by Shad86** [comment]
Windows oder Linux? und welches OS Version?

**Comment by Blacky1326** [comment]
Windows und Windows 2012 Xampp Nutze ich Php 7 Getestet und auch Php 5 geht alles net.

**Comment by Shad86** [comment]
Mit Windows kann ich dir so gar nicht helfen leider. :/

**Comment by Newcomer1989** [comment]
Meist ist das ein Rechteproblem. Bitte also die Dateirechte von Windows prüfen. Speziell müssen die Verzeichnisse avatars, logs und updates volle Lese- und Schreibrechte bekommen, sodass der entsprechende User (mit dem das Ranksystem gestartet wird) dort Zugriff hat.

Weiterhin kann es auch ein Problem des PHP Aufrufs sein. Hier einfach mal in einem Eingabeaufforderungsfenster  den Befehl `php -v` eingeben. Damit solltest du die PHP Version erhalten. Kommt hier nichts, so müsstest du prüfen, wie du PHP installiert hast und es folglich aufgerufen wird. Der nötige Aufruf kann als Parameter dann in der `other/phpcommand.php` definiert werden. Beispiele sind dort bereits beschrieben.

**Comment by Newcomer1989** [comment]
Bitte auf den folgenden Thread beachten. Hier haben wir noch einmal übersichtlich und hoffentlich verständlich alle Schritte zusammengetragen.

https://github.com/Newcomer1989/TSN-Ranksystem/issues/369

**Comment by Newcomer1989** [comment]
Release 1.2.3 ist veröffentlicht. Hier sind in der install.php noch einmal weitere Checks aufgenommen worden, um sicherzustellen, dass die Anforderungen auch erfüllt werden.
