### ISSUE TITLE
Bot Timed immer aus nach 9sec ca. linux

### ISSUE THREAD

**Issue by Yatheria1** [Newcomer1989/TSN-Ranksystem#367]
Hallo ich habe das problem das der Bot immer wieder austimed und ich mitlerweile nicht mehr weis warum.
Habe es jetzt wieder installiert und schon auf sämtlichen versionen Probiert aber kein Erfolg. Im Log steht auch nix...

**Comment by Shad86** [comment]
Wie versuchst du das ganze zu starten?

**Comment by Shad86** [comment]
Da seit 11 Tagen keine Antwort von dir mehr erfolgte schließe ich den Issue. Im übrigen ist Version 1.2.3 raus gekommen vielleicht löst dies deine Probleme.
