### ISSUE TITLE
Linebreaks

### ISSUE THREAD

**Issue by FireEmerald** [Newcomer1989/TSN-Ranksystem#37]
I just took a short look inside the code, and found something like *calc_userstats.php* and *update_groups.php*.

- https://github.com/Newcomer1989/TSN-Ranksystem/blob/master/jobs/calc_userstats.php
- https://github.com/Newcomer1989/TSN-Ranksystem/blob/master/jobs/update_groups.php

Is it intended, that there are no line breaks at all? It's unreadable.

**Comment by Newcomer1989** [comment]
Yes, it is intended. The Ranksystem works as Bot 24/7, so the code will be cached. In this shema the filesize are 30-40% less. The unneeded signs for human readable needs also cpu time to handle as such.
So it is general a way to save ressources!

**Comment by FireEmerald** [comment]
@Newcomer1989 You are talking about **minified** files - these files should be provided in the [Release](https://github.com/Newcomer1989/TSN-Ranksystem/releases) section of your repository, added to each release as additional files. The development itself and the repository should be always in a human readable style.
