### ISSUE TITLE
Error while getting servergrouplist

### ISSUE THREAD

**Issue by Galaxy200** [Newcomer1989/TSN-Ranksystem#372]
So i just reinstalled my Root Server, now i am trying to Install my Ranksystem again, but i just get this Error in my log file: update_groups 1:2052: Error while getting servergrouplist: file input/output error.

the query has the right rights and everything.

**Comment by Newcomer1989** [comment]
That's a response of your TeamSpeak server:
"file input/output error"

There should be missing the ts3 permission "i_ft_file_browse_power".

**Comment by Galaxy200** [comment]
Sehe gerade das du Deutsch bist, schreiben wir mal Deutsch. :D
https://i.imgur.com/7ZGzuXI.png
Die rechte sollte die Query doch haben oder nicht?

**Comment by Newcomer1989** [comment]
Hat der Query User auch die im Screenshot aufgeführte Servergruppe?

**Comment by Galaxy200** [comment]
https://i.imgur.com/CNFmem9.png Sollte er haben, ich nutze serveradmin und diese hat doch Standardmäßig Admin Server Query, nicht? Außerdem habe ich die Rechte auch bei Quest Server Query hinzugefügt

**Comment by Newcomer1989** [comment]
Bitte noch den Nachtrag beachten.

**Comment by Galaxy200** [comment]
Danke, lag daran.

**Comment by Newcomer1989** [comment]
Ok, dann schließe ich den Issue mal ;-)
