### ISSUE TITLE
Keine Icons

### ISSUE THREAD

**Issue by Yatheria1** [Newcomer1989/TSN-Ranksystem#373]
also zb bei servergruppe zuweisen und bei der allgemeinen Rangliste werden die icons nicht angezeigt.
Was kann ich dagegen tun ? Icon sind im ordner...

**Comment by Newcomer1989** [comment]
Dürfte an den Apache Einstellungen liegen. Dort ist ein Alias hinterlegt, der das Icons Verzeichnis umlenkt, sodass die darin liegenden Dateien nach außen nicht angezeigt werden können.

Hier mal ein Beitrag aus einem anderem Repo von Git, was dir aber helfen dürfte.
https://github.com/MrBertie/taskpaperplus/issues/1#issuecomment-14761329

**Comment by Yatheria1** [comment]
Was habt ihr angedacht die 1,2,3 zu veröffentlichen ?

**Comment by Shad86** [comment]
Newcomer selbst steckt mitten in den Prüfungen muss sich derzeit noch darauf konzentrieren.

Von daher wird das Ranksystem erst nächstes Jahr wieder etwa ab Februar/März ‘18 mit Updates versorgt werden.

Es dauert also noch etwas - letztlich ja aber auch verständlich da man das Studium durchaus bestehen sollte ;) und dieses somit Vorrang vor allem anderen hat.

**Comment by Shad86** [comment]
Version 1.2.3 Released und "Fehler" behoben.
