### ISSUE TITLE
Issue after update from Debian Wheezy to Jessie

### ISSUE THREAD

**Issue by JoniVR** [Newcomer1989/TSN-Ranksystem#376]
Hi,

First of all, thanks for this ranksystem, it has served us great and I already donated once just because of how awesome it is. Thanks for your work.

So after updating to Jessie (I did have lots of issues with apache and had to reinstall it) I'm having issues with the ranksystem, I know this is probably something stupid, but I can't figure it out.

I'm getting:
```
<?PHP
$target = $_SERVER['HTTP_HOST'].rtrim(dirname($_SERVER['PHP_SELF']), '/\\').'/stats/';
if(isset($_SERVER['HTTPS'])) {
	header('Location: https://'.$target);
} else {
	header('Location: http://'.$target);
}
?>
```

when I try to open it inside a browser. 

Here's the link where you can see the issue:
https://vitaltactic.be/ranksystem/

Any idea on a way to fix this? Or should I just go ahead an reinstall? Will my database data be preserved in case of a reinstall?

Thanks for your time.

**Comment by Newcomer1989** [comment]
That should be a problem with your machine. Seems, there is PHP not correct configurated.

Is there running anything else on your site, which is working?

**Comment by JoniVR** [comment]
Yes, everything else is working correctly, but none of that is built with php, so it could indeed be an issue with the php configuration. I'll look into that.

Just one more thing, in case I can't fix it and have to reinstall, is it sufficient to remove the ranksystem folder and just do the install process again? Will the SQL data be overwritten or erased or will it just work?

Thanks again.

**Comment by Newcomer1989** [comment]
If you install the Ranksystem to the same database, it will be overwritten. So all data would be lost.

Try to install the Ranksystem a second time. **New** database and **new** space on the webserver!
On the install.php are some checks, to valid your system. If it runs well, the original instance should also runs perfect.

**Comment by JoniVR** [comment]
Alright thank you, after looking into it some more, it looks like php was just not enabled yet. Still not working, but that's a different issue and not related to this. Updating distribution versions sure is a pain in the ass.... Thanks for your time, helped me a lot!
