### ISSUE TITLE
Webinterface - Forgot password

### ISSUE THREAD

**Issue by EscuderoKevin** [Newcomer1989/TSN-Ranksystem#377]
Bot not connect (i change serveradmin password for TS3)
i dont remember my  password in webinterface 

Solution (? ♥

**Comment by Shad86** [comment]
http://your-homepage.com/tsn-ranksystem/webinterface

![password-recovery](https://user-images.githubusercontent.com/18570683/34474860-7ef5a758-ef85-11e7-96c9-076dd01290e6.png)
