### ISSUE TITLE
Cronjobs anlegen

### ISSUE THREAD

**Issue by VisMotrix** [Newcomer1989/TSN-Ranksystem#379]
Can you confirm if this cronjob is right ?
![cronjob](https://user-images.githubusercontent.com/35074091/34532293-e5e1e93c-f0b5-11e7-8038-ddc73a4d090f.PNG)

the command:
/home/www/Subdomains/ts3ranking/worker.php check >/dev/null 2>&1

**Comment by Shad86** [comment]
usually on linux the correct path is /var/www/Subdomains/..... but its your system, so you have to check where it is.

**Comment by Shad86** [comment]
If its still not working or if you have any question about it, just open a new issue and may refer to this one if needed.
