### ISSUE TITLE
Stats page wont open

### ISSUE THREAD

**Issue by ShrewdSpirit** [Newcomer1989/TSN-Ranksystem#38]
Hello. I'm getting this error when I open ranksystem/stats/ and that page wont open
```
2016/05/17 15:21:19 [error] 2308#0: *40809 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to a member function fetchAll() on a non-object in /www/ranksystem/other/session.php on line 1" while reading response header from upstream, client: 91.99.161.74, server: test.com, request: "GET /ranksystem/stats/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "test.com"
```

**Comment by Newcomer1989** [comment]
All other works fine?

It could be there are no user on your TeamSpeak server online at the moment you try to open the stats page?

**Comment by ShrewdSpirit** [comment]
There are 30 users in the ts server. The stats page wont open (It wont redirect to 404 either) it just opens a blank screen

**Comment by ShrewdSpirit** [comment]
When I try to start ranksystem with $php worker.php start it gives me this:
```
Starting the Ranksystem Bot.sh: 1: cannot create /www/ranksystem/logs/pid: Permission denied
sh: 1: cannot create ./logs/ranksystem.log: Permission denied
 [Failed]
```
They are owned by root

**Comment by Newcomer1989** [comment]
Ok, the problem seems to be, that you haven't run the ranksystem once.

You followed the instructions for installation?

**Comment by ShrewdSpirit** [comment]
Yes I've ran it before. It happened after the update

**Comment by Newcomer1989** [comment]
Please check the permissions of the folder avatars, icons, logs and the file other/dbconfig.php.
This should be set to chmod 777

**Comment by ShrewdSpirit** [comment]
Yes, they are all 777 and they are owned by the web user

**Comment by ShrewdSpirit** [comment]
The pid file is always owned by root. I've removed the file but still ranksystem gives me permission error about logs/pid file

**Comment by Newcomer1989** [comment]
Update to which version?

Read this how to start the Ranksystem https://github.com/Newcomer1989/TSN-Ranksystem/issues/24

**Comment by ShrewdSpirit** [comment]
From 1.0 to 1.0.1. Also I'm using the same way said in that issue but I get this error:
```
Starting the Ranksystem Bot.sh: 1: cannot create /www/ranksystem/logs/pid: Permission denied
 [Failed]
```
That pid file is created by root somehow (I think it's cronjob creating that file)

**Comment by Newcomer1989** [comment]
I think you didn't start it in the same way. You said, you started it with user root.
But you have to use your webuser to start it!
Again, please read the post here https://github.com/Newcomer1989/TSN-Ranksystem/issues/24

**Comment by ShrewdSpirit** [comment]
Oh! Right. The crontab was edited by root user. Now I can run $php worker.php start and it says "Starting the Ranksystem Bot. [OK]" but $php worker.php status says "The Ranksystem does not seem to run."

**Comment by Newcomer1989** [comment]
Then it could be, the Ranksystem directly closed after connecting.

Please check the logs/ranksystem.log for more information.

And also here (https://github.com/Newcomer1989/TSN-Ranksystem/issues/39) it becomes to and installation support... So this is closed for me and I will not answer anymore due I give no installation support!
