### ISSUE TITLE
Avatar download

### ISSUE THREAD

**Issue by VisMotrix** [Newcomer1989/TSN-Ranksystem#381]
Hey, i have an Musik bot wich changes his avatar to the cover of the album and the tsn Ranksystem allways download the new avatar.
Why dose tsn Ranksystem download the avatar ?
And can i disable the avatar download funktion?

**Comment by Shad86** [comment]
you can expand the "Avatar refresh time":

![avatar delay](https://user-images.githubusercontent.com/18570683/34642523-a331d3b6-f314-11e7-8c51-45b15efe5691.png)

The Avatar gets downloaded for the mystats site.
