### ISSUE TITLE
Error 111: Connection refused

### ISSUE THREAD

**Issue by Lizorg** [Newcomer1989/TSN-Ranksystem#382]
Hello,

There is no way I can get it to work. I always get stucked at this step.

> 2018-01-07 17:40:33.117269   ERROR     Error 111: Connection refused
> 2018-01-07 17:40:32.112068   INFO      Connect to TS3 Server (Address: "XX.XX.XX.XXXX" Voice-Port: "9987" Query-Port: "10011").
> 2018-01-07 17:40:32.112032   INFO      Loading addons [done]
> 2018-01-07 17:40:32.111988   INFO        Addon: 'assign_groups' [OFF]
> 2018-01-07 17:40:32.111731   INFO      Loading addons...
> 2018-01-07 17:40:32.111691   INFO        Ranksystem Version: 1.2.3
> 2018-01-07 17:40:32.111620   INFO        Check files permissions [done]
> 2018-01-07 17:40:32.108266   INFO        Check files permissions...
> 2018-01-07 17:40:32.107902   INFO        No newer version detected; Database check finished.
> 2018-01-07 17:40:32.107819   INFO      Check Ranksystem database for updates.
> 2018-01-07 17:40:32.103146   INFO      Initialize Bot...
* I've hidden TS3 server's IP address for security reasons.

OS: Linux
Added Ranksystem server's IP to the TS3 server's whitelist
Yeah, I've restarted the TS3 server many times. Including the Linux itself.

I don't know what am I doing wrong. :(

Many thanks in advance!

**Comment by Shad86** [comment]
seems you don't use the standart query port "10011" ask your Hoster which queryport your ts3-server use - or may check if your queryport is even open.

**Comment by Newcomer1989** [comment]
Is the TS3 server on the same machine like the Ranksystem?

If no, be sure, your server where the Ranksystem runs is able to get a connection to the server where the TS3 server is running.
Perhaps try to test it with a simple ping.

**Comment by Lizorg** [comment]
@Shad86 Has to be the 10011 query port since I also use the YaTQA program sometimes.

@Newcomer1989 Nope, for the Ranksystem I am using a web hosting (wich has cronjobs).

**Comment by Newcomer1989** [comment]
Then you have a problem to get a connection between the Webhost (Ranksystem) and your TS3 server.

**Comment by Newcomer1989** [comment]
You can ask your webhoster, if he allows TCP connections to external servers or he want to activate this for you.

If you hoster does not support this, you can ask us for a [free hosting](https://ts-n.net/ranksystem.php#support) of the Ranksystem.

**Comment by Lizorg** [comment]
@Newcomer1989 seems like. Because the YaTQA works completely fine. Okay, I will look into it!

**Comment by Newcomer1989** [comment]
solved with an free hosting
