### ISSUE TITLE
Icons erneut runterladen lassen

### ISSUE THREAD

**Issue by Yatheria1** [Newcomer1989/TSN-Ranksystem#386]
Wie kann ich die Icons erneut runter laden lassen ? da ich die alten aus dem tsicons ordner gelöscht habe.
Die IDs der Icons hat sich geändert daher wurden sie auch nicht mehr angezeigt.

**Comment by Shad86** [comment]
Dazu müsstest du einmal den groups table in der bei dir relevanten sql datenbank leeren NICHT löschen

**Comment by Newcomer1989** [comment]
Die IDs der Icons sind völlig unrelevant. Entscheidend sind die IDs der Gruppen.
Solange diese gleich bleiben kann es daran liegen, dass dein Browser die alten Icons noch gecached hat. Um den Cache zu bereinigen die Seite mit STRG + F5 neu laden.
Damit sollten die neuen Icons angezeigt werden, denn das Ranksystem lädt diese im Regelfall automatisch in den Ordner tsicons, sobald sie auf dem TS server geändert werden.

In deinem Fall bleibt aber nur noch ein delete in der groups Tabelle, da du manuell das Verzeichnis geleert hast:
`DELETE FROM groups;`

**Comment by Yatheria1** [comment]
Ok jetzt werden mir aber immernoch nicht die icons angezeigt.
Sondern nur diese  Standart Bildchen.

**Comment by Newcomer1989** [comment]
Eine nähere Beschreibung wäre hilfreich, damit man dir helfen kann.

**Comment by Shad86** [comment]
Da keine weitere Antwort mehr erfolgte, schließe ich das issue.

Wenn es weiterhin Fragen gibt erstelle einfach ein neues issue.
