### ISSUE TITLE
Prestige Levels

### ISSUE THREAD

**Issue by EGXZ** [Newcomer1989/TSN-Ranksystem#388]
Hey, I wanted to give a feature for the March version.

### Prestiges:

Let me explain, someone reach the level 100 and I heard that you are working on a kind of forever server group so when X reached the highest level, another ranksystem ? start to rank so like.. 0-100 beside the normal rank till the next prestige.

I don't know if you guys understand it sorry. I have some issues to explain this.

Sincerely,

**Comment by Newcomer1989** [comment]
Sorry, I didn't really understand it 100%.
I try to describe what I understood, please correct me, if it is wrong:

You describe normal Ranks/Level in your case from Level 0-100. At this point, sure that is still possible to do.
Then when an user reached level 100 he should get a prestige rank, like prestige 1. This group should stay permanent.
Then the Level begins again by level 0, till the user reaches again level 100, then he will got prestige 2.
Is it right?
What will happens in this case with prestige 1 group? This should be removed?

It I understood it right, it is still possible to do exactly what I have described with multiple Ranksystems. Let me explain:

**Ranksystem 1**
Handle the normal Level 0-100. After Level 100 you can also define multiple rounds to begin new with Level 0. You only need to increase the time for that. 

Example:
```
[..]
Level 99   after 47 days online time
Level 100  after 50 days online time
Level 0    after 51 days online time
Level 1    after 52 days online time
[..]
Level 100  after 100 days online time
Level 0    after 101 days online time
[..]
```

**Ranksystem 2**
Handle the prestige. The time to get the first group in this Ranksystem is that time, you would get Level 100 at the Ranksystem 1; for each step/round.

Example:
```
Prestige 1   after 50 days online time
Prestige 2   after 100 days online time
[..]
```

**Comment by EGXZ** [comment]
Yes, you understood it, correctly.

What will happens in this case with prestige 1 group? This should be removed?

=> Yeah it will be removed and get remplaced by prestige 2 group.

But the thing is I can't install system like that rn, cause people already start to leveling.

So there will be no sync between it.

**Comment by Newcomer1989** [comment]
That's true.. For the moment there is no other way.

There will come with one of the next updates a feature, what could help. The function to assign servergroups will be enlarged. Then it will be possible to set a needed time, before an user can set himself this group. That would also not be a automatically way, but possible.
The automatically way is also on our very long to do list as "multiple rankup definitions". So anytime it will come, I hope ;-)

Till that it would be possible, to install the second system like described and add manually the time to the user, they have already done in system 1 (webinterface - administrate - add online time to user). If you have not hundred or more user, this should be a possible task.

**Comment by EGXZ** [comment]
Well.. seem unlucky for me I have 90 users/daily, so yeah R.I.P. xd

**Comment by Newcomer1989** [comment]
double with #191
