### ISSUE TITLE
Not connecting to the TeamSpeak 3 server

### ISSUE THREAD

**Issue by hackerpedro** [Newcomer1989/TSN-Ranksystem#39]
Hi,

the page says "NOT CONNECTED TO TS3" and indeed it's not connected, but I double checked and the TeamSpeak 3 setting are OK, serveradmin, password, etc... What it could be?

**Comment by Newcomer1989** [comment]
That means YOU as user are not connected to the ts3 server.

That doesn't mean the query isn't connected to the ts3 server.

I will take this as suggestion and change the text to something like "You are not connected to the TS3".

**Comment by hackerpedro** [comment]
Wait, but i'am connected, the stats dont show up, nothing works, and says that the script is not connected to the server you can checkit if you want: http://www.panel.equalite.eu/ts3/rank/stats/index.php

**Comment by Newcomer1989** [comment]
Yes, the yellow message means, the script is not connected to the teamspeak.

You already filled out all informations inside the webinterface? If this values are true, the Ranksystem should connects automatically!

**Comment by hackerpedro** [comment]
I have other scripts running with the same username and password, and they run OK, so I assure you that all the data imputed is OK!

**Comment by Newcomer1989** [comment]
What message you got on starting the Ranksystem? Also check the log (logs/ranksystem.log).

**Comment by Newcomer1989** [comment]
Update to which version?

Read this how to start the Ranksystem https://github.com/Newcomer1989/TSN-Ranksystem/issues/24

**Comment by hackerpedro** [comment]
There is no file on .log, and how do i start Ranksystem? I jest uploaded the files to the webserver!

**Comment by Newcomer1989** [comment]
Please follow the instructions "Installation Linux"
http://ts-n.net/ranksystem.php

**Comment by hackerpedro** [comment]
Completely done, all the steps...

**Comment by Newcomer1989** [comment]
Then read this, how to start the Ranksystem https://github.com/Newcomer1989/TSN-Ranksystem/issues/24

**Comment by hackerpedro** [comment]
Is there any way to create a php script to use the check command with a cron job? and then assign a chron job to that script and then it would run the final worker.php check

**Comment by Newcomer1989** [comment]
What?? A script to run the "startscript" a cronjob? It would be redundant...
Please use for this the crontable like described on the installation guide!

Thats now a installation help and no bug report or anything else.. So this is closed for me and I will not answer anymore due I give no installation support!
