### ISSUE TITLE
Suspend sheduler on stopping the Bot

### ISSUE THREAD

**Issue by monster010** [Newcomer1989/TSN-Ranksystem#390]
Heyho Newcomer,

es wäre gut, wenn der Bot den Stop-Befehl bekommt, auch der Cronjob diesen nicht mehr starten würde.

LG

**Comment by Newcomer1989** [comment]
Wie soll der Bot denn erkennen, wie der Cronjob angelegt ist? Bzw. ob es denn überhaupt einen Cronjob gibt?
Unter Windows läuft das ganze eher als Task. Auch kann es unter verschiedenen Usern eingerichtet sein.
Geschweige denn, wenn jemand einen Daemon oder Dienst dafür einrichtet.
Und das sind nur Punkte, die mir spontan einfallen. Da wird sicherlich noch viel mehr hoch kommen.

Das wird meiner Meinung nach ein Fass ohne Boden. An das Thema würde ich daher nur sehr ungern gehen.

So ist eindeutig klar, der Bot macht derzeit nichts und es muss sich userseitig darum gekümmert werden.

Im übrigen machen das sogar nicht mal wirklich große Projekte. Um nur ein Beispiel zu nennen, bei Apache musst du auch separat neben den Startscript einstellen, wenn der Webserver mit Systemstart gestartet werden soll.

Ein Thema auf meiner Todo-Liste ist die Überarbeitung, dass der Prozess sich von alleine nicht mehr beendet. Dann wäre der Cronjob in der derzeitigen Form nicht mehr nötig, sondern nur noch wenn der Webserver neu gestartet wird oder das vollständige System.
Von der Prio ist das allerdings ein Punkt, der noch ziemlich weit entfernt liegt.

**Comment by monster010** [comment]
Leg in der Datenbank einen Boolean fest, wenn dieser Boolean auf true steht wurde der Bot gestoppt, dann soll der Cronjob nichts überprüfen, ist denke ich ohne Probleme möglich im Code hinzuzufügen.

**Comment by Newcomer1989** [comment]
Ok, in die Richtung hatte mich deine Ausgangsfrage nicht geleitet ;-)
Aber danke für den letzten Post bzw. Hinweis. Damit sollte es machbar sein.

Im worker.php check würde dann der Boolean beachtet und je nach Ausprägung wird der Bot nicht gestartet.
Im worker.php start würde der Boolean aber missachtet und der Bot würde gestartert bzw. vielmehr der Boolean damit dann auch wieder zurückgesetzt.

Habe ich das so richtig interpretiert?

**Comment by Newcomer1989** [comment]
Ok, das sollte eine Kleinigkeit sein. Wird mit entweder in der nächsten, spätestens aber in der darauffolgenden Version kommen.

**Comment by Newcomer1989** [comment]
done with version 1.2.4
