### ISSUE TITLE
Ranksystem error on update_groups.php if group name has emoji in it

### ISSUE THREAD

**Issue by bykidi** [Newcomer1989/TSN-Ranksystem#391]
![default](https://user-images.githubusercontent.com/1337953/35096755-6e4d6b76-fc5e-11e7-81de-771389eac7c0.png)

![default](https://user-images.githubusercontent.com/1337953/35096778-80d0911a-fc5e-11e7-84e5-d7916a9c5d20.png)

**Comment by bykidi** [comment]
👻

**Comment by Myszax** [comment]
Hello.
@Newcomer1989 if you working with TS3 strings remember they are encoded in UTF8MB4, not it UTF8. 
I'd recommend you to change string comparison method (in database structure) from utf8_general_ci to utf8mb4_general_ci for every TS3 String like client_nickname, server_group_name etc. For charset I suggest also add `charset=utf8mb4` to your PDO connection string. Should looks like `"mysql:host=localhost;dbname=db_name;charset=utf8mb4"`.
I don't think this will solve the problem, but should help you in the future :)

**Comment by Newcomer1989** [comment]
Has somehow gone past me. On that time I created this (in the middle of 2014) I couldn't find any official documentation how TeamSpeak encode his things. I am also sure, I tested nearly all special signs and all I could entered in TeamSpeak, was stored correctly by the Ranksystem.
Today it is still not documented inside the [query manual](http://media.teamspeak.com/ts3_literature/TeamSpeak%203%20Server%20Query%20Manual.pdf).
Interesting is, that it will now reported the first time^^

But sure, this should be changed and will be done with one of the next releases.

**Comment by Myszax** [comment]
Haha :P Just TS3 things xD Query Manual won't tell you everything.
I discovered many odd things by myself :P I'm working with ts3 query libs since 1 year :)
If you download ts3server and look into *sql* -> *create_mariadb* folder there will be file called `create_tables.sql`. Open it and you will find many lines `CHARACTER SET 'utf8mb4';`.
Thats how I found it.

**Comment by Newcomer1989** [comment]
Ok, I tested this 'TS3 thing'.. and it took it out of me.

TeamSpeak only supports 4 byte chars inside the group names, if I saw it right.
The server name, the client nickname and also chat messages with 4 byte chars are not possible.

I will change it with version 1.2.5 of the Ranksystem to support the 4 bytes inside the group names. I will not change all, cause the 4 bytes need more database space as the 3 bytes. Also it slows the system.
So all other fields will stay by default utf-8 (3 bytes).

I can only wonder was TeamSpeak was thinking in adding a 4 bytes support, but only for the group names... Either I would support it, then everywhere or I do not support it (IMHO the best way), but then nowhere ;-)

**Comment by Myszax** [comment]
> The server name, the client nickname and also chat messages with 4 byte chars are not possible.
  
Yep, you are right.
4 byte chars are possible in *Offline Messages* system. Also when server/channel group names is supported then logs are affected too
`2018-02-13 13:36:54.957690|INFO    |VirtualServer |1  |client (id:3) was added to servergroup 'Test💎'(id:231) by client 'Myszax'(id:2)`
Your system is not using Offline Messages or ts3 server logs, am I right? :p


> I can only wonder was TeamSpeak was thinking in adding a 4 bytes support, but only for the group names... 

I don't really know xD Maybe they plan to support rest in the future?
Char counter I mean byte counter counts fine, but 4 byte chars get shrank when I try to send.
![ts](https://user-images.githubusercontent.com/6831024/36150301-7fa72816-10c3-11e8-907a-ebe7fe915f08.png)

> Either I would support it, then everywhere or I do not support it (IMHO the best way), but then nowhere ;-)

Do as you wish. It's your project :)

**Comment by Newcomer1989** [comment]
> Do as you wish. It's your project :)
That meant not the Ranksystem. I meant TeamSpeak. Or have you an idea, why they allow it in group names, but not in nickname, channelname, servername.. ? ;-)

The Ranksystem will support it with the next version for groups. And TeamSpeak is not my project :-P

All other things the Ranksystem are using, are not affected. We checked that already.

**Comment by Myszax** [comment]
> That meant not the Ranksystem. I meant TeamSpeak.

Ah, you meant TS :p Sorry my bad, misunderstanding.
> Or have you an idea, why they allow it in group names, but not in nickname, channelname, servername.. ? ;-)

As I remember some time in the past (about 2-3 years ago) they had problems with some UTF-8 chars. They were crashing TS and people were using them to crash other users TS. When they patched it and everything seems nice, people found another chars that were crashing, then TS patched it again. This situation took place two or three times.
Maybe in the end they decide to not support 4 byte chars. I don't know if it was really 4 byte chars that were crashing TS. Just my deduction xD And maybe they forgot to block this in groups? Or it's just not invasive that much.
> And TeamSpeak is not my project :-P

Yes, yes I know :)
> The Ranksystem will support it with the next version for groups.

Fine :-)

**Comment by Newcomer1989** [comment]
Special characters in servergroups will be supported since 1.2.6.. should be solved.
