### ISSUE TITLE
Top users of the week and month not working properly

### ISSUE THREAD

**Issue by SimonHax** [Newcomer1989/TSN-Ranksystem#392]
The top users of the week and month just show all 0 hours. But the all time top is working correctly. Total online time is however working correctly. This is my ranksystem site: http://waza.tk/rank/stats/top_week.php

Im using the newest versions of Apache, php and MySQL. And its all running on linux

What could be the problem here?

**Comment by Newcomer1989** [comment]
There is no really problem.

The thing is, you are running the Ranksystem less then 1 month. You can see that also on the index page on the top right corner. For the month there are not enough data collected yet.
Wait to get the first month full and then the top week and also the top month pages should be working fine.

**Comment by SimonHax** [comment]
Thanks! I assumed that after a week the top week would work. But I'm just inpatient. Keep up the work!
