### ISSUE TITLE
You are not connected to the server

### ISSUE THREAD

**Issue by PassiCode** [Newcomer1989/TSN-Ranksystem#395]
Hello, I recently installed the Rank system on our Linux root server. Everything worked perfectly, but after a root server restart, the website always say: "You are not connected to the server".
What can I do?

**Comment by bykidi** [comment]
put phpinfo.php in your site folder, open it with your browser, make sure that REMOTE_ADDR is your actual IP address and it match with your IP on TS server

**Comment by PassiCode** [comment]
Where i find the php info file?

**Comment by Shad86** [comment]
At first make sure the ranksystem is running

If it run and it wont change:

clear your session one time

![sess](https://user-images.githubusercontent.com/18570683/35875143-acc4837a-0b6e-11e8-8d8d-adcff1f7d0d9.png)

If that wont help, check your logfile in your ranksystem webinterface

**Comment by PassiCode** [comment]
1. the ranking system is online 2. I tried it, but it did not help either. 3. nothing was found in the logs

**Comment by PassiCode** [comment]
> Also Be sure your connect on both "tools" with the same ip 

How should I check that

**Comment by PassiCode** [comment]
Ok apparently I'm really connected to another IP as I'm on the site. But how can I fix it. Does the ts3 run on ipv6?

**Comment by Shad86** [comment]
Yes the TS3 Server supports ipv6 and 4, so you could force ts3 to use ipv4 or 6 only.

Old thread on teamspeak forum: https://forum.teamspeak.com/threads/127160-Force-Teamspeak3-to-use-ipv4-only

**Comment by PassiCode** [comment]
but why is it suddenly so?

**Comment by PassiCode** [comment]
But is it really?
 All other users on the server have synonymous the problem.

**Comment by Shad86** [comment]
Hm, well i don't know but it seems something changed after you restarted the Server.

**Comment by PassiCode** [comment]
in which file should I adjust the ip settings of the teamspeak?

**Comment by Shad86** [comment]
if it exists, in your ts3server.ini should be in the main ts3-server folder - if it got generated

**Comment by PassiCode** [comment]
I've looked again now. The ip4 address on the website is the same as on the ts.

**Comment by PassiCode** [comment]
So it has to be something else ...

**Comment by Shad86** [comment]
Well, the bot say's you're not connected.

4 cases are possible:

1.you're not on the ts3

2.the bot itself can't see you

3.the bot isn't connected (but in this case there would be a other message like "the ranksystem seems to be offline and the data are old")

4.Ipv4 / ip6 issue (but this one you already fixed)

**Comment by bykidi** [comment]
disable the bot delay option during the tests

**Comment by PassiCode** [comment]
I tryed it, but it still not working

**Comment by Shad86** [comment]
you can try it, but i think the behavior would be the same after it, as you said it worked before you restarted your root, so there has to be changed something after you restarted your root.

you can also send me your ranksystem website privately @ rank@hdf-multigaming.de - i will take a look over it tomorrow, as i have to go to sleep now

**Comment by Newcomer1989** [comment]
1) How looks your "voice_ip=" inside your ts3server.ini?

2) What are you getting on the linux comand "ifconfig"?

3) What webserver are you using? If apache, how looks your "httpd.conf"?

4) Have you firewall or a special routing on your machine, like iptables?

**Comment by PassiCode** [comment]
i didn't creat ts3server.ini

**Comment by PassiCode** [comment]
2. Command not found

**Comment by PassiCode** [comment]
3. I only found a apach2.conf file ``# This is the main Apache server configuration file.  It contains the
# configuration directives that give the server its instructions.
# See http://httpd.apache.org/docs/2.4/ for detailed information about
# the directives and /usr/share/doc/apache2/README.Debian about Debian specific
# hints.
#
#
# Summary of how the Apache 2 configuration works in Debian:
# The Apache 2 web server configuration in Debian is quite different to
# upstream's suggested way to configure the web server. This is because Debian's
# default Apache2 installation attempts to make adding and removing modules,
# virtual hosts, and extra configuration directives as flexible as possible, in
# order to make automating the changes and administering the server as easy as
# possible.

# It is split into several files forming the configuration hierarchy outlined
# below, all located in the /etc/apache2/ directory:
#
#	/etc/apache2/
#	|-- apache2.conf
#	|	`--  ports.conf
#	|-- mods-enabled
#	|	|-- *.load
#	|	`-- *.conf
#	|-- conf-enabled
#	|	`-- *.conf
# 	`-- sites-enabled
#	 	`-- *.conf
#
#
# * apache2.conf is the main configuration file (this file). It puts the pieces
#   together by including all remaining configuration files when starting up the
#   web server.
#
# * ports.conf is always included from the main configuration file. It is
#   supposed to determine listening ports for incoming connections which can be
#   customized anytime.
#
# * Configuration files in the mods-enabled/, conf-enabled/ and sites-enabled/
#   directories contain particular configuration snippets which manage modules,
#   global configuration fragments, or virtual host configurations,
#   respectively.
#
#   They are activated by symlinking available configuration files from their
#   respective *-available/ counterparts. These should be managed by using our
#   helpers a2enmod/a2dismod, a2ensite/a2dissite and a2enconf/a2disconf. See
#   their respective man pages for detailed information.
#
# * The binary is called apache2. Due to the use of environment variables, in
#   the default configuration, apache2 needs to be started/stopped with
#   /etc/init.d/apache2 or apache2ctl. Calling /usr/bin/apache2 directly will not
#   work with the default configuration.


# Global configuration
#

#
# ServerRoot: The top of the directory tree under which the server's
# configuration, error, and log files are kept.
#
# NOTE!  If you intend to place this on an NFS (or otherwise network)
# mounted filesystem then please read the Mutex documentation (available
# at <URL:http://httpd.apache.org/docs/2.4/mod/core.html#mutex>);
# you will save yourself a lot of trouble.
#
# Do NOT add a slash at the end of the directory path.
#
#ServerRoot "/etc/apache2"

#
# The accept serialization lock file MUST BE STORED ON A LOCAL DISK.
#
#Mutex file:${APACHE_LOCK_DIR} default

#
# The directory where shm and other runtime files will be stored.
#

DefaultRuntimeDir ${APACHE_RUN_DIR}

#
# PidFile: The file in which the server should record its process
# identification number when it starts.
# This needs to be set in /etc/apache2/envvars
#
PidFile ${APACHE_PID_FILE}

#
# Timeout: The number of seconds before receives and sends time out.
#
Timeout 300

#
# KeepAlive: Whether or not to allow persistent connections (more than
# one request per connection). Set to "Off" to deactivate.
#
KeepAlive On

#
# MaxKeepAliveRequests: The maximum number of requests to allow
# during a persistent connection. Set to 0 to allow an unlimited amount.
# We recommend you leave this number high, for maximum performance.
#
MaxKeepAliveRequests 100

#
# KeepAliveTimeout: Number of seconds to wait for the next request from the
# same client on the same connection.
#
KeepAliveTimeout 5


# These need to be set in /etc/apache2/envvars
User ${APACHE_RUN_USER}
Group ${APACHE_RUN_GROUP}

#
# HostnameLookups: Log the names of clients or just their IP addresses
# e.g., www.apache.org (on) or 204.62.129.132 (off).
# The default is off because it'd be overall better for the net if people
# had to knowingly turn this feature on, since enabling it means that
# each client request will result in AT LEAST one lookup request to the
# nameserver.
#
HostnameLookups Off

# ErrorLog: The location of the error log file.
# If you do not specify an ErrorLog directive within a <VirtualHost>
# container, error messages relating to that virtual host will be
# logged here.  If you *do* define an error logfile for a <VirtualHost>
# container, that host's errors will be logged there and not here.
#
ErrorLog ${APACHE_LOG_DIR}/error.log

#
# LogLevel: Control the severity of messages logged to the error_log.
# Available values: trace8, ..., trace1, debug, info, notice, warn,
# error, crit, alert, emerg.
# It is also possible to configure the log level for particular modules, e.g.
# "LogLevel info ssl:warn"
#
LogLevel warn

# Include module configuration:
IncludeOptional mods-enabled/*.load
IncludeOptional mods-enabled/*.conf

# Include list of ports to listen on
Include ports.conf


# Sets the default security model of the Apache2 HTTPD server. It does
# not allow access to the root filesystem outside of /usr/share and /var/www.
# The former is used by web applications packaged in Debian,
# the latter may be used for local directories served by the web server. If
# your system is serving content from a sub-directory in /srv you must allow
# access here, or in any related virtual host.
<Directory />
	Options FollowSymLinks
	AllowOverride None
	Require all denied
</Directory>

<Directory /usr/share>
	AllowOverride None
	Require all granted
</Directory>

<Directory /var/www/>
	Options Indexes FollowSymLinks
	AllowOverride None
	Require all granted
</Directory>

#<Directory /srv/>
#	Options Indexes FollowSymLinks
#	AllowOverride None
#	Require all granted
#</Directory>




# AccessFileName: The name of the file to look for in each directory
# for additional configuration directives.  See also the AllowOverride
# directive.
#
AccessFileName .htaccess

#
# The following lines prevent .htaccess and .htpasswd files from being
# viewed by Web clients.
#
<FilesMatch "^\.ht">
	Require all denied
</FilesMatch>


#
# The following directives define some format nicknames for use with
# a CustomLog directive.
#
# These deviate from the Common Log Format definitions in that they use %O
# (the actual bytes sent including headers) instead of %b (the size of the
# requested file), because the latter makes it impossible to detect partial
# requests.
#
# Note that the use of %{X-Forwarded-For}i instead of %h is not recommended.
# Use mod_remoteip instead.
#
LogFormat "%v:%p %h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" vhost_combined
LogFormat "%h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" combined
LogFormat "%h %l %u %t \"%r\" %>s %O" common
LogFormat "%{Referer}i -> %U" referer
LogFormat "%{User-agent}i" agent

# Include of directories ignores editors' and dpkg's backup files,
# see README.Debian for details.

# Include generic snippets of statements
IncludeOptional conf-enabled/*.conf

# Include the virtual host configurations:
IncludeOptional sites-enabled/*.conf

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet

**Comment by Newcomer1989** [comment]
Which linux do you have?

**Comment by PassiCode** [comment]
1) I will TRY
2) Debian

**Comment by Newcomer1989** [comment]
2. you can install ifconfig with `apt-get install net-tools` or you use the command `ip address` and share us this result.

**Comment by PassiCode** [comment]
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 37.114.45.###  netmask 255.255.254.0  broadcast 37.114.45.###
        inet6 fe80::####:4ff:fee4:7dca  prefixlen 64  scopeid 0x20<link>
        ether 4e:65:04:e4:7d:ca  txqueuelen 1000  (Ethernet)
        RX packets 52598353  bytes 9839955874 (9.1 GiB)
        RX errors 0  dropped 89668  overruns 0  frame 0
        TX packets 58984206  bytes 8431539841 (7.8 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1  (Lokale Schleife)
        RX packets 22156649  bytes 9378218961 (8.7 GiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 22156649  bytes 9378218961 (8.7 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Comment by Newcomer1989** [comment]
No problem. That tells us, you are using IPv4 and IPv6 on your machine at the same time.

So you should have a look, what protocol the user should use. Perhaps force IPv4 for the ts3server and also for the webserver and you should be fine.

**Comment by Newcomer1989** [comment]
Should be solved with version 1.2.4. 

+ added new verification step, when the users IP between website and TS3 server differs; at this point the user can register himself also with a token; to protect from spams the user need to join a verification channel, where he will be able to choose himself to be able to receive the token
