### ISSUE TITLE
Error PHP SAM

### ISSUE THREAD

**Issue by EscuderoKevin** [Newcomer1989/TSN-Ranksystem#396]
Hi i used httpd in centos 6.

CRITICAL  PHP SAM is missed. Installation of PHP SAM is required! Shutting down!

how to install ? i try google but nothing

**Comment by Newcomer1989** [comment]
Can you please share me a link of your Ranksystem?

If you do not want to make it public, send it to the mail address: admin@ts-n.net

**Comment by EscuderoKevin** [comment]
http://190.112.0.116:81/ranking/

**Comment by Newcomer1989** [comment]
can you enable the site navigation for the moment please?

**Comment by Newcomer1989** [comment]
You can activate this inside the webinterface -> stats page -> show site-navigation

**Comment by EscuderoKevin** [comment]
Ready

**Comment by Newcomer1989** [comment]
Did you changed anything on the Ranksystem files and/or database?

**Comment by EscuderoKevin** [comment]
No , yesterday Working , now when i try look dont work.

**Comment by Newcomer1989** [comment]
I never seen this error before.
I am sure there is something wrong with the source code.

Please download the original sources and overwrite it on your machine.
https://ts-n.net/downloads/ranksystem_1.2.4.zip

Take note, that you do not overwrite the other/dbconfig.php and the other/phpcommand.php.
Also you should not upload the install.php on your webspace.
So exclude this 3 files from uploading.

**Comment by EscuderoKevin** [comment]
i do that and i have SAME error , i think its Module About PHP. 
i dont use Webspace i mount on same PC with TS3

**Comment by EscuderoKevin** [comment]
I restart Virtual Machine and now its Works ! Thanks mate. Good Ranking :$

Where i can do Translate to SPANISH for u ?

**Comment by EscuderoKevin** [comment]
No , not work hahaha .

https://www.escuderokevin.net/capturas/EscuderoKevin.net-1518432054-7c0e097a-36d4-4afa-855f-4bfeddb6e762.png

**Comment by Newcomer1989** [comment]
Did you now replaced the Ranksystem sources, like described?

**Comment by Newcomer1989** [comment]
For the translation you could take the language/core_en.php file, translate this and send me this after.
I would add it to the next release.

**Comment by EscuderoKevin** [comment]
Yep. y remove in new files dbconfigs.php , phpcommand.php and install.php.

**Comment by Newcomer1989** [comment]
Hmm, can you join our public ts3 server (ts-n.net), would be easier to analyze the problem ;-)

**Comment by Newcomer1989** [comment]
Solved the problem via remote session.

The file permissions for the Ranksystem were wrong set

**Comment by bykidi** [comment]
Can you please tell what exactly?
Same stuff happened on my machine, ubuntu 16.04.3 lts x64
Using PHP 7.2.1

**Comment by Newcomer1989** [comment]
This solves the problem
https://github.com/Newcomer1989/TSN-Ranksystem/issues/396#issuecomment-364882923

**Comment by bykidi** [comment]
SGFM.
I will check within few hours (when i get home) plus will try to translate to russian

**Comment by maxlxl** [comment]
For me just a restart of apache2 and after that the start of the bot via the webinterface solved the problem.
