### ISSUE TITLE
Ability to set custom TS3 server IP for stats page [Suggestion]

### ISSUE THREAD

**Issue by bykidi** [Newcomer1989/TSN-Ranksystem#397]
Why? Because i host my ranksystem instance on subdomain and my server is hosted on main domain.

Also thank you for an 1.2.4 update, i'm getting 2-3x reduced cpu load times compared to 1.2.3 (even without delays)

**Comment by Newcomer1989** [comment]
Why you not not enter the main domain inside the ts3 host address?

**Comment by bykidi** [comment]
The address i use is 'domainname.com'
TS3 is hosted on 'domainname.com'
But ranksystem is hosted on 'subdomain.domainname.com'
=>
Hostname is shown as 'subdomain.domainname.com:9987' on ranksystem server stats page.

**Comment by Newcomer1989** [comment]
When your TS3 server is hosted on 'domainname.com' insert this inside the TS3 server address instead of the ip address.
Then on the ranksystem page will be shown as TS3 address the 'domainname.com:9987'. This is what you want, right?

**Comment by bykidi** [comment]
Yes, but i use 127.0.0.1 as an address

**Comment by Newcomer1989** [comment]
Tip: Set your domain name on your machine as local -> 127.0.0.1

https://en.wikipedia.org/wiki/Hosts_(file)

Then your server will root the traffic inside and not via your external LAN.
