### ISSUE TITLE
Online Zeit wird genommen statt die Aktive Zeit

### ISSUE THREAD

**Issue by GambarojaLP** [Newcomer1989/TSN-Ranksystem#4]
Hey ;)
Ich hab folgendes Problem mit dem Ranksystem, und zwar wird die Idle Time hergenommen statt 
der Aktiven Zeit. 

PHP ist auf neuester Version
MySQL wäre dass einzigste Problem, läuft auf einer free datenbank
Worker VBS wird alle 5 Minuten auf dem V-Server Ausgeführt

Ich weiss nicht wirklich woran dass Liegen könnte bis auf dass mit der MySQL Datenbank...
Ja ich hab auch den Regler aktiviert bei Idle Time dass die abgezogen wird. 
Ich hoffe du könntest mich eventuell mal im Teamspeak besuchen (GambarojaLP)
IP: ts.gamer-verein.de

Danke! :100:

**Comment by Newcomer1989** [comment]
Mit der Aussage, kann ich leider gar nichts anfangen.

> Ich hab folgendes Problem mit dem Ranksystem, und zwar wird die Idle Time hergenommen statt
der Aktiven Zeit.

Damit ich dir helfen kann, bitte näher beschreiben, was genau das Problem ist. Welche Zeit wird auf der worker.php bzw. der list_rankup.php angezeigt? Ein Beispiel an einer Person könnte hier helfen. Und welche Zeit sollte deiner Meinung nach andernfalls dort erscheinen? Wie lange war die Beispiel-Person reell auf dem TeamSpeak online und wie lange davon inaktiv?
Bitte auch die relevanten Konfigurationen posten. Die Idletime ist an, das ist ok; wie sieht denn bei dir die Config zum "rank up" aus?

Für eine nähere Erläuterung, was das Ranksystem wertet kann per Mouse-Over die Beschreibung der Idletime im Webinterface herangezogen werden. Dort sind beide Varianten beschrieben.

**Comment by GambarojaLP** [comment]
Kannst du mich eventuell mal auf Steam adden oder auf den Teamspeak kommen?
Über GitHub dauert dass Ganze einfach Jahre ;D

Steam: http://www.steamcommunity.com/id/GambarojaLP
Ts³: 83.169.13.15 (GambarojaLP)

LG

**Comment by GambarojaLP** [comment]
Wurde Geklärt! Danke nochmal an dich! Bist ein Netter Typ ;)
