### ISSUE TITLE
Change boosted user to mode 'online time' if general 'Idletime' is activated

### ISSUE THREAD

**Issue by Shad86** [Newcomer1989/TSN-Ranksystem#40]
Hello,

(Version 1.0.1)

**English:**

we had a talk about some suggestions and i said i will test again the boost thingy, because i thought the boost isnt working with enabled idletime.

http://puu.sh/oW9fk/453b2c8358.png (Online time gets boosted active time not)

i set the "Boosting-Server Group" -> http://puu.sh/oW9il/0eca17cd75.png

if i boost over the selective client thingy it works without any issue only on the Servergroup-boost it doesnt boost the active time.

regards :)

**German:**

Wir hatten ja ein Gespräch über ein paar features gehabt und dabei ist mir ja aufgefallen (war mir aber da nicht sicher) dass das boosten mit aktivierte idlezeit nicht geht und das ich das sobald ich zeit habe nochmal teste.

Über die Boostfunktion per Servergruppe (http://puu.sh/oW9il/0eca17cd75.png) funktioniert es bei mir nun also tatsächlich nicht.

http://puu.sh/oW9fk/453b2c8358.png (Online Zeit wird geboosted / Aktive Zeit nicht)

Wenn ich die Zeit über -> "Clients editieren (Selektiv)" "gutschreibe" funktioniert es aber einwandfrei

Grüße :)

**Comment by Newcomer1989** [comment]
Ok, thx for the report.

I will have a look on this after the next release 1.0.2 gets published. I'll hope I can release it the next 1-2 weeks..

**Comment by Newcomer1989** [comment]
You checked the person on your screen (http://puu.sh/oW9fk/453b2c8358.png) doesn't idle at this moment?

Cause it should all be boosted, the online time and when he idle also the idle time. So it could be correct!

Make sure the person, which have the boost, doesn't idle at this time. Then it should get concerned as active time.

**Comment by Shad86** [comment]
Hm...

So as a suggestion the bosst group should boost the really relevant "times" then (Online Time and active time) because for that i think should be the "boost" thing.

Because these 2 times are really relevant for the next rank up's and for only that the boost thing usually gets used in my opinion.

I think that makes it a loot more easier if someone wants to boost someone. 
Especially you dont have to explain every person you boost, that he/she now have to speak continuously, because he/she gets boosted. (For example i have a boost that is finished after 3 min.)
So if i stop talking for 1 or 2 min. i didnt get the rank up because i "idled" to long.

**Comment by Newcomer1989** [comment]
Thats what you want is no boost.

What you described is a already implement with the function to edit clients. You find this inside the webinterface. There you can set a special time to an user. For example give them the needed 3000 second to get level 2.


But I will think about it, to add a new switch to change the boost to your described way.

**Comment by Shad86** [comment]
Yeah i thought that would be better to have an option like that because then i dont have to login all the time if i have to or want to boost someone, so i can stay on the ts3-server and just can give him a group.

thanks

Shad86

**Comment by Shad86** [comment]
Or you make checkboxes behind the boost thing (Idletime / Online Time / Active Time), so that everyone can decide what time normally should be boosted

**Comment by Newcomer1989** [comment]
Thats what I mean.

A function as a switch to turn idletime or online time on escpecially for the boost function. And this function overmodulate the function above which is called "Idletime".

To select for a rank the idle time himself makes no sense for me. So it will be 2 values, not 3.

**Comment by Newcomer1989** [comment]
Never heard any more about this request. Is that still needed or can we close it?

**Comment by Shad86** [comment]
Depends on if the boost still boost also idle time, then yes would be great to have this feature
