### ISSUE TITLE
"PHP SAM fehlt" // "Servergruppe wurde gelöscht"

### ISSUE THREAD

**Issue by TricityGaming** [Newcomer1989/TSN-Ranksystem#402]
Seit heute kommt es nach dem Start des RankSystems zu Fehlern. Ich musste aus Crash Gründen den TeamSpeak neuaufsetzen, dabei haben sich manche Gruppen IDs verschoben.  Die Gruppen IDs habe ich wieder richtig im RankSystem eingetragen, es meint aber immer noch das diese Gruppen nicht exestieren.
Zu dem startet der Bit nicht "PHP SAM is missed. Installation of PHP SAM is required! Shutting down!". Zu PHP SAM habe ich nur eine Seite auf php.net gefunden laut der Installationanleitung scheint es aber bei mir installiert zu sein.

OS: Debian 8
(Vorher hat es einwandfrei funktioniert)
![fehler in log](https://user-images.githubusercontent.com/36425229/36123738-e95b87f0-104d-11e8-8095-f32228d31f8a.PNG)
![phpsam](https://user-images.githubusercontent.com/36425229/36123739-e97bafb2-104d-11e8-8866-226281d6eeaf.PNG)

**Comment by Shad86** [comment]
Bitte lade nochmals dieses release herunter -> https://ts-n.net/downloads/ranksystem_1.2.4.zip und ersetze die webspacesachen.

Danach sollte das php sam Problem gelöst sein.

Zu den Gruppen Meldungen:

Du hast Gruppen angegeben die so nicht existieren, deshalb wirst du darauf hingewiesen.
Im comment https://github.com/Newcomer1989/TSN-Ranksystem/issues/398#issuecomment-364884842 wird auch erklärt wie man es beheben kann.

MfG

Shad86

**Comment by TricityGaming** [comment]
Werde ich alles testen. Nur die Gruppen sind halt da, aber da kann es auch durch den Yatqa Snapshot Probleme geben. Danke schon mal.

**Comment by TricityGaming** [comment]
So habe alles durchgeführt, das Problem mit den Gruppen Meldungen hat sich durch das Update auch erledigt. Funktioniert alles wie gewünscht. Danke für die Hilfe!
