### ISSUE TITLE
Database Connection failed:  No such file or directory

### ISSUE THREAD

**Issue by EscuderoKevin** [Newcomer1989/TSN-Ranksystem#403]
Database Connection failed: SQLSTATE[HY000] [2002] No such file or directory

**Comment by EscuderoKevin** [comment]
When i try start with php worker.php check

**Comment by EscuderoKevin** [comment]
https://www.escuderokevin.net/capturas/EscuderoKevin.net-1518480825-8c927425-4281-4253-a509-5b4076039b63.png

**Comment by EscuderoKevin** [comment]
https://www.escuderokevin.net/capturas/EscuderoKevin.net-1518499787-3837ed8b-ba68-4a57-b274-c261160bd873.png

**Comment by Shad86** [comment]
and you 100% sure apache is your webuser? its really uncommon that "apache" is a webuser usually the standart webuser is www-data

**Comment by Newcomer1989** [comment]
I guess you are talking about an existing Ranksystem instance, which were already running and working before, right?

Then have a look to the other/dbconfig.php. Are the connection details inside correct?

Are you sure, the database, which is called inside the other/dbconfig.php, is online and reachable?

**Comment by EscuderoKevin** [comment]
Yep all its ok.

**Comment by EscuderoKevin** [comment]
@Newcomer1989 you do Yesterday , you join my TeamWiever u remember ? i restart Machine and dont work.

**Comment by Newcomer1989** [comment]
Sorry, there were the last days to much requests, that I can remember each error/problem exactly.

Help me to remember, what we did together via teamviewer session?

**Comment by EscuderoKevin** [comment]
Are u in TS3 for show u via Teamwiever again ?

**Comment by Newcomer1989** [comment]
At the moment not. I am busy this days. Please describe it here. Then I can have an eye on it between or perhaps also others are able to help you.

**Comment by EscuderoKevin** [comment]
Only when i try start worker.php with root or sudo or other ACC

Database Connection failed: SQLSTATE[HY000] [2002] No such file or directory

SQL its working and all configs its OK:

**Comment by Newcomer1989** [comment]
Should be a wrong configured PHP.

Have a look here -> https://stackoverflow.com/questions/29695450/pdoexception-sqlstatehy000-2002-no-such-file-or-directory

> Quick test (run in shell):
> `php -r "new PDO('mysql:hostname=localhost;dbname=test', 'username', 'password');"`
> 
> QLSTATE[HY000] [2002] No such file or directory means php cannot find the mysql.default_socket file. Fix it by modifying php.ini file. On Mac it is mysql.default_socket = /tmp/mysql.sock (See PHP - MySQL connection not working: 2002 No such file or directory)

**Comment by EscuderoKevin** [comment]
Thx, Fixed ♥
