### ISSUE TITLE
Top User des Monats - nicht genügend Daten

### ISSUE THREAD

**Issue by Shadowoli** [Newcomer1989/TSN-Ranksystem#405]
Hallo,
seit dem neuen update (1.2.4) funktioniert bei mir die Top user des Monats Liste nicht mehr.
Top User der Woche/aller Zeiten funktioniert wie gehabt nur seit dem neuen Update eben zeigt es bei der Monats-Liste "nicht genügend Daten ..." an.
Woran könnte das liegen?
Falls ihr es euch selbst anschauen wollt --> https://shadowlp.hopto.org/rank/stats/top_month.php
Danke schonmal im voraus :) 👍

**Comment by Shadowoli** [comment]
Vielleicht sollte man noch dazu sagen dasd das System schon seit mindestens anderthalb Jahren läuft es also definitiv genug Daten haben sollte.
(Es hat vor dem Update funktioniert)

**Comment by Shadowoli** [comment]
Und vielleicht das ich zu dumm war einen Titel zu schreiben...... ignoriert den Titel es geht um Top User des Monats nicht der Woche 🤦🏻‍♂️

**Comment by Newcomer1989** [comment]
Wie sah denn vor dem Update der Wert bei "Online Zeit aller User / Monat" auf der stats/index.php aus? Derzeit steht dort auch nicht genügend Daten. Folglich wäre es korrekt die Top-User auszublenden.

Fraglich ist natürlich, warum nicht genügend Daten in der DB vorhanden sind. Das muss ich mir demnächst anschauen. Mit der aktuellen Version werden die Daten noch einmal etwas "schärfer" bereinigt. Evtl. wird etwas zu viel gelöscht. Das könnte dann mit der längeren Ausfallzeit bei dir zu tun haben, die man im "server usage" Graph sieht.

**Comment by Shadowoli** [comment]
Also vor dem Update standen auf Stats/Index.php ganz normal werte was genau kann ich nicht sagen

Der Ausfall im Servergraf ist darauf zurückzuführen, das nach dem Update die php Sam Extension auf meinem Server gefehlt hat und ich diese erst nach einigen Stunden installiert habe des wegen war der Vlt für einige Zeit inaktiv.

**Comment by Newcomer1989** [comment]
> Was vielleicht auch wichtig zu wissen ist: In der "Meine Statistiken" Seite steht bei "Online Zeit der letzten 30 Tage" ein Wert ( bei mir "6 days, 20 hours, 33 mins, 46 secs")

Das kann ja durchaus korrekt sein oder was möchtest du uns hiermit sagen?

**Comment by Shadowoli** [comment]
Eigentlich wollte ich damir sagen das das Rankingsystem durchaus Daten über die letzen 30 Tage abgespeichert hat somit (so glaube ich zumindest)
>Mit der aktuellen Version werden die Daten noch einmal etwas "schärfer" bereinigt. Evtl. wird etwas zu >viel gelöscht
das, nicht die Fehlerursache sein kann.
Kann aber auch sein dass das kompletter Müll ist was ich hier schreibe xD

**Comment by IMmmKI** [comment]
Heey

I have the same issue here with the top user of the month page. 

This was working 100% before the update. 

Thanks,

**Comment by Newcomer1989** [comment]
Kannst du diesen SQL Befehl auf deiner Datenbank absetzen und uns das Ergebnis teilen?

`select count(distinct(timestamp)) from user_snapshot;`

**Comment by IMmmKI** [comment]
Here we go: 

![image](https://user-images.githubusercontent.com/11090621/36324475-4359430c-135d-11e8-9577-3771bfbb3e5a.png)

**Comment by Newcomer1989** [comment]
Ok, that is the reason, why you are not able to see the top user of month.

The count need to give a value with 120 or above out, that this stats will be shown.

The actual SQL in release 1.2.4 will only delete entries above 121:
`DELETE a FROM $dbname.user_snapshot AS a CROSS JOIN(SELECT DISTINCT(timestamp) FROM $dbname.user_snapshot ORDER BY timestamp DESC LIMIT 1000 OFFSET 121) AS b WHERE a.timestamp=b.timestamp;`

Please run the SELECT statement (SQL) multiple times, nearly every 6 hours (the data for this table will be collected each 6 hours)... Have a look for, if the result is increasing.
When it is increasing, the problem were before 1.2.4 and you need to wait till enough data are build/stored to get the top month page back.

The problem of version 1.2.3 and before was, that this page were always show. If there are not enough values, the shown results were wrong. This was fixed and seems to be working fine.

Please inform us, what you get as result on your selects.

**Comment by Shadowoli** [comment]
Ich hab das hier:
>select count(distinct(timestamp)) from user_snapshot;

jetzt über ein paar Tage verteilt ausgeführt und der Output war IMMER: 117

**Comment by Newcomer1989** [comment]
Vielen Dank für die Rückmeldung. Habe gesehen, da hat sich noch der alte Delete Befehl versteckt, der da so nicht mehr hingehört.
Wird mit der Version 1.2.5 bereinigt. Wird dann ein paar Tage dauern, bis sich die Werte wieder aufbauen. Nach spätestens einer Woche sollte dann aber fast in allen Fällen die Monatsstats wieder angezeigt werden.

**Comment by Shadowoli** [comment]
Alles klar danke für die schnelle Hilfe :)

**Comment by Newcomer1989** [comment]
Wurde mit Version 1.2.5 behoben
