### ISSUE TITLE
"Next rankup" Bug?

### ISSUE THREAD

**Issue by capsload** [Newcomer1989/TSN-Ranksystem#407]
https://ts-n.net/ranksystem_dev/stats/list_rankup.php?sort=nextup&order=desc&seite=1&user=25&search=

Plötzlich brauchen User unheimlich viel Idle-Zeit um in das nächste level zu kommen. (Sogar euere Seite ist affected.)

Fix?

**Comment by Shad86** [comment]
Hallo,

als erstes denke ich mal das du eher Online Zeit oder Aktive Zeit meinst (mit idle-zeit bekommt man ja kein nächstes rank up) :)

Ja es ist soweit richtig das auf der Seite hohe Werte angezeigt werden, allerdings sollte nach einem connect des users, sobald das ranksystem den Nutzer gesehen und erfasst hat, sich die Zeit wieder auf den ursprünglichen Wert korrigieren.

Warum das derzeit so ist, wird bereits untersucht.

**Comment by Newcomer1989** [comment]
Will be fixed with version 1.2.5

**Comment by Newcomer1989** [comment]
Was already fixed with version 1.2.5
