### ISSUE TITLE
Error Webinterface saving Settings /  Unkown column 'registercid'

### ISSUE THREAD

**Issue by Shad86** [Newcomer1989/TSN-Ranksystem#408]
@IMmmKI put you post here
> Hi There, 
> 
> I hope you guys are well? 
> 
> I am not too sure what the issue is but let me explain and I will supply all the resources.
> 
> When I try and start the bot after the auto updated this morning, I get the following errors. 
> 
> ![image](https://user-images.githubusercontent.com/11090621/36092111-e077d3b4-0fee-11e8-85cf-71c4da5903c6.png)
> 
> So then I go to the core and try and change the rank up definition parm. When I change the ID of the server groups. I get this error. 
> 
> ![image](https://user-images.githubusercontent.com/11090621/36092172-17f672fa-0fef-11e8-9394-bea04a572f53.png)
> 
> Now I noticed if I enter a server ID of a group that I don't have, I get this error about the DB. 
> 
> ![image](https://user-images.githubusercontent.com/11090621/36092208-3c2f6dc0-0fef-11e8-91a0-594930dad3df.png)
> 
> But I also noticed that it says update available but the bot has updated itself. I can see so from the log layout and the log. 
> 
> ![image](https://user-images.githubusercontent.com/11090621/36092238-55def2b8-0fef-11e8-8ae0-4c86e419b8d3.png)
> 
> Now I can go to the DB and save the changes and make sure all is correct, It says I have to restart the bot to apply changes. But I cannot do so. 
> 
> [ranksystem.log](https://github.com/Newcomer1989/TSN-Ranksystem/files/1715974/ranksystem.log)
> [apache_phpstack-32671-70617-195347.cloudwaysapps.com.error.log](https://github.com/Newcomer1989/TSN-Ranksystem/files/1715975/apache_phpstack-32671-70617-195347.cloudwaysapps.com.error.log)
> 
> Any ideas?

**Comment by Shad86** [comment]
> The first screenshot shows you the problem. You have a wrong rankup definition. That is the reason the Ranksystem doesn't startup correct.
> The first problem initiate the second one. Your files version is 1.2.4 but your database version is 1.2.3.
> 
> So you need to correct your rankup defintion to solve all your problems.
> 
> If I am right, you will now not be able to save it via webinterface.
> You need to update this value direct on the database. Enter the following SQL command to correct it:
> 
> `UPDATE config SET grouptime='31534000=>XXX';`
> Replace the XXX with an valid server group ID on your ts3 server.
> 
> After this change you should be able to start the Bot. Then the update process should update your database to version 1.2.4., which should be shown after also on the Webinterface (reload needed).
> 
> Then you are fine!

**Comment by Newcomer1989** [comment]
Opened to be pinned at start page.. So also others can find this issue more easy.

**Comment by Newcomer1989** [comment]
With the changed update process on 1.2.6 it should be solved, also if the update comes from a lower version as 1.2.5
