### ISSUE TITLE
SQL Array Error

### ISSUE THREAD

**Issue by MSparkle** [Newcomer1989/TSN-Ranksystem#409]
When i try to add time to groups or edit the exception mode it tells me:
Array ( [0] => 42S22 [1] => 1054 [2] => Unknown column 'registercid' in 'field list' )
when i was using 1.2.3 version there was no problem

**Comment by IMmmKI** [comment]
Hey

Follow the steps from the below link.

https://github.com/Newcomer1989/TSN-Ranksystem/issues/408

**Comment by Newcomer1989** [comment]
Duplicate issue #408, like IMmmKI described.
