### ISSUE TITLE
Status seite 145 Tage+

### ISSUE THREAD

**Issue by Yatheria1** [Newcomer1989/TSN-Ranksystem#410]
https://rank.adligerunde.eu/stats

Status Seite bei allen die nicht online waren seit dem Update 1.2.4 250 Tage....
Vielleicht seht ihr es selbst.

**Comment by Shad86** [comment]
Das wissen wir bereits, dazu gibt es auch schon ein paar issues.

Für gewöhnlich korrigieren sich diese Zeiten bei den usern sobal sie sich mit dem TS3 befinden und vom ranksystem erfasst und bearbeitet wurden (je  nach Größe und ob mit oder ohne slowmode zwischen 0.5-X Sekunden)

Es wird auf jedenfall danach geschaut.

**Comment by Yatheria1** [comment]
Nja aber was ist mir usern die eventuell nicht mehr auf unseren Server sich verbinden bei den bleibt dann diese Zeit stehen.

**Comment by Newcomer1989** [comment]
duplicate issue #407
