### ISSUE TITLE
Default logfolder

### ISSUE THREAD

**Issue by tryano** [Newcomer1989/TSN-Ranksystem#411]
Hallo,
nach dem Ändern des Standardlogverzeichnisses und dem anschließenden Löschen des /logs/ Ordners crashed der Query-Client.
Hängt vermutlich mit dem "pid"-File zusammen, das auch in /logs/ abgelegt wird, aber nach ändern des Standardlogverzeichnisses nicht mit in das geänderte Logverzeichnis geschrieben wird.

Aber super Arbeit!

**Comment by Newcomer1989** [comment]
Ist ja auch richtig bzw. unvermeidbar.

Für die richtige Handhabe: Zuerst den Bot stoppen. Dann das Logverzeichnis im Webinterface anpassen.
Wichtig, dass neue Logverzeichnis muss die korrekten Owner-Rechte und Schreibrechte besitzen, damit der Bot dort reinschreiben kann.
Erst danach dürfen die alten Log-Files gelöscht werden. Das Verzeichnis selbst muss vorhanden bleiben für die Funktonialität des Bots!

Ein ändern/löschen eines Log-Verzeichnisses im laufenden Betrieb wird vermutlich in nahezu jeder Software zum Absturz oder zumindest zu Fehlern führen.
