### ISSUE TITLE
Migrate from external system to Ranksystem - Convert/Import user & time

### ISSUE THREAD

**Issue by P-Kito** [Newcomer1989/TSN-Ranksystem#412]
Tag: Question

Hey!

First of all: Nice work!
I coded the same stuff on my own as Java bot. I want to switch to your bot tho.

Do you have a quick thought on how to insert my old data (2k client+) into the database of your system?

My DB looks like that (Example):

TS DB ID || millisecond time 
2 || 12312323
34 || 38474747

Any idea, how to select it and insert it in the new (your) system?
Where is the current time saved? How do I put in all the old clients into the bot, without having them to connect first, so I can set the time?

I set up server groups, etc already.

Greetz

**Comment by P-Kito** [comment]
http://vortexirc.com/ Is my old ranking, any chance to convert to your system? It's saved in milliseconds as described above.

(I am german, if you want to continue in german.)

**Comment by Newcomer1989** [comment]
This information are stored inside the table user.

You should find there a field `cldbid`, which is the TS DB ID and a field `count`, which is the time.

The time is stored inside the Ranksystem as normal seconds, so you need to divide your milliseconds with 1.000. And you also need to round this value to a natural number (without comma).

BUT: That the Ranksystem is able to work, you need at least the unique client ID, stored in field `uuid`.

The rest values of the user table should be filled by the Ranksystem, when an user is joining your server.

describe user;
+-----------+---------------+------+-----+---------+-------+
| Field     | Type          | Null | Key | Default | Extra |
+-----------+---------------+------+-----+---------+-------+
| uuid      | varchar(29)   | NO   | PRI | NULL    |       |
| cldbid    | int(10)       | NO   | MUL | 0       |       |
| count     | int(10)       | NO   |     | 0       |       |
| name      | varchar(30)   | YES  |     | NULL    |       |
| lastseen  | bigint(11)    | NO   |     | 0       |       |
| grpid     | int(10)       | NO   |     | 0       |       |
| nextup    | int(10)       | NO   |     | 0       |       |
| idle      | int(10)       | NO   |     | 0       |       |
| cldgroup  | varchar(255)  | YES  |     | NULL    |       |
| online    | tinyint(1)    | NO   | MUL | 0       |       |
| boosttime | int(10)       | NO   |     | 0       |       |
| rank      | int(10)       | NO   |     | 0       |       |
| platform  | varchar(32)   | YES  |     | NULL    |       |
| nation    | varchar(3)    | YES  |     | NULL    |       |
| version   | varchar(64)   | YES  | MUL | NULL    |       |
| firstcon  | bigint(11)    | NO   |     | 0       |       |
| except    | tinyint(1)    | NO   |     | 0       |       |
| ip        | varbinary(16) | YES  |     | NULL    |       |
| grpsince  | bigint(11)    | NO   |     | 0       |       |
| cid       | int(10)       | NO   |     | 0       |       |
+-----------+---------------+------+-----+---------+-------+

**Comment by P-Kito** [comment]
```sql
INSERT INTO ts3_ranksystem.user (uuid, cldbid, count)
SELECT 
ts3c.client_unique_id,
cr.clientid, 
ROUND(cr.msTime / 1000, 0)
FROM ts3rankings.ClientRanking cr
JOIN ts3.clients ts3c
	ON ts3c.client_id = cr.clientid AND ts3c.server_id = 1



```

I merged them, all working. Now all need to connect, so the bot fetches the nicknames etc. Might aswell want to get them from TS3 DB.
