### ISSUE TITLE
Can't clean install version 1.2.4

### ISSUE THREAD

**Issue by xopez** [Newcomer1989/TSN-Ranksystem#415]
Error message shown in Browser: `Database Connection failed: could not find driver `
Installing 1.2.2 and upgrading to 1.2.4 is working.

**Comment by Newcomer1989** [comment]
For a clean install please take the download from our main page
https://ts-n.net/downloads/ranksystem_1.2.4.zip

With Version 1.2.5 it will also be fixed here on the GitHub Version.
