### ISSUE TITLE
Getting error when saving changes in core.php

### ISSUE THREAD

**Issue by xopez** [Newcomer1989/TSN-Ranksystem#416]
As mentioned here #415 I managed to install the version from homepage. Thanks for that. But I encountered another problem when trying to save things at the core.php.
I get following error:
`Array ( [0] => 42S22 [1] => 1054 [2] => Unknown column 'registercid' in 'field list' ) `
A screenshot of my changes can be viewed here:
https://screenshots.firefox.com/IBr2VQ6rf4EqAWgc/rank.mightful-noobs.de

**Comment by Newcomer1989** [comment]
duplicate issue #408
