### ISSUE TITLE
Disable next rank up

### ISSUE THREAD

**Issue by GYJohn** [Newcomer1989/TSN-Ranksystem#417]
Is it possible to deactive the "next rank up" option?
I only need the stats and the next rank field can't be empty.

Thank you!

Answers in English/Deutsch

**Comment by Shad86** [comment]
Hallo,

die einzige Lösung wäre eine vorhandene Gruppe zu nehmen und einen sehr hohen Wert zu nehmen, so das faktisch nie jemand aufsteigen wird.

Der Max Wert sollte 999999999 sein (ca. 31,7 Jahre)

**Comment by GYJohn** [comment]
Moin,

da hab ich schon versucht, der will die Gruppe aber nicht annehmen.
