### ISSUE TITLE
bootstrap-select documentation has moved

### ISSUE THREAD

**Issue by caseyjhol** [Newcomer1989/TSN-Ranksystem#418]
I'm the lead developer for the bootstrap-select project. I see that your project is utilizing bootstrap-select and you have been kind enough to give us an attribution in your info section. However, we have recently moved the repo and documentation. The new location for the documentation is: https://developer.snapappointments.com/bootstrap-select. If you could update the link and change the copyright to "2012-2018 SnapAppointments, LLC" it would be much appreciated. I can submit a PR if that would be easier. Thanks!

Edit: I've gone ahead and submitted a PR just to make things easier.

**Comment by Newcomer1989** [comment]
Thx for information. I will check this and update the bootstrap-select with one of the next updates of the Ranksystem and then also change the copyright for sure.
