### ISSUE TITLE
Beschreibung im TAB ändern

### ISSUE THREAD

**Issue by TheChaosToast** [Newcomer1989/TSN-Ranksystem#422]
Servus zusammen,

ich wusste jetzt nicht wie ich den Titel Beschreiben soll, aber ich hätte es gern wieder das statt TS-N.NET Ranksystem mein eigener Seitenname angezeigt wird - wie auf dem Bild :)
![unbenannt](https://user-images.githubusercontent.com/36563709/36472761-06577e94-16f3-11e8-8b37-2cb9e1b3c705.png)

Früher musste man dazu (wenn ich mich recht erinnere) die index.php bearbeiten. Könnte mir bitte jemand sagen wo ich dies ändern kann

Liebe Grüße

**Comment by Newcomer1989** [comment]
Dafür ist derzeit ein Eingriff in den Programmcode notwendig. Leider können wir solche Änderungen nicht supporten, da wir sonst nichts anderes mehr tun würden.
Änderungen am Code sind natürlich grundlegend möglich, aber auf eigenem Risiko. Weiterhin sollte dies aufgrund des Auto-Updaters unbedingt gesichert werden.

Eine Funktion zum Ändern ist bereits auf unserer ToDo-Liste und wird auch irgendwann folgen. Allerdings ist die Liste sehr lang. Ein ETA kann also nicht genannt werden.
