### ISSUE TITLE
Bot startet nicht - Sonderzeichen in Username/Passwort

### ISSUE THREAD

**Issue by PaDo90** [Newcomer1989/TSN-Ranksystem#424]
Hallo, habe soeben das TSN Ranksystem auf meinem Debian 8 Server installiert.
Ganz nach Anleitung auf der TS-N.NET Webseite.

Wenn ich den Bot aber starten möchte, steht folgendes im Log (IP ist anonymisiert):

> 2018-02-23 13:30:29.964583   ERROR     Fehler 0: php_network_getaddresses: getaddrinfo failed: Name or service not known
> 2018-02-23 13:30:29.958031   INFO      Connect to TS3 Server (Address: "85.25.XXX.XXX" Voice-Port: "9987" Query-Port: "10011").
> 2018-02-23 13:30:29.957944   INFO      Loading addons [done]
> 2018-02-23 13:30:29.957838   INFO        Addon: 'assign_groups' [OFF]
> 2018-02-23 13:30:29.957444   INFO      Loading addons...
> 2018-02-23 13:30:29.957337   INFO      Ranksystem Version: 1.2.4
> 2018-02-23 13:30:29.957120   INFO        Check files permissions [done]
> 2018-02-23 13:30:29.945053   INFO        Check files permissions...
> 2018-02-23 13:30:29.944321   INFO        No newer version detected; Database check finished.
> 2018-02-23 13:30:29.944227   INFO      Check Ranksystem database for updates.
> 2018-02-23 13:30:29.944133   INFO        Config check [done]
> 2018-02-23 13:30:29.943839   INFO        Config check started...
> 2018-02-23 13:30:29.943756   DEBUG     Using PHP Version: 5.6.33-0+deb8u1
> 2018-02-23 13:30:29.943626   DEBUG     Running on OS: Linux 3.16.0-042stab127.2
> 2018-02-23 13:30:29.934465   INFO      Initialize Bot...

Ich habe im Webinterface unter "TS3 Hostadresse" localhost versucht sowie die eigentliche IP des Servers. Querry Daten sind natürlich auch eingetragen. Eigentlich alles so wie es sein soll aber der Server möchte einfach nicht starten.

Rufe ich oder ein anderer User die Statistik-Seite auf steht dort "verification needed!" und obwohl ich im gewählten Channel bin (extra über den Link der Verifizierungsseite verbunden) sagt er mir trotzdem, dass sich kein User in diesem Channel befindet, welchen ich im Webinterface unter "Verifizierung-Channel" eingetragen habe. (Channel-ID: 1, ist der Channel welcher als Eingangschannel vom TS³ Server ist)

Bin Ratlos, vielleicht könnt ihr mir helfen? :)

**Comment by Newcomer1989** [comment]
Das ist ein lokales Netzwerk Problem.

**Comment by PaDo90** [comment]
Das bezweifel ich irgendwie. Das System ist ganz frisch aufgesetzt, absolut ohne Fehler!

**Comment by Newcomer1989** [comment]
> Nun wurde der komplette Server ganz frisch neu aufgesetzt, alles nach Anleitung installiert (so wie es vorher auch lief) und jetzt startet er gar nicht.

Also verstehe ich richtig:
Das Ranksystem lief bereits auf deinem System ohne Probleme. Nun wurde das OS (sprich die Host Machine) neu aufgesetzt und seit dem geht es nicht mehr!?
Ich sehe hier 3 mögliche Fehlerquellen: OS (u.a. Netzwerk, Firewall), Ranksystem, TS3 Server

Probiere den Aufbau einer connection zu dem TS3 Query mal ohne das Ranksystem. Damit sollte sich erkennen lassen, dass es sich hier um kein Problem mit dem Ranksystem handelt.

Fehlerquelle kann auch das IP Protokoll sein. Bitte darauf achten, dass beim Test das identische Protokoll, also die identischen connection details genutzt werden, wie mit dem Ranksystem.

**Comment by PaDo90** [comment]
Genau, vorher lief alles, dann wollte ich ein Update vom Ranksystem installieren weil es eben nicht mehr lief, obwohl nichts verändert wurde am Server. Update installiert, lief trotzdem nicht. Dann habe ich paar Tage später den kompletten Server neu aufgesetzt und mir gedacht, ich probiere es nochmal. Leider ohne Erfolg!

Teamspeak, Domains, Netzwerk, alles läuft perfekt. Kann mich ganz normal mit der Serverquerry z.B mit YaTQA verbinden.

Neben dem Ranksystem nutze ich noch ein TS3-Webinterface (Psychokiller's) aber das hatte ich vorher auch schon mit dem Ranksystem im Einsatz. In dem Webinterface klappt auch alles ohne Probleme. Nur eben das Ranksystem nicht.

**Comment by Newcomer1989** [comment]
Nutzt das Webinterface denn die gleiche Adresse (IP), wie die, die du im Ranksystem gesetzt hast?
Läuft das Webinterface denn auch auf der gleichen Machine, wie das Ranksystem?

> Probiere den Aufbau einer connection zu dem TS3 Query mal ohne das Ranksystem. Damit sollte sich erkennen lassen, dass es sich hier um kein Problem mit dem Ranksystem handelt.

Hast du das denn mal versucht?

**Comment by PaDo90** [comment]
Natürlich, läuft alles auf dem gleichen System, habe nur eine Statische IP.

> Probiere den Aufbau einer connection zu dem TS3 Query mal ohne das Ranksystem. Damit sollte sich erkennen lassen, dass es sich hier um kein Problem mit dem Ranksystem handelt.

Wie gesagt ich kann mich sonst überall verbinden mit den gleichen Daten. YaTQA sowie das TS3 Webinterface welches ich verwende. Klappt alles mit der gleichen Query. Oder meinst du etwas anderes?

**Comment by Shad86** [comment]
Die dbconfig ist auch korrekt?

 - Hostdaten korrekt? (richtige Ip eingetragen? - wenn localhost oder 127.0.0.1 eingetragen ist bitte darauf achten das unter Umständen eine der beiden Adressen nicht auflösen können [config überprüfen])

- Logindaten zum mysql Server korrekt?

- DNS könnte auch weiterhin ein Problem sein, nur weil program X funktioniert muss das nicht zwingend heißen, das deshalb der DNS in Ordnung ist, auch hier die configs überprüfen

**Comment by PaDo90** [comment]
Ja, wie bereits im Anfangsbeitrag erwähnt habe ich es mit "localhost" mit "127.0.0.1" sowie mit der eigentlichen Server IP probiert. Auch mit der Domain, mit welcher man sich auf den TS-Server verbinden kann. Die Ports sind auch alle Teamspeak Standard.

MySQL Daten sind natürlich correct, sonst würde das Ranksystem Interface ansich ja nicht gehen.

DNS hat auch alles die gleiche Einstellung wie vorher alles war, wo das Ranksystem noch lief.

**Comment by monster010** [comment]
PaDo90 versuch es mal mit der externen IP, denke das sollte dein Problem lösen.

**Comment by Shad86** [comment]
https://github.com/Newcomer1989/TSN-Ranksystem/issues/280#issuecomment-307804710 hab ich hier noch unter einem Github post gefunden - solltest du also ein eigenes Passwort gesetzt haben, könnte das eventuell die Ursache sein

**Comment by PaDo90** [comment]
Ernsthaft? Daran lag es ... Gerade das Serverquerry Passwort geändert (Nur ein Sonderzeichen entfernt) und schon ging es! Ist ja dann wohl ein Bug im Ranksystem, oder? Dass es evtl nicht geht, wenn man Sonderzeichen im Passwort verwendet?

**Comment by Newcomer1989** [comment]
Funktioniert denn genau dieses Passwort mit anderen Tools, z.B. dem Webinterface?

**Comment by PaDo90** [comment]
Ja, hat sonst überall ohne Probleme funktioniert mit dem Passwort. Webinterface von Psychokiller sowie YaTQA.

In dem Passwort war ein Fragezeichen, habe dieses durch eine Zahl ersetzt, das Serverquerry Passwort hatte ich selbst vergeben.

**Comment by Newcomer1989** [comment]
Ok, vielen Dank für die Info.

Wir werden das Testen / Prüfen. Sollte es ein Fehler sein, wird es mit einem der künftigen Releases behoben, sofern es am Ranksystem liegen sollte.

**Comment by Newcomer1989** [comment]
solved with release version 1.2.7
