### ISSUE TITLE
Disable search engine's indexing by default [Suggestion]

### ISSUE THREAD

**Issue by bykidi** [Newcomer1989/TSN-Ranksystem#425]
Hello Newcomer! Thanks for an 1.2.5 update.
Here is another suggestion for a ranksystem: ability to disable indexing of ranksystem pages for search engines.
First of all: it's not SEO-friendly.
Second and most important one: there is no point of indexing that at all.
Everything the search engine now do is making useless server load by indexing the ranksystem.

![default](https://user-images.githubusercontent.com/1337953/36611962-45bddd18-18e6-11e8-8a2f-eccc07015c08.png)

**Comment by bykidi** [comment]
I think that
`<meta name="robots" content="noindex" />`
will do the job mostly

**Comment by xopez** [comment]
#427 
Added robots.txt to merge.
So it's basically all denied and you don't need it in every file.

You can read more here about it: https://en.ryte.com/wiki/Robots.txt

**Comment by Newcomer1989** [comment]
declined

This is the job of each web administrator. I think it shouldn't be done by an application.

When I am not wrong, the robots.txt should be lying inside the root folder of the webspace and in best case give information for all the different (sub)folders. Then every person should manage it for himself, what he wishes would be listed and what not.
