### ISSUE TITLE
Fehlermeldung:  ERROR         Es ist die Servergruppe mit der ID 41 im Parameter 'Servergruppen-Ausnahmen' (Webinterface -> Kern) konfiguriert, jedoch ist diese Servergruppe nicht (mehr) auf dem TS3 Server vorhanden! 

### ISSUE THREAD

**Issue by Tiiiimo** [Newcomer1989/TSN-Ranksystem#426]
Hey,
ich erhalte diese Fehlermeldung, aber diese Gruppen sind verfügbar und exestieren noch.
Hat jemand von euch eine Idee, woran das liegen könnte oder was ich beachten sollte?
✘━━━━━━━━━━━━━━━━━━━━━━━━━━━━✘
Infos:
Version des RankSystems 1.2.5
PHP Version: 5.6
Database Version: 5.5
Linux 2.6.32
✘━━━━━━━━━━━━━━━━━━━━━━━━━━━━✘
Code: https://hastebin.com/inoducomey.pl

**Comment by Newcomer1989** [comment]
duplicate https://github.com/Newcomer1989/TSN-Ranksystem/issues/414
