### ISSUE TITLE
TeamSpeak is only refreshed at first connect

### ISSUE THREAD

**Issue by xopez** [Newcomer1989/TSN-Ranksystem#428]
Since Version 1.2.4 I have the problem that the TeamSpeak-data at the bottom of "stats/index.php" is only refreshed at first connect. Only the clock of the onlinetime is running right. You can look here: https://rank.mightful-noobs.de/stats/index.php

Example:
User (Online / Max) | 8 / 512
Actual data: 
User: 4 / 512 (-2 reserved)
Queries: 1 / 512

Furthermore a problem of this is, that the next rankup time isn't refreshed and static, cause the bot sees them as offline.

**Comment by xopez** [comment]
I updated to 1.2.5 with same problem.

**Comment by xopez** [comment]
Log:

```
2018-02-24 12:19:56.484311   INFO      Initialize Bot...
2018-02-24 12:19:56.489315   DEBUG     Running on OS: Linux 4.4.0-112-generic
2018-02-24 12:19:56.489368   DEBUG     Using PHP Version: 7.2.2
2018-02-24 12:19:56.489410   DEBUG     Database Version: 5.7.21-0ubuntu0.16.04.1
2018-02-24 12:19:56.489448   INFO      Check Ranksystem database for updates.
2018-02-24 12:19:56.489486   INFO        No newer version detected; Database check finished.
2018-02-24 12:19:56.489919   INFO        Check files permissions...
2018-02-24 12:19:56.494112   INFO        Check files permissions [done]
2018-02-24 12:19:56.494166   INFO      Ranksystem Version: 1.2.5
2018-02-24 12:19:56.494203   INFO        Config check started...
2018-02-24 12:19:56.494612   INFO        Config check [done]
2018-02-24 12:19:56.494668   INFO      Loading addons...
2018-02-24 12:19:56.495088   INFO        Addon: 'assign_groups' [OFF]
2018-02-24 12:19:56.495144   INFO      Loading addons [done]
2018-02-24 12:19:56.495183   INFO      Connect to TS3 Server (Address: "mightful-noobs.de" Voice-Port: "9987" Query-Port: "10011").
2018-02-24 12:19:56.508232   INFO        Connection to TS3 Server established.
2018-02-24 12:19:56.509616   NOTICE      No channel defined where the Ranksystem Bot should be entered.
2018-02-24 12:19:56.509683   INFO      Bot starts now his work!
```
Seems all fine and finds new clients, but doesn't refresh the time

`2018-02-24 12:31:52.173487   INFO      User 'TS3Bridge - Mightful Noobs' (eindeutige Client-ID: luuofJPPk1bRFB2IcvfsGE1MJ0A=; Client-Datenbank-ID: 200) ist bisher unbekannt -> wurde nun zum Ranksystem hinzugefügt.`

**Comment by xopez** [comment]
Got this message over TeamSpeak today.

```
Your Ranksystem seems to be slow. This is not a big deal, but it needs more ressources then necessary.
Here you'll find some information to optimize it: https://ts-n.net/ranksystem.php#optimize
Last 10 runtimes in seconds (lower values are better):
5.14642;5.12268;5.15484;5.12149;5.12146;5.14657;5.15469;5.15486;5.12989;5.12397
```

Maybe its connected to my problem

**Comment by Shad86** [comment]
Yes for sure, because then you only get an update after more or less 5 seconds.

**Comment by Shad86** [comment]
i would definitely recommend to optimize your database, as your times get more accurate. best would be to get the loop under 1sec. if possible.

**Comment by xopez** [comment]
I have all done from the tutorial, and I see it is running faster now.
But id doesn't change the fact that the server details at the bottom aren't refreshed and not the current data. It's only the data at the first connect after the install. And people which are online are shown as offline.
I don't get any PHP errors.

**Comment by Shad86** [comment]
Ich habs gerade mal bei mir getestet, ich verbinde darauf und es wechselt instant auf von 11 auf 12 user.

kannst du eventuell mal überprüfen ob es bei dir ein Problem mit dem cache gibt?

getestet habe ich es mit Chrome

**Comment by xopez** [comment]
Ist Serverseitig ausgeschaltet.
Meine Module in Apache:
```
access_compat
actions
alias
auth_basic
auth_digest
authn_core
authn_file
authz_core
authz_host
authz_user
autoindex
bw
cgi
cgid
dav
dav_fs
dav_lock
deflate
dir
env
expires
fastcgi
fcgid
filter
geoip
headers
heartbeat
include
info
mime
mpm_prefork
negotiation
perl
proxy
proxy_fcgi
python
request
rewrite
session
setenvif
socache_shmcb
ssl
status
suexec
unique_id
userdir
```
Auch der Ordner `/var/cache/apache2/mod_cache_disk` ist leer.
Caching Clientside kanns auch nicht sein, da ich es mit Firefox Privatem Fenster gemacht habe.

**Comment by Shad86** [comment]
Ich war soeben mal auf deiner Rank-System-Seite, da scheint allgemein etwas kaputt zu sein, es werden nämlich auch keine Statistiken erzeugt/angezeigt.

Diese Info fehlte bis dato.

Sinnvoll wäre hier jetzt:

- Backup machen

- Dann mal die aktuellste version herunterzuladen (https://github.com/Newcomer1989/TSN-Ranksystem/archive/1.2.5.zip)

- Dann entpacken und alles außer other/dbconfig.php - install.php und other/phpcommand.php über die Dateien auf dem Webserver drüber zu ziehen.

So kann man erst mal sicherstellen das die Daten auf dem Webserver nicht beschädigt sind.

Wenn du das alles gemacht hast, den Bot wieder starten und überprüfen ob du auch auf der Server-Statistik-Seite Statistiken generiert bekommst.

Sollte es wieder erwartend nicht gehen, melde dich einfach nochmal

**Comment by xopez** [comment]
Ist genauso, ich kann später auch damit nochmal einen cleaninstall versuchen

**Comment by Shad86** [comment]
Wäre mal ein Versuch Wert, denke aber bitte daran ein Backup zu machen.

**Comment by xopez** [comment]
ok, ich schließe den Fehler, nach cleaninstall mit aktueller Version klappt es. Danke für die Hilfe.
