### ISSUE TITLE
Flood Ban beim Avatar downloaden

### ISSUE THREAD

**Issue by Tiiiimo** [Newcomer1989/TSN-Ranksystem#429]
Wenn der Bot versucht die Avatars zu downloaden wird der gebannt.
Außerdem können die Icons auf der Website( Rank-Liste Group-Icon + Server-Icon) nicht angezeigt werden

Was kann man dagegen tun?

Code: https://pastebin.com/LkcRwxYg

**Comment by Shad86** [comment]
Die Ip des Webservers sollte / muss in die Whitelist des Teamspeak 3 Servers eingetragen werden, die Datei befindet sich im TS3-Server ordner und heißt Query_Ip_Whitelist.txt

**Comment by Tiiiimo** [comment]
Habe ich gemacht, funktioniert trotzdem nicht

**Comment by Shad86** [comment]
Die Whitelist, braucht zwischen 5-10min bis sie geladen wird / greift.

Solange nichts an den Standarteinstellungen in yatqa oder ähnlichen tools am TS3 verändert wurden, sollte es gehen.

**Comment by Tiiiimo** [comment]
Die IP Adresse ist ja standartgemäß 127.0.0.1, da er auf dem Server liegt, wodrauf auch der Ts ist. Und diese Adresse war schon von anfang an drinne...

**Comment by Shad86** [comment]
Wie gesagt, kann es mir gerne mal mit dir zusammen anschauen, komm dafür einfach auf den TS3 - ich heiße da auch Shad86 :)

**Comment by Tiiiimo** [comment]
Gerne, könntest du mir nur vielleicht die IP sagen?

**Comment by Shad86** [comment]
Haben es auf dem TS3 gelöst, im Ranksystem Webinterface stand nicht 127.0.0.1 weshalb der Whitelisteintrag nicht gegriffen hat.
