### ISSUE TITLE
list_rankup.php leer bei einstellung "ausgeschl. Clients: ON"

### ISSUE THREAD

**Issue by oDerPaul** [Newcomer1989/TSN-Ranksystem#430]
Hey

Mir ist so eben aufgefallen das wenn ich im Webinterface unter "Statistik Seite" die Einstellung "ausgeschl. Clients" einschalte, werden auf der "list_rankup.php" bei der ersten Seite keine User mehr angezeigt.
Geht man auf Seite 2 oder ändert die Sotierung werden User angezeigt.

Schalte ich die Einstellung wieder aus, ist die erste Seite wieder normal gefüllt.

![webinterface](https://user-images.githubusercontent.com/17052707/36632091-29f3e8a6-1982-11e8-92d5-f4e6aa5626b4.png)

![listrankup](https://user-images.githubusercontent.com/17052707/36632090-29d97b06-1982-11e8-97b8-66288ced0a53.png)

**Comment by Newcomer1989** [comment]
Kann ich so leider nicht nachstellen. Bist du dir sicher, dass es etwas mit den ausgeschlossenen Clients zu tun hat oder eher mit denen in der höchsten Gruppe?! Sind denn bei dir ggfs. viele User im höchsten Rang?

**Comment by oDerPaul** [comment]
Im höchsten Rang ist keiner aber relativ viele sind ausgeschlossen.

**Comment by Newcomer1989** [comment]
Bitte mal schauen, ob es mit der aktuellen Version 1.2.6 immer noch besteht.

**Comment by Newcomer1989** [comment]
Falls noch Probleme bestehen sollte, bitte den Issue wieder öffnen oder gerne einen neuen aufmachen. Ansonsten gehen wir davon aus, dass es behoben ist.
