### ISSUE TITLE
Bug  ServergruppenID

### ISSUE THREAD

**Issue by quietMichael** [Newcomer1989/TSN-Ranksystem#431]
Hi,

Und zwar habe ich folgenden Fehler das Ranksystem lief Problemfrei, und auf einmal findet er die Gruppen ID`s nicht Obwohl diese Vorhanden sind...

Hier Screenshots:

https://cloud.online-freunde.com/index.php/s/3QS7ZBykqsJ7nRo
https://cloud.online-freunde.com/index.php/s/XBs3dAbdrsnbKLr

Grüße

**Comment by Shad86** [comment]
BItte einmal das Rank-system ausschalten und dann diesen sql befehl absetzen ->

DELETE FROM groups;

Dann wieder starten und im Log schauen ob er sich nun die Gruppen richtig zieht.

Danach sollte alles wieder normal funktionieren

**Comment by quietMichael** [comment]
Top Danke das war es.

Grüße
