### ISSUE TITLE
Probleme mit nicht existierenden Server Group IDs

### ISSUE THREAD

**Issue by Sheggymuh** [Newcomer1989/TSN-Ranksystem#437]
Hallo,
ich bekomme folgenden Fehler:
`ERROR         Es ist die Servergruppe mit der ID 181 im Parameter 'Servergruppen-Ausnahmen' (Webinterface -> Kern) konfiguriert, jedoch ist diese Servergruppe nicht (mehr) auf dem TS3 Server vorhanden! Bitte korrigiere dies oder es können hierdurch Fehler auftreten!`

Die ID, die dort angegeben ist, existiert auf jeden Fall, geprüft in der Datenbank.
QueryLogin hat alle Rechte, wurde mit serveradmin geprüft.

Welche Faktoren könnten eventuell dazu führen, dass die ID nicht mehr korrekt gelesen wird?

**Comment by monster010** [comment]
Denke dir sollte das hier helfen [https://github.com/Newcomer1989/TSN-Ranksystem/issues/431#issuecomment-368290464](url)
