### ISSUE TITLE
Bot doesn't start

### ISSUE THREAD

**Issue by Thalothas** [Newcomer1989/TSN-Ranksystem#439]
Hi All,

So i just installed the ranksystem bot on a Linux machine that has everything installed, webinterface etc works but when i click start bot it does nothing it doesnt give me an error it doesnt give me an php error nothing at all i'm trying everything but could not come to any conclusions on what it might be :(

Also it does not generate an Log.

Greetings Thalothas

**Comment by Shad86** [comment]
Hello,

You can also try to start it with debug to get may a list of errors.
1) Go to file jobs/bot.php and comment the line `error_reporting(0);` out (change to `//error_reporting(0);`)
2) Open a command line and run the jobs/bot.php manual
`php jobs/bot.php`
3) Post the output here...

**Comment by Thalothas** [comment]
PHP Fatal error:  Uncaught Error: Undefined class constant 'MYSQL_ATTR_INIT_COMMAND' in /opt/lampp/htdocs/other/config.php:12
Stack trace:
#0 /opt/lampp/htdocs/jobs/bot.php(62): require_once()
#1 {main}
  thrown in /opt/lampp/htdocs/other/config.php on line 12

commented out the error reporting and this is what i got.

**Comment by Shad86** [comment]
on line 12 in the config.php you would find this:

PDO::MYSQL_ATTR_INIT_COMMAND => 'SET NAMES utf8',

if it looks the same then i think there is a problem with utf8

Check that you have the locales package installed

dpkg -l locales


down vote
Check that you have the locales package installed

`dpkg -l locales`

If its not installed:

`apt-get install locales`

As root now execute:

`dpkg-reconfigure locales`

and there you can navigate with the up/down arrow keys
then choose your language, for example:

`en_US-UTF-8`

and then press enter and choose and accept everything.
After it is done close your console and open a new one.
Then all should work

**Comment by Thalothas** [comment]
Hello Shad,

I still am getting the same error as before tried to reconfigure the locales, everything when perfect but didnt solve the problem :s

**Comment by Shad86** [comment]
Okay, i searched a little bit on google and found out, that pdo extension may is disabled.

pls make sure that this:

#/etc/php/php.ini

extension=pdo_mysql.so

is available and enabled

**Comment by Shad86** [comment]
you also can install it by

sudo apt-get install php7.0-mysql
or
sudo apt-get install php7.1-mysql

**Comment by Thalothas** [comment]
I did the sudo apt-get install php7.0-mysql but now it cant connect anymore but also doesnt doesnt give me the error i uncommented the extensions which got commented again and now get this

**Comment by Thalothas** [comment]
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/php_bz2.dll' - /usr/lib/php/20151012/php_bz2.dll: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/php_curl.dll' - /usr/lib/php/20151012/php_curl.dll: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/php_gd2.dll' - /usr/lib/php/20151012/php_gd2.dll: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/php_pdo_mysql.dll' - /usr/lib/php/20151012/php_pdo_mysql.dll: cannot open shared object file: No such file or directory in Unknown on line 0
Database Connection failed: SQLSTATE[HY000] [2002] No such file or directory

**Comment by Shad86** [comment]
https://askubuntu.com/questions/776322/startup-unable-to-load-dynamic-library-usr-lib-php-20151012-php-mbstring-dll ...

**Comment by Thalothas** [comment]
still have the same error as the first one 

(PHP Fatal error: Uncaught Error: Undefined class constant 'MYSQL_ATTR_INIT_COMMAND' in /opt/lampp/htdocs/other/config.php:12
Stack trace:
#0 /opt/lampp/htdocs/jobs/bot.php(62): require_once()
#1 {main}
thrown in /opt/lampp/htdocs/other/config.php on line 12)

got any more info did everything on this page  https://github.com/Newcomer1989/TSN-Ranksystem/wiki/Install-Requierements-and-Instructions

**Comment by Shad86** [comment]
you 100% sure you have php-mysql (in your relevant version) installed? your need pdo otherwise you would get this error - as said - isn't a ranksystem issue

**Comment by Thalothas** [comment]
Oke so after 2 days of checking things out on my own i finally correctly installed php and the ranksystem worked for 2 minutes then i wanted to setup the verification channel and got this

`2018-03-13 09:42:04.221464   CRITICAL  Critical Config error! Shutting down!
2018-03-13 09:42:04.205429   ERROR         There is a servergroup with ID 6 configured inside your 'servergroup exception' paramter (webinterface -> core), but that servergroup ID isn't existent on your TS3 server (anymore)! Please correct this or errors might happen!
2018-03-13 09:42:04.205400   CRITICAL      There is a servergroup with ID 50 configured inside your 'rank up definition' paramter (webinterface -> core), but that servergroup ID isn't existent on your TS3 server (anymore)! Please correct this or errors might happen!
2018-03-13 09:42:04.205324   CRITICAL      There is a servergroup with ID 47 configured inside your 'rank up definition' paramter (webinterface -> core), but that servergroup ID isn't existent on your TS3 server (anymore)! Please correct this or errors might happen!`

**Comment by Thalothas** [comment]
Is the above error becouse i dont have a servergroup that has the ID of 6 or 50 or 47, and i need to say for example wich servergroup i want to give when a certain time has passed for the user?

**Comment by Thalothas** [comment]
Nevermind i got it working and i understand it now :dancer:

**Comment by Thalothas** [comment]
Thanks for the help Shad :3
