### ISSUE TITLE
Bug ServergruppenID

### ISSUE THREAD

**Issue by quietMichael** [Newcomer1989/TSN-Ranksystem#440]
Fehler besteht wieder Letzte Antwort von shad war:

BItte einmal das Rank-system ausschalten und dann diesen sql befehl absetzen ->

DELETE FROM groups;

Dann wieder starten und im Log schauen ob er sich nun die Gruppen richtig zieht.

Danach sollte alles wieder normal funktionieren

Allerdings ist der Fehler wieder da.

Grüße

**Comment by Shad86** [comment]
Wie lange, ist das nochmal her?

hast du das nun wieder so getan, wenn ja wäre es gut noch einmal bis zum nächsten auftreten zu warten.

Wichtig hierbei (wie auch bei unserem letzten Gespräch gesagt) die Zeiten merken, wann es passiert ist (und am besten natürlich notieren)

MfG

Shad86

**Comment by quietMichael** [comment]
Ich lasse hier Offen damit man es sehen kann ;)

**Comment by IMmmKI** [comment]
Hey, 

I have the same error every few days. I have run the SQL command and then everything is happy again.

**Comment by IMmmKI** [comment]
Hey Guys, 

Any idea?

**Comment by Shad86** [comment]
In the next version the handling will be improved, so that this error should no longer occur.

**Comment by Newcomer1989** [comment]
Should be fixed with release 1.2.6
