### ISSUE TITLE
PHP Fehlermeldung

### ISSUE THREAD

**Issue by PaDo90** [Newcomer1989/TSN-Ranksystem#441]
Das Ranksystejm läuft jetzt einwandfrei bei mir, allerdings ist mir etwas in einem Error-Log aufgefallen.
Die Logdatei war nach nichtmal 2 Tagen über 100 GB groß(!) musste ich mir dann mal anschauen bevor ich die lösche.

Folgende Zeilen erscheinen mehr als genüge in der Log-Datei:

> [Fri Mar 02 01:22:44.786264 2018] [fcgid:warn] [pid 19348:tid 140624537814784] [client 66.249.65.94:44582] mod_fcgid: stderr: PHP Warning:  A non-numeric value encountered in /var/www/vhosts/XXX.de/httpdocs/ts3stats/stats/list_rankup.php on line 191
[Fri Mar 02 01:22:44.786271 2018] [fcgid:warn] [pid 19348:tid 140624537814784] [client 66.249.65.94:44582] mod_fcgid: stderr: PHP Warning:  A non-numeric value encountered in /var/www/vhosts/XXX.de/httpdocs/ts3stats/stats/list_rankup.php on line 191
[Fri Mar 02 01:22:44.786277 2018] [fcgid:warn] [pid 19348:tid 140624537814784] [client 66.249.65.94:44582] mod_fcgid: stderr: PHP Warning:  A non-numeric value encountered in /var/www/vhosts/XXX.de/httpdocs/ts3stats/stats/list_rankup.php on line 191
[Fri Mar 02 01:22:44.786283 2018] [fcgid:warn] [pid 19348:tid 140624537814784] [client 66.249.65.94:44582] mod_fcgid: stderr: PHP Warning:  A non-numeric value encountered in /var/www/vhosts/XXX.de/httpdocs/ts3stats/stats/list_rankup.php on line 191
[Fri Mar 02 01:22:44.786290 2018] [fcgid:warn] [pid 19348:tid 140624537814784] [client 66.249.65.94:44582] mod_fcgid: stderr: PHP Warning:  A non-numeric value encountered in /var/www/vhosts/XXX.de/httpdocs/ts3stats/stats/list_rankup.php on line 191
[Fri Mar 02 01:22:44.786296 2018] [fcgid:warn] [pid 19348:tid 140624537814784] [client 66.249.65.94:44582] mod_fcgid: stderr: PHP Warning:  A non-numeric value encountered in /var/www/vhosts/XXX.de/httpdocs/ts3stats/stats/list_rankup.php on line 191
[Fri Mar 02 01:22:44.786302 2018] [fcgid:warn] [pid 19348:tid 140624537814784] [client 66.249.65.94:44582] mod_fcgid: stderr: PHP Warning:  A non-numeric value encountered in /var/www/vhosts/XXX.de/httpdocs/ts3stats/stats/list_rankup.php on line 191
[Fri Mar 02 01:22:44.786313 2018] [fcgid:warn] [pid 19348:tid 140624537814784] [client 66.249.65.94:44582] mod_fcgid: stderr: PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /var/www/vhosts/XXX.de/httpdocs/ts3stats/stats/list_rankup.php on line 191
[Fri Mar 02 01:28:06.667355 2018] [fcgid:warn] [pid 19349:tid 140624558794496] [client 208.110.93.52:48536] mod_fcgid: stderr: PHP Warning:  Division by zero in /var/www/vhosts/XXX.de/httpdocs/ts3stats/stats/list_rankup.php on line 174
[Fri Mar 02 01:28:06.667410 2018] [fcgid:warn] [pid 19349:tid 140624558794496] [client 208.110.93.52:48536] mod_fcgid: stderr: PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /var/www/vhosts/XXX.de/httpdocs/ts3stats/stats/list_rankup.php on line 191
[Fri Mar 02 01:28:38.536109 2018] [fcgid:warn] [pid 19348:tid 140624731514624] [client 208.110.93.52:48780] mod_fcgid: stderr: PHP Warning:  Division by zero in /var/www/vhosts/XXX.de/httpdocs/ts3stats/stats/list_rankup.php on line 174
[Fri Mar 02 01:28:38.536153 2018] [fcgid:warn] [pid 19348:tid 140624731514624] [client 208.110.93.52:48780] mod_fcgid: stderr: PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /var/www/vhosts/XXX.de/httpdocs/ts3stats/stats/list_rankup.php on line 191
[Fri Mar 02 01:29:10.558274 2018] [fcgid:warn] [pid 19349:tid 140624548304640] [client 208.110.93.52:49074] mod_fcgid: stderr: PHP Warning:  Division by zero in /var/www/vhosts/XXX.de/httpdocs/ts3stats/stats/list_rankup.php on line 174
[Fri Mar 02 01:29:10.558314 2018] [fcgid:warn] [pid 19349:tid 140624548304640] [client 208.110.93.52:49074] mod_fcgid: stderr: PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /var/www/vhosts/XXX.de/httpdocs/ts3stats/stats/list_rankup.php on line 189
[Fri Mar 02 01:29:43.533370 2018] [fcgid:warn] [pid 19348:tid 140624537814784] [client 208.110.93.52:49544] mod_fcgid: stderr: PHP Warning:  Division by zero in /var/www/vhosts/XXX.de/httpdocs/ts3stats/stats/list_rankup.php on line 174
[Fri Mar 02 01:29:43.533399 2018] [fcgid:warn] [pid 19348:tid 140624537814784] [client 208.110.93.52:49544] mod_fcgid: stderr: PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /var/www/vhosts/XXX.de/httpdocs/ts3stats/stats/list_rankup.php on line 191
[Fri Mar 02 01:30:16.743315 2018] [fcgid:warn] [pid 19349:tid 140624432916224] [client 208.110.93.52:49682] mod_fcgid: stderr: PHP Warning:  Division by zero in /var/www/vhosts/XXX.de/httpdocs/ts3stats/stats/list_rankup.php on line 174
[Fri Mar 02 01:30:16.743358 2018] [fcgid:warn] [pid 19349:tid 140624432916224] [client 208.110.93.52:49682] mod_fcgid: stderr: PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /var/www/vhosts/XXX.de/httpdocs/ts3stats/stats/list_rankup.php on line 191
[Fri Mar 02 01:30:48.610132 2018] [fcgid:warn] [pid 19349:tid 140624569284352] [client 208.110.93.52:50234] mod_fcgid: stderr: PHP Warning:  Division by zero in /var/www/vhosts/XXX.de/httpdocs/ts3stats/stats/list_rankup.php on line 174

Jemand eine Idee, was das sein kann?

**Comment by PaDo90** [comment]
Niemand eine Idee? Ich muss 1-2 mal am Tag die Log-Datei löschen weil diese einfach mehrere 100 GB groß ist. Es kam sogar schon vor, dass die Dateien so groß waren, dass die Platten vom Server VOLL(!) waren.

**Comment by Shad86** [comment]
Hallo,

entschuldige deine Nachricht ist wohl leider untergegangen.

Diesen Fehler:

> 208.110.93.52:50234] mod_fcgid: stderr: PHP Warning: Division by zero in /var/www/vhosts/XXX.de/httpdocs/ts3stats/stats/list_rankup.php on line 174

Sehe ich zum ersten mal, dass müsste sich vermutlich @Newcomer1989 mal genauer anschauen

Bei diesen Fehler:


 musst du mal schauen ob du eventuell die max execution time etwas heraufsetzen musst.

Setz es mal auf 60 Sekunden (60 Sekunden sind auf jeden fall noch im Rahmen) und beobachte ob diese Meldung weiterhin bleibt oder sich sogar das ganze problem damit löst.

**Comment by Newcomer1989** [comment]
Version 1.2.6 ist nun draußen.. Bitte mal testen, ob das Problem noch besteht.

**Comment by PaDo90** [comment]
Wollte ich gerade machen, allerdings startet der Bot jetzt nicht mehr mit der Fehlermeldung:

> 2018-03-25 16:54:21.234475   CRITICAL  Please check the files pemissions. Shutting down!
> 2018-03-25 16:54:21.232738   WARNING       File is not writeable /var/www/vhosts/gamedcom.de/httpdocs/ts3stats/avatars/pnaodnckacbbejgphmbmdomnmmpclccgkdjiebbj.png
> 2018-03-25 16:54:21.231968   WARNING       File is not writeable /var/www/vhosts/gamedcom.de/httpdocs/ts3stats/avatars/ggmaldfggjopplnjmijcbhaamddlddapgngimmpg.png
> 2018-03-25 16:54:21.231696   WARNING       File is not writeable /var/www/vhosts/gamedcom.de/httpdocs/ts3stats/avatars/ndbjmmhkclobhpgballakhfdlaoglgpegdplnhfi.png
> 2018-03-25 16:54:21.229476   WARNING       File is not writeable /var/www/vhosts/gamedcom.de/httpdocs/ts3stats/avatars/jdphkneciggbmcbnaekfoijfhdgndgeojnknmaco.png
> 2018-03-25 16:54:21.229293   WARNING       File is not writeable /var/www/vhosts/gamedcom.de/httpdocs/ts3stats/avatars/lhbcehcackjmcfjjjalcnnaffhkkepggdmgjkdkm.png
> 2018-03-25 16:54:21.225391   WARNING       File is not writeable /var/www/vhosts/gamedcom.de/httpdocs/ts3stats/avatars/mccekpcdnhoomkoigccnojapldfofjfnmjhfdhhn.png
> 2018-03-25 16:54:21.224004   WARNING       File is not writeable /var/www/vhosts/gamedcom.de/httpdocs/ts3stats/avatars/ickpndoilogofocmfedcekndgnpileijnlndilph.png
> 2018-03-25 16:54:21.223835   WARNING       File is not writeable /var/www/vhosts/gamedcom.de/httpdocs/ts3stats/avatars/cpciifelndacofohbcikciomepbbfdkafgfomgeo.png
> 2018-03-25 16:54:21.221452   WARNING       File is not writeable /var/www/vhosts/gamedcom.de/httpdocs/ts3stats/avatars/bkdgiijahlejckdlhoiepkgafnpepgbdbdncipkp.png

Dabei ist der Ordner "avatars" leer. Hat die Gruppe und Eigentümer "www-data [33]".
chown -R www-data:www-data /var/www/vhosts/gamedcom.de/httpdocs/ts3stats wurde ausgeführt!

**Comment by Shad86** [comment]
ein `chmod 777 avatars/* -Rf` ist auch noch notwendig.

MfG

Shad86

**Comment by PaDo90** [comment]
Hab den Fehler gefunden, ich depp war in der falschen Installation :D SORRY

**Comment by Shad86** [comment]
An sich hast du aber nun keine Fehlermeldungen mehr?

**Comment by PaDo90** [comment]
Doch, leider schon. :/
Das lief jetzt seit Gestern über die ganze Nacht und es wurde wieder ein error_log erstellt,
welche 194 GB groß ist, mit lauter Fehlermeldungen aus dem Ranksystem. Welche Fehlermeldungen das diesmal genau sind, kann ich nicht sagen, da ich so eine große Datei nicht öffnen kann, da hängt sich jegliches Textverarbeitungsprogramm auf.

Das komische ist, selbst wenn ich diese 194 GB große error_log mit "rm error_log" lösche, 
wird kein freier Speicher auf dem Server frei o.O

> root@www:~# cd /var/www/vhosts/gamedcom.de/logs
> root@www:/var/www/vhosts/gamedcom.de/logs# rm error_log
> root@www:/var/www/vhosts/gamedcom.de/logs# df -h
> Filesystem      Size  Used Avail Use% Mounted on
> /dev/vzfs       200G  200G     0 100% /

Die error_log wird bei mir in folgenden Verzeichnisen, erstellt:
/var/www/vhosts/gamedcom.de/logs
/var/www/vhosts/system/gamedcom.de/logs

Warum genau das doppelt ist, kann ich auch nicht sagen. Warum der Speicher nicht frei wird, obwohl die die beiden Files wie oben beschrieben gelöscht habe, kann ich mir auch nicht erklären.

Ich habe eine 200GB Festplatte in dem Server, wenn ich mir alle größen von den Ordnern anzeigen lasse, NACHDEM ich die beiden großen Logdateien gelöscht habe, sieht es wie folgt aus:


> root@www:~# du -sh /*
> 0       /aquota.group
> 0       /aquota.user
> 8.1M    /bin
> 4.0K    /boot
> 140K    /deleted.list
> 0       /dev
> 6.8M    /etc
> 3.2M    /home
> 45M     /lib
> 3.8M    /lib32
> 4.0K    /lib64
> 4.0K    /media
> 4.0K    /mnt
> 977M    /opt
> du: cannot access '/proc/28586/task/28586/fd/4': No such file or directory
> du: cannot access '/proc/28586/task/28586/fdinfo/4': No such file or directory
> du: cannot access '/proc/28586/fd/4': No such file or directory
> du: cannot access '/proc/28586/fdinfo/4': No such file or directory
> 0       /proc
> 34M     /root
> 302M    /run
> 5.0M    /sbin
> 559M    /servers
> 4.0K    /srv
> 0       /sys
> 120K    /tmp
> 1.5G    /usr
> 3.2G    /var

Wenn ich alles zusammen rechne, komme ich doch bei weitem nicht auf 200GB

**Comment by Shad86** [comment]
Hast du 2 ranksysteme am laufen? Weil das Ranksystem selbst erstellt nur eine log und die rotiert mit 5Mb (also nicht wirklich groß)

Ansonsten (da du nicht darauf geantwortet hattest) wäre auch die Frage ob du meinen Kommentar gelesen hast:

https://github.com/Newcomer1989/TSN-Ranksystem/issues/441#issuecomment-375010992

**Comment by PaDo90** [comment]
Nein, habe nur ein Ranksystem am laufen.

Die max execution time steht bei mir sogar auf 120, da dies für Wordpress empfohlen wird.

**Comment by Shad86** [comment]
d.h. das aber dass das eventuell nicht überall greift oder eventuell sogar nur bei Wordpress. Mal eine phpinfo.php erstellt und geschaut ob sich der max execution Wert ändert wenn du ihn anpasst?

Weil die log besagt ja eben, das der max exec nur 30 ist an dem punkt.

**Comment by PaDo90** [comment]
Ja, habe ich: http://prntscr.com/iwom1c
Hier steht auch der richtige Wert (120)

Die phpinfo-Datei liegt im Root-Verzeichsnis der Domain.

**Comment by PaDo90** [comment]
So, ich habe es jetzt mal ganz anders gemacht, ich habe den Kompletten Webspace bzw die komplette Domain wo das Ranksystem läuft aus Plesk entfernt und wieder erneut angelegt, anschließend ein Backup der Homepage-Daten lokal von meinem PC wieder aufgespielt OHNE das Ranksystem.

Habe dann das Ranksystem erneut von eurer Homepage geladen, ohne alte Daten wieder aufzuspielen. Ich habe nicht einmal die install.php oder sonstiges über den Browser aufgerufen, wirklich nur über wget das Ranksystem auf den Server geladen und entpackt.

Und schon wird die access_log mit Inhalt gefüllt:

> 158.69.252.176 - - [26/Mar/2018:21:26:18 +0200] "GET /ts3stats/stats/list_rankup.php?sort=uuid&order=desc&seite=0&user=100&search=filter:lastseen:%3E:1500189424: HTTP/1.0" 301 735 "-" "Mozilla/5.0 (compatible; MJ12bot/v1.4.7; http://mj12bot.com/)"
> 158.69.252.176 - - [26/Mar/2018:21:26:24 +0200] "GET /ts3stats/stats/list_rankup.php?sort=uuid&order=desc&seite=0&user=100&search=filter:lastseen:%3E:1506586079: HTTP/1.0" 301 735 "-" "Mozilla/5.0 (compatible; MJ12bot/v1.4.7; http://mj12bot.com/)"
> 54.36.149.98 - - [26/Mar/2018:21:26:30 +0200] "GET /ts3stats/stats/list_rankup.php?sort=lastseen&order=desc&seite=9&user=100&search=filter:lastseen:>:1490558305: HTTP/1.0" 301 742 "-" "Mozilla/5.0 (compatible; AhrefsBot/5.2; +http://ahrefs.com/robot/)"
> 54.36.148.134 - - [26/Mar/2018:21:26:44 +0200] "GET /ts3stats/stats/list_rankup.php?sort=rank&order=desc&seite=2&user=887&search=filter:lastseen:>:1484498701: HTTP/1.0" 301 734 "-" "Mozilla/5.0 (compatible; AhrefsBot/5.2; +http://ahrefs.com/robot/)"
> 158.69.252.176 - - [26/Mar/2018:21:26:46 +0200] "GET /ts3stats/stats/list_rankup.php?sort=uuid&order=desc&seite=0&user=100&search=filter:lastseen:%3E:1506586083: HTTP/1.0" 301 735 "-" "Mozilla/5.0 (compatible; MJ12bot/v1.4.7; http://mj12bot.com/)"
> 158.69.252.176 - - [26/Mar/2018:21:27:11 +0200] "GET /ts3stats/stats/list_rankup.php?sort=uuid&order=desc&seite=0&user=100&search=filter:lastseen:%3E:1506949521: HTTP/1.0" 301 735 "-" "Mozilla/5.0 (compatible; MJ12bot/v1.4.7; http://mj12bot.com/)"
> 158.69.252.176 - - [26/Mar/2018:21:27:26 +0200] "GET /ts3stats/stats/list_rankup.php?sort=uuid&order=desc&seite=0&user=100&search=filter:lastseen:%3E:1507104479: HTTP/1.0" 301 735 "-" "Mozilla/5.0 (compatible; MJ12bot/v1.4.7; http://mj12bot.com/)"
> 158.69.252.176 - - [26/Mar/2018:21:27:43 +0200] "GET /ts3stats/stats/list_rankup.php?sort=uuid&order=desc&seite=0&user=100&search=filter:lastseen:%3E:1507119192: HTTP/1.0" 301 735 "-" "Mozilla/5.0 (compatible; MJ12bot/v1.4.7; http://mj12bot.com/)"
> 158.69.252.176 - - [26/Mar/2018:21:27:49 +0200] "GET /ts3stats/stats/list_rankup.php?sort=uuid&order=desc&seite=0&user=100&search=filter:lastseen:%3E:1507119194: HTTP/1.0" 301 735 "-" "Mozilla/5.0 (compatible; MJ12bot/v1.4.7; http://mj12bot.com/)"
> 158.69.252.176 - - [26/Mar/2018:21:27:56 +0200] "GET /ts3stats/stats/list_rankup.php?sort=uuid&order=desc&seite=0&user=100&search=filter:lastseen:%3E:1507467921: HTTP/1.0" 301 735 "-" "Mozilla/5.0 (compatible; MJ12bot/v1.4.7; http://mj12bot.com/)"
> 158.69.252.176 - - [26/Mar/2018:21:28:05 +0200] "GET /ts3stats/stats/list_rankup.php?sort=uuid&order=desc&seite=0&user=100&search=filter:lastseen:%3E:1509420202: HTTP/1.0" 301 735 "-" "Mozilla/5.0 (compatible; MJ12bot/v1.4.7; http://mj12bot.com/)"
> 158.69.252.176 - - [26/Mar/2018:21:28:12 +0200] "GET /ts3stats/stats/list_rankup.php?sort=uuid&order=desc&seite=0&user=100&search=filter:lastseen:%3E:1509712072: HTTP/1.0" 301 735 "-" "Mozilla/5.0 (compatible; MJ12bot/v1.4.7; http://mj12bot.com/)"
> 158.69.252.176 - - [26/Mar/2018:21:28:23 +0200] "GET /ts3stats/stats/list_rankup.php?sort=uuid&order=desc&seite=0&user=100&search=filter:lastseen:%3E:1509712073: HTTP/1.0" 301 735 "-" "Mozilla/5.0 (compatible; MJ12bot/v1.4.7; http://mj12bot.com/)"
> 158.69.252.176 - - [26/Mar/2018:21:28:28 +0200] "GET /ts3stats/stats/list_rankup.php?sort=uuid&order=desc&seite=0&user=100&search=filter:lastseen:%3E:1509712075: HTTP/1.0" 301 735 "-" "Mozilla/5.0 (compatible; MJ12bot/v1.4.7; http://mj12bot.com/)"
> 158.69.252.176 - - [26/Mar/2018:21:28:33 +0200] "GET /ts3stats/stats/list_rankup.php?sort=uuid&order=desc&seite=0&user=100&search=filter:lastseen:%3E:1510402183: HTTP/1.0" 301 735 "-" "Mozilla/5.0 (compatible; MJ12bot/v1.4.7; http://mj12bot.com/)"
> 158.69.252.176 - - [26/Mar/2018:21:28:40 +0200] "GET /ts3stats/stats/list_rankup.php?sort=uuid&order=desc&seite=0&user=100&search=filter:lastseen:%3E:1510402185: HTTP/1.0" 301 735 "-" "Mozilla/5.0 (compatible; MJ12bot/v1.4.7; http://mj12bot.com/)"
> 158.69.252.176 - - [26/Mar/2018:21:28:48 +0200] "GET /ts3stats/stats/list_rankup.php?sort=uuid&order=desc&seite=0&user=100&search=filter:lastseen:%3E:1510402189: HTTP/1.0" 301 735 "-" "Mozilla/5.0 (compatible; MJ12bot/v1.4.7; http://mj12bot.com/)"
> 158.69.252.176 - - [26/Mar/2018:21:28:56 +0200] "GET /ts3stats/stats/list_rankup.php?sort=uuid&order=desc&seite=0&user=100&search=filter:lastseen:%3E:1510920583: HTTP/1.0" 301 735 "-" "Mozilla/5.0 (compatible; MJ12bot/v1.4.7; http://mj12bot.com/)"
> 158.69.252.176 - - [26/Mar/2018:21:29:02 +0200] "GET /ts3stats/stats/list_rankup.php?sort=uuid&order=desc&seite=0&user=100&search=filter:lastseen:%3E:1510920585: HTTP/1.0" 301 735 "-" "Mozilla/5.0 (compatible; MJ12bot/v1.4.7; http://mj12bot.com/)"
> 158.69.252.176 - - [26/Mar/2018:21:29:46 +0200] "GET /ts3stats/stats/list_rankup.php?sort=uuid&order=desc&seite=0&user=100&search=filter:lastseen:%3E:1510920589: HTTP/1.0" 301 735 "-" "Mozilla/5.0 (compatible; MJ12bot/v1.4.7; http://mj12bot.com/)"
> 158.69.252.176 - - [26/Mar/2018:21:29:56 +0200] "GET /ts3stats/stats/list_rankup.php?sort=uuid&order=desc&seite=0&user=100&search=filter:lastseen:%3E:1512303191: HTTP/1.0" 301 735 "-" "Mozilla/5.0 (compatible; MJ12bot/v1.4.7; http://mj12bot.com/)"
> 
Die IP am Anfang ist mir nicht bekannt. IP Lookup sagt mir die IP kommt aus Canada von "OVH Hosting, Inc." Aber warum versucht diese IP ständig auf die Seite zuzugreifen? o.O

**Comment by Shad86** [comment]
ahrefs docu:

> If for some reason you want to prevent AhrefsBot from visiting your site, put the two following lines into the robots.txt file on your server:
```
User-agent: AhrefsBot 
Disallow: /
```

**Comment by Shad86** [comment]
Also - ich habe nun auch mal etwas herumprobiert

.htaccess funktioniert aber sie muss genau in dem Ordner liegen wo der Bot crawled - dann klappt es

Also in deinem Fall müsste die .htaccess file hier liegen:

`ts3stats/stats/list_rankup.php`

mit diesem Inhalt:

```
SetEnvIfNoCase User-agent (mj12bot|ahrefs) not-allowed=1

Order Allow,Deny
Allow from ALL
Deny from env=not-allowed
```

**Comment by PaDo90** [comment]
So, ich habe jetzt folgendes gemacht:

im Hauptverzeichnis der Domain eine .htaccess mit folgendem Inhalt:

```
SetEnvIfNoCase User-agent (mj12bot|ahrefs) not-allowed=1

Order Allow,Deny
Allow from ALL
Deny from env=not-allowed
```
Zusätzlich noch eine robots.txt mit dem Inhalt:

```
User-agent: MJ12bot
Disallow: /

User-agent: ahrefs
Disallow: /
```
Und nochmal eine robots.txt im Verzeichnis wo die index.php von dem Ranksystem liegt mit dem Inhalt:

```
User-agent: *
Disallow: /
```

Bin mal gespannt ob jetzt noch ständig Einträge rein kommen. Ich werde die Log-Dateien mal beobachten und sollte dort eine IP eines Bots häufiger auftreten, werde ich diese mittels iptables ausschließen.

Habe übrigens das Ranksystem nochmal komplett neu installiert und der Anfangsfehler mit der error_log scheint nun gelöst zu sein. Es ist zwar schade um die ganzen gesammelten Statistiken aber ich weiß leider nicht wie ich das Datenbank Backup einspielen kann, da ich nur ein Backup der gesamten Datenbank habe und wenn ich das einspiele, startet der Bot nicht, auch wenn alle Daten gleich sind wie jetzt :/

**Comment by Newcomer1989** [comment]
Ein DB restore sollte ohne Probleme möglich sein, selbst wenn das älter wäre als die aktuelle Version, die du von unserer Page beziehst.
Hier ein Eintrag aus unserem Wiki, was zu beachten ist -> https://github.com/Newcomer1989/TSN-Ranksystem/wiki#changed-teamspeak-host--server---mitigation-old-ranksystem

**Comment by Newcomer1989** [comment]
Wenn ich es richtig sehe, ist das ursprüngliche Problem geklärt und es ist bekannt, wie es behoben werden kann.
Am Ranksystem kann bzw. sollte meiner Meinung nach nichts geändert werden diesbezüglich.
Falls noch Probleme bestehen sollten bitte den Issue wieder öffnen bzw. einen neuen aufmachen.
