### ISSUE TITLE
Rankingsystem Bot startet nicht

### ISSUE THREAD

**Issue by TheViech** [Newcomer1989/TSN-Ranksystem#442]
Guten Tag.

Ich habe ein Problem mit der Installation des TSN Ranksystems.
Die Installation des Webinterfaces war erfolgreich.
Doch beim einstellen der "Kern-Einstellungen" wird mir nach dem drücken der "speichern" Taste die Fehlermeldung "**Array ( [0] => 42S22 [1] => 1054 [2] => Unknown column 'registercid' in 'field list' )** " angezeicht.
Wenn ich dann trotzdem versuche den Bot zu starten passiert nichts.
Ich habe dann ein bischen nachgeforscht und den Debug modus aktiviert.
Dadurch wird die Fehlermeldung " **Request to start the Ranksystem from ::1. It seems the request came not from the command line! Shutting down!**" angezeigt.

Meine Systeme sind:
V-Server von Hosteurope mit Windows Server 2012 R2
Für die Datenbank habe ich XAMPP Control Panel v3.2.2 benutzt

Ich bedanke mich im Vorhinein für eine Antwort

**Comment by Shad86** [comment]
Dieser Kommentar sollte dir helfen, denke ich :) -> https://github.com/Newcomer1989/TSN-Ranksystem/issues/408#issuecomment-365919838

**Comment by TheViech** [comment]
Leider hat es bei mir nicht funktioniert. Ich habe die Rankup definition erfolgreich verändert allerdings will der Bot immernoch nicht starten und jetzt wird auch keine Fehlermeldung im Log angezeitgt.
Meine Vermutung ist, dass der Bot nichteinmal den Server findet da auf der Seite mit den Server Statistiken das hir steht.
![grafik](https://user-images.githubusercontent.com/37024355/36945135-9e035b78-1fa9-11e8-83b8-0d3a9b55dc31.png)

Ich habe jetzt mal den ganzen Bot neu intalliert mit der Version 1.2.5 und es geht immernoch nichts.
falls es in irgendeiner Weise hilft sind hir noch meine Daten von phpMyAdmin:
![grafik](https://user-images.githubusercontent.com/37024355/36945163-24c43952-1faa-11e8-8bea-46e4714df866.png)

**Comment by Shad86** [comment]
Dann mal hier drüber schauen, da du Windows nutzt -> https://github.com/Newcomer1989/TSN-Ranksystem/wiki/Bot-not-starting---Windows

**Comment by TheViech** [comment]
Ich habe alle Schritte befolgt:
1.) Funktioniert einwandfrei.
2.) COM ist auch aktiviert.
3.) Exec ist auch aktiviert.
4.) Ich nutze XAMPP und nicht Plesk also fällt das auch weg.
5.) Ich habe dort allen Gruppen/Usernamen Follen Zugriff gegeben
     ![grafik](https://user-images.githubusercontent.com/37024355/36950708-4dd053bc-1ffa-11e8-8437-e936c8361f3f.png)
6.) Wenn ich die jobs/bot.php datei starte kommt bei mir nur " **#!/usr/bin/php**  "
     Und wenn ich dann versuche den Bot zu starten kommt im log:
     ![grafik](https://user-images.githubusercontent.com/37024355/36950721-9c4ee3aa-1ffa-11e8-80b4-31b09cbf1e07.png)

**Comment by Newcomer1989** [comment]
Wie startest du den Bot?

Der Aufruf über den Browser auf die jobs/bot.php ist falsch!

**Comment by TheViech** [comment]
Ich starte den Bot über das Webinterface.

**Comment by Newcomer1989** [comment]
Was steht denn in deiner `other/phpcommand.php`?

Dort ist im Standard der Befehl "php" aktiv. Ist dieser auf deinem Server überhaupt verfügbar? Oder müsste dort nicht eher der korrekte Pfad zu deiner php.exe rein? Ein Beispiel für Windows befindet sich auch in der Datei.

**Comment by Newcomer1989** [comment]
Sollte mit vorgenannten Punk funktionieren. Ansonsten müssten wir uns das mal gemeinsam via Fernwartung anschauen. Dafür einfach mal auf unserem public TS (ts-n.net) wegen einem Termin melden.
