### ISSUE TITLE
Kann keine Zeit zu User hinzufügen

### ISSUE THREAD

**Issue by Saidyra** [Newcomer1989/TSN-Ranksystem#447]
Leider kann ich seit kurzem keine Zeit mehr zu einem User hinzufügen.
Das System sagt zwar, dass die Zeit erfolgreich hinzugefügt wurde, die Datenbank ändert sich allerdings nicht.
Der User auf der Datenbank hat kompletten Zugriff, sollte also reichen.
Kann mir da jemand weiterhelfen?

**Comment by Shad86** [comment]
Hier müsstest du wohl kurz das ranksystem ausschalten dann den user auswählen welchem du die zeit hinzufügen möchtest und dann wieder starten.

Wir schauen uns das an und versuchen das natürlich zeitnah wieder so umzusetzen, das man nicht dafür das ranksystem stoppen muss

**Comment by Newcomer1989** [comment]
solved with release version 1.2.7
