### ISSUE TITLE
Will svg icons be supported?

### ISSUE THREAD

**Issue by Forge-Media** [Newcomer1989/TSN-Ranksystem#449]
Hi, very nice panel!

Since Teamspeak 3 provided support for .svg icons (_in v 3.1.5 I think_) we've been updating many of the icons on our server to .svg to support hi-resolution monitors. The TSN-Ranksystem successfully gets the .svg icons from our server but it stores them as .pngs in /tsicons/

This results in group icons not displaying on the TSN-Ranksystem panel such as our server icon and icons on the Assign Servergroups Addon.

Just interested if this would ever be something that would be supported?

**Comment by Newcomer1989** [comment]
I will have a look on it.. If I can reproduce it, I will try to fix it with the next release 1.2.7

**Comment by Newcomer1989** [comment]
It is a longer time ago... but now we support all official supported file types by TeamSpeak.

It is part of the current beta of 1.3.8.
