### ISSUE TITLE
stats/index.php  Undefined index: REMOTE_ADDR

### ISSUE THREAD

**Issue by NimaGame** [Newcomer1989/TSN-Ranksystem#45]
Hi.
I'm getting this error when I open /stats/ and that page wont open.

```
PHP Notice:  Undefined index: REMOTE_ADDR in /home/nimagame/www/ranksystem/stats/index.php on line 17
PHP Fatal error:  Call to a member function fetchAll() on a non-object in /home/nimagame/www/ranksystem/other/session.php on line 1
```

or list_rankup.php 

```
PHP Notice:  Undefined index: REMOTE_ADDR in /home/nimagame/www/ranksystem/stats/list_rankup.php on line 9
PHP Fatal error:  Call to a member function fetchAll() on a non-object in /home/nimagame/www/ranksystem/other/session.php on line 1
```
Please help me.
Thank you.

**Comment by Newcomer1989** [comment]
Please do not open the stats page via command line.

The Website visitor tell his IP address. This address will be used to match it with the TeamSpeak clients.

There are two ways, you get this error:

1) You opened the file via command line. -> Ple

**Comment by NimaGame** [comment]
When I open the stats page in my browser , I just see a white page.
https://i.imgsafe.org/0ad5c90.png

**Comment by Newcomer1989** [comment]
Then please check 2)

You need the string _SERVER["REMOTE_ADDR"] in your PHP Variables!

**Comment by NimaGame** [comment]
Where is 2) ?
how?

**Comment by CosmoAbdon** [comment]
What version of PHP you are using ?

try upgrade to 5.4, works for me.

**Comment by NimaGame** [comment]
5.4.45 . . .

**Comment by Newcomer1989** [comment]
still not respond

**Comment by Newcomer1989** [comment]
> Then please check 2)
> 
> You need the string _SERVER["REMOTE_ADDR"] in your PHP Variables!

still no respond.. What was the result of your check?

**Comment by NimaGame** [comment]
my current bot's version is 1.0.2-dev.
My php version is : 5.4.45

> You need the string _SERVER["REMOTE_ADDR"] in your PHP Variables!

how?

**Comment by CosmoAbdon** [comment]
try create a info.php in your server with this code

`<?php`
`phpinfo();`
`?>`

So use ctrl+f : and put "REMOTE_ADDR" on your text box search.
So u can see if have something defined.

After that, try change in your code ...

Original : 
`$_SERVER['REMOTE_ADDR']);`

Change test 1 :

`$_SERVER["HTTP_REMOTE_ADDR"];`

save this file, and reload this page. If not works try the second change ..

Change test 2 : 

`$SERVER['REMOTE_ADDR']);`

Try like that .. just a little change to your variable to global not superglobal ..

report your results

**Comment by NimaGame** [comment]
> try create a info.php in your server with this code

<?php
phpinfo();
?>

So use ctrl+f : and put "REMOTE_ADDR" on your text box search.
So u can see if have something defined.

Yes , I found it.

> After that, try change in your code ...

Original :
$_SERVER['REMOTE_ADDR']);

Change test 1 :

$_SERVER["HTTP_REMOTE_ADDR"];

save this file, and reload this page. If not works try the second change ..

Change test 2 :

$SERVER['REMOTE_ADDR']);

Try like that .. just a little change to your variable to global not superglobal ..

report your results

Didn't work for me.

**Comment by Newcomer1989** [comment]
So you find it, ok.

But what's the value, which is standing on the php info page for the string REMOTE_ADDR?

**Comment by NimaGame** [comment]
![cadpture](https://cloud.githubusercontent.com/assets/16646645/15571802/313573b4-2352-11e6-8179-9a4d2b83d256.PNG)

**Comment by Newcomer1989** [comment]
Try to make a PHP File with the following.

What output you get?

```
<?PHP
var_dump($_SERVER);
?>
```

**Comment by NimaGame** [comment]
array(33) { ["USER"]=> string(7) "webuser" ["HOME"]=> string(13) "/home/nimagame" ["FCGI_ROLE"]=> string(9) "RESPONDER" ["SCRIPT_FILENAME"]=> string(26) "/home/nimagame/www/info.php" ["QUERY_STRING"]=> string(0) "" ["REQUEST_METHOD"]=> string(3) "GET" ["CONTENT_TYPE"]=> string(0) "" ["CONTENT_LENGTH"]=> string(0) "" ["SCRIPT_NAME"]=> string(9) "/info.php" ["REQUEST_URI"]=> string(9) "/info.php" ["DOCUMENT_URI"]=> string(9) "/info.php" ["DOCUMENT_ROOT"]=> string(17) "/home/nimagame/www" ["SERVER_PROTOCOL"]=> string(8) "HTTP/1.1" ["GATEWAY_INTERFACE"]=> string(7) "CGI/1.1" ["SERVER_SOFTWARE"]=> string(11) "nginx/1.2.1" ["REMOTE_ADDR"]=> string(13) "151.*.*.*" ["REMOTE_PORT"]=> string(5) "39501" ["SERVER_ADDR"]=> string(14) "158.*.*.*" ["SERVER_PORT"]=> string(2) "80" ["SERVER_NAME"]=> string(14) "****.com" ["HTTPS"]=> string(0) "" ["REDIRECT_STATUS"]=> string(3) "200" ["HTTP_HOST"]=> string(17) "ts.****.com" ["HTTP_USER_AGENT"]=> string(77) "Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:46.0) Gecko/20100101 Firefox/46.0" ["HTTP_ACCEPT"]=> string(63) "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8" ["HTTP_ACCEPT_LANGUAGE"]=> string(14) "en-US,en;q=0.5" ["HTTP_ACCEPT_ENCODING"]=> string(13) "gzip, deflate" ["HTTP_COOKIE"]=> string(83) "JTS3ServerModWebUI=pknejthjq5d8n5evhefc70rh86; PHPSESSID=02vsdtas0eb67n0nhq4oc13fu2" ["HTTP_PRAGMA"]=> string(8) "no-cache" ["HTTP_CACHE_CONTROL"]=> string(8) "no-cache" ["PHP_SELF"]=> string(9) "/info.php" ["REQUEST_TIME_FLOAT"]=> float(1464525653.9529) ["REQUEST_TIME"]=> int(1464525653) }

**Comment by Newcomer1989** [comment]
I can't solve this problem on this way. There must be changed anything, which you don't tell us.

If you agree, I can try to debug your problem via remote session. For this contact me on the TeamSpeak (address: ts3server://ts-n.net)

**Comment by Newcomer1989** [comment]
Closed due no response
