### ISSUE TITLE
Reflected XSS in list_rankup.php

### ISSUE THREAD

**Issue by JVMerkle** [Newcomer1989/TSN-Ranksystem#451]
list_rankup.php encoded keine special Chars

Bsp: (Tested with Firefox)
[Reflected JS alert](https://ts-n.net/ranksystem_dev/stats/list_rankup.php?sort=lastseen&order=desc&seite=4&user=25&search=%22%3E%3Cscript%3Ealert(%27hi%27);%3C/script%3E)

Refl. XSS wird bei Chrome meist durch den Auditor geblockt. Inwieweit der sich austricksen lässt weiß ich nicht.

**Comment by Newcomer1989** [comment]
Auch das wird mit der nächsten Version bereinigt.

**Comment by Newcomer1989** [comment]
Sollte mit Version 1.2.6 behoben sein.

Falls es noch Probleme geben sollte, bitte noch einmal bescheid geben oder gerne auch einen pull request erstellen.
