### ISSUE TITLE
Fehler in der Config?

### ISSUE THREAD

**Issue by DZPhoenix** [Newcomer1989/TSN-Ranksystem#454]
Ich bekomme nach der Installation folgenden Fehler: **Fatal error: Uncaught Error: Call to a member function fetch() on boolean in /var/www/vhosts/deutschland-zockt.net/ranksystem.deutschland-zockt.net/other/config.php:51 Stack trace: #0 /var/www/vhosts/deutschland-zockt.net/ranksystem.deutschland-zockt.net/stats/index.php(3): require_once() #1 {main} thrown in /var/www/vhosts/deutschland-zockt.net/ranksystem.deutschland-zockt.net/other/config.php on line 51**

Weiß jemand zufällig, wie ich den Fehler beheben kann?

**Comment by Shad86** [comment]
Das würde zumindest in Zeile 51 stehen:

if (isset($mysqlcon) && ($config = $mysqlcon->query("SELECT * FROM config")->fetch())) {

wenn man dort weiter liest sieht man das er da die ts3 config zieht.

Vermute das entweder diese Daten Fehlerhaft sind oder keine Daten eingetragen sind.

**Comment by Shad86** [comment]
Wenn das alles nicht zutrifft, würde ich dich noch bitten eine neuinstallation zu versuchen um diesen Fehler mit auszuschließen (das die Installation eventuell Fehlerhaft ist)

**Comment by DZPhoenix** [comment]
`if (isset($mysqlcon) && ($config = $mysqlcon->query("SELECT * FROM config")->fetch())) {
	if(count($config) != 0) {
		$ts['host']      = $config['tshost'];
		$ts['query']     = $config['tsquery'];
		$ts['voice']     = $config['tsvoice'];
		$ts['user']      = $config['tsuser'];
		$ts['pass']      = $config['tspass'];
		$webuser         = $config['webuser'];
		$webpass         = $config['webpass'];`

Hätte ich dort etwas eintragen müssen? Denn die Installation habe ich gestern gemacht und nachdem ich die Datenbankverbindung angegeben habe, trat dann dieser Fehler auf...

**Comment by DZPhoenix** [comment]
Habe die Installation nochmal gemacht und nun scheint es zu funktionieren. Ich danke dir aber trotzdem ^^
