### ISSUE TITLE
Ranking läuft nur noch in notizen

### ISSUE THREAD

**Issue by chris031992** [Newcomer1989/TSN-Ranksystem#455]
> 2018-03-15 23:49:04.487433   NOTICE    Überprüfung der Datenbankbereinigung abgeschlossen. Alle unnötigen Daten wurden gelöscht.
> 2018-03-15 23:49:04.487334   NOTICE    Überprüfung der zu löschenden User abgeschlossen. Nichs wurde getan, da die Funktion 'Clientlöschung' deaktiviert ist (Webinterface - Kern).
> 2018-03-15 23:49:03.052381   NOTICE    Überprüfung der Datenbankbereinigung abgeschlossen. Alle unnötigen Daten wurden gelöscht.
> 2018-03-15 23:49:03.052273   NOTICE    Überprüfung der zu löschenden User abgeschlossen. Nichs wurde getan, da die Funktion 'Clientlöschung' deaktiviert ist (Webinterface - Kern).
> 2018-03-15 23:49:01.661984   NOTICE    Überprüfung der Datenbankbereinigung abgeschlossen. Alle unnötigen Daten wurden gelöscht.
> 2018-03-15 23:49:01.661872   NOTICE    Überprüfung der zu löschenden User abgeschlossen. Nichs wurde getan, da die Funktion 'Clientlöschung' deaktiviert ist (Webinterface - Kern).
> 2018-03-15 23:49:00.279313   NOTICE    Überprüfung der Datenbankbereinigung abgeschlossen. Alle unnötigen Daten wurden gelöscht.
> 2018-03-15 23:49:00.279198   NOTICE    Überprüfung der zu löschenden User abgeschlossen. Nichs wurde getan, da die Funktion 'Clientlöschung' deaktiviert ist (Webinterface - Kern).
> 2018-03-15 23:48:58.849760   NOTICE    Überprüfung der Datenbankbereinigung abgeschlossen. Alle unnötigen Daten wurden gelöscht.
> 2018-03-15 23:48:58.849651   NOTICE    Überprüfung der zu löschenden User abgeschlossen. Nichs wurde getan, da die Funktion 'Clientlöschung' deaktiviert ist (Webinterface - Kern).
> 2018-03-15 23:48:57.265920   NOTICE    Überprüfung der Datenbankbereinigung abgeschlossen. Alle unnötigen Daten wurden gelöscht.
> 2018-03-15 23:48:57.265772   NOTICE    Überprüfung der zu löschenden User abgeschlossen. Nichs wurde getan, da die Funktion 'Clientlöschung' deaktiviert ist (Webinterface - Kern).
> 2018-03-15 23:48:55.950892   NOTICE    Überprüfung der Datenbankbereinigung abgeschlossen. Alle unnötigen Daten wurden gelöscht.
> 2018-03-15 23:48:55.950764   NOTICE    Überprüfung der zu löschenden User abgeschlossen. Nichs wurde getan, da die Funktion 'Clientlöschung' deaktiviert ist (Webinterface - Kern).
> 2018-03-15 23:48:54.598352   NOTICE    Überprüfung der Datenbankbereinigung abgeschlossen. Alle unnötigen Daten wurden gelöscht.
> 2018-03-15 23:48:54.598233   NOTICE    Überprüfung der zu löschenden User abgeschlossen. Nichs wurde getan, da die Funktion 'Clientlöschung' deaktiviert ist (Webinterface - Kern).
> 2018-03-15 23:48:53.203576   NOTICE    Überprüfung der Datenbankbereinigung abgeschlossen. Alle unnötigen Daten wurden gelöscht.
> 2018-03-15 23:48:53.203475   NOTICE    Überprüfung der zu löschenden User abgeschlossen. Nichs wurde getan, da die Funktion 'Clientlöschung' deaktiviert ist (Webinterface - Kern).
> 2018-03-15 23:48:51.856093   NOTICE    Überprüfung der Datenbankbereinigung abgeschlossen. Alle unnötigen Daten wurden gelöscht.
> 2018-03-15 23:48:51.855980   NOTICE    Überprüfung der zu löschenden User abgeschlossen. Nichs wurde getan, da die Funktion 'Clientlöschung' deaktiviert ist (Webinterface - Kern).
> 2018-03-15 23:48:50.454884   NOTICE    Überprüfung der Datenbankbereinigung abgeschlossen. Alle unnötigen Daten wurden gelöscht.
> 2018-03-15 23:48:50.454778   NOTICE    Überprüfung der zu löschenden User abgeschlossen. Nichs wurde getan, da die Funktion 'Clientlöschung' deaktiviert ist (Webinterface - Kern).
> 2018-03-15 23:48:49.046612   NOTICE    Überprüfung der Datenbankbereinigung abgeschlossen. Alle unnötigen Daten wurden gelöscht.
> 2018-03-15 23:48:49.046445   NOTICE    Überprüfung der zu löschenden User abgeschlossen. Nichs wurde getan, da die Funktion 'Clientlöschung' deaktiviert ist (Webinterface - Kern).
> 2018-03-15 23:48:47.650012   NOTICE    Überprüfung der Datenbankbereinigung abgeschlossen. Alle unnötigen Daten wurden gelöscht.
> 2018-03-15 23:48:47.649866   NOTICE    Überprüfung der zu löschenden User abgeschlossen. Nichs wurde getan, da die Funktion 'Clientlöschung' deaktiviert ist (Webinterface - Kern).
> 2018-03-15 23:48:46.189927   NOTICE    Überprüfung der Datenbankbereinigung abgeschlossen. Alle unnötigen Daten wurden gelöscht.
> 2018-03-15 23:48:46.189833   NOTICE    Überprüfung der zu löschenden User abgeschlossen. Nichs wurde getan, da die Funktion 'Clientlöschung' deaktiviert ist (Webinterface - Kern).
> 2018-03-15 23:48:44.855779   NOTICE    Überprüfung der Datenbankbereinigung abgeschlossen. Alle unnötigen Daten wurden gelöscht.
> 2018-03-15 23:48:44.855610   NOTICE    Überprüfung der zu löschenden User abgeschlossen. Nichs wurde getan, da die Funktion 'Clientlöschung' deaktiviert ist (Webinterface - Kern).
> 2018-03-15 23:48:43.437076   NOTICE    Überprüfung der Datenbankbereinigung abgeschlossen. Alle unnötigen Daten wurden gelöscht.
> 2018-03-15 23:48:43.436941   NOTICE    Überprüfung der zu löschenden User abgeschlossen. Nichs wurde getan, da die Funktion 'Clientlöschung' deaktiviert ist (Webinterface - Kern).
> 2018-03-15 23:48:42.097228   NOTICE    Überprüfung der Datenbankbereinigung abgeschlossen. Alle unnötigen Daten wurden gelöscht.
> 2018-03-15 23:48:42.097111   NOTICE    Überprüfung der zu löschenden User abgeschlossen. Nichs wurde getan, da die Funktion 'Clientlöschung' deaktiviert ist (Webinterface - Kern).
> 2018-03-15 23:48:40.773363   NOTICE    Überprüfung der Datenbankbereinigung abgeschlossen. Alle unnötigen Daten wurden gelöscht.
> 2018-03-15 23:48:40.773241   NOTICE    Überprüfung der zu löschenden User abgeschlossen. Nichs wurde getan, da die Funktion 'Clientlöschung' deaktiviert ist (Webinterface - Kern).
> 2018-03-15 23:48:39.395017   NOTICE    Überprüfung der Datenbankbereinigung abgeschlossen. Alle unnötigen Daten wurden gelöscht.
> 2018-03-15 23:48:39.394824   NOTICE    Überprüfung der zu löschenden User abgeschlossen. Nichs wurde getan, da die Funktion 'Clientlöschung' deaktiviert ist (Webinterface - Kern).
> 2018-03-15 23:48:34.333029   INFO      Bot starts now his work!
> 2018-03-15 23:48:34.332902   INFO        Joined to specified Channel.
> 2018-03-15 23:48:34.324870   INFO        Connection to TS3 Server established.
> 2018-03-15 23:48:34.251781   INFO      Connect to TS3 Server (Address: "-----------" Voice-Port: "" Query-Port: "------").
> 2018-03-15 23:48:34.251746   INFO      Loading addons [done]
> 2018-03-15 23:48:34.251696   INFO        Addon: 'assign_groups' [OFF]
> 2018-03-15 23:48:34.251379   INFO      Loading addons...
> 2018-03-15 23:48:34.251327   INFO        Config check [done]
> 2018-03-15 23:48:34.250889   INFO        Config check started...
> 2018-03-15 23:48:34.250826   INFO      Ranksystem Version: 1.2.5
> 2018-03-15 23:48:34.250760   INFO        Check files permissions [done]
> 2018-03-15 23:48:34.243598   INFO        Check files permissions...
> 2018-03-15 23:48:34.243240   INFO        No newer version detected; Database check finished.
> 2018-03-15 23:48:34.243187   INFO      Check Ranksystem database for updates.
> 2018-03-15 23:48:34.243152   DEBUG     Database Version: 5.7.20-0ubuntu0.17.04.1
> 2018-03-15 23:48:34.243113   DEBUG     Using PHP Version: 7.0.22-0ubuntu0.17.04.1
> 2018-03-15 23:48:34.243049   DEBUG     Running on OS: Linux 4.10.0-42-generic
> 2018-03-15 23:48:34.239107   INFO      Initialize Bot...
> 
Das  problem ist das er immer und immer wieder prüft obwohl er das nur jeden tag machen soll und das deleten auch aus ist. Es lief echt monate ohne probleme und nun geht garnix mehr und die leute auf dem server, also die rund 7k user sind etwas verärgert XD und ich kann denen nicht helfen weil ich nicht weiss warum der bot auf einmal immer wieder wiederholt. stell ich auf, das er löschen kann tut er es und dann gehts wieder los er sucht seine 5 min und dann deletet er dann sucht er wieder ....... teufelskreis

**Comment by chris031992** [comment]
**brauchen dringenst hilfe bzw. das diese schleife unterbunden wird! der bot tut nix anderes wärend er die user prüft was er aber ja garnicht machen soll laut webinterface einstellung**

**Comment by chris031992** [comment]
> > 2018-03-16 16:26:57.181392   NOTICE    Scanne nach Usern, welche zu löschen sind...
> 2018-03-16 16:26:55.766625   NOTICE    Überprüfung der Datenbankbereinigung abgeschlossen. Alle unnötigen Daten wurden gelöscht.
> 2018-03-16 16:26:55.766506   NOTICE      Es wurden 3 Clients aus der Ranksystem-Datenbank gelöscht, da sie nicht mehr in der TeamSpeak Datenbank vorhanden sind.
> 2018-03-16 16:26:55.763408   NOTICE      Clients in der Ranksystem Datenbank: 5218
> 2018-03-16 16:26:55.763087   NOTICE      Clients in der TeamSpeak Datenbank gefunden: 5215 (von 7679)
> 2018-03-16 16:25:00.565760   NOTICE    Scanne nach Usern, welche zu löschen sind...
> 2018-03-16 16:24:59.044263   NOTICE    Überprüfung der Datenbankbereinigung abgeschlossen. Alle unnötigen Daten wurden gelöscht.
> 2018-03-16 16:24:59.044183   NOTICE      Es wurden 3 Clients aus der Ranksystem-Datenbank gelöscht, da sie nicht mehr in der TeamSpeak Datenbank vorhanden sind.
> 2018-03-16 16:24:59.041109   NOTICE      Clients in der Ranksystem Datenbank: 5218
> 2018-03-16 16:24:59.040814   NOTICE      Clients in der TeamSpeak Datenbank gefunden: 5215 (von 7679)
> 2018-03-16 16:23:04.731361   NOTICE    Scanne nach Usern, welche zu löschen sind...
> 2018-03-16 16:22:59.663214   INFO      Bot starts now his work!
> 2018-03-16 16:22:59.663149   INFO        Joined to specified Channel.
> 2018-03-16 16:22:59.654763   INFO        Connection to TS3 Server established.

**Comment by Shad86** [comment]
Momentan befindet sich das Ranksystem schon im abschluss der nächsten Version, wodurch wir deinen Fehler zwar anschauen können aber erst mit der übernächsten Version beheben, können falls es tatsächlich ein Fehler des Ranksystems sein sollte.

Wann hättest du denn Zeit, das man sich mal auf dem TS3 treffen kann?

**Comment by chris031992** [comment]
also ich hätte heute noch oder morgen zeit auch bis spät in die nacht ^^ sag einfach deine ts daten und uhrzeit ich komm dann drauf.

**Comment by chris031992** [comment]
der fehler ist nun weg... warum auch immer. Wir haben keinen serverrestart oder irgendwas getan ich hab nur als wenig leute auf dem ts waren ihn nochmal versucht zu starten und er hat wie vorher angefangen die db abzugleichen und es dann aber geschafft. Nun Leufts wieder. Hab aber kompletten log 9999zeilen gesaved wo alles seid dem 12.2 drin steht. Mich würde interessieren ob der Fehler sich provozieren lässt wenn man den bot nun ausschaltet und einschaltet. Bin aber grad happy das er sich gefangen hat. Trotzdem komisch da dieses Problem anscheinend ohne ursache kamm und auch ging.

**Comment by Shad86** [comment]
Okay, vielleicht, war doch ein falscher Wert gespeichert (in dem fall ein zu kleiner Check Intervall) zu irgendeinem Zeitpunkt. Solange man dann aber nicht das ranksystem neustartet, bleibt dieser Wert erhalten, da man nach dem Speichern neustarten muss damit die Änderungen wirksam werden.

Das wäre zumindest aus meiner Sicht, derzeit die Logische Ursache.

Ich schließe das ganze erstmal, sollte es doch wieder auftreten mach einfach ein neues issue auf und verweiße auf dieses issue.
