### ISSUE TITLE
Bot verliert die Verbindung, wenn andere Query connected

### ISSUE THREAD

**Issue by DZPhoenix** [Newcomer1989/TSN-Ranksystem#457]
Ich habe das Problem, wenn die Query unserer Website auf den Ts3 verbindet, verliert der Rankingbot die Verbindung.

**Comment by Shad86** [comment]
Bot und ranksystem sind auf dem selben Server? Verbindet der bot per localhost oder per Publicip? Wenn PublicIP ist die IP auf der Whitelist?

MfG

Shad86

**Comment by DZPhoenix** [comment]
Ja, beide waren auf dem gleichen Webserver. Und beide Bots verbinden auf die PublicIP (da anderer Server). Wie meinst du das eigentlich mit der Whitelist?

**Comment by Shad86** [comment]
teamspeak hat eine eigene whitelist im Server Ordner (Query_IP_Whitelist.txt) - wenn du mit der Public Ip verbindest MUSS diese in dieser Liste mit aufgeführt werden. Sonst kann es zu einem Flood ban kommen. (Was ich in deinem Fall vermute, da du mit der public ip verbindest)

**Comment by DZPhoenix** [comment]
Okay, nachdem ich die IP eingetragen funktioniert der Bot wieder recht zuverlässig ^^ Danke

**Comment by DZPhoenix** [comment]
Das Problem tritt leider weiterhin auf. Ich habe jetzt eventuell nen Befehl gefunden, der das Problem beheben könnte, jedoch weiß ich leider nicht wo ich den eintragen soll... Der Befehl wäre query_buffer_mb.
Weißt du zufällig wo ich den eintragen muss? Zur Info, ich nutze einen Windows-Server
