### ISSUE TITLE
Statistiken für Woche und Monat werden nicht aktualisiert

### ISSUE THREAD

**Issue by TheChaosToast** [Newcomer1989/TSN-Ranksystem#458]
Hallo zusammen,

ich weiß nicht ob es euch schon aufgefallen ist, aber die Statistiken für die Woche und Monat werden nicht aktualisiert. Diese stehen bei den TOP10 Usern seit 10 Tagen auf dem gleichen Stand, obwohl diese User alle eingeloggt waren. Die gesamte Zeit in Tagen wird korrekt angezeigt, aber nicht für die einzelnen User in den bunten Feldern.

Ich habe den Bot und auch den Server mehrmals neu gestartet, da ich dachte es liegt an einem temporären Problem.

Danke für Eure Hilfe und Antworten

**Comment by Newcomer1989** [comment]
Magst du uns einen Screenshot teilen, damit wir wissen welche Stelle du genau meinst?!

**Comment by TheChaosToast** [comment]
Jup, kann ich machen ...

![screen](https://user-images.githubusercontent.com/36563709/37568442-6a1055c8-2ad5-11e8-8e8b-d29a9666baa1.png)
 
Die rot markierten sind nur Beispielhaft ... das tritt bei allen TOP10 Usern - egal ob Monatlich oder Wöchentlich. Beim Gesamtstatus funktioniert alles bestens.

**Comment by TheChaosToast** [comment]
Hab zufälligerweise nur ich das Problem?

**Comment by Newcomer1989** [comment]
Habe es extra mal überprüft. Sollte eigentlich passen.
Bitte beachte, dass die Werte immer vom Zeitpunkt, wann du sie aufrufst, eine Woche bzw. 30 Tage rückwärts gerechnet werde. Aktualisieren sollten die Werte sich alle 6 Stunden.
Ist also ein User regelmäßig zur gleichen Zeit, gleich lang online, so kann es passieren, dass die Werte sich nicht ändern. Bzw. nur so geringfügig ändern, dass es ggfs. kaum auffällt.

Hier zwei Screenshots, wie es bei mir gerade aussieht:
![image](https://user-images.githubusercontent.com/11364569/37614951-583d8b4a-2bac-11e8-99cf-54d0b6ab3f86.png)
![image](https://user-images.githubusercontent.com/11364569/37614957-5cb3c7d4-2bac-11e8-9569-51f845b1216f.png)

**Comment by TheChaosToast** [comment]
Hallo und danke für die ausführliche Antwort.

Aber eins versteh ich nicht, ich selbst bin permanent und ständig Online (sofern es das Netz zulässt) da müsste ich doch rein theoretisch in der Wochen/Monatsstatistik ganz oben stehen? Denn da steh ich in der Woche mit 7 Stunden und im Monat mit 78 Stunden. Das ergibt nicht wirklich sinn für mich. Denn ich glaube mich erinnern zu können das es mal "richtig" gezählt wurde.

Oder mal anders gefragt - wie kann ich überprüfen das es korrekt funktioniert? 

Vielen Dank :)

**Comment by Newcomer1989** [comment]
Welchen Modus hast du im Ranksystem denn aktiviert.. online Zeit oder aktive Zeit?

**Comment by Newcomer1989** [comment]
Wir haben es nun noch einmal bei versch. Instanzen beobachtet. Die Werte werden korrekt gebildet.

Falls es Probleme geben sollte, bitte sauber dokumentieren und noch einmal öffnen.
Aus der Doku müssen wir dann erkennen zu welchem Zeitpunkt welche Werte vorhanden waren. Wie gesagt, sie werden nur alle 6 Std. neu berechnet.

**Comment by TheChaosToast** [comment]
Sorry ... um Deine Frage zu beantworten, ich verwende nur die aktive Zeit. Leider hat sich herausgestellt, daß bei mir tatsächlich die Monats und Wochenstatistiken nicht funktionieren. Alles andere wird gezählt nur in den farbigen Feldern werden die korrekten Werte nicht angezeigt. Ich werde es jetzt noch eine Weile beobachten. 

Ich überlege auch eine Neuinstallation zu wagen und dann das Datenbankbackup einzuspielen. Nur hab ich Bedenken das es dann immer noch nicht funktionieren tut :(
