### ISSUE TITLE
Critical config error!

### ISSUE THREAD

**Issue by elam023** [Newcomer1989/TSN-Ranksystem#459]
I installed the Ranksystem on a virtual machine external to the TeamSpeak3 server. I have correctly configured the Ranksystem but after a series of drops of connections during the download of the icons a series of critical errors do not allow me to start the Ranksystem.
I've already added the Ranksystem ip to the TeamSpeak3 server whitelist.
Here is the log of the Ranksystem: https://pastebin.com/ze5GLhFW

**Comment by elam023** [comment]
I noticed that other users have reported my problem but I could not understand because was written in another language that I do not know.

**Comment by Shad86** [comment]
2018-03-17 13:46:36.788682   ERROR     TS3 Error: 3331: Error while getting servergrouplist: flood ban

explains everything...

Whitelist the Public ip from the ranksystem on your ts3 server (in the Server Folder is a file called -> Query_IP_Whitelist.txt)

only ip in numbers is allowed like 123.123.123.123

regards

Shad86

**Comment by Shad86** [comment]
Next error about groups:

hey,

Stop your bot and check your database with: 

`SELECT * FROM groups;`

if it doesn't fit with your teamspeak groups do:

DELETE FROM groups;

after that start the ranksystem again. it should work fine again then.

**Comment by elam023** [comment]
Solved!
Thanks!
