### ISSUE TITLE
Top User

### ISSUE THREAD

**Issue by braum123** [Newcomer1989/TSN-Ranksystem#46]
Hey
folgendes Problem
bei den Top Usern ist auf dem 2. platz jemand der nur 2 sec da war und wieder gegangen ist.
ich bin seit stunden drinne bin auf dem letzten und auf dem ersten ist ein etwas neuerer.
er hat 100%
der rest alle 0
wie wird  der top user ermittelt?

und ich würde gerne den anderen ermöglichen in ihre eigenen stats zu sehen etc, aber dann sehen die ja den kompletten datei-pfad sehen und dann in den hauptordner gehen und in die logs etc schauen. kann man da etwas gegen machen? oder brauch ich mir da kein sorgen machen ?

**Comment by CosmoAbdon** [comment]
u can send a screenshot ? if possible, of course.

**Comment by Newcomer1989** [comment]
> und ich würde gerne den anderen ermöglichen in ihre eigenen stats zu sehen etc, aber dann sehen die ja den kompletten datei-pfad sehen und dann in den hauptordner gehen und in die logs etc schauen. kann man da etwas gegen machen? oder brauch ich mir da kein sorgen machen ?

There is an options inside the webinterface to choose a divergent log path. Put it to a folder, which is not under your www path from your webserver. So it will be hidden from the public.
This solve your problem?


For the other thing (top user): It would be wonderful to see anything. So a screen would be helpful.

**Comment by braum123** [comment]
sry hab jetzt den zusammenhang verstanden von der startseite das grüne gelbe und rote ranking... das ist all time ,  woche und tag. und da steht noch zu wenige daten... also brauch ich nur geduld.
Das alltime geht die anderen brauchen noch ein wenig :)

kannst du bitte noch etwas erläutern wie ich den ordner verstecke. also ich muss ja den link rausgeben mit dem example.de/ranksystem/stats/top_week.php . das was man ändern kann ist ja nur der log path

**Comment by Juggernaut132** [comment]
I have the same problem. http://tools.join-fps.de/ranking/stats/top_month.php

**Comment by Shad86** [comment]
@Juggernaut132 there are not enough datas for top month, that there can be something generated, you have to wait at least 1 Month ;)

**Comment by Juggernaut132** [comment]
Oh okay, thanks! :+1:

**Comment by braum123** [comment]
i want it like Juggernaut132!! so u cant see the folder :D

**Comment by braum123** [comment]
captain please teach me

**Comment by Juggernaut132** [comment]
If you are using debian try "a2dismod autoindex"

**Comment by Juggernaut132** [comment]
Is there any way to exclude some channel?

**Comment by Newcomer1989** [comment]
This is not a chat.. Please report bugs or suggestion or also questions with different topics also in different issues!
I think the first question is solved here, so its closed now.
