### ISSUE TITLE
Add online Time to User does no longer work

### ISSUE THREAD

**Issue by bykidi** [Newcomer1989/TSN-Ranksystem#460]
I have no clue. I migrated to Debian stretch few days ago and noticed that time adder no longer adds time to user.
This is might be related to newest PHP which i also have now
PHP 7.2.3-1+0 20180306120016.19+stretch~1.gbp81bf3b (cli) (built: Mar  6 2018 12:00:19) ( NTS )

**Comment by bykidi** [comment]
TeamViewer session is possible, if needed

**Comment by Shad86** [comment]
Is already a known issue -> https://github.com/Newcomer1989/TSN-Ranksystem/issues/447 - as long as it doesn't work in the normal way:

Stop the bot choose the user you want to add time, then start the ranksystem again

regards

**Comment by bykidi** [comment]
Can confirm that it's working
