### ISSUE TITLE
Message to optimize the Ranksystem

### ISSUE THREAD

**Issue by SossenSystems** [Newcomer1989/TSN-Ranksystem#461]
Hi,

das Ranksystem läuft bei mir auf rankbot.phynixgaming.net.
Das ist ein eigener Server nur für das Ranksystem.
Der Webserver läuft auf ngnix.

Was mich nur extrem wundert ist, dass das Webinterface hin und wieder das gelbe Label anzeigt mit „Es scheint das...“ typischer Label wenn der Bot länger nicht auf dem TeamSpeak 3 Server war.
Mittlerweile läuft dieser Stabil, nur ziemlich langsam ich glaube das ist auch der Grund für den Label.

Vorhin habe ich diese Nachricht via privatemessage erhalten „<18:34:02> "Level-System": 
Your Ranksystem seems to be slow. This is not a big deal, but it needs more ressources then necessary.
Here you'll find some information to optimize it: https://ts-n.net/ranksystem.php#optimize
Last 10 runtimes in seconds (lower values are better):
4.44170;6.70635;4.30548;5.85737;6.92705;4.15024;6.86982;6.10418;6.76681;5.12581“ ich glaube aber ehr weniger dass das ganze am Webserver liegt.

Was ich auch komisch finde ist das auf der Stats Seite ein Ergebnis als -50 Tage wiedergeben wird.

Gruß Michael :)

**Comment by Shad86** [comment]
Ich kann keine -50 tage sehen, entweder bin ich blind oder der Fehler wurde von dir selbst behoben.

> 4.44170;6.70635;4.30548;5.85737;6.92705;4.15024;6.86982;6.10418;6.76681;5.12581“ ich glaube aber ehr weniger dass das ganze am Webserver liegt.

Das hat so auch eher weniger mit dem Webserver zu tun.

Zumindest sehe ich mysql / mariadb eher als etwas separates und wenn du zu langsame Werte hast, kann das durchaus ein mysql / mariadb Problem sein. (Denn die Standartconfig ist nunja, meist nicht gerade die beste) 

Es könnte natürlich auch die Hardware eine Rolle spielen aber selbst mit HDD's konnte ich damals mit einer Optimierten mysql / mariadb Config noch recht gute Werte erreichen.

**Comment by Newcomer1989** [comment]
Hat sich damit wohl erledigt.. Eigentlich steht auch alles in der Nachricht bzw. in den verlinkten Tipps zum Optimieren.

Wird die Systemumgebung sauber eingerichtet, so sollte das Ranksystem gut mit den Ressourcen umgehen und sehr zügig arbeiten. Klar, auf großen System wird es schon etwas dafür benötigen. O.g. Werte sollten aber um mind. das 5 fache optimierbar sein!

**Comment by SossenSystems** [comment]
Vielen Dank für deine Rückmeldung!

Liegt höchstwahrscheinlich an MySQL.
An den Ressourcen wird es wahrscheinlich nicht liegen.
```
CPU-Auslastung
51.87% von 1 CPU(s) // 8 x Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (1 Socket)
Speicherverbrauch
35.00% (716.88 MiB von 2.00 GiB) // DDR4 Ram tackung hab ich gerade nicht parat

```
Aber ist ist jetzt mit der neusten Version (1.2.6) ziemlich gut geworden.
