### ISSUE TITLE
Addon-/Plugin-System für 3rd Party Scripts

### ISSUE THREAD

**Issue by DanielR92** [Newcomer1989/TSN-Ranksystem#462]
Hallo zusammen,

es wäre sehr sinnvoll wenn es ein plugin Ordner existiert, wo von dort aus zusätzliche funktionen hiinzugefügt werden kann / geladen werden kann. Bis jetzt ist alles sehr staar miteinander verbunden.

Besser wäre es flexibel!

Edit:

Anregungen:
+ **bot.php**: alles auf Threads aufbauen (pthreads (v3) => voraussetzung PHP 7.2+)
+ vorhandenen Addons Prüfen (wird dann im Thread dazu geladen, bei löschung/deakt. wird es raus genommen.)
+ **Webinterface**: einzelne abfragen bzw. aktionen sollen individuel getiment werden können.

**Comment by Shad86** [comment]
Die Addons-Sache war damals erstmal nur ein Test.

Leider sind uns bis dato leider immer wieder Punkte dazwischen gekommen, so dass wir uns der Addonsache nicht widmen konnten.

Wann wir uns dem ganzen annehmen, können wir derzeit nicht sagen, da wir derzeit mit bugfixing beschäftigt sind und danach eig. noch die Wünsche aus dem Voting offen sind.

Wenn du aber natürlich eine Idee hast, wie man das modularer lösen könnte, sind wir um jede Hilfe dankbar, da dieses Projekt derzeit nur in der Freizeit entwickelt wird und wir keine Einnahmen daraus erzielen. (Open-Source-Projekt)

Natürlich werden jegliche Helfer auch immer in unserem Ranksystem verlinkt.

**Comment by DanielR92** [comment]
Achso ok,

ideen hätte ich schon jedoch kommende Tage selbst kaum Zeit. Werde mich mal damit beschäftigen...

**Comment by Newcomer1989** [comment]
Dieser Punkt steht bereits auf unserer ToDo Liste.. Allerdings ist dort sehr viel drauf, die Zeit allerdings stark begrenzt, wie Shad86 bereits berichtete.

Wenn du also in die Richtung etwas machen möchtest, dann sehr gerne als Pull-Request einstellen.

**Comment by DanielR92** [comment]
Wo kann man den aktuellen stand der ToDo's einsehen?
Mantis vorhanden?
Würde gerne einige kleinigkeiten behilflich sein, bzw. aushelfen bei problemen oder fragen.

**Comment by Newcomer1989** [comment]
Ein Teil der ToDo-Liste befindet sich hier: https://ts-n.net/ranksystem.php#todo
Allerdings ist das nicht alles. Wir müssen die Liste mal wieder aktualisieren.

Wäre super etwas Unterstützung zu haben. Die Zeit ist doch sehr begrenzt, wenn man Vollzeit berufstätig ist und noch zusätzlich studiert.
Wichtig wäre jedoch eine Absprache, was du gerne übernehmen möchtest, damit nicht parallel an den gleichen Dingen gearbeitet wird und es nachher quer läuft. Du kannst und über den Public TS erreichen (Adresse: ts-n.net).

**Comment by HellBz** [comment]
Würde mich da auch anbieten, hatte ja schonmal dieses KleineAFK-Move Script mit dir gemacht

**Comment by Newcomer1989** [comment]
Wir sind hier in eine leicht andere Richtung gegangen, in dem wir eine API anbieten.

Ein Plugin-System birgt immer das Risiko, dass ein externes Script, welches eingebunden wird, zu Problem führt. Aus der Sicht macht es mehr Sinn die externen Scripte auch extern zu lassen und sauber abzugrenzen. Wenn tatsächlich Bedarf / Interesse besteht, würden wie die API zu einer vollständigen REST API ausweiten. D.h. es wäre dann auch über die API möglich gewisse Löschanfragen oder Updateanfragen zu schicken. Derzeit können nur Daten ausgelesen werden.
So zumindest die Idee. Das aber auch nur, wenn wirklich ein Bedarf besteht. Aktuell sind die Anfragen hiernach sehr verhalten.
