### ISSUE TITLE
SQL syntax error bei der Installation (minus im namen) [gelöst]

### ISSUE THREAD

**Issue by interas99** [Newcomer1989/TSN-Ranksystem#468]
Guten Abend,

ich möchte gerne auf meinem Root das Rankingsystem installieren und bekomme dabei folgenden Fehler, wenn ich bei der Installation eine Verbindung zur Datenbank herstellen will:

`Database error: 42000 Array ( [0] => 42000 [1] => 1064 [2] => You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-Ranking' at line 1 )
Database error: 42000 Array ( [0] => 42000 [1] => 1064 [2] => You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-Ranking.user (uuid varchar(29) CHARACTER SET utf8 COLLATE utf8_unicode_ci PRIMA' at line 1 )
Database error: 42000 Array ( [0] => 42000 [1] => 1064 [2] => You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-Ranking.groups (sgid int(10) NOT NULL default '0' PRIMARY KEY,sgidname varchar(' at line 1 )
Database error: 42000 Array ( [0] => 42000 [1] => 1064 [2] => You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-Ranking.config (webuser varchar(64) CHARACTER SET utf8 COLLATE utf8_unicode_ci,' at line 1 )
Database error: 42000 Array ( [0] => 42000 [1] => 1064 [2] => You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-Ranking.server_usage (timestamp bigint(11) NOT NULL default '0',clients smallin' at line 1 )
Database error: 42000 Array ( [0] => 42000 [1] => 1064 [2] => You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-Ranking.user_snapshot (timestamp bigint(11) NOT NULL default '0',uuid varchar(2' at line 1 )
Database error: 42000 Array ( [0] => 42000 [1] => 1064 [2] => You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-Ranking.stats_server (total_user int(10) NOT NULL default '0',total_online_time' at line 1 )
Database error: 42000 Array ( [0] => 42000 [1] => 1064 [2] => You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-Ranking.stats_user (uuid varchar(29) CHARACTER SET utf8 COLLATE utf8_unicode_ci' at line 1 )
Database error: 42000 Array ( [0] => 42000 [1] => 1064 [2] => You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-Ranking.stats_server SET total_user='9999'' at line 1 )
Database error: 42000 Array ( [0] => 42000 [1] => 1064 [2] => You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-Ranking.job_check (job_name varchar(20) CHARACTER SET utf8 COLLATE utf8_unicode' at line 1 )
Database error: 42000 Array ( [0] => 42000 [1] => 1064 [2] => You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-Ranking.job_check (job_name) VALUES ('calc_user_limit'),('calc_user_lastscan'),' at line 1 )
Database error: 42000 Array ( [0] => 42000 [1] => 1064 [2] => You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-Ranking.stats_nations (nation varchar(3) CHARACTER SET utf8 COLLATE utf8_unicod' at line 1 )
Database error: 42000 Array ( [0] => 42000 [1] => 1064 [2] => You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-Ranking.stats_versions (version varchar(64) CHARACTER SET utf8 COLLATE utf8_uni' at line 1 )
Database error: 42000 Array ( [0] => 42000 [1] => 1064 [2] => You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-Ranking.stats_platforms (platform varchar(32) CHARACTER SET utf8 COLLATE utf8_u' at line 1 )
Database error: 42000 Array ( [0] => 42000 [1] => 1064 [2] => You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-Ranking.addons_config (param varchar(255) CHARACTER SET utf8 COLLATE utf8_unico' at line 1 )
Database error: 42000 Array ( [0] => 42000 [1] => 1064 [2] => You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-Ranking.addons_config (param,value) VALUES ('assign_groups_active','0'),('assig' at line 1 )
Database error: 42000 Array ( [0] => 42000 [1] => 1064 [2] => You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-Ranking.addon_assign_groups (uuid varchar(29) CHARACTER SET utf8 COLLATE utf8_u' at line 1 ) `

Hier mal das Bild, damit es Übersichtlicher ist: [http://abload.de/image.php?img=fehlervwu04.png](http://abload.de/image.php?img=fehlervwu04.png)

Ich hab schon im Internet nach diesem Fehler gesucht aber nichts gefunden, außer Änderungen im Quellcode. Aber daran sollte es doch eigentlich nicht liegen? 

Das System ist gerade frisch aufgesetzt. Habe es bei meinem alten Root zum laufen gebracht und habe aber bei dem System keine Änderungen außer von der Hardware.

Ich verwende die PHP Version 7.0
Und den MYSQL Server auf Version 5.7.21
Das ganze Läuft auf Ubuntu 16.04

Da ich im Moment nicht mehr weiter weiß, wollte ich hier mal nachfragen ob ihr noch Ideen habt woran es liegen könnte?

MfG

Interas

**Comment by Shad86** [comment]
Hast du es auch schon einmal mit einer kompletten Neuinstallation des Ranksystems versucht? Die Datenbank selbst muss glaube ich auch zudem in utf8mb4 sein.

**Comment by interas99** [comment]
Ja hatte ich, hat aber nichts dran geändert. 
Ich gucke morgen mal welches Format die Datenbank hat, schon mal danke für den Hinweis. Werde mich da morgen früh direkt hinsetzten und das nachgucken und mein Ergebnis schreiben.

**Comment by interas99** [comment]
Also ich hab das Ranksystem nun 5 mal neuinstalliert, da sobald ich diesen Fehler bekomme und es mit anderen Daten versuche (habs einmal mit Root versucht) immer nur eine weiße Seite angezeigt bekomme... 

Ich hab die Datenbank auf uft8mb4 geändert und bekomme immernoch den gleichen Fehler.

Hier mal ein Bild zur Datenbank. Der Benutzer heißt genau gleich (was ja eigentlich irrelevant ist) und hat alle Rechte auf dieser Datenbank.

![datenbank](https://user-images.githubusercontent.com/34246253/38033325-18ae153a-32a0-11e8-82aa-5f2befcec1fb.PNG)

**Comment by Shad86** [comment]
Vielleicht, gibt es tatsächlich eine Inkompatibilität zu der mysql Version - was ich dir so aber Momentan nicht sagen kann, da ich selbst derzeit nur mariadb 10.1 im Einsatz habe - dazu müsste sich @Newcomer1989 mal äußern ob er diesbezüglich was weiß.

Natürlich kannst du auch mal schauen ob bei dir bei mariadb, das gleiche problem besteht.

**Comment by Newcomer1989** [comment]
Probiere mal bitte das Minus aus den Namen zu entfernen.

Sowohl der Username als auch der DB-Name sollte keine Sonderzeichen beinhalten.

**Comment by interas99** [comment]
Hat jetzt einwandfrei Funktioniert.

Viel Dank für die Hilfe =D

wie viel doch ein "-" ausmacht...
