### ISSUE TITLE
HY000 error due saving the user for the webinterface

### ISSUE THREAD

**Issue by maxibanki** [Newcomer1989/TSN-Ranksystem#47]
Hallo,
nachdem ich die Datenbank Daten eingegeben habe, und er die Tabellen alle erstellt hat, soll ich mir ja einen Account erstellen. Daraufhin gebe ich die Daten bzw irgendeinen Login ein und drücke auf den Submit button. Daraufhin erhalte ich eine Komplett weiße Seite mit folgendem Text:
"HY000"
Hast du einen Rat?
Ich benutze einen Mysql Server 5.7, was vielleicht der Grund ist

**Comment by Newcomer1989** [comment]
Inside the error message should be a 4 digits long error code.
HY000 says only error ;-)

Cause you could insert all other, it could only be your username or password.

You have any special signs inside your username or password?
Try a username and password that only have alphanumeric signs. No special signs, like whitespace or slash...

**Comment by maxibanki** [comment]
I tested the username with the following data:
user: "test"
pw: "testtest"
but that did´t work anyway
Here is a screenshot with the soucecode, which is displayed: 
http://i.imgur.com/LsL5fsd.png

**Comment by Newcomer1989** [comment]
Then please check, the database is correctly installed.

You have to find a table "config" inside your database. And there should be already exists some columns.

Otherwise, you tried to delete all and install it from beginning on?

**Comment by maxibanki** [comment]
all tables are empty except the cleanclients which contains a timestamp with the number 1 and the job_check which contains that
http://i.imgur.com/vQ4ENkJ.png

**Comment by Newcomer1989** [comment]
Again...

> You have to find a table "config" inside your database. And there should be already exists some columns.

**Comment by maxibanki** [comment]
This `config` table is empty

**Comment by Newcomer1989** [comment]
so, there are no columns definitions set?

**Comment by maxibanki** [comment]
yep http://i.imgur.com/0Qgt7aO.png

**Comment by maxibanki** [comment]
Hier noch logs, falls sie helfen: http://hastebin.com/danerayolo.coffee

**Comment by Newcomer1989** [comment]
on install.php you'll find this code line

`echo '<span class="wncolor">',$mysqlcon->errorCode(),'</span><br>';`

Please replace it with following

`echo '<span class="wncolor">',print_r($mysqlcon->errorInfo()),'</span><br>';`

Then try to install it again and post us here the error you get.

**Comment by maxibanki** [comment]
Array ( [0] => HY000 [1] => 1366 [2] => Incorrect integer value: '' for column 'defchid' at row 1 ) 1

**Comment by Newcomer1989** [comment]
Seems to special to your database.. No other reported this before. Try this:

Search in install.php for this line

`if($mysqlcon->exec("INSERT INTO config (webuser,webpass,tshost,tsquery,tsvoice,tsuser,language,queryname,queryname2,grouptime,resetbydbchange,msgtouser,upcheck,uniqueid,updateinfotime,currvers,exceptuuid,exceptgroup,dateformat,showexgrp,showexcld,showcolcld,showcoluuid,showcoldbid,showcolot,showcolit,showcolat,showcolnx,showcolsg,bgcolor,hdcolor,txcolor,hvcolor,ifcolor,wncolor,sccolor,showgen,showcolrg,showcolls,slowmode,cleanclients,cleanperiod,showhighest,boost,showcolas,defchid,timezone,logpath) VALUES ('$user','$pass','localhost','10011','9987','serveradmin','en','http://ts-n.net/ranksystem.php','www.ts-n.net/ranksystem.php','31536000=>47,31536060=>50','1','1','1','xrTKhT/HDl4ea0WoFDQH2zOpmKg=,9odBYAU7z2E2feUz965sL0/MyBom=','7200','1.0.2','xrTKhT/HDl4ea0WoFDQH2zOpmKg=','2,6','%a days, %h hours, %i mins, %s secs','1','1','1','1','1','1','1','1','1','1','#101010','#909090','#707070','#FFFFFF','#3366CC','#CC0000','#008000','1','1','1','0','1','86400','1','','1','','Europe/Berlin','$logpath')") === false)	{`

and replace it with

`if($mysqlcon->exec("INSERT INTO config (webuser,webpass,tshost,tsquery,tsvoice,tsuser,language,queryname,queryname2,grouptime,resetbydbchange,msgtouser,upcheck,uniqueid,updateinfotime,currvers,exceptuuid,exceptgroup,dateformat,showexgrp,showexcld,showcolcld,showcoluuid,showcoldbid,showcolot,showcolit,showcolat,showcolnx,showcolsg,bgcolor,hdcolor,txcolor,hvcolor,ifcolor,wncolor,sccolor,showgen,showcolrg,showcolls,slowmode,cleanclients,cleanperiod,showhighest,boost,showcolas,defchid,timezone,logpath) VALUES ('$user','$pass','localhost','10011','9987','serveradmin','en','http://ts-n.net/ranksystem.php','www.ts-n.net/ranksystem.php','31536000=>47,31536060=>50','1','1','1','xrTKhT/HDl4ea0WoFDQH2zOpmKg=,9odBYAU7z2E2feUz965sL0/MyBom=','7200','1.0.2','xrTKhT/HDl4ea0WoFDQH2zOpmKg=','2,6','%a days, %h hours, %i mins, %s secs','1','1','1','1','1','1','1','1','1','1','#101010','#909090','#707070','#FFFFFF','#3366CC','#CC0000','#008000','1','1','1','0','1','86400','1','','1','0','Europe/Berlin','$logpath')") === false)	{`

after this try again.. hopefully for the last time ;-)

**Comment by maxibanki** [comment]
now it is working, but it isn´t connecting to the teamspeak server. The cronjob is additionally set.

**Comment by maxibanki** [comment]
Can you speak german?

**Comment by Newcomer1989** [comment]
There are your TeamSpeak settings wrong or you have to check the network connection (firewall) from your webserver to your TeamSpeak server about TCP query port!
