### ISSUE TITLE
Kann die Datei nicht unzippen

### ISSUE THREAD

**Issue by Vyzeax** [Newcomer1989/TSN-Ranksystem#470]
Hey, ich habe bereits die Version 1.2.5 auf unserem VServer (Ubuntu 8.0 x86_64 (minimal)) die Datei installiert, jedoch kann sie nicht geunzipped (oder wie man das nennt, :D) werden.

Ich bin leider sehr unerfahren im Bereich VServer/Putty, bitte deshalb auch um Hilfe.

Vielen Dank!

**Comment by Newcomer1989** [comment]
Zur Info: Die aktuellste Version des Ranksystems ist die 1.2.6

> Ubuntu 8.0 x86_64 (minimal)

Ist nicht dein Ernst, oder? Wenn ich mich nicht gerade komplett vertue, ist die aus dem Jahr 2008.
Bitte besorge dir zunächst ein aktuelles System!

Ansonsten müsstest du das Paket unzip installieren, um es zu entpacken:
`sudo apt-get install unzip`

Bzw. das Ranksystem benötigt hierfür das entsprechende PHP Paket:
`sudo apt-get install php-zip `

**Comment by Vyzeax** [comment]
Wie gesagt, ich bin sehr unerfahren in diesem Bereich. Habe mich übrigens vertan, war Debian 8.0 minimal, habe die Version jetzt aber auf Ubuntu 16.04 geändert. Es läuft alles 👍
