### ISSUE TITLE
Happy April ❤️

### ISSUE THREAD

**Issue by SossenSystems** [Newcomer1989/TSN-Ranksystem#471]
Nice joke with the Ranksystem today 💪🏼

**Comment by SossenSystems** [comment]
P.S.: https://phynixgaming.net/index.php/Thread/173-Ein-Schreck-wird-gebraucht-der-1ste-April-macht-was-er-will/#post594 :dango:

**Comment by Shad86** [comment]
Nicht einsehbar ohne account^^

**Comment by SossenSystems** [comment]
Uppss mein Fehler xD
https://image.prntscr.com/image/YEiTKC4oRxWmmPTq4vfBAA.png

**Comment by Newcomer1989** [comment]
Wir können euch etwas beruhigen.. Am 02. April sollte alles wieder wie gewohnt laufen.

Wem es extrem stört, der kann den Slowmode aktivieren, um den Aprilscherz zu deaktivieren.
