### ISSUE TITLE
Move bis zum Flood ban

### ISSUE THREAD

**Issue by monster010** [Newcomer1989/TSN-Ranksystem#472]
heyho NewComer,

ich hab da so ein kleines Problem:

[Bot] Viki = Ranksystem

`<05:58:10> "[Bot] EDI" wurde von "[Bot] Viki" aus Channel "╚ Warte auf Freischaltung" in Channel "[cspacer33]" verschoben
<05:58:10> Die Channel Gruppe "Guest" [Geerbt von: [cspacer40]] wurde "[Bot] EDI" von "» WaterFlow - Gaming «♦» Nicht mit dem Strom, sondern dagegen «" zugewiesen.
<05:58:10> "[Bot] EDI" wurde von "[Bot] Viki" aus Channel "[cspacer33]" in Channel "[*spacer19]-.." verschoben
<05:58:10> Die Channel Gruppe "Guest" [Geerbt von: [cspacer40]] wurde "[Bot] EDI" von "» WaterFlow - Gaming «♦» Nicht mit dem Strom, sondern dagegen «" zugewiesen.
<05:58:10> "[Bot] EDI" wurde von "[Bot] Viki" aus Channel "[*spacer19]-.." in Channel "[*spacer2]═" verschoben
<05:58:10> Die Channel Gruppe "Guest" [Geerbt von: [cspacer40]] wurde "[Bot] EDI" von "» WaterFlow - Gaming «♦» Nicht mit dem Strom, sondern dagegen «" zugewiesen.
<05:58:10> "[Bot] EDI" wurde von "[Bot] Viki" aus Channel "[*spacer2]═" in Channel "[*spacer20]-.." verschoben
<05:58:10> Die Channel Gruppe "Guest" [Geerbt von: [cspacer40]] wurde "[Bot] EDI" von "» WaterFlow - Gaming «♦» Nicht mit dem Strom, sondern dagegen «" zugewiesen.
<05:58:10> "[Bot] EDI" wurde von "[Bot] Viki" aus Channel "[*spacer20]-.." in Channel "[cspacer40]" verschoben
<05:58:10> Die Channel Gruppe "Guest" wurde "[Bot] EDI" von "» WaterFlow - Gaming «♦» Nicht mit dem Strom, sondern dagegen «" zugewiesen.
<05:58:10> Die Verbindung von "[Bot] Viki" wurde unterbrochen (connection lost)`

Kompletter ausschnitt https://pastebin.com/7Hv52bUP

**Comment by Newcomer1989** [comment]
Bitte für heute den Slowmode auf die geringste Stufe stellen, ab morgen sollte es nicht mehr auftreten.
Happy April ;-)
