### ISSUE TITLE
Big Issue!

### ISSUE THREAD

**Issue by EGXZ** [Newcomer1989/TSN-Ranksystem#473]
Since yesterday, I have a problem with my bot and I think who is stranger.

Yesterday, I wanted to put 100 levels and this idea did not please me so I decided to remove it and I also removed the groups and now that as soon as a person rankup ranksystem moves the rankup user in all channels???!

I know I explained it wrong, but it's a crazy thing!!

**Comment by Shad86** [comment]
its aprils fool ;D

**Comment by EGXZ** [comment]
Jesus christ is there a way to disable this please ?

**Comment by Shad86** [comment]
only @Newcomer1989 can say that

**Comment by Shad86** [comment]
What you could do @EGXZ is that you revoke the moverights from the bot in the meantime

**Comment by Shad86** [comment]
I got an additional info:

> If you find it extremely annoying, you can activate the slow mode to deactivate the April Fool.

**Comment by Newcomer1989** [comment]
In germany we say "April April" ;-)

You can disable the april fool by activating the slowmode. Each variant of the slowmode will deactivate the movings.

Tomorrow the move funtion will be disabled automatically.

**Comment by NothingTV** [comment]
If you have a Anti-Channelhopping Script, it's pure bullshit to move a user straight through 100 Channels til he gets banned.. I mean it's a nice Idea to implent a April Fool, but something like that?

**Comment by Shad86** [comment]
But why should a user get banned for getting moved? i would say that the script isn't correct written. or at least not logical.

But as told you can deactivate it.

**Comment by NothingTV** [comment]
You mean for getting moved 30 times a second? Idk maybe for anti-flood?

**Comment by Shad86** [comment]
Still unlogic , why banish the guy which gets moved from another "person"? I mean, you said that if someone gets moved many times from a third person he also get banned.

I never would use such a script on my Server, it would be a to high risk that other people come on my teamspeak and ban my users.

We really feel really sorry, if it may bother someone but as many time written here on Github, you where able to disable it.

But please stop blaming us that you having such a wrong written Script on your server, which punishes innocent users.

**Comment by Newcomer1989** [comment]
> You mean for getting moved 30 times a second? Idk maybe for anti-flood?

Anti-Flood would ban that user, which do the move not that user, which get moved.

Sorry for the problems you have gotten. That was not our concern! We have though about that problem before we implement it, thats the reason why the april fool was only active on systems, which had the slowmode deactivated. So we could be sure, the Ranksystem doesn't get banned.

In your case the ban comming from a third party application. I think you should check this tool, which you are using. What I have read here, this doesn't make any sense in this case.
