### ISSUE TITLE
aktive zeit

### ISSUE THREAD

**Issue by tmdg2** [Newcomer1989/TSN-Ranksystem#474]
ich habe das ranks auf aktive zeit aber die user level weiter ohne das sie sprechen habe es schon neu install bin radlos ;/ 
system debian 8.10

**Comment by Shad86** [comment]
Wie sieht denn bei den kerneinstellungen bei dir der ignorier idle Wert aus?

![igno-idle](https://user-images.githubusercontent.com/18570683/38199725-15b66954-3692-11e8-84e0-7482c421b19f.jpg)

Je nachdem wie hoch dieser Wert ist, lvl'n die Leute noch "nach" - auf meinem Beispielbild würde einer noch 1:59Min nachleveln, bevor er als idle gemarkt wird.

**Comment by tmdg2** [comment]
Danke
