### ISSUE TITLE
Select on DB failed: array

### ISSUE THREAD

**Issue by kevinboeger** [Newcomer1989/TSN-Ranksystem#475]
https://i.imgur.com/bnXgl49.png

bekomme nur das in der Console. Danach ist der Bot rip. Problem trifft ab und an auf nicht genau zu sagen wann und warum

**Comment by Newcomer1989** [comment]
After your Error message have to be an array with more information. Can you please share use this also.. Thx!

**Comment by kevinboeger** [comment]
https://i.imgur.com/jbXkbK5.png mehr hab ich dort ned

**Comment by Newcomer1989** [comment]
Das reicht aber schon völlig aus. Entweder ist die Verbindung zur DB unterbrochen oder die DB ist in diesem Moment nicht erreichbar.

Zuvor hat er wohl mehrere Minuten lang Avatare geladen, was gerade nach längerer Offline-Zeit sein kann. Jedoch ist die Geschwindigkeit sehr langsam, wie es scheint.
Auf welchen Level hast du den Slowmode aktiviert? Findest du im Webinterface unter der Ruprik TeamSpeak.

**Comment by Newcomer1989** [comment]
Scheint sich geklärt zu haben, da keine Rückmeldung mehr erfolgt.
