### ISSUE TITLE
Ranksystem bugs

### ISSUE THREAD

**Issue by xWarzywko** [Newcomer1989/TSN-Ranksystem#476]
Hi, i have a big trouble with ranksystem. Namely ranksystem works fine for some period of time, after that Ranksystem moves 1 random guys and move him to all channels on my TS3 server after moves on all channels he stop and moves next user in a while. Any suggestions?

**Comment by bykidi** [comment]
![default](https://user-images.githubusercontent.com/1337953/38304108-ede76790-3810-11e8-9f29-9c0914f161ac.png)

**Comment by bykidi** [comment]
that was april first joke, it should be disabled now
make sure that your server clocks are running fine
if they are - enable any slowmode

**Comment by xWarzywko** [comment]
Nice joke XD

**Comment by Newcomer1989** [comment]
> Nice joke XD

Thx!
Its designed only to do that on 1st april. So it shouldn't happen now.
