### ISSUE TITLE
Lädt die Icons nicht runter

### ISSUE THREAD

**Issue by TheChaosToast** [Newcomer1989/TSN-Ranksystem#477]
Servus,

ich habe meine ganzen Icons im Teamspeak geändert und wollte diese in das Ranksystem übernehmen. Nachdem ich den Bot neu gestartet habe bekam ich die Meldung das der Bot ordnungsgemäß funktioniert. Aber es waren noch die alten Icons hinterlegt. Also hab ich den Bot gestoppt, den Ordner "tsicons" geleert (bis auf die .gitignore und rs.png) die Schreibberechtigung für den Ordner "tsicons" überprüft (777) und den Bot nschließend neu gestartet. 

Auch hier wieder alles ordnungsgemäß gestartet nur die neuen Icons nicht im Ordner. Bug oder Feature ;)
Wäre lieb wenn wenn es wieder funktioniert - Danköö

**Comment by Shad86** [comment]
Hallo versuch mal folgendes:

Das Rank-system ausschalten und dann diesen sql befehl absetzen ->

DELETE FROM groups

Danach wieder starten, dann sollten die Icons eig. geladen werden.

**Comment by TheChaosToast** [comment]
Jap, hat super funktioniert. 

Vielen Dank :)
