### ISSUE TITLE
Planet TeamSpeak stellt alle Dienste ein

### ISSUE THREAD

**Issue by xopez** [Newcomer1989/TSN-Ranksystem#478]
Moin,

ich wollte nur drauf hinweißen, dass Planet TeamSpeak zum 30.04.2018 alle seine Dienste einstellen wird.
Einfach weil es auf /stats/index.php eine Verlinkung dahin gibt.
Ab Zeile 439:
```
<tr>
	<td><?PHP echo $lang['stix0045']; ?></td>
	<td><?PHP if ($sql_res['server_weblist'] == 1) { echo '<a href="https://www.planetteamspeak.com/serverlist/result/server/ip/'; if($ts['host']=='localhost' || $ts['host']=='127.0.0.1') { echo $_SERVER['HTTP_HOST'];} else { echo $ts['host']; } echo ':'.$ts['voice'] .'" target="_blank">'.$lang['stix0046'].'</a>'; } else { echo $lang['stix0047']; } ?></td>
</tr>
```
Somit wird es, denke ich, in Zukunft auch nicht mehr möglich sein, seinen TS abzufragen.

Meldung auf jeder Seite von Planetteamspeak.
![grafik](https://user-images.githubusercontent.com/28950736/38405619-0c44e30a-3971-11e8-90b7-314ccb3a9753.png)

**Comment by DanielR92** [comment]
Das macht nichts, da sein PHP-Framework unabhängig von seinem Server läuft...

**Comment by xopez** [comment]
Das das nichts macht ist mir soweit auch klar.
Meine nur, man sollte die Verlinkung rechtzeitig entfernen, sodass nicht andere die ganze Zeit sagen, dass der Link nicht klappt.

**Comment by bbashy** [comment]
Warning message has gone since then.

**Comment by xopez** [comment]
It's really gone. Maybe it was their april fools. standing there on 1st April made me think twice about it. But standing there on the sixth day I thought it's really happening.

**Comment by Newcomer1989** [comment]
Whatever it was, there were much changes inside the TS3 PHP Framework the last weeks.
I will try to update it with the next version of the Ranksystem.
