### ISSUE TITLE
Error 0: invalid reply from the server

### ISSUE THREAD

**Issue by Vyzeax** [Newcomer1989/TSN-Ranksystem#479]
Hey,

ich habe heute versucht, den Bot auf meinen neuen Server connecten zu lassen. Jedoch kam es beim connecten zu folgendem Fehler: Error 0: invalid reply from the server. Ich habe die Daten komplett korrekt eingetragen, auch der Querylogin ist korrekt. Kurzzeitig steht dort etwas von Flood-Ban, aber da ich den Serveradmin-Login verwendet habe, kann das eigentlich auch nicht sein.

Bitte um Hilfe, danke im Voraus!

Vyzeax

**Comment by Shad86** [comment]
Bitte nochmal Ip / Whitelist und Query port kontrollieren:

> invalid reply from the server
Die Ursache für diese Fehlermeldung ist meistens ein Flood Ban. Die andere mögliche Fehlerquelle ist die falsche Zahl als TCP Query Port (nämlich der Port eines anderen TCP Dienstes).

**Comment by Vyzeax** [comment]
Hey, da ich den Bot über den gleichen V-Server laufen lasse, müsste eigentlich kein Eintrag auf der Whitelist erforderlich sein. Ein anderer Bot hat mir dann die Fehlermeldung eines Flood-Banns gegeben.
Die Admin-Query müsste das aber eigentlich ignorieren können..

**Comment by Shad86** [comment]
Das kommt immer darauf an wie die Whitelist aussieht. Im Regelfall steht 127.0.0.1 drin, (ich hab aber durchaus auch schon komplett leere Query_IP_Whitelist.txt's gesehen) aber sobald du mit der Public IP verbindest ist diese in der Whitelist einzutragen (Egal ob gleicher Server oder nicht).

**Comment by Vyzeax** [comment]
Okey, werde ich nachher ausprobieren. Danke :)

**Comment by Shad86** [comment]
Nur damit ich nun weiß ob man das ganze nun schließen kann - hat es denn nun geklappt? :)

**Comment by Shad86** [comment]
Da ich keine weitere Antwort erhalten habe, sehe ich das Problem als gelöst und schließe es hiermit.
