### ISSUE TITLE
Ranking in a channel

### ISSUE THREAD

**Issue by EGXZ** [Newcomer1989/TSN-Ranksystem#480]
Hi,

Do you think we can put the daily, weekly, monthly (our choice) information in a channel?

#1 %recipent% - 50 hours

And one last question what is the file to replace TS-N Ranking by my server name?

Sincerely,

**Comment by Shad86** [comment]
Just to make it clear:

Do you mean, that you can choose about a single user
or
Choose between Top 10 from users of day,week,month

> And one last question what is the file to replace TS-N Ranking by my server name?

It is planned for the future, to make it easier to edit but atm see it as an credit for our Software as it is for free and without any other annoying advertise.

regards

Shad86

**Comment by EGXZ** [comment]
Oh okay I see, so I'll leave it to reward your incredible work that turned the ts3 servers upside down.

And for the question the same principe as on the daily weekly & monthly website.

But on a channel because it is a faster access and the human likes to play with his ego ^')
