### ISSUE TITLE
Feature: Zeit Berechnung

### ISSUE THREAD

**Issue by Yatheria1** [Newcomer1989/TSN-Ranksystem#481]
Wie währe es mit einer Funktion wo User Berechnen können wie viel Zeit sie brauchen um auf ein gewisses Level zu kommen? (Bsp: ich bin Level 25 und möchte wissen wie lange ich bis Level 30 Brauche.)

**Comment by Newcomer1989** [comment]
Das sollte mit der Funktion "!nextup" möglich sein. Diesen Chat-Command kannst du im Webinterface aktivieren.
Dort gibt es auch die Variante "allowed - all next ranks".
