### ISSUE TITLE
User-Zeiten scheinen beim wiederherstellen eines Backups zu verschwinden

### ISSUE THREAD

**Issue by Galaxy200** [Newcomer1989/TSN-Ranksystem#483]
Hallo,

Ich habe heute meinen kompletten Server neuinstalliert und somit auch nochmal meinen TeamSpeak Server neu eingerichtet, nun bin ich an den Punkt angekommen das Ranksystem wieder einzurichten, jedoch wollte ich dafür die alte Datenbank verwenden damit meine User ihre Zeiten nicht verlieren jetzt zum Problem: Beim Starten des Bots gibt das System allen Usern den ersten Rang statt den, den sie vorher hatten, obwohl die Datenbank von mir Importiert wurde. Ist das ein bekannter fehler und wenn ja was kann ich dagegen machen?

**Comment by Galaxy200** [comment]
Es scheint so als wenn die Zeiten der User resettet wird wenn die Datenbank ID ersetzt wird (Weil die User ja nach neuer TS Installation auch neue ID's haben)

**Comment by xopez** [comment]
Ich weiß ja nicht wie du die Daten zurückgespielt hast. Ich kann nur folgendes sagen:
Ich habe vor 2 Wochen auch meinen dedicated Server resetted. Habe vorher von der datenbank ein Abbild gemacht (bei mir über Plesk) und danach wieder das abbild importiert. Und es läuft ohne Probleme.

**Comment by Shad86** [comment]
Dieses Problem tritt nur auf wenn man kein Fullbackup des Ts-Ordner macht.

Bei Snapshots bekommen die User eine neue Id

Ich bin gerade unterwegs - von daher schau mal im Webinterface nach da gibt es einen Schalter wo man den redet bei neuen Id‘s verhindern kann

**Comment by Galaxy200** [comment]
Danke @Shad86 das hat funktioniert. Hätte ich idiot mal selber genauer geschaut hätte ich dieses Issue nicht mal Öffnen müssen :D

**Comment by Newcomer1989** [comment]
Nur der vollständigkeithalber, sprich für andere, die diesen Thread hier finden.

Bitte auch das Wiki beachten. Hier sind alle Schritte beschrieben.
https://github.com/Newcomer1989/TSN-Ranksystem/wiki#changed-teamspeak-host--server---mitigation-old-ranksystem
