### ISSUE TITLE
i can change the style in the stat site

### ISSUE THREAD

**Issue by AndryGabry01** [Newcomer1989/TSN-Ranksystem#486]
I want to delete a button from the page, is it possible?

**Comment by Newcomer1989** [comment]
Sure it is possible.. Unfortunately we can't support changes like this. At this moment, we start with supporting such changes, we will not be able to bring any more update with bug fixes or new features. Cause supporting individual solutions would take the whole of our time.
We ask for your understanding.. Thx!
