### ISSUE TITLE
Add time to the user

### ISSUE THREAD

**Issue by NOFEAR2h** [Newcomer1989/TSN-Ranksystem#487]
Add time to the user not work...
i added 1 day for UID (client) and save, while the query to the database is normal.
The data changes literally for 1 second and return to the original position in which they were.
I reinstalled the whole system. I did not touch only the database because it's important. There are no errors in the logs

**Comment by Shad86** [comment]
Is already knowen Bug -> https://github.com/Newcomer1989/TSN-Ranksystem/issues/460#issuecomment-374001573

Stop the bot 

Now choose the user you want to add time 

enter the desired time and press save

then start the ranksystem again.

regards

**Comment by NOFEAR2h** [comment]
Thanks. Not immediately noticed the headline. I do not have much knowledge of English to immediately notice)
