### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by growndex** [Newcomer1989/TSN-Ranksystem#488]
Hello..
I can not install the platform I'm saying that the php_exec function is disabled. How do I fix it? Like hosts do not approve my feature on enable ...? Please help me
![screenshot_2](https://user-images.githubusercontent.com/36424033/39646437-1b923d88-4fe4-11e8-85eb-3c3597b577b3.png)

**Comment by growndex** [comment]
Hostu is bought from a company .. Is not another method?

**Comment by Shad86** [comment]
Well then the only solution would be to go to the ts-n.net Teamspeak or you can also use the contact formular https://ts-n.net/contact.php. 

There you can ask for a sponsored ts3-ranksystem hosting
