### ISSUE TITLE
SQL Query / I/O Hard Drive

### ISSUE THREAD

**Issue by Knot3n** [Newcomer1989/TSN-Ranksystem#489]
Hi,

ich weiß nicht ob das gewollt ist oder ein Bug ist deshalb mache ich mal darauf aufmerksam.

Zu sehen auf dem ersten Bild ist das wirklich viele Prozesse gestartet werden vom TSN PHP Script zum abrufen der Datenbank.

Beim zweiten Bild ist zu sehen das echt viele Anfragen gemacht werden. 
Waren auch schon über 400 mal.

Beim dritten Bild, sieht man andauernde PEAKS der SSD.

Sobald ich die mysql Datenbank neustarte hab ich paar Minuten ruhe bis dann die Prozesse wieder hochkommen. 

Kann man das Optimieren, ist das so gewollt / richtig?
Was liest der Bot / das PHP Script als von der DB das es knapp jeweils immer 500 Kb/s bis 1-2 MB Reads sind.

![process](https://user-images.githubusercontent.com/27648479/39675908-b9beec3a-5161-11e8-995a-872412000892.JPG)

![sql](https://user-images.githubusercontent.com/27648479/39675911-bc9a8a86-5161-11e8-99e1-c0c1396f0746.JPG)

![disk](https://user-images.githubusercontent.com/27648479/39675913-c0b64b82-5161-11e8-839f-0124567b8c04.JPG)

**Comment by Shad86** [comment]
Die vielen geöffneten Prozesse könnte unter Umständen ein Hinweiß darauf sein, das er viel auf bzw. über eine HDD schreibt (hhds = langsam braucht Zeit = hoher IO Wert) und eben braucht bis er das ganze abgearbeitet hat.

Wenn mysql an sich optimiert ist liegt das meiste im Cache und wird darüber gehandelt. Was dazu führt das nur minimal auf der hdd lesen+ schreiben stattfindet und somit sich der IO Wert auch verbessert.

Sollten die vielen Prozesse weiterhin offen bleiben müsste man sich das mal genauer anschauen (ich hab es gerade mal bei mir überprüft und da ist max 1 sleep  Prozess dauerhaft da +1-2 "unterprozesse" ab und an mal am triggern)

Ich nutze aber sowohl eine optimierte mariadb als auch ssd's

**Comment by Knot3n** [comment]
Dann werde ich die MariaDB mal opitimieren und dann berichten.

Sind übrigens SSD's die verbaut sind. 

Danke schon mal für das schnelle Feedback.

**Comment by Shad86** [comment]
Selbst wenn es SSD's sind, sind auch diese um einiges langsamer als so ein Ramriegel :)

SSD's = von 200 MB/s bis zu 550 MB/s / RAM = von 1900MB/s bis zu 3700 MB/s -> das nur als kleiner fun fact =D

Weil an und für sich geht es bei der Optimierung mehr darum, viel in den Cache zu legen. 
So sind dann die meisten Lese- und Schreibvorgänge im Ram.

Noch als wie ich finde, wichtigen Hinweiß

Eine Optimierung kann man wiederum auch nur dann hinbekommen, wenn man den freien Ram zur Verfügung hat. 
Weil wenn dieser z.B. voll ausgelastet ist, kann man natürlich auch nicht mehr wirklich etwas in den cache legen bzw. wenn man es in den cache legt würde es wohl im swap landen.
Wie wir alle wissen, ist der swap die HDD / SSD, Gewinn wäre hier also fast 0.

**Comment by Knot3n** [comment]
Naja ich hab 16GB Ram drin, was ich auch aufstocken könnte wenn ich es brauche.

Davon werden Maximal 15-20 % benutzt.

Demnach ist da platz, 
Ich habe nun paar Optimierungen vorgenommen, trotz allem ist bei IOTOP zu sehen das mysql viel schreibt / liest. 

Wäre es möglich ggf. deine / eure Cache Optimierungen zu bekommen?

**Comment by Shad86** [comment]
heißt das nun das, sich gar nichts geändert hat? Also sind die IO Werte komplett gleich?

Configs abgeben macht keinen Sinn, weil die auf jedes System eigens abgestimmt werden müssen :/

**Comment by Shad86** [comment]
Bitte eins nicht vergessen, das schreiben und lesen wird nur verlagert (in dem fall an eine performantere Stelle), so dass dein IO Wert sich bessert und du an Performanz gewinnst. 
Die schreibe und lese Vorgänge selbst verschwinden dadurch natürlich nicht.
Es wird sozusagen nur das ganze lesen und schreiben auf der Festplatte reduziert, weil wie schon zu Anfang gesagt, das die meisten einbusen bringt.

**Comment by Knot3n** [comment]
Bin halt wenn man das wirklich nicht "verkleinern" kann, das TSN System auf nen zweit System zu legen anstatt auf die Kiste wo wirklich viel passiert.

**Comment by Shad86** [comment]
Ich kann mir das ganze gerne mal mit dir zusammen auf dem ts-n.net (<-ip) ts3 anschauen. Vielleicht können wir gemeinsam noch was rauskitzeln

**Comment by Knot3n** [comment]
Hi,

das wäre sehr nett, wie siehts mit heute abend aus?

**Comment by Shad86** [comment]
Abends ist bei mir schlecht, wenn abends dann schon recht früh, so ab 17/18 Uhr

**Comment by Knot3n** [comment]
Wir können das gerne jetzt machen nur ich hab kein Mikro hier, da ich auf der Arbeit bin :) 
18 Uhr kurz nach 18 Uhr würde auch passen. 👍

**Comment by Shad86** [comment]
Kurz nach 18 Uhr passt auch, ist denke ich auch besser, weil man dazu etwas ruhe und Zeit braucht
