### ISSUE TITLE
Bot Lost Connection

### ISSUE THREAD

**Issue by Joele25** [Newcomer1989/TSN-Ranksystem#49]
I've got a problem with the teamspeak bot. it lost his connection immediatly. If I set it on Highdelay It loose it after 9 seconds. The ranksystem script and the server teamspeak are in the same server, is that a problem?

**Comment by Shad86** [comment]
The The Folder from the rank system in the Webspace Folder is set to www-data recursiv?

Just in case you also can try to set your own ip from the Server into the Query_IP_Whitelist.txt (you can find this file in your TS3-Server folder)

Some additional questions:

How big or small is your Server?

How Much CPU's / How Strong (GhZ)
How Much Ram

regards

Shad86

**Comment by Joele25** [comment]
this is my personal directory /var/www/vhosts/deltaforceitalia.eu/httpdocs/ranksystem
I tryed also to whitelist the ip but It didnt work

**Comment by Joele25** [comment]
I just created now www-data and add it to www-data group. I also run your command and this is what I get http://i.imgur.com/61pmrUw.png

**Comment by Newcomer1989** [comment]
How looks your cpu usage?

Does the ranksystem.log says any special?

You set all needed TeamSpeak permissions?

```
TeamSpeak 3 Server Query Account with Permissions:

    b_virtualserver_client_list
    i_client_private_textmessage_power
    i_group_member_add_power
    i_group_member_remove_power
    b_client_remoteaddress_view
    b_virtualserver_servergroup_list
    b_virtualserver_client_dbinfo
    b_virtualserver_client_dblist
    b_icon_manage
    i_ft_file_browse_power
    i_ft_file_download_power
```

**Comment by Joele25** [comment]
Ranksystem just say that the bot is connected and it's working, the server permission is perfect and all can I say is that one of my friend host that script in another server and it worked (using always my ts server).. So I think it's a problem of bot connecting in localhost...

**Comment by Joele25** [comment]
CPU usage 2.8% RAM usage 3.06%

**Comment by Shad86** [comment]
I also let him connect over localhost and dont have any issues with it.

can you do following command:

`uptime`

So that we know if the load is also fine :)

**Comment by Joele25** [comment]
19:38:01 up 19:48,  2 users,  load average: 0.28, 0.31, 0.18

**Comment by Newcomer1989** [comment]
Check there is nothing which ends the process.
For example:
- restart PHP
- restart Webserver
- ...

**Comment by Joele25** [comment]
Nothing changed... T_T   What's about the fact that changing delay it crashed after 9 second instead of crashing immediatly?

**Comment by Shad86** [comment]
you start it also with "sudo -u www-data php /path/to/your/websever/path/to/ranksystem/worker.php check >/dev/null 2>&1" because that is important - because if you save something and you start it as root he cant start it again.

regards

Shad86

**Comment by Joele25** [comment]
Yes I do

**Comment by Shad86** [comment]
hm for the moment i dont have an idea and here it is already 11:30 p.m. (living in germany) so im also a little bit tired.

**Comment by Joele25** [comment]
Same here, thanks a lot! my teamspeak is deltaforceitalia.eu, feel free to join ask for "Asder17"

**Comment by Newcomer1989** [comment]
Inside the jobs/bot.php you'll find the following line

`error_reporting(0);`

Please delete this line and run the Bot again. 
Post us here the logs, you get in ranksystem.log

**Comment by Joele25** [comment]
PHP Notice:  Undefined variable: dbname in /var/www/vhosts/deltaforceitalia.eu/httpdocs/ranksystem/jobs/bot.php on line 58
PHP Warning:  Missing argument 2 for check_shutdown(), called in /var/www/vhosts/deltaforceitalia.eu/httpdocs/ranksystem/jobs/calc_user.php on line 83 and defined in /var/www/vhosts/deltaforceitalia.eu/httpdocs/ranksystem/jobs/bot.php on line 65
PHP Notice:  Undefined variable: dbname in /var/www/vhosts/deltaforceitalia.eu/httpdocs/ranksystem/jobs/bot.php on line 58
PHP Warning:  Missing argument 2 for check_shutdown(), called in /var/www/vhosts/deltaforceitalia.eu/httpdocs/ranksystem/jobs/get_avatars.php on line 9 and defined in /var/www/vhosts/deltaforceitalia.eu/httpdocs/ranksystem/jobs/bot.php on line 65
PHP Notice:  Undefined variable: dbname in /var/www/vhosts/deltaforceitalia.eu/httpdocs/ranksystem/jobs/bot.php on line 58
PHP Warning:  Missing argument 2 for check_shutdown(), called in /var/www/vhosts/deltaforceitalia.eu/httpdocs/ranksystem/jobs/update_groups.php on line 8 and defined in /var/www/vhosts/deltaforceitalia.eu/httpdocs/ranksystem/jobs/bot.php on line 65
PHP Warning:  Missing argument 2 for check_shutdown(), called in /var/www/vhosts/deltaforceitalia.eu/httpdocs/ranksystem/jobs/update_groups.php on line 24 and defined in /var/www/vhosts/deltaforceitalia.eu/httpdocs/ranksystem/jobs/bot.php on line 65
PHP Fatal error:  Cannot use string offset as an array in /var/www/vhosts/deltaforceitalia.eu/httpdocs/ranksystem/jobs/update_groups.php on line 56

**Comment by Newcomer1989** [comment]
Problem solved via remote session. 

It was a special case where something was wrong with the groups. So on first run changed the jobs/update_groups.php

`if (!isset($sqlhisgroup['0']) || $sqlhisgroup['0']['iconid'] != $sIconId || $iconarr["i".$sIconId] > $sqlhisgroup['0']['icondate']) {`

and replaced it with

`if (!isset($sqlhisgroup['0'])) {`

After first run stop the Ranksystem and changed it back.
