### ISSUE TITLE
Boosters

### ISSUE THREAD

**Issue by EGXZ** [Newcomer1989/TSN-Ranksystem#490]
Hi,

I organized for Easter an experience booster, but I removed the boosters to the person before they end, but now as soon as I put it to someone it automatically deletes itself I have to put it manually, how do I "reset" the fact that the booster does not delete itself.^^?

**Comment by Shad86** [comment]
The Boost shouldn't be removed manually as the time will not be reset. If you did so, then following will happen: 

you give someone again the boostgroup but now only the rest of the time as you removed the group the last time gets counted. So it my looks like the boost is to "short" but in fact he just finish the boost - what you interrupt.

As there is no reset function for it, you may have to re-assign the boost and for the next time be sure to not manually interrupt the boost.

**Comment by Shad86** [comment]
Btw. we discussed this Situation already (so it shouldn't be something whats "new" to you) ->https://github.com/Newcomer1989/TSN-Ranksystem/issues/394

**Comment by EGXZ** [comment]
No no,

I actually knew the issue but was looking for a thing to "skip" the delete.^^

**Comment by Shad86** [comment]
> If you do this, the rest of the boost time will be retained in the database and resumed as soon as you reset the group to him. 
so if you want to avoid this behavior, pls don't remove the boost group manually.
(https://github.com/Newcomer1989/TSN-Ranksystem/issues/394#issuecomment-362724185)

But for now with this second issue it should be to 200% clear that there is no reset function for the boost thing - IF you manipulate the boost group manually. ;)

regards

Shad86
