### ISSUE TITLE
1024 characters ?

### ISSUE THREAD

**Issue by 3cmXD** [Newcomer1989/TSN-Ranksystem#492]
Good morning,

I was wondering why the messages aren't 100% cutomizable? I mean I want to say that on the small box it does not accept the 1024 of TeamSpeak she is blocked with 602 what is strange... ?

**Comment by Newcomer1989** [comment]
You can add a max length of 500 characters inside this fields.

TeamSpeak counts this characters different, thats why you will come to more characters there.

The most simple and fastest way were to set the limit to 500. If you can exactly exlpain, how TeamSpeak counts his signs, we can perhaps increase it. But then we need to be sure, to count it on the same way like TS.

**Comment by Newcomer1989** [comment]
Priority at the moment is not for this. It is not a bug.
If someone wants to implement the algorithm to be sure don't exceed the 1024 characters, feel free to make a pull request.
