### ISSUE TITLE
FQDN in Verification-Channel-Link is wrong

### ISSUE THREAD

**Issue by Schnookeuz** [Newcomer1989/TSN-Ranksystem#493]
Hey Guys!

I saw that the link for the verification channel on /stats/verify.php is wrong.
If V-Channel-ID is 1234 and the FQDNs are as this:
TS: ts.example.com
Ranksystem: rank.example.com
...the link at the first step shows "ts3server://rank.example.com:9987?cid=1234"

Yes, that works if Ranksystem and TS-Server are on the same machine and IP, but if the machine has two IPs and the services are assigned to each of them, then it will not work.

Greetz
Schnoo

**Comment by Newcomer1989** [comment]
On building the link, your TS3 address will be checked (Webinterface - TeamSpeak - TS3 Hostaddress).

If it is a local ip address or "localhost" it can only take your domain "rank.example.com". For other user, the local address wouldn't be reachable!
In this case your webserver and your TS3 are on the same host machine. If there is nothing wrong with your DNS and network routing the address "rank.example.com" is valid and should be reachable for the user!

If your TS3 address is not a local one, the Ranksystem will using this one to build the validation link -> Should be no problem.

So one question to you: How looks the TS3 address in your case?
