### ISSUE TITLE
Cannot start session

### ISSUE THREAD

**Issue by TheSoulrester** [Newcomer1989/TSN-Ranksystem#497]
Ich habe das Problem, dass direkt nach der Installation der Bot nicht funktioniert...
Nach der Installation wird man auf /webinterface/ geleitet, dort kriege ich aber leider nur einen PHP Error:

> 
Warning: session_start(): Cannot start session when headers already sent in /www/htdocs/xxxxxx/ranksystem/webinterface/bot.php on line 2

Warning: Cannot modify header information - headers already sent by (output started at /www/htdocs/xxxxxxxx/ranksystem/webinterface/bot.php:1) in /www/htdocs/xxxxxxxx/ranksystem/webinterface/bot.php on line 162

**Comment by Newcomer1989** [comment]
Bitte alle Cookies im Browser von deiner Website mal löschen und dann das Webinterface erneut aufrufen.

Regulär solltest du auf die webinterface/index.php geleitet werden. Diese bietet dir die Login-Seite.

Bsp.:
https://ts-n.net/ranksystem_dev/webinterface/

**Comment by TheSoulrester** [comment]
hm, ich habe einfach nochmal alles neu installiert gehabt und ab dann ging es ohne probleme

manchmal poppt aber mittlerweile folgendes auf:

>  Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /www/htdocs/w0173b8a/ts3_ranksystem/webinterface/bot.php:1) in /www/htdocs/w0173b8a/ts3_ranksystem/webinterface/bot.php on line 2

**Comment by Newcomer1989** [comment]
Deine Fehlermeldungen mit den Sessions könnte am Hoster liegen. Ggfs. schleust der noch etwas dazwischen, was vor dem Session-Aufruf jedoch nicht passieren darf. Aus Sicht des Ranksystems ist da nichts, was diese Meldung verursachen könnte.

Zu dem Cronjob: Welchen Sinn sollte eine solcher URL-Aufruf haben?
Der Bot läuft grundlegend dauerhaft. Einzige Aufgabe des Crons ist es, den Bot neu zu starten, falls er gecrasht ist.

**Comment by TheSoulrester** [comment]
das scheint ja das problem zu sein: er läuft nicht dauerhaft durch, 
deswegen will ich ihn ja per cronjob "neustarten" - die url domain.tld/worker.php rufe ich regelmäßig auf, aber er startet nicht neu?

ich habe gedacht, dass dieses "check" ein parameter ist? es scheint ja auch noch "parameter" zu geben wie "start, status,..."?

**Comment by Newcomer1989** [comment]
> das scheint ja das problem zu sein: er läuft nicht dauerhaft durch,

Da wäre es sinnvoll zunächst Ursachenforschung zu betreiben, wenn es tatsächlich so häufig passiert.
Im Regelfall sollte es nur erforderlich sein, wenn der TS3 Server oder die DB neu gestartet wird. Da ist es auch kein Beinbruch, eben den Bot mal manuell zu starten. Sprich im Regelfall wird der Cron nicht unbedingt benötigt.

> deswegen will ich ihn ja per cronjob "neustarten" - die url domain.tld/worker.php rufe ich regelmäßig auf, aber er startet nicht neu?

Das ist ja super, wenn du einen Cronjob hast. Dann lege den Bot einfach auf die gleiche Machine und alles ist gut ;-)

> inwiefern ist es möglich, den worker mit parameter aufzurufen wie zum beispiel domain.tld/worker.php?check

Parameter sind eine ganz schlechte Idee. Oder was hälst du davon, wenn irgend jemand einfach mal über den URL Aufruf deinen Bot beendet?
Wenn du das so unbedingt möchtest, musst du dir es selbst in die worker.php programmieren. Ich jedenfalls sehe es als Sicherheitslücke!

**Comment by TheSoulrester** [comment]
ahh, also versteh ich das so, dass nur der cronjob auf der selben instanz (selbe ip-adresse?) den bot wieder neu starten lässt?

habe aktuell einen externen cronjob dienst - d.h. das würde es erklären, wieso der worker das ranksystem nicht neu startet :(

wie finde ich am besten heruas, wieso der bot sich "aufhängt"? ts3 startet nicht neu,db wird auch nicht neu gestartet

**Comment by Newcomer1989** [comment]
> ahh, also versteh ich das so, dass nur der cronjob auf der selben instanz (selbe ip-adresse?) den bot wieder neu starten lässt?

Du kannst den Bot nur über das Webinterface starten oder alternativ über die command-line (shell).
`php worker.php start`

> wie finde ich am besten heruas, wieso der bot sich "aufhängt"? ts3 startet nicht neu,db wird auch nicht neu gestartet

Dazu mal in die Ranksystem log schauen, ob die etwas sagt. Falls nein, muss es an der Systemumgebung liegen. Dann in die Logs deines Systems schauen.

> aber: wieso startet denn der bot auch nicht neu, wenn ich die domain "domain.tld/worker.php" manuell aufrufe?

Dafür ist die Worker.php nicht gedacht. Diese kann nur über die command-line bedient werden. Sonst könnte jeder den Bot über die URL starten/stoppen, wenn er sie kennt.

**Comment by vans1208** [comment]
Moin zusammen. 
Habe genau das gleiche Problem. Bin auch bei all. Inkl. Das ranksystem läuft soweit gut. Also in den Logs Wird auch nichts angezeigt. Bei mir ist auch das Problem das der bot im ts nach 10-15 Connection lost hat. Und muss ihn dann neu starten. Dann wieder die Verbindung verliert. Hab ihn auch in die whiteliste eingefügt im ts. Aber hilft auch nichts.

**Comment by Shad86** [comment]
> 10-15
gehe mal davon aus das da noch min. fehlt?

Wenn dies tatsächlich der Fall ist, mal den Hoster fragen ob der Prozess Systemseitig gekillt wird. (Könnte sein, das eben bei zu hoher Auslastung oder zu lang laufendem Prozess diese gekillt werden - eben systemseitig oder manuell)

**Comment by vans1208** [comment]
Ja klar meinte min. 😬 sorry. Ja habe heute mal den Hoster geschrieben. Warte jetzt auf die Antwort. Und gebe dann Bescheid. Weil komisch ist es schon.

**Comment by vans1208** [comment]
Haben jetzt hin und her geschrieben mit den Provider. Er meinte ich zitiere Macht Ihr Script eine Ausgabe oder dergleichen?
Auf dem Server gibt es ein Idletimeout. Das heißt nach spätestens 10 Minuten wird das Script entsprechend beendet. Auf einem SharedServer-Tarif lässt sich dies entsprechend nicht erhöhen.

Stelle ich mir die Frage ob es möglich ist das der bot nicht alle 15 min das leaderboard aktualisiert sondern vll. Alle 10 oder so.

**Comment by TheSoulrester** [comment]
Und oder vlt tatsächlich mitbienem Link Neustartbar ist. Könnte man ja im webibterface als Einstellung aktivierbar machen - und dann wird ein cryptischer Link generiert sodass nicht jeder Handel den Bot starten/deaktivieren kann

**Comment by Shad86** [comment]
> Stelle ich mir die Frage ob es möglich ist das der bot nicht alle 15 min das leaderboard aktualisiert sondern vll. Alle 10 min. oder so.

Das würde das ganze unperformant machen und man müsste ja dahingehend mehrere Stellen nur dafür anpassen.

Einzige Möglichkeit wäre eben einen cronjob einzurichten, wenn ihr beide nur das kleinste Paket nutzt wäre das natürlich nicht möglich. 
Dann bliebe nur noch die Möglichkeit für euch es auf einem v-server zu installieren oder ein Sponsored Hosting von ts-n.net zu nutzen.

**Comment by vans1208** [comment]
Ok. Wie läuft da das ab mit der cronjob variante. Habe die etwas  größere Paket. Sprich 25 cronjobs frei.

**Comment by Shad86** [comment]
> Login in to your server via ssh.
> 
> Enter the command "crontab -e" (In vim you have to press "i" to be able to edit the text)
> 
> Paste the following line in a new line (you have to edit the path):
> 
> */10 * * * * sudo -u www-data php /path/to/your/websever/path/to/Ranksystem/worker.php check >/dev/null 2>&1
> 

https://ts-n.net/ranksystem.php#install

**Comment by TheSoulrester** [comment]
da würde es schon weiter anfangen: ich habe zwar nicht dieses paket, ABER: ssh zugang ist in dem 2 paket mit 25 cronjobs NICHT vorhanden

**Comment by TheSoulrester** [comment]
so, ich habe mir mal einen test-account bei all-inkl bestellt und das ganze mit dem cronjob probiert: es funktioniert nicht so, wie es zu funktionieren hat da man den cronjob nicht per ssh (konsole) erstellen kann.

das script wird wie oben schon beschrieben nach 10 min beendet
https://i.imgur.com/Tpy96QH.png

**Comment by vans1208** [comment]
Ja das ist ja das Problem. Du kannst nicht per ssh auf die Konsole zugreifen. Vll. Sollte man mal fragen ob es möglich ist den cronjob Befehl den Support zu geben. Dann die ihn vll. Ein setzen. Oder

**Comment by Shad86** [comment]
Es ist logisch das man bei einem webspace keinen ssh login hat, dennoch sollte man die Zeile im Webinterface denke ich doch wo eintragen können.

Sonst wäre es ja sinnfrei, wenn man 25 cronjobs zur Verfügung hat sie aber nirgends eintragen kann.

---
Webuser, Zeit und das es php ist wird vermutlich separat eingestellt aber die Zeile an sich sollte dann diese hier sein:

`/path/to/your/websever/path/to/Ranksystem/worker.php check >/dev/null 2>&1`

Falls php nicht separat eingestellt wird:

`php /path/to/your/websever/path/to/Ranksystem/worker.php check >/dev/null 2>&1`

**Comment by Newcomer1989** [comment]
Hat sich wohl erledigt.. Ansonsten einfach noch einmal melden.
