### ISSUE TITLE
[Frage] Wieso str_replace(' ', '', $client_data[x]['name']?

### ISSUE THREAD

**Issue by xopez** [Newcomer1989/TSN-Ranksystem#498]
Hallo,

mir ist soeben aufgefallen, dass bei `top_all.php`, `top_week.php` und `top_month.php` immer die Replacebefehle `str_replace(' ', '', $client_data[0]['name']` von einem Leerzeichen kommen in der oberen Hälfte der jeweiligen Seite. Hat es einen Sinn, dass diese Zeichen entfernt werden?
Im Vergleich unten drunter werden diese nicht angewendet. Deswegen ist der nutzen mir fraglich.

**Comment by Newcomer1989** [comment]
Die ist gedacht um unschöne Zeilenumbrüche zu verhindern.

Nach näherem Betrachten gibt es da aber eine bessere Lösung über CSS (white-space: nowrap;).

Wird mit der nächsten Version (1.2.7) angepasst.
