### ISSUE TITLE
Help me 

### ISSUE THREAD

**Issue by Parzival99** [Newcomer1989/TSN-Ranksystem#50]
Hello 
I try to install the ranksystem on my Debian 8 vserver.
Now i have one problem when i try to install the database withe the insatll.php then come this Erro:

`Database error: SQL Connection failed: SQLSTATE[HY000] [2003] Can't connect to MySQL server on 'My server Addres' (111)`

I hope someone can help me.

**Comment by Newcomer1989** [comment]
The Problem stands inside the message.
'My server Addres' is no valid address!!!

More help you find here:

**Comment by Parzival99** [comment]
no this with my server addres have i written in ther stay my server address
