### ISSUE TITLE
Ranksystem Bot still connected - Stats will be not updated

### ISSUE THREAD

**Issue by ibimslan** [Newcomer1989/TSN-Ranksystem#500]
Hi. The bot was able to see people in the verify channel, but now it stopped working.

I didn't change anything on the linuxserver or on the configs.

**Comment by ibimslan** [comment]
https://i.imgur.com/S9EeKn8.png

**Comment by Newcomer1989** [comment]
Could it has to do something with your problem before, where the database get not updated correct? https://github.com/Newcomer1989/TSN-Ranksystem/issues/499

If I see it right, you Ranksystem isn't running continuously!
https://screenshotscdn.firefoxusercontent.com/images/5c5e6b78-a381-47de-b01c-ea2732f4efd8.png

**Comment by ibimslan** [comment]
ye i dont know what happened. it would be nice if you could help me over teamspeak voice.. i could connect to teamspeak if you're available

**Comment by Newcomer1989** [comment]
sure.. TS address: ts-n.net

**Comment by ibimslan** [comment]
solved

**Comment by Newcomer1989** [comment]
Problem is that utf8-mb4 characters were using on client names.
This is newly supported with TS server version 3.2.0.

How you will matter this problem with 1.2.6?
As long as user with utf8mb4 characters are online:
- The Ranksystem Bot will stay connected to the TeamSpeak server
- But there will be no stats collected anymore
- Also new servergroups and servergroupicons could not be saved into the database, they will continuously downloaded
If all user will utf8mb4 characters will be offline, the stats collecting will go one



We will add this support also to the Ranksystem with the next version 1.2.7.

**Comment by bykidi** [comment]
3 days ago my ranksystem also 'died' like this. What is the quickfix for this problem?

**Comment by Newcomer1989** [comment]
Prevent user from being using utf8-mb4 characters till 1.2.7 is out.

**Comment by Newcomer1989** [comment]
version 1.2.7 is out and should solved the problem
