### ISSUE TITLE
The bot doesn't connect to the ts

### ISSUE THREAD

**Issue by LafaWebDesigner** [Newcomer1989/TSN-Ranksystem#503]
![ts32](https://user-images.githubusercontent.com/36082110/41201489-47eeec68-6cb9-11e8-9169-abcff8f4bed6.PNG)
![ts3](https://user-images.githubusercontent.com/36082110/41201490-480e1cfa-6cb9-11e8-868d-c457a09e097d.PNG)

When i start the bot the log doesn't give me any information, i have installed allt he requirements, the bot is connected to the database, the query password is correct, i don't know what to do!

**Comment by LafaWebDesigner** [comment]
Hi yes, i've fixed it thx! There was a problem in the bot.php fil:
PHP Notice:  Undefined variable: mysqlcon in /var/www/html/rank/jobs/bot.php on line 102
if(!unlink('install.php')) {
changed to
if(!unlink('../install.php')) {

**Comment by Shad86** [comment]
okay thanks for the fast reponse! 👍

**Comment by Newcomer1989** [comment]
I am sure, this were not the problem. Like you posted, it is only a warning, no error..

But it is now working for you, so it is fine :)
