### ISSUE TITLE
2 instances on one server

### ISSUE THREAD

**Issue by TricityGaming** [Newcomer1989/TSN-Ranksystem#504]
Is is it possible to install/have 2 RankSystems in different directories?
I tried it but everytime the Query got banned on the other server for some minutes.

Ist es möglich das RankSystem in zwei unterschiedlichen Ordnern zu installieren und zu nutzen?
Ich habe es bereits versucht aber sobald ich die zweite Instanz gestartet habe, stoppt die Instanz die zu erst gestartet wurde (Wird dann nicht nur gestoppt sondern auch für kurze Zeit gebannt (error 0: invalid response).

**Comment by Shad86** [comment]
Meinst du? => 2 Ranksystem => 1 TS3-Server? Ja das funktioniert. (habe ich persönlich auch so am laufen)

**Comment by monster010** [comment]
klar, geht auch

**Comment by Shad86** [comment]
Ja auch das geht - wenn der bot allerdings gebannt wird ist er wohl nicht gewhitelisted - ich weiß nicht ob man instanzenweit whitelisten kann oder ob man auch für jeden virtuellen server whitelisten muss (in dem Fall muss die public ip des webservers in der Whitelist stehen)

**Comment by TricityGaming** [comment]
Das läuft alles auf ein Server also muss ich das eig. nicht auf whitelisten. Ich probiers dann nochmal, danke für die schnelle Antwort.

**Comment by TricityGaming** [comment]
Irgendwie kriegen die Queries ein Floodbann was kein Sinn ergibt da ja erstens alles localhost ist und zweitens beide Admin Server Query Logins haben (unterschiedliche Logins) und bei der Gruppe die Anti-Flood Limitierung gesetzt ist.

Als Info ich hab auf einen der Server noch ein JTS3Mod installiert, gibt es vielleicht eine Limitierung von max. Queries auf den TeamSpeaks? (Der bleibt aber ohne Probleme connectet)

Und zudem sehe ich gerade nach 5 Minuten ist der Flood Bann immer noch nicht weg und keiner der beiden kann joinen (Auch nicht einzelnd bzw. einer von denen)

**Comment by monster010** [comment]
schau mal beim ts3 server in die query_ip_whitelist.txt, wenn dort nicht 127.0.0.1 drin steht schreib das rein und speicher die datei, dadurch dürften die query's keinen floodban bekommen

**Comment by TricityGaming** [comment]
So hab jetzt nochmal alles durchgeschaut und wieder gestartet (Nach ein paar Minuten). In der whitelist datei stand 127.0.0.1 also localhost IP schon drin. Funktioniert plötzlich jetzt alles. Hoffe das bleibt so wenn nicht meld ich mich.
Danke für die Hilfe 👍 :)
