### ISSUE TITLE
SQL Syntax Error - MySQL >= 8 bzw. MariaDB >= 10.3

### ISSUE THREAD

**Issue by SomeNix** [Newcomer1989/TSN-Ranksystem#505]
`Database error: 42000 Array ( [0] => 42000 [1] => 1064 [2] => You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'except tinyint(1) NOT NULL default '0',grpsince bigint(11) NOT NULL default '0',' at line 1 ) `

Dieser Fehler kommt wenn man das Ranksystem einrichtet direkt nachdem mann die DB Daten eingegeben hat!

Datenbank-Server

    Server-Typ: MariaDB
    Server-Version: 10.3.7-MariaDB-1:10.3.7+maria~xenial - mariadb.org binary distribution
    Protokoll-Version: 10
    Server-Zeichensatz: UTF-8 Unicode (utf8)

Webserver (NGINX Reverse Proxy)

    nginx/1.10.3
    Datenbank-Client Version: libmysql - mysqlnd 5.0.12-dev - 20150407 - $Id: b5c5906d452ec590732a93b051f3827e02749b83 $
    PHP-Erweiterung: mysqliDokumentation curlDokumentation mbstringDokumentation
    PHP-Version: 7.0.30-0ubuntu0.16.04.1

Außerdem der Apache2 Error Log bezüglich des Ranksystems: https://hastebin.com/ekeviwufeq.pas
Nginx Error Log: https://hastebin.com/egadagiyak.cs

**Comment by Shad86** [comment]
Welche version hast du verwendet? hast du diese hier geladen? -> https://ts-n.net/downloads/ranksystem_1.2.6.zip Oder von woanders?

Ansonsten bitte noch einmal eine Neuinstallation mit der von mir verlinkten Version versuchen.

**Comment by Newcomer1989** [comment]
Sind denn Sonderzeichen in DB-Name, DB-User und/oder DB-Passwort enthalten? Ggfs. mal ohne probieren.

**Comment by SomeNix** [comment]
@Shad86 Genau die oben genannte Version habe ich verwendet und ich habe es bestimmt jetzt schon duzend mal neu installiert und auch andere aus unserem Team haben es erfolglos versucht...

@Newcomer1989 Ich habe nocheinmal versucht das Passwort ohne Sonderzeichen 32 Zeichen lang zu benutzen, leider erfolglos...

**Comment by Shad86** [comment]
Also ich hatte nun nochmal Zeit um es mal selbst zu versuchen mit dem installieren.
Ich konnte es reibungslos installieren und mich nach der installation ins Webinterface einloggen.

Zudem habe ich es auch schon in den letzten Wochen 1-2 mal installiert (da ich es ab und an für Leute hoste)

Wenn du es nochmal testen willst:

Beispieldaten um gleiche Voraussetzungen zu haben:

username: rank_rank
passwort: abcdefghijklmnop (16 Zeichen)

System das ich nutze:

Debian 9
php7.2
mariadb 10.1.26

**Comment by SomeNix** [comment]
Also ich konnte den Fehler jetzt eingrenzen und wenn ihr euch mal meine Daten anschaut die ich oben angegeben habe benutzen wir die aktuellste Version 10.3.7-MariaDB, welche nichtder veralteten Version im Ubuntu/Debian Package entspricht. Ich gehe relativ fest davon aus das sich was in den Versionen geändert hat und es dementsprechend zu dem Syntax Error kommt!.

Wir haben den Setup nocheinmal auf einem anderen Server erfolgreich durchgeführt und müssen jetzt leider, trotz mehraufwand die DB Version etc. downgraden.

Nachwievor existiert der Syntax error bei oben genannter Serverkonfiguration.
Wie und ob ihr das Problem für künftige Versionen beheben wollt liegt dann wohl bei euch...

**Comment by Newcomer1989** [comment]
Ok, thx für die Info. Wir werden uns das ansehen. Auch unter MySQL 8 hat sich einiges geändert.

Probleme in Verbindung mit dem Ranksystem scheint es zu geben mit den Versionen:
MySQL ab 8
MariaDB ab 10.3

Mit Version 1.2.7 werden wir versuchen einen entsprechenden Support hierfür herzustellen.
Bis dahin bitte eine ältere Version nutzen, wie SomeNix bzw. wenn möglich das Update der DB-Version noch etwas verschieben.

**Comment by Newcomer1989** [comment]
solved with release version 1.2.7
