### ISSUE TITLE
Phishing verdacht einiger Dateien laut Google Webmasters

### ISSUE THREAD

**Issue by Paddyboy1991** [Newcomer1989/TSN-Ranksystem#509]
Guten Tag, da Ich heute Festellen musste das auf meiner Homepage einige Fehler waren und meine Seite somit als Phising verdacht gelistet ist habe Ich mal ein bisschen nachgeschaut..
Mir fielen auch 3 Dateien von dem Ranking auf (![c3abc638aee485f5e1df36835a36e6b1](https://user-images.githubusercontent.com/16993167/42107182-b6b5456c-7bd6-11e8-8127-601a60f7f4a8.png)
) und wollte mal deswegen nun nachfragen ob denn die Seite auch wirklich sicher ist vor so etwas.
Mit freundlichen Grüßen

**Comment by Paddyboy1991** [comment]
okay wie ich gerade an einer clean Installation sehe gibt es diese Dateien gar nicht..
Kommt man denn nur mit dem serveradmin Passwort denn in das Admin Panel um Dateien hochzuladen? Denn dieses ist bei uns gehackt worden.

**Comment by Shad86** [comment]
Ich wollte gerade schon annmerken, das es diese php dateien nicht von ranksystem seite aus gibt.

Zu keiner Zeit kann man per Webinterface selber etwas hochladen, dieses dient nur dazu den Bot einzustellen, der dann wiederum die benötigen Dateien läd.

Du hast aber die ranksystemdateien schon von der ts-n.net Seite bzw. von hier (Github)? Oder doch von woanders her?

**Comment by Paddyboy1991** [comment]
die Seite habe Ich direkt von der Homepage runtergeladen. Ich schau mir gleich ein Backup an um nachzusehen ob da diese Dateien vorhanden sind..

**Comment by Paddyboy1991** [comment]
Da zu viel passiert ist habe Ich mich für den letzten Punkt entschieden. Jedoch bin Ich immer noch auf der suche wie dies Passiert sein könnte, da Ich lediglich ein WBB und das Ranking sowie einen Bannerbot besitze. Meine Vermutung ist der Bannerbot, jedoch wollte Ich hierbei noch einmal auf Nummer sicher gehen und Nachfragen ob es eventuelle Sicherheitslücken die so etwas bewerkstelligen können hier Vorhanden sind, da der Angriff über PHP Dateien ausgeführt worden sind und sich so eine Backdoor in mein System eingeschlichen hat.
Danke auf alle fälle für die Tipps!
Mit freundlichen Grüßen

**Comment by Newcomer1989** [comment]
Von einem solchen Problem haben wir bisher noch nicht gehört. Auch bietet das Ranksystem keine Funktion zum Upload von Dateien, welche über das Frontend bedient werden könnte.

Der Source Code ist frei zugänglich. Es kann also jederzeit revisioniert/ penetriert werden. Wenn also etwas nicht ganz sauber sein sollte, gerne melden. Sicherheit hat eine sehr hohe Priorität für uns! Bekannte Probleme werden von uns daher bevorzugt behandelt. Stand heute sind alle uns bekannten/gemeldeten Schwachstellen behoben.

Da es keine 100%ige Sicherheit gibt können wir es natürlich nicht gänzlich ausschließen, jedoch halte ich es für sehr unwahrscheinlich, dass das geschilderte Problem vom Ranksystem kommt.
