### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by Parzival99** [Newcomer1989/TSN-Ranksystem#51]
Hey 
I have a problem! When  i try to install the database withe the install.php . I fill all the things in (name; PW etc.) than kome this error:
`Datenbank-Fehler: SQL Connection failed: SQLSTATE[HY000] [2003] Can't connect to MySQL server on '213.136.94.122' (111)`

I hope someone can help me

**Comment by Shad86** [comment]
you have filled in the correct datas and you also have a msql database?

**Comment by Parzival99** [comment]
yes i fill in the right things but i dont have i database

**Comment by Shad86** [comment]
At first, before you want to install the rank system.

Be sure that you have installed a msql-server

debian: apt-get install mysql-server 
ubuntu: sudo apt-get install mysql-server 

(for how to setup up the msql server follow the instructions and / or use google)

if you want to manage it over phpmyadmin:

(Ubuntu) apt-get install phpmyadmin / (debian) apt-get install phpmyadmin

use the logininformations from your msql server.

once your logged in you can create a database (for that also use google)

once you created your database you can install the ranksystem.

**Comment by Parzival99** [comment]
okey i have install mysql but it dont work

**Comment by Parzival99** [comment]
who can i find the loggininformation?

**Comment by Shad86** [comment]
from the msql-server? you create the login while you install the msql-server...

**Comment by Parzival99** [comment]
okey i have install the mysql but i have no login

**Comment by Parzival99** [comment]
this come when i try to login:
`ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
`

**Comment by Shad86** [comment]
puuuuh - if you have time i can help you tomorrow round about CEST 3 p.m. (sunday)

**Comment by Newcomer1989** [comment]
Sorry, this here is no support area!
The first question would be already answered on an other issue https://github.com/Newcomer1989/TSN-Ranksystem/issues/50
All other is basic knowledge for a server admin. You will not need 30 sec. google that to get the answer to your questions!
