### ISSUE TITLE
No graph for Nationalities

### ISSUE THREAD

**Issue by HubertIK** [Newcomer1989/TSN-Ranksystem#510]
I have a problem with my ranksystem website. Everything works fine, except the graph for nationality.

Thats how it looks like:
https://i.gyazo.com/0b0361c411c4b95cc4dcb108a3bf3211.png

There are also some errors on this Website:
https://i.gyazo.com/4cb1a2be169f506c6da1c00794d70754.png

Pls help. Dont know how to fix this.

edit* -> The whole thing was a new installation

**Comment by xopez** [comment]
Doesn't matter if new or upgrade.
Having the same issue.
Website if you wanna look: https://rank.mightful-noobs.de/stats/
Nothing in the error log from apache and PHP.

But I'm not getting an error on the browserconsole.
Firefox 61.0 (64-Bit)

**Comment by Newcomer1989** [comment]
This issue happens, when there are not enough different values to fill at least 5 nations.

We will fix it with the next release.

**Comment by Newcomer1989** [comment]
Release 1.2.8 is out and should fix it
