### ISSUE TITLE
Notice Meldungen auf "Meine Statistiken"

### ISSUE THREAD

**Issue by ZeitZumKiffen** [Newcomer1989/TSN-Ranksystem#512]
Mahlzeit, nach dem neuen Update zeigt er die Statistik Seite total buggy an. Hatte nix weiter an den System dran geändert. Ich war auch mit den Server verbunden, bei anderen Usern ist das Problem auch mit der Seite wurde mir gesagt. Hab es trotzdem mal versucht mein Token etc einzugeben, hat auch danach alles geklappt und es sieht wieder normal aus. Blöde ist, das es nun bei den anderen genau so ist das Sie diese Fehler sehen.

//Hier die Seite für das testen.
https://teamspeak3.zeitzumkiffen.de/stats/my_stats.php
//Hier das Bild
https://gyazo.com/ada6a92ce9209925bc3755d86ddb442a

Mit freundlichen Grüßen

**Comment by Newcomer1989** [comment]
Hier kommen zwei Dinge zusammen.

- Es ist nicht 100 % sauber programmiert. Es ist aber kein Fehler/Bug. In keiner Konstellation kommt es zu einem falschen Ergebnis. Wir werden jedoch mit dem nächsten Update nachbessern

- Die Webserver Einstellungen sind sehr restriktiv, dass auch Notice Meldungen ausgeben werden. Diese gehören in eine Log, aber nicht auf die Website. Wir würden empfehlen die Einstellung im Webserver zu korrigieren, da es ein Sicherheitsrisiko ist

**Comment by xopez** [comment]
In der php.ini
```
; This directive controls whether or not and where PHP will output errors,
; notices and warnings too. Error output is very useful during development, but
; it could be very dangerous in production environments. Depending on the code
; which is triggering the error, sensitive information could potentially leak
; out of your application such as database usernames and passwords or worse.
; For production environments, we recommend logging errors rather than
; sending them to STDOUT.
; Possible Values:
;   Off = Do not display any errors
;   stderr = Display errors to STDERR (affects only CGI/CLI binaries!)
;   On or stdout = Display errors to STDOUT
; Default Value: On
; Development Value: On
; Production Value: Off
; http://php.net/display-errors
display_errors = Off
```

**Comment by ZeitZumKiffen** [comment]
@Newcomer1989 
k, naja...bis jetzt ist eh nix passiert (sollte nun deaktiviert sein)

@xopez 
Danke, wusste nicht mehr ob es im Rankingsystem Ordner war oder die php.ini, nutze nämlich ein Webinterface für alles und habs dann auch gefunden :P

**Comment by Newcomer1989** [comment]
Release 1.2.8 is out.. it should be fixed with it
