### ISSUE TITLE
Bot won't start

### ISSUE THREAD

**Issue by alsoGAMER** [Newcomer1989/TSN-Ranksystem#513]
If i start the bot from the webinterface it shutting down automatically after 3/4 seconds[](url)
[ranksystem.log](https://github.com/Newcomer1989/TSN-Ranksystem/files/2205227/ranksystem.log)

**Comment by Newcomer1989** [comment]
When you start the Bot, will there be created a file named "pid" inside the "logs" folder?

**Comment by alsoGAMER** [comment]
No

**Comment by Newcomer1989** [comment]
Then this is the problem.

Please have a look to the permissions of your Ranksystem installation.

You need to set the right owner.. for linux:
`chown -R www-data:www-data /var/www/ranksystem`

And you also need to set special permissions to some directories.. for linux:
`chmod 777 avatars/ tsicons/ update/ logs/`

Perhaps you can make an `ls -l` and send us a screenshot of it.

**Comment by alsoGAMER** [comment]
All is correctly configured, also the /var/log/ranksystem (for logs)

**Comment by alsoGAMER** [comment]
The webinterface itself run correctly, only the bot have this problem

**Comment by Newcomer1989** [comment]
The logspath is only for the logfile.. the PID file will be created inside the ranksystem installation directory inside the "logs" folder.
Are you sure this folder is existent and has the needed permissoins?
You checked the existing PID file inside the right path (beginning question)?

**Comment by alsoGAMER** [comment]
Ah.. ok i'll try to create

**Comment by alsoGAMER** [comment]
Logs folder exist and all permissions is correctly configured

**Comment by Newcomer1989** [comment]
Puh.. it is all, but not correct. You did chmod 777 all of the folders. Please only do this on the above defined ones.

> You checked the existing PID file inside the right path (beginning question)?
This question is still open. You observed the path /var/www/ranksystem/logs for a pid file on starting the Ranksystem?

**Comment by alsoGAMER** [comment]
the file is not created, and the screenshot I sent shows that the permissions (777) are there and they are all correct, it is not the first time that I install this interface

**Comment by alsoGAMER** [comment]
Now it works, I tinkered a bit and I did start. Still remains the question of why is a bit lazy to generate the pid file.

Tip: Make sure that the pid file is put in directory not accessible from the web, but are accessible if you set the correct permissions (Eg. /var/log/ranksystem)

**Comment by Newcomer1989** [comment]
hmm, I think it is not possible it will sometimes work and sometimes not with exactly the same system envoirements. It need to be changed anything it is now able to start.
Would be nice, if you can give us a hint, what you have done. Then we can validate it and perhaps enable a new check for this.

**Comment by alsoGAMER** [comment]
I simply reinstalled it until it worked, however the choice to make it only compatible with php5 has made things a bit more complex, it would be much appreciated (personally) an update that makes it compatible with php7. I'm also working for the improvement of the Italian translation since the current one has many typos/grammatical and even contains some strings not translated. 
I would be very honored if you, once finished the file is uploaded in the repository and used as the official

**Comment by Shad86** [comment]
> an update that makes it compatible with php7

We support php 7 since Version 1.2.2 21.January.2017 - So... what Php 7 Version did you use?

> I'm also working for the improvement of the Italian translation since the current one has many typos/grammatical and even contains some strings not translated.

We do not translate this things, the community is doing it, so thank you for fixing / improving it.

**Comment by alsoGAMER** [comment]
The most recent version downloadable from the website, but the problem is that if I configure everything to use php7 to the interface would give errors only and the bot does not start even

**Comment by Shad86** [comment]
Again which php7 Version do you use?

**Comment by alsoGAMER** [comment]
@Shad86 php7.2.7, but atm i using php5.6 without errors

**Comment by alsoGAMER** [comment]
@pascual48 reinstalling everything over and over again until it worked, also trying to change multiple versions of php, directories, and configurations of nginx

**Comment by Newcomer1989** [comment]
Ok, I think the topic is solved.. All other please in a new/other issue
