### ISSUE TITLE
Bot no start

### ISSUE THREAD

**Issue by pascual48** [Newcomer1989/TSN-Ranksystem#514]
Tengo montado tsn ranksystem en windows server, luego de instalarlo y configurar ip de servidor al iniciar el bot no hace nada

¿que debo hacer?

**Comment by pascual48** [comment]
error say: PHP Notice: Undefined variable: mysqlcon in c:/xampp/htcpdocs/jobs/bot.php on line 103
Notice: Undefined variable: mysqlcon in c:/xampp/htcpdocs/jobs/bot.php on line 103

**Comment by Shad86** [comment]
Maybe this helps you -> https://github.com/Newcomer1989/TSN-Ranksystem/wiki/Bot-not-starting---Windows

**Comment by Newcomer1989** [comment]
In your case also check your database configurations.. especially the `other/dbconfig.php` contained the correct credentials

**Comment by pascual48** [comment]
Los datos de dbconfig.php están correctos

**Comment by pascual48** [comment]
cuando ejecuto el comando en mi cmd me sale qu ehay un error on ine 103 del archivo bot.php

**Comment by pascual48** [comment]
también me he dado cuenta que no se crea un archivo llamado "pid" en logs (uso windows server)

**Comment by Newcomer1989** [comment]
> también me he dado cuenta que no se crea un archivo llamado "pid" en logs (uso windows server)

Then please check, what Shad86 already sent.
https://github.com/Newcomer1989/TSN-Ranksystem/wiki/Bot-not-starting---Windows

**Comment by Shad86** [comment]
Pls write in english as no one will understand you - thanks!
