### ISSUE TITLE
Bot startet nicht

### ISSUE THREAD

**Issue by lukas2002m** [Newcomer1989/TSN-Ranksystem#519]
Hallo,
ich habe seit der aktuellen Version 1.2.8 (nach dem Update) das Problem, dass der Bot nicht mehr startet.
Ich habe den Bot bereits neu installiert, was jedoch keine Abhilfe des Problems brachte.

Wenn ich die bot.php starte, erhalte ich folgende Medung:

> Fatal error: Uncaught Error: Class 'PDO' not found in /var/www/html/secure/https/ranksystem/other/config.php:71
Stack trace:
#0 /var/www/html/secure/https/ranksystem/jobs/bot.php(55): require_once()
#1 {main}
  thrown in /var/www/html/secure/https/ranksystem/other/config.php on line 71

Eingesetzte PHP Version:

> PHP 7.0.30-0+deb9u1 (cli) (built: Jun 14 2018 13:50:25) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies

Bei der eingesetzten Version handelt es sich um eine PHP-FPM, bei der PDO aktiviert ist.

**Comment by Shad86** [comment]
schau mal mit `php -m` ob dort auch PDO und pdo_mysql aufgelistet sind

**Comment by Newcomer1989** [comment]
Fall PHP PDO wirklich installiert ist, bitte auch darauf achten, ob evtl. mehere PHP Versionen installiert sind.

Entscheidend ist das PHP, welches in der other/phpcommand.php definiert ist. Bitte den dortigen Befehl (im Standard "php") für die Überprüfung nutzen.

**Comment by lukas2002m** [comment]
Hallo,
ich habe den Fehler nun beheben können in dem ich PHP sowie den Bot vollständig neu installiert habe.
Ich möchte mich an dieser Stelle für den schnellen und netten Support bedanken.

MfG
