### ISSUE TITLE
Multiple queries online at the same time

### ISSUE THREAD

**Issue by Juggernaut132** [Newcomer1989/TSN-Ranksystem#52]
Hi,

since some days I have the problem that the Bot connects multiple times, again and again.. I've restarted the bot, but it happens again..

Screen: https://gyazo.com/28973e52fde057a35ba26084bde3ad74

The TS server is on a Dedicated MC-32 Server from OVH, the Bot runs with a vServer from KMS-Hosting. The IP of the vServer is whitelisted

**Comment by Newcomer1989** [comment]
Be sure you started the bot with the webserver-user!

Check you did the following:

**Comment by Juggernaut132** [comment]
I started the bot as web user changed the host and it happens again.

**Comment by Newcomer1989** [comment]
How looks your cronjob entry?

**Comment by Juggernaut132** [comment]
Exactly like your from above.

I've switched the mysql Host, now it seems to work fine, thanks anyway!
