### ISSUE TITLE
Show us your modded TSN-Ranksystem!

### ISSUE THREAD

**Issue by Christian1998** [Newcomer1989/TSN-Ranksystem#521]
Hey guys, i just modded our Ranksystem and I wonder what your situation looks like :)
![bildschirmfoto am 2018-07-28 um 19 16 37-fullpage](https://user-images.githubusercontent.com/13522681/43358983-ca7d7c1a-929a-11e8-87cc-4235d87f2674.png)
(Live on https://ranking.shootoo.net.)

**Comment by Newcomer1989** [comment]
Nice idea..
But not really nice is the copyright violation :(

**Comment by Christian1998** [comment]
@Newcomer1989 Just added the menupoint back. Ill create my own as soon i have more time.

**Comment by Newcomer1989** [comment]
Seems to get no interest for other users.. Cause this is primary a issue platform, we will close this.
