### ISSUE TITLE
"!!!! Logs folder is not writable !!!!" Error

### ISSUE THREAD

**Issue by Heacien** [Newcomer1989/TSN-Ranksystem#524]
I'm getting following error while setting up my webspace and testing your system:
`[...]\Administrator>[...]\php\php.exe -f [...]\worker.php check
´╗┐
 !!!! Logs folder is not writable !!!!

 Cancel start request...`

I have php installed whit the instructions of microsoft (https://docs.microsoft.com/en-us/iis/application-frameworks/install-and-configure-php-on-iis/install-and-configure-php).

Btw. I set up the security of the ranksystem folder for everyone to nearly all options, so i cant get a clue out of the error message...

**Comment by Shad86** [comment]
Check your rights it seems the bot can’t write into the logs folder

**Comment by Heacien** [comment]
As I said: The Program Folder got full rights for everyone

**Comment by Shad86** [comment]
The message that the logs folder is not writable, only appears if the rights are not correct and/or if it’s not possible for the bot to write to the folder.

**Comment by Heacien** [comment]
Ok, I think I did some mistakes while setting up my server. Thank you for trying ;)
