### ISSUE TITLE
Ranksystem-Bot ist eine Kopie von mir.

### ISSUE THREAD

**Issue by ncl2k** [Newcomer1989/TSN-Ranksystem#527]
Guten Tag,
wenn ich den Bot über localhost starte, dann wird er eine Kopie von meiner Standart Identität, auch wenn ich eine neue Identität erstelle bleibt er eine Kopie. Auf einem anderen Server habe ich hingekriegt, aber weiß leider nicht mehr genau wie. Wie funktioniert das genau?

MfG NcL2k

**Comment by Newcomer1989** [comment]
Wenn ich es richtig verstehe, geht um die TS3 unique ID und die damit verbundenen TS3 query Zugangsdaten.

Die Zugangsdaten für den ServerQuery hängen mit Ausnahme des serveradmins immer an der TS3 unique Client ID, welche die Zugangsdaten erstellt.
Soll das unter einer anderen ID laufen, so kann diese im TS3 Client unter "Extras" -> "Identitäten" erstellt werden.
Zum connecten mit dieser Identität im Verbindungsdialog (unten links) auf "Mehr" klicken. In den erweiterten Optionen kann dann die gewünschte Identität ausgewählt werden.
Nach dem Verbinden mit diesen den Query-Zugang erstellen "Extras" -> "ServerQuery Login" und die erstellten Zugangsdaten im Webinterface des Ranksystems (Bereich TeamSpeak) hinterlegen.

**Comment by ncl2k** [comment]
Ich Vollidiot...
Vielen Dank für die schnelle Hilfe :D
