### ISSUE TITLE
LIMITED Servergroups?

### ISSUE THREAD

**Issue by h1rule** [Newcomer1989/TSN-Ranksystem#528]
Tried to make this; but it seems to be too long?

`0=>431,30=>412,172800=>413,389000=>414,604800=>415,920000=>416,1300001=>417,1900800=>418,2592096=>419,3092096=>578,3592095=579,4252095=>580,4952095=>581,5752095=>582,6252095=>583,6952095=>584,7352095=>585,7952095=>586,8202095=>587,15778476=>588,31536000=>589,63113904=>590`

**Comment by Shad86** [comment]
Where'd you try to enter that?

**Comment by Shad86** [comment]
> 3092096=>578,3592095=579,425

;)

**Comment by h1rule** [comment]
AH :D haha geil, danke!
