### ISSUE TITLE
Problem mit der Installation

### ISSUE THREAD

**Issue by TheFrecyboyYT** [Newcomer1989/TSN-Ranksystem#53]
Wenn ich das installieren möchte, kommen diese Fehler

Installiere Datenbank:
Fehler beim Erstellen der Datenbank: 42000

Installiere Tabellen:
Fehler beim Erstellen der Tabelle: 42000.
Fehler beim Erstellen der Tabelle: 42000.Fehler beim Erstellen der Tabelle: 42000.Array ( [0] => 42000 [1] => 1064 [2] => You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '@Ranksystem.cleanclients (timestamp bigint(11) NOT NULL default '0')' at line 1 ) Fehler beim Erstellen der Tabelle: 1.Array ( [0] => 42000 [1] => 1064 [2] => You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '@Ranksystem.cleanclients SET timestamp='1'' at line 1 ) Fehler beim Erstellen der Tabelle: 1.Fehler beim Erstellen der Tabelle: 42000.
Fehler beim Erstellen der Tabelle: 42000.Fehler beim Erstellen der Tabelle: 42000.
Fehler beim Erstellen der Tabelle: 42000.
Array ( [0] => 42000 [1] => 1064 [2] => You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '@Ranksystem.user_snapshot (timestamp)' at line 1 ) Fehler beim Erstellen der Tabelle: 1.Fehler beim Erstellen der Tabelle: 42000.
Fehler beim Erstellen der Tabelle: 42000.
Array ( [0] => 42000 [1] => 1064 [2] => You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '@Ranksystem.stats_server SET total_user='9999'' at line 1 ) Fehler beim Erstellen der Tabelle: 1.Fehler beim Erstellen der Tabelle: 42000.
Array ( [0] => 42000 [1] => 1064 [2] => You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '@Ranksystem.job_check (job_name) VALUES ('calc_user_limit'),('calc_user_lastscan' at line 1 ) Fehler beim Erstellen der Tabelle: 1.Fehler beim Erstellen der Tabelle: 42000.

Bitte um Hilfe

**Comment by Newcomer1989** [comment]
How you named the database?

Can you make a screenshot on the installation page with your out filled data?

**Comment by TheFrecyboyYT** [comment]
![2](https://cloud.githubusercontent.com/assets/20009531/16331881/4694eef8-39f3-11e6-9b5c-bbcab50471b7.PNG)
![3](https://cloud.githubusercontent.com/assets/20009531/16331880/46935462-39f3-11e6-8c5f-0d0d62a4387f.PNG)

**Comment by TheFrecyboyYT** [comment]
![1 5](https://cloud.githubusercontent.com/assets/20009531/16331903/5f8c217e-39f3-11e6-85e4-4b743cbf79a3.PNG)

**Comment by TheFrecyboyYT** [comment]
it work.
