### ISSUE TITLE
Ranking crasht Täglich wegen MySql fehler

### ISSUE THREAD

**Issue by Paddyboy1991** [Newcomer1989/TSN-Ranksystem#531]
Die Fehlermeldung:

2018-08-19 06:31:45.853549   CRITICAL  Select on DB failed: Array
(
    [0] => HY000
    [1] => 2006
    [2] => MySQL server has gone away
)
 Shutting down!

Mehr bekomme ich leider nicht raus aus der Log.
Eine Idee welche Array gemeint ist?
Mit freundlichen Grüßen

**Comment by Newcomer1989** [comment]
> [2] => MySQL server has gone away

Die Meldung ist eigentlich eindeutig. Der MySQL Server wurde wohl runtergefahren.

Das es täglich auftritt.. Ist es denn immer zur gleichen Zeit? Evtl. wird die Datenbank per cronjob etc. neu gestartet.
Ansonsten kann dies natürlich auch immer passieren, wenn die Datenbank aktualisiert wird. Dafür muss sie auch neustarten.

**Comment by Paddyboy1991** [comment]
Nein ein Cron läuft nicht drüber und die Zeit variiert auch immer um 2h ca

**Comment by Shad86** [comment]
Ich vermute mal du meinst +- 2H also mal 2 Stunden früher mal 2 Stunden später?

Dann wäre gut zu wissen ob das nur zu "Stoßzeiten" auftritt (also wenn viel los ist)

Dann wären auch logs gut vom Betriebssystem, weil dort meist noch etwas mehr zu sehen ist, warum etwas crashed.

Wenn du weiter Hilfe brauchst kannst du natürlich auch gerne auf unseren teamspeak kommen (ts-n.net)

**Comment by Newcomer1989** [comment]
Zur Info, wir hatten das Problem auch schon mal bei jemand anderem. Dort hatten wir uns per Fernwartung hin verbunden und konnten das Problem lösen.

https://github.com/Newcomer1989/TSN-Ranksystem/issues/361#issuecomment-352418618
