### ISSUE TITLE
Rank Vergabe Problem

### ISSUE THREAD

**Issue by Killer0561** [Newcomer1989/TSN-Ranksystem#533]
Hallo,
ich habe ein gewisses Problem mit dem aktuellen Rank System. Ich habe die Rank Zeiten und Gruppen eingestellt. Nun stellt sich das Problem, wenn zum Beispisl ein längerer bestehender Teamspeak User bereits die Gruppe Community hat, aber der niedrigste Rank zum Beispiel Trailphase ist, entfernt der Bot den höchsten Rank und der User fängt wieder bei der Trailphase an. Kann man das irgendwie unterbinden, das dies nicht passiert?
LG Killer0561

**Comment by Newcomer1989** [comment]
Wenn die Gruppe "Community" Teil der "Rangsteigerung Defintion" ist, dann wird er diese Gruppe entfernen und die Gruppe "Trailphase" vergeben. Grund hierfür ist, dass die benötigte Zeit für diese Gruppe fehlt.

Du kannst in diesem Fall manuell bei den Personen eine entsprechende Zeit hinterlegen, sodass sie wieder der höheren Gruppe zugeordnet werden. Das geht im Webinterface unter "Administration" -> "Zeit zu User hinzufügen".

**Comment by Killer0561** [comment]
Gut ok, danke für deine Hilfe :)
LG Killer0561
