### ISSUE TITLE
Ranksystem, nach 1.2.9 nutzer bekommt nach entfernen sein rank nicht mehr wieder

### ISSUE THREAD

**Issue by hijodeputa1337** [Newcomer1989/TSN-Ranksystem#534]
Hallo, einer meiner Mods hatte aus Spaß seinen Privaten Kollegen den Rank einfach entfernt, eigentlich sollte er dann ja nach paar Sekunden/Minuten automatisch den Rank wieder bekommen. (Hatte das auch mal getestet, damals ging das). Nun ist nach 4 Stunden immer noch nix passiert, und meine Vermutung ist das er erst beim nächsten Aufstieg sein neuen Rank bekommt. Der Bot läuft aufn TeamSpeak3 Server, sehe ihn via ServerQuery Ports anzeigen.....aber bis jetzt hatte er den Rank nicht wieder im TeamSpeak 3. Woran liegt das?  

Und ist es möglich via Datenbank Command alle Spieler die länger als 4 monate nicht mehr gesehen wurden zu löschen?

**Comment by Newcomer1989** [comment]
Solche manuelle Eingriffe sind nicht vorgesehen. Hat der Betroffene eine höhere Gruppe als vorgesehen, so wird es meist direkt korrigiert. Fehlende oder niedrigere werden im Zweifel erst mit der nächsten Rangsteigerung erkannt/gesetzt.
Am besten den manuellen Fehler auch wieder manuell korrigieren 😉

**Comment by Newcomer1989** [comment]
Solche manuelle Eingriffe sind nicht vorgesehen. Hat der Betroffene eine höhere Gruppe als vorgesehen, so wird es meist direkt korrigiert. Fehlende oder niedrigere werden im Zweifel erst mit der nächsten Rangsteigerung erkannt/gesetzt.
Am besten den manuellen Fehler auch wieder manuell korrigieren 😉

**Comment by Newcomer1989** [comment]
Bezüglich dem Löschen gibt es eine Option im Webinterface unter Core -> Clean Clients. Bitte dort die onclick Hilfe beachten.
