### ISSUE TITLE
php_com_dotnet

### ISSUE THREAD

**Issue by mehdi0121** [Newcomer1989/TSN-Ranksystem#536]
![image](https://user-images.githubusercontent.com/41438090/44740505-e33bb400-ab0f-11e8-956f-ace21425ca4c.png)
where is my problm?

**Comment by Shad86** [comment]
You read the text in the red box?

**Comment by mehdi0121** [comment]
yes !

**Comment by Shad86** [comment]
well if you really did it, why you opened an issue?

You don't understand what there stand? or Why? Im confused

**Comment by mehdi0121** [comment]
I do not know how to solve this problem! pls help me!

**Comment by Newcomer1989** [comment]
Have a look to the Wiki, Step 2
https://github.com/Newcomer1989/TSN-Ranksystem/wiki/Bot-not-starting---Windows

**Comment by mehdi0121** [comment]
tnx!
