### ISSUE TITLE
 The informations on this site could be outdated! It seems the Ranksystem is no more connected to the TeamSpeak. 

### ISSUE THREAD

**Issue by mehdi0121** [Newcomer1989/TSN-Ranksystem#537]
Sorry, I have another problem
![image](https://user-images.githubusercontent.com/41438090/44748409-f4db8680-ab24-11e8-99b6-aa3c4deab499.png)
I'm entering all the information correctly, but I encounter this problem

**Comment by mehdi0121** [comment]
![image](https://user-images.githubusercontent.com/41438090/44749202-189fcc00-ab27-11e8-9d8d-2147b1bc81d2.png)

**Comment by Shad86** [comment]
Is there something in the ranksystem.log file (rank/log/ranksystem.log)?

**Comment by mehdi0121** [comment]
![image](https://user-images.githubusercontent.com/41438090/44792988-6addfd00-abba-11e8-85bf-47675c82af89.png)

**Comment by Newcomer1989** [comment]
You should not run the Bot via opening the URL ../jobs/bot.php in your browser!

Start / Stop the bot via the webinterface. I am very confused, you are the first, who did it at this way!

**Comment by mehdi0121** [comment]
No, I did not do it. I pressed the start button, but did not work
![image](https://user-images.githubusercontent.com/41438090/44883188-8a187f80-accb-11e8-9573-73ae13853fea.png)

**Comment by Newcomer1989** [comment]
You get a new entry in the Ranksystem log, when you are pressing the start button?

We changed something on the startup process with version 1.2.10. I see, you are still on 1.2.9.

Please download the Ranksystem new with the actual version and try to reinstall it.
Then have a look to the other/phpcommand.php and setup it with you PHP like described here in step 1  https://github.com/Newcomer1989/TSN-Ranksystem/wiki/Bot-not-starting---Windows

**Comment by mehdi0121** [comment]
tnx

**Comment by Newcomer1989** [comment]
It helped.. your problem is solved?

**Comment by Newcomer1989** [comment]
Closed, due to no response.
