### ISSUE TITLE
Error 0: php_network_getaddresses: getaddrinfo failed: Name or service not known

### ISSUE THREAD

**Issue by hitelare2** [Newcomer1989/TSN-Ranksystem#54]
Error 0: php_network_getaddresses: getaddrinfo failed: Name or service not known

**Comment by Newcomer1989** [comment]
Where you get this error?

What did you before?

**Comment by hitelare2** [comment]
When I start the bot

Install the Bot and configure it

**Comment by hitelare2** [comment]
I tried on both Debian and Ubuntu

**Comment by hitelare2** [comment]
Same Error appears

**Comment by Newcomer1989** [comment]
ok, and where you get this error?
What you did exactly? How you started the Bot, via webinterface or console?


It would be a dream, if people take some trouble on sending bug reports. A complete bug description is requirement to be able to solve it!

**Comment by hitelare2** [comment]
on the log file

I download it, but it in the /var/www/html/ranks, configure it, I run it with webinterface and worker.php

**Comment by Shad86** [comment]
@hitelare2 pls describe it exactly and offer a log file (remove sensitive data if you have some in there) and a screenshot, so that he can see where and when this issue exactly comes up.

Its not possible to help you if you don't explain and show where the problem happen ;)

regards

Shad86

**Comment by Newcomer1989** [comment]
Closed due imprecise answer.

I do not waste my time to ask 10 times the same thing.

If I get a full description, like already said before, I would like have a look on it.
