### ISSUE TITLE
[UI] inconsistent blocks

### ISSUE THREAD

**Issue by r4sas** [Newcomer1989/TSN-Ranksystem#540]
ipad pro emulation in opera:
![ipad pro emulatinon in opera](https://user-images.githubusercontent.com/7023612/44754833-489d9e00-ab2c-11e8-80ca-fc91b61f793f.png)

**Comment by Newcomer1989** [comment]
We do not want to solve this rare case with the current Bootstrap version (3.4.1), since there is Bootstrap 4 longer released.

This should be a part, when we update to a newer Bootstrap / Theme.
