### ISSUE TITLE
Top User List no refresh

### ISSUE THREAD

**Issue by ArcaneGA** [Newcomer1989/TSN-Ranksystem#543]
I have since minimum 1 month no refresh of the Top User List also all of this list. Week, moth and all time

How can I fix it?

**Comment by Shad86** [comment]
seems like you haven't collected enough time for the moment, btw you can see how many entries are missing if you go on the relevant pages for top week, top month....

**Comment by ArcaneGA** [comment]
Well the system running minimum 1 or 2 years I think there so enought collected time. All works fine but only the entries for top week, top month and all time.

At 5. place in week I see an person that was last online at 2018-07-08 and the time of me is not the correct I think

**Comment by Newcomer1989** [comment]
Can we get a link of your Ranksystem, that we can have a look?! Thx!

**Comment by ArcaneGA** [comment]
https://ranksystem.arcane-gaming.de/stats/index.php

**Comment by Newcomer1989** [comment]
Have you already checked your Ranksystem log?

**Comment by ArcaneGA** [comment]
Yes, but there is no relevant entry

**Comment by Newcomer1989** [comment]
I see, there is.. Perhaps join our Public TS (ts-n.net), then we can have a look together.

**Comment by Newcomer1989** [comment]
Then problem was, there were 1800 clients, which are not any more existing on the TS3 server.

After deleting this, all runs perfectly!
