### ISSUE TITLE
[Request] promotion changes

### ISSUE THREAD

**Issue by IceCupe123** [Newcomer1989/TSN-Ranksystem#545]
Hi can u add a option that we can exclude certin server groups to get promoted but they still get ranked.
like a admin get listed in top users but dont get promoted . sry for my bad english

**Comment by Newcomer1989** [comment]
I do not understand, what exactly you are meaning!

You have several things you can do:

1) Webinterface - Core - servergroup exceptions
There you can add servergroups. User in this groups will not get ranked.

2) Webinterface - Core - exception mode
There are several modes, how to collect the time of people which are excepted. For more click on it to get a documentation.

3) Webinterface - Stats page - excepted client
Here you can show/hide excepted clients on the stats page.

That already helped? If not, please describe more, what do you wish..

**Comment by Newcomer1989** [comment]
Closed, due to no response.
