### ISSUE TITLE
"my_stats.php" bearbeiten

### ISSUE THREAD

**Issue by Kamiikaze** [Newcomer1989/TSN-Ranksystem#546]
Wäre es möglich das man die Anzahl der Stunden sowie Verbindungen zum nächsten Rang im Webinterface einstellen könnte? Da meine Änderungen sonst nach jedem Update verschwinden^^
Damit meine ich Z75-83 in "my_stats.php"

```
	$time_for_bronze = 50;
	$time_for_silver = 100;
	$time_for_gold = 250;
	$time_for_legendary = 500;

	$connects_for_bronze = 50;
	$connects_for_silver = 100;
	$connects_for_gold = 250;
	$connects_for_legendary = 500;
```

**Comment by xopez** [comment]
fände ich ehrlich gesagt, auch gut, wenn die in die DB wandern, da dort eh alle Optionen sind.
Dann bräuchte man nur im Webinterface eine neue Sektion mit "Errungenschaft" oder ähnlich.

**Comment by Newcomer1989** [comment]
Ist mit der 1.3.0 umgesetzt.

Webinterface -> Stats Page
