### ISSUE TITLE
undefined function ssh2_connect() in verify.php

### ISSUE THREAD

**Issue by xopez** [Newcomer1989/TSN-Ranksystem#547]
Hallo, über SSH2 bekomme ich folgenden Fehler, wenn ich mich bei multiplen Teamspeakverbindungen von einer IP verifizieren möchte.
`[Thu Sep 06 16:03:03.027217 2018] [proxy_fcgi:error] [pid 5605] [client 5.57.197.0:50047] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function ssh2_connect() in /var/www/vhosts/mightful-noobs.de/rank.mightful-noobs.de/libs/ts3_lib/Transport/TCP.php:65\nStack trace:\n#0 /var/www/vhosts/mightful-noobs.de/rank.mightful-noobs.de/libs/ts3_lib/Transport/TCP.php(141): TeamSpeak3_Transport_TCP->connect()\n#1 /var/www/vhosts/mightful-noobs.de/rank.mightful-noobs.de/libs/ts3_lib/Adapter/ServerQuery.php(73): TeamSpeak3_Transport_TCP->readLine()\n#2 /var/www/vhosts/mightful-noobs.de/rank.mightful-noobs.de/libs/ts3_lib/Adapter/Abstract.php(57): TeamSpeak3_Adapter_ServerQuery->syn()\n#3 /var/www/vhosts/mightful-noobs.de/rank.mightful-noobs.de/libs/ts3_lib/TeamSpeak3.php(333): TeamSpeak3_Adapter_Abstract->__construct(Array)\n#4 /var/www/vhosts/mightful-noobs.de/rank.mightful-noobs.de/stats/verify.php(92): TeamSpeak3::factory(Object(TeamSpeak3_Helper_Uri))\n#5 {main}\n  thrown in /var/www/vhosts/mightful-noobs.de/rank.mightful-noobs.de/libs/ts3_lib/Transport/TCP.php on line 65\n', referer: https://rank.mightful-noobs.de/stats/verify.php`

**Comment by xopez** [comment]
https://github.com/planetteamspeak/ts3phpframework/issues/103

**Comment by xopez** [comment]
kommt möglicher davon, dass auf der seite selbst php 7.2.9 läuft, aber es für plesk dort kein ssh2-modul gibt.

**Comment by Newcomer1989** [comment]
Schau mal in der Beschreibung zur "TS3 Query encryption". Da steht alles genau beschrieben, was benötigt wird, um eine verschlüsselte Verbindung aufbauen zu können.

Wenn Plesk verwendet wird, ist natürlich wichtig, dass die für den Bot gültige PHP Installation/Version auch über die PHP-SSH2 Extension verfügt!

**Comment by xopez** [comment]
das mit der extension war mir schon bewusst.
Habe es nun mit Plesk geschafft.
Für PHP-7.2 lass ich es mal da.
```
sudo apt-get install plesk-php72-dev build-essential
/opt/plesk/php/7.2/bin/pecl install https://pecl.php.net/get/ssh2-1.1.2.tgz
echo "extension=ssh2.so" > /opt/plesk/php/7.2/etc/php.d/ssh2.ini
plesk bin php_handler --reread
service plesk-php72-fpm restart
```
Damit hats geklappt und wurde auch mit /opt/plesk/php/7.2/bin/php -m angezeigt.

**Comment by Newcomer1989** [comment]
Da macht Plesk das Geschäft wohl schwieriger, anstelle es zu vereinfach xD

**Comment by xopez** [comment]
jop, sehe ich genauso^^
