### ISSUE TITLE
Bot startet nicht

### ISSUE THREAD

**Issue by cr0co** [Newcomer1989/TSN-Ranksystem#548]
Bot startet nicht.
es steht
Der Ranksystem Bot sollte gestartet sein. Für mehr Informationen bitte die Log unterhalb prüfen!
im log steht aber nichts, und es wird keine PID angelegt.

Wenn ich aber via cronjob die worker.php datei ausführe wird eine PID angelegt, 
der bot ist aber nicht im server zu sehen.

**Comment by Newcomer1989** [comment]
Da sind wohl die Berechtigungen fehlerhaft gesetzt. Bitte diese wie in der Installationsanleitung beschriebn, setzen:
https://ts-n.net/ranksystem.php#install

**Comment by cr0co** [comment]
das war das erste das ich geprüft hatte, leider ohne erfolg

**Comment by Newcomer1989** [comment]
Wie sehen diese denn aus?

**Comment by cr0co** [comment]
![unbenannt](https://user-images.githubusercontent.com/6071154/45221783-cf801280-b2b2-11e8-8060-10abcdce30e0.png)

**Comment by Newcomer1989** [comment]
Es wird wohl Plesk genutzt.

Dann wird es sehr wahrscheinlich erforderlich sein, die PHP Version von Plesk in der Datei `other/phpcommand.php` vorzugeben

**Comment by cr0co** [comment]
Ja wir haben Plesk in einsatz, mit Server PHP 5.6.27 und Domainphp 7.1
welches soll ich nun eintragen? habe es mit
$phpcommand = "php56";
und
$phpcommand = "php71";
versucht, keine fehlermeldung nichts.

**Comment by xopez** [comment]
Bei Plesk liegt es hier:
`$phpcommand = "/opt/plesk/php/7.2/bin/php"`
7.2 ist die PHP Version. Wenn du nur 7.1 hast, dass muss da logischerweise 7.1 hin.

**Comment by Newcomer1989** [comment]
Ich hoffe, die Tipps haben geholfen.
Falls ja, gerne kurz bescheid geben, damit wir das Ticket schließen könnten.
Falls nein, einfach mal bei uns auf dem Public TS (ts-n.net) vorbei schauen, dann können wir dir dort weiterhelfen.

**Comment by Newcomer1989** [comment]
Closed, da keine Rückmeldung mehr kam.
