### ISSUE TITLE
Bot Startet nicht (Windows)

### ISSUE THREAD

**Issue by MINIMhduifgh** [Newcomer1989/TSN-Ranksystem#549]
Folgendes Problem wenn ich versuche den Bot über die worker.php zu starten kriege ich folgenden Fehler:
`Starting the Ranksystem Bot. Keine Instanzen verfügbar. [Failed]`
Wenn ich versuche die bot.php zu starten stopt der Bot einfach:
>2018-09-11 16:20:10.899883   INFO      Received signal to stop! Shutting down!
>2018-09-11 16:20:07.897711   INFO      Bot starts now his work!
>2018-09-11 16:20:07.897711   INFO      Config check [done]
>2018-09-11 16:20:07.896711   INFO      Config check started...
>2018-09-11 16:20:07.896711   INFO        Joined to specified Channel.
>2018-09-11 16:19:47.891567   INFO        TS3 Server version: 3.3.1 on Windows [Build: 1534753160 from 2018-08-20 10:19:20]
>2018-09-11 16:19:47.890567   INFO      Connection to TS3 Server established.
>2018-09-11 16:19:47.850565   INFO      Connect to TS3 Server (Address: "localhost" Voice-Port: "9987" Query-Port: "10011" SSH: "0").
>2018-09-11 16:19:47.733558   DEBUG     Database Version: 5.5.5-10.1.34-MariaDB
>2018-09-11 16:19:47.733558   DEBUG     Using PHP Version:  7.2.7

Danke, ich habe übrigens keine Ahnung von php und MYSQL.
Edit: Er verbindet sich übrigens bei keiner der beiden Wege mit TS.

**Comment by Newcomer1989** [comment]
Bitte die vollständige Log vom Ranksystem posten. Diese hier scheint lückenhaft zu sein. Es fehlen entscheidende Einträge, z.B. die Ranksystem Version und auch das OS.

Bitte auch unbedingt die folgenden Schritte beachten / prüfen. Erfahrungsgemäß werden 95% der Fehlerfälle hierüber abgefangen.
https://github.com/Newcomer1989/TSN-Ranksystem/wiki/Bot-not-starting---Windows

> Edit: Er verbindet sich übrigens bei keiner der beiden Wege mit TS.

Das kann nicht stimmen. Der Bot könnte sonst nicht die TS3 Server Version in die Log ausgeben. können. Diese ist erst nach connect zum TS3 abfragbar!
Bitte beachten, dass der Bot kein Client ist. Dieser verbindet sich via Query.

**Comment by MINIMhduifgh** [comment]
Danke für die Hilfe habe den Bot jetzt zum laufen gebracht.
sry für meine unfähigkeit im wiki nachzuschauen.
