### ISSUE TITLE
Define Idle time to accept as active time

### ISSUE THREAD

**Issue by NichoTheMan** [Newcomer1989/TSN-Ranksystem#55]
If i enable the idle time function, a user will not get active time if he is not talking. Is it possible to set the idle time manually?

To something like 5 minutes, if he has not spoken in the last 5 minutes he will be set as idle.

EDIT:

Another thing you could add is AFK channel or Idle channel. So when the clients are in the idle channel they will not get active time, but when they are not in idle channel they get active time.

I have created a simple bot in python that automatically moves them into the AFK channel after 15 minutes of being idle. 

The afk bot function could also be of great use to me and many others i assume.

**Comment by Shad86** [comment]
I picked out the 2 things in the Changelog which are related to your Question:

1.1.0 (2016-XX-XX)
......
**+ added function ingore idletime; idle time of an user will be ignored (counted as active time), if it is under a predefined value**
**+ added possibility to except channel**
etc......

You can find the **full** changelog on http://ts-n.net/ranksystem.php (just scroll a little bit down)

And before your ask, there is no eta at the moment, if it gets clearer Newcomer usually adds a little bit more specific date :).

If you have still questions feel free to ask

greetings

Shad86

**Comment by NichoTheMan** [comment]
Oh, great.

Then the only suggestion left out i think is the AFK bot using the channel exception. Not needed but saves resource usage if the ranksystem already has this.

**Comment by Shad86** [comment]
i dont know what you exactly mean - can you explain it?

Because as i posted there will come an option where the ranksystem can ignore specific channels for example an "afk-channel"

"**+ added possibility to except channel**"

greetings

**Comment by NichoTheMan** [comment]
I mean so the bot moves you to the except channel after the idle time you have set has passed.

Teamspeak sets client status to idle after a certain amount of time (not sure exactly how long).

In the python bot i created it moves the client to the afk channel automatically if the idle time has passed and the user has been idle for 20 minutes.

**Comment by Newcomer1989** [comment]
About the function to move clients to an afk channel after a predefined online time -> This will not come nearly as feature. At the moment its is a Ranksystem and not more!

Sure the Ranksystem is written modular, so it would be easy to add new "module". There are only a quite things to do for that. Perhaps this will come in any future release. But I think not more this year ;-)
I think this would be a milestone for version 2.0.0

Also I have to reconsider whether I activate this at all. There are still so much other Bots, which do so much stuff. I do not think there is a gap which need to be to close.

**Comment by NichoTheMan** [comment]
I could create modules to support the project but it's hard when there are no commentsin the code or documentation.

I'll go through the code and try though.

**Comment by Newcomer1989** [comment]
It is not ready enough for this at the moment, thats why there is no documentation .

Please standby and look for the changelog to get the info when it is implemented.

**Comment by Newcomer1989** [comment]
Topic closed. Release 1.1.0 is out and function -> Define Idle time to accept as active time <- is a part of the release.
