### ISSUE TITLE
TS3 Error: 2051- Servergroup Icon file not found (file not exists)

### ISSUE THREAD

**Issue by mghkli** [Newcomer1989/TSN-Ranksystem#553]
hi,
bot repeat doing something and doesn't start.

https://pastebin.com/Ky1B4uma (ranksystem.log) - i edit it because no one could read it xD

**Comment by Shad86** [comment]
> 2018-09-25 18:42:09.176962   ERROR     TS3 Error: 2051: Error while downloading servergroup icon from group '7' with ID 284: file not found (file not exists)
> 
> 2018-09-25 18:42:09.175791   ERROR     TS3 Error: 2051: Error while downloading servergroup icon from group '5' with ID 283: file not found (file not exists)
> 
> 2018-09-25 18:42:08.975448   ERROR     TS3 Error: 2051: Error while downloading servergroup icon from group '★ Mαηαgєяѕ' with ID 394: file not found (file not exists)

If you still have this icons delete them on your server end upload them again, as it seems they are broken and as shown are not found / not existent.

**Comment by mghkli** [comment]
that is not the point . i fix that and its  happening again
https://pastebin.com/SwunghPm

**Comment by Newcomer1989** [comment]
What did you exactly?

If such an error appears, you need:
1) remove that icons from all groups
2) remove that icon from the TS3 server; Perhaps you will get the error above also here. Then you need to delete the icon from your file system (installation folder TS3 server; example: `/files/virtualserver_1/internal/icons/icon_1005586596`)
3) upload the new icon to your TS3 server
4) define the new ones to the groups

After that the Ranksystem will try to download the icons again. You should see it inside the Ranksystem log.

**Comment by Newcomer1989** [comment]
I took again a look to your log.
I see, the Ranksystem is still adding all ppl again and again. It seems, the information could not be saved/stored into the database succesfully.

You could try to do a fresh installation of the Ranksystem.
Also you can contact us on our public server (ts-n.net), then we can have a look together on it via a remote session.

**Comment by Newcomer1989** [comment]
Closed due no response
