### ISSUE TITLE
Is it possible to hide Bots from the stats page?

### ISSUE THREAD

**Issue by RedocPlays** [Newcomer1989/TSN-Ranksystem#555]
Hi. I wonder if it is possible to hide bots from the stats page (current users online). With the bots the online count is never 0, even if no users are connected...

**Comment by Shad86** [comment]
You mean Musicbots? "Real Clients":

Under "Core" you can except user or clients with specific server groups
![exception-tsn](https://user-images.githubusercontent.com/18570683/46259649-60c25d80-c4dc-11e8-819b-d5a7b51247c2.png)

**Comment by GLITCH-Gamga** [comment]
Just Copy the UID and use the Client expetion in the following format:
UID,UID2,UID3,UID4,...
Or the Servergroup exeption like this:
GroupID.GroupID2,...

To remove the entry from the site you have to got into your database and remove the entry manually.
If you can't remember where you have stored the database for the rank system, just check the database settings in your webinterface.

**Comment by Newcomer1989** [comment]
We are counting the real clients, which are on the server. That information we got about the serverinfo command via query.
At this number also the query clients will be counted. This we substract to get the real clients.
clients online = $serverinfo['virtualserver_clientsonline'] - $serverinfo['virtualserver_queryclientsonline']

So when your bot is a query user (should be in most case), it will not be counted. If your bot uses a TS client (mostly musicbots), it will be counted.

Basicly, no I don't want to change how it is working. It would make all much more complicated and will confuse some other users.
