### ISSUE TITLE
list_rankup admin Seite 2 folgende nicht möglich

### ISSUE THREAD

**Issue by xopez** [Newcomer1989/TSN-Ranksystem#556]
Hallo,

mir ist soeben ein weiterer, eher kleiner Fehler aufgefallen.
Wenn man über das Webinterface die Clientliste komplett anschaut, also im Admin-Modus (list_rankup.php?admin=true), dann funktioniert das nur auf der ersten Seite. Sobald man auf Seite 2 oder andere klickt, oder auch auf Anzahl der Einträge landet man wieder bei der Standardansicht, welche eingeschränkt ist.

**Comment by Shad86** [comment]
Das ist uns auch schon bereits aufgefallen. 
Wir sind aber derzeit noch am überlegen, ob das ganze so in dem Umfang überhaupt noch gebraucht wird, da es früher dazu dienlich war schnell einen Blick auf die IP-Adressen zu werfen. Dies wurde auf Grund der DSGVO komplett entfernt.

Alle weiteren Daten kann man nun eig. auch durch ein kurzzeitiges Umstellen (ohne neustart des Bots) der config, einsehen. So das die Admin view eig. nur noch wenig Sinn ergibt.

**Comment by Newcomer1989** [comment]
So ganz schlüssig bin ich mir noch nicht, ob die Admin-Liste noch wirklich benötigt wird. So macht es natürlich keinen Sinn. Entweder sollte sie funktionieren oder ganz weg ;)
Da es nur eine Kleinigkeit ist, wird es mit der nächsten Version korrigiert.

**Comment by Newcomer1989** [comment]
Sollte mit 1.2.12 behoben sein.
