### ISSUE TITLE
CSRF Token ist inkorrekt oder abgelaufen 

### ISSUE THREAD

**Issue by TheViech** [Newcomer1989/TSN-Ranksystem#557]
Hallo,
ich habe vor einiger Zeit auf der ts-n.net Seite einen Rankinbot gehostet bekommen. Einige Wochen lang lief er einwandfrei allerdings bekomme ich seit einiger Zeit die Meldung: "_CSRF Token ist inkorrekt oder abgelaufen (=Sicherheitsprüfung fehlgeschlagen)! Bitte lade die Seite neu und versuche es noch einmal! Bei wiederholtem Fehlerfall bitte den Session Cookie aus deinem Browser löschen und es noch einmal versuchen!_". Ich habe versucht die Cookies meines Browsers zu löchen, einen anderes Browser zu benutzen und es mit einem anderen Computer in einem anderen Netzwerk versucht allerdings hat das alles nicht funktioniert. Die Meldung kommt immer wenn ich versuche im Webinterface etwas zu speichen z.B. Zeit hinzufügen/entfernen, Bot neustarten, Länge des Log-Auszugs verändern oder irgendwelchen Einstellungen verändern.

**Comment by Shad86** [comment]
Welche Version nutzt du derzeit?

Einzusehen unter "xyz.de/ranksystem/webinterface" (Die Versionsnummer steht dann recht groß - links oben)

MfG

Shad86

**Comment by TheViech** [comment]
Ich benutze zurzeit die Webinterface Version 1.2.11 allerdings wird es immer automatisch geupdated (hoffe das soll so sein)

**Comment by Shad86** [comment]
Ich meine ich hatte das mit newcomer schon getestet und ich meine wir hatten diesbezüglich auch in der 1.2.11 das behoben, da ich in der 1.2.10 da auch so einen Extremfall hatte.

Kannst du mal im log schauen ob du noch den updateverlauf drin hast? Wenn ja kopier den mal und schick ihn hier rein per pastebin vielleicht findet man da noch was auffälliges.

**Comment by TheViech** [comment]
Nein tut mir leid der Auszug des Logs den ich sehe ist auf 20 Zeilen beschrenkt und ich kann wegen diesem fehler nicht auf 9999 zeilen stellen aber da ich den Bot auf eurer Webside gehoste bekommen habe hoffe ich dass ihr die log datei direkt einsehen könnt. Das ist die Internetadresse des Webinterfaces: https://ts-n.net/host/rs/76/webinterface/

**Comment by Shad86** [comment]
Sorry das ich so lange nicht darauf geantwortet habe, hab deine Antwort irgendwie übersehen, am besten schreibst du newcomer per Kontakt an -> https://ts-n.net/contact.php , da es sich hierbei um eine gehostete Lösung von ihm handelt.

Hier auf Github behandeln / supporten wir mehr die self-hostings.

Von ihm oder mir gehostete Ranksysteme, werden eig. immer im eigenen Support gehandelt, zwecks der besseren Übersichtlichkeit.

**Comment by TheViech** [comment]
OK dann werde ich morgen eine Nachricht an ihn schreiben.

Danke trotsdem für die Hilfe :D
