### ISSUE TITLE
Exclude Teamspeakusers from Ranking?

### ISSUE THREAD

**Issue by dakeeper** [Newcomer1989/TSN-Ranksystem#56]
Hello,

is it possible to exclude users from the ranking system?
e.g. a Musicbot etc...

**Comment by Shad86** [comment]
Yes it is - it is under core settings:

http://puu.sh/pE56V/9cbfa80faa.png

greetings

**Comment by dakeeper** [comment]
Oh , ok just didn`t saw it. Thx.
