### ISSUE TITLE
Frage zum Boosting

### ISSUE THREAD

**Issue by xopez** [Newcomer1989/TSN-Ranksystem#564]
Hallo zusammen,
ich bin dabei das Boostingsystem mit der API von teamspeak-servers.org zu automatisieren. Ich gebe per PHP, den Usern eine Gruppe, welche im Ranksystem als Boost definiert ist. Dieses entfernt nach gewisser Zeit diesen Rang, was ja auch so gewollt ist.

Da die API, zwar nach gewisser Zeit, die abgefragte JSON leert, aber man, während man auf der Liste ist, wieder voten kann, bevor das ganze geschieht, kommt es zu unterschiedlichen Zeitintervallen, wie lang ein Vote bestehen bleibt. Der User soll den Boost auch nur erhalten, solang er drauf ist.
Soviel vorweg kommen wir zu meiner Frage.

Kann ich den Wert booosttime in der DB unter der "user"-Tabelle einfach händisch per PHP anpassen, sodass das Rankingsystem nicht mit den Unregelmäßigkeiten durcheinander kommt?
Wenn ich es richtig gesehen habe, ist die Formel einfach aktuelle Zeit + definierte Boostzeit = Zeit, bis zum Boostingende.

EDIT:
2. Frage:
Kann ich dementsprechend auch händisch die Servergruppe entfernen und das Feld boosttime auf 0 setzen in der DB?

**Comment by Shad86** [comment]
Hallo,

was händisch oder per script abzuändern ist immer mit Vorsicht zu genießen von daher empfehle ich immer zu Anfang -> Bitte erst mal ein Backup machen dann meine Gedanken dazu zu lesen und wenn dann noch gewollt umsetzen.


Die Daten in der Datenbank werden ja in einem Zyklus abgearbeitet, wenn du es also gerade bearbeitest, während die Datenbank daran arbeitet, kann es sein das die Änderung von dir gar nicht greift.

Du müsstest also dann auch noch schauen / überprüfen ob er den Wert den du verändert hast tatsächlich übernommen hat.

0 Hatte bei mir nicht funktioniert 1 hingegen als kleinster Wert funktionierte Prima (2 mal getestet), Vorteil -> du stellst es auf 1 und das Ranksystem entfernt 1 Sekunde später die Servergruppe, somit müsstest du die Servergruppe nicht selbst entfernen.


 (Getestet mit Realtime auf einem mittel bis wenig ausgelasteten Server)

Viel Spaß beim testen, ich denke das sollte ohne weiteres möglich sein. Aber wie schon am Anfang gesagt bitte erst ein backup machen.

MfG

Shad

**Comment by xopez** [comment]
Danke schonmal für die Hinweise. Schließe den Post erstmal, werde es aber mal so versuchen 👍
