### ISSUE TITLE
Boost Function - Wrong group named in log

### ISSUE THREAD

**Issue by xopez** [Newcomer1989/TSN-Ranksystem#565]
Hallo,

ich verwende ja seit kurzem das Boostsystem.
Mir ist eine kleine unschönheit im Log aufgefallen, wenn der betroffene User, nach abgelaufener Zeit, die Servergruppe entfernt bekommt. Es wird die richtige Gruppe entfernt.
`<19:15:10> "Buboder|Fynn" wurde von "Ranksystem" aus der Server Gruppe "Voter" entfernt.`
Laut TS, was ja stimmt.
Im Log steht jedoch `2018-12-17 19:15:13.745989   INFO      Servergruppe Rang 36 (ID: 71) von User 'Buboder|Fynn'`
Das ist die Gruppe die er aktuell vom Ranksystem hat. Dort müsste theoretisch auch die Gruppe, in meinem Fall "Voter", stehen.

**Comment by Newcomer1989** [comment]
Ok, vielen Dank für den Hinweis. Wir werden es uns ansehen und mit einer der nächsten Versionen bereinigen.

**Comment by Newcomer1989** [comment]
Sollte mit 1.2.12 behoben sein.
