### ISSUE TITLE
Es werden keine Ranks mehr auf dem TS vergeben aber in den Stats aufgehführt

### ISSUE THREAD

**Issue by RoY4ll** [Newcomer1989/TSN-Ranksystem#567]
Guten Tag in die Runde,
seit dem ich einen Crash auf meinem Server hatte habe ich alles wieder neu gemacht. Die alte Datenbank wieder hergestellt etc. Alle haben Ihre Ranks aber wenn ein neuer dazu kommt bekomme ich dieses zwar im Log zu sehen, so wie in den Stats, jedoch bekommt derjenige seinen Rank nicht.
Der Bot zeigt keinerlei fehler an. Könnt ihr mir da helfen?

Gruß

**Comment by Newcomer1989** [comment]
Bitte dazu den folgenden Wiki Eintrag beachten:
https://github.com/Newcomer1989/TSN-Ranksystem/wiki#changed-teamspeak-host--server---mitigation-old-ranksystem

Fraglich ist, wie der Restore erfolgte. Haben sich dadurch ggfs. IDs von Servergruppen auf dem TS geändert? Dann wäre speziell Punkt 4.4 des o.g. Wiki Eintrags zu beachten.
