### ISSUE TITLE
Boost function - Allow Floatingnumberes as factor

### ISSUE THREAD

**Issue by xopez** [Newcomer1989/TSN-Ranksystem#568]
Hello,
Simple as the title says. It would be nice, if you can take a factor like 1.25 and not only whole integers. Maybe you can limit it to 3 decimal places.

**Comment by xopez** [comment]
Yeah, for my uses factor 2 is a bit to much

**Comment by Newcomer1989** [comment]
This feature will be added with the next version.

**Comment by xopez** [comment]
working fine with 1.3.0.
Closing it
