### ISSUE TITLE
Error due selecting virtual server - 1024: invalid serverID

### ISSUE THREAD

**Issue by BlackScaryZ** [Newcomer1989/TSN-Ranksystem#570]
Hi, Sorry for my bad english I try to make good explain.

When I boot the bot I have this error "Error due selecting virtual server - 1024: invalid serverID"
I have same error in YaTqa but I can fix that when I enter manualy the server id.
Now I want know how can I enter manualy the server id in Rank system bot ? Can we update for add case with server id in config ?

**Comment by BlackScaryZ** [comment]
Ok I fix my problem.
In jobs/bot.php line 282 I replace that
$ts3server = $ts3host->serverGetByPort($ts['voice'], $queryname);
by
$ts3server = $ts3host->serverGetById(myserverid);
and now bot work

**Comment by xopez** [comment]
I think the line is wrong:
That is the location: https://github.com/Newcomer1989/TSN-Ranksystem/blob/master/jobs/bot.php#L142

**Comment by Newcomer1989** [comment]
@BlackScaryZ What voice port did you entered inside the Webinterface?

@xopez Whats wrong with this line?

**Comment by xopez** [comment]
> @xopez Whats wrong with this line?

I just meant that the above mentioned line is the wrong place

**Comment by Newcomer1989** [comment]
This is a question of the Ranksystem version, which BlackScaryZ didn't shared with us, till now.

**Comment by Newcomer1989** [comment]
Due no response, we close this issue. Please feel free to reopen it, when you need help.
