### ISSUE TITLE
Bot Startet auf Windows nicht.

### ISSUE THREAD

**Issue by MasterYuma** [Newcomer1989/TSN-Ranksystem#573]
Hallo,

ich habe ein folgendes Problem und zwar startet der Bot nicht auf meinem Dedicated Windows Server. Als Benutzer Oberfläche für Webspace benutze ich Plesk und habe bereits PHP 7.2.14 aktiviert. Dazu habe ich die DLL in der php.ini für die jeweilige PHP Version ebenfalls aktiviert. Sowie Neustart der Service ebenfalls durchgeführt. In der phpcommand.php habe ich den Pfad bereits angepasst.
Also im allem alles gemacht. Der Bot startet auch manuell über die Windows Shell und bekomme auch die Meldung das der anfängt zu Arbeiten, jedoch anschließend mit dem Kommentar (Received signal to stop! Shutting down!) wieder ausgeschaltet wird. Habe naher auch nochmal die Checkliste abgearbeitet vom [Ticket mit Win. Problemen:](https://github.com/Newcomer1989/TSN-Ranksystem/issues/369).

LOG:
> 2019-01-18 09:17:40.614254   INFO      ###################################################################
2019-01-18 09:17:40.614925   INFO      
2019-01-18 09:17:40.615284   INFO      ###################################################################
2019-01-18 09:17:40.615606   INFO      Initialize Bot...
2019-01-18 09:17:40.619746   DEBUG     Running on OS: Windows NT 10.0
2019-01-18 09:17:40.620176   DEBUG     Using PHP Version: 7.2.14
2019-01-18 09:17:40.620478   DEBUG     Database Version: 5.6.36
2019-01-18 09:17:40.620761   INFO      Check Ranksystem database for updates...
2019-01-18 09:17:40.621040   INFO        No newer version detected; Database check finished.
2019-01-18 09:17:40.623355   INFO        Check files permissions...
2019-01-18 09:17:40.665807   INFO        Check files permissions [done]
2019-01-18 09:17:40.666219   INFO      Check Ranksystem database for updates [done]
2019-01-18 09:17:40.666474   INFO      Check Ranksystem files for updates...
2019-01-18 09:17:40.666737   INFO      Check Ranksystem files for updates [done]
2019-01-18 09:17:40.666986   INFO      Ranksystem Version: 1.2.11
2019-01-18 09:17:40.667239   INFO      Loading addons...
2019-01-18 09:17:40.667863   INFO        Addon: 'assign_groups' [OFF]
2019-01-18 09:17:40.668143   INFO      Loading addons [done]
2019-01-18 09:17:40.668381   INFO      Connect to TS3 Server (Address: "localhost" Voice-Port: "9987" Query-Port: "10011" SSH: "0").
2019-01-18 09:17:40.680308   INFO      Connection to TS3 Server established.
2019-01-18 09:17:40.680921   INFO        TS3 Server version: 3.5.0 on Windows [Build: 1540536487 from 2018-10-26 08:48:07]
2019-01-18 09:17:40.681177   INFO          Select virtual server...
2019-01-18 09:17:40.683892   INFO          Select virtual server [done]
2019-01-18 09:17:40.685091   INFO        Joined to specified Channel.
2019-01-18 09:17:40.685367   INFO      Config check started...
2019-01-18 09:17:40.686065   INFO      Config check [done]
2019-01-18 09:17:40.686322   INFO      Bot starts now his work!
2019-01-18 09:17:43.683051   INFO      Received signal to stop! Shutting down!

Würde mich über eine Hilfe sehr freuen.

Beste Grüße
MasterYuma (Varnox Gaming Administrator)

**Comment by MasterYuma** [comment]
Update: Habe versucht den Bot manuell über den Worker zu starten und bekomme folgende Fehlermeldung.

> Starting the Ranksystem Bot.No Instance(s) Available.
 [Failed]

Ich habe jedoch die COM ext. in der jeweiligen PHP Version aktiviert.


Grüße
MasterYuma

**Comment by DAmNRelentless** [comment]
@MasterYuma 
Ich hatte mit dieser PHP Version auch dieses Problem. Geh mal runter auf die 7.1. Da hat's bei mir sofort funktioniert.

**Comment by MasterYuma** [comment]
@DAmNRelentless Es geht ebenfalls nicht.

Welche Extension muss man den genau alle in die PHP.ini eintragen ?
Habe bis jetzt nur die php_com_dotnet.dll eingetragen, weil curl und sowas schon aktiviert sind.

> ;extension=php_bz2.dll
extension=php_curl.dll
;extension=php_fileinfo.dll
;extension=php_ftp.dll
extension=php_gd2.dll
extension=php_gettext.dll
;extension=php_gmp.dll
;extension=php_intl.dll
extension=php_imap.dll
;extension=php_interbase.dll
;extension=php_ldap.dll
extension=php_mbstring.dll
;extension=php_exif.dll 
extension=php_mysqli.dll
;extension=php_oci8_12c.dll
extension=php_openssl.dll
;extension=php_pdo_firebird.dll
extension=php_pdo_mysql.dll
;extension=php_pdo_oci.dll
;extension=php_pdo_odbc.dll
;extension=php_pdo_pgsql.dll
extension=php_pdo_sqlite.dll
;extension=php_pgsql.dll
;extension=php_shmop.dll
;extension=php_snmp.dll
;extension=php_soap.dll
extension=php_sockets.dll
extension=php_sqlite3.dll
;extension=php_tidy.dll
;extension=php_xmlrpc.dll
extension=php_xsl.dll
extension=php_com_dotnet.dll


Grüße
MasterYuma

**Comment by DAmNRelentless** [comment]
@MasterYuma
Hast du auch den Pfad zu PHP im Ranking-System geändert? Ich hab mir einiges an Kopfzerbrechen gespart, indem ich die Umgebungsvariable von PHP einfach geändert habe zur alten Version. Diese wurde aber nur aktualisiert, nachdem ich das System neugestartet habe, also da erstmal drauf achten.
Ansonsten habe ich folgende Extensions aktiviert:
```
extension=php_com_dotnet.dll
;extension=php_bz2.dll
extension=php_curl.dll
;extension=php_fileinfo.dll
;extension=php_ftp.dll
extension=php_gd2.dll
extension=php_gettext.dll
;extension=php_gmp.dll
;extension=php_intl.dll
extension=php_imap.dll
;extension=php_interbase.dll
;extension=php_ldap.dll
extension=php_mbstring.dll
;extension=php_exif.dll
extension=php_mysqli.dll
;extension=php_oci8_12c.dll
extension=php_openssl.dll
;extension=php_pdo_firebird.dll
extension=php_pdo_mysql.dll
;extension=php_pdo_oci.dll
;extension=php_pdo_odbc.dll
;extension=php_pdo_pgsql.dll
extension=php_pdo_sqlite.dll
;extension=php_pgsql.dll
;extension=php_shmop.dll
;extension=php_snmp.dll
;extension=php_soap.dll
extension=php_sockets.dll
extension=php_sqlite3.dll
;extension=php_tidy.dll
;extension=php_xmlrpc.dll
extension=php_xsl.dll
```
Guck auch nochmal nach, ob die `php_com_dotnet.dll` sich wirklich im Extensions Ordner befindet. Bei manchen Fällen bei PHP 7.1 fehlt die nämlich. Einfach mal in die PHP Log schauen, welcher Fehler es sonst noch sein kann.

**Comment by Newcomer1989** [comment]
Das klingt schwer nach der COM-Extension.
1) Bist du dir sicher, dass du in der richtigen PHP.ini bist, welche auch zu der Version 7.2.14 gehört?
2) Bitte prüfe, ob auch die php_com_dotnet.dll in dem angegebenen extension Verzeichnis liegt.

**Comment by MasterYuma** [comment]
@DAmNRelentless Habe auch den Pfad angepasst zu der aktuellen PHP-Version. Habe auch nach der Änderung von der php.ini den Service Neugestartet. Dazu es ist egal mit welcher PHP-Version ich es teste kommt immer das selbe dabei raus.

@Newcomer1989 Ich habe in allen PHP Versionen von Plesk die COM-Extension aktiviert. Sowie auch die DLL files vorhanden sind.


Ich führe im Ranksystem Pfad die Windows-Shell aus, natürlich als Administrator und versuche die Worker.php manuell zu Starten wo dann der Instance Fehler kommt. Die Methode mit der Deaktivierung von error_reporting(0); in der bot.php habe ich auch bereits gemacht und der Bot Startet einwandfrei wie auch oben beschrieben, jedoch beendet der sich auch gleich mit dem Kommentar "Received signal to stop! Shutting down!". Hier vermute ich einfach eine einmalige Ausführung zum Start.


Grüße
MasterYuma

**Comment by Newcomer1989** [comment]
WMIC ist bei dir auch verfügbar?
-> Punkt 4

https://github.com/Newcomer1989/TSN-Ranksystem/wiki/Bot-not-starting---Windows

**Comment by MasterYuma** [comment]
Soweit ich weiß noch nicht aktiviert, weil ich auch zum ersten Mal was davon höre. Ich werde es Morgen testen und bescheid geben.

Gute Nacht Allen

**Comment by Newcomer1989** [comment]
Ich glaube, wir haben bald alle Punkte der Liste durch. ;-)
Einer davon wird es jedoch sehr wahrscheinlich sein.

Schaue doch gerne mal bei uns auf dem Public Server vorbei. Wir können uns das gerne mal gemeinsam per Fernwartung anschauen.

**Comment by MasterYuma** [comment]
Okay ich werde heute mal vorbei schauen. Wäre ca. 20:30 da kann es aber nicht versprechen. :)

Grüße
MasterYuma

**Comment by Newcomer1989** [comment]
kein Problem.. einfach in der Abendzeit mal probieren.

**Comment by MasterYuma** [comment]
@Newcomer1989 Ich habe zwar das Problem noch nicht gelöst aber ich glaube das wir die nächste Zeit auf Linux umsteigen da unsere Projekte nicht wirklich Windows brauchen. Wir haben jetzt Ranksystem über unseren alten Linux Server laufen.

Ich habe mir mal den Code angeschaut und festgestellt das in worker.php unter der function start zwei User Names eingetragen sind. 
root / administrator

Jedoch sind die Usernames bei vielen unterschiedlich und habe den Code ein wenig angepasst.
Habe hinzugefügt das der current user ausgelesen wird.

> if(isset($_SERVER['USER']) && $_SERVER['USER'] == "root" || isset($_SERVER['USERNAME']) && $_SERVER['USERNAME'] == 'get_current_user')

Wäre eventuell eine bessere Möglichkeit. :)


Beste Grüße
MasterYuma

**Comment by Newcomer1989** [comment]
Die Prüfung auf root bzw. administrator ist ein Check, dass das Ranksystem nicht mit vollen Admin-Rechten gestartet wird. Wer es unbedingt will, kann 10 Sekunden warten, dann startet es dennoch.. aber es gibt zumindest eine Warnmeldung.
Diese Warnmeldung auf den 'current_user' auszuweiten, wäre da nicht zielführend.
