### ISSUE TITLE
Aktualisierung der Libraries

### ISSUE THREAD

**Issue by xopez** [Newcomer1989/TSN-Ranksystem#575]
Hallo,

ich würde gerne was ansprechen zwecks der aktuellen Bibliotheken.
Für folgende gibt es bereits eine neuere Version. Nur weiß ich nicht in wie weit das einfach machbar ist.

Font Awesome 4.7.0 → 5.6.3
flag-icon-css 2.8.0 → 3.2.1
Bootstrap 3.3.7 → 4.2.1
morris.js 0.5.0 → 0.5.1 (bereits hier: #574)
Bootstrap Switch 3.3.2 → 4.7.0 (8 Tage alt und auch support für Bootstrap 4)
Bootstrap TouchSpin 3.1.2 → 4.2.5 (Bootstrap 4 compatible (also bootstrap 3 is still supported).)
bootstrap-select v1.13.0-beta → 1.13.2 (Support für Bootstrap 4) EDIT: Auf Github bereits v1.13.5
Bootstrap Show Password 1.0.3 → 1.1.2 (Copyright erneuern)

**Comment by Newcomer1989** [comment]
Inbesondere Bootstrap 4 ist ohne weiteres leider nicht machbar, da alle anderen Libs auch mit bootstrap 4 klar kommen müssen. Zumindest war hier mein letzter Stand, dass dies nich alle können. Habe aber auch schon einige Zeit nicht mehr alle Libs im Detail geprüft.
Grundlegend updaten wir aber immer mal wieder die Libs, sofern es zu keinen Abhängigkeitsproblemen kommt bzw. Bugs entstehen. Eine neue Version ist nicht immer auch gut ;)

In Bezug auf das Webinterface steht aber noch ein Umbau an, welcher für die Stats-Seite schon vor einigen Versionen passiert ist (mit 1.2.7). Damit würden dann auch die Libs zwischen Stats-Seite und Webinterface wieder gleich gezogen werden, was dann natürlich auch noch im Copyright vermerkt wird.

Generell sind wir noch daran einige Optimierungen am Code vorzunehmen und gewisse gewachsene Dinge mal "aufzuräumen". Da wird sich in den nächsten Versionen noch einiges tun.

**Comment by Newcomer1989** [comment]
Ein Teil der Libs wurde mit der 1.3.0 aktualisiert, sofern es zu keinen Kompatibilitätsproblemen kam.

Bootstrap 4 bedingt ein Austausch einiger Libs, daher wird dies vorerst nicht kommen. Es steht auf unserer ToDo-Liste, aber noch weit in der Zukunft.
