### ISSUE TITLE
Windows, Invalid Query

### ISSUE THREAD

**Issue by JaniVagyok** [Newcomer1989/TSN-Ranksystem#576]
Hello, says invalid query, i can login with the query i created, how can i fix it ? http://prntscr.com/mcy5d9

**Comment by Newcomer1989** [comment]
Please have a look to the point 4 of the wiki. -> [WMIC](https://github.com/Newcomer1989/TSN-Ranksystem/wiki/Windows---Checklist---Bot-not-starting#4-wmic-command-registered)

**Comment by Newcomer1989** [comment]
Closed due no response
