### ISSUE TITLE
xampp connection error

### ISSUE THREAD

**Issue by Drmohammad11** [Newcomer1989/TSN-Ranksystem#577]
Failed to connect to database: SQLSTATE[HY000] [1045] Access denied for user 'rankuser'@'localhost' (using password: YES)

**Comment by Newcomer1989** [comment]
How can we help you with this?

It says, the connection details of your database are wrong.

Please check the entered credentials during the installation process.

**Comment by htm1994** [comment]
Hi 
I install xampp 5.6 and i going install tsn rank system.
when click install database show this error:
Failed to connect to database: SQLSTATE[HY000] [1045] Access denied for user 'rankuser'@'localhost' (using password: YES)
check this file xampp/phpmyadmin/bin/config.php.ini 
Password is empty but show this error
plz help me.

**Comment by Newcomer1989** [comment]
You added a DB user named "rankuser" and set this as "localhost"?

Then you should give them a passwort due creation.
example:
`create user 'rankuser'@'localhost' identified by 'your_password_here';`

<br><br>

> Failed to connect to database: SQLSTATE[HY000] [1045] Access denied for user 'rankuser'@'localhost' (using password: YES)

That message says, your user has a password, but that one you typed in is wrong.

If you still need help, please try to google this error. It isn't a problem with the Ranksystem. That error would also appear with each other script. This is a problem due creation the database user or inserting the credentials due installation.

**Comment by htm1994** [comment]
Hi
after copy rank system file in xampp 
in address bar example.com/install.php
then open install page and I should write dbname, dbuser. dbpassword, host address & select dbtype then click install data base but show error : Failed to connect to database: SQLSTATE[HY000] [1045] Access denied for user 'rankuser'@'localhost' (using password: YES)

search in google but not fund awnser for problem.
just find this way:
edite this file: check this file xampp/phpmyadmin/bin/config.php.ini

**Comment by Newcomer1989** [comment]
> search in google but not fund awnser for problem.

guys, really?

https://stackoverflow.com/questions/31154124/sqlstatehy000-1045-access-denied-for-user-usernamelocalhost-using-cakep

https://www.ostraining.com/blog/coding/error-1045-phpmyadmin/

Took me 2 mins of google.

**Comment by htm1994** [comment]
tank you 
I Find different link in google but i can not change password.
this link help me:
https://www.ostraining.com/blog/coding/error-1045-phpmyadmin/

tank you friend tank you.
