### ISSUE TITLE
Verify

### ISSUE THREAD

**Issue by CrazyboyUndead** [Newcomer1989/TSN-Ranksystem#578]
Hallo,
Jeder User muss sich immer wieder nach ca. 1-6 Stunden neu Verifizieren.
Ich kenne es von anderen Servern das man es sogar gar nicht machen muss.
Kann man da was einstellen oder muss es so?
Ich habe alle Voraussetzungen erfüllt, wie beschrieben: https://ts-n.net/ranksystem.php#requirements 
und alles Ordnungsgemäß installiert.
Der Bot hat auch genug rechte.

MfG Philipp

**Comment by Newcomer1989** [comment]
Did you read this?
https://github.com/Newcomer1989/TSN-Ranksystem/wiki#verify-process---how-is-it-working

**Comment by CrazyboyUndead** [comment]
Ja, aber es sollte ja wenigstens bei einigen User funktionieren. Es geht bei keinem.
Wenn es so sein soll dann kann das Problem geschlossen werden.

MfG Philipp

**Comment by Newcomer1989** [comment]
> It uses your client IP address from the website and try to match this IP address with a user on the TeamSpeak 3 server. 

Wenn also die IP Adresse auf dem TS Server eine andere ist als die auf der Homepage, kann der Bot kein Matching vornehmen. Das kann z.B. dann der Fall sein, wenn der TS Server aussschließlich oder zumindest überwiegen IPv4 nutzt, die Homepage aber IPv6.
Auch kann es vorkommen, wenn du vor deiner Homepage einen Art Proxy setzt, welcher die Quell-IP Adresse verschleiert. So macht das z.B. auch ein ganz bekannter Anbieter -> cloudflare.

Es gibt natürlich noch unzählig weitere Ursachen. Probiere doch mal auf deinem Webserver und TS-Server jeweils die IP Adressen zu tracken und miteinander zu vergleichen.
