### ISSUE TITLE
No Connect Bot

### ISSUE THREAD

**Issue by htm1994** [Newcomer1989/TSN-Ranksystem#579]
Hi
When click On Start Bot Show This message and No Connect Bot:

Ranksystem Bot should be started. Check the log below for more information!

Pictures: https://mega.nz/#!p1YGgQ5I!A55fgCKALCLnpliVS-JNWBK82zk_a_t49tcLO3dM_FU
plz help ty

**Comment by Newcomer1989** [comment]
Are you using windows?

**Comment by htm1994** [comment]
Yes
I use windows server 2012R2
plz help me

**Comment by Newcomer1989** [comment]
Please pay attention to this [wiki article](https://github.com/Newcomer1989/TSN-Ranksystem/wiki/Windows---Checklist---Bot-not-starting)

**Comment by htm1994** [comment]
Hi
Read This link and i did them.
start bot and not runing
perrmissions folder set on Which user?
start bot and show this error:
2019-02-15 21:43:34.734235   CRITICAL  Your PHP version (5.4.45) is below 5.5.0. Update of PHP is required! Shutting down!
but php version is 7.2.14
plz help me

**Comment by Newcomer1989** [comment]
If there stand PHP version 5.4.45, then your PHP version you are using is 5.4.45 not 7.2.14 :-P

You really carefully read the article? Please focus on [step 1)](https://github.com/Newcomer1989/TSN-Ranksystem/wiki/Windows---Checklist---Bot-not-starting#1-php-installationpath)

**Comment by htm1994** [comment]
Hi 
I did step1 and show php version is 7.2.14
I did not get step 5 & 6.
how to set permission folder? witch users?
ty

**Comment by Newcomer1989** [comment]
> You really carefully read the article? Please focus on [step 1)](https://github.com/Newcomer1989/TSN-Ranksystem/wiki/Windows---Checklist---Bot-not-starting#1-php-installationpath)

-> Fill out the full path to the php.exe into the file other/phpcommand.php. Examples are already inside. 

When you see inside the Ranksystem.log the PHP version 7.x, you have done it right!

**Comment by htm1994** [comment]
Hi
This Picture for show php version.
![phpver](https://user-images.githubusercontent.com/13364607/52916551-40156b80-32f6-11e9-9350-b3c4ae6a9d19.png)

log tsn rank bot:
`2019-02-15 21:37:53.170307   DEBUG     Successful login attempt to the webinterface from IP ::1.
2019-02-15 21:40:22.387501   DEBUG     Successful login attempt to the webinterface from IP ::1.
2019-02-15 21:42:05.323142   DEBUG     Successful login attempt to the webinterface from IP ::1.
2019-02-15 21:43:17.937560   DEBUG     Successful login attempt to the webinterface from IP ::1.
2019-02-15 21:43:34.734235   CRITICAL  Your PHP version (5.4.45) is below 5.5.0. Update of PHP is required! Shutting down!
2019-02-15 21:46:37.292464   DEBUG     Successful login attempt to the webinterface from IP ::1.
2019-02-17 18:12:06.293613   DEBUG     Successful login attempt to the webinterface from IP ::1.
`

**Comment by Newcomer1989** [comment]
How looks your `other/phpcommand.php`?

You are cheating, bro.. you go inside the xamp folder. Sure, there is under the PHP folder a php.exe inside. 
But how should the Ranksystem know, that your PHP is placed there?

So type `php -v` inside the system32 folder (or anywhere else) and you will see, you have also a PHP 5.4.45 installed.
Since your PHP environment variable ("php") is pointing to the other version (5.X), the Ranksystem will use this as default.

You need to change the environment variable or you disclose to the Ranksystem where your PHP is installed. Last you can do with the `other/phpcommand.php`.
There is also one example inside, which is exactly what you need:
`$phpcommand = 'c:\xampp\php\php.exe';`

**Comment by htm1994** [comment]
Thank you my friend
I did not understand what you meant, and I used another way to give the php address.
Thank you again

**Comment by Newcomer1989** [comment]
Ok, nice to hear it helps.
Cause it seems to be all working fine, I will close this issue. If you still need help, feel free to reopen it.
