### ISSUE TITLE
Rankbot lädt ununterbrochen Servericons herunter

### ISSUE THREAD

**Issue by Bourns** [Newcomer1989/TSN-Ranksystem#580]
Guten Tag zusammen,

ich habe ein Problem mit dem Rankbot. Im Betrieb lädt er ununterbrochen die Servericons herunter.
Ich habe eben mal in die Logs geschaut, innerhalb der letzten 2,5 Stunden wurden etwas mehr als 39000 Einträge in die Logs geschrieben und jedes mal geht es um 4 Server Icons.

Weiss jemand wie das behoben werden kann, oder soll das so sein? Auf anderen Logs die ich gegooglet habe, ist das nämlich nicht der Fall.

Übrigens sind die Icons alle im .png und .bmp Format. Der Bot hat soweit ich das sehe auch alle Rechte.

Beste Grüße

**Comment by Newcomer1989** [comment]
Bitte die Icons aus dem TS Server mal austauschen und dabei die Log beobachten. Soetwas haben wir schon öfter gesehen, wenn die Icons "korrupt" waren. Ein reupload derer hat im Regelfall geholfen.

**Comment by Bourns** [comment]
Bringt leider keine Abhilfe :-(

**Comment by Newcomer1989** [comment]
Naja, wenn alle Icons entfernt würden, dürfte der Bot keine mehr runterladen. Folglich muss es Abhilfe schaffen.
Über die Vorgehensweise könnte man mit einem Schritt für Schritt Entfernen/Hinzufügen von Icons ermitteln können an welchem es lag/liegt.
Sofern du hier näheres ausmachen könntest, wäre es natürlich hilfreich einen Hinweis zu erhalten. Ggfs. das betroffene Icon zu sharen, wenn/damit es sich nachstellen lässt.

**Comment by Bourns** [comment]
Ich habe mir auf dem Server alle Icons anzeigen lassen, habe Sie alle gelöscht und den Server bzw den Bot neu gestartet. Dann lädt der Bot auch keine Icons mehr, da ja sämtliche Servergruppen "nackt"sind. Sobald ich einer Gruppe wieder Icons vergebe, fängt der Bot an, sich wieder in dauerschleife zu laden. Kann es sein das vielleicht vielleicht noch zusätliche Recht vergeben oder geändert werden müssen? Habe eure Anleitung befolgt mit einer Ausnahme. Mein Pfad ist nicht /var/www/ranksystem sondern jetzt gerade aktuell /var/www/html/ranksystem da das webinterface in eurer Vorgabe nicht aufgerufen werden konnte.

Beste Grüße

**Comment by Bourns** [comment]
Kurze Anmerkung. Es ist übrigens egal ob ich nur ein Icon Stück für Stück vergebe um den Fehler einzugrenzen oder ob ich mehrere vergebe. Das Problem ändert sich nicht.

**Comment by Newcomer1989** [comment]
Bitte stelle uns ein Icon mal bereit, welches das Problem verursacht.

**Comment by Bourns** [comment]
ich habe dir mal ein paar mehr eingefügt.

Beste Grüße

![pubg](https://user-images.githubusercontent.com/47642062/52901424-b4bbad80-3203-11e9-9726-231406bb1e92.png)
![red-c](https://user-images.githubusercontent.com/47642062/52901426-b9806180-3203-11e9-81e7-1b5f1026bb48.png)
![serveradmin](https://user-images.githubusercontent.com/47642062/52901427-ba18f800-3203-11e9-9338-38d70c618081.png)
![gta 5](https://user-images.githubusercontent.com/47642062/52901431-c8671400-3203-11e9-9cdf-ce011a542421.png)
![dying light](https://user-images.githubusercontent.com/47642062/52901432-c8ffaa80-3203-11e9-9e6a-ee68a0b9d0b5.png)
![gast](https://user-images.githubusercontent.com/47642062/52901433-c8ffaa80-3203-11e9-8081-962b2873b439.png)
![germany](https://user-images.githubusercontent.com/47642062/52901434-c8ffaa80-3203-11e9-94c6-3fa719ab019c.png)

**Comment by Newcomer1989** [comment]
Habe das erste mal ausprobiert.. Habe damit keine Probleme

```
2019-02-16 16:12:58.148608   INFO      Noticed icon of servergroup 'Meta Server Admin' with ID 47 got removed from TS3 server, now it was also removed from the Ranksystem.
2019-02-16 16:12:43.137394   INFO      Download new ServerGroupIcon for group 'Meta Server Admin' with ID: 47
```

**Comment by Newcomer1989** [comment]
Welches Betriebssystem hat denn dein TS Host?

**Comment by Bourns** [comment]
Bis vorhin habe ich es auf einem Raspbian Pi mit Raspbian Stretch versucht.

**Comment by Newcomer1989** [comment]
Ein Raspberry PI hat einen ARM CPU, welcher von TeamSpeak nicht supportet wird. Vermutlich ist es ein Problem von/mit TeamSpeak.

**Comment by Newcomer1989** [comment]
https://forum.teamspeak.com/threads/133432-TeamSpeak-on-Raspberry-Pi?highlight=ARM+Raspberry

They are not supported for "**server** and PC client."
