### ISSUE TITLE
phpseclib Integration 

### ISSUE THREAD

**Issue by xopez** [Newcomer1989/TSN-Ranksystem#581]
Hallo,

Ich habe die Tage zum ersten mal was über phpseclib gelesen und es bietet ssh an. Damit wäre es möglich ssh ohne das php Modul zu nutzen.
https://github.com/phpseclib/phpseclib
Nur so als Idee, da man das Modul ja immer. Händisch installieren muss

**Comment by Newcomer1989** [comment]
Dafür wird eine extra extension im Webserver benötigt, welche das Ranksystem nicht mitliefern kann. Weiterhin würden einige, die einen free Webhoster nutzen, damit vollständig entfallen, da sie den Webserver garantiert nicht um weitere Pakete erweitern können.

So auf die schnelle gesehen heißt das IMHO -> Ersetze derzeit den Install von PHP-SSH2

```sudo apt-get install php-ssh2```

durch phpseclib

```
sudo apt-get install php-pgsql php-pear
sudo pear channel-discover phpseclib.sourceforge.net
sudo pear remote-list -c phpseclib
sudo pear install phpseclib/Net_SSH2
sudo service apache2 restart
```

Sieht nicht wirklich einfacher für den Anwender aus. Dann kommen noch die Unterschiede der jeweiligen Webserver hinzu, etc. pp.

**Comment by xopez** [comment]
Okay. Ich dachte man kann es einfach als Library einbindet.

```
<?php
set_include_path(get_include_path() . PATH_SEPARATOR . 'phpseclib');

include('Net/SSH2.php');
?> 
```

**Comment by Newcomer1989** [comment]
Sehe da aktuell keine Notwendigkeit.
a) Ist der SSH Query von TeamSpeak noch sehr verbuggt (siehe auch https://github.com/Newcomer1989/TSN-Ranksystem/issues/550)
b) Nutzt so gut wie niemand die SSH-Schnittstelle, nicht zuletzt wg. a)
c) Unter localhost-Verbindungen ist die SSH Verbindung grundlegend nicht zu empfehlen (perfomance-Verlust)

Wenn du das anders siehst, mache gernen einen Pull-Request und baue die lib entsprechend ein.
Bitte die Abhängigkeiten dokumentieren (welche Pakete installiert werden müssen, etc). Zumeist wird wohl Apache, nginx und IIS als Webserver eingesetzt. Die Lösung müsste diese also unebdingt unterstützen!
