### ISSUE TITLE
Problems with V7.3 PHP

### ISSUE THREAD

**Issue by ruymb** [Newcomer1989/TSN-Ranksystem#584]
Hi there I seem to be having a problem with 7.3 when using this system when I was using it with VestaCP it worked perfectly but due to complications with the host I had to move to another host I decided to use ISP Manager v5.0, Since then I can't seem to get the bot to start at all I've checked all pacakges to make sure it works PHP-XML, PHP-SSH2, PHP-ZIP all are installed and the exec permissions are working so I can't understand why the bot is not working?

Please could you help me

Many thanks
RUYMB.

**Comment by Shad86** [comment]
> PHP 5.5.0 or higher with PDO support; PHP 7.3 ready!
> with privileges for PHP command "exec"
> with "cURL" extension for PHP
> with "Zip" extension for PHP
> with "COM" extension for PHP (needed on Windows only)
> with "SSH2" extension for PHP (needed for TS3 query connection with SSH)

These are the needed packages.

Next question do you use Windows or Linux? (VPS) or only a Webhoster?

Also could you please provide logs from the ranksystem (there is a folder called logs in the ranksystem folder)

regards

Shadow86

**Comment by ruymb** [comment]
Guess what all installed.

**Comment by ruymb** [comment]
I use Linux ISP Manager 5.

**Comment by Newcomer1989** [comment]
Are you sure, you checked the installed packages for the right PHP version?

Please locate your PHP version on your system. Put the full path into the `other/phpcommand.php`.
We have described what to do for windows, [here](https://github.com/Newcomer1989/TSN-Ranksystem/wiki/Windows---Checklist---Bot-not-starting#1-php-installationpath). I think it should be no problem to adapt it for linux.

**Comment by Newcomer1989** [comment]
Closed, since no response
