### ISSUE TITLE
Dauerhafter Festplattenzugriff

### ISSUE THREAD

**Issue by UeberDaniel** [Newcomer1989/TSN-Ranksystem#586]
Habe heute mal das Rankingsystem auf meinen Server gemacht und bemerkt, dass sekündlich auf die Festplatte zugegriffen wird (auch ohne einen einzigen User im TS). Ich denke auf Dauer wird das die Lebenszeit der Platte verkürzen. Gibt es eine Möglichkeit die Lese/Schreibzugriffe nur z. B. einmal alle 5 Minuten stattfinden zu lassen, bzw. wenn es nötig ist?
![hdd](https://user-images.githubusercontent.com/10797624/53614441-4ea73100-3bda-11e9-9e80-d0add39c9d68.jpg)

**Comment by UeberDaniel** [comment]
Wahr wohl doch kein dauerhafter Zustand

**Comment by Newcomer1989** [comment]
Eine Festplatte für einen Server sollte darauf ausgelegt sein. Die Zugriffswerte scheinen auf den ersten Blick völlig normal zu sein. Auch kommen diese vermutlich nicht ausschließlich vom Ranksystem. Das System selbst schreibt regelmäßig Systemlogs etc..

Im Webinterface kannst du unter "TeamSpeak" den "Query-Slowmode" nutzen, um die System-Ressourcen zu schonen. Natürlich auf Kosten der Genauigkeit des Bots.

Ansonsten werden die meisten Schreibzugriffe vermutlich von der Datenbank verursacht. Hier kannst du deine Platte deutlich entlasten, wenn die DB sauber cached, also den RAM nutzt.
Mögliche Systemoptimierungen haben wir [hier](https://ts-n.net/ranksystem.php#optimize) zusammengefasst. Speziell Punkt 3 und das dort verlinkte Tutorial kann ich nur empfehlen.
