### ISSUE TITLE
Select on DB failed

### ISSUE THREAD

**Issue by MARL3N** [Newcomer1989/TSN-Ranksystem#587]
2019-03-02 20:42:45.230049   CRITICAL  Select on DB failed: Array
![453b94193e55b1751d207daf751682dd](https://user-images.githubusercontent.com/43937273/53687057-b2e40500-3d40-11e9-9e9c-e9e36f7103b0.png)

**Comment by Shad86** [comment]
Means that the Server lost the connection to the mysql server or the mysql server got shut down - so its a error on your side, what you have to check

**Comment by Newcomer1989** [comment]
Have also a look [here](https://github.com/Newcomer1989/TSN-Ranksystem/issues/406)
