### ISSUE TITLE
[Fixed] Bot startet nicht

### ISSUE THREAD

**Issue by FreakyFP** [Newcomer1989/TSN-Ranksystem#588]
Hey, ich habe das Ranksystem jetzt über einen längeren Zeitraum ohne Probleme genutzt doch nachdem ich es ca. einen Monat aus hatte und nun wieder nutzen wollte startet es nichtmehr, es erschient wie gewohnt die Meldung der Bot sei gestartet der log bleibt leer.

Dass steht in den Apache logs

`2019-03-07 14:02:43	Access	91.xxx.xxx.xx	200	POST /ranking/webinterface/bot.php HTTP/1.0	https://www.hardcoregamers.de/ranking/webinterface/bot.php	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.2 Safari/605.1.15	34.5 K	Apache SSL/TLS access
`

**Comment by Newcomer1989** [comment]
Welches Operating System läuft denn auf der Machine, auf der das Ranksystem installiert ist? Windows?

**Comment by FreakyFP** [comment]
Ubuntu 18.04

**Comment by Newcomer1989** [comment]
Wurde denn evtl. eine neue PHP Version aufgespielt? Dann könnten noch notwendige Pakete fehlen.

Schau mal hier bei Schritt 3
https://ts-n.net/ranksystem.php#install

**Comment by FreakyFP** [comment]
Habe jetzt alles überprüft und es war schon alles vorhanden, funktioniert dennoch nicht

**Comment by Newcomer1989** [comment]
Bitte mal auf dem TeamSpeak bei uns vorbei schauen.. dann können wir via Remote Session uns das Problem mal ansehen.

**Comment by Newcomer1989** [comment]
Problem war/ist die DNS Auflösung auf dem Server.
Als Datenbank-Adresse wurde "localhost" verwendet, was wohl nicht funktionierte. Mit "127.0.0.1" klappte es problemlos.
