### ISSUE TITLE
webinterface login giving black page

### ISSUE THREAD

**Issue by Joele25** [Newcomer1989/TSN-Ranksystem#589]
Hi, I had a datamigration from one server to another. After I changed up a bit the database settings to match the new one I tryed to login into the webinterface but It gives me a blank page. What should I do?

**Comment by Newcomer1989** [comment]
Sound like something is wrong with your database. Wrong credentials, failed permissions, connection issues...

Please have also a look [here](https://github.com/Newcomer1989/TSN-Ranksystem/wiki#changed-teamspeak-host--server---mitigation-old-ranksystem)

**Comment by Joele25** [comment]
I'm sure that the dbconfig.php is correct. What else could it be? I also modified the path to php to match the new one, is it possible that in some way is not correct?

**Comment by Joele25** [comment]
I think I get what is going wrong here, how can I get ranksystem to use a specific centos user? Could be a permission problem

**Comment by Joele25** [comment]
Resolved upgrading my php version to 7.3.3
