### ISSUE TITLE
Problem with giving ranks

### ISSUE THREAD

**Issue by mimi0808** [Newcomer1989/TSN-Ranksystem#59]
Hi,

I have a problem with giving ranks. Everything I have set. Bot sends a message about reaching the next rank, but does not grant the rank. The log shows: 
"ERROR     calc_user 10:It happened a problem with the servergroup of the user mimi0808  (unique Client-ID: xxxxxxxxxxxxxxxxxxx; Client-database-ID 13)!"
Everything else works just bot is not give ranks.

Thanks in advance for help

**Comment by Shad86** [comment]
Can you go to /webinterface.php and login.

Then go to Core settings and pls make a screenshot of the line rankup and maybe also offer a logfile pls dont forgett to remove sensitive datas from the log if there are some.

regards

**Comment by mimi0808** [comment]
Thanks for your interest in my problem.

screenshot:
![ranksystem](https://cloud.githubusercontent.com/assets/20230028/16506082/6c8cda76-3f20-11e6-969b-d1f511524fca.jpg)
![ranksystem2](https://cloud.githubusercontent.com/assets/20230028/16506085/7239621e-3f20-11e6-81cd-54780f808e4f.jpg)

I would add that the bot is logged on the original serveradmin so have all the powers. (It can not be over, not have permission to give rank)

Sorry for my English
Regards

**Comment by Newcomer1989** [comment]
Which servergroups the user have and which group should be given by the Ranksystem?

Plese delete the ending comma at your servergroup exception!

**Comment by mimi0808** [comment]
The user is a Guest/Normal (I tested both possibilities). He should get the group "LvL 1" - group which I gave id 62.
