### ISSUE TITLE
Webinterface Start/Stop page is not working

### ISSUE THREAD

**Issue by Joele25** [Newcomer1989/TSN-Ranksystem#590]
As title my start/stop page is not working at all. Logs are visible only if you refresh the page. The only way I saw that actually work for starting the boot is to run manually the command via SSH.
The page load itself proprely and respond with a message based on what button you clicked but it still doesnt work. What can it be?

Running on CentOS7 with Apache. 
My PHP version
`PHP 7.2.16 (cli) (built: Mar  5 2019 14:45:10) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
with Zend OPcache v7.2.16, Copyright (c) 1999-2018, by Zend Technologies
`
My PHP extensions
`opcache bcmath bz2 calendar ctype curl dom exif fileinfo ftp gd gettext iconv json mbstring mysqlnd pdo phar posix shmop simplexmlsockets sqlite3 sysvmsg sysvsem sysvshm tidy tokenizer xml xmlwriter xsl mcrypt mysqli pdo_mysql pdo_sqlite wddx xmlreaderssh2 zip
`

**Comment by Newcomer1989** [comment]
You need to define the right PHP for the Ransystem Bot.

https://github.com/Newcomer1989/TSN-Ranksystem/wiki#multiple-php-versions---how-to-set-the-php-version

Be sure, the PHP version you define, fullfill the required extensions.

**Comment by Joele25** [comment]
Solved, thanks!
