### ISSUE TITLE
Error on loading addons config nach wiederherstellung

### ISSUE THREAD

**Issue by xopez** [Newcomer1989/TSN-Ranksystem#592]
Hallo,

ich mein Ranksystem scheint nach der Wiederherstellung eines Backups nicht mehr aufrufbar zu sein.
Das Backup wurde mit mysqldump gemacht, als der Bot aus war. Ich habe meinen Server zurückgesetzt, da ich weg von Plesk wollte.
Ich habe in MySQL einen User angelegt und dieser hat definitiv auch rechte auf das Ranksytem.
User wie folgt im MySQL erfasst:
```
CREATE USER 'ts3_ranksystem'@'localhost' identified by 'PASS';
GRANT ALL PRIVILEGES ON ts3_ranksystem to 'ts3_ranksystem'@'localhost';
```
Dazu habe ich die dbconfig.php angepasst mit neuem User und passwort.
Auf der stats seite erscheint die Meldung `Error on loading addons config.. Database down, not reachable, corrupt or empty?`

Ein start via CLI schreibt einen anderen Fehler.
```
sudo -u www-data php /var/www/html/rank.mightful-noobs.de/worker.php start

 !!!! Logs folder is not writable !!!!

 Cancel start request...

```

**Comment by Shad86** [comment]
Vermutlich stimmen die Ordner Berechtigungen nicht oder du hast im Ranksystem einen falschen / alten logpfad angegeben. Ggf überprüfen oder eben Berechtigungen anpassen.

Ordner die "chmods" benötigen:

chmod 777 tsicons/ avatars/ logs/ update/ other/dbconfig.php -Rf

MfG

Shad86

**Comment by xopez** [comment]
Gleiche Problem. Das hatte ich auch schon größtenteils nur bei den dbconfig nicht.

**Comment by xopez** [comment]
OK, pdo-mysql war nicht aktiv.
Jetzt kommt ein andere fehler im webinterface
```2019/03/20 21:15:52 [error] 1870#1870: *834 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: cfg in /var/www/html/rank.mightful-noobs.de/webinterface/index.php on line 66PHP message: PHP Notice:  Undefined variable: cfg in /var/www/html/rank.mightful-noobs.de/webinterface/index.php on line 70PHP message: PHP Notice:  Undefined variable: cfg in /var/www/html/rank.mightful-noobs.de/webinterface/index.php on line 76PHP message: PHP Notice:  Undefined variable: cfg in /var/www/html/rank.mightful-noobs.de/webinterface/index.php on line 87PHP message: PHP Fatal error:  Uncaught Exception: DateTimeZone::__construct(): Unknown or bad timezone () in /var/www/html/rank.mightful-noobs.de/webinterface/index.php:34
Stack trace:
#0 /var/www/html/rank.mightful-noobs.de/webinterface/index.php(34): DateTimeZone->__construct('')
#1 /var/www/html/rank.mightful-noobs.de/webinterface/index.php(87): enter_logfile(NULL, '  INFO      ', 'Incorrect login...')
#2 {main}
  thrown in /var/www/html/rank.mightful-noobs.de/webinterface/index.php on line 34" while reading response header from upstream, client: 5.57.199.231, server: rank.mightful-noobs.de, request: "POST /webinterface/ HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.3-fpm.sock:", host: "rank.mightful-noobs.de", referrer: "https://rank.mightful-noobs.de/webinterface/"```

**Comment by Shad86** [comment]
Schau mal ob überhaupt alle Pakete installiert sind, nach dem zurücksetzen.

Dieser Befehl sollte eig. alle Pakete beinhalten:

apt-get install php-zip libapache2-mod-php php-curl php-xml php-mysql php-common php-ssh2

**Comment by xopez** [comment]
da gabs definitiv noch was.
```apt-get install php-zip php-curl php-xml php-mysql php-common php-ssh2
Reading package lists... Done
Building dependency tree
Reading state information... Done
php-common is already the newest version (2:69+ubuntu18.04.1+deb.sury.org+2+php7.3).
php-common set to manually installed.
php-xml is already the newest version (2:7.3+69+ubuntu18.04.1+deb.sury.org+2+php7.3).
php-xml set to manually installed.
The following additional packages will be installed:
  libssh2-1
The following NEW packages will be installed:
  libssh2-1 php-curl php-mysql php-ssh2 php-zip
...
```

Habe alle aktiviert. Nun gibts eine andere Fehlermeldung:
```
2019/03/20 21:25:13 [error] 1870#1870: *1059 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined variable: cfg in /var/www/html/rank.mightful-noobs.de/stats/index.php on line 18PHP message: PHP Notice:  Undefined variable: cfg in /var/www/html/rank.mightful-noobs.de/stats/index.php on line 20PHP message: PHP Notice:  Undefined variable: cfg in /var/www/html/rank.mightful-noobs.de/stats/index.php on line 22PHP message: PHP Notice:  Undefined variable: cfg in /var/www/html/rank.mightful-noobs.de/stats/index.php on line 24PHP message: PHP Notice:  Undefined variable: cfg in /var/www/html/rank.mightful-noobs.de/stats/index.php on line 26PHP message: PHP Notice:  Undefined variable: cfg in /var/www/html/rank.mightful-noobs.de/stats/index.php on line 28PHP message: PHP Notice:  Undefined variable: cfg in /var/www/html/rank.mightful-noobs.de/stats/index.php on line 30PHP message: PHP Notice:  Undefined variable: cfg in /var/www/html/rank.mightful-noobs.de/stats/index.php on line 32PHP message: PHP Notice:  Undefined variable: cfg in /var/www/html/rank.mightful-noobs.de/stats/index.php on line 34PHP message: PHP Notice:  Undefined variable: cfg in /var/www/html/rank.mightful-noobs.de/stats/index.php on line 36PHP message: PHP Notice:  Undefined variable: cfg in /var/www/html/rank.mightful-noobs.de/stats/index.php on line 38PHP message: PHP Notice:  Undefined variable: cfg in /var/www/html/rank.mightful-noobs.de/stats/index.php on line 40PHP message: PHP Notice:  Undefined variable: cfg in /var/www/html/rank.mightful-noobs.de/stats/index.php on line 42PHP message: PHP Fatal error:  Uncaught Error: Call to a member function fetch() on bool in /var/www/html/rank.mightful-noobs.de/stats/index.php:56
Stack trace:
#0 {main}
  thrown in /var/www/html/rank.mightful-noobs.de/stats/index.php on line 56" while reading response header from upstream, client: 5.57.199.231, server: rank.mightful-noobs.de, request: "GET /stats/ HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.3-fpm.sock:", host: "rank.mightful-noobs.de"```
libapache2-mod-php ist für mich nicht relevant, da ich nginx nutze.

Vielleicht stimmt auch was mit meiner NGINX config nicht.
```
server {
	listen 443 ssl http2;
	listen [::]:443 ssl http2;

	server_name rank.mightful-noobs.de;
	set $base /var/www/html/rank.mightful-noobs.de;
	root $base/;

	# SSL
	ssl_certificate /etc/letsencrypt/live/rank.mightful-noobs.de/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/rank.mightful-noobs.de/privkey.pem;
	ssl_trusted_certificate /etc/letsencrypt/live/rank.mightful-noobs.de/chain.pem;

	# index.php
	index index.php;

	# index.php fallback
	location / {
		try_files $uri $uri/ /index.php?$query_string;
	}

	# handle .php
	location ~ \.php$ {
		include nginxconfig.io/php_fastcgi.conf;
	}

	include nginxconfig.io/general.conf;
}

# subdomains redirect
server {
	listen 443 ssl http2;
	listen [::]:443 ssl http2;

	server_name *.rank.mightful-noobs.de;

	# SSL
	ssl_certificate /etc/letsencrypt/live/rank.mightful-noobs.de/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/rank.mightful-noobs.de/privkey.pem;
	ssl_trusted_certificate /etc/letsencrypt/live/rank.mightful-noobs.de/chain.pem;

	return 301 https://rank.mightful-noobs.de$request_uri;
}

# HTTP redirect
server {
	listen 80;
	listen [::]:80;

	server_name .rank.mightful-noobs.de;

	include nginxconfig.io/letsencrypt.conf;

	location / {
		return 301 https://rank.mightful-noobs.de$request_uri;
	}
}
```
php_fastcgi.conf:
```
# 404
try_files $fastcgi_script_name =404;

# default fastcgi_params
include fastcgi_params;

# fastcgi settings
fastcgi_pass			unix:/var/run/php/php7.3-fpm.sock;
fastcgi_index			index.php;
fastcgi_buffers			8 16k;
fastcgi_buffer_size		32k;

# fastcgi params
fastcgi_param DOCUMENT_ROOT		$realpath_root;
fastcgi_param SCRIPT_FILENAME	$realpath_root$fastcgi_script_name;
fastcgi_param PHP_ADMIN_VALUE	"open_basedir=$base/:/usr/lib/php/:/tmp/";
```

**Comment by xopez** [comment]
Ok, vergiss das da oben. Der FF cache wollte es nicht darstellen.
Jetzt bekomme ich auch im webinterface 
```
!!!! Logs folder is not writable !!!!
Cancel restart request!
```

**Comment by xopez** [comment]
So,

ich habe nicht dran gedacht, das sich ja der Logpfad auch geändert hat und es ja in der DB steht.
Sorry für die Umstände.
Ich schließe den issue dann mal

**Comment by Newcomer1989** [comment]
Welcher Pfad steht denn im Webinterface?

Ist denn dort auch das Verzeichnis hinterlegt, welches du hier zeigst?

**Comment by xopez** [comment]
Wie gesagt, ich stand noch ein andere drin. Da ich aber von Plesk/Apache weg bin zu reinem Linux, habe ich meine Verzeichnisstruktur angepasst. Deswegen hat der Pfad in der DB nicht mehr gestimmt.
der jetztige Pfad ist dieser:
`/var/www/html/rank.mightful-noobs.de/logs`
vor wars das hier:
`/var/www/vhosts/mightful-noobs.de/rank.mightful-noobs.de/logs`

**Comment by Newcomer1989** [comment]
Oh, sorry.. hatte die Nachricht nicht gesehen. Hatte den Tab noch im Browser offen gehabt. Normalerweise lädt GitHub die Nachrichten automatisch nach; hier wohl scheinbar nicht.

Ok, dann hat es sich aber erledigt / geklärt. :)
