### ISSUE TITLE
Merge users

### ISSUE THREAD

**Issue by theonlychristian** [Newcomer1989/TSN-Ranksystem#595]
Hi,
How can I merge users without destroying the database and let the ranksystem raise their then new ranks correctly?

example from mariadb table 'user':
MariaDB [ts3_ranksystem]> select * from user where name = "FRANK";
```
+------------------------------+--------+---------+-------+------------+-------+--------+-------+----------+-----------+------+----------+------------+-----+
| uuid                         | cldbid | count   | name  | lastseen   | grpid | nextup | idle  | cldgroup | boosttime | rank | platform | grpsince   | cid |
+------------------------------+--------+---------+-------+------------+-------+--------+-------+----------+-----------+------+----------+------------+-----+
| 0WbEm73k/pk7nNgkMrnBxkGBQ+Y= |     11 |   40360 | FRANK | 1541282432 |    18 |   4134 |  6318 | 18       |         0 |   22 | Windows  | 1540063185 |  23 |
| jU2TOD3XB5KdlCskBnP4vXgk7W8= |     25 | 1873260 | FRANK | 1553544600 |    33 | 130513 | 49690 | 33       |         0 |    4 | Windows  | 1550351209 |   2 |
+------------------------------+--------+---------+-------+------------+-------+--------+-------+----------+-----------+------+----------+------------+-----+
```

Simply adding Time to COL 'count' wont do anything, right?

**Comment by Shad86** [comment]
You also can add time to a specific user over the webinterface under the administration tab

(Not recommended/not supported if issues are coming up then) If you do it over the database directly pls be sure the rank system is stopped

**Comment by theonlychristian** [comment]
Okay, Now this works - Have now stopped - edited - and started the bot.
How can I now "hide" users, which I think are obsolete?

**Comment by Shad86** [comment]
I don’t know if you’re using the clean clients feature - if so as soon as
your deleting the user who is obsolete out of your TeamSpeak database he
will be delete out of the ranksystem database automatically after 24h
(standard setting)
theonlychristian <notifications@github.com> schrieb am Di. 26. März 2019 um
12:49:

**Comment by Newcomer1989** [comment]
The answer helped? Can we close this issue?

**Comment by theonlychristian** [comment]
Hi.

Nice service btw! Yes – ticket can be closed.

Regards

A happy user

Von: Newcomer1989 <notifications@github.com>
Gesendet: Freitag, 29. März 2019 20:14
An: Newcomer1989/TSN-Ranksystem <TSN-Ranksystem@noreply.github.com>
Cc: theonlychristian <christian.schimmel@hotmail.com>; Author <author@noreply.github.com>
Betreff: Re: [Newcomer1989/TSN-Ranksystem] Merge users (#595)


The answer helped? Can we close this issue?
