### ISSUE TITLE
Error on Admin Addtime page

### ISSUE THREAD

**Issue by Forge-Media** [Newcomer1989/TSN-Ranksystem#596]
Hi, noticed today that I cannot access the Admin Addtime page, I simply get the following errors:
([Image Link](https://i.imgur.com/D6FoK46.png))

```
Warning: ini_set(): Headers already sent. You cannot change the session module's ini settings at this time in /srv/users/serverpilot/apps/forgedashboard/public/webinterface/admin_addtime.php on line 2

Warning: ini_set(): Headers already sent. You cannot change the session module's ini settings at this time in /srv/users/serverpilot/apps/forgedashboard/public/webinterface/admin_addtime.php on line 3

Warning: ini_set(): Headers already sent. You cannot change the session module's ini settings at this time in /srv/users/serverpilot/apps/forgedashboard/public/webinterface/admin_addtime.php on line 8

Warning: session_start(): Cannot start session when headers already sent in /srv/users/serverpilot/apps/forgedashboard/public/webinterface/admin_addtime.php on line 13

Warning: Cannot modify header information - headers already sent by (output started at /srv/users/serverpilot/apps/forgedashboard/public/webinterface/admin_addtime.php:1) in /srv/users/serverpilot/apps/forgedashboard/public/webinterface/admin_addtime.php on line 42
```

However, the Remove online Time from User page works correctly, the only page producing this error is **admin_addtime.php**

### PHP Environment:

I'm using php 7.2.8 (can't use php 7.3 as there appears to be no [PHP SSH2 Extension for it currently](https://serverpilot.io/docs/how-to-install-the-php-ssh2-extension)).

```
Registered PHP Streams | https, ftps, compress.zlib, compress.bzip2, php, file, glob, data, http, ftp, zip, phar, ssh2.shell, ssh2.exec, ssh2.tunnel, ssh2.scp, ssh2.sftp

cURL support | enabled
```

Otherwise TSN Bot is working correctly, just this page which gives error!

### Extra: 

Possibly an issue with PHP7.2 ([based on what I'm reading here](https://phabricator.wikimedia.org/T197030)). Pretty sure this only happened when I switched to PHP7.2 from 5.5

The error also appears regardless if you are logged into the **Webinterface** or not, accessing the page on incognito mode, or once logged out still generates the above error: [LINK](https://dashboard.forgegaming.net/webinterface/admin_addtime.php)

**Comment by Newcomer1989** [comment]
Very interesting. The header / session handling is exactly the same on admin_addtime and admin_remtime.

Could be really a problem with the session handling in PHP 7.2. But really have no idea, why it appears on that page and not on others..
Do you want to try to upgrade to the higher PHP version?
The error with PHP SSH2 should be easy to solve. You only need to install the package. On linux:
`apt-get install php7.3-ssh2`

You can define, which PHP should be used, inside the file `other/phpcommand.php`

**Comment by Newcomer1989** [comment]
Cause you didn't response our message, we close this issue. When you still need help, feel free to reopen it.

**Comment by Forge-Media** [comment]
Hi, apologies for not replying sooner.

**Regarding the above command `apt-get install php7.3-ssh2` this returns the following error:**
```
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package php7.3-ssh2
E: Couldn't find any package by glob 'php7.3-ssh2'
E: Couldn't find any package by regex 'php7.3-ssh2'
```

Using the command `sudo apt-get install php-ssh2` returns the following: 
```
Reading package lists... Done
Building dependency tree
Reading state information... Done
php-ssh2 is already the newest version (0.12-39-g3dfe336+0.12-1build1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

I use [Serverpilot](https://serverpilot.io/) on my Ubuntu server to manage php websites and according to the following page: https://serverpilot.io/docs/how-to-install-the-php-ssh2-extension
There is no supported ssh2 dll for PHP7.3, confirmed on the PECL site: https://pecl.php.net/package/ssh2/1.1.2/windows. **Unless this is outdated.**

Whilst the above does cause problems for the TSN worker to connect using ssh, if I set the app to use php v7.3 (no ssh2). The above error when accessing the _Admin Addtime page_ is still present on php v7.3 and php v7.2, even when setting TS3 Query encryption off and using telnet again.

Thus it appears for me that the original post error:

```
Warning: ini_set(): Headers already sent. You cannot change the session module's ini settings at this time in /srv/users/serverpilot/apps/forgedashboard/public/webinterface/admin_addtime.php on line 2

Warning: ini_set(): Headers already sent. You cannot change the session module's ini settings at this time in /srv/users/serverpilot/apps/forgedashboard/public/webinterface/admin_addtime.php on line 3

Warning: ini_set(): Headers already sent. You cannot change the session module's ini settings at this time in /srv/users/serverpilot/apps/forgedashboard/public/webinterface/admin_addtime.php on line 8

Warning: session_start(): Cannot start session when headers already sent in /srv/users/serverpilot/apps/forgedashboard/public/webinterface/admin_addtime.php on line 13

Warning: Cannot modify header information - headers already sent by (output started at /srv/users/serverpilot/apps/forgedashboard/public/webinterface/admin_addtime.php:1) in /srv/users/serverpilot/apps/forgedashboard/public/webinterface/admin_addtime.php on line 42
```
Still happens on php7.2 or 7.3.

If I set my TSN Dashboard to use PHP v7.0 I can now access the _Admin Addtime page_, however, I still see this error below the navigation bar: [Here is an image showing the error text](https://i.imgur.com/DNLBTVP.png).

```
cannot_start(): Cannot send session cache limiter - headers already sent (output started at /srv/users/serverpilot/apps/forgedashboard/public/webinterface/admin_addtime.php:1) in /srv/users/serverpilot/apps/forgedashboard/public/webinterface/admin_addtime.php on line 13
```

**Comment by Newcomer1989** [comment]
Ok, I checked it again. It could be a problem with the encoding of the admin_addtime.php, since it is in UTF-8 BOM.
With the next release I will remove the BOM, so it is then only in UTF-8.

**Comment by Forge-Media** [comment]
Hi, I opened admin_addtime.php in vscode and re-saved it with plain UTF-8 encoding and the problem has gone away. So it would appear that this was the issue all along.

Thanks for the help!
