### ISSUE TITLE
Vielen Dank

### ISSUE THREAD

**Issue by MeXtreaM** [Newcomer1989/TSN-Ranksystem#597]
Danke an das Team. 
Nachdem ich bei all-inkl.com eine Subdomain angelegt hatte, stellte ich letzendlich fest das das Scipt leider nicht ordentlich (dauerhaft) ausgeführt wird. Der Bot machte für einige Minuten seine Arbeit und verlor dann immer wieder die Verbindung zum TS Server. 
Laut Support von all-inkl hat das was mit php_value max_execution_time zu tun. Naja, die technische Umgebung lässt es halt nicht zu. Habe dann eine Anfrage bei TSN gestellt, wegen hosting und schwups keine 12 Stunden später erhielt ich eine Mail mit allen nötigen Angaben. Der Bot ist nun dauerhaft auf unserem TS Server und macht das was er soll.
Hätte ich mir viele Stunden Fehlersuche sparen können......
Meine Wertschätzung ließ mich auf den Spendenbutton klicken (sollte für ein, zwei Runden Bier reichen...^^). Macht weiter so. Bin sehr gespannt wie die Weiterentwicklung aussieht.

MfG
MeXtreaM

https://ts-ranksystem.com/hosted/107/stats/index.php

**Comment by Newcomer1989** [comment]
Vielen Dank für die netten Worte. Schön hier auch mal eine positive Rückmeldung zu sehen. In den meisten Fällen erhalten wir nur Issues, wenn etwas nicht wie gewünscht funktioniert oder Fragen bestehen.

Natürlich auch vielen Dank für die Spende! Wir werden nicht alles auf einmal versaufen, versprochen ;-)

**Comment by xopez** [comment]
Finde, ist der falsche Ort für Rückmeldungen :D
Aber wenn wir schonmal dabei sind.
Danke auch dafür ;)
