### ISSUE TITLE
Hide it query port in log

### ISSUE THREAD

**Issue by htm1994** [Newcomer1989/TSN-Ranksystem#598]
Hi
I want hide query port in log.
plz help for hid query port.
thank you

**Comment by Newcomer1989** [comment]
It is not advisable to reduce the content of the log.

You should instead hide the full log from public, when you think there are sensitive information inside!

You have two options:
1) Relocate the logfile to a private area and config it for the Ranksystem -> Webinterface -> Other -> Logpath
2) Exclude .log files from your web server.

**Comment by htm1994** [comment]
Thank you.
Can I connect to the server without a query and username and password and work properly?
Do you create such a feature?

**Comment by Shad86** [comment]
Thats not possible as the bot needs for some actions administrative rights.
