### ISSUE TITLE
Webinterface - Passwort ändern schlägt fehl

### ISSUE THREAD

**Issue by xopez** [Newcomer1989/TSN-Ranksystem#599]
Hallo,

wie der Titel bereits sagt, versuchte ich grade mein Webinterface Passwort zu ändern.
Jedoch misslingt das:
![grafik](https://user-images.githubusercontent.com/28950736/55742194-666ea200-5a2f-11e9-931e-a110d7a61643.png)

**Comment by Newcomer1989** [comment]
Stimmt, hat sich mit der Version 1.2.12 eingeschlichen beim Ändern der Config.

Wird mit der nächsten Version 1.3.0 gefixt.

**Comment by xopez** [comment]
Funktioniert und ich schließe es.
