### ISSUE TITLE
Log spam with the new 1.00 version

### ISSUE THREAD

**Issue by Sqveeze** [Newcomer1989/TSN-Ranksystem#6]
Hello,

I just upgraded to the new 1.00 version, and now every icon on the new "top list" is a cracked image not found icon, (you know what i mean). And the teamspeak has this in the log:

file download from (id:0), '/icon_1396826995' by client 'rank'(id:1)
file download from (id:0), '/icon_1396826995' by client 'rank'(id:1)
file download from (id:0), '/icon_1396826995' by client 'rank'(id:1)
file download from (id:0), '/icon_1396826995' by client 'rank'(id:1)
file download from (id:0), '/icon_1396826995' by client 'rank'(id:1)
file download from (id:0), '/icon_1396826995' by client 'rank'(id:1)
file download from (id:0), '/icon_1396826995' by client 'rank'(id:1)
file download from (id:0), '/icon_1396826995' by client 'rank'(id:1)
file download from (id:0), '/icon_1396826995' by client 'rank'(id:1)
file download from (id:0), '/icon_1396826995' by client 'rank'(id:1)
file download from (id:0), '/icon_1396826995' by client 'rank'(id:1)
file download from (id:0), '/icon_1396826995' by client 'rank'(id:1)
file download from (id:0), '/icon_1396826995' by client 'rank'(id:1)

**Comment by Spazmic** [comment]
I have the same issue.

**Comment by Newcomer1989** [comment]
Its noted. I will try to fix it with the next version.

**Comment by Sqveeze** [comment]
By the way, the requested icon that the bot tries to download, its always the server icon! I tried to change it, that's why i know!

**Comment by Newcomer1989** [comment]
Yes I know, but thx for information. All other icons will be checked and only downloaded, if its got changed.

**Comment by Newcomer1989** [comment]
log spam should be emended with release 1.01
(enable the update check inside the webinterface to get notified when it gets published)
I can't follow the problem with cracked images.. Please open for this a new issue, if its still a problem
