### ISSUE TITLE
Error 0: Name or service not known

### ISSUE THREAD

**Issue by kreidlerflorett** [Newcomer1989/TSN-Ranksystem#60]
Hello,

I have installed the latest version 1.0.2 on my vServer.
I have followed every step on your installation guide on your hompage.
I use Debian 8, Apache2, PHP5, MySQL und phpMyAdmin.

I could see the webinterface etc but when I try to start the bot (via webinterface and worker.php) comes the same error: 

My ranksystem.log 
```
INFO      Initialize Bot...
INFO      Check Ranksystem database for updates.
INFO      No newer version detected; Database check finished.
INFO      Ranksystem Version: 1.0.2
INFO      Connect to TS3 Server (Address: "ts.therenegade.de" Voice-Port: "9541" Query-Port: "10011").
ERROR  Error 0: php_network_getaddresses: getaddrinfo failed: Name or service not known
```
The files are owned by www-data and the premission of logs, others/dbconfig.php, avatars and icons are by 777.

I have also reinstalled all and i become the same error again.

**Comment by Shad86** [comment]
maybe you could try it with a clear ip format for example 11.11.11.11.

usually "Name or service not known" means that this service isnt known or not reachable

regards

**Comment by Newcomer1989** [comment]
Please check your local network configs. This isn't a problem with the Ranksystem especially.

For example check this:
http://albertech.net/2011/05/fix-php_network_getaddresses-getaddrinfo-failed-name-or-service-not-known/
