### ISSUE TITLE
[Feature] DSGVO Datenexport

### ISSUE THREAD

**Issue by xopez** [Newcomer1989/TSN-Ranksystem#600]
Hallo,

ich möchte ein neues Feature ansetzen, da ich aber dafür vermutlich viel länger brauchen werde als ihr, öffne ich es mal als Issue. Vielleicht geht das noch für 1.3.0.

Der User sowie im Webinterface soll es möglich sein die Daten zu exportieren eines Users in JSON-Format am besten. Auf der Stats-Seite soll der User es selbst für sich können mittels des autologins via IP. Vielleicht bei seinen eigenen Stats.

Auf dem Webinterface soll es ein Dropdown aller User geben mit Suchmöglichkeit. So wie bei user_addtime zum Beispiel. Ich weiß nicht wieviel aufwand das ist.

Hintergrund. Habe einen User der seine Daten will und das ist die einzige Möglichkeit wo welche sein können.

Löschen können muss nicht der Fall sein, da langt ein Löschen auf seiten TS und ein Anstoßen des Löschenvorgangs über den Bot. Müsste ja gehen meine ich.

**Comment by Newcomer1989** [comment]
Du kannst die IP Adresse im Ranksystem hashen lassen, damit sind die Daten annonymisiert und nicht mehr auf eine gezielte Person rückschließbar.
Ob die unique Client ID als zuordenbares Kriterium zu einer Person zählt, wie eine IP Adresse oder nicht, dürfte strittig sein. Meiner Meinung nach, ist hierüber direkt keine Adresse einer Person ableitbar. Sprich die unique Client Id ist annonym.

Somit wäre das Ranksytem in diesem Modi nicht das Problem. Sprich die Auskunft aus Sicht RS ergibt, es können keine zugehörigen Daten ermittelt werden bzw. es liegen keine vor.

In jedem Fall wird die IP immer nur temporär gespeichert.

Problematischer dürfte hier der TS Server sein, welcher die IP im Klartext und über den Disconnect hinaus speichert. Dafür ist dann aber TeamSpeak verantwortlich 😉

**Comment by xopez** [comment]
Das habe ich sowieso aktiviert. Danke für die Info. Ich dachte halt das die UID mit unter diesen Daten fällt, deshalb die Frage.

Vielleicht wird das ja was mjt TS5 wenn das mal kommt

**Comment by Newcomer1989** [comment]
Mit der UID selbst kannst du ja nix anfangen. Erst über die IP Adresse kann diese einem konkreten Anschluss und damit einer konkreten Person zugeordnet werden.

TS5 wird daran vermutlich nichts ändern. Denn erstens müsste es überhaupt erst mal release fertig werden und zweitens werden keine grundlegenden Dinge zwischen Server und Client geändert. Es soll ja weiterhin ein TS3 Server bleiben, welcher dann auch noch mit einem TS3 Client kompatibel bleibt.

**Comment by xopez** [comment]
Das stimmt soweit. Und habe keine Einwände mehr.
Das mit TS5 ist mir bewusst. Dachte, da ja Serverseitig was im Hintergrund geändert wird.
Aber belassen wir es dabei, würde ich vorschlagen.

Danke nochmals :)
Ich schließ den Issue mal.
