### ISSUE TITLE
ip Ban

### ISSUE THREAD

**Issue by htm1994** [Newcomer1989/TSN-Ranksystem#601]
HI
Some people inside the teamspeak server are automatically Ban IP(flood).
I feel like auto rank bot.
How to fix the problem?
thank you

**Comment by Shad86** [comment]
As you use a query connection you need to whitelist the ip where the ranksystem is hosted. Just write, in a new line the ip (example -> 123.45.67.890) into the query_ip_whitelist.txt which you can find in the Ts3-Server folder.

**Comment by htm1994** [comment]
Yes I added the ip ranksystem in query_ip_whitelist.txt
But my problem is that the clients are getting banned and I can not list them on this list.

**Comment by Newcomer1989** [comment]
The problem you described isn't a problem with the Ranksystem, cause the Ranksystem doesn't ban user.

You need to change your anti-flood options and / or TeamSpeak permissions. But this isn't the right place to get support for TeamSpeak. Try it with the official TeamSpeak forum -> https://forum.teamspeak.com
