### ISSUE TITLE
Critical TS3 error on core function! Shutting down!

### ISSUE THREAD

**Issue by DragonHacker1** [Newcomer1989/TSN-Ranksystem#602]
Hello, since got installed this, is on docker container (myseft), databases are separated, i verified too many times to see if they cause by myseft. The problem is after an uncertain time like, one hour or more they automatically shutdown (i don't know why, but i did setup crontab) I verified databases are 100% corrected also i allowed pretty much all connections (for temporar time to see if this affect) The logs don't tell me too much.. i like to tog a loglevel a bit higher to see if the problem relevant by my site, but i got one (older) worked pretty well.
Here go logs : 
https://pastebin.com/apvc66BJ
https://pastebin.com/Defih1Dv
(they are like a bit of informations, but if required more, please can be specified, i will sent all informations possible)
Thank you for reading.
Additionally info:
Using PHP Version: 7.2.17-1+0~20190410151005.18+stretch~1.gbp23a36d
Database Version: 5.5.5-10.3.13-MariaDB-1:10.3.13+maria~bionic-log
Running on OS: Linux 4.9.0-8-amd64
TSN RANKSYSTEM v 1.2.12, i rechecked if have all things required.
All things are on same network, i don't know what problem, but only server are external, so databases, this system are on same network.

A temporary solution was restarting continous like 15 minutes, check button work somehow, but sometimes the rank STUCK without error like freezing.

**Comment by Newcomer1989** [comment]
> 2019-04-11 23:56:39.544727   ERROR     TS3 Error: 0: connection to server 'TEAMSPEAK' lost

This is in most cases a ban. You should whitelist the IP address of your host of the Ranksystem
to the query_ip_whitelist.txt, which you'll find inside the TS3 server installation directory.

**Comment by Newcomer1989** [comment]
Cause you do not response our message, we close this issue. When you still need help, feel free to reopen it.
