### ISSUE TITLE
Czech language - font

### ISSUE THREAD

**Issue by Ondra3211** [Newcomer1989/TSN-Ranksystem#604]
When I set Czech language on my site the font is italic. I want normal font like english language.

**Comment by Newcomer1989** [comment]
Yeah, this is an error inside the language file. It will be fixed with the next release.

**Comment by Ondra3211** [comment]
When will be new release?

**Comment by Shad86** [comment]
As soon as everything's done (no eta)

**Comment by Newcomer1989** [comment]
Is fixed with 1.3.0
