### ISSUE TITLE
TS icons

### ISSUE THREAD

**Issue by Ondra3211** [Newcomer1989/TSN-Ranksystem#605]
Hi, I deleted all icons in `tsicons`. I think they are cached but new icons not generating. I tried restart the bot but nothing.

**Comment by Newcomer1989** [comment]
We will be add a new bot command with the version 1.3.0 to re-download the icons.

https://ts-ranksystem.com/#commands

!reloadgroups

**Comment by Newcomer1989** [comment]
1.3.0 is out now
