### ISSUE TITLE
Abhängige Gruppe um den Groupassigner zu nutzen

### ISSUE THREAD

**Issue by xRaid96** [Newcomer1989/TSN-Ranksystem#606]
Es wäre cool, wenn es die Möglichkeit gäbe eine oder mehrere Gruppen als Voraussetzung für den Groupassigner zu setzen. Sprich ich brauche Gruppe X um mir weitere Gruppen geben zu können. Hat den Hintergrund: Bei uns sollen sich Gäste keine Gruppen geben können, Mitglieder schon.

**Comment by Newcomer1989** [comment]
Im nächsten Schritt wird mit dem Addon erst einmal die [multiple Vergabe](https://github.com/Newcomer1989/TSN-Ranksystem/issues/560#issuecomment-435128360) von Gruppen kommen.

Voraussetzungen bzw. Exception kommen dann wenn erst in einem weiteren Schritt.
Ob es überhaupt sinnig ist, müssen wir dann noch überdenken, da es nur ein Addon ist und das Ranksystem nicht zum Group Assigner werden soll.

Ich nehme es aber zunächst einmal auf die Feature-Liste.

**Comment by Shad86** [comment]
Wir haben nun "Servergruppen - Ausnahmen" hinzugefügt.

Vielleicht wird es in Zukunft auch eine Whitelist geben aber für den Moment sollte es zumindest davor schützen, dass Nutzer nicht ohne Berechtigung das Ganze nutzen können.
