### ISSUE TITLE
!nextup not working

### ISSUE THREAD

**Issue by Zeemaister** [Newcomer1989/TSN-Ranksystem#608]
"!nextup" command not working.

**Comment by Shad86** [comment]
Which Version do you use? For me it definitely works on Version 1.2.12.

**Comment by Zeemaister** [comment]
1.2.12

**Comment by Shad86** [comment]
Send logs and/or check your configs, that you're not in an excepted Group (under Core in the Webinterface)

**Comment by Newcomer1989** [comment]
Please check also this TeamSpeak permission

i_client_private_textmessage_power

**Comment by Zeemaister** [comment]
What group the bot get? On the mobile TeamSpeak the !nextup command is working when I join to the Token room but not on the PC.

**Comment by Newcomer1989** [comment]
>What group the bot get?

That group, you gave the bot. We can't answer that to you xD


> On the mobile TeamSpeak the !nextup command is working when I join to the Token room but not on the PC.

That could be a problem with the unique ID, you gave the Bot.
You tried, the !nextup command isn't working for you only? Are other people on your server able to use this command?

**Comment by Zeemaister** [comment]
I tried on the PC with new Identity and its working. So what is this problem with unique ID?

**Comment by Newcomer1989** [comment]
You need to create an own identity only for the Query-Bot.
When multiple user are online with the same identity, it could brings problems to send messages to the correct recipient.
