### ISSUE TITLE
Bot crashes after 10 seconds

### ISSUE THREAD

**Issue by Kenionek** [Newcomer1989/TSN-Ranksystem#609]
Hello

Sinds a week the bot crashes every time after like 10 seconds

here is the log: https://pastebin.com/HuNshKs3

btw: sorry for my bad English :/

**Comment by Newcomer1989** [comment]
> MySQL server has gone away

It is a problem with your database.

Have a look the database is online, reachable and scripts are able/allowed to hold a connection!
Perhaps you may need to increase the [connection limit](https://stackoverflow.com/questions/22297773/how-to-increase-mysql-connectionsmax-connections).

**Comment by Kenionek** [comment]
> > MySQL server has gone away
> 
> It is a problem with your database.
> 
> Have a look the database is online, reachable and scripts are able/allowed to hold a connection!
> Perhaps you may need to increase the [connection limit](https://stackoverflow.com/questions/22297773/how-to-increase-mysql-connectionsmax-connections).

thank you for the answer.
I changed the max connections and max allowed packet and it is working for now, I hope it will work now like before without crashing
