### ISSUE TITLE
Server Statistik - Kreisdiagramm zeigt falsche Daten

### ISSUE THREAD

**Issue by xopez** [Newcomer1989/TSN-Ranksystem#610]
Hallo,

mir ist grade aufgefallen, dass eines der Kreisdiagramm von den Plattformen falsche Daten anzeigt. Ich habe keine Ahnung ob das auch die anderen betrifft.
Da es nur rein optisch auf dem Dashboard ist, ist kann das ruhig auch mit nächstem release behoben werden,
![grafik](https://user-images.githubusercontent.com/28950736/57556099-60454b80-7376-11e9-84c8-629554e32e35.png)
Anzeige:
178 Windows
1 Linux
3 Android
0 iOs
3 OSX

Jedoch auf der platforms.php, was stimmt.
1 | Windows | 178 | 96.2 %
2 | Linux | 3 | 1.6 %
3 | OSX | 3 | 1.6 %
4 | iOS | 1 | 0.5 %
![grafik](https://user-images.githubusercontent.com/28950736/57556242-c336e280-7376-11e9-8d3e-f78b6af2baeb.png)

Kann gerne hier nachgeprüft werden: https://rank.mightful-noobs.de/stats/index.php

**Comment by Newcomer1989** [comment]
Sollte hoffentlich mit der Version 1.3.0 nun endgültig bereinigt sein. Gerne mal schauen und ein Feedback geben.
Vorerst schließe ich den Issue mal.

**Comment by xopez** [comment]
Grade aktualisiert.
Schaut gut aus :)
