### ISSUE TITLE
Bot Stopped Working

### ISSUE THREAD

**Issue by raphlexz** [Newcomer1989/TSN-Ranksystem#619]
Hi!

I have several problems. First of all, we are 3 in my TeamSpeak server, where the Rank System is needed to run. I start it, it gives the first rank, but only for me, then the Bot stopped working sing appears in the Webinterface. I start it again, it don't give any error, but instantly stop working, and no one else get a rank.

[ranksystem.log](https://github.com/Newcomer1989/TSN-Ranksystem/files/3277113/ranksystem.log)
![ranksystem](https://user-images.githubusercontent.com/51711919/59282748-b3f2cf80-8c69-11e9-97b9-93515684da90.png)

I have the latest version. Thanks the help!

**Comment by Newcomer1989** [comment]
Did you matter about this message?

> It seems to be, you are running multiple PHP versions on your system.
> 
> Your webserver (this site) is running with version: 5.6.40
> The defined command in "other/phpcommand.php" is running with version: 7.0.33

You should see it, when you try to login into the webinterface.
Please correct this and try it again.

**Comment by Newcomer1989** [comment]
> I start it again, it don't give any error, but instantly stop working

Where is you location of the logfile?
You set it about the Webinterface -> Other -> Logpath

For this directory you need permissions to write files.

When you start the Ranksystem. Appears there a file named "pid"? If not, there is any permission issue.

**Comment by Newcomer1989** [comment]
As we didn't get any feedback, we close this issue.

Please feel free to reopen it, when you still have problems.
