### ISSUE TITLE
Reset-Function

### ISSUE THREAD

**Issue by Shad86** [Newcomer1989/TSN-Ranksystem#621]
**New Feature**

Reset-Function 

***1) What should this feature do?***

The following possibilities should be given:

Resetting the whole rank system (start from 0)

Resetting the users but not the server statistics

If possible, a kind of backup function, before you reset, in case you are so stupid (I'm not excluded) and clicked on the wrong reset button

***2) Where should it be located?***
_On which existing part of the Ranksystem you would add this new feature?_

A good place would be "Administrate" 

***3) What would be the benefit?***
_Please only report this feature, when you think also other people would have a benefit of it._

Well, we all know it we played around, with the adding time / removeing time and fucked up the Whole thing ooor we made some mistakes with the rankupdefintion, so we want to reset the whole thing.

At the moment it costs a lot of time, as we have to reinstall the whole thing, this function would make it a way easier for all.

**Comment by Newcomer1989** [comment]
done with 1.3.1
