### ISSUE TITLE
Datenbank Fehler

### ISSUE THREAD

**Issue by Robert08020** [Newcomer1989/TSN-Ranksystem#622]
**Rank System Version:**
1.3.0

Hallo, habe heute auf meinem VServer das Rank System installiert. Ging auch alles problemlos, habe dem Ordner rank die Rechte 777 gegeben, sowie allen Unterordnern. Beim Einrichten kam dann das Problem, als ich unter Kern den Verifizierungschannel eingegeben habe und gespeichert habe, das folgende Fehlermeldung kam: Deine Änderungen konnten nicht gespeichert werden aufgrund eines Datenbank-Fehlers. Bitte behebe das Problem und versuche es erneut!

Die Daten der Datenbank sind alle korrekt
**Rank System log**
https://pastebin.com/3tQCMMNA

**Comment by Newcomer1989** [comment]
Bitte prüfen im Kern primär die Felder Servergruppen-Ausnahmen, Rangsteigerung Definition und Boost auf falsche Servergruppen-IDs.

Sobald das Ranksystem einmal gestartet wurde, speichert der Bot die Gruppen des TS und prüft diese bei Eingaben gegen.
Wenn IDs in der config verwendet werden, welche nicht auf dem TS existieren, wird die config abgewiesen.

Falls das nicht helfen sollte, bitte einen Screenshot von der vollständigen Seite machen inkl. der Fehlermeldung.

**Comment by Newcomer1989** [comment]
Da wir keine weitere Rückmeldung erhalten haben, gehen wir davon aus, dass obige Tipps geholfen haben. Aufgrunddessen schließen wir den Issue.

Sollte das Problem weiterhin bestehen, gerne den Issue wieder öffnen.
