### ISSUE TITLE
PHP Fatal error: DateTime::__construct()

### ISSUE THREAD

**Issue by xopez** [Newcomer1989/TSN-Ranksystem#623]
**Ranksystem Version:**
1.3.0

**Beschreibung:**
**1) Was hast du getan?**
`/stats/my_stats.php` aufgerufen

**2) Was war deine Erwartung?**
Die Seite sollte ohne Probleme geladen werden
**3) Was ist stattdessen passiert?**
PHP Fatal Error:
https://pastebin.com/2PWL1NXG

**Ranksystem Log**
Unabhängig von dem Fehler.

EDIT:
Das passiert nicht immer.

**Comment by Newcomer1989** [comment]
1) Welche Einstellung hast du denn im Webinterface -> Other -> hash IP addresses gewählt?

2) Ist der betroffene User auf der Homepage mit der gleichen IP, wie auf dem TS online?

3) Gibt es weitere User auf dem TS, die mit dieser IP online sind?

4) Gibt es weitere User auf dem TS, die mit der gleichen unique Client ID online sind?

5) Bitte teile uns einen Screenshot von der List Rankup des betroffenen Users. Entscheidend ist, dass wir die online Zeit als auch die Idle Zeit darauf erkennen.

**Comment by xopez** [comment]
Es tritt nur auf, wenn ich, die von mir definierte Gruppe für den Boost habe. Also wird es denke ich bei dieser Bedingung auch bei den anderen Userns auftreten.

1. Hash-IP ist auf sicheres Hashen gestellt.
2. Ja, der User ist der gleiche.

Ich denke, dass passiert wegen der Kommazahl beim Boosting die ich nun definiert habe
` 144=>1.25=>10800`

![grafik](https://user-images.githubusercontent.com/28950736/59375048-926b1400-8d4d-11e9-819a-4e0b6c45a7eb.png)

**Comment by Newcomer1989** [comment]
Daran kann es wirklich liegen.

Wenn du magst, kannst du mal versuchen in der /stats/my_stats.php nach Zeile 32 die beiden folgenden Zeilen einzufügen.

```
	$dbdata_fetched['count'] = round($dbdata_fetched['count']);
	$dbdata_fetched['idle'] = round($dbdata_fetched['idle']);
```

Gerne noch einmal Rückmeldung geben, ob es geholfen hat.

**Comment by xopez** [comment]
Hat geklappt 👍

**Comment by Newcomer1989** [comment]
fixed with 1.3.1
