### ISSUE TITLE
Statistik Fehler bei aktuelle Servergruppe

### ISSUE THREAD

**Issue by Robert08020** [Newcomer1989/TSN-Ranksystem#624]
**Ranksystem Version:**
1.3.0

Hallo, bei meiner Statistik in der Rang Liste stehen ja alle User, die bereits auf dem Server waren, die Online Zeit dazu und die Servergruppe. Bei den meisten stimmt das auch, nur nicht bei mir. Bei mir stimmt zwar die Online Zeit und die restlichen auch, allerdings darf bei Servergruppe nicht 1 Tag stehen, da ich erst nach 1 Tag auf dem Server diese Gruppe bekomme und wie Sie sehen, war ich erst 13 h drauf. Bei nächste Servergruppe "1 Tag", das stimmt alles, sogar wenn der nächste Rang kommt etc.

Wie kann ich diesen Fehler beheben? 

**Ranksystem Log**
https://pastebin.com/j2f0cFAn

(nicht wundern, kann etwas unübersichtlich sein, da ich den Bot mehrmals gestartet habe. Hoffentlich geht es trotzdem)

**Comment by Newcomer1989** [comment]
> Bei mir stimmt zwar die Online Zeit und die restlichen auch, allerdings darf bei Servergruppe nicht 1 Tag stehen, da ich erst nach 1 Tag auf dem Server diese Gruppe bekomme und wie Sie sehen, war ich erst 13 h drauf. Bei nächste Servergruppe "1 Tag", das stimmt alles, sogar wenn der nächste Rang kommt etc.

Sorry, aber das habe ich ehrlich gesagt nicht verstanden. Kannst du uns vielleicht noch einen Screenshot von der Seite schicken, auf der das Erwähnte ersichtlich wird?

**Comment by Robert08020** [comment]
Hallo, wie auf dem Bild zu sehen, bin ich in der Gruppe 1 Tag, obwohl ich diese erst noch bekomme, wie unter nächste Servergruppe zu sehen und nun ist meine Frage, wieso ist das so?

Ich habe es so auf dem Server eingestellt, das wenn ein User auf unserem Server jeweils 24 h darauf ist, bekommt er die Gruppen 1 Tag bis 7 Tage zugeteilt. Damit man sieht, wie viel Tage diese bereits auf dem Server ist.


![Screenshot_54](https://user-images.githubusercontent.com/51743742/59486081-79ab4d00-8e78-11e9-9a08-c96ea373f131.jpg)

Nun habe ich den Test gemacht und habe meine Zeit auf kurz unter 1 Tag gestellt. Also ich diesen dann aber erreicht habe, bekam ich weder eine Benachrichtigung das ich im Rang aufgestiegen bin, oder den Rang selbst.

Hier nochmal ein Auszug davon:

![Screenshot_55](https://user-images.githubusercontent.com/51743742/59488012-9fd3eb80-8e7e-11e9-9abc-0d91384c215f.jpg)

Bild vom Kern:

![Screenshot_56](https://user-images.githubusercontent.com/51743742/59488041-b9753300-8e7e-11e9-9320-5594627d0716.jpg)

**Comment by Robert08020** [comment]
Habe den Fehler gefunden,. der Rang wurde mir am Anfang mal gegeben, durchs testen und blieb da stehen, hab diesen nun in der Datenbank entfernt und nun gehts!

Trotzdem Vielen Dank für die Antwort!

**Comment by Newcomer1989** [comment]
Das ist mit dem Testen immer so eine Sache. Wenn mehrmals die an der Rangsteigerung geschraubt wird, kann es natürlich immer zu Konstellationen kommen, die das Ranksystem nicht erkennt.
Aus Perfomance-Gründen wollen wir nicht ständig alle User und alle Gruppen auf Korrektheit prüfen. Im Zweifel bereinigt sich so etwas dann, wenn der nächste reguläre Rankup ansteht.

Ansonsten gibt es in der aktuellen Beta-Version eine Reset-Funktionn, mit welcher man nach einem Test einen vollständigen Reset ausführen kann. Das dürfte in deiner Konstellation auch helfen, falls noch Bedarf besteht.
