### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by grezzeoo** [Newcomer1989/TSN-Ranksystem#625]
Wrong PHP command defined inside the file "other/phpcommand.php"! PHP not found here!
Please insert a valid PHP command inside this file!

Definition out of "other/phpcommand.php":
php

Result of your command:

You can test your command before via console by adding the parameter '-v'.
Example:
php -v
You should get back the PHP version!

**Comment by Newcomer1989** [comment]
Wrong PHP command defined inside the file "other/phpcommand.php"! PHP not found here!
**Please insert a valid PHP command inside this file!**

Definition out of "other/phpcommand.php":
php

Result of your command:

You can test your command before via console by adding the parameter '-v'.
Example:
php -v
You should get back the PHP version!
