### ISSUE TITLE
Wrong PHP command - Cant log in into Webinterface

### ISSUE THREAD

**Issue by Thilo12** [Newcomer1989/TSN-Ranksystem#626]
**Ranksystem Version:**
1.3.0

**Beschreibung:**
**1) Was hast du getan?**
nothing, the ranksystem updated itself and now i cant login anymore

**2) Was war deine Erwartung?**
-
**3) Was ist stattdessen passiert?**
cant login into webinterface anymore
![Unbenannt](https://user-images.githubusercontent.com/51885294/59566613-c3f02200-9062-11e9-901a-da2ead4e594e.png)

**Ranksystem Log**
_Poste einen Log vom letzten Start des Ranksystems._
_Den Log teilst du am besten z.B. mit https://pastebin.com/ (Das macht es übersichtlicher)._

**Comment by Newcomer1989** [comment]
Wie hast du denn das Ranksystem bisher gestartet bekommen? Über das Webinterface?
Oder über Shell und wenn mit welchem Command?

**Comment by Thilo12** [comment]
Worker läuft ohne probleme, ich kann mich nurnichtmehr einloggen übers webinterface und das erst nach dem update

**Comment by Thilo12** [comment]
C:\xampp\php\php.exe -f C:\xampp\htdocs\rank\worker.php check 

über den task manager

**Comment by Newcomer1989** [comment]
Joa, das ist so aber nicht vorgesehen.

Dann trage 'C:\xampp\php\php.exe' doch auch in der other/phpcommand.php ein, dann sollte alles funktionieren. Einschließlich dem Start & Stop über das Webinterface.

**Comment by Thilo12** [comment]
Unter welchem $phpcommand soll ich das verzeichniss eintragen?

`<?PHP
## Uncomment the command you need to run PHP
## This are only examples
## If you miss one, feel free to add it
## Only one command should be active at the same time!
$phpcommand = "php";
#$phpcommand = "php56";
#$phpcommand = "php70";
#$phpcommand = "/usr/bin/php5";
#$phpcommand = "/usr/bin/php";
#$phpcommand = "C:\PHP5\php.exe";
#$phpcommand = "C:\PHP7\php.exe";
#$phpcommand = "\"C:\Program Files (x86)\PHP\php.exe\"";  // on blanks you need special marks \"
#$phpcommand = "c:\wamp\bin\php\php.exe";
?>`

**Comment by Newcomer1989** [comment]
Es ist nur einer Aktiv im Standard:

Zeile 8:
`$phpcommand = 'php';`

Du könntest diesen auskommentieren, also auch ein `#` davor setzen.

Und dafür in Zeile 21 den `#` entfernen, das enspricht deiner Installation:
`$phpcommand = 'C:\xampp\php\php.exe';`

**Comment by Thilo12** [comment]
Ich hab um es uns zu erleichtern mal als link die screenshots hinzugefügt

nachdem ich versucht hab php auszukommentieren und in zeile 13 sowie 14 meinen pfad testweiße im wechsel angegeben habe kam diese fehlermeldung im webinterface... 

https://gyazo.com/db43e4550c54764f3668afad3d37ff1b

https://gyazo.com/589a4c14c16f3f1860931d03a4a7a90a

**Comment by Newcomer1989** [comment]
Du hast leider noch eine alte Vorlagen-Datei.

Bitte benutze an Stelle von den  normalen Gänsefüßchen `"` ein einfaches `'`.
Also wie bereits oben gepostet:
`$phpcommand = 'C:\xampp\php\php.exe';`

**Comment by Thilo12** [comment]
Ich hab jetzt alles auskommentiert und bevor <?php> endet `$phpcommand` = 'C:\xampp\php\php.exe';´
eingefügt 
jetzt kommt es zu dieser fehlermeldung...
$phpcommand = 'C:\xampp\php\php.exe';

**Comment by Shad86** [comment]
hast du mal überprüft ob der webuser in dem Ordner stimmt? und dieser in den Ordner schreiben kann?

**Comment by Shad86** [comment]
bitte schick auch nochmal einen screen von der phpcommand.php

**Comment by Newcomer1989** [comment]
Closed, da keine Rückmeldung mehr kam..
