### ISSUE TITLE
!clean problem 

### ISSUE THREAD

**Issue by Spooonky** [Newcomer1989/TSN-Ranksystem#627]
**Ranksystem Version: 1.3.0 -pre-1.3.1-1**

**Beschreibung:**
**1) Was hast du getan?**
Ich habe !clean in den Server Chat eingetragen.

**2) Was war deine Erwartung?**
Das der Befehl !clean ausgeführt wird

**3) Was ist stattdessen passiert?**
Habe vom Bot diese Nachricht erhalten:
<23:57:42> "SCL Ranksystem": Die Bereinigung der User-Datenbank wurde gestartet. Führe den Befehl !log aus, um mehr Informationen zu erhalten.
<23:57:42> "SCL Ranksystem": Du bist nicht berechtigt diesen Befehl abzusetzen!

**Ranksystem Log**
https://pastebin.com/03C42NCB

**Comment by Shad86** [comment]
Einzige beiden Ideen die ich auf die schnelle dazu habe:

Ausgeschlossen?
Admin ID nicht gesetzt?

**Comment by Spooonky** [comment]
Ich bin selber als Admin eingetragen. Die ID habe ich 2 mal ersetzt um sicher zu gehen. 
Ausgeschlossen bin ich auch nicht.

**Comment by Newcomer1989** [comment]
Thx, ist einfach ein Fehler im Check. Wird dann mit der Pre2 behoben.

**Comment by Newcomer1989** [comment]
fixed with 1.3.1
