### ISSUE TITLE
Top User Liste zeigt falsche Werte an

### ISSUE THREAD

**Issue by DerRene97** [Newcomer1989/TSN-Ranksystem#628]
**Ranksystem Version:**
1.3.0

**Beschreibung:**
**1) Was hast du getan?**
Ich rufe die Top User listen auf (Woche/Monat/aller Zeiten) und sehe das keine korrekten Online zeiten angezeigt werden.
Auf Platz 1 der aller Zeiten Liste wird mir ein User mit 48 Stunden angezeigt.
Gehe ich jedoch auf die Rank-Liste und Sortiere nach "ges. online Zeit" habe ich User mit über 30 Tagen Onlinezeit.
In den Kern Einstellungen habe ich den Modus "online Zeit" eingestellt.
**2) Was war deine Erwartung?**
Korrekt angezeigte Werte

Da in der Rank-Liste die richtigen Onlinezeiten angezeigt werden, sollte die Datenbank diese ja auch richtig erfassen. Jedoch scheinen die Top User listen diese nicht richtig aufzulisten.
Ich hoffe auf Tipps für eine Problemlösung

**Comment by Newcomer1989** [comment]
Das kann ich so an meinem System nicht nachvollziehen, nutze allerdings auch den Modus aktive Zeit.

Hier gerne zum Vergleich:
https://ts-n.net/ranksystem_dev/stats/list_rankup.php?sort=rank&order=asc&seite=1&user=25&search=
https://ts-n.net/ranksystem_dev/stats/top_all.php

Magst du uns denn mal einen Link zu deinem Ranksystem teilen, damit wir uns das näher ansehen können?!

**Comment by DerRene97** [comment]
Klar, hier die Links:
http://egc-clan.de/ts/stats/list_rankup.php?sort=count&order=desc&seite=1&user=25&search=
http://egc-clan.de/ts/stats/top_all.php

**Comment by Newcomer1989** [comment]
Sieht für mich auf den ersten Blick korrekt aus. Die User mit annähernd 30 Tagen sind vom Ranksystem ausgeschlossen, wie in der Spalte "nächste Servergruppe" zu sehen. Daher haben diese Personen auch keine Nummer in der Spalte Rang.
Der erste User mit Rang (nicht ausgeschlossen) taucht bei dir erst auf Seite 8 auf.

Sollte das zu sehr verwirren, da bei dir schon einige User ausgeschlossen sind, würde ich empfehlen die ausgeschlossenen User von der List-Rankup zu nehmen. Das kannst du im Webinterface -> Stats Page -> excepted Client.

**Comment by DerRene97** [comment]
Ah ich verstehe jetzt wo das Problem liegt.
Ich habe bewusst relativ viele Server Gruppen ausgeschlossen da ich das System nur für unbekannte und neue Clients nutze um deren Permissions etwas einzuschränken.
Daher hatte ich in den toplisten eine if-Abfrage entfernt, dass auch ausgeschlossene User mit aufgelistet werden. Durch ein Update scheinen diese Änderungen aber überschrieben worden zu sein.
Habe das ganze nun wieder angepasst wie ich es hatte und nun wird es auch wieder wie gewohnt angezeigt.

**Comment by Newcomer1989** [comment]
Ok, dann hat es sich ja erledigt ;-)
