### ISSUE TITLE
XSS In multiple stats/top_*.php

### ISSUE THREAD

**Issue by Roshke** [Newcomer1989/TSN-Ranksystem#629]
In some ranks such as 10 and 3 for example htmlspecialchars(); function is missing which let's users do nasty XSS.

I had luck that my friend was Rank 10 and we got the idea to test this.

**Comment by Newcomer1989** [comment]
Ok, thx for reporting that.. It will be fixed with the next update.

**Comment by Newcomer1989** [comment]
fixed with 1.3.1
