### ISSUE TITLE
What is Idle Time?

### ISSUE THREAD

**Issue by juvcrafter** [Newcomer1989/TSN-Ranksystem#63]
Hey,
What is in your eyes the idle time?
What is "active time" and what is "idle time"

Is idle time the time, when you are not talking?

**Comment by Shad86** [comment]
Yes the Idletime is the time where you'r not talking.

So if idletime is active the bot ranks only
Up if the specific  / active time / speachtime is reached.

If idletime is off only the onlinetime counts for rankups

Regards

Shad86
