### ISSUE TITLE
Fehlerhafte Darstellung auf der Statsseite

### ISSUE THREAD

**Issue by Spooonky** [Newcomer1989/TSN-Ranksystem#634]
**Ranksystem Version:**
1.3.0-pre-1.3.1-8

**Beschreibung:**
**1) Was hast du getan?**
Beim Aufrufen der Stats seite ist mir aufgefallen das die Stats nicht richtig dargestellt werden. 
Der Ring für die Versionen ist verschoben. 

**2) Was war deine Erwartung?**
---

**3) Was ist stattdessen passiert?**
Ring ist nach links oben verschoben. 

http://31.19.113.232/rank/stats/index.php

**Comment by Newcomer1989** [comment]
Sollte in Version 1.3.0-pre-1.3.1-9 gefixt sein. Ist auch schon raus -> !update
