### ISSUE TITLE
Reset User-boost-cache on changing Boost-Config

### ISSUE THREAD

**Issue by xopez** [Newcomer1989/TSN-Ranksystem#635]
**Ranksystem Version:**
1.3.0

**Beschreibung:**
**1) Was hast du getan?**
Ich nutze das Boostingfeature. Habe durch eine automatisiertes Tool die Servergruppe erhalten. Das Ranksystem nimmt es nach ca. 1sec wieder weg. Das passiert nur selten und ist jetzt das 2. mal seit einer woche aufgetreten.
Hier noch meine Boostdefiniton: `144=>1.25=>10800`

**2) Was war deine Erwartung?**
Die Gruppe soll natürlich erst nach abgelaufener Zeit abgenommen werden.

**3) Was ist stattdessen passiert?**
Wurde quasi direkt weggenommen.

**Ranksystem Log**
https://pastebin.com/EnaMK9dz

```
2019-06-29 08:42:47.830844|INFO    |VirtualServer |1  |client (id:2) was added to servergroup 'Voter'(id:144) by client 'Votebot'(id:1203)
2019-06-29 08:42:48.763761|INFO    |VirtualServer |1  |client (id:2) was removed from servergroup 'Voter'(id:144) by client 'Ranksystem'(id:758)
```

**Comment by Newcomer1989** [comment]
Tritt das Problem denn immer bei unterschiedlichen Usern auf? Oder ist hiervon immer der gleiche User betroffen?

Wir haben schon mehrmals Probleme in dieser Richtung gesehen. Hier war es so, dass ein Boost einer Person gegeben wurde (durch zuweisen einer Gruppe). Wurde dann währenddessen (Boost der Person war noch nicht abgelaufen) die Boost-Config geändert, konnte das Ranksystem die alte Gruppe (aufgrund von Unwissenheit) nicht mehr entfernen. Wurde dann bei der gleichen Person die neue Boost-Gruppe hinterlegt, so wurde sie direkt entfernt, da noch der Zeitpunkt aus der ersten Vergabe hinterlegt war.

Wir planen hier eine Bereinigungsfunktion. Wenn die Boost-Config geleert wird, so werden beim Start des Bots alle gemerkten Zeiten resettet. Da sich die 1.3.1 schon in der Endphase befindet, werden wir das aber erst mit 1.3.2 umsetzen können.
Sobald es in der Beta-Version verfügbar ist, werde ich mich hier noch einmal melden.

**Comment by xopez** [comment]
Es waren einmal ich selbst und einmal einer meiner Moderatoren. Die Config wurde in letzter Zeit nicht geändert. Das einzige, was geändert wurde, ist, dass der Faktor auf den Dezimalwert geändert wurde. Das habe ich aber schon bei Release geändert. Sollte somit schon 2 Wochen ca. her sein.

Vielleicht hat es damit was zu tun, dass es im nachhinein entfernt wurde. Ich könnte es mal versuchen nachzustellen damit.

**Comment by xopez** [comment]
> Vielleicht hat es damit was zu tun, dass es im nachhinein entfernt wurde. Ich könnte es mal versuchen nachzustellen damit.

Damit hat es jedenfalls nichts zu tun

**Comment by Newcomer1989** [comment]
Ich schätze schon, dass es die von mir beschriebene Konstellation betrifft. Gib mir ein paar Tage, um es zu programmieren. Sobald es Bestandteil der Beta-Version ist, gebe ich bescheid.

**Comment by Newcomer1989** [comment]
Ist Bestandteil der aktuellen Beta der 1.3.7.

Wird die Boost-Definition vollständig geleert, so wird während des Speichern die Boost-Zeit bei allen Clients zurückgesetzt, falls noch eine hinterlegt ist. Am besten hierfür zuvor den Bot kurz stoppen und nach dem Speichern neustarten, damit es zu keinen Überschneidungen kommt.

**Comment by wilkens-florian** [comment]
Ihre Nachricht wurde soeben weitergeleitet.
Bitte beachten sie das diese Nachricht unverbindlich ist.
