### ISSUE TITLE
TeaSpeak - New loop

### ISSUE THREAD

**Issue by almir101** [Newcomer1989/TSN-Ranksystem#636]
**Ranksystem Version:**
The Ranksystem is running on version: 1.3.1
**Description:**
The bot updated itself automatically through beta channel

**2) What did you expect?**
/
**3) What result did you get?**
Recently I opened up topic about looping and I was able to fix it by editing database structure
(groups name and users name to varchar(120) instead of varchar(30))
And the bot was able to write gathered informations to the database.
Since last update the loop occurred again. Groups name and Users name structure remained at varchar(120), however I set it back to the 30, but it is still looping (I know this makes no sense but just to make sure it is not mistake made by me editing structures)
**Ranksystem Log**

https://life2game.info/dl/secret_files/text/ranksystem.log
Temp SQL Dump from /logs
https://life2game.info/dl/secret_files/files/temp_sql_dump.sql

**Comment by almir101** [comment]
Manually edited table structure as in picture below
http://life2game.info/dl/secret_files/photos/chrome-01-July-2019_15-42-27-606-32Mb0qlEVJOCTeKWNixZ.jpg
And then it worked, because in combination of TeaSpeak server and special character names
clients were able to exceed that limit of varchar(30).
And it worked on 1.3.0-pre-1.3.1-2 and all versions after that, but on 1.3.1 it started looping again.

**Comment by Newcomer1989** [comment]
Should be fixed with version 1.3.2. Please do a !update.
