### ISSUE TITLE
Last update breaks everything

### ISSUE THREAD

**Issue by NOFEAR2h** [Newcomer1989/TSN-Ranksystem#638]
**Ranksystem Version:**
1.3.1

**Description:**
**1) What did you do?**
I did not do anything, the reason arose after the automatic update

**2) What did you expect?**
Normals work))

**3) What result did you get?**
The system began to work in the opposite direction. Levels of groups go backwards, look at the screen - https://i.imgur.com/Ga97FLh.png and Verification does not work on the site

**Ranksystem Log**
https://pastebin.com/ETVUyR6Q

**Comment by Shad86** [comment]
1. The ranksystem now corrects wrong set groups in all directions (this could be the "backwards thing")

So the thing with the levels should be fine

2. that what i can see in your log is that there is a "loop" so the dev have to look into it

I would have one question in advance:

Which TS3-Server version do you use?

**Comment by NOFEAR2h** [comment]
Version: 3.9.0 Linux

**Comment by Newcomer1989** [comment]
Should be fixed with version 1.3.2. Please do a !update.
