### ISSUE TITLE
TopUserLists PHP Fehlermeldung

### ISSUE THREAD

**Issue by VisMotrix** [Newcomer1989/TSN-Ranksystem#639]
**Ranksystem Version:**
1.3.1

Wenn ich auf eine der 3 top usere seiten gehe bekomme ich dies fehlermeldung:
PHP Warning:  array_intersect_key(): Expected parameter 2 to be an array, null given in C:\inetpub\wwwroot\AVS\test\stats\top_all.php on line 40
PHP Warning:  array_intersect_key(): Expected parameter 2 to be an array, null given in C:\inetpub\wwwroot\AVS\test\stats\top_week.php on line 42
PHP Warning:  array_intersect_key(): Expected parameter 2 to be an array, null given in C:\inetpub\wwwroot\AVS\test\stats\top_month.php on line 42

ich denke es hat was mit der php ini zu tuhen.
Ich benutze WIN2016 und php 7

**Ranksystem Log**
https://pastebin.com/McTpcZT7

**Comment by Shad86** [comment]
Hey die logs sind hier nur aus einem recht aktuellen stand, hast du noch logs die weiter zurückliegen?

Falls nicht, lass das Ranksystem mal laufen und schick ca. 24h später einen log in dem du auch 2-3 mal versucht hast mit !update ein update anzufragen.

Webinterface link wäre ggf. auch hilfreich um weitere Fehler auszuschließen.

**Comment by VisMotrix** [comment]
Hier die logs von ein paar tagen:
https://pastebin.com/UaAsMs3p

Und hier der link zum interface
http://5.9.62.215/AVS/TeamSpeak-Ranksystem/stats/index.php

**Comment by Shad86** [comment]
Okay, hast du mal folgendes überprüft?

>  network connection to ts-ranksystem.com (IP: 164.132.201.2) on TCP port 443

Vermute nämlich das der Bot einfach nicht mit uns kommunizieren kann.

**Comment by VisMotrix** [comment]
hallte ich übersehen, Danke ist eingetragen.

**Comment by Newcomer1989** [comment]
Thx für den Hinweis.

Die PHP Warnings werden mit der Version 1.3.3 behoben (bzw. ist bereits Bestandteil der Beta Version).
