### ISSUE TITLE
Starting the ranksystem bot.

### ISSUE THREAD

**Issue by hellboy12332** [Newcomer1989/TSN-Ranksystem#64]
Hi, i have it installed on windows, i have everything working accept when i try to launch the bot itself i get an error stating "Starting the Ranksystem Bot.No Instance(s) Available.[Failed]" I have tried fresh installs of everything i can, can i have some help please

**Comment by Shad86** [comment]
The only thing i saw in the Changelog about the "comeback" for the "Windows Version" is:

> **! windows support is back (for the webspace); the COM extension for PHP is required (extension=php_com_dotnet.dll -> only Windows!)**

so maybe this is missing on your site?

im Sorry im not that into on the windows Version

regards

**Comment by hellboy12332** [comment]
Yeah i already tried that i added extension=php_com_dotnet.dll to my php.ini as instructed and have confirmed that the .dll is actually there haha, but thanks anyway :)

**Comment by hellboy12332** [comment]
I was able to get this working with going back to version 1.00

Thanks.

**Comment by Newcomer1989** [comment]
You made sure, that the COM extension is really enabled?

You can check this with [phpinfo](http://php.net/manual/de/function.phpinfo.php).

**Comment by hellboy12332** [comment]
Yeah I did, I worked out that for some reason version 1.0.2 will only work if i copy and replace the "worker.php" with the one from version 1.00, perhaps its just an issue with windows 10 as thats what it's all running off, but by doing what i did everything is working fine there is no errors, i would also like to say thank you very much for putting this all together and releasing it for public use ! 10/10

**Comment by hellboy12332** [comment]
I wish i could give you error logs or something but it never starts enough to even make any logs -.- if you want to look at my PHP config heres the link, as far as i can tell the COM extension is working [http://arenacafe666.ddns.net:85/phproot/version.php](url)
