### ISSUE TITLE
Multiple PHp 

### ISSUE THREAD

**Issue by jacopomozzy** [Newcomer1989/TSN-Ranksystem#640]
**Ranksystem Version:** 1.3.0

**Description:**
Ranksystem stopped working saying into the webinterface:
It seems to be, you are running multiple PHP versions on your system.

Your webserver (this site) is running with version: 7.2.19-1+ubuntu18.04.1+deb.sury.org+1
The defined command in "other/phpcommand.php" is running with version: 7.3.6-1+ubuntu18.04.1+deb.sury.org+1

Please use the same PHP version for both!

You can define the version for the Ranksystem Bot inside the file "other/phpcommand.php". More information and examples you will find inside.
Current definition out of "other/phpcommand.php":

php

You can also change the PHP version, your webserver is using. Please use the world wide web to get help for this.

We recommend to use always the latest PHP version!

If you can't adjust the PHP versions on your system environment, it works for your purposes, it's ok. However, the only supported way is one single PHP version for both!

The path where you could find PHP on your website:
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

What can I do?

**Ranksystem Log**
_Add a Ranksystem-Log extract of the last startup._
_You can also use https://pastebin.com/ for this and share us the link._

**Comment by Shad86** [comment]
well you have to look where the php version is, what your webserver is using and then correct it there -> "other/phpcommand.php":

There are also examples in it how you can do it.

Also know that you only have one line activated all others should be "deactivated" with a #

regards

**Comment by jacopomozzy** [comment]
How can I check and then what I have to write for correct the php version?

Regards

**Comment by Newcomer1989** [comment]
I would recommend to change the PHP version for your webserver. You are using the latest PHP version for the Ranksystem, that is good.

https://lmgtfy.com/?q=linux+apache+change+php+version

**Comment by jacopomozzy** [comment]
Thank you!
