### ISSUE TITLE
Infinite Loop after update

### ISSUE THREAD

**Issue by Ajdedja** [Newcomer1989/TSN-Ranksystem#641]
**Ranksystem Version:**
1.3.2

**Description:**
I updated the program. After that, he started giving me an infinite loop in the log, repeating the same pattern several times.
The program has never given problems with version 1.3.0.
The fact that you use port 10033 for querry is wanted.

**Ranksystem Log**
https://pastebin.com/5Vtw3CJG

**Comment by Newcomer1989** [comment]
Will be fixed with the next version.

You can change to the beta channel to get the update already.

**Comment by Ajdedja** [comment]
I tried updating to the beta. The situation does not improve. The bot disconnects after a few seconds without leaving any message in the log

**Comment by Newcomer1989** [comment]
You tried or have you updated?
Which is your current version?

**Comment by Ajdedja** [comment]
I updated it. Now I'm not at the PC and I can't check the exact version, but it was something like 1.3.2 - 1.beta etc etc ...

**Comment by Newcomer1989** [comment]
I would need the exact version.

**Comment by Ajdedja** [comment]
Good evening, finally to the PC. The version of the script is 1.3.2-pre-1.3.3-2. With this version, the bot crashes after a few seconds, without leaving any message in the logs.

https://pastebin.com/JZYvwWDe

**Comment by Newcomer1989** [comment]
Can you please run the Bot with debug Log-Level and post us your log again. Thx.

**Comment by Ajdedja** [comment]
https://pastebin.com/3F3GXyMy

**Comment by Newcomer1989** [comment]
hmm... I think we need to have a look to your system. 

It would be nice, when you can contact us on our support TS: ts-n.net

**Comment by mcmufffin** [comment]
Heyho!

Habe das gleiche Problem, ist 1.3.2 die neuste Beta?

**Comment by mcmufffin** [comment]
Works with latest beta :) Bot took some time before updating after chaning update channel.
