### ISSUE TITLE
XAMPP - Owner/Access Permissions missing.

### ISSUE THREAD

**Issue by Thilo12** [Newcomer1989/TSN-Ranksystem#642]
**Ranksystem Version:**
Neuste
**Beschreibung:**
**1) Was hast du getan?**
Guten Tag,
Ich hatte mich vor ca 2 wochen gemeldet, kurz danach ging es in den Urlaub :-) Deswegen wurde der alte post geschlossen. Es wäre super wenn nochmal Support gegeben werden könnte.
Aktuelle Lage: https://gyazo.com/c5f37db375a372a566b0621b62bed839
Starten des Workers nicht möglich. Leider läuft das ganze auf Windows, sonst könnte ich die beigesetzten Linux Terminal Commands nutzen. (USER sind angepasst VOLLZUGRIFF) woran liegt es?

**Comment by Newcomer1989** [comment]
Was genau steht denn im Logpath (Webinterface -> Other -> Logpath)?

**Comment by Thilo12** [comment]
Im webinterface weder über Localhost noch von außen was zu machen.... ich bekomme nur diese Meldung das wars :( In den datein befindet sich kein Ordner oder eine Datei namen Logpath.

https://gyazo.com/35a5d98d352f47300bb8c45bd8c3a453

**Comment by Shad86** [comment]
Newcomer meinte du sollst im Webinterface unter „other“ nachschauen was bei logpath steht und dies bitte (per Screenshot) mitteilen. :)

**Comment by Thilo12** [comment]
Das ist ja mein problem :D 

https://gyazo.com/0e0cdbddab318c1b53c01954757a6977 

ich komme nicht zu Other ich bekomme auf jeder dieser seiten die fehlermeldung

**Comment by Shad86** [comment]
Sorry noch früh, da steht das „ank/logs“ der logpfad sei? du bist dir sicher das „ank/logs“ als Pfad so existiert?

**Comment by Newcomer1989** [comment]
Hast du einen Zugriff auf die Datenbank?

Dann schau mal, was dort drin steht..
`select * from cfg_params where param='logs_path';`

**Comment by Thilo12** [comment]
Wo genau finde ich das? 
https://gyazo.com/442422d761df28acf7ed5f63cbc41907

**Comment by Newcomer1989** [comment]
In der DB, welche du bei der Installation angegeben hast.

**Comment by Thilo12** [comment]
Es hat funktioniert! ich habe den pfad angepasst und jetzt klappt wieder alles, vielen dank!

//Kann geschlossen werden
