### ISSUE TITLE
Bot Crash after update

### ISSUE THREAD

**Issue by Ajdedja** [Newcomer1989/TSN-Ranksystem#649]
**Ranksystem Version:**
1.3.3

**Description:**
I saw that there are other people with the same problem, but I opened the ticket anyway because unlike them my server version is 3.9.1

**1) What did you do?**
Nothing, just automatic update

**2) What result did you get?**
Bot Crash.

**Ranksystem Log**

https://pastebin.com/iVsqUmpX

**Comment by Shad86** [comment]
Knowen issue at the moment, the dev will look after it asap.

**Comment by Newcomer1989** [comment]
Can you send us here the dump file out of `/logs/temp_sql_dump.sql`? Thx in advance!

**Comment by Ajdedja** [comment]
I had already put the Debug-Mode but it didn't generate the file for me. I tried to look for it, but in my folder there is no file with a similar name. There is only PID and the classic log. Is there a way to generate it manually?

**Comment by Newcomer1989** [comment]
Is it possible to get remote hands on your system?
We would like to have a look on your Ranksystem to debug the problem.
You can contact us on our public TS server (address: ts-n.net), when you agree.

**Comment by Newcomer1989** [comment]
Please install the PHP extension [mbsting ](https://www.php.net/manual/en/book.mbstring.php). This should solve the problem.

On Linux you can install it with the following command:
`apt install php-mbstring`
