### ISSUE TITLE
Problem update_groups 6: - Download GroupIcons continuously

### ISSUE THREAD

**Issue by PAR4NA** [Newcomer1989/TSN-Ranksystem#65]
Server statistics not update

http://pastebin.com/wU02S08V

**Comment by Shad86** [comment]
Hello @par4na i also saw that on a other thread and as i also said there its only a thought but it looks like the database is corrupt but im not that sure about it.

So well you can tyr a fresh install or just wait for an answer from @Newcomer1989 

regards

Shad86

**Comment by par4na** [comment]
Hi @Shad86 , my datebae is new, I had to reset my teamspeak to put this rank because of the same problem. At first the rank was working, after the additions of new servergrups rank began to give problems.

**Comment by Newcomer1989** [comment]
It seems to be a problem with the servergroup 
Puniçao &quot;Use Push to Talk&quot;

Can you let me know, how it is exactly written in your TeamSpeak?
Its this?
Puniçao "Use Push to Talk"

**Comment by par4na** [comment]
I deleted the servergroups  with ----------******---------- and Puniçao "Use Push to Talk", and I am having the same problem

http://pastebin.com/X43fBwc1

**Comment by par4na** [comment]
Resolved: The rank can not download all the servergrups at once, I was added gradually and now works.

**Comment by Newcomer1989** [comment]
>  I was added gradually and now works.

How you did that exactly? You deleted all other servergroups and recreated it gradually?

**Comment by par4na** [comment]
Nope.

I did the backup server, and deleted 80% the serverus groups, I turn on the teamspeak, and called the rank, waited 10 minutes to see if I will not give error.

I deleted the teamspeak and restored the backup,  and deleted 60% the serverus groups, I turn on the teamspeak, and called the rank, waited 10 minutes to see if I will not give error.

I deleted the teamspeak and restored the backup,  and deleted 40% the serverus groups, I turn on the teamspeak, and called the rank, waited 10 minutes to see if I will not give error.

I deleted the teamspeak and restored the backup,  and deleted 40% the serverus groups, I turn on the teamspeak, and called the rank, waited 10 minutes to see if I will not give error.

I do not deleted server groups from my server, I just did it gradually loading the new groups

"sorry I do not speak English and it is difficult to express"

**Comment by Newcomer1989** [comment]
Ok, I am really confused.

I will try to test it with much servergroups. If I can reproduce the problem, I will change the insert to smaller steps.

**Comment by par4na** [comment]
Thanks you for making this wondrous script.

My Staff is working on the translation to Portuguese

**Comment by Newcomer1989** [comment]
A translation to portuguese would be really nice.

Here an actual language file as base.
http://pastebin.com/0FyBjpee

**Comment by Newcomer1989** [comment]
Back to topic..
The problem should be solved with 1.1.0. It happened with servergroups without an icon or especially when the server has no servericon set.

**Comment by Newcomer1989** [comment]
Release 1.1.0 is out. Problem should be solved with this.

**Comment by Jo0Lz** [comment]
I am having this exact same issue. Keeps downloading the ServerGroupIcon, and it keeps running into the same error.

http://pastebin.com/n3R21XTu
