### ISSUE TITLE
Bot versucht über Benutzer-ip zu starten.

### ISSUE THREAD

**Issue by AgendZero** [Newcomer1989/TSN-Ranksystem#650]
**Ranksystem Version:**
1.3.2 mit 1.3.3 Dateien, da ich nicht starten kann.
**Beschreibung:**
**1) Was hast du getan?**
Versucht den Bot nach dem Update zu starten.
**2) Was war deine Erwartung?**
Das der Bot startet.
**3) Was ist stattdessen passiert?**
Der Bot ist nicht gestartet.
**Ranksystem Log**
https://pastebin.com/yTSF6vat

Mir ist der Fehler durchaus bekannt, habe ihn aber auch schon vorher "behoben", jedoch müsste es doch möglich sein, dass dies nicht passiert und nach einem Update gefixt oder nicht überschrieben wird.

**Comment by Shad86** [comment]
Bezgüglich:

> 2019-07-28 20:36:07.169781   CRITICAL  Request to start the Ranksystem from "My Local IP" It seems the request came not from the command line! Shutting down!

Normalerweise, ist das ein Anzeichen dafür, dass der Bot nicht korrekt gestartet wurde.

Wenn es sich tatsächlich um einen Fehler bei dir handeln sollte und du es aber immer stillschweigend von selbst behebst, können Dinge ohne jeglichen Report natürlich auch nicht gefixed werden. (Leider sind uns derzeit jegliche Glaskugeln zum Hellsehen leider ausgegangen)

Bezzüglich:

> Der Bot ist nicht gestartet. (Version 1.3.3)

Das ist bekannt und der Dev, wird sich so schnell es ihm möglich ist darum kümmern.

**Comment by AgendZero** [comment]
Dieser Fehler wurde bereits hier in irgendeinem Threat bearbeitet wo es hieß, dass man zwei Zeilen löschen muss damit der "Fehler" weg seie. Gesagt getan. Danach ging es. Dazu muss ich sagen das ich das System jetzt seit ca. 5 Tagen nutze...

**Comment by Shad86** [comment]
Okay, gut es klang so als würdest du das schon immer so machen.

Ein User war der Meinung (zumindest kann ich mich daran dunkel erinnern) das er es damit "gelöst" hat, jedoch hat ein Dev dazu eindeutig geschrieben, dass dies nicht der richtige Weg ist und man sich sein Problem anschauen müsste - jedoch wie so oft melden sich dann diese Personen nicht mehr - ergo kann das Problem dann auch nicht angegangen werden.

Btw:

Kannst du mal das Dump-File /logs/temp_sql_dump.sql hier anhängen? Vielen Dank!

**Comment by AgendZero** [comment]
Ein ganz normal gehostets Webspace welches unter plesk läuft.

**Comment by Shad86** [comment]
Plesk und gehostet, ist eher eine schwierige Kombi  - da ist schwer nachzuvollziehen, wi was gehandelt wird. 

Dein Fehler deutet aber ziemlich darauf hin, dass dieser nicht als command ausgeführt wird (php exec) sondern abgewandelt wird z.B. per URL ausgeführt wird. Was bei dem Ranksystem grundsätzlich nicht erlaubt ist - Dinge per URL auszuführen, da man ja sonst das Ranksystem einfach ohne login neustarten / stoppen und starten könnte.

**Comment by AgendZero** [comment]
Ich denke mal, das ich das Problem bei mir gefunden habe. Habe nochmal an der php Version herum gefummelt. Jetzt ist die Warnmeldung im Loginbereich auch richtig weg. Jedoch lässt sich der Bot nicht starten, bzw er gibt auch keinen Output in der Console aus...

**Comment by rleite01** [comment]
@AgendZero 
Hey, I have the same problem!
Can you help me solve? I can't start the bot.

**Comment by rleite01** [comment]
@AgendZero 
Hey, I have the same problem!
Can you help me solve? I can't start the bot.

**Comment by AgendZero** [comment]
Update php to the latest version and write the correct path of the php location in the phpcommands.php. Thats what i've done.

**Comment by Newcomer1989** [comment]
> Habe nochmal an der php Version herum gefummelt. Jetzt ist die Warnmeldung im Loginbereich auch richtig weg.

Das wäre auch eine wichtige Info gewesen, die wir hätten hier eingangs benötigt. Spätestens, wenn etwas nicht wie gewünscht funktioniert, sollte man Warnmeldung dann beachten.

> Ich denke mal, das ich das Problem bei mir gefunden habe. [..] Jedoch lässt sich der Bot nicht starten, bzw er gibt auch keinen Output in der Console aus...

Ok, also ist das Problem aber noch nicht behoben. Was genau steht denn nun in der phpcommand.php?

Läuft neben Plesk auch noch CPanel, oder wurde da vielleicht was durcheinander gebracht?
Die Meldung `2019-07-28 20:36:07.169781   CRITICAL  Request to start the Ranksystem from "My Local IP" It seems the request came not from the command line! Shutting down!` ist grundlegend bekannt von CPanel, allerdings nicht typisch für Plesk.
Und ich weiß gar nicht, kann man CPanel überhaupt neben Plesk beretreiben, da doch beide die gleiche Aufgabe haben?!

**Comment by AgendZero** [comment]
> Das wäre auch eine wichtige Info gewesen, die wir hätten hier eingangs benötigt. Spätestens, wenn etwas nicht wie gewünscht funktioniert, sollte man Warnmeldung dann beachten.

Mir ist diese Warnmeldung nicht ganz aufgefallen bzw. irrelevant erschienen. Die Warnmeldung bezog sich auf die php-Version. Das TSN ist auf einer anderen php-Version gelaufen als der Webserver selbst. Habe daher die php-Version im gesamten Webspace aktualisiert. Nun steht in der phpcommand.php => `/opt/plesk/php/7.3/bin/php` statt `php`, da bei mir das normale `php` nicht ausgereicht hat.

> Ok, also ist das Problem aber noch nicht behoben. Was genau steht denn nun in der phpcommand.php?

Durch das anpassen der php-Version und der phpcommand.php lief alles einwandfrei.

> Läuft neben Plesk auch noch CPanel, oder wurde da vielleicht was durcheinander gebracht?
Die Meldung 2019-07-28 20:36:07.169781 CRITICAL Request to start the Ranksystem from "My Local IP" It seems the request came not from the command line! Shutting down! ist grundlegend bekannt von CPanel, allerdings nicht typisch für Plesk.
Und ich weiß gar nicht, kann man CPanel überhaupt neben Plesk beretreiben, da doch beide die gleiche Aufgabe haben?!

Wie gesagt, habe nur Obiges angepasst und schon läuft es.

**Comment by Newcomer1989** [comment]
> Jedoch lässt sich der Bot **nicht** starten, bzw er gibt auch keinen Output in der Console aus...

Wie darf ich dann diesen Satz verstehen? Hat es sicht erledigt?

**Comment by AgendZero** [comment]
> Wie darf ich dann diesen Satz verstehen? Hat es sicht erledigt?

Habe halt auf "Bot starten" geklickt und nichts ist passiert, keine Meldung in der Log.
Nach dem Anpassen des php gedönze läuft alles wie es soll.

**Comment by Newcomer1989** [comment]
Ok, super!
