### ISSUE TITLE
Servergruppen zuweisen

### ISSUE THREAD

**Issue by AgendZero** [Newcomer1989/TSN-Ranksystem#651]
**Vorhandenes Feature**
 
***1) Ich beziehe mich auf das folgende bestehende Feature***
Servergruppen zuweisen
 
***2) Was möchtest du hinzufügen oder ändern?***
Es sollte möglich sein Servergruppen auszuschließen welche diese Funktion nutzen.
oder
Es sollte möglich sein abzufragen welche Servergruppe benötigt wird um diese Funktion zu nutzen.
 
***3) Was wäre der Vorteil?*****
Um es auf unser Beispiel zu legen: Wir haben eine externe Freischaltung über unsere Homepage. Durch das zuweisen einer der Servergruppen wird die Standartservergruppe überschrieben, da ja jetzt eine vorhanden ist. Das würden wir gerne dadurch verhindern.

Ich hoffe ich habe es verständlich erklärt.

**Comment by Shad86** [comment]
Wir haben eine Blacklist hinzugefügt.
