### ISSUE TITLE
Group assigner upgrade

### ISSUE THREAD

**Issue by almir101** [Newcomer1989/TSN-Ranksystem#652]
It would be nice to have that users can assign themselves groups based on their current group.
Example:
I have game icons which anyone can assign...
But I have some groups that I want to be able to be used only by members who are Higher than Level 5 (TSN system groups are in range of 1 to 10 in my server)
There is group called DJ, this particular group allows you to command with public Musicbots on server. (You can move bot from bot room to your room, play music etc.) and I want only active members to have it, I assume that active members are level 5 or more.
To assume, it will be nice to add an extra option in ../stats/assign_groups.php
along with this current to add 1 more extra option like 
"Limit of simultaneous groups: 5" just to be named "Groups with requirements" or something.
I hope you understand my bad english language.

**Comment by almir101** [comment]
Or if possible to be able to make infinite of those like special groups for level 7, special for level 8 etc..

**Comment by Shad86** [comment]
We've added a "servergroup exception" list.

Maybe there will be a whitelist in the future, but for now it should at least prevent users from using it without permission.
