### ISSUE TITLE
Infinite loop adding grups/deleting

### ISSUE THREAD

**Issue by DragonHacker1** [Newcomer1989/TSN-Ranksystem#655]
**Ranksystem Version:**
1.3.3 beta channel
**Description:**
**1) What did you do?**
restarting the ranksystem, identifyin issues, changing the to stable channel
**2) What did you expect?**
I should expect last stable update fix the issue in stable channel.
**3) What result did you get?**
Same issue, nothing worked, last time i did had this issue rolling beta channel instant fixed the issue but seem is same this time again.
**Ranksystem Log**
_Add a Ranksystem-Log extract of the last startup._
_You can also use https://pastebin.com/ for this and share us the link._
https://pastebin.com/2R9rgARA
The line is too huge, i did extract a partially line since is infinite loop, i did shutdown for not food with infinite messages.

**Comment by Shad86** [comment]
You're in the beta Channel atm?

You're using Teamspeak?

You also installed the new needed Package? -> apt install php-mbstring

**Comment by DragonHacker1** [comment]
Yes im on beta channel,  i checked double check right now, seem the problem is same. I use teamspeak, i instaled right now, i did service nginx restart, restarting again the ranksystem, seem i didn't have mbstring, but i use nginx. I wanted to say this stuff worked pretty well 2months, so is not first time, i had this issue on 1.3.0 seem that time when i did switched beta channel all problems seem solved but right now is same, nothing did changed.

**Comment by Shad86** [comment]
> seem i didn't have mbstring, but i use nginx
Has nothing to do with nginx - its a php modul and you need to install it as mentioned (i only say that because in your sentence it looks like you didn't installed it)
