### ISSUE TITLE
RS is losing time

### ISSUE THREAD

**Issue by borius973** [Newcomer1989/TSN-Ranksystem#656]
**Ranksystem Version:**
1.3.3
**Description:**
**1) What did you do?**
Identified a problem with a custom script, reinstall VPS with RS bot, change VPS with RS bot

The problem is that RS accidentally loses time to people. This problem also caused a loss of client rank (massive WRONG groups removed in log).
As a proof, I attach an extract from the script that stores the client's time from DB at 2 minute intervals. Time is extracted directly from users table, count column.

https://i.imgur.com/I7rEFma.png

In the picture you can see RS taking the client ~4000 second.
2019-08-05 23:46:02 -> 27679232 seconds
2019-08-05 23:48:02 -> 27675289 seconds 

At that moment the client was Offline.

`2019-08-05 23:46:12.820231   ERROR     TS3 Error: 0: connection to server 'xx.xx.xx.xx:xxxxx' lost`

https://pastebin.com/q4sW50E2

The time of loss fits with the error.
RS worked for 3 years without a problem, error began about a month ago.

**Comment by Shad86** [comment]
So you moved to a other vps?

Some thoughts on this:

1.st you may took a wrong backup (an older one)

2.nd The old server has a time difference of 1 hour from the new server. (what are round about ~4000 Seconds)

Because out of nowhere the ranksystem wont remove just 4000 Seconds

**Comment by borius973** [comment]
Hello @Shad86 
I moved VPS because of this problem, on the new VPS the problem persists.
This problem repeats multiple times a day, same for old and new VPS.
I've tried everything to repair, problem still persists.

**Comment by Shad86** [comment]
Be careful - if you use 2 different vps - so wont mix it up and also care about that you wont use the same Database for both (or even mixing up Backups). As you will get time differences.

Next thing is, do you have ignore idle active in your config (Under Core)? If you have ignore idle for example set to 4000 Sec, this would also explain why people "lose" time as people only lose time if they idle over exact or over 4000 seconds.

**Comment by borius973** [comment]
> Be careful - if you use 2 different vps - so wont mix it up and also care about that you wont use the same Database for both (or even mixing up Backups). As you will get time differences.

Dont worry, old VPS has been complete deleted before the new VPS was installed.

> Next thing is, do you have ignore idle active in your config (Under Core)? If you have ignore idle for example set to 4000 Sec, this would also explain why people "lose" time as people only lose time if they idle over exact or over 4000 seconds.

Ignore idle is set to 600 secs, the time I mentioned (4000 secs) is random... the time it takes is random, once it is 10 hours, then 1 hour.

`2019-08-05 23:46:12.820231 ERROR TS3 Error: 0: connection to server 'xx.xx.xx.xx:xxxxx' lost`

The main thing is that when bot is dropped from TS server, then RS takes time.

**Comment by Newcomer1989** [comment]
> As a proof, I attach an extract from the script that stores the client's time from DB at 2 minute intervals. Time is extracted directly from users table, count column.
> 
> https://i.imgur.com/I7rEFma.png

What table is it, which you are showing us here?
There is no table named "users". The "user" table looks different and is saving the information unique per user.
It could be the table "user_snapshot", but there is the column "idle" missing. And the Ranksystem doesn't save values in this table each 2 minutes!

We got reported a similiar problem. Please have also a look to our instructions here https://github.com/Newcomer1989/TSN-Ranksystem/issues/644#issuecomment-517848841

**Comment by borius973** [comment]
You did not understand me. This table is mine, the table contains count extract from user table. 
The table should display an error that takes time. At 23:46 I had saved Time (user table / count column) 27679232 and at 23:48 noon i had 27675289.

**Comment by Newcomer1989** [comment]
The Ranksystem is doing a loop of scanning clients each second, I couldn't image how this should be possible.

Ok, let me describe, how the Ranksystem is working:
1) It is selecting the data out of the database (table user) at the beginning of each loop.
2) It takes the timestamp of the last scan (loop) out of the database (table job_check).
3) It collects the user, which are online on the TS3 server via TS3 server query.
4) Then it calculates the new time values (difference between now and job_check.calc_user_lastscan [2] and add this to user.count [1])
5) On end of a full loop, it updates the new values to the database.

On this method it can only be a problem, when your server time changes. Since there is a check inside, we should be sure, this is not the problem or you would find an error inside the Ranksystem.log.
```
} elseif($select_arr['job_check']['calc_user_lastscan']['timestamp'] > $nowtime) {
		enter_logfile($cfg,3,"Negative time between now and last scan (Error in your server time!).. reset time difference to zero.");
```


Since you are using `a custom script` it would be helpful, what exactly you have modified and/or what scripts are running against the same (ranksystem) database and what this scripts are exactly doing!

The loss of the times, does this affect all users or only a few?

**Comment by borius973** [comment]
I didn't interfere with the RS scripts, my PHP script only selects count column from RS user table and store data to my table. 

I think RS takes time to all.

btw RS takes time only if it falls (loss connect from TS server)

> 2019-08-05 23:46:12.820231 ERROR TS3 Error: 0: connection to server 'xx.xx.xx.xx:xxxxx' lost

I solved this problem temporarily with turned off SSH query. If it was turned on, RS disconnect very often.

**Comment by Newcomer1989** [comment]
The loss of the times, does this affect all users or only a few?

**Comment by borius973** [comment]
all users

**Comment by Newcomer1989** [comment]
Really all users, so the full table user at the same time?

**Comment by borius973** [comment]
*All users who were offline at the time of RS disconnection

**Comment by Newcomer1989** [comment]
I hope, we could fix the problem.. You can change to the beta channel and test it with this version. A feedback would be nice!

**Comment by borius973** [comment]
I'm testing it 48h, so far without a problem. Thank you

**Comment by Newcomer1989** [comment]
Since it seems to be solved we close this issue. When again problems appear, please feel free to reopen it.
