### ISSUE TITLE
Server usage issue

### ISSUE THREAD

**Issue by Meshiikun** [Newcomer1989/TSN-Ranksystem#658]
**Ranksystem Version:**
1.3.3

Why on "Server usage" the maximum value is 600?

![index](https://user-images.githubusercontent.com/52542499/62866575-61896a00-bd11-11e9-8a61-7df1be1c3096.jpg)

Thanks for answers

**Comment by Shad86** [comment]
As i know the Server usage expands if its needed - or did you test it and it wont got higher?

On mine for example it only has a max Usage of 100.

**Comment by Meshiikun** [comment]
I didn't test anything, one or two updates ago was 100 because I had max 80 people on my server.
I was thinking if it's possible to edit manually inside a file, I don't know

**Comment by Newcomer1989** [comment]
It is cause we added a new line with the max clients. See [changelog](https://ts-ranksystem.com/#changelog) from version 1.3.0.

It is planed in future versions to add a config parameter to deactivate this line.

To optimize the view now, you could reduce the max-clients. Cause in your case it seems, there are at least 400 slots never used.

**Comment by Meshiikun** [comment]
> 
> 
> It is cause we added a new line with the max clients. See [changelog](https://ts-ranksystem.com/#changelog) from version 1.3.0.
> 
> It is planed in future versions to add a config parameter to deactivate this line.
> 
> To optimize the view now, you could reduce the max-clients. Cause in your case it seems, there are at least 400 slots never used.

Ok, thanks
