### ISSUE TITLE
Changing installation folder

### ISSUE THREAD

**Issue by NinjonikSVK** [Newcomer1989/TSN-Ranksystem#659]
Hello!

I just want to know how can i change installation directory of TSN Ranksystem, because i changed it from: /var/www/html/ranksystem to /var/www/ranksystem.

But my ranksystem configuration is still in /var/www/html/ranksystem

How can i fix it?
And you should add some forum for this rank system.

**Comment by Shad86** [comment]
pls explain it exactly - because usually you can move it in any folder you want.

Only thing you have to change is the path to your Logfolder (Webinterface -> other)

Then all should work normal again.

**Comment by NinjonikSVK** [comment]
Okay..

**Comment by NinjonikSVK** [comment]
It's working. Thank You.

**Comment by Newcomer1989** [comment]
For others, which are finding this issue -> have a look [here](https://github.com/Newcomer1989/TSN-Ranksystem/wiki#changed-teamspeak-host--server---mitigation-old-ranksystem)
