### ISSUE TITLE
subfolder redirection while being on rootfolder?

### ISSUE THREAD

**Issue by Zaragan** [Newcomer1989/TSN-Ranksystem#660]
If ihave ranksystem installed on the root folder of my host why do i get redirected to a subfolder that doesnt exist on the host? Also, when i continue browsing after visit the webinterface i keep browsing with the duplicated subfolder (example: land on "page.net/stats" go to interface "page.net/PAGE/webinterface" and come back to stats with "page.net/PAGE/stats".

**Ranksystem Version:**
1.3.3
**Description:**
**1) What did you do?**
Go from stats page (mypage.net/stats) to webinterface link on the upright dropdown menu.
**2) What did you expect?**
get redirected to mypage.net/webinterface/bot.php
**3) What result did you get?**
mypage.net/MYPAGE/webinterface/bot.php (note the duplicated "MYPAGE")
**Ranksystem Log**
_Add a Ranksystem-Log extract of the last startup._
https://pastebin.com/A1wLGB1p

**Comment by Shad86** [comment]
Wrong redirect is usually a config issue on Serverside, so it seems your cms (if you're having one) or your apache/nginx config are messing up something.
