### ISSUE TITLE
how many groups can I add to the ranking system

### ISSUE THREAD

**Issue by MARL3N** [Newcomer1989/TSN-Ranksystem#661]
Hi, how many groups can I add to the ranking system?

**Comment by Newcomer1989** [comment]
As much as you can define with 21588 characters. The field inside the webinterface is limited for this count.

**Comment by MARL3N** [comment]
how to add more characters? i have 1-100 levels

**Comment by Newcomer1989** [comment]
21588 characters means you have 215 per definition of one level (by 100 level).
This should be more then enough.
Where exactly is the problem?
