### ISSUE TITLE
_Wrong file/folder permissions!

### ISSUE THREAD

**Issue by Flockeeey** [Newcomer1989/TSN-Ranksystem#663]
Hallo,
nach dem automatischen Update auf Version 1.3.3 wird uns der folgende Fehler angezeigt:

_Wrong file/folder permissions!
You need to correct the owner and access permissions of the named files/folders!_

Bei "List of concerned files/folders:" ist nichts eingetragen.

Wir benutzen IIS unter Windows und haben bereits alle PHP Extensions überprüft.
Die Schreib- und Leseberechtigungen im IIS haben sich auch nicht verändert und sind korrekt vergeben.

**Comment by Newcomer1989** [comment]
Das Update ist ja schon eine Zeit lang her. Sicher, dass es wirklich damit kam?

Beim Prüfen der Dateien auch unbedingt das Hauptverzeichnis beachten. Als User muss natürlich der User des Webservers berechtigt werden.

**Comment by Flockeeey** [comment]
Hi, 
entschuldigung für die verspätete Antwort, wir haben bis heute probiert den Fehler selbst zu beheben, finden aber keinen Lösungsansatz mehr..

Hier ein Auszug aus dem Log:

> > ###################################################################
> 2019-09-08 11:09:04.226841   NONE      Initialize Bot...
> 2019-09-08 11:09:04.239904   NONE      Running on OS: Windows NT 10.0
> 2019-09-08 11:09:04.240578   NONE      Using PHP Version: 5.6.31
> 2019-09-08 11:09:04.241194   NONE      Database Version: 5.5.5-10.3.12-MariaDB
> 2019-09-08 11:09:04.242310   INFO      Check Ranksystem database for updates...
> 2019-09-08 11:09:04.242972   INFO        Check files permissions...
> 2019-09-08 11:09:04.819299   INFO        Check files permissions [done]
> 2019-09-08 11:09:04.823908   INFO        No newer version detected; Database check finished.
> 2019-09-08 11:09:04.824608   INFO      Check Ranksystem database for updates [done]
> 2019-09-08 11:09:04.825298   NOTICE    Check Ranksystem files for updates...
> 2019-09-08 11:09:04.826291   NOTICE    Check Ranksystem files for updates [done]
> 2019-09-08 11:09:04.827653   NONE      Ranksystem Version: 1.3.3 (on Update-Channel: )
> 2019-09-08 11:09:04.828395   NOTICE    Loading addons...
> 2019-09-08 11:09:04.830340   NOTICE      Addon: 'assign_groups' [OFF]
> 2019-09-08 11:09:04.832676   NOTICE    Loading addons [done]
> 2019-09-08 11:09:04.833448   NONE      Connect to TS3 Server (Address: "" Voice-Port: "" Query-Port: "" SSH: "" Query-Slowmode: "0.0").
> 2019-09-08 11:09:04.851877   ERROR     TS3 Error: 0: Failed to parse address ":"
> 2019-09-08 11:09:04.853065   CRITICAL  Critical TS3 error on core function! Shutting down!
> 2019-09-08 11:09:04.853706   NONE      
> ###################################################################

Im Webinterface kann man sich nicht einloggen, ausserdem besteht die fehlermelung:
https://ibb.co/N3d25FC

Rechte sind alle richtig gesetzt, auch im Hauptverzeichnis.

bitte um unterstützung

**Comment by Newcomer1989** [comment]
> 2019-09-08 11:09:04.240578 NONE Using PHP Version: 5.6.31

Zunächst verwendet ihr eine total veraltete PHP Version. Wir würden empfehlen zu aktualisieren.

Ansonsten, was steht denn in eurer `other/phpcommand.php`?

Bei Windows sind die Fehlermöglichkeiten leider um ein vielfaches Vielschichtiger als bei Linux. Es wäre super, wenn wir uns das gemeinsam per Fernwartung anschauen könnten. Am besten mal mit uns über den Public TeamSpeak Kontakt aufnehmen -> TS3: ts-n.net

**Comment by Newcomer1989** [comment]
Wurde per Remote-Session besprochen. In Tabelle cfg_params fehlen wesentliche Einträge. Restore Backup oder Neuinstallation erforderlich.
