### ISSUE TITLE
Keine Funktion

### ISSUE THREAD

**Issue by florianfinn** [Newcomer1989/TSN-Ranksystem#664]
**Ranksystem Version:**
1.3.3
**Beschreibung:**
**1) Was hast du getan?**
Nach Vorgabe PHP Addons installiert und install.php ausgeführt.
**2) Was war deine Erwartung?**
Volle Funktion des Systems
**3) Was ist stattdessen passiert?**
System logt verbundende User, aber trägt nichts in die Stats ein.
Via. ServerQuery sehe ich den Bot auf den Teamspeak connected aber es werden keine Daten in das System geladen. 
**Ranksystem Log**

https://pastebin.com/grddjm2w

Nach einem Bot Neustart sieht der Log 1zu1 genau so aus. Auch werden wieder die User (Die im vorherigen Log angeblich eingetragen wurden) wieder als "Nie dagewesen" eingetragen.

-> ServerQuery und Mysql Login wurde zum Test schon auf serveradmin und root gesetzt um ungenügende Rechte auszuschließen.

**Comment by Shad86** [comment]
Hey, es könnte sein, das noch folgendes (derzeit noch nicht dokumentiertes Paket fehlt): [mbsting ](https://www.php.net/manual/en/book.mbstring.php)

Es kann unter Ubuntu/Debian mit folgendem Befehl installiert werden:
`apt install php-mbstring`

Ein Neustart von apache2 oder nginx sollte nach der Installation noch durchgeführt werden, dann sollte alles wieder gehen.

**Comment by florianfinn** [comment]
Die PHP Addons sind vollständig installiert:
http://prntscr.com/p1u7ar

**Comment by Newcomer1989** [comment]
Deine Log vom Ranksystem ist unvollständig. Bitte poste eine volle Log, damit wir dir helfen können.

**Comment by florianfinn** [comment]
https://pastebin.com/L7Qy8BbL

**Comment by Newcomer1989** [comment]
Hmm, sieht so aus als würde der Bot hart nach dem calc_user abbrechen. Anstehen würde get_avatars, was wohl nicht zum Ende kommt laut Log File.

Würde so per Ferndiagnose fast darauf tippen, dass beim Upload der Files auf den Webspace etwas schief gelaufen ist. Probiere einfach mal die Dateien von unserer Website neu herunterzuladen und auf deinen Webspace erneut hochzuladen. Bitte dabei aber das Verzeichnis `other` auslassen, sonst musst du es neu installieren.

**Comment by florianfinn** [comment]
Okay, irgendwie unlogisch, aber nach erneutem downloaden der Daten, funktioniert es nun.
