### ISSUE TITLE
Negative values for online time

### ISSUE THREAD

**Issue by jacopomozzy** [Newcomer1989/TSN-Ranksystem#666]
**Ranksystem Version:** http://mozzygaming.it/ts3ranks/stats/index.php

**Description:**
**1) What did you do?** Nothing, I watched to the page and the values are negative

**2) What did you expect?**

**3) What result did you get?**

**Ranksystem Log**
_Add a Ranksystem-Log extract of the last startup._
_You can also use https://pastebin.com/ for this and share us the link._

**Comment by Shad86** [comment]
negative values don't just come out of nothing.

I suppose a lot of time has been deducted or values have been modified for users in general.

**Comment by jacopomozzy** [comment]
The only thing that I did it was adding time to a friend that changed profile.
This negative value will resolve automatically next week/month or I have to do something?

Regards

**Comment by Shad86** [comment]
yes it should disappear after a while.
How long it takes depends on how much the last few weeks have been modified

So it could be already disappear after a week but it also could take a month (remember in case of the ranksystem "a week/a month" means "7 Days/30 Days" from point of modification)
