### ISSUE TITLE
Kleinere Fehler im Ranksystem

### ISSUE THREAD

**Issue by TheChaosToast** [Newcomer1989/TSN-Ranksystem#668]
Ich setze die aktuelle Version vom Ranksystem ein 1.3.3

Nachdem ich meinen Server auf die aktuellste PHP Version 7.3.9 geupdatet habe ist mir aufgefallen das der Bot startet und auch korrekt funktioniert, aber bei Start/Stopp Bot steht das der "Bot gestoppt" ist. Bug oder Feature? :)

Ein zweiter Fehler ist mir heute in den Logs aufgefallen: 

`[Wed Oct 02 12:43:23.449688 2019] [proxy_fcgi:error] [pid 3409:tid 139766028764928] [client 54.36.xxx.xxx:49428] AH01071: Got error 'PHP message: PHP Notice:  Undefined offset: 40 in /home/users/domain/www/ranking/stats/list_rankup.php on line 363

PHP message: PHP Notice:  Undefined offset: 40 in /home/users/domain/www/ranking/stats/list_rankup.php on line 366'`

Vielen Dank für ein Feedback :)

**Comment by Newcomer1989** [comment]
> PHP message: PHP Notice: Undefined offset: 40 in /home/users/domain/www/ranking/stats/list_rankup.php on line 366'`

Sollte mit dem nächsten Update behoben werden.

> Nachdem ich meinen Server auf die aktuellste PHP Version 7.3.9 geupdatet habe ist mir aufgefallen das der Bot startet und auch korrekt funktioniert, aber bei Start/Stopp Bot steht das der "Bot gestoppt" ist. Bug oder Feature? :)

Wie startest du denn den Bot.. Webinterface, Konsole?
Stimmt denn die Angabe in der `other\phpcommand.php`?
Stimmt auch der User des Startvorgangs (des Bots) mit dem des Webservers überein?
Hintergrund ist, dass die Webseite die Information versucht auszulesen, was also über den User des Webservers passiert. Dieser benötigt folglich die Berechtigung den Prozess zu sehen. Wird der Prozess z.B. unter root gestartet, kann der webserver diesen nicht sehen -> Folge: Es steht da Bot ist offline.

**Comment by TheChaosToast** [comment]
> 
> Wie startest du denn den Bot.. Webinterface, Konsole?
> Stimmt denn die Angabe in der `other\phpcommand.php`?
> Stimmt auch der User des Startvorgangs (des Bots) mit dem des Webservers überein?
> Hintergrund ist, dass die Webseite die Information versucht auszulesen, was also über den User des Webservers passiert. Dieser benötigt folglich die Berechtigung den Prozess zu sehen. Wird der Prozess z.B. unter root gestartet, kann der webserver diesen nicht sehen -> Folge: Es steht da Bot ist offline.

Den Bot starte ich grundsätzlich per Webinterface. Die Angabe habe ich noch nicht probiert, werde ich die Tage aber mal überprüfen. Der Webserver läuft über ein Webpanel - gehe ich also davon aus das der als user www läuft.

**Comment by Newcomer1989** [comment]
Da wir keine erneute Rückmeldung erhalten haben, gehen wir davon aus, dass das Problem gelöst werden konnte.

Falls nicht, gerne noch einmal melden.
