### ISSUE TITLE
System findet Servergruppen nicht

### ISSUE THREAD

**Issue by florianfinn** [Newcomer1989/TSN-Ranksystem#669]
**Ranksystem Version:**
1.3.3
**Beschreibung:**

Das Ranking System findet Servergruppen nicht, die aber existieren und versucht ständig, vorhandene Servergruppen Icons neu runterzuladen.

- Clean install -> Keine Änderung
- Der TS wurde einmal umgezogen und mittels YaTQA Snapshot wiederhergestellt.

Ranking: https://prnt.sc/pdztgd
**Ranksystem Log**
https://pastebin.com/8qD9VezA

- Zusatz: Es wurden auf dem Teamspeak die Namen der Ranks geändert. Nun meldet das System immer weiterhin die alten Namen in den ts Benachrichtigungen. Wie kann dies geändert werden?

**Comment by Shad86** [comment]
Hallo,

zu allererst sicherstellen bei einem Umzug, dass das hier (wie in diesem Bild zu sehen) abgeschaltet ist :
![database-datenbank-reset](https://user-images.githubusercontent.com/18570683/66713381-813d1d00-edaa-11e9-97ba-9fa68962d3c6.png)

Dann den Bot einmal mit !reloadgroups anschreiben. Danach zieht er sich alle gruppen nochmal neu und das Problem sollte spätestens nach einem erneuten connect vom betroffenem user behoben sein.

**Comment by florianfinn** [comment]
!reloadgroups gibt keine Rückmeldung oder Änderung.
Meine TS ID ist im Bot als Admin eingetragen.

**Comment by Shad86** [comment]
Das kann daran liegen, das du den Querylogin auf deinem Server Admin Client erstellt hast.

Da der Query immer mit dem account verknüpft ist, kann er dir nicht zurückschreiben.

Lösung dafür, entweder eine andere Identität mit der du nie auf den TS3 joinst erstellen, oder mit einer andern Identität joined dir auch adminrechte hat.

**Comment by florianfinn** [comment]
Das hat jetzt soweit geklappt. Gibt keine Fehlermeldung mehr. Allerdings loopen jetzt ein paar Servergruppen, die nix mit dem System zu tun haben wegen dem icon download. Aber soweit geht ja alles.
