### ISSUE TITLE
System wird nicht geupdatet

### ISSUE THREAD

**Issue by monster010** [Newcomer1989/TSN-Ranksystem#670]
**Ranksystem Version:**
 1.3.3

**Beschreibung:**
**1) Was hast du getan?**
 !update ausgeführt
**2) Was war deine Erwartung?**
Das sich das System updatet
**3) Was ist stattdessen passiert?**
Nichts

In der Datenbank steht als version_latest_available 1.3.3-beta-1.3.4-1 drin, die version_current_using ist 1.3.3. Hab rausgefunden das die PHP Funktion version_compare zwar Versionen vergleicht, allerdings ist 1.3.3 = 1.3.3-beta-1.3.4-1. Hab einfach ma in der Test PHP Datei den vergleich version_compare('1.3.4-beta-1.3.4-1', '1.3.3', '>') gemacht und das ist dann auch größer.

**Comment by Newcomer1989** [comment]
Vorher war es immer mit "pre" in der Mitte, was einige irritierte.. Hatte es von der Schematik nur auf "beta" geändert.

Also von `1.3.3-pre-1.3.4-1` auf `1.3.3-beta-1.3.4-1`.

Die Function version_compare hat aber mehr Logik als gedacht. Es erkennt den Begriff "beta" und ist so schlau, dass 1.3.4 kleiner als 1.3.4-beta ist.
Habe die Semantik nochmals überarbeitet und die Beta-1 entsprechend angepasst. Sollte dann passen, wenn der nächste Check läuft und sich auch aktualisieren. Kannst es ja gerne mal testen.

Aber wie schnell hast du das gemerkt, war ja selbst noch nicht mal fertig xD

**Comment by monster010** [comment]
Is mir dadurch aufgefallen, dass es eine beta gibt, aber mein system sich nicht darauf updatet. hab dann bissel in den code geschaut und dann das mit version_compare festgestellt.

Hab jetzt die Beta version drauf ^^
