### ISSUE TITLE
Add / Remove time doesn't work - PHP 7.3.10

### ISSUE THREAD

**Issue by Newcomer1989** [Newcomer1989/TSN-Ranksystem#671]
**Ranksystem Version:** 1.3.3 (but does not matter)

**Description:**
**1) What did you do?**
Webinterface -> Administrate -> Add time
Added a time to a user. Which user doens't matter, also as the chosen time.
Got after adding the time a message about the webinterface all was saved successfully.
Example:
`Active time of 3600 seconds for the unique Client-ID (xrTKhT/HDl4ea0WoFDQH2zOpmKg=) will be added in a few seconds (have a look to the Ranksystem log).`

**2) What did you expect?**
The time should be added to the user. There should be a log entry inside the Ranksystem.log like
`2019-10-15 22:02:26.565997   NOTICE    Add an active time of 3600 seconds for the unique Client-ID (xrTKhT/HDl4ea0WoFDQH2zOpmKg=); requested about admin function.`

**3) What result did you get?**
There is no time added. And also no message appears inside the Ranksystem.log

**Comment by Newcomer1989** [comment]
Problem comes with new PHP version 7.3.10

https://www.php.net/ChangeLog-7.php

> PDO_MySQL:
>     Fixed bug #41997 (SP call yields additional empty result set).

This ends in a new bug :(
https://bugs.php.net/bug.php?id=78623

Which is already fixed with this commit
http://git.php.net/?p=php-src.git;a=commit;h=114c03b9a6122d85ec5ccaafc031ee47e7c26df8
http://git.php.net/?p=php-src.git;a=commitdiff;h=114c03b9a6122d85ec5ccaafc031ee47e7c26df8;hp=545412a6cdefbb6d6bddf29a636832873349e10c

But this fix is not yet released.

**To solve this problem yet, you need to downgrade to PHP 7.3.9.**

**Comment by Bealze** [comment]
Can confirm @Newcomer1989 I use whm to manage all this and  wasn't able to change to PHP 7.3.9 but a simple rollback to PHP 7.0 and these options are all working as intended

**Comment by Newcomer1989** [comment]
PHP 7.3.11 is out.
The problem should be solved with!

**Comment by Shad86** [comment]
I tested the "add time" and the "remove time" function and it seems to be working again after updating PHP to 7.3.11 and restarting the bot. 

I also had issues with resetting the password, what also works for me again with PHP Version 7.3.11

**Comment by Newcomer1989** [comment]
Closed, since the most should be on newer versions and no one will update to 7.3.10
