### ISSUE TITLE
TS3 Fehler: 10061: Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte. 

### ISSUE THREAD

**Issue by razzviruz** [Newcomer1989/TSN-Ranksystem#672]
**Ranksystem Version:**
1.3.3
**Beschreibung:**
**1) Was hast du getan?**
bin im verifizierungschannel
**2) Was war deine Erwartung?**
Verifizierung
**3) Was ist stattdessen passiert?**
TS3 Fehler: 10061: Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte. 
**Ranksystem Log**
_Poste einen Log vom letzten Start des Ranksystems._
https://pastebin.com/5B9rNThj

**Comment by Newcomer1989** [comment]
Das Ranksystem benötigt eine Connection zum TS3 Server und damit muss natürlich auch eine Netzwerkverbindung zwischen den beiden Hostsystemen erlaubt sein.

Es sieht so aus, als ob entsprechende Netzwerkfreigaben (ggfs. Firewall Whitelisting) fehlen.

Sollte das Ranksystem und der TS3 auf dem gleichen Hostsystem laufen, nutze doch einfach localhost, also `127.0.0.1` als TS3 Host-Adresse.

Ich schließe den Issue damit auch wieder, da es kein Problem vom Ranksystem ist, sondern eine Einrichtungsgeschichte.
