### ISSUE TITLE
 Notice: Undefined variable: sqlhisgroup in C:\xampp2\htdocs\rank\stats\assign_groups.php on line 156

### ISSUE THREAD

**Issue by razzviruz** [Newcomer1989/TSN-Ranksystem#673]
**Ranksystem Version:**
1.3.1
**Beschreibung:**
**1) Was hast du getan?**
 möchte gruppe zuweisen 
**2) Was war deine Erwartung?**
icon angezeigt und zugewiesen
**3) Was ist stattdessen passiert?**

Notice: Undefined variable: sqlhisgroup in C:\xampp2\htdocs\rank\stats\assign_groups.php on line 156
**Ranksystem Log**
gibt nix in der log dazu
_Den Log teilst du am besten z.B. mit https://pastebin.com/ (Das macht es übersichtlicher)._

**Comment by Newcomer1989** [comment]
Ohne Log File können wir dir leider nicht helfen.

**Comment by razzviruz** [comment]
https://pastebin.com/t47A8ECc

**Comment by Shad86** [comment]
Hängt vermutlich hiermit zusammen -> https://github.com/Newcomer1989/TSN-Ranksystem/issues/671 - ein updaten auf PHP 7.3.11 sollte dein Problem beheben
