### ISSUE TITLE
Problem mit Umzug

### ISSUE THREAD

**Issue by christian8796** [Newcomer1989/TSN-Ranksystem#674]
Sehr geehrte Damen und Herren,

ich habe das Ranksystem auf einen Debian 8 Server installiert. Und habe nun einen neuen Server und wollte das Ranksystem und den Teamspeak 3 Server umziehen. 

Durch den Umzug sind die Servergruppen-IDs verrutscht. 

Zum Ranksystem:
Ich habe die Dateien von alten Server auf den neuen Server hochgeladen. Habe die Datenbank-Config dann neu angepasst. Und habe die Datenbank auf den neuen Server hochgeladen. Dann habe ich die Levelgruppen neu angepasst, da diese sich geändert haben. 

Jetzt habe ich das Problem, dass einige User einfach von Level 1 anfangen und ihr alten Rank verlieren. Habe ich etwas falsch gemacht? Gibt es Lösungsvorschläge?

Mit freundlichen Grüßen
Chris G.

**Comment by Newcomer1989** [comment]
Wir haben dazu einen Wiki Artikel verfasst. Dort findest du eine Beschreibung, was zu tun ist.

https://github.com/Newcomer1989/TSN-Ranksystem/wiki#changed-teamspeak-host--server---mitigation-old-ranksystem
