### ISSUE TITLE
Autostart - Absturz

### ISSUE THREAD

**Issue by florianfinn** [Newcomer1989/TSN-Ranksystem#675]
**Ranksystem Version:**
1.3.4-beta-2

Das Ranked System geht nach X Tagen immer aus. Es ist kein Muster oder Fehlermeldungen festzustellen. Evl. damit zu tun? https://github.com/Newcomer1989/TSN-Ranksystem/issues/669
10 Servergruppen, die nichts mit dem Ranked System zu tun haben, loopen den Avatar download durch. In den Server Daten sind diese Avatare vorhanden und löschen ändert auch nichts.

Ich betreibe das Ranked System in einem Ubuntu Docker Container. Leider habe ich noch keine Möglichkeit gefunden, beim "crash" des Bots, den Container neuzustarten bzw. den Bot-Dienst (?) direkt. Ein Cronjob, der den Container alle 12h neustarten soll, funktioniert auch nicht wie gedacht, da der Bot nicht Automatisch startet, sondern immer Manuell gestartet werden muss. 
Kann man irgendwie den Bot Status extern Monitoren (z.b. Email Benachrichtigung) oder bei absturz ihn automatisch neustarten lassen?

LG florianfinn

**Comment by Shad86** [comment]
> 7) ADD CRONJOB (OPTIONAL)

Optional: Create a cronjob to be sure, the Bot is running 24/7. This will restart the Bot automatically, e.g. on a database restart.

Open a SSH session to the host machine of your webserver.

Enter the command crontab -e, go to editing mode (in VIM you need to press i).

Paste the following in a new line:

*/10 * * * * sudo -u www-data php /path_to_your_webspace/path_to_the_ranksystem/worker.php check >/dev/null 2>&1
Configure the path, where your TSN Ranksystem is located and replace www-data with the user of your webserver.

Save and quit the crontab (in VIM :wq).

https://ts-ranksystem.com/#linux


Damit sollte es eigentlich reibungslos klappen (sofern eben alles korrekt ist - richtiger webuser/pfad...)

**Comment by Shad86** [comment]
Besteht das Problem weiterhin?

**Comment by florianfinn** [comment]
Also bis jetzt gab es noch keinen weiteren Absturz. Aber nach einem Manuellen neustarten des Docker Containers bzw. des Servers startet das System nicht direkt neu. 
Wir setzen aber demnächst Docker nochmal frisch auf, um ein Problem von der Seite auszuschließen.
Ich melde mich dann nochmal, wie es läuft.

**Comment by Newcomer1989** [comment]
Da wir nichts mehr gehört haben, gehen wir davon aus, dass alles gut läuft.

Daher -> Closed
