### ISSUE TITLE
Add ability to have more then one server on the same rank system

### ISSUE THREAD

**Issue by regchanuk** [Newcomer1989/TSN-Ranksystem#677]
Add ability to have more then one server on the same rank system
since im running multi teamspeak servers would like to add a second server to the system or more since i run 3 servers

Distinguish whether it refers to an existing or new feature..
 
**Existing Feature**
 
***1) I am referring to the following existing feature:***
 
***2) What do you want to add or change on it?***
 
***3) What would be the benefit?***
_Please only report this feature, when you think also other people would have a benefit of it._
 
**New Feature**
 
***1) What should this feature do?***
 
***2) Where should it be located?***
_On which existing part of the Ranksystem you would add this new feature?_
 
***3) What would be the benefit?***
_Please only report this feature, when you think also other people would have a benefit of it._

**Comment by Shad86** [comment]
Unfortunately, this feature would go beyond the scope.
