### ISSUE TITLE
Nur 3 Rankups werden gespeichert.

### ISSUE THREAD

**Issue by SebSeifert** [Newcomer1989/TSN-Ranksystem#679]
OS: Ubuntu 18.04
Server: nginx/php 7.3.11
Hallo,
ich habe folgendes Problem. Wenn ich in den Rankups folgendes eintrage:
`60=>67,43200=>68,86400=>69,86400=>70,86400=>71,86400=>72,86400=>73,86400=>74,86400=>75,86400=>76,86400=>77,86400=>78,86400=>79,86400=>81,86400=>82,86400=>83,86400=>84,86400=>85,86400=>86,86400=>87,86400=>88,86400=>89,86400=>90,86400=>91,86400=>92,86400=>93,86400=>94,86400=>95,86400=>96,86400=>97,86400=>98,86400=>99`

Wird der kram zwar in der DB gespeichert aber im Webinterface steht nur:
`60=>67,43200=>68,86400=>99`

Auf der Rank Seite: https://rank.ballerstube-nord.de/stats/list_rankup.php steht bei den leuten dann als nächstes der Rang mit der ID: 99 Obwohl 69 kommen müsste.
Auch weniger in der definition passen nicht.
Die Gruppen IDs sind alle in der groups Tabelle vorhanden.

**Comment by Shad86** [comment]
Hallo, im Webinterface im Reiter "Kern" wird dir mit einem Klick das eig, auch erklärt, wie die Gruppen einzutragen sind, deine sind in dem Fall nicht kumulativ, weshalb es vermutlich zu diesem problem kommt.

Hier nochmals der Hilfetext dazu:

> Definiere hier, nach welcher Zeit ein User automatisch in eine vorgegebene Servergruppe gelangen soll.
> 
> Zeit (Sekunden)=>Servergruppen ID
> 
> Entscheidend hierfür ist die 'online Zeit' bzw. die 'aktive Zeit' des Users, je nach Einstellung des Modus.
> 
> Maximaler Wert sind 999.999.999 Sekunden (über 31 Jahre)
> 
> Jeder Eintrag ist vom nächsten durch ein Komma zu separieren.
> 
> Die Zeiten sind kumulativ zu hinterlegen.
> 
> Beispiel:
> 60=>9,120=>10,180=>11
> In diesem Beispiel erhält ein User die Servergruppe 9 nach 60 Sekunden, die Servergruppe 10 nach weiteren 60 Sekunden, die Servergruppe 11 nach weiteren 60 Sekunden.

**Comment by SebSeifert** [comment]
Sorry nicht richtig gelesen. Hab ich jetzt in Handarbeit gemacht. Musste das ganze aber trotzdem von Hand in der DB abspeichern und hat das ganze wohl auch angenommen. Aber Speichern unter Kern geht nicht.
Fehlermeldung: `Wrong definition, please look at description for more details. No comma at ending!
`
Mein String den ich speichern möchte: `60=>67,43260=>68,129660=>69,302460‬=>70,475260=>71,648060=>72,820860=>73,993660=>74,1252860=>75,1512060=>76,1857660=>77,2289660‬=>78,2894460=>79,3499260=>81,4104060‬=>82,4708860=>83,5400060=>84,6091260=>85,6868860=>86,7646460=>87,8510460=>88,9460860=>89,10411260=>90,11620860=>91,12830460=>92,14040060=>93,15249660=>94,16459260=>95,17668860=>96,18878460=>97,20088060=>98,21297660=>99`

Fehlermeldung wird ab hier: `60=>67,43260=>68,129660=>69,302460‬=>70` schon angezeigt. Ohne die 70 gehts.

Gibt's eigentlich ein Script welches den String einfacher erstellen kann? Is ziemlich anstrengend zusammenzusetzen mit so vielen Gruppen.

**Comment by Shad86** [comment]
Achte darauf das auf der gesamten Seite - also eben auch in den exceptions etc.. - ich hatte mir mal ne excel tabelle gemacht - bis dato gibt es so keine alternative

**Comment by Newcomer1989** [comment]
Seit Version 1.3.4 wurde die Rankup Definition im Webinterface überarbeitet. Sie kann nun Userfreundlich erfasst werden.

![grafik](https://user-images.githubusercontent.com/11364569/71451785-fbabf500-277c-11ea-83aa-f6d031449e4d.png)
