### ISSUE TITLE
Bot Removing Wrong Server Group

### ISSUE THREAD

**Issue by HellsLegacy** [Newcomer1989/TSN-Ranksystem#68]
Hi, I own a TS3 server and I've been experiencing some problems with the rank system. I have a member server group (not the default join group) and a lot of level server groups. Every so often, the bot will remove people from the member server group for no reason. The people aren't leveling up or anything, the bot just removes member every so often. I want the bot to not remove the member group. Please help quickly, thanks!

**Comment by Newcomer1989** [comment]
Please post your rank up definition here.
And give us a hint, which group gets removed.

**Comment by CoolAAA** [comment]
Im the other owner of the server here are the ranks

Rank defentions:
http://prntscr.com/bwzckf

Server groups:
http://prntscr.com/bwze9v

**Comment by Shad86** [comment]
Hello,

i dont know if that is maybe an issue, but you are using always a new line in the "Rankup" but the instruction says:

"Each entry have to seperate from the next with a comma"

so maybe try it without a new line and only comma (without space)

regards

Shad86

**Comment by mightyBroccoli** [comment]
I am not sure if my question is fitting in this context. But i will just ask and find out. I am wondering when i have x groups set up in my rankup section, will the bot remove the "old" group and assign the "new" group or do I have to remove the "old" groups from all the users ?

**Comment by Shad86** [comment]
*Offtopic*

The Bot always remove the old rank and give then the new one

*pls always (if you'r not sure if it fits) make a new topic for your Question/s in most case thats the right decision and keeps each "issue threads" cleaner*

*Offtopic end*

**Comment by Newcomer1989** [comment]
The newline character will be the problem here, cause this will take an empty value to the array.

Like Shad86 explained, please remove this. With the new Version 1.1.0 there will be a syntax check about this field inside the webinterface. So it will be in future not possible any more to fill out it in wrong way.
