### ISSUE TITLE
There is a servergroup with ID 6 configured inside

### ISSUE THREAD

**Issue by RennatoJr** [Newcomer1989/TSN-Ranksystem#680]
Does anyone know how to solve this error?
I can't find it
http://prntscr.com/px4jwi

**Comment by Shad86** [comment]
Du hast es sogar schön eingerahmt "servergroup exception" dort ist die id 6 definiert ;)

**Comment by RennatoJr** [comment]
I searched everything and did not find, can you tell me where this option is?

**Comment by Shad86** [comment]
Oh sorry that i wrote it in german :/ - was already a little bit late yesterday.

Translated ->
> You even framed it nicely "servergroup exception" where id 6 is defined;)
