### ISSUE TITLE
 Language change

### ISSUE THREAD

**Issue by RennatoJr** [Newcomer1989/TSN-Ranksystem#681]
How to set a default language other than English?
http://prntscr.com/px5wtc

**Comment by Shad86** [comment]
"Webinterface" -> "Other"

The Red one in the middle is for a permanent change - and if you have also people that speak/read in a other language, they can  swtich by themself always with clicking on the globe  (green one - it always in the right corner)
![language-tsn](https://user-images.githubusercontent.com/18570683/68932797-a222d480-0793-11ea-806f-240487dd6a93.png)

**Comment by RennatoJr** [comment]
thank you friend
