### ISSUE TITLE
locking

### ISSUE THREAD

**Issue by RennatoJr** [Newcomer1989/TSN-Ranksystem#682]
Hello, I have a problem I would like to know if you can solve.
After a while the bot connected it hangs my hosting, all https stops working. I go to the terminal and finish php, the bot drops and returns to normal.
Can you see the logs to try to find out what's going on?

**Comment by Shad86** [comment]
For such a issue we need more then just logs.

We would also need:

OS + Version
Systemsepcs like Ram / CPU (Mhz/Ghz)

If its Linux pls also send us the output of:

`uptime`

**Comment by RennatoJr** [comment]
OS;  CLOUDLINUX 7.7
CPU Xeon 1 x 3,0GHz
Memória 3GB (1F+2V)


I only use for the bot

**Comment by Shad86** [comment]
Hm i cant guarantee that the ranksystem fully support Cloudlinux and if that's maybe an issue.

On the other side you only have 1 CPU and i don't know how much user you have on your ts3-server.

So you may could test if slowmode reduce your issue (you can find it in the Webinterface under "Teamspeak" -> "Query-Slowmode"), try it with "Middle delay (0,5seconds)" and look if you get less trouble.

**Comment by RennatoJr** [comment]
I am using on a test server, only I am logged in

**Comment by RennatoJr** [comment]
Does linux UBUNTU work well?

**Comment by RennatoJr** [comment]
The strange thing is that it only crashes the php pages, does not load.
But the bot is working normal.
But if I need to make any changes I have to finish the bot by ssh to be able to access the panel https

**Comment by Shad86** [comment]
Ubuntu should work well but as i said - i dont know if the OS is the issue or maybe the hardware power, thats why i suggested to try out the slowmode as described above

**Comment by RennatoJr** [comment]
http://prntscr.com/pys15r

still the same problem

**Comment by Newcomer1989** [comment]
You didn't answered some of our questions..
1) What is the CPU usage at the moment of the problems?
2) What is the RAM usage at the moment of the problems?
3) Logs would be helpful!
3.1) Of the Ranksystem for sure
3.2) Of the webserver
3.3) And your system as well
4) What do you mean with "it hangs the hosting"? You got any special error? On which place you got this error?
5) Are there several connections of the Ranksystem on you TS3 server at the moment of the problems?

**Comment by Newcomer1989** [comment]
Closed, since we got no response.
