### ISSUE TITLE
Bot zählt keine aktive Zeit

### ISSUE THREAD

**Issue by icemcnet** [Newcomer1989/TSN-Ranksystem#683]
**Ranksystem Version:**1.3.3

**Beschreibung:**
**1) Was hast du getan?**
Ich habe die Webseite vom Ranksystem aufgerufen und festgestellt, dass der Bot laut Fehlermeldung nicht zum Teamspeak verbunden ist. Laut Log ist er das aber und auch auf dem Teamspeak lässt der Bot sich wiederfinden. Die Fehlermeldung ist also falsch. ABER: Trotz, dass der Bot verbunden ist, wird die Onlinezeit nicht gezählt (es werden neue User erkannt und bei dem Wert "Anzahl User" hinzugefügt, jedoch bekommen diese und bestehende alte Nutzer keine neue aktive Zeit dazugerechnet)

**2) Was war deine Erwartung?**
Dass das Ranksystem funktioniert, jedoch tut es das nur zum Teil (Bot ist verbunden, zählt aber keine Onlinezeit)

**3) Was ist stattdessen passiert?**
steht oben.

**Ranksystem Log**
https://pastebin.com/B1AQicLD

**Comment by Shad86** [comment]
Könntest du mir diese Infos -> https://github.com/Newcomer1989/TSN-Ranksystem/issues/678#issuecomment-554751258 zukommen lassen

**Comment by icemcnet** [comment]
https://share.icemc.net/4876343646331ae8f849fbf1feb76514

**Comment by Shad86** [comment]
Wenn du weißt, wie du das absetzt, müsste es hiermit behoben sein:

!WICHTIG - Bitte Backup davor machen - WICHTIG!

ALTER TABLE `user` 
MODIFY COLUMN `uuid` char(50) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL FIRST,
MODIFY COLUMN `name` varchar(30) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL AFTER `count`;

Falls nicht, komm gerne auf den teamspeak ts-n.net

**Comment by icemcnet** [comment]
Auch nach erfolgreichen Ausführen ist der Fehler immer noch da :(

**Comment by Shad86** [comment]
Kannst du mir nochmal einen Screen vom Colum user schicken bitte

**Comment by icemcnet** [comment]
https://share.icemc.net/cab5c7b1e8a812f610ee2614c9a8d7d4

**Comment by Shad86** [comment]
komm mal bitte auf den Teamspeak, ich muss mir das mal genauer anschauen

**Comment by Shad86** [comment]
Folgende Probleme wurden behoben:

Fehlende php Pakete + Ordner Berechtigungen wurden gefixt

Columns wurden berichtigt

beschädigte job_check.sql wurde korrigiert

letzteres führte dann zur vollständigen Reparatur
