### ISSUE TITLE
Ständige Abstürze

### ISSUE THREAD

**Issue by R4id0n** [Newcomer1989/TSN-Ranksystem#684]
Hallo, ich habe das Problem, dass in regelmäßigen Abständen der Rankbot mir die Server Admin Gruppe entzieht(Bot läuft mit meiner Identität) und dann nacheinander so oft connected, bis der Ts keine Slots mehr frei hat. Danach stürzt er ab und ist offline.

**Comment by Shad86** [comment]
Das Ts-Ranksystem entzieht nur Gruppen die du im Ranksystem angegeben hast. 

Stelle bitte auch sicher das du das ts-n-ranksystem aus einer sicheren Quelle heruntergeladen hast (https://ts-ranksystem.com/#linux / https://ts-ranksystem.com/#windows / https://github.com/Newcomer1989/TSN-Ranksystem/archive/master.zip )

Derzeit ist die aktuellste Version (1.3.0 - Stable) überprüfe zudem sowohl das du das ganze korrekt installiert, wie auch konfiguriert hast.

> ......(Bot läuft mit meiner Identität) ....

Sollte ein Bot, egal welcher Art und sei er noch so Vertrauenswürdig, nie tun.

Für Bots im Allgemeinen sollte immer eine separate Identität verwendet werden.
