### ISSUE TITLE
 Admin & Server Admin should not receive servergroup, but still count online time

### ISSUE THREAD

**Issue by RealPwned** [Newcomer1989/TSN-Ranksystem#685]
I would like to set all users, but without Admin, Server Admin which have 2h online time, the member rank. But if I remove the server group ID of Admin and Server Admin, they will not be counted in the ranking (Time spend on TeamSpeak). How can I set that Admin and Server Admin not get the ranks, but still ranked in the ranking?

Thanks

**Comment by Shad86** [comment]
If im right you have to use this case:

![exception-tsn](https://user-images.githubusercontent.com/18570683/69638257-a2a45080-105a-11ea-99b3-15b673eaa885.png)

If you use this case, you also have to putt excepted clients on, on the stattspage
![statts-page-exceptioncase](https://user-images.githubusercontent.com/18570683/69638327-c2d40f80-105a-11ea-8bae-d040288c690b.png)

If think this should work

**Comment by Shad86** [comment]
As there is no answer after 12 days, it seems this works for you - case closed :)
