### ISSUE TITLE
Monitoring/informing about Ranksystem status/errors

### ISSUE THREAD

**Issue by zmechu** [Newcomer1989/TSN-Ranksystem#688]
Simple request :-)

Bot stops sometimes with- or without reason, no problem with that :-) But is there a way to add kind of "monitoring" feature, which inform Teamspeak Administration with sth like "Ops, Ranksystem doesn't work, seems to be stopped, check logs and restart it".

Regards!

**Comment by Shad86** [comment]
The worker.php have a Status check function.

So as in all the Install guides suggested ;) - make a Task Scheduler (windows) https://ts-ranksystem.com/#windows (point 8) or a Cronjob (Linux) https://ts-ranksystem.com/#linux (Point 7)

regards

Shad86
