### ISSUE TITLE
Ranksystem disconnects with PHP 7

### ISSUE THREAD

**Issue by Newcomer1989** [Newcomer1989/TSN-Ranksystem#69]
With PHP 7 is the package php7.0-xml required. Without this, the TS3 PHP Framework will not work correctly.

The Bot will start and bind short a connection to the teamspeak server. But it will directly disconnects.
The Ranksystem logfile will looks like this:

```
2016-07-26 22:45:42.444377   INFO      Connect to TS3 Server (Address: "your.domain" Voice-Port: "9987" Query-Port: "10011").
2016-07-26 22:45:42.444277   INFO        Ranksystem Version: 1.1.0
2016-07-26 22:45:42.443849   INFO        No newer version detected; Database check finished.
2016-07-26 22:45:42.443657   INFO      Check Ranksystem database for updates.
2016-07-26 22:45:42.435976   INFO      Initialize Bot...
```

Try to install this:
`sudo apt-get install php7.0-xml`

Its also possible you get this error message or found this in your webserver log:
`PHP Fatal error:  Uncaught Error: Call to undefined function utf8_encode() in /var/www/html/rs/ts3_lib/Helper/String.php:475`

**Comment by mightyBroccoli** [comment]
I also had this error, or I could even be the one who reported it in the first place, not sure.

It is working with the latest php Version on my Debian maschine

> Distributor ID: Debian
> Description:    Debian GNU/Linux 8.6 (jessie)
> Release:        8.6
> Codename:       jessie

> PHP 7.0.11-1~dotdeb+8.1 (cli) ( NTS )
> Copyright (c) 1997-2016 The PHP Group
> Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
>     with Zend OPcache v7.0.11-1~dotdeb+8.1, Copyright (c) 1999-2016, by Zend Technologies

I have these additional packs installed.

> php7.0                                          install
> php7.0-cli                                      install
> php7.0-common                                   install
> php7.0-curl                                     install
> php7.0-intl                                     install
> php7.0-json                                     install
> php7.0-mbstring                                 install
> php7.0-mcrypt                                   install
> php7.0-mysql                                    install
> php7.0-opcache                                  install
> php7.0-readline                                 install
> php7.0-xml                                      install
> php7.0-zip                                      install

It is possible that you need some more modules if your are not using fpm something like l`ibapache2-mod-php7.0`, but basically this should work. It works for me.

**Comment by Newcomer1989** [comment]
A check for this will come with release 1.1.2

**Comment by Newcomer1989** [comment]
release 1.1.2 is out
