### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by Acu1ty** [Newcomer1989/TSN-Ranksystem#691]
Hi i just try to install ranksystem on fresh vps but when i try to open install.php i get this "error" can you help me?

http://prntscr.com/qc9gqo

Thanks

**Comment by Newcomer1989** [comment]
You need to install PHP on your server. When you see the code in plaintext, your system environment is wrong configured.

**Comment by Acu1ty** [comment]
I just fresh install new system and follow instruction on wiki, but still same problem. Can you help me? 
System: Ubuntu 18.04
php version: http://prntscr.com/qd6t3a
php-extensions: http://prntscr.com/qd6tge

**Comment by Newcomer1989** [comment]
I guess, your webserver is wrong configured. You need to define PHP for it.

We can have a look together, if needed.. I am available on the public server now (TS: ts-n.net).

**Comment by Newcomer1989** [comment]
Solved with a reinstall of the webserver (apache).

PHP was installed after the webserver. The webserver didn't noticed the new path of PHP.
