### ISSUE TITLE
high mysql i/o

### ISSUE THREAD

**Issue by mcmufffin** [Newcomer1989/TSN-Ranksystem#692]
Moin!

zuerst vielen Dank für die Software!

Ich frage mich ob sich die mysql querries optimieren lassen?

Aktuell schreibt das System selbst bei einem kleinem Server (maximal 150 Leute) konstant mit über 1MB/s auf die SSD (bzw die MariadB). Lassen sich diese querries irgendwie optimieren?

Kenne mich mit der Programmierung nicht sonderlich gut aus, wäre es nicht aber sinnvoller die qurries erst einmal für 60 Sekunden o.ä. im Cache zu halten und erst dann auf SQL zu schreiben?
Mir scheint es etwas unnötig dass wirklich jede connected Sekunde von Clients direkt accounted und commited werden muss?! Das verursacht gerade auf SSDs IMHO nur unnötig viel wear. 

Für Input wäre ich dankbar!

**Comment by Newcomer1989** [comment]
Hey,

mit dem Gedanken haben wir auch schon öfter gespielt. Das würde aber heißen einiges am System zu ändern. Das Konzept des Ranksystems beruht von Anfang an darauf, dass die Daten immer aktuell in die DB geschrieben werden und damit im Fron-End live zur Verfügung stehen.
Ebenso ist damit gewährleistet, dass kein Datenverlust eintritt, wenn irgendetwas passieren sollte (z.B. Process-Kill, etc.). Bisher sind wir genau damit sehr gut gefahren und haben ein sehr stabiles und zuverlässiges System.

Eigentlich ist doch auch genau dafür eine DB da, oder? Natürlich können wir die Funktionen der DB nachprogrammieren, was aber Zeitaufwand darstellt, den wir nicht anderweitig nutzen können. Ebenso stellt das natürlich auch etliche Risiken/Probleme dar (s.o.).

Dein I/O Wert scheint mir auch recht hoch. Bei uns auf dem Host-System laufen über 100 Ranksystem-Instanzen neben noch diversen anderen Dingen. Dort haben wir über das volle System einen Write-Wert von ~400 KB/s. Read ist nahezu bei 0.

Ich vermute, deine DB lässt sich noch stark optimieren. Wenn du magst, können wir uns das gemeinsam mal anschauen. Komme gerne einfach mal auf dem TS bei uns vorbei (Adresse: ts-n.net)

**Comment by Newcomer1989** [comment]
Hier noch ein Link zu einem Tutorial, was wir sehr gut finden und uns auch schon bei der Optimierung der DB geholfen hat.

http://www.speedemy.com/17-key-mysql-config-file-settings-mysql-5-7-proof
