### ISSUE TITLE
Datenbank Verbindung fehlgeschlagen..

### ISSUE THREAD

**Issue by 7quit** [Newcomer1989/TSN-Ranksystem#693]
**Ranksystem Version:**
1.3.4

**Beschreibung:**
**1) Was hast du getan?**
Ich hatte das Ranksystem schon mal installiert, musste es aber wegen ein Webspace (Plesk) neu Installation Neuinstallieren, ich habe alles neu erstellt (Datenbank etc).
Ich habe alle Datenbanken und TeamSpeak Daten korrekt angegeben nur, wenn ich den Bot starten möchte, kommt folgender Fehler:  https://pastebin.com/E3XpF6Hz

**2) Was war deine Erwartung?**
Dass es eigentlicht normal starten sollte, da ich alles neu eingerichtet habe..

**3) Was ist stattdessen passiert?**
Es kam ein Fehler was ich oben schon gesagt habe.

**Ranksystem Log**
`No log entry found...
The logfile will be created with next startup.`

**Comment by Shad86** [comment]
Vermutlich fehlt das php Modul mysql -> php-mysql

**Comment by Newcomer1989** [comment]
Bitte auf die fehlenden PHP extensions achten. Für einen Windows Host sind sie z.B. hier gelistet:
https://ts-ranksystem.com/?more#windows

In deinem Fall (could not find driver) fehlt in jedem Fall PHP PDO!

**Comment by Newcomer1989** [comment]
Closed, da keine Antwort mehr kam.

**Comment by UeberDaniel** [comment]
Habe das gleiche Problem, Ja die php_pdo.dll fehlt. Die gibt es aber auch nicht mehr im ext Ordner und wird laut https://www.php.net/manual/en/pdo.installation.php bei installationen > PHP 5.3 auch nicht mehr benötigt. In meinem Fall habe ich php 7.2 und die php_pdo_mysql.dll ist in der php.ini gelisted. Bekomme aber nach dem Installieren der DB also bei "3. Configure Webinterface" die Fehlermeldung "Failed to connect to database: could not find driver", die Tabellen wurden zuvor aber erfolgreich in der DB angelegt?

**Comment by Newcomer1989** [comment]
Das klingt sehr suspekt.. Bitte schaue am besten mal in der Abendzeit bei uns auf dem Public TS vorbei (Adresse: ts-n.net). Wir können uns das dann mal näher anschauen, gerne auch per Fernwartung.

**Comment by UeberDaniel** [comment]
Es hat, als ich es nach ein paar Stunden erneut probiert hatte, auf einmal funktioniert. Keine Ahnung warum. Btw, ich hatte schonmal ein Post hier gemacht weil sich das Ranksystem (auf Windows) immer abgeschaltet hat. Dies hing mit dem Leerlauftimeout des Appools, also der Website im IIS auf welcher das Ranksystem lief. Den Wert von 20 min auf 0 min ändern und er läuft dauerhaft. Das Könntest du evtl. bei der Fehlersuche oder der Windows Checkliste ergänzen :)
![timeout](https://user-images.githubusercontent.com/10797624/76986120-8302a200-6941-11ea-923c-8b4e4b909095.jpg)

**Comment by Newcomer1989** [comment]
Ok, danke für die Info. Vermutlich hattest du die nötigen Einstellungen schon vorgenommen, musstest nur noch den Webserver-Prozess neu starten.

Das mit der Leerlauftime werde ich bei Gelegenheit noch als zusätzlichen Check aufnehmen.
