### ISSUE TITLE
Aktive Zeit wird random abgezogen

### ISSUE THREAD

**Issue by SomeNix** [Newcomer1989/TSN-Ranksystem#694]
**Ranksystem Version:1.3.5 (trat aber schon früher auf)**

**Beschreibung:**
**1) Was hast du getan?**
Das Ranksystem von Online Zeit zu Aktiver Zeit umgestellt. (Vor längerer Zeit)
Seid dem taucht das Problem immer mal wieder auf.

**2) Was war deine Erwartung?**
Das System sollte so wie davor weiterfunktionieren. 

**3) Was ist stattdessen passiert?**
Zu random Zeiten, werden Spieler einfach runtergestuft bzw. zeit abgezogen: Siehe 
```
<22:27:42> "Ranksystem": Herzlichen Glückwunsch, du bist 1 Level aufgestiegen.
Online Zeit: 83 Tag/e, 8 Stunde/n, 0 Minute/n und 2 Sekunde/n.
*** 22.12.2019
<20:20:13> "Ranksystem1": Herzlichen Glückwunsch, du bist 1 Level aufgestiegen.
Online Zeit: 83 Tag/e, 5 Stunde/n, 20 Minute/n und 6 Sekunde/n.
```

**Ranksystem Log**
Ich habe jetzt keinen spezifischen Log mehr, währenddessen es zu so einem Vorkomniss kam, da diese iwie relativ schnell gelöscht werden ...?
Und im aktuellen Log ist auch nichts komisch oder ungewöhnlich. Den Log kann ich dementsprechend noch nachreichen...

**Comment by Newcomer1989** [comment]
Anhand deiner Beschreibung kann ich leider das Problem nicht nachstellen.
Auch deine geposteten Nachrichten sind wenig hilfreich.

Wir benötigen eine ausführlichere Beschreibung und in jedem Fall eine Log, damit wir das Problem analysieren können.
