### ISSUE TITLE
Install Dont Create Database And Dont Show The Error

### ISSUE THREAD

**Issue by SeniorSpirit** [Newcomer1989/TSN-Ranksystem#696]
Hi ,
Im Using The Latest Rank System
And I Installed all requirements

but when i triyed to create a database , it dosent work  and dont show error just create box with red color :
![error](https://user-images.githubusercontent.com/44285201/72144748-46994f80-33ae-11ea-8180-f0fe044a0743.png)
Please Help Me To Fix That

Im Using Ubuntu 18.04.3 , Apache2 , php 7.2

**Comment by Newcomer1989** [comment]
What database are you using and which version of it?

Be sure, you installed the needed PHP extension (PHP-PDO) & driver for your database (https://www.php.net/manual/en/pdo.installation.php).

**Comment by SeniorSpirit** [comment]
Hi,
I Installed All of extensions ,
my database:
mysql  Ver 14.14 Distrib 5.7.28, for Linux (x86_64)

Pls explain to me more about require database drivers

**Comment by Newcomer1989** [comment]
On a Linux system you need to install,
- PHP PDO
`apt install php-pdo`
- PHP MySQL
`apt install php-mysql`

**Comment by SeniorSpirit** [comment]
Tnx For your Help , Pls add this to requirements in site : php-mysql
