### ISSUE TITLE
Fehler und Probleme nach Update

### ISSUE THREAD

**Issue by meinTS3** [Newcomer1989/TSN-Ranksystem#697]
Nach einem Restart wurde automatisch das aktuelle Update eingespielt.
Danach kam die Meldung, dass das Ranksystem lange nicht mehr aktiv gewesen sein soll obwohl es bis vor dem Update problemlos lief und auch alles korrekt verarbeitet wurde. Nun wurden alle Ränge etc. auf Stand Mitte 2019 zurück gesetzt. Seit dem läuft eine Endlosschleife in der Usern Ränge gegeben und direkt wieder weggenommen werden. Ist vielleicht bekannt, woran das liegen könnte und wie ich das fixen kann? Würde ungern nach Jahren alles resetten und neu beginnen.

**Comment by Newcomer1989** [comment]
Wir würden von deinem Ranksystem eine Log benötigen. Am besten inkl. des Update-Vorgangs und mit allem was danach passiert ist.

**Comment by meinTS3** [comment]
Da sind inzwischen (über Nacht) viele tausend Zeilen angefallen.
Kann ich euch nicht einfach Zugang geben?

**Comment by Newcomer1989** [comment]
Problem konnte gemeinsam per Fernwartung behoben werden.

Es liefen zwei Ranksystem zu gleichen Zeit. Eines aus einem Altsystem mit veralteten Werten. Daher haben beide System sich gegenseitig beeinflusst.
