### ISSUE TITLE
You don't have permission to access this resource.Server unable to read htaccess file, denying access to be safe

### ISSUE THREAD

**Issue by RealPwned** [Newcomer1989/TSN-Ranksystem#698]
Hey, ich habe gerade das RankingSystem auf einem neuen Server installiert und nachdem ich 
den installer.php ausgeführt habe, bekam ich den Fehler, dass Datei XY nicht schreibbar gewesen ist, das habe ich durch die chrown Commands behoben und danach bekomme ich direkt folgende Fehlermeldung. Das RankingSystem läuft auf einer sauberen SubDomain und es befindet sich keine .htaccess Datei im Ordner. Jemand eine Idee?

![image ](https://user-images.githubusercontent.com/44307473/72826978-33259880-3c7a-11ea-8cc2-0a82abd69006.png)

**Comment by Newcomer1989** [comment]
Bitte prüfe mal die Owner Rechte des Verzeichnisses bis zum root-Verzeichnis des Webservers hoch.

Gleiches gilt dann für Zugriffsrechte (chmod).
