### ISSUE TITLE
No maessage

### ISSUE THREAD

**Issue by CreyPer** [Newcomer1989/TSN-Ranksystem#699]
I have the following problem

If I want to verify myself, the bot does not send a token, even if someone has a level up, he gets no message. There is no error in the logs

**Comment by Newcomer1989** [comment]
Are the bot using the query user serveradmin to connect or did you created a new query account?

When you created a new account, you used a unique cliend ID for this, right? Could it be, this unique ID is a second time connected at this moment?

**Comment by CreyPer** [comment]
That worked, thank you very much

**Comment by Newcomer1989** [comment]
for documentation:

**Solution**
Create a separate unique client ID for creation of a queryaccount &
use a separate queryaccount for each single bot.
