### ISSUE TITLE
Changing the login password to the webinterface?

### ISSUE THREAD

**Issue by Spazmic** [Newcomer1989/TSN-Ranksystem#7]
Hello,

Could you please explain how to change the password that is used on webinterface login?

Thanks

**Comment by Sqveeze** [comment]
login to phpmyadmin, and look in the ranksystem's DB.

Table -> Config -> edit webuser and webpass rows.

(BTW: This script requires minimal knowledge about PHP, and stuff. Why the hell you opened 3 different and pointless issue in github? You don't even know how to script work but you can qq. Nice)

**Comment by Spazmic** [comment]
Thanks for your help, even tough you went full retard at the end :+1:

**Comment by Newcomer1989** [comment]
Or if you have no PHPMyAdmin the SQL Statement:
`update config set webpass = 'YOURPASSWORDHERE';`
