### ISSUE TITLE
AFK Time

### ISSUE THREAD

**Issue by juvcrafter** [Newcomer1989/TSN-Ranksystem#70]
Hey,
What means "Idle Time". How Long must a user be "idle" that the bot stops putting the time to "online time"?

**Comment by Shad86** [comment]
a user is idle if the idletime starts counting up so as soon as the user stops talking and writing.

**Comment by juvcrafter** [comment]
Can you make it so:
If a user isnt doing anything for 2-3 minutes, so he wont get "Online Time".

**Comment by Shad86** [comment]
> a user is idle if the idletime starts counting up, so as soon as the user stops talking and writing. 
(If you have set a delay under slowmode the count could be slightly inaccurate)

A user get no online time as soon as he is doing nothing as explained (if no slowmode is set)...

**Comment by juvcrafter** [comment]
But it is so, that if he is not talking for 5 seconds. That is sh*t.

**Comment by m0k1** [comment]
@juvcrafter This project is opensource, try to implement that at your one, don't be so rude ! 
And by the way before opening new issues try to check for older ones, your question is already discussed in #55 !

@Newcomer1989 close this and mark it as duplicate.
