### ISSUE TITLE
Password recovery if standard method not available

### ISSUE THREAD

**Issue by jusito** [Newcomer1989/TSN-Ranksystem#700]
Today I was unable to login and for an unknown reason the ranksystem wasn't able to connect to teamspeak server, so I couldn't reset the normal way.

There should be a documented workaround or a second possibility to reset the password if everything else fails. The current solution is only sufficient in most cases for this, because if the connection fails or the user handling fails its impossible to reset with this function. There should be official documentation for this, because this is the only way to ensure that it is up-to-date. If there would be an official workaround, it would also much easier and safer for less experienced people to use it.

Thanks for your time.
 
### Workaround I used for 1.3.3:
[for ppl in the next month/years check insert into command here](https://github.com/Newcomer1989/TSN-Ranksystem/blob/master/webinterface/changepassword.php#L98)
- Iam using docker for it but you can do this without too
- ContainerNameDatabase: e.g. MariaDB_RS (iam using MariaDB)
- DatabaseName: e.g. ts3_ranksystem
- DatabaseUser: e.g. root
- NewPassword: e.g. SecurePW

Generate new Password:
1. `docker run -it --rm php:7.4.2-zts-alpine` or use any php console like (http://www.writephponline.com/)
2. `echo password_hash("NewPassword", PASSWORD_DEFAULT);`
3. the output is used as NewPasswordHash

Set in database:
1. `docker run -it --network="container:ContainerNameDatabase" --rm mysql mysql -hContainerNameDatabase -uDatabaseUser -p` or start any SQL Client
2. insert password for database (currently dbconf.php contains the cleartext password)
2. `USE DatabaseName;`
3. ```INSERT INTO DatabaseName.`cfg_params` (`param`,`value`) VALUES ('webinterface_pass','NewPasswordHash') ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);```
4. done

**Comment by Newcomer1989** [comment]
Thx for your documentation and your suggestion.

We added this to the official Wiki https://github.com/Newcomer1989/TSN-Ranksystem/wiki/FAQ#reset-password-webinterface

When you are still using the version 1.3.3, please update your system! There was fixed a security issue with version 1.3.6. Current version is [1.3.7](https://ts-ranksystem.com/#download).
