### ISSUE TITLE
Bot startet normal ohne Fehlermeldung, Vergibt aber keine Ränge

### ISSUE THREAD

**Issue by PaDcOnGaming** [Newcomer1989/TSN-Ranksystem#702]
**Ranksystem Version:**
-Aktuell
**Beschreibung:**
**1) Was hast du getan?**
-Normal nach der Anleitung von xCasaTV installiert.
**2) Was war deine Erwartung?**
Funktionierendes Ranking System nach seinem Prinzip
**3) Was ist stattdessen passiert?**
Der Bot startet normal ohne Fehlermeldung. Vergibt aber keine Ränge.
**Ranksystem Log**
https://pastebin.com/8wK2rxwK

**Comment by Shad86** [comment]
Das müsste man sich mal genauer ansehen, hast du denn mal Zeit auf den ts-n.net (URL identisch) zu kommen? Ich bin so ab ca. 14Uhr am Pc.

**Comment by PaDcOnGaming** [comment]
Danke für die schnelle antwort. Habe das ganze noch einmal neuinstalliert. Nun tut er was er soll.

**Comment by Newcomer1989** [comment]
> Query-Port: "10022" SSH: "0"

Der Fehler war vermutlich hier.. Query-Port und TS3 Query encryption (=SSH) auf "off" passt nicht zusammen.

Daher zur Doku für ggfs. andere, die den gleichen Fehler haben:
Query-Port 10011 und SSH "off" oder
Query-Port 10022 und SSH "on"
