### ISSUE TITLE
Bot startet nicht mehr nach Einstellungsanpassungen

### ISSUE THREAD

**Issue by Knatterstubede** [Newcomer1989/TSN-Ranksystem#704]
**Ranksystem Version:**

**Beschreibung:**
**1) Was hast du getan?**

**2) Was war deine Erwartung?**

**3) Was ist stattdessen passiert?**

**Ranksystem Log**
_Poste einen Log vom letzten Start des Ranksystems._
_Den Log teilst du am besten z.B. mit https://pastebin.com/ (Das macht es übersichtlicher)._

**Comment by Shad86** [comment]
Gehört hierzu -> https://github.com/Newcomer1989/TSN-Ranksystem/issues/703

Loglevel war falsch eingestellt, so das der Fehler nicht direkt gefunden werden konnte ein kurzeitiges umstellen auf loglvl 6 (debug) konnte zur Problemlösung führen (Berechtigungsfehler)
