### ISSUE TITLE
Always stop

### ISSUE THREAD

**Issue by fellow25** [Newcomer1989/TSN-Ranksystem#707]
**Ranksystem Version:**
1.3.7
**Description:**
The bot stops working without displaying any error.

**Ranksystem Log**
https://pastebin.com/GcjDgH8s

**Comment by Newcomer1989** [comment]
With the debug mode there will be created an SQL file inside the logs folder
`logs/temp_sql_dump.sql`
Please share this file with us.

Is this a fresh Ranksystem installation?

Please share us also a part of the log of the startup of the Ranksystem.

**Comment by fellow25** [comment]
[temp_sql_dump.zip](https://github.com/Newcomer1989/TSN-Ranksystem/files/4333213/temp_sql_dump.zip)

**Comment by Newcomer1989** [comment]
and the two other things?

**Comment by fellow25** [comment]
[Downloads.zip](https://github.com/Newcomer1989/TSN-Ranksystem/files/4333224/Downloads.zip)

**Comment by fellow25** [comment]
https://pastebin.com/rfU1resg

**Comment by Newcomer1989** [comment]
Please try to switch to the current beta version. 

Webinterface -> Other -> Update Channel -> beta

![grafik](https://user-images.githubusercontent.com/11364569/76688790-8986d600-6630-11ea-994e-e3df4104f6b7.png)

If you do not have this option, you need to active the "expert mode" first.

![grafik](https://user-images.githubusercontent.com/11364569/76688821-c18e1900-6630-11ea-8186-d4693bff91f2.png)

**Comment by fellow25** [comment]
I test now but the version is 1.3.7 too...

**Comment by Newcomer1989** [comment]
The current beta is 1.3.8-beta-4

**Comment by fellow25** [comment]
How to update?

**Comment by Newcomer1989** [comment]
Set the beta status like described above. Restart the bot after.
Then write the Bot the command `!update`.

**Comment by fellow25** [comment]
Este cliente do ServerQuery não se registrou para eventos de mensagem de texto privada usando "servernotifyregister event=textprivate". A mensagem de texto não foi recebida.

**Comment by fellow25** [comment]
Olá, uma nova versão do Sistema de ranking está disponível!

versão atual: 1.3.7
nova versão: 1.3.8-beta-4

Confira nosso site para obter mais informações https://ts-ranksystem.com/#changelog.

iniciando o processo de atualização em segundo plano. Verifique o arquivo ranksystem.log!

But isn't updating...

**Comment by fellow25** [comment]
Hello, i have now a version 1.3.8 beta 4, but continues to stop.

*/10 * * * * sudo -u www-data php /path_to_your_webspace/path_to_the_ranksystem/worker.php check >/dev/null 2>&1

![Sem Título](https://user-images.githubusercontent.com/62182525/76739694-7d9c3080-6764-11ea-8c62-824898537cc9.png)

I need help for complete correctly the cron...

**Comment by Shad86** [comment]
`*/10 * * * *` Stands for Check every 10min.

and the second one:

` sudo -u www-data php /path_to_your_webspace/path_to_the_ranksystem/worker.php check >/dev/null 2>&1`

Here `path_to_your_webspace` and `path_to_the_ranksystem` should be replaced with the correct path to your ranksystemfolder and then the whole command should be insert into `Command`

Example could be: 
sudo -u www-data php /www/example/tsn-ranksystem/worker.php check >/dev/null 2>&1

**Comment by fellow25** [comment]
sudo -u www-data php /home/tugawarp/public_html/ranks/worker.php check >/dev/null 2>&

But stop again and dont start... :(

**Comment by Newcomer1989** [comment]
- Is `php` a valid command on your system.
- Also are you able to use `sudo -u` on this place?
- Ist `www-data` the correct user for you?

Perhaps you need to ask your hoster to clearify this questions.

Also you can ask your hoster, if they stop PHP processes like the Ranksystem, which is running continuously.

**Comment by fellow25** [comment]
Good morning, the problem is solved. Correction of the script to work with Cpanel.

**Comment by Newcomer1989** [comment]
You want to share us, what you have exactly done / changed?
This could helps other, which have the same problem.

**Comment by fellow25** [comment]
![Sem Título](https://user-images.githubusercontent.com/62182525/76913587-50a86480-68af-11ea-8447-dd53b33b1fcb.png)

The owner of the accommodation solved the problem. He said that the cpanel was not prepared for the said command.

**Comment by Newcomer1989** [comment]
Ok, then I guess, the PHP command was not available a executable command.

Thx for sharing that information!
