### ISSUE TITLE
Top user ranking bug

### ISSUE THREAD

**Issue by toster234** [Newcomer1989/TSN-Ranksystem#708]
**Ranksystem Version:**
1.3.7
**Description:**
**1) What did you do?**
I removed some hours from this user on first place
**2) What result did you get?**
The hours I deleted have disappeared, but on ranking page is bug. There is on week and month top page.
**Ranksystem Log**
https://pastebin.com/847AD8aL

**Image**
There is image or you visit my website https://ts-24.pro/ranksystem/stats/top_week.php
![image](https://user-images.githubusercontent.com/26941529/76748631-63218180-677b-11ea-9644-4b5c67f92e87.png)

**Comment by Shad86** [comment]
The ranking system always calculates back from the present 7 days (week) or 30 days (month).
In the last 7 or 30 days the user still had the time you subtracted, so he is still considered in these two statistics. So it takes up to 7 or 30 days for the statistics to be displayed correctly.

**Comment by toster234** [comment]
I expected this, but can I manually fix it? A lot of people take advantage of it, and I still have complaints about how it's possible...

**Comment by Shad86** [comment]
unfortunately, this isn't "fixable".

**Comment by toster234** [comment]
I don't want to make a new issue, but tell me about it:
![image](https://user-images.githubusercontent.com/26941529/77821479-e4b5cf80-70ea-11ea-84ea-bd536e136438.png)
[https://ts-24.pro/ranksystem/stats/list_rankup.php](https://ts-24.pro/ranksystem/stats/list_rankup.php)

Only TOP 10 users display the next group as 12

---
Config:
![image](https://user-images.githubusercontent.com/26941529/77821530-5db52700-70eb-11ea-8e4a-1a5740b9ff41.png)
