### ISSUE TITLE
[Windows] [Xampp] Can't create database

### ISSUE THREAD

**Issue by TheKinger007** [Newcomer1989/TSN-Ranksystem#709]
**Ranksystem Version:**

**Description:**
**1) What did you do?**
Installed Xampp and moved all the things into the htdocs folder

**2) What did you expect?**
Using the install.php and getting things installed :)

**3) What result did you get?**
The "install database" button still keeps greyed out even if i filled out all things
![Capturarcccc](https://user-images.githubusercontent.com/62248887/76765334-214e0680-678e-11ea-9535-22fc67efc2d0.PNG)
![Capturarsadf](https://user-images.githubusercontent.com/62248887/76765336-2317ca00-678e-11ea-85e4-94d0e3dfc3ec.PNG)
![capturefile](https://user-images.githubusercontent.com/62248887/76765338-23b06080-678e-11ea-941f-061d58f8074b.PNG)

**Ranksystem Log**
No logs as i didn't even got it started (:

**Comment by Newcomer1989** [comment]
The PHP extension [com_dotnet ](//php.net/manual/en/book.com.php) is missing.

You need to install this and try to install it again after.

**Comment by TheKinger007** [comment]
I don't think so... it's here
![ssssssddd](https://user-images.githubusercontent.com/62248887/76802396-7e1de100-67cf-11ea-9b7c-664f69f4dd84.PNG)

**Comment by Newcomer1989** [comment]
You need also to customize it inside your PHP.ini

**Comment by Newcomer1989** [comment]
Solved via remote session. Added the php_comdot to the php.ini

In case of XAMPP the PHP.ini file was found in `C:\xampp\php\php.ini`.
Added near of the other extensions the following line:
`extension=php_com_dotnet.dll`
