### ISSUE TITLE
Die exec Funktion

### ISSUE THREAD

**Issue by AgendZero** [Newcomer1989/TSN-Ranksystem#710]
Hallo,
wir haben in unseren Servern die exec-Funktion deaktiviert da diese enorme Sicherheitsrisiken bietet, jedoch ist uns aufgefallen das das TSN-System diese Funktion nutzt. Einige, vor allem qualitative Hoster deaktivieren diese Funktion ebenfalls und machen dadurch eine Nutzung des TSN nicht mehr möglich. 
Gibt es die Möglichkeit dies im nächste Update durch vergleichbare Funktionen zu ersetzen?

**Comment by Newcomer1989** [comment]
Die exec-Funktion wird benötigt, damit der Bot über das Webinterface als dauerhafter Prozess im Hintergrund gestartet werden kann.

> Gibt es die Möglichkeit dies im nächste Update durch vergleichbare Funktionen zu ersetzen?
Welche Alternative sollen wir denn deiner Meinung nach benutzen?

**Comment by AgendZero** [comment]
escapeshellarg () + escapeshellcmd()

**Comment by Newcomer1989** [comment]
Damit wird aber immer noch exec benötigt.
