### ISSUE TITLE
[TSN] Exception Groups to the Assign Servergroups

### ISSUE THREAD

**Issue by froland20** [Newcomer1989/TSN-Ranksystem#711]
Distinguish whether it refers to an existing or new feature..
 
**Existing Feature**
 
*** I am referring to the following existing feature:***

- Can you add to the TSN RankSystem the Exception Groups function department
of Assign Servergroups?
- I want to use this feature on my TeamSpeak server but I don't want that use it anyone.
- I'm attaching a file to illustrate what I want. :)
![Suggestion](https://user-images.githubusercontent.com/58860010/77776744-c601fb00-704e-11ea-8074-993e96f884ff.PNG)

Thank you,
Roland

**Comment by Shad86** [comment]
as it make sense  -> accepted

**Comment by Newcomer1989** [comment]
It is part of the current beta version - 1.3.11-beta-3
Please let use know, if this is what you are asking for.

**Comment by Shad86** [comment]
servergroup exception is added into stable. :)
