### ISSUE TITLE
Kann directory root nicht ändern ohne Fehlermeldungen zu erhalten

### ISSUE THREAD

**Issue by Kourgiantakis** [Newcomer1989/TSN-Ranksystem#712]
**Ranksystem Version: 1.3.7**

**Beschreibung:**
**1) Was hast du getan?**

Ich habe versucht, direkt den directory root von apache statt /ranksystem zu benutzen, da sonst mein reverse proxy nicht funktioniert (nutze Nginx Proxy Manager)

Also von: 
/var/www/html/ranksystem

nach 

/var/www/html/

**2) Was war deine Erwartung?**

Es sollte problemlos möglich sein, den ordner zu ändern.

**3) Was ist stattdessen passiert?**

Fehlermeldungen, weil das System wahrscheinlich nach /ranksystem sucht, anstatt nach einer Variable. Eigentlich sollte es ihm egal sein, in welchem ordner die dateien liegen, so lange die Dateistruktur beibehalten wird.

Das ist nur mein limitiertes Verständnis davon, wie es sein sollte.

Ich habe an anderer Stelle gelesen, dass man im Webinterface einfach den "Logs"-Folder ändern soll. Man kommt aber erst überhaupt nicht ins interface, wenn der Ordner nicht da ist.

![screen](https://user-images.githubusercontent.com/33792951/77906643-93434700-7288-11ea-8444-c1ff95efc803.png)

**Comment by Shad86** [comment]
Ist auch kein Problem, dennoch wird im Webinterface der logpfad festgelegt, wenn du diesen nicht anpasst kommt es dann natürlich zu diesem Problem.

Expert mode anschallten (was er laut deinen Bild wohl schon ist) und unter other anpassen. Dann kann der Ordner auch umbenannt werden oder ein anderer ort gesucht werden

**Comment by Newcomer1989** [comment]
Bitte einfach die Reihenfolge deiner Vorgehensweise wie folgt ändern.

1) Logpfad umlegen auf neues Verzeichnis
2) Dann erst das System verschieben von `/var/www/html/ranksystem` nach `/var/www/html/`

Grundlegend sollte es aber kein Thema sein, das Verzeichnis zu ändern, da die Pfade von uns relativ festgelegt sind und nicht absolut. Einzige Ausnahme ist der Logpfad, damit man diesen auch ganz woanders hinlegen kann (z.B. /var/logs/..).

**Comment by Kourgiantakis** [comment]
Ich hatte einen kleinen Denkfehler. Das beste ist es einfach den directory root von apache zu ändern.
Der neue root ist dann einfach /ranksystem statt /html.
