### ISSUE TITLE
Incorrectly displays the next group for the top ten

### ISSUE THREAD

**Issue by toster234** [Newcomer1989/TSN-Ranksystem#713]
**Ranksystem Version:**
1.3.7
**Description:**
**1) What did you do?**
I've changed the time required for the group
**2) What result did you get?**
Incorrectly displays the next group for the top ten

![image](https://user-images.githubusercontent.com/26941529/77821479-e4b5cf80-70ea-11ea-84ea-bd536e136438.png)
[https://ts-24.pro/ranksystem/stats/list_rankup.php](https://ts-24.pro/ranksystem/stats/list_rankup.php)

Only TOP 10 users display the next group as 12. If time passes, he gets the right group. Not the twelfth

---
Config:
![image](https://user-images.githubusercontent.com/26941529/77821530-5db52700-70eb-11ea-8e4a-1a5740b9ff41.png)

**Comment by Newcomer1989** [comment]
We would need your full rank definition to be able to analyze the problem.

Also, are you using the time mode 'active time' or the 'online time'?

**Comment by toster234** [comment]
The problem was solved when I added new groups. But still, nowhere was the same time to get group. I use 'online time'
