### ISSUE TITLE
Time in Seconds Accumulative

### ISSUE THREAD

**Issue by Pepreal** [Newcomer1989/TSN-Ranksystem#714]
*New Feature**
 
***1) What should this feature do?***
Give an option to count in cumulative or accumulative(not sure it this translate correct)
 
***2) Where should it be located?***
Rank settings
 
***3) What would be the benefit?***
Different way of counting the ranks levels

If it is possible i like this option so instead counting upwards from the previous level it start counting the current rank level from 0sec.

To clarify
cumulative:
rank 1: 100sec
rank 2: 150sec
So if your are rank 1 and going to rank 2 it takes 50 sec.
If its is accumulative from rank 1 to 2 its takes 150 sec

**Comment by Newcomer1989** [comment]
Like it is described on the online help:

```
The time in seconds needs to be entered cumulative!

wrong:
100 seconds, 100 seconds, 50 seconds

correct:
100 seconds, 200 seconds, 250 seconds
```

We don't want to offer additional ways to define the time. This would make it only more difficult for all parties.

You need only once time to understand it and also once a time to define it. We chose our path a long time ago. To change it now would only confuse everyone.
