### ISSUE TITLE
Löschen von einzelnen Usern oder Zeiten

### ISSUE THREAD

**Issue by Cookie4Free** [Newcomer1989/TSN-Ranksystem#718]
Die Option zum löschen einzelner User oder deren Zeiten aus der DB einfügen.
Options Möglichkeiten:
User samt Daten aus dem Ranksystem löschen, damit er erneut in diesem angelegt wird (eventuelle ausnahmeregelungen, sollen hierbei auch gelöscht werden)
User Zeiten reseten

**Comment by Shad86** [comment]
Ich gehe hier mal wie im Titel stehend auf das löschen / resetten von einzelnen User ein - ist umgesetzt und unter "Administration" zu finden.
MfG
Shad86
