### ISSUE TITLE
TS3 Icons werden nicht bei der zuweisung Angezeigt

### ISSUE THREAD

**Issue by xIrinaShaykx** [Newcomer1989/TSN-Ranksystem#722]
**Ranksystem Version:1.3.7**

Ich weiß das kommst schon zum keine Ahnung wie vielten mal, aber
ich hab keine Ahnung wie und was ich getan hatte. Als ich fertig war mit dem Einstellen 
wollte ich die Server Gruppen hinzufügen aber die Icons waren nicht geladen.
Deswegen bin ich am verzweifeln weil ich nicht weiß was ich tun soll.

Da ich das nicht selber hoste wird es schwierig mit !reloadicons

**Comment by Bealze** [comment]
get the default them with more info from ts3 site and just use the server group ids the icons will show in time unless the host is havening issues

**Comment by xIrinaShaykx** [comment]
not working at all...

**Comment by Shad86** [comment]
maybe one of this commands help you(just send it to the bot):


!reloadgroups/!reloadicons | - none - | required | Cleans the group cache.All server groups will be reloaded from the TS3 server and associated with this the group icons will be re-downloaded.Also the server icon will be re-downloaded.
-- | -- | -- | --

**Comment by Newcomer1989** [comment]
Versteh ich das Problem richtig, dass alle Servergruppen im Webinterface angezeigt werden, lediglich die zugehörigen Icons fehlen bzw. nicht angezeigt werden?

Hast du denn schon mal in die Log vom Ranksystem geschaut. Ist da ggfs. ein Fehler vorhanden.
Kannst du denn mit uns mal einen Part der Log teilen. Am besten zurück bis zum Letzten Start des Bots.

Die Log selbst am besten in ein https://pastebin.com/ legen.

**Comment by xIrinaShaykx** [comment]
Hab lang versucht irgendwie dem Bot auf Ts zu schreiben hab es endlich hinbekommen //close
