### ISSUE TITLE
Ranking wird nicht gezählt :/

### ISSUE THREAD

**Issue by TheChaosToast** [Newcomer1989/TSN-Ranksystem#724]
Eingesetzt wird die aktuelle Version 1.3.7 

Ich habe mein Ranksystem um einen Eintrag im Ranking erneuert: verifiziert. Den Standardeintrag Gast habe ich umbenannt zu unverifiziert - mit dem Hintergrund, wenn das Ranksystem mal ausfallen sollte, das neue User diesen Rang bekommen.

Den neuen Rang habe ich mit 1=>25 im Ranksystem eingetragen. Leider bekommt der User diesen Rang nicht zugewiesen. Mein Ranking ist so eingestellt, das nur aktive User bis zu 1 Sekunde gezählt werden. Der User in der Eingangszone hat Sprechverbot und nur wenn ich in einen anderen Channel switche wo man auch reden kann, dann funktioniert es.

Gibt es eine Möglichkeit das so Einzustellen, das der User auch in der Eingangshalle trotz Sprechverbot den Rang verifiziert bekommt? Oder habe ich nur einen Denkfehler?
Vielen Dank im voraus

**Comment by Newcomer1989** [comment]
Ist schwer nachzuvollziehen, da du kein Screenshot deiner Steuerungen gemacht hast und eigene Begrifflichkeiten verwendest.

Wenn ich es richtig verstehe, hast du den Parameter "Ignoriere Idle" auf 1 gesetzt.
Was passiert denn, wenn du diesem mal auf z.B. 5 Sekunden stellst?

Ansonsten, wie sehen denn eine Ausnahmeregeln aus (Rank - Ausnahmen)?

**Comment by TheChaosToast** [comment]
Hallo und danke für die schnelle Antwort. Leider hat sich bei mir der Fehlerteufel eingeschlichen. Habe falsche Einstellungen verwendet. Nun läuft es wie es soll :)

Vielen Dank :)

**Comment by Newcomer1989** [comment]
Ok, super
