### ISSUE TITLE
Installations Problem

### ISSUE THREAD

**Issue by neomlt** [Newcomer1989/TSN-Ranksystem#726]
Hallo 

Mein Problem is ziemlich exotisch,
Ich habe das Tsn_ranksystem neu installiert mit datenbank und allem seit dem habe ich das Problem das ich nix mehr konfigurieren kann wie ihr im screen sehen könnt.
![tsn](https://user-images.githubusercontent.com/26040951/80829505-91ea9e80-8be7-11ea-9eec-2fd851464fd5.PNG)

Woran könnte das liegen fehlen mir irgendwelche php extension ?
diese sind aktive genutz wird PHP 7.4.
extension=bz2
extension=curl
extension=fileinfo
extension=gd2
extension=gettext
extension=mbstring
extension=exif      ; Must be after mbstring as it depends on it
extension=mysqli
extension=pdo_mysql
extension=pdo_sqlite
extension=php_mysql.dll
extension=php_com_dotnet.dll

in der phpcommand.php  ist der Path angegeben
$phpcommand = 'C:\webserver\php\php.exe';

Grüße Neo

**Comment by Shad86** [comment]
Im Reiter Teamspeak kannst du auch nichts anlegen?

**Comment by Newcomer1989** [comment]
> Ich habe das Tsn_ranksystem neu installiert mit datenbank und allem seit dem habe ich das Problem das ich nix mehr konfigurieren kann wie ihr im screen sehen könnt.

Das klingt danach, dass du das System vorher schon genutzt hast. Wie genau hast du es denn neu installiert? Sind da noch irgendwelche Dinge (Daten) von dem alten Ranksystem vorhanden?
Oder handelt es sich hier wirklich um eine Erst-Installation?

**Comment by neomlt** [comment]
Reiter Teamspeak is auch leer

Hab von Xampp zu Maridb gewechselt alles komplett neu installiert und keine datenbank geimportet neuer Apache server ...

**Comment by Newcomer1989** [comment]
Was steht denn in der Log zum Apache (error.log), wenn du die Seite aufrufst?

**Comment by TheMimnu** [comment]
Bei mir lag es an Php 7.4 ich nutze momentan 7.0

neomlt <notifications@github.com> schrieb am Fr., 1. Mai 2020, 20:30:

**Comment by Newcomer1989** [comment]
> Bei mir lag es an Php 7.4 ich nutze momentan 7.0 

Mit PHP 7.4 gibt es da keine Probleme. Das Ranksystem ist voll kompatibel mit PHP 7.4. Wenn das geholfen hat, lag es einer fehlerhaft konfigurierten PHP Installation.

**Comment by neomlt** [comment]
[Fri May 01 20:36:13.614561 2020] [mpm_winnt:notice] [pid 1224:tid 500] AH00422: Parent: Received shutdown signal -- Shutting down the server.
[Fri May 01 20:36:15.614675 2020] [mpm_winnt:notice] [pid 4744:tid 444] AH00364: Child: All worker threads have exited.
[Fri May 01 20:36:16.426722 2020] [mpm_winnt:notice] [pid 1224:tid 500] AH00430: Parent: Child process 4744 exited successfully.
PHP Warning:  PHP Startup: Unable to load dynamic library 'php_mysql' (tried: C:/webserver/php/ext\\php_mysql (Das angegebene Modul wurde nicht gefunden.), C:/webserver/php/ext\\php_php_mysql.dll (Das angegebene Modul wurde nicht gefunden.)) in Unknown on line 0
PHP Warning:  PHP Startup: Failed to load C:/webserver/php/ext\\php_com_dotnet, Das System kann die angegebene Datei nicht finden.\r\n in Unknown on line 0
[Fri May 01 20:36:22.934094 2020] [mpm_winnt:notice] [pid 3384:tid 500] AH00455: Apache/2.4.43 (Win64) PHP/7.4.5 configured -- resuming normal operations
[Fri May 01 20:36:22.934094 2020] [mpm_winnt:notice] [pid 3384:tid 500] AH00456: Apache Lounge VS16 Server built: Apr 21 2020 16:23:13
[Fri May 01 20:36:22.934094 2020] [core:notice] [pid 3384:tid 500] AH00094: Command line: 'C:\\webserver\\Apache24\\bin\\httpd.exe -d C:/webserver/Apache24'
[Fri May 01 20:36:22.934094 2020] [mpm_winnt:notice] [pid 3384:tid 500] AH00418: Parent: Created child process 3948
PHP Warning:  PHP Startup: Unable to load dynamic library 'php_mysql' (tried: C:/webserver/php/ext\\php_mysql (Das angegebene Modul wurde nicht gefunden.), C:/webserver/php/ext\\php_php_mysql.dll (Das angegebene Modul wurde nicht gefunden.)) in Unknown on line 0
PHP Warning:  PHP Startup: Failed to load C:/webserver/php/ext\\php_com_dotnet, Das System kann die angegebene Datei nicht finden.\r\n in Unknown on line 0
[Fri May 01 20:36:23.107104 2020] [mpm_winnt:notice] [pid 3948:tid 444] AH00354: Child: Starting 64 worker threads.
[Fri May 01 20:36:31.729597 2020] [php7:error] [pid 3948:tid 968] [client 213.153.87.176:52221] PHP Fatal error:  Uncaught Error: Call to undefined function openssl_random_pseudo_bytes() in C:\\webserver\\Apache24\\htdocs\\rank2020\\webinterface\\bot.php:179\nStack trace:\n#0 {main}\n  thrown in C:\\webserver\\Apache24\\htdocs\\rank2020\\webinterface\\bot.php on line 179
[Fri May 01 20:36:33.234683 2020] [php7:error] [pid 3948:tid 968] [client 213.153.87.176:52223] PHP Fatal error:  Uncaught Error: Call to undefined function openssl_random_pseudo_bytes() in C:\\webserver\\Apache24\\htdocs\\rank2020\\webinterface\\ts.php:46\nStack trace:\n#0 {main}\n  thrown in C:\\webserver\\Apache24\\htdocs\\rank2020\\webinterface\\ts.php on line 46, referer: http://46.4.96.134/rank2020/webinterface/bot.php

**Comment by Newcomer1989** [comment]
Joa, da stehen doch genau die Dinge drin, die ich dir eben geschrieben habe.. daher noch einmal.

> Außerdem passe bitte mal die beiden folgenden Dinge in der php.ini an:
> 
>     extension=php_mysql.dll ist redundant. Bitte diese Zeile löschen
>     extension=php_com_dotnet.dll ändern auf extension=com_dotnet
> 
> Danach am besten den Webserver auch mal neu starten.

**Comment by neomlt** [comment]
[Fri May 01 20:50:01.832932 2020] [mpm_winnt:notice] [pid 2144:tid 500] AH00424: Parent: Received restart signal -- Restarting the server.
[Fri May 01 20:50:01.861934 2020] [mpm_winnt:notice] [pid 2144:tid 500] AH00455: Apache/2.4.43 (Win64) PHP/7.4.5 configured -- resuming normal operations
[Fri May 01 20:50:01.861934 2020] [mpm_winnt:notice] [pid 2144:tid 500] AH00456: Apache Lounge VS16 Server built: Apr 21 2020 16:23:13
[Fri May 01 20:50:01.861934 2020] [core:notice] [pid 2144:tid 500] AH00094: Command line: 'C:\\webserver\\Apache24\\bin\\httpd.exe -d C:/webserver/Apache24'
[Fri May 01 20:50:01.861934 2020] [mpm_winnt:notice] [pid 2144:tid 500] AH00418: Parent: Created child process 6176
[Fri May 01 20:50:02.832990 2020] [mpm_winnt:notice] [pid 6176:tid 444] AH00354: Child: Starting 64 worker threads.
[Fri May 01 20:50:03.833047 2020] [mpm_winnt:notice] [pid 4300:tid 444] AH00364: Child: All worker threads have exited.
[Fri May 01 20:57:19.437962 2020] [php7:error] [pid 6176:tid 1000] [client 213.153.87.176:52360] PHP Fatal error:  Uncaught Error: Call to undefined function openssl_random_pseudo_bytes() in C:\\webserver\\Apache24\\htdocs\\rank2020\\webinterface\\bot.php:179\nStack trace:\n#0 {main}\n  thrown in C:\\webserver\\Apache24\\htdocs\\rank2020\\webinterface\\bot.php on line 179, referer: http://46.4.96.134/rank2020/webinterface/
[Fri May 01 20:57:21.060055 2020] [php7:error] [pid 6176:tid 1000] [client 213.153.87.176:52360] PHP Fatal error:  Uncaught Error: Call to undefined function openssl_random_pseudo_bytes() in C:\\webserver\\Apache24\\htdocs\\rank2020\\webinterface\\bot.php:179\nStack trace:\n#0 {main}\n  thrown in C:\\webserver\\Apache24\\htdocs\\rank2020\\webinterface\\bot.php on line 179, referer: http://46.4.96.134/rank2020/webinterface/bot.php
[Fri May 01 20:57:21.430076 2020] [php7:error] [pid 6176:tid 1000] [client 213.153.87.176:52360] PHP Fatal error:  Uncaught Error: Call to undefined function openssl_random_pseudo_bytes() in C:\\webserver\\Apache24\\htdocs\\rank2020\\webinterface\\ts.php:46\nStack trace:\n#0 {main}\n  thrown in C:\\webserver\\Apache24\\htdocs\\rank2020\\webinterface\\ts.php on line 46, referer: http://46.4.96.134/rank2020/webinterface/bot.php
[Fri May 01 20:57:22.393131 2020] [php7:error] [pid 6176:tid 1000] [client 213.153.87.176:52360] PHP Fatal error:  Uncaught Error: Call to undefined function openssl_random_pseudo_bytes() in C:\\webserver\\Apache24\\htdocs\\rank2020\\webinterface\\ts.php:46\nStack trace:\n#0 {main}\n  thrown in C:\\webserver\\Apache24\\htdocs\\rank2020\\webinterface\\ts.php on line 46, referer: http://46.4.96.134/rank2020/webinterface/ts.php

extension=bz2
extension=curl
;extension=ffi
;extension=ftp
extension=fileinfo
extension=gd2
extension=gettext
;extension=gmp
;extension=intl
;extension=imap
;extension=ldap
extension=mbstring
extension=exif      ; Must be after mbstring as it depends on it
extension=mysqli
;extension=oci8_12c  ; Use with Oracle Database 12c Instant Client
;extension=odbc
;extension=openssl
;extension=pdo_firebird
extension=pdo_mysql
;extension=pdo_oci
;extension=pdo_odbc
;extension=pdo_pgsql
extension=pdo_sqlite
;extension=pgsql
;extension=shmop
extension=com_dotnet

sollten jetzt so passen 

Nach restart des server ist das fenster denoch Schwarz

**Comment by Newcomer1989** [comment]
Da müsste dann noch eine weitere Extension aktiviert werden, welche wohl eigentlich Standard ist.

extension=php_openssl.dll

**Comment by neomlt** [comment]
Ja Wunderbar vielen Dank @Newcomer1989 bin halt nicht so in der materie drin,

wie kann ich nun am besten die alten daten importieren ?

**Comment by Newcomer1989** [comment]
Kein Problem. Der Check fehlt wohl auch noch im System. Werde ich dann noch aufnehmen.

Schau mal in unserem Wiki, dort haben wir eine kurze Anleitung für eine Relokation hinterlegt:
https://github.com/Newcomer1989/TSN-Ranksystem/wiki/FAQ#changed-teamspeak-host--server---mitigation-old-ranksystem
