### ISSUE TITLE
Datenschutz

### ISSUE THREAD

**Issue by mrkillertoast** [Newcomer1989/TSN-Ranksystem#728]
**Neue Funktion**
 
***1) Was sollte dieses Feature tun?*****
Eine Einstellung um ein Impressum und ein Datenschutz Text für das Rangsystem zu integrieren

***2) Wo soll es sich befinden? *****
Ich denke am besten wäre wenn es im Backend eine Neue Gruppe Datenschutz(o. ä.) geben würde und auf dem Frontend unterhalb der Ranksystem info einen neunen Punkt Impressum & Datenschutz,
 
***3) Was wäre der Nutzen?*****
Das Ranksystem könnte als eigenständige Seite agieren und der Betreiber könnte sich so vor abmahnugen schützen.

**Comment by robotter112** [comment]
Ja das wäre schon echt ein wichtiges feature.

**Comment by NickSlowinski** [comment]
Ich arbeite derzeitig an einer Lösung für @robotter112 und werde diese dann auch mit einem Pull-Request veröffentlichen.

Es ist ein Gefallen für ihn, deswegen werde ich es vorerst nur funktional umsetzen (siehe unterhalb).
Wie ich es umsetzen werde:
Auf jeder öffentlichen Seite wird ein kleiner Footer am Seitenende eingefügt mit den entsprechenden Links zum Impressum und zur Datenschutzerklärung. Im Backend können diese entsprechend eingetragen werden, dabei ist aber die Datenschutzerklärung nicht mehrsprachig angedacht, sondern als einfache Schreibbox (ähnlich wie die Server News).
Eventuell liefere ich den Text für eine deutsche Datenschutzerklärung mit, welche aber noch geringfügig angepasst werden muss zwecks Logging vom Webserver, ob selbst gehostet oder bei einem Anbieter, etc.

Je nachdem wie bei mir die persönlichen Termine klappen, könnte das morgen früh oder Sonntag Abend fertig sein.
