### ISSUE TITLE
I can't message the RankSystem

### ISSUE THREAD

**Issue by Ykaru19** [Newcomer1989/TSN-Ranksystem#729]
**Ranksystem Version:**

**Description:**
**1) What did you do?**
I set up the ranks, and the bot is working, he's giving ranks . But i can't message him with !nextup, !help etc..
All is working, only this thing is not, what should I do, step by step, please..

**Ranksystem Log**
_Add a Ranksystem-Log extract of the last startup._
_You can also use https://pastebin.com/ for this and share us the link._

**Comment by Ykaru19** [comment]
It gives me the rank i set but the commands dont work.

**Comment by Newcomer1989** [comment]
How did you create the query login for the Ranksystem?
About the TS3 Client -> Tools -> ServerQuery Login?
Then the Ranksystem Bot might also use the same unique Client ID like yours. That would explain the problem.

You need to create a new unique Client ID, which will be used for the Ranksystem only.
For this do the following:
1) Create a new unique Client ID -> TS3 Client -> Tools -> Identity (CTRL + I)
2) Join with the new unique Client ID:
      - TS3 Client Connection dialog with -> "more". Then there appears a field with "Identity".
      - Choose the new one and connect with.
3) Give the new unique Client ID the needed permissions on the TS3 server
4) Create the query login -> Tools -> ServerQuery Login.
5) Enter the new query credentials inside the Ranksystem Webinterface

Use this unqiue Client ID only for the Ranksystem Bot. You musn't use this to connect to the TeamSpeak.

**Comment by Ykaru19** [comment]
Ok, I did that, now I can message him with !nextup etc ..
But only my group can do that. And is the biggest group, other cant

**Comment by Shad86** [comment]
Then i would say its to 99% an Permission issue, so maybe other people or the bot itself hasn't enough "i_client_private_textmessage_power"
