### ISSUE TITLE
RankingSystem start via Linux command? 

### ISSUE THREAD

**Issue by RealPwned** [Newcomer1989/TSN-Ranksystem#736]
Hey,
ist es möglich das Ranking System via Linux cmd (putty) zu starten?
denn ich habe das Problem, dass der "Bot" nach einiger Zeit einfach disconnectet...
ich möchte das sofern es geht gerne den Bot alle 12-24h per Cronjob neustarten lassen.

LG.

**Comment by Shad86** [comment]
Hallo,

in unserer Installationsanleitung unter Punkt 7) sollte die Lösung zu deinem Problem sein:

https://ts-ranksystem.com/#linux
