### ISSUE TITLE
deactivable Max-Slots - Server-Graph

### ISSUE THREAD

**Issue by UeberDaniel** [Newcomer1989/TSN-Ranksystem#737]
Wie schon beschrieben wäre es sinnvoll wenn jenes Diagramm mit der eigentlichen Nutzung des Servers skalieren würde und eben von dem Höchststand (oder Max. Channels je nach dem) und nicht der maximalen Serverkapazität ausgehen würde.
![Anmerkung 2020-06-05 185559](https://user-images.githubusercontent.com/10797624/83903491-864a4480-a75e-11ea-86d4-ca66b5b283b0.png)

**Comment by Newcomer1989** [comment]
Eine Autoskalierung ist bereits enthalten bzw. macht der Graph schon.

Was du möchtest, ist ein schon von anderer Seite herangetragener Wunsch, die Max-Slots auszublenden.
Genau das ist bereits auf unserer Todo-Liste und wird mit einem der nächsten Versionen kommen.

**Comment by Newcomer1989** [comment]
Ist bereits mit Release 1.3.11 umgesetzt worden.
