### ISSUE TITLE
verification-channel ID?

### ISSUE THREAD

**Issue by Marcel40625** [Newcomer1989/TSN-Ranksystem#738]
**Ranksystem Version:** 1.3.7

**Description:** The Verification link uses cid 2621, but i havent set it anywhere in the webinterface and dont know how to change it, cant find any option, even in pro mode, only found the channel id setting for the bot itself and its set to cid 10

**Comment by Newcomer1989** [comment]
You can edit this inside the Webinterface -> Stats page -> Verification-Channel
To be able to see this field you need to enable the expert mode.

**Comment by lgund** [comment]
I couldn't find this tree. Expert mode is on. Version of the interface 1.3.12

![image](https://user-images.githubusercontent.com/13957661/94864330-19109c80-043c-11eb-8cf9-812249342bab.png)

**Comment by Newcomer1989** [comment]
We moved it with one of the last versions.

Have a look to Webinterface -> Stats page -> General (Stats)

![grafik](https://user-images.githubusercontent.com/11364569/94869390-9096f980-0445-11eb-8ba5-9e511be84c83.png)
