### ISSUE TITLE
Bot crashed

### ISSUE THREAD

**Issue by enyonyelison** [Newcomer1989/TSN-Ranksystem#739]
the system is stopping working after a while, he asks me for this permission, but I already put it, and even so he bugged
as print:
![image](https://user-images.githubusercontent.com/13843354/84170975-a4f75680-aa50-11ea-811a-e1c7eeed1f02.png)
![image](https://user-images.githubusercontent.com/13843354/84171017-b2acdc00-aa50-11ea-895d-ea4a70e5a3b4.png)

**Comment by Newcomer1989** [comment]
Did you changed something with your teamspeak server?

Like a restore of a TS3 server snapshot or
a migration to a new (TS / host) server or 
restoring an backup or
anything like that?

**Comment by enyonyelison** [comment]
> Did you changed something with your teamspeak server?
> 
> Like a restore of a TS3 server snapshot or
> a migration to a new (TS / host) server or
> restoring an backup or
> anything like that?

yes, more time

**Comment by Newcomer1989** [comment]
You would like to describe, what you did and when?
To be able to help you, we need a bit more feedback / information.

**Comment by enyonyelison** [comment]
> You would like to describe, what you did and when?
> To be able to help you, we need a bit more feedback / information.

just did a normal backup on yatqa
![image](https://user-images.githubusercontent.com/13843354/84179361-34563700-aa5c-11ea-921a-f6a2f4aa0f18.png)

**Comment by Newcomer1989** [comment]
..and when did you used this last? Before you get the error above?

I guess, with restoring a snapshot the database IDs changed.
Please have a look to this FAQ article. Espeacially to the point 4
I guess, this overwrites the client database ID

**Comment by enyonyelison** [comment]
> ..and when did you used this last? Before you get the error above?
> 
> I guess, with restoring a snapshot the database IDs changed.
> Please have a look to this FAQ article. Espeacially to the point 4
> I guess, this overwrites the client database ID

where I see the faq?

**Comment by enyonyelison** [comment]
I did the entire group ID selection again in the system. and yet the error still persists

**Comment by Newcomer1989** [comment]
sorry, I fotgot the link
https://github.com/Newcomer1989/TSN-Ranksystem/wiki/FAQ#changed-teamspeak-host--server---mitigation-old-ranksystem

**Comment by Newcomer1989** [comment]
I guess, it is a problem with restoring the server snapshot. Nevertheless, it would be nice if our answer our question of "when you did this?" The time relation between the restoring and the appearing of the error is still not clear.

We would also need a full log of the Ranksystem to be able to analyze the problem further.

**Comment by enyonyelison** [comment]
[ranksystem.log](https://github.com/Newcomer1989/TSN-Ranksystem/files/4794805/ranksystem.log)
follow the server log

**Comment by Newcomer1989** [comment]
That isn't a full log of the Ranksystem.
We need a log, which contatins the startup of the Ranksystem, the problem you reported and all what between happened.

**Comment by enyonyelison** [comment]
the log is very long, but I took the part that it crashed, then start it again after a while, it stops again.
[ranksystem.log](https://github.com/Newcomer1989/TSN-Ranksystem/files/4794944/ranksystem.log)

**Comment by Newcomer1989** [comment]
Which server is this?

2020-06-17 16:50:20.178796   INFO        TS3 Server version: 1.4.14 on Linux [Build: 1590409357 from 2020-05-25 09:22:37]

**Comment by Newcomer1989** [comment]
Seems to be, you are using TeaSpeak.

Could you connect to our public server -> TS: ts-n.net
Would be much easier instead of asking all things here on github.

**Comment by Newcomer1989** [comment]
Closed due no response
