### ISSUE TITLE
Top users category excluding users

### ISSUE THREAD

**Issue by mightyBroccoli** [Newcomer1989/TSN-Ranksystem#74]
I have set up the bot, and it is working correctly and without problems. Just some minor problems with the webinterface. 
We are a really old teamspeak with some users above 1k hours active. But with the new bot some groups got removed so I excluded users in somegroups from the ranking up system. 
But the problem is when users are excluded from rankup they are also excluded from the TopUsers Category and that is not how I intended. 
2 questions 
Is is possible to fix that and second is this even intended?

**Comment by Shad86** [comment]
I tested it also to exclude a client-id and even if excepted Groups are enabled under Style settings

https://puu.sh/qrSnx/feeb41901b.jpg

i dont see the guy anymore he just disappears in all rankups also in the "list rankup"

**Comment by mightyBroccoli** [comment]
any news ?

**Comment by mightyBroccoli** [comment]
any infos from @Newcomer1989 ?

**Comment by Newcomer1989** [comment]
The main problem seems that user got removed out of their servergroups. I think we should solve this, then you musn't exclude it from ranking and they will be back on top lists etc...

How looks your rankup definition? Can you make a screenshot from core defintions out of the webinterface, that would be helpful?!

**Comment by mightyBroccoli** [comment]
Yes the main problem is that my server is a really old server, with many ppl in a specific group in my case group 7, ppl came up to me to add some kind of apprentice group ( in my case 41) for new members. 
The problem is that group 7 was not excluded in getting group 41.
I achived this by excluding group 7 from rankup.
![2016-08-14 15_01_06-mightybroccolis s mighty stats page](https://cloud.githubusercontent.com/assets/14238117/17649248/171a3bd2-6230-11e6-8b6e-d2f8db368fe7.png)

**Comment by Newcomer1989** [comment]
Ok, when I understand it correct.. The TeamSpeak is older then the Ranksystem. So you given some ppl group 7 manual. Now the Ranksystem don't know of the activity before and let them begin with group 41 (remove group 7). This is right?

Then the solution is, that you have to give all that ppl at least the needed time for group 7. This you can do inside the webinterface. If you did this for all remove the group 7 from exclusion and all will be good ;-)
