### ISSUE TITLE
BOT is stopped. BOT stoppt nach dem Start/Restart sofort?

### ISSUE THREAD

**Issue by JonaxGames** [Newcomer1989/TSN-Ranksystem#743]
**Beschreibung:**
**1) Was hast du getan?**
Ich habe wie beschrieben das Webinterface versucht zu installieren. Ich habe meinen ts3 serveradmin account verknüpft. Sobald ich den bot starten möchte, bricht er ab und zeigt mir bot is stopped. 
**2) Was war deine Erwartung?**
Ich habe bereits 2 cleane Neuinstallationen gemacht. Hat leider nicht geholfen. Außerdem habe ich mehrmals auf verschiedenen Wegen meine Datenbank verknüpft. Zwischen den Server ist keine Firewall. Datenbank/Webinterface/Teamspeak sind lokal
**3) Was ist stattdessen passiert?**
Keine Fehlermeldung. BOT stoppt nachdem ich ihn starten möchte.
4) Mein System:
- Debian 10
- Maria DB / PHPMyAdmin
- Teamspeak Version: 3.12.1
- Apache2

**Ranksystem Log**
[ranksystem.log](https://github.com/Newcomer1989/TSN-Ranksystem/files/4808666/ranksystem.log)

**Comment by Newcomer1989** [comment]
Bitte mal direkt die 1.3.8 herunterladen und diese installieren.

https://ts-ranksystem.com/#download

**Comment by JonaxGames** [comment]
> Bitte mal direkt die 1.3.8 herunterladen und diese installieren.
> 
> https://ts-ranksystem.com/#download

leider kein erfolg. Ich habe die Zip-Datei heruntergeladenen --> entpackt --> Rechte vergeben --> DB angelegt --> DB eingetragen --> teamsepak login eingetragen --> bot gestartet 
[ranksystem.log](https://github.com/Newcomer1989/TSN-Ranksystem/files/4808678/ranksystem.log)

**Comment by Newcomer1989** [comment]
das ist immer noch die Version 1.3.7
> 2020-06-21 00:56:51.201936   NONE      Ranksystem Version: 1.3.7 (on Update-Channel: stable)

Bitte darauf achten, dass du die ZIP-Datei von unserer Seite lädst und diese auch wirklich neu heruntergeladen bzw. lokal überschrieben wird.

Wenn du in die install.php schaust, siehst du ganz oben, ob es die 1.3.7 oder die 1.3.8 Sourcen sind.

**Comment by JonaxGames** [comment]
Wo kann ich die Version 1.3.8 direkt herunterladen? Ich habe diese Version nicht in den Releases auf Github gefunden, wenn ich auf der tsn Webseite, download lastest anklicke, lädt er mir automatisch die  1.3.7 herunter.

**Comment by Shad86** [comment]
Hallo,

gerade mal überprüft:

https://ts-ranksystem.com/#download <--- dort wird 1.3.8 heruntergeladen

MfG

Shad86

**Comment by JonaxGames** [comment]
Habe die Zip-Datei gerade neu heruntergeladen. In der install.php zeigt er mit die Version 1.3.7
![image](https://user-images.githubusercontent.com/48924461/85222528-1ffb2e00-b3bc-11ea-9c7a-0347ee6e0516.png)

**Comment by Shad86** [comment]
Wie schon darauf hingewiesen wurde:

> Bitte darauf achten, dass du die ZIP-Datei von unserer Seite lädst und diese auch wirklich neu heruntergeladen bzw. lokal überschrieben wird.

Ich habe es gerade eben vor 5 min versucht, kann also nicht sein, das ich die neue und du nach mir dann die alte version lädst.

Säubere mal deinen Download ordner und lade es erneut herunter, da muss irgend ein Fehler auf deiner Seite liegen, da wie ich bereits sagte, es nicht sein, kann das wenn du 3 min nach mir die datei herunter lädst, von der mir angegeben Seite, das du eine ältere Version lädst als ich.

Auch sicherstellen, das du nicht irgendwelche Cache tools im Broswer nutzt, die eventuell eine Seiten version anzeigen, die viel zu alt ist.

**Comment by JonaxGames** [comment]
> Wie schon darauf hingewiesen wurde:
> 
> > Bitte darauf achten, dass du die ZIP-Datei von unserer Seite lädst und diese auch wirklich neu heruntergeladen bzw. lokal überschrieben wird.
> 
> Ich habe es gerade eben vor 5 min versucht, kann also nicht sein, das ich die neue und du nach mir dann die alte version lädst.
> 
> Säubere mal deinen Download Ordner und lade es erneut herunter, da muss irgend ein Fehler auf deiner Seite liegen, da wie ich bereits sagte, es nicht sein, kann das wenn du 3 min nach mir die Datei herunter lädst, von der mir angegeben Seite, das du eine ältere Version lädst als ich.
> 
> Auch sicherstellen, das du nicht irgendwelche Cache tools im Browser nutzt, die eventuell eine Seiten version anzeigen, die viel zu alt ist.

Sehr komisch, aber scheint nun zu funktionieren. Die Schritte, die du mir erklärt hast habe ich bereits getan, es war trotzdem nicht möglich die Datei herunterzuladen. Ich werde mir das mal etwas genauer ansehen. Habe nun einen anderen PC genutzt und damit die Zip heruntergeladen. Nun läuft der bot bisher ohne Probleme.

Viele Dank und Grüße,
Jonax
