### ISSUE TITLE
permisison issue 

### ISSUE THREAD

**Issue by cptmacp** [Newcomer1989/TSN-Ranksystem#744]
version :- 1.3.8

I cant setup the bot 

i was running but it gives error 

"
You need to correct the owner and access permissions of the named files/folders!

The owner of all files and folders of the Ranksystem installation folder must be the user of your webserver (e.g.: www-data).
On Linux systems you may do something like this (linux shell command):
chown -R www-data:www-data /opt/lampp/htdocs/ftp/rn

Also the access permission must be set, that the user of your webserver is able to read, write and execute files.
On Linux systems you may do something like this (linux shell command):
chmod -R 640 /opt/lampp/htdocs/ftp/rn

"
 tried running as normal user and as root 
both giving same error 

also what does this mean?

"The owner of all files and folders of the Ranksystem installation folder must be the user of your webserver (e.g.: www-data)."

webserver ? as in the vps user ? as in the login user i use?

**Comment by cptmacp** [comment]
fixed it 

thanks

**Comment by Bealze** [comment]
what changed i to now get 2020-06-21 11:45:06.096919   CRITICAL      Could not save new update. Please check the permissions for folder 'update'.  but the zip is in there?
