### ISSUE TITLE
Bot shutting down after a few seconds - No Errors

### ISSUE THREAD

**Issue by xSpiriTxx** [Newcomer1989/TSN-Ranksystem#746]
**Ranksystem Version:**
1.3.7

**Description:**
**1) What did you do?**
start the bot

**2) What did you expect?**
that the bot starts

**3) What result did you get?**
the bot shuts down after a few seconds

**Ranksystem Log**
_Add a Ranksystem-Log extract of the last startup._
_You can also use https://pastebin.com/ for this and share us the link._
![rankbot_log](https://user-images.githubusercontent.com/36414837/85379937-9d4dac80-b53c-11ea-9422-e03d176658f0.png)

**Comment by Newcomer1989** [comment]
Is it a fresh installation?

You are writing Ranksystem Version 1.3.7 but log says 1.3.8. Where did you seen the version 1.3.7?

Are you getting any errors / info messages on login page of the webinterface?

**Comment by xSpiriTxx** [comment]
I reinstalled the bot but it keeps stopping.

Sorry I downloaded both versions. But I installed the ranksystem_lastest. so its 1.3.8

The only notification I get when I am on the login page is that I should use the webinterface only via HTTPS.

**Comment by bykidi** [comment]
I'm also getting the same on my instance. Latest PHP, latest ranksystem, latest server. No errors. Ranksystem crashes (bot loses connection) a second or less after the start/check command.

No errors... even with debug mode...
Can provide the remote access if needed.

**Comment by xSpiriTxx** [comment]
Here I have a screenshot of the debug mode log. Maybe this helps. 

![image](https://user-images.githubusercontent.com/36414837/85615829-1f34f700-b65d-11ea-9c12-c7691bf380a3.png)

**Comment by xSpiriTxx** [comment]
I finally found an error while installing the bot

![image](https://user-images.githubusercontent.com/36414837/85621111-0d575200-b665-11ea-8328-232c0a021cca.png)

**Comment by Newcomer1989** [comment]
> I reinstalled the bot but it keeps stopping.
> 
> Sorry I downloaded both versions. But I installed the ranksystem_lastest. so its 1.3.8

Since it is a fresh installation. Please be sure, your are not downloading the version 1.3.7.
Download our latest version 1.3.8 here -> https://ts-ranksystem.com/#download

To check, you are using the version 1.3.8, you can have a look into the `install.php`. On top you see the version inside the sources.

**Comment by xSpiriTxx** [comment]
I dont know how but when I installed the bot I used a other server query login and now it works thanks,
