### ISSUE TITLE
Error while removing group: empty result set

### ISSUE THREAD

**Issue by djalmasi** [Newcomer1989/TSN-Ranksystem#747]
**Ranksystem Version:**

**Description:**
**1) What did you do?**
Updating to the new version (1.3.8)
**2) What did you expect?**
To work well
**3) What result did you get?**
The bot always adding and removing the assign group and flooding.
**Ranksystem Log**
_Add a Ranksystem-Log extract of the last startup._
_You can also use https://pastebin.com/ for this and share us the link._

2020-06-23 21:12:35.928069   ERROR     addon_assign_groups:2563: Error while removing group: empty result set
2020-06-23 21:12:34.213456   ERROR     addon_assign_groups:2563: Error while removing group: empty result set
2020-06-23 21:12:32.526989   ERROR     addon_assign_groups:2563: Error while removing group: empty result set
2020-06-23 21:12:30.918115   ERROR     addon_assign_groups:2563: Error while removing group: empty result set

**Comment by Newcomer1989** [comment]
We would need a full log of the Ranksystem since the last startup of it.

**Comment by djalmasi** [comment]
I just only can this - https://pastebin.com/VZGs3F3j
No more at the log file

**Comment by Newcomer1989** [comment]
Are you using official TeamSpeak server or a TeaSpeak?

**Comment by djalmasi** [comment]
Official TeamSpeak

**Comment by djalmasi** [comment]
Here is the full log: http://bot.djalmasi.hu/alma/logsranksystem.log

**Comment by djalmasi** [comment]
https://bot.djalmasi.hu/alma/logsranksystem.log
https://bot.djalmasi.hu/alma/bot.log
https://bot.djalmasi.hu/alma/level-6.log

**Comment by Newcomer1989** [comment]
Can you have a look, you have entries in the `addon_assign_groups` table?
`SELECT * FROM addon_assign_groups;`

If yes, you can try to delete this manually.
`DELETE FROM addon_assign_groups;`

Normally, this happens due adding / removing the groups by the system.
The real problem might be another one and not the addon function.
To get more information we would need a debug log, at the time, the error occurs. I can't find this error inside your level-6 log.

**Comment by Ultrashadow** [comment]
So this solves the problem but only temporarily. Could you tell me where to find the log informations you need to take a closer look?

**Comment by Newcomer1989** [comment]
Do you have this problem still with the current beta version? -> 1.3.10-beta-5

**Comment by Ultrashadow** [comment]
seems to be fixed, thanks

**Comment by Newcomer1989** [comment]
@djalmasi Do you have this problem still with the current version? -> 1.3.10

**Comment by djalmasi** [comment]
Unfortunately, I can't answer that. In the meantime, my server that had been running for two years was down. TeamSpeak abolished my license.

**Comment by Newcomer1989** [comment]
That's bad to hear.

Then we close this issue. If your state changes and you still got this problem again, feel free to reopen it.
