### ISSUE TITLE
Store new BUG again and again

### ISSUE THREAD

**Issue by djalmasi** [Newcomer1989/TSN-Ranksystem#748]
**Ranksystem Version:**

**Description:**
**1) What did you do?**
Updating to the new version (1.3.8)
**2) What did you expect?**
To work well
**3) What result did you get?**
Every time I restart the bot it always floods it.
**Ranksystem Log**
_Add a Ranksystem-Log extract of the last startup._
_You can also use https://pastebin.com/ for this and share us the link._

2020-06-23 21:56:41.316083   NOTICE        Store new cldbid 6632 for client (uuid: 6wg0ULYh+hcslP94Vu5rOfsBEAQ= old cldbid: 114123)
2020-06-23 21:56:41.315793   NOTICE      Client (uuid: 6wg0ULYh+hcslP94Vu5rOfsBEAQ= cldbid: 114123) known by the Ranksystem changed its cldbid. New cldbid is 6632.

Again and again and again and never stop it, if i restart, starts from the beginning

**Comment by Newcomer1989** [comment]
Also here, we would need a full log of the Ranksystem, since the last startup of it.

Please also change the log-level (Webinterface -> Other -> Log-Level) to "6- Debug" before.

**Comment by djalmasi** [comment]
https://pastebin.com/HjCtpEZw

**Comment by Newcomer1989** [comment]
> 2020-06-24 01:23:00.048435   NONE        Log Level: 5 - INFO

Please also change the log-level (Webinterface -> Other -> Log-Level) to "6- Debug" before.

**Comment by djalmasi** [comment]
I dont know how! The Debug has turned on

**Comment by djalmasi** [comment]
https://bot.djalmasi.hu/alma/logsranksystem.log
https://bot.djalmasi.hu/alma/bot.log
https://bot.djalmasi.hu/alma/level-6.log

**Comment by Newcomer1989** [comment]
All looks fine. The client-database-IDs are not repeating. Each line is a new client-database-ID.

Seems to be, you were changing anything with your TS server, that the database IDs are changing; like a deployment of a server-snapshot. This could be also done a long time before.
In result you are getting double entries of the client-database-IDs inside the Ranksystem database. This will repair itself over time, when the user connects to your server and get the new client-database-ID on your TeamSpeak server. The Ranksystem will update it.
The problem are clients, which are longer not seen on the TeamSpeak server. They will stay with an old client-database-ID inside the Ranksystem database. It could be, there is a current user which has the same client-database-ID; they overlap.

New is, we are using the client-database-ID with version 1.3.8 of the `user_snapshot` table (resource / performance reasons).
We enabled a repair mode, you can see in the logfile, which sets it to virtual client-database-IDs. The existing TeamSpeak clients were corrected after.

I think, it should not "spams" your log any longer. There shouldn't left a big problem.

There are two **solutions**:

1) Clean your Ranksystem database. Delete old clients, which are not inside your TeamSpeak database anymore.
Webinterface -> Other -> clean clients -> ON
2) Ignore this log entry. It will be diminish over time. When it is still annoying, do step 1. Cause some user will never connect your TeamSpeak again, you will never solve the ID changes to 100%.
