### ISSUE TITLE
Stats are not added on database.

### ISSUE THREAD

**Issue by DragonHacker1** [Newcomer1989/TSN-Ranksystem#749]
**Ranksystem Version:**
1.3.8, checked on 1.3.9-1
**Description:**
**1) What did you do?**
Analyzing the logs, with debug on.
**2) What did you expect?**
I expected to be as normal.
**3) What result did you get?**
I got results with Executing SQL commands failed: Array issue.
Seem does pop randomly, could be again the bug with over teamspeak3 limits of characters(like i reported).
**Ranksystem Log**
_Add a Ranksystem-Log extract of the last startup._
_You can also use https://pastebin.com/ for this and share us the link._
https://pastebin.com/uFdzvxG0

Fixed. Thank you so much.

**Comment by Newcomer1989** [comment]
Solved via TeamSpeak conversation.
