### ISSUE TITLE
Bot removing wrong server group

### ISSUE THREAD

**Issue by mightyBroccoli** [Newcomer1989/TSN-Ranksystem#75]
I set up the bot to grant 3 different groups 43,44 and 45. Those are just groups which assign a symbol.
Everything works fine except the fact that the bot is removing server groups which he shouldn't.

```
INFO      Servergruppe 7 von User MightyBroccoli (eindeutige Client-ID: ***=; Client-Datenbank-ID 1) entfernt.
INFO      Servergruppe 43 zu User MightyBroccoli (eindeutige Client-ID: ***=; Client-Datenbank-ID 1) hinzugefügt.
```

I am not sure why the bot is doing this. This is my rankup configuration and there is nothing about server group 7.

![2016-08-17 18_01_39-mightybroccolis s mighty stats page](https://cloud.githubusercontent.com/assets/14238117/17743637/ae80229a-64a4-11e6-9d57-94724b8923c4.png)

**Comment by Shad86** [comment]
hm...

check if there is really no syntax error -> ah guy on #68 had the same problem

**Comment by Newcomer1989** [comment]
You changed the rankup definition after the Ranksystem already runs? So the servergroup 7 was defined in an older definition and was given to this user from the Ranksystem?

**Comment by mightyBroccoli** [comment]
@Newcomer1989 yes this could possibly be, your idea from my older issue got me to change the rank setup completly. Can I clean out old ranks in the system ?

**Comment by Newcomer1989** [comment]
The Ranksystem will clear itselfs.. there is nothing, what you have to do.

The only effect is, what you concerned, that the Ranksytem try to remove a group, which is not defined for the Ranksystem. But the Ranksystem remember, that it gives this group to the user.

If you don't want to remove that groups from the user (so it should stay), you can remove the knowledge from the Ranksystem.

SQL to your Ranksystem database:
`UPDATE user SET grpid='0' WHERE grpid NOT IN ('43','44','45');`

Please test it before and make a backup from your database!
