### ISSUE TITLE
Crashing instantly on calc_serverstats

### ISSUE THREAD

**Issue by bykidi** [Newcomer1989/TSN-Ranksystem#751]
**Ranksystem Version:**
1.3.8

**Description:**
**1) What did you do?**
No idea?

**2) What did you expect?**
Everything should work as expected?

**3) What result did you get?**
No idea?

**Ranksystem Log**
Nothing useful in the logfile, but running the bot.php will lead to
PHP Fatal error:  Uncaught Error: Call to a member function fetch() on bool in /var/www/ranks/jobs/calc_serverstats.php:400
Stack trace:
#0 /var/www/ranks/jobs/bot.php(463): calc_serverstats()
#1 /var/www/ranks/jobs/bot.php(569): run_bot()
#2 {main}
  thrown in /var/www/ranks/jobs/calc_serverstats.php on line 400

**Comment by Newcomer1989** [comment]
Is the table user_snapshot existing in your database?

Can you please run the following SQL statements on your database and post us the result. Thx!

```show tables;```

```desc user_snapshot;```

```select count(*) from user_snapshot;```

```select distinct(id) from user_snapshot;```

**Comment by bykidi** [comment]
`

Tables_in_ts3ranksuser |  
-- | --
addon_assign_groups
addons_config
admin_addtime
bak_addons_config
bak_cfg_params
bak_groups
bak_job_check
bak_server_usage
bak_stats_server
bak_stats_user
bak_user
bak_user_snapshot
cfg_params
csrf_token
groups
job_check
server_usage
stats_nations
stats_platforms
stats_server
stats_user
stats_versions
user
user_iphash
user_snapshot

`

**Comment by bykidi** [comment]
localhost/ts3ranksuser/		https://goodgame.by/megasuperphpmyadmin1337/db_sql.php?db=ts3ranksuser
SQL-запрос успешно выполнен.

desc user_snapshot



newid	int(10) unsigned	NO	PRI	
    NULL
	auto_increment	
timestamp	int(10) unsigned	NO	MUL	0		
uuid	char(29)	YES	MUL	
    NULL
		
count	int(10)	NO		0		
idle	int(10)	NO		0

**Comment by bykidi** [comment]
![изображение](https://user-images.githubusercontent.com/1337953/86480997-cd285b80-bd57-11ea-960e-34640c6ebddb.png)

**Comment by bykidi** [comment]
![изображение](https://user-images.githubusercontent.com/1337953/86481044-e16c5880-bd57-11ea-9058-6c780363a0b7.png)

**Comment by bykidi** [comment]
unknown column 'id' in 'field list'

**Comment by Newcomer1989** [comment]
> ![grafik](https://user-images.githubusercontent.com/11364569/86481219-df060080-bd4f-11ea-817f-804c2c7c7b18.png)


Where comes the field "newid"? This is not from us!

The tables should looks like this, after the update to 1.3.8

![grafik](https://user-images.githubusercontent.com/11364569/86481286-0361dd00-bd50-11ea-9f56-4b5543aabaa3.png)

Before the update (1.3.7 and older), it looks like

![grafik](https://user-images.githubusercontent.com/11364569/86481467-5f2c6600-bd50-11ea-9ffc-5da2630a8857.png)

**Comment by bykidi** [comment]
no idea where it came from, i have not touched the ranksystem database manually since... ever?

**Comment by Newcomer1989** [comment]
Can you also run the following commands pls.

`desc bak_user_snapshot;`

`select count(*) from bak_user_snapshot;`

`select distinct(id) from bak_user_snapshot;`

**Comment by bykidi** [comment]
![изображение](https://user-images.githubusercontent.com/1337953/86481844-6efc7800-bd59-11ea-9c29-d0be80c83198.png)
![изображение](https://user-images.githubusercontent.com/1337953/86481864-7c196700-bd59-11ea-9512-5900ed569586.png)

**Comment by bykidi** [comment]
gonna check for my daily backups to see when exactly that column appeared in database

**Comment by Newcomer1989** [comment]
If you want, we can have a look on your system via remote session. Normally it should be possible to repair it.

**Comment by Newcomer1989** [comment]
Problem was really the field "newid" on the table user_snapshot.
Repaired via session on TeamSpeak.
