### ISSUE TITLE
After the removed webspace...

### ISSUE THREAD

**Issue by froland20** [Newcomer1989/TSN-Ranksystem#756]
**Ranksystem Version:**
1.3.9-beta-4

**Description:**

I removed the webspace caches at the ranksystem and I restarted the bot.

The bot removed all avatars and icons.

When the bot is started the avatars are downloaded again but the icons are not.

I've restarted it several times already, but the ranksystem don't want to download them again.

Thanks,
ExXeL

**Comment by Newcomer1989** [comment]
We released a few minutes ago version 1.3.10-beta-5.

Please have a look, if you still have the problem with this version and let us know your insights.

You can start a reset job again to clean the webspace or use the bot command `!reloadgroups` to force a new download.

**Comment by Newcomer1989** [comment]
Should be solved with the release of the version 1.3.10
