### ISSUE TITLE
SQL commands failed: Data too long for column 'nation' with value 'UNKNOWN'

### ISSUE THREAD

**Issue by armandotir** [Newcomer1989/TSN-Ranksystem#758]
Hello, my ranksystem dont work anymore when i delete my server and recreated and import backup, i select log on debug and upload here
[logsql.zip](https://github.com/Newcomer1989/TSN-Ranksystem/files/4965073/logsql.zip)

**Comment by armandotir** [comment]
i changed Query-Slowmode on low delay and bot work good
but not problem? before work on RealTime

**Comment by Newcomer1989** [comment]
It looks like, you are using a TeaSpeak server.

Seems to be TeaSpeak is using an unkown country as "UNKOWN". TeamSpeak transfer an empty value in this case.

We can have a look to handle this case with the next beta (1.3.10-beta-2).

**Comment by armandotir** [comment]
in 1.3.10-beta2 have new problem likely before


2020-08-05 15:26:13.115901   DEBUG     last loop: 0.4432 sec.
2020-08-05 15:26:13.115818   DEBUG     reset_rs needs: 0.00001
2020-08-05 15:26:13.115708   DEBUG     SQL executions needs: 0.21015

)
    [2] => Out of range value for column 'server_ping' at row 1
    [1] => 1264
    [0] => 22003
(
2020-08-05 15:26:13.104741   ERROR     Executing SQL commands failed: Array

**Comment by Newcomer1989** [comment]
Can you please share us also a log for this error.. Thx!

**Comment by armandotir** [comment]
sure i uploaded.
[logs.zip](https://github.com/Newcomer1989/TSN-Ranksystem/files/5028794/logs.zip)

**Comment by Newcomer1989** [comment]
ok, try out beta-4.. this should solve the 'server_ping' problem.

**Comment by armandotir** [comment]
in beta-4 bot stopped again
[logs.zip](https://github.com/Newcomer1989/TSN-Ranksystem/files/5034280/logs.zip)

**Comment by Newcomer1989** [comment]
Hmm, there is no error inside your log. Are you sure it crashed? How did you checked it?

If it really chrashed, you can try to catch the error with the following steps:

1. Start the Ranksystem Bot.
2. Wait till it crashes.
3. There should be still existing an `logs/pid` file (after the crash)
3. Open a command line and run the jobs\bot.php manual
    `php jobs\bot.php`
4. Post the console output here...

**Comment by armandotir** [comment]
Could not open input file: jobsbot.php

**Comment by Newcomer1989** [comment]
First, thx for your response and you help!

That seems to be an unexpected response of the TeaSpeak server. We never got this problem on a TeamSpeak server.
The problem appears on the event handling by waiting on new text messages (notifyTextmessage) or clients, which joins the server (notifyCliententerview).

Can you confirm the bot crashes at this point, some one writes a text message to him or a new client joins the server?

**Comment by armandotir** [comment]
you're welcome.
i disabled command in my server so i think not problem of send text message to bot, without anybody join server bot is stopped
i run bot and after 30 secounds crashed

**Comment by Newcomer1989** [comment]
I am not able to reproduce this issue, since I am not using a TeaSpeak server. I also see, you are using also a beta of TeaSpeak.

If you agree, we can have a look about a remote session to this problem. We can try to debug it.
For this please join our public server (TS address: ts-n.net).

**Comment by armandotir** [comment]
sure, i cant join your server
my ts3client 3.5.3

<10:39:48> Trying to resolve hostname ts-n.net
<10:39:50> Trying to connect to server on ts-n.net
<10:39:56> Failed to connect to server

**Comment by Newcomer1989** [comment]
The server is online and reachable.. must be a client side problem

**Comment by armandotir** [comment]
maybe you limit country?

**Comment by Newcomer1989** [comment]
No, there is no country limit

**Comment by Newcomer1989** [comment]
The problem of the topic of this issue is solved with release of the version 1.3.10
