### ISSUE TITLE
Upgrade documentation?

### ISSUE THREAD

**Issue by jkroepke** [Newcomer1989/TSN-Ranksystem#759]
Hi!

Ich habe grade von 1.3.8 -> 1.3.9 aktualisiert indem ich einfach den Webroot ausgetaucht habe. Reicht das aus oder wie muss ein DB Update durchgeführt werden?

Finde nur die Dokumentation zu installation.

**Comment by Shad86** [comment]
Das Update erfolgt automatisch innerhalb von 24h (sobald eine neue Version verfügbar ist) oder kann indem man den bot mit !update anschreibt manuell getriggert werden.

**Comment by jkroepke** [comment]
Kann ich den das Update nun dennoch manuell durchführen?

**Comment by Newcomer1989** [comment]
Das DB-Update startet nach dem Starten des Bots automatisch. Bitte die Ranksystem.log beachten.
