### ISSUE TITLE
Icons werden nicht mehr angezeigt

### ISSUE THREAD

**Issue by TheChaosToast** [Newcomer1989/TSN-Ranksystem#761]
Ich setze aktuell Version 1.3.9 ein. Nach einem Webspacewechsel habe ich das Ranksystem neu heruntergeladen und meine alte Datenbank eingespielt. Nun zeigt er mir die Servergruppenicons nicht mehr an. Ich habe in der Datenbank den Eintrag "groups" geleert und er lädt die Icons auch herunter, werden mir dennoch nicht angezeigt. Im ordner Icons sind sie auch drin.

Welche möglichkeit hab ich noch?

**Comment by Shad86** [comment]
Der Ordner an sich wo sich die Icons befinden sollte tsicons heißen.

Lese- sowie Schreibrechte müssen Vorhandensein.

Du kannst auch dem bot mal per command schreiben:


`!reloadgroups`

`!reloadicons` 

Cleans the group cache.All server groups will be reloaded from the TS3 server and associated with this the group icons will be re-downloaded.Also the server icon will be re-downloaded.

Ich hoffe ich konnte dir damit weiterhelfen.

**Comment by TheChaosToast** [comment]
Guten Morgen,

Leider nix gebracht :(
Ich habe dem Ordner tsicons die Rechte 777 gegeben ich habe die Befehle wie oben eingegeben. Die Icons werden nicht angezeigt. Avatar sind übrigens kein Problem.

Ich habe meine Datenbank gesichert und die alte Version 1.3.8 von meiner Festplatte geholt und neu eingespielt. Aber auch das funktioniert nicht. Witzigerweise zeigt er mir trotzdem Version 1.3.9 an :/.

Ich weiß gerade absolut nicht was das Problem ist?

**Comment by Newcomer1989** [comment]
Hast du denn den Command `!reloadgroups` mal probiert?

Danach ggfs. den `Bot neu starten`, dann sollte er eigentlich nach und nach die Gruppen und Icons neu laden.

**Comment by TheChaosToast** [comment]
Heyho,

Hab ich probiert. Ohne Erfolg. Er lädt ja auch alles runter, die Daten werden in der Datenbank und auch im tsicons-Ordner gespeichert. Ich bekomme sie nicht angezeigt.

**Comment by Newcomer1989** [comment]
Am besten zeige uns mal einen Screen von dem Verzeichnis `tsicons/` und eines von der DB mittels folgendem SQL:
`select * from groups;`

**Comment by TheChaosToast** [comment]
So jetzt scheints zu funktionieren :)

Bot mehrmals hintereinander neu gestartet und jetzt gehts. Allerdings das nächste Problem. Jetzt läuft in dem Log (vermutlich in einer Endlosschleife immer wieder

2020-08-05 21:37:51.660233   NOTICE          Repair double client-database-ID for XXXXX 

Das läuft für alles User durch die Online sind. Wie gesagt in einer Endlosschleife. Was kann ich jetzt noch tun?

**Comment by Newcomer1989** [comment]
Ok, dann erst einmal die Frage, was genau wurde denn alles gemacht in Bezug auf den Webspacewechsel?
Welche Schritte hast du genau alle vorgenommen bei dem Wechsel? Bitte so detailliert als möglich, damit wir das nachvollziehen können.

**Comment by TheChaosToast** [comment]
Guten morgen, 

also kurz die DB ist eingespielt und es läuft zumindest wieder das Ranksystem ohne Probleme. Ich habe die Daten per FTP gesichert, und die Datenbank mit PHPmyAdmin gesichert (.gz gepackt) dann hab ich alles auf den neuen Webspace hochgeladen, den ordnern (update, tsicons, los, avatare) die rechte 777 gegeben. DAtenbank versucht einzuspielen - abbruch nach einiger Zeit mit 504 Gateway Timeout. Zuletzt hab ich db einfach unentpackt per shell eingespielt und nun läuft es. Nur jetzt spinnt er wieder mit den icons :(
