### ISSUE TITLE
Client shows up as top week active but not been on in months

### ISSUE THREAD

**Issue by arriej** [Newcomer1989/TSN-Ranksystem#764]
**Ranksystem Version:**
3.12.1

**Description:**
There is an odd issue my ranking system. 
There is a user "Amory", Last seen: 2020-06-08 01:33:38
Yet he shows up in the top week with 9 active hours. 

The page: 
[https://alpha.salyfactory.com/](url)

**Ranksystem Log**
https://paste.ubuntu.com/p/3bW66PjCJR/

**Comment by Newcomer1989** [comment]
This user seems to be excepted by the Ranksystem. If its true, you did this about the Webinterface -> Rank -> Exceptions.
Can you confirm this?

**Comment by arriej** [comment]
The user isn't an Exception. The only Group i have in Exceptions is the server group Bot's, that he is not a part of. The reason he doesn't have a rank image is because he has not joined Teamspeak since I have redone my server.  So I revoke everyone' s rank. 
![Capture1](https://user-images.githubusercontent.com/1354079/90013506-ab4ebc80-dca5-11ea-8ee6-37b95f28ee5f.PNG)


Also noticed he was in the top of the moth on 4th place. and that isn't possible as well. as he really hasn't been online since 2020-06-08. He hasn't been registered in the Ts server side database.  So not part of server groups.

**Comment by Newcomer1989** [comment]
I have an idea of what the problem is.

Can you please enable the debug log (Webinterface -> Other -> Log-Level) and let the bot running for at least 10 minutes after.
Please share also this log with us.

**Comment by arriej** [comment]
Here you go: https://paste.ubuntu.com/p/TsHBY26NhV/

I hope there is a way to retain the old data so people can still come on teamspeak and keep their old hours the racked up on the old server.

**Comment by Newcomer1989** [comment]
Ok, I think I still repaired it with the 1.3.11-beta-2. But I didn't tested yet, since I need to adjust your special constellation.
I will try to do this the next view days and release the 1.3.11-beta-2 then.

**Comment by arriej** [comment]
sounds good, Do I need to change to the beta release channel? or can i stay on the stable one?

**Comment by Newcomer1989** [comment]
It would be better. Then you can test it earlier and we can validate we fix your case.

**Comment by arriej** [comment]
Alright, Its currently set to the beta release channel. made a backup of the database. I Restarted the bot hasn't updated yet. `Ranksystem Version: 1.3.10 (on Update-Channel: beta)` 
My bot automatically reboots at 3 minutes past midnight (UTC +1) So if it reboots it will update when you made the beta available.

**Comment by arriej** [comment]
It updated, Unfortunately din't fix the week stats page

https://paste.ubuntu.com/p/6TcRFF9sKZ/

**Comment by Newcomer1989** [comment]
Sure, it can't. We will fix it with beta-2. This version isn't released yet, like I described above.

**Comment by arriej** [comment]
The weekly and monthly stats seem to be working properly now. 
Ran the bot  in Debug mode mode for a bit.  The errors about the missing DB id is still there, not sure how breaking this is at the moment.  Log: https://paste.ubuntu.com/p/SsHCmgZFj7/

When i'm home later on ill compare my  to the weekly and monthly ones and see if they match. 
Thanks for the update.

**Comment by Newcomer1989** [comment]
>The weekly and monthly stats seem to be working properly now.

Ok, nice to hear that.

>Ran the bot in Debug mode mode for a bit. The errors about the missing DB id is still there, not sure how breaking this is at the moment. 

Sure, that message is correct. The information is intentional, cause the clients are missing. You can "repair" this with the clean function, which deletes the old clients out of the Ranksystem database. In your case this might not be wished, cause you would remove the collected times of these users and when they really join to your server in a few days, they would begin by zero.
That is why we only output this message with the debug log-level.

**Comment by arriej** [comment]
Aah makes sense! 
Well the issue is fixed! thanks for that.
