### ISSUE TITLE
Probelem beim Verbinden

### ISSUE THREAD

**Issue by timo017** [Newcomer1989/TSN-Ranksystem#765]
**Ranksystem Version:**
1.3.10
**Beschreibung:**
**1) Was hast du getan?**
Installiert alles geklappt. Nur verbinden tut sich der Bot leider nicht und es kommt eine Fehlermeldung.
**2) Was war deine Erwartung?**
---
**3) Was ist stattdessen passiert?**
---
**Ranksystem Log**
https://pastebin.com/xieLDmzk
https://pastebin.com/NVwu0vMr

**Comment by Newcomer1989** [comment]
Query-Zugangsdaten für den TS waren falsch. Wurde gemeinsam über TS Support behoben.
