### ISSUE TITLE
New wish: AFK Kick

### ISSUE THREAD

**Issue by juvcrafter** [Newcomer1989/TSN-Ranksystem#77]
Hey,
Can you make a System, which kicks specified Groups, when they are a time x afk? So the System can block afk farming :) That is the easiest way for this i think

**Comment by Newcomer1989** [comment]
This could be a module for the Ranksystem. But there are a quite things to do that the Ranksystem handles modules.
Perhaps this will come with one of the next releases. Then it is not the problem to code a little module, which do this job.
