### ISSUE TITLE
BANNER PLACEHOLDERS

### ISSUE THREAD

**Issue by rafalohaki** [Newcomer1989/TSN-Ranksystem#775]
Is there a possibility to add placeholders from website to banners?
I want to show my users their active time via banner.

**Comment by Newcomer1989** [comment]
Sure, you can use the API for this.

Example:
https://ts-n.net/ranksystem_dev/api/?apikey=t8c6wvpi9cjc4k1bj9y42t0dtpedfsadtcyjt2xxbybdgg04l1dogxywwvoegsn5&userstats&uuid=xrTKhT/HDl4ea0WoFDQH2zOpmKg=

There you'll get all information, you need.
The value of `count` - `idle` would be the active time. This value is also available for the week (`count_week` - `idle_week`) and the month (`count_month` - `idle_month`).

Have a look to the "Webinterface" -> "Add-ons" -> "API" to create an API key and get the URL to the API of your Ranksystem instance.

On questions feel free to ask them here.

**Comment by rafalohaki** [comment]
how to paste this api into banner?
can i inject it into ready banner like https://github.com/xman8830/BannerTS3
or do i have to create it from scratch

**Comment by Newcomer1989** [comment]
I do not know, how the banner works. Perhaps, you get support there.

The Ranksystem gives back a JSON string as result, like you can see in the example above.
