### ISSUE TITLE
Verifizierungschannel bearbeiten

### ISSUE THREAD

**Issue by lgund** [Newcomer1989/TSN-Ranksystem#776]
**Ranksystem Version:**
1.3.12

**Beschreibung:**
Ich kann der Bot "Verify Channel" nicht editieren.

**Ranksystem Log**
![image](https://user-images.githubusercontent.com/13957661/94864530-6c82ea80-043c-11eb-86b9-5fb55e669993.png)

**Comment by Newcomer1989** [comment]
https://github.com/Newcomer1989/TSN-Ranksystem/issues/738#issuecomment-702428944
