### ISSUE TITLE
Automatische Ränge hinzufügen

### ISSUE THREAD

**Issue by vlltJan** [Newcomer1989/TSN-Ranksystem#777]
Hallo,

ich habe mal eine Frage, und zwar würde ich gerne, wenn User neu auf den TS joinen, dass die dann viele Gruppen auf einmal bekommen. Leider weiß ich auch nicht wie ich das machen kann, dass man auf einmal direkt viele Gruppen bekommt und bei den Gruppen zuweiser steht ja irgendwas mit **kumulativ**.

**Comment by Shad86** [comment]
Bei diesem system hier handelt es sich um ein Ranksystem, das dir eine Gruppe gibt nach einer von dir angegeben Zeit.

Kumulativ steht deshalb dort, da man die Zeiten die man dort angibt kumulativ angeben muss. Dazu auch nochmal den Hilfetext genau lesen, dazu einfach auf "Funktions-Beschreibung" bei Rank -> Rank Definition klicken.

Was du probieren könntest, grundsätzlich die Gruppen die vergeben werden auf Permanente Gruppe zu stellen, allerdings geht das nur für eine vom User noch nicht erreichte Zeit.

**Comment by vlltJan** [comment]
> Bei diesem system hier handelt es sich um ein Ranksystem, das dir eine Gruppe gibt nach einer von dir angegeben Zeit.
> 
> Kumulativ steht deshalb dort, da man die Zeiten die man dort angibt kumulativ angeben muss. Dazu auch nochmal den Hilfetext genau lesen, dazu einfach auf "Funktions-Beschreibung" bei Rank -> Rank Definition klicken.
> 
> Was du probieren könntest, grundsätzlich die Gruppen die vergeben werden auf Permanente Gruppe zu stellen, allerdings geht das nur für eine vom User noch nicht erreichte Zeit.

Aber früher ging es noch, da konnte man bei den Sekunden "0" angeben und man hat es direkt bekommen mit mehreren Gruppen nur leider jetzt nicht mehr, weißt du zufällig welche Version das war?

**Comment by Shad86** [comment]
Das du die gruppen sofort bekommst bei geringer Zeitangabe sollte eig. noch immer gehen, wie gesagt, das einzige, damit alle Gruppen bleiben müsstest du noch zusätzlich Permanente Gruppe anschalten neben der Rangangabe.

Wichtig ist natürlich auch, das die user mit dem Rangsystem noch keine Zeit gesammelt haben, sollte es noch Gruppen geben die erst nach z.B. 3 Tagen erreicht wird, denn dann wartet das Rangsystem, wenn du Änderungen vorgenommen hast bis der User die nächste Gruppe erreicht.

**Comment by Newcomer1989** [comment]
> Aber früher ging es noch, da konnte man bei den Sekunden "0" angeben und man hat es direkt bekommen mit mehreren Gruppen nur leider jetzt nicht mehr, weißt du zufällig welche Version das war?

Du kannst als kleinsten Wert 1 Sekunde einstellen. Das ist ja fast instant, wenn ein User erstmals auf den TS connected. Wenn es mehere Gruppen sind, kannst du die Zeit jeweils um eine Sekunde erhöhen. Das ist aber natürlich nicht ganz gleichzeitig.

Mehrere Gruppen zur gleichen Zeit, dürfte noch nie funktioniert haben. Das Ranksystem würde dann nur eine davon zuweisen. Das mehrere Gruppen auch gleichzeitig bestehen bleiben, funktioniert erst seit Version 3.1.12. Bitte daher auf die Version achten.

**Comment by vlltJan** [comment]
@Newcomer1989 Hey, also kann man ab der Version: 3.1.12 mehrere Gruppen hinzufügen, die direkt gesetzt werden also (0 oder 1 Sekunde)? Weil das ging mal!

**Comment by Newcomer1989** [comment]
Ab Version 3.1.12 kann man Gruppen die Option zuweisen, dass sie vom Ranksystem nicht mehr entfernt werden sollen.
Bisher war es immer so, dass das Ranksystem die alte Gruppe entfernt hat (z.B. Level 1) und dann die neue Gruppe zugewiesen hat (z.B. Level 2). Damit war es nicht möglich, mehrere gleichzeitig bestehende Gruppen über das Ranksystem automatisiert zu vergeben.
Das geht jetzt mit der aktuellen Version. In der "Rank Definition" können diese jeweils mit einer Sekunde Abstand hinterlegt werden.

Was aber nicht geht, ist das diese Gruppen alle zum exakt gleichen Zeitpunkt vergeben werden. Darin verstehe ich persönlich aber auch keinen Sinn. Sofern erforderlich, bitte den Use Case mal näher erläutern, warum genau das notwendig ist bzw. was der Sinn dahinter ist.

**Comment by Newcomer1989** [comment]
@7quit Ab Version 1.3.14 wird das möglich sein, wenn es die ersten Gruppen sind (Reihenfolge in Sekunden), welche ein User erhält.
Diese dann z.B. mit 1, 2, 3, 4 Sekunden definieren und alle als permanente Gruppe setzen.
Damit das alles zeitgleich passiert, ein kleiner Trick: Setze deine Default Servergruppe (i.d.R. Gast) in den Boost. Dort den Faktor 4 hinterlegen und eine ausreichend hohe Gültigkeit (z.B. 999999).
So wird der User 1 Sekunde nach dem Connect auf dem TS, 4 Servergruppen gleichzeitig bekommen.
