### ISSUE TITLE
API "Wiki" page

### ISSUE THREAD

**Issue by arriej** [Newcomer1989/TSN-Ranksystem#778]
Not entirely sure on where/how I should post this. But to have a bit of an overview of what i can do with the API i made a wiki page of it. its completely written in markdown. feel free to use it. At the bottom there is a spoiler with the source to copy. 

# Stats API

URL build:
 `https://ts-n.net/ranksystem_dev/api/ `?apikey=` `[APIKEY]` `&` `[Paramater]` `&` `*Sub paramater*`

Test API key
> `t8c6wvpi9cjc4k1bj9y42t0dtpedfsadtcyjt2xxbybdgg04l1dogxywwvoegsn5`

the output of the API is in JSON string. 

## Parameters
- **groups** - Get details about the TeamSpeak servergroups.
- **rankconfig** - Get the rankup definition, which contains the assignment of (needed) time to servergroup.
- **server** - Get details about the TeamSpeak server.
- **userstats** - Get additional statistics about the TeamSpeak user.
- **user** - Get details about the TeamSpeak user.

# Groups
## Usage

Get details about the TeamSpeak servergroups.
Example: `https://ts-n.net/ranksystem_dev/api/?apikey=[APIKEY]&groups`
A sub parameter is necessary for the groups to be able to get data. 

**Sub parameters**
- **all** - Get details about all TeamSpeak user. Result is limited by 100 entries.
- **limit** - Define a number that limits the number of results. Maximum value is 1000. Default is 100.
- **order** - Define a sorting order. Value of 'sort' param is necessary. Add as value 'asc' for ascending or 'desc' for descending.
- **sgid** - Get details about TeamSpeak servergroups by the servergroup TS-database-ID.
- **sgidname** - Get details about TeamSpeak servergroups by servergroup name or a part of it.
- **sort** - Define a sorting. Available is each column name, which is given back as a result.

## Examples
* **All Example**: `?apikey=[APIKEY]&groups&all`.
* **Limit Example**: `?apikey=[APIKEY]&groups&limit=10`.
* **Order Example**: `?apikey=[APIKEY]&groups&all&sort=sgid&order=asc`.
* **Sgid Example**: `?apikey=[APIKEY]&groups&sgid=123` [^1].
* **Sgidname Example**: 1. Filter by servergroup name. `?apikey=[APIKEY]&groups&sgidname=Level01` .<br> 2. Filter by servergroup name with a percent sign as placeholder. `?apikey=[APIKEY]&groups&sgidname=Level%`.
* **Sort Example**:  1. Sort by servergroup name. `?apikey=[APIKEY]&groups&all&sort=sgidname`. <br> 2. Sort by TeamSpeak sort-ID. `?apikey=[APIKEY]&groups&all&sort=sortid`.

---

# Server
## Usage
Get details about the TeamSpeak server, see the output tab for a detailed list of data. 
Example: `https://ts-n.net/ranksystem_dev/api/?apikey=[APIKEY]&server`

## Output
Copy of the outpdate on 02/10/2020
```JSON
[{
"total_user":"126",
"total_online_time":"60383285",
"total_online_month":"8897466",
"total_online_week":"1563542",
"total_active_time":"39276463",
"total_inactive_time":"21106822",
"country_nation_name_1":"GB",
"country_nation_name_2":"DE",
"country_nation_name_3":"ZA",
"country_nation_name_4":"NL",
"country_nation_name_5":"BE",
"country_nation_1":"53",
"country_nation_2":"25",
"country_nation_3":"9",
"country_nation_4":"6",
"country_nation_5":"3",
"country_nation_other":"14",
"platform_1":"117",
"platform_2":"3",
"platform_3":"1",
"platform_4":"2",
"platform_5":"0",
"platform_other":"3",
"version_name_1":"3.5.3 [Build: 1588756070]",
"version_name_2":"3.5.2 [Build: 1585812952]",
"version_name_3":"3.3.2 [Build: 1566767614]",
"version_name_4":"3.5.0 [Build: 1582117478]",
"version_name_5":"3.5.1 [Build: 1582118844]",
"version_1":"86",
"version_2":"17",
"version_3":"14",
"version_4":"2",
"version_5":"2",
"version_other":"5",
"server_status":"1",
"server_free_slots":"97",
"server_used_slots":"3",
"server_channel_amount":"33",
"server_ping":"18",
"server_packet_loss":"0.0126",
"server_bytes_down":"25219715377",
"server_bytes_up":"68212729933",
"server_uptime":"5042010",
"server_id":"1",
"server_name":"Saly Factory Teamspeak Server",
"server_pass":"0",
"server_creation_date":"1589659788",
"server_platform":"Linux",
"server_weblist":"1",
"server_version":"3.12.1 [Build: 1585305527]",
"user_today":"17",
"user_week":"38",
"user_month":"52",
"user_quarter":"87"}]
``` 

# Userstats
## Usage

Get details about the TeamSpeak servergroups.
Example: `https://ts-n.net/ranksystem_dev/api/?apikey=[APIKEY]&userstats`
A sub parameter is necessary for the groups to be able to get data.

**Sub parameters**
- **all** - Get details about all TeamSpeak user. Result is limited by 100 entries.
- **limit** - Define a number that limits the number of results. Maximum value is 1000. Default is 100.
- **order** - Define a sorting order.
- **part** - Define, which part of the result you want to get. This is needed, when more then 100 clients are inside the result. At default you will get the first 100 clients. To get the next 100 clients, you will need to ask for part 2
- **sort** - Define a sorting. Available is each column name, which is given back as a result.
- **uuid** - Get details about TeamSpeak user by unique client ID.

## Examples
* **All** Example: `?apikey=[APIKEY]&userstats&all`.
* **Limit** Example: `?apikey=[APIKEY]&userstats&limit=10"`.
* **Order** Example: `?apikey=[APIKEY]&userstats&all&order=asc`.
* **Part** Example: `?apikey=[APIKEY]&userstats&all&part=2`.
* **Sort** Examples: 1. Sort by online time of the week. `?apikey=[APIKEY]&userstats&all&sort=count_week`. <br> 2. Sort by idle time of the week. `?apikey=[APIKEY]&userstats&all&sort=(count_week-idle_week)`. <br> 3. Sort by online time of the month. `userstats&all&sort=count_month` .
* **Uuid** Example:  `userstats&uuid=[UUID]`.

# User
## Usage

Get details about the TeamSpeak servergroups.
Example: `https://ts-n.net/ranksystem_dev/api/?apikey=[APIKEY]&user`
A sub parameter is necessary for the groups to be able to get data. 

**Sub parameters**
- **all** - Get details about all TeamSpeak user. Result is limited by 100 entries.
- **cldbid** - Get details about TeamSpeak user by client TS-database ID.
- **limit** - Define a number that limits the number of results. Maximum value is 1000. Default is 100.
- **name** - Get details about TeamSpeak user by client nickname.
- **online** - Get the online TeamSpeak user.
- **order** - Define a sorting order. Add value 'asc' for ascending or 'desc' for descending.
- **part** - Define, which part of the result you want to get. This is needed, when more then 100 clients are inside the result. At default you will get the first 100 clients. To get the next 100 clients, you will need to ask for part 2.
- **sort** - "Define a sorting. Available is each column name, which is given back as a result.
- **uuid** - Get details about TeamSpeak user by unique client ID.

## Examples
* **All** Example: `?apikey=[APIKEY]&userstats&all`.
* **cldbid** Example: `?apikey=[APIKEY]&user&cldbid=7775`.
* **Limit** Example: `?apikey=[APIKEY]&user&all&limit=10`.
* **name** Example: 1. Filter by client nicknam: `?apikey=[APIKEY]&user&name=arriej`. <br> 2. Filter by client nickname with a percent sign as placeholder: `?apikey=[APIKEY]&user&name=%user%`. 
* **online** Example: `?apikey=[APIKEY]&user&online`.
* **Order** Example: `?apikey=[APIKEY]&userstats&all&order=asc`.
* **Part** Example: `?apikey=[APIKEY]&user&name=TeamSpeakUser&part=2`.
* **Sort** Examples: 1. Sort by online time.  `?apikey=[APIKEY]&user&all&sort=count`. <br> 2. Sort by active time. `?apikey=[APIKEY]&user&all&sort=(count-idle)`. <br> 3. Sort by rank ?apikey=[APIKEY]&user&all&sort=rank`. 
* **Uuid** Example:  `?apikey=[APIKEY]&userstats&uuid=[UUID]`.

## Output
The output for a single user when `?apikey=[APIKEY]&userstats&all` is used 
```JSON
"fXQhZPpCLwBlozun8HFPY0QCDK6Y":
{"cldbid":"3",
"count":"4258858.000",
"name":"arriej",
"lastseen":"1601671121",
"grpid":"73",
"nextup":"191337",
"idle":"554995.000",
"cldgroup":"6,11,18,73",
"online":"1",
"boosttime":"0",
"rank":"1",
"platform":"Windows",
"nation":"NL",
"version":"3.5.3 [Build: 1588756070]",
"firstcon":"1587579330",
"except":"0",
"grpsince":"1601288830",
"cid":"11"},
```

<details>
  <summary>Source to copy</summary>

  ```

# Stats API

URL build:
 `https://ts-n.net/ranksystem_dev/api/ `?apikey=` `[APIKEY]` `&` `[Paramater]` `&` `*Sub paramater*`

Test API key
> `t8c6wvpi9cjc4k1bj9y42t0dtpedfsadtcyjt2xxbybdgg04l1dogxywwvoegsn5`

the output of the API is in JSON string. 

## Parameters
- **groups** - Get details about the TeamSpeak servergroups.
- **rankconfig** - Get the rankup definition, which contains the assignment of (needed) time to servergroup.
- **server** - Get details about the TeamSpeak server.
- **userstats** - Get additional statistics about the TeamSpeak user.
- **user** - Get details about the TeamSpeak user.

# Groups
## Usage

Get details about the TeamSpeak servergroups.
Example: `https://ts-n.net/ranksystem_dev/api/?apikey=[APIKEY]&groups`
A sub parameter is necessary for the groups to be able to get data. 

**Sub parameters**
- **all** - Get details about all TeamSpeak user. Result is limited by 100 entries.
- **limit** - Define a number that limits the number of results. Maximum value is 1000. Default is 100.
- **order** - Define a sorting order. Value of 'sort' param is necessary. Add as value 'asc' for ascending or 'desc' for descending.
- **sgid** - Get details about TeamSpeak servergroups by the servergroup TS-database-ID.
- **sgidname** - Get details about TeamSpeak servergroups by servergroup name or a part of it.
- **sort** - Define a sorting. Available is each column name, which is given back as a result.

## Examples
* **All Example**: `?apikey=[APIKEY]&groups&all`.
* **Limit Example**: `?apikey=[APIKEY]&groups&limit=10`.
* **Order Example**: `?apikey=[APIKEY]&groups&all&sort=sgid&order=asc`.
* **Sgid Example**: `?apikey=[APIKEY]&groups&sgid=123` [^1].
* **Sgidname Example**: 1. Filter by servergroup name. `?apikey=[APIKEY]&groups&sgidname=Level01` .<br> 2. Filter by servergroup name with a percent sign as placeholder. `?apikey=[APIKEY]&groups&sgidname=Level%`.
* **Sort Example**:  1. Sort by servergroup name. `?apikey=[APIKEY]&groups&all&sort=sgidname`. <br> 2. Sort by TeamSpeak sort-ID. `?apikey=[APIKEY]&groups&all&sort=sortid`.

---

# Server
## Usage
Get details about the TeamSpeak server, see the output tab for a detailed list of data. 
Example: `https://ts-n.net/ranksystem_dev/api/?apikey=[APIKEY]&server`

## Output
Copy of the outpdate on 02/10/2020
```JSON
[{
"total_user":"126",
"total_online_time":"60383285",
"total_online_month":"8897466",
"total_online_week":"1563542",
"total_active_time":"39276463",
"total_inactive_time":"21106822",
"country_nation_name_1":"GB",
"country_nation_name_2":"DE",
"country_nation_name_3":"ZA",
"country_nation_name_4":"NL",
"country_nation_name_5":"BE",
"country_nation_1":"53",
"country_nation_2":"25",
"country_nation_3":"9",
"country_nation_4":"6",
"country_nation_5":"3",
"country_nation_other":"14",
"platform_1":"117",
"platform_2":"3",
"platform_3":"1",
"platform_4":"2",
"platform_5":"0",
"platform_other":"3",
"version_name_1":"3.5.3 [Build: 1588756070]",
"version_name_2":"3.5.2 [Build: 1585812952]",
"version_name_3":"3.3.2 [Build: 1566767614]",
"version_name_4":"3.5.0 [Build: 1582117478]",
"version_name_5":"3.5.1 [Build: 1582118844]",
"version_1":"86",
"version_2":"17",
"version_3":"14",
"version_4":"2",
"version_5":"2",
"version_other":"5",
"server_status":"1",
"server_free_slots":"97",
"server_used_slots":"3",
"server_channel_amount":"33",
"server_ping":"18",
"server_packet_loss":"0.0126",
"server_bytes_down":"25219715377",
"server_bytes_up":"68212729933",
"server_uptime":"5042010",
"server_id":"1",
"server_name":"Saly Factory Teamspeak Server",
"server_pass":"0",
"server_creation_date":"1589659788",
"server_platform":"Linux",
"server_weblist":"1",
"server_version":"3.12.1 [Build: 1585305527]",
"user_today":"17",
"user_week":"38",
"user_month":"52",
"user_quarter":"87"}]
``` 

```
# Userstats
## Usage

Get details about the TeamSpeak servergroups.
Example: `https://ts-n.net/ranksystem_dev/api/?apikey=[APIKEY]&userstats`
A sub parameter is necessary for the groups to be able to get data.

**Sub parameters**
- **all** - Get details about all TeamSpeak user. Result is limited by 100 entries.
- **limit** - Define a number that limits the number of results. Maximum value is 1000. Default is 100.
- **order** - Define a sorting order.
- **part** - Define, which part of the result you want to get. This is needed, when more then 100 clients are inside the result. At default you will get the first 100 clients. To get the next 100 clients, you will need to ask for part 2
- **sort** - Define a sorting. Available is each column name, which is given back as a result.
- **uuid** - Get details about TeamSpeak user by unique client ID.

## Examples
* **All** Example: `?apikey=[APIKEY]&userstats&all`.
* **Limit** Example: `?apikey=[APIKEY]&userstats&limit=10"`.
* **Order** Example: `?apikey=[APIKEY]&userstats&all&order=asc`.
* **Part** Example: `?apikey=[APIKEY]&userstats&all&part=2`.
* **Sort** Examples: 1. Sort by online time of the week. `?apikey=[APIKEY]&userstats&all&sort=count_week`. <br> 2. Sort by idle time of the week. `?apikey=[APIKEY]&userstats&all&sort=(count_week-idle_week)`. <br> 3. Sort by online time of the month. `userstats&all&sort=count_month` .
* **Uuid** Example:  `userstats&uuid=[UUID]`.


# User
## Usage

Get details about the TeamSpeak servergroups.
Example: `https://ts-n.net/ranksystem_dev/api/?apikey=[APIKEY]&user`
A sub parameter is necessary for the groups to be able to get data. 

**Sub parameters**
- **all** - Get details about all TeamSpeak user. Result is limited by 100 entries.
- **cldbid** - Get details about TeamSpeak user by client TS-database ID.
- **limit** - Define a number that limits the number of results. Maximum value is 1000. Default is 100.
- **name** - Get details about TeamSpeak user by client nickname.
- **online** - Get the online TeamSpeak user.
- **order** - Define a sorting order. Add value 'asc' for ascending or 'desc' for descending.
- **part** - Define, which part of the result you want to get. This is needed, when more then 100 clients are inside the result. At default you will get the first 100 clients. To get the next 100 clients, you will need to ask for part 2.
- **sort** - "Define a sorting. Available is each column name, which is given back as a result.
- **uuid** - Get details about TeamSpeak user by unique client ID.

## Examples
* **All** Example: `?apikey=[APIKEY]&userstats&all`.
* **cldbid** Example: `?apikey=[APIKEY]&user&cldbid=7775`.
* **Limit** Example: `?apikey=[APIKEY]&user&all&limit=10`.
* **name** Example: 1. Filter by client nicknam: `?apikey=[APIKEY]&user&name=arriej`. <br> 2. Filter by client nickname with a percent sign as placeholder: `?apikey=[APIKEY]&user&name=%user%`. 
* **online** Example: `?apikey=[APIKEY]&user&online`.
* **Order** Example: `?apikey=[APIKEY]&userstats&all&order=asc`.
* **Part** Example: `?apikey=[APIKEY]&user&name=TeamSpeakUser&part=2`.
* **Sort** Examples: 1. Sort by online time.  `?apikey=[APIKEY]&user&all&sort=count`. <br> 2. Sort by active time. `?apikey=[APIKEY]&user&all&sort=(count-idle)`. <br> 3. Sort by rank ?apikey=[APIKEY]&user&all&sort=rank`. 
* **Uuid** Example:  `?apikey=[APIKEY]&userstats&uuid=[UUID]`.

## Output
The output for a single user when `?apikey=[APIKEY]&userstats&all` is used 
```JSON
"fXQhZPpCLwBlozun8HFPY0QCDK6Y":
{"cldbid":"3",
"count":"4258858.000",
"name":"arriej",
"lastseen":"1601671121",
"grpid":"73",
"nextup":"191337",
"idle":"554995.000",
"cldgroup":"6,11,18,73",
"online":"1",
"boosttime":"0",
"rank":"1",
"platform":"Windows",
"nation":"NL",
"version":"3.5.3 [Build: 1588756070]",
"firstcon":"1587579330",
"except":"0",
"grpsince":"1601288830",
"cid":"11"},
```

  
</details>

**Comment by Shad86** [comment]
@arriej we've added your initial post to the wiki :)
