### ISSUE TITLE
The Ranksystem does not seem to run.

### ISSUE THREAD

**Issue by PsychoMonster** [Newcomer1989/TSN-Ranksystem#78]
Hallo,

ich habe das Problem das sich der Bot nicht mit dem Teamspeak3 server verbindet. Er kam nach der Installation auf den server drauf und ging sofort wieder. Jetzt joint er nicht mehr auf den Server und bei dem status abruf steht: 'The Ranksystem does not seem to run.' ! aber nach dem befehl php worker.php start steht dies: Starting the Ranksystem Bot. [Ok]. Hoffe um schnelle Hilfe.

Liebe Grüße 

Psycho

**Comment by Shad86** [comment]
Die Logdatei sollte dir mehr darüber sagen können, warum es nicht startet.

(Wo sie hingespeichert wird sollte im webinterface.php stehen )

**Comment by Newcomer1989** [comment]
Like Shad86 already described, we need the ranksystem.log to see what happens.

Perhaps your server was banned due flood. Please be sure, you have whitelist the ip address of your webhost (website) for your teamspeak server.

**Comment by Newcomer1989** [comment]
seems to be solved with issue 84
