### ISSUE TITLE
Cross Origin Policy API

### ISSUE THREAD

**Issue by arriej** [Newcomer1989/TSN-Ranksystem#782]
I'm trying to use the API to display online users on my Teamspeak server on my website (salyfactory.com)
The data is coming from alpha.salyfactory.com.  
Both sites are hosted on the same webserver. But use different SSH certificates. 

Due to the the overreaction of browser safety it throws an error in the browser.  this is an issue client sides. But i cant expect everyone that uses my site to install an addon. 

> The same-origin policy restricts which network messages one origin can send to another. For example, the same-origin policy allows inter-origin HTTP requests with GET and POST methods but denies inter-origin PUT and DELETE requests. Additionally, origins can use custom HTTP headers when sending requests to themselves but cannot use custom headers when sending requests to other origins.

> The restrictions on reading information received from other origins is also somewhat subtle. For example, the HTML <script> element can execute content retrieved from foreign origins, which means web sites should not rely on the same-origin policy to protect the confidentiality of information in a format that happens to parse as script (e.g., JavaScript source files, JSON format, JSONP services, or JavaScript/gif polyglots). For all such resources, no loss of security would result (and much flexibility would be gained) from adding the Access-Control-Allow-Origin:* header to all responses.

So there is a relatively easy way to bypass the security issues, Wihtout losing much system safety. 
Maybe add an option to add IP's to the Access control allow origin. 

**Ranksystem Version:**
1.3.12

I hope this isn't an unclear mess. and you're able to implant something in the API so I don't have to work with a proxy.

**Comment by Newcomer1989** [comment]
We will add an option to set the header 'Access-Control-Allow-Origin' attribute with the next beta (1.3.13-beta-4).

Would be nice, if you can test it with this version and give us feedback if it solves your problem.

**Comment by arriej** [comment]
the updates works perfectly,
Added the domain and fixed our issue.

**Comment by Newcomer1989** [comment]
Thx for the feedback.. nice to hear!

**Comment by Newcomer1989** [comment]
Release 1.3.13 is out.
