### ISSUE TITLE
Exclusions appear in the listing order

### ISSUE THREAD

**Issue by krygnc** [Newcomer1989/TSN-Ranksystem#783]
Why do I see what I exclude
![ts3rank](https://user-images.githubusercontent.com/73647888/97574893-f2269580-19fc-11eb-9d00-53e337fc89fc.png)

**Comment by arriej** [comment]
Not sure how you have set up your exclusion groups.
But I have it setup with a server group "Bots" that are excluded from ranking up.  The exception mode is set to default. 
You can find this setting in rank  -> Exceptions. 

![Capture1000](https://user-images.githubusercontent.com/1354079/97650297-ace48100-1a59-11eb-8547-79a10017f7d2.PNG)

Then to hide these clients from the list rankup navigate to "Stats page" -> "List rankup" and there my excepted client setting  is off. 
![Capture1001](https://user-images.githubusercontent.com/1354079/97650296-ac4bea80-1a59-11eb-8661-49c3bc1d3664.PNG)


With these settings my music bot isn't showing up in the list rankup.

**Comment by krygnc** [comment]
Ooo excepted client mod off it happened ty <3
