### ISSUE TITLE
Import Mode

### ISSUE THREAD

**Issue by LeBaasti** [Newcomer1989/TSN-Ranksystem#786]
The import mode in version 1.3.12 is not available. But it is shown briefly when you click on the category. That makes it difficult for me because otherwise I would have to enter everything manually.

**Comment by LeBaasti** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/48323856/97881313-89079080-1d22-11eb-83a5-657bbdd758fd.png)

**Comment by Shad86** [comment]
You can see the import modus as soon as you activate the expert mode (On top of the page on the right side, click on your name - there is the button for expert mode)

**Comment by LeBaasti** [comment]
oh, ok. thank you
