### ISSUE TITLE
Restart error with cornjob 

### ISSUE THREAD

**Issue by arriej** [Newcomer1989/TSN-Ranksystem#788]
Hello,

Since beta-5 I seem to have issues with restarting the bot trough the normal way I used to restart it.
I've setup a cornjob to restart my bot at 1AM.  This always used to work without issues.
Script path: `alpha.salyfactory.com/worker.php` Argument: ` restart` 

But then Plesk proceeds to send me an email (only on errors)  with the title: `/opt/plesk/php/7.4/bin/php -f 'alpha.salyfactory.com/worker.php' -- 'restart' > /dev/null`
In the email nothing more then: 
`PHP Notice:  Undefined offset: 2 in /var/www/vhosts/salyfactory.com/alpha.salyfactory.com/other/config.php on line 46`

When I put the bot in debug mode and do the reboot trough the cornjob the output is the following: 
https://paste.ubuntu.com/p/B2D3sJchcf/ - Nothing special can be noticed in the log. 

Using PHP 7.4.12, since you are switching to php8, maybe thats the issue? 

Issue 2: 
I also Seem to get crashes now and then, Have had 2 since beta5. Only 1 threw errors in the log file: https://paste.ubuntu.com/p/3tSgVRsScg/

**Comment by Newcomer1989** [comment]
> PDO::query(): Broken pipe

That sounds like a database problem. Perhaps you need to increase the `wait_timeout` option for your database.

Happens issue 1 also, when you manual use the restart command? Also, when you start it about the webinterface?

**Comment by arriej** [comment]
I just tried to monitor the logfile while executing it trough different ways, Such as cornjob restart an manual restart (trough the web interface) I haven't got around to testing it from within teamspeak. 
But none of these actions seem to write to a log file at least, not one i can easily find. Same for the errors thrown on the cornjob restarts. I'm going to do some more testing and trying to find a file it writes to. I'll come with more info.
 
- Never pressed "Comment" after typing this out. Just saw the update msgs as well. ill stop trying then :P  I have not made changed to my rank definitions, And will see how it turns out when its out of the beta branch.

**Comment by Newcomer1989** [comment]
> PHP Notice: Undefined offset: 2 in /var/www/vhosts/salyfactory.com/alpha.salyfactory.com/other/config.php on line 46

The notice message should be solved with the current release 1.3.13.

If you encounter further problems, please open a new thread.
