### ISSUE TITLE
Ipv6 ready

### ISSUE THREAD

**Issue by mightyBroccoli** [Newcomer1989/TSN-Ranksystem#79]
In regards of the newly released teamspeak server version 3.0.13 the IPv6 compatability is added to the range of possible addresses to connect. The Ranksystem seams to not register those adresses the database collects a 0.0.0.0 for each client connected through IPv6.
Will this be regarded in the new version ?

**Comment by Newcomer1989** [comment]
This wasn't possible for version 1.1.0. But I will try to code this to the 1.1.1. 

Also there should come a support to connect to your ts3 server via IPv6.

Like everytime I can't give you an ETA for 1.1.1. Its only a hobby ;-)

**Comment by ryanmemer** [comment]
If the 1.1.1 looks anything like the updated screenshots on your ranksystem webpage, then I can't fucking wait. It looks amazing!

**Comment by Newcomer1989** [comment]
Good news for you.. You musn't wait ;-)

The screenshots on the Ranksystem page are the version 1.1.0 and this is still released. You can download it from the Ranksystem page or here from GitHub.

**@mightyBroccoli**
If you want, I would give you a pre version of the 1.1.1. There you could try out the IPv6 will be saved correctly. When you are interested, contact me on the public ts3 server (ts-n.net).

**Comment by ryanmemer** [comment]
Not these ones ;D https://gyazo.com/6f9dcb51910c180297a5dd74523e46b8

**Comment by Newcomer1989** [comment]
Yes, this one.. What are standing on top? -> Webinterface 1.1.0

This is the new webinterface!

**Comment by ryanmemer** [comment]
Oh I thought I had that version, is it an edit of the original 1.1.0?

**Comment by Newcomer1989** [comment]
No this wasn't changed.. But please stop this here. This is not the topic of the thread. If you have problems there, please open an separate issue.

**Comment by mightyBroccoli** [comment]
@Newcomer1989 sure dude I would like that.
Just for timezone purposes i am UTC+1 i hope you are not -7 or stuff like that. I looked on your public teamspeak but I am not sure if I am looking at the right time :8ball:
