### ISSUE TITLE
!!!! Logs folder is not writable !!!! Cancel restart request!

### ISSUE THREAD

**Issue by LeBaasti** [Newcomer1989/TSN-Ranksystem#790]
I specified the correct folder, but it still doesn't work:
https://prnt.sc/vructo
https://prnt.sc/vrucxu
https://prnt.sc/vrud2q

**Comment by Newcomer1989** [comment]
Which version of the Ranksystem are you using?

Is it a fresh installation? If not, what has been changed (hosting relocation, ...) ?

On which operating system is the Ranksystem installed?

What exactly you did, that you run into this error? Can you please describe the steps you did / the shell commands you entered.
