### ISSUE TITLE
Hohe CPU Auslastung mit Mariadb in Verbindung des Ranksystems

### ISSUE THREAD

**Issue by Killer0561** [Newcomer1989/TSN-Ranksystem#793]
Ranksystem Version | > 1.3.13
TeamSpeak 3 Server Version | > 3.13.2 [Stable] Linux
TeamSpeak 3 Client Version | > 3.5.6 [Stable] Windows
Ranksystem Statistik Seite | > https://serverinterface.egu-multigaming.de/teamspeak/ranksystem/stats/
Ranksystem Log | > https://pastebin.com/J31hVjKA

0) Beschreibung:
>> Wenn der Bot aktiv ist, steigt die CPU Leistung in einem Interval zwischen 10 bis 20 Sekunden auf 100% CPU für 2 bis 5 Sekunden. Ist das normal? Wenn ich den Bot abschalte, verschwindet die hohe CPU Auslastung. Irgendwelche Ideen, woran das liegen könnte?

1) Was hast du getan? 
>> Den Bot abgeschaltet, weil dadurch die hohe CPU Auslastung verschwunden ist.

2) Was war deine Erwartung?
>> Das die hohe CPU Auslastung verschwindet.

3) Was ist stattdessen passiert?
>> keine Angabe.

Gruß, Killer0561 (Sascha)

**Comment by Newcomer1989** [comment]
Der Auszug für die Log ist etwas kurz, um da wirklich etwas nachvollziehen zu können..

Was genau verursacht denn die hohe Systemlast? Der Prozess des Ranksystem bots oder die Mariadb? Abgesehen von der CPU Last. Wie sieht es mit der I/O Last bzw. dem RAM aus?

Was für eine CPU ist denn verbaut? Handelt es sich um einen virtuellen oder dedicated Server?

**Comment by Killer0561** [comment]
Ich hab den Log nochmal aktualisiert. Hatte vergessen auf Log Level 6 Debug zu setzen.
https://pastebin.com/J31hVjKA

Wie es ganz so aussieht verursacht das Ranksystem die hohe Last bei Mariadb. Ich hatte nur HLStatsx aktiv als Testzwecke, da war die hohe CPU Auslastung nicht aufgetreten. Nachdem ich das Ranksystem mit eingeschaltet hatte, steigt die Auslastung auf 100% CPU.

32 GB DDR3 Ram sind im Server verbaut. Es handelt sich um einen dedicated Server.

Gruß, Killer0561 (Sascha)

**Comment by Newcomer1989** [comment]
Die Executions, sprich die Ausführung der Befehle an die Datenbank (Inserts, Updates, etc.) dauert wohl sehr lange.

Bsp.:
`2020-12-02 16:03:22.332774   DEBUG     SQL executions needs: 1.44259`

Hier hat nur das Executen 1,4 Sekunden gedauert. In Anbetracht der Größe von nicht einmal 400 Usern in der DB und ca. 15 gleichzeitigen Online-Nutzern ist das ein sehr schlechtes Ergebnis.

Zum Vergleich bei uns dauert das im Schnitt nicht einmal 0,03 Sekunden. Obwohl wir knapp 35k User in der DB haben und teilweise ~180 User gleichzeitig online.
https://ts-n.net/ranksystem_dev/stats/

```
17:27 · Newcomer1989 !runtime
17:27 · TSN Ranksystem Last 10 runtimes (in seconds):
[..]
Ø 0.02172 sec. (Σ 179101)
```

Gleichzeitig hat unserer Datenbank unabhängig dessen weit über Faktor 100 mehr zu tun, da über die gleiche DB auch unserer Hosted Instanzen und etliche weitere Dinge laufen.

Alles in allem zeigt das, dass die DB wohl sehr schlecht performed. 

Ggfs. liegt hier auch eine Misskonfiguration vor. Selbst eine Default-DB sollte wesentlich besser abschneiden.
Vielleicht würde ein vollständiger Neuinstall der DB helfen. Wichtig: Auch die Konfigurationsdateien überinstallieren.

Alternativ oder zusätzlich zu einer Neuinstallation, können wir dir ein gutes Tutorial zum Verbessern der DB Perfomance empfehlen. Das kostet zwar auch etwas Zeit, bringt aber wirklich viel. Insbesondere lernt man auch einiges.
http://www.speedemy.com/17-key-mysql-config-file-settings-mysql-5-7-proof/

**Comment by Killer0561** [comment]
Ich hab den Guide befolgt und komme zu dem Ergebnis, das die CPU Auslastung sich reduziert hat.
Vielen Dank für die Hilfe nochmals. Das Thema kann hier geschlossen werden.

Gruß, Killer0561 (Sascha)
