### ISSUE TITLE
PHP 8 - New Ranksystem Installation - Uncaught TypeError server_usage.php:8

### ISSUE THREAD

**Issue by RealZezzo** [Newcomer1989/TSN-Ranksystem#797]
Beschreibung | unterhalb ausfüllen
-- | --
Ranksystem Version | 1.3.14
Nutzt du TeamSpeak oder TeaSpeak? | TeamSpeak
Pastebin Link zu deiner Ranksystem Log *¹ | https://pastebin.com/pe8639BD

---

### 1) Was hast du getan?

Ich habe das Ranksystem gestartet, sodass es auf den Teamspeak connectet soll.

### 2) Was war deine Erwartung?

Das der Bot dem Teamspeak joint und stabil auf dem Teamspeak bleibt.

### 3) Was ist stattdessen passiert?

Das System startet, der Bot joint auf den Teamspeak (mit Admin Server Query), disconnectet nach ein paar Sekunden wieder und das Ranksystem stoppt komplett.

---

#### *¹ Ranksystem Log - HOW-TO
- Wechsel den Log-Level zu `6 - Debug` (-> Webinterface -> Anderes -> Log-Level).
- Wechsel die Sprache zu `EN english` (-> Webinterface -> Anderes -> Sprache).
- Starte den Ranksystem Bot neu und lasse ihn für mind. 10 Minuten laufen (-> Webinterface -> Start / Stop Bot -> Bot neu starten).
- Kopiere einen Auszug aus der Ranksystem Log, welche mindestens auch den letzten Neustart enthält (-> Webinterface -> Start / Stop Bot -> unten).
- Bitte nutze https://pastebin.com/ um die Log zu teilen.

**Comment by Newcomer1989** [comment]
Kannst du mal in der Datenbank schauen, was da bei den folgenden SQL-Befehlen raus kommt?

```
SHOW TABLES IN `psyrank`;

DESC `psyrank`.`server_usage`;

SELECT MAX(`timestamp`) AS `timestamp` FROM `psyrank`.`server_usage`;

SELECT COUNT(*) FROM `psyrank`.`server_usage`;
```

Handelt es sich um ein frisch installiertes / eingerichtetes System?

**Comment by RealZezzo** [comment]
> Kannst du mal in der Datenbank schauen, was da bei den folgenden SQL-Befehlen raus kommt?
> 
> ```
> SHOW TABLES IN `psyrank`;
> 
> DESC `psyrank`.`server_usage`;
> 
> SELECT MAX(`timestamp`) AS `timestamp` FROM `psyrank`.`server_usage`;
> 
> SELECT COUNT(*) FROM `psyrank`.`server_usage`;
> ```
> 
> Handelt es sich um ein frisch installiertes / eingerichtetes Ranksystem?

Tables:
https://pastebin.com/a2zW5g7k

Und ja ist ein frisch installiertes System über xampp

**Comment by Newcomer1989** [comment]
Ok, danke für die Rückmeldung.. sieht so aus, als wäre noch eine kleine Anpassung in Bezug auf PHP 8 erforderlich.

Wenn du magst, kannst du die Änderung direkt durchführen.

Datei: `jobs/server_usage.php`

Zeile 8

alt:
`if(key($db_cache['max_timestamp_server_usage'])  == 0 || ($nowtime - key($db_cache['max_timestamp_server_usage'])) > 898) { // every 15 mins`

neu:
`if(key($db_cache['max_timestamp_server_usage']) === '' || ($nowtime - key($db_cache['max_timestamp_server_usage'])) > 898) { // every 15 mins`


Damit sollte es dann funktionieren. Wir werden es natürlich auch in der nächsten Version umsetzen, das kann aber ggfs. noch ein paar Tage dauern.

**Comment by RealZezzo** [comment]
Viele Dank für die Hilfe. Funktioniert jetzt alles wieder wie es soll! Ihr macht hier einen tollen Support!
