### ISSUE TITLE
Error 524

### ISSUE THREAD

**Issue by ghost** [Newcomer1989/TSN-Ranksystem#798]
Hey, I am completly new to the world of linux but I have been trying to setup my team speak server using a vps that I rented, however, what is happening is that when I start the ranksystem bot it gives me this: https://pastebin.com/W0Rw5TRm. My teamspeak ip whitelist looks like this: https://prnt.sc/w3daeb (the ranksystem ip address). I do not know how to solve this or if there is anything I have to do about the ports on my vps. Looking for help.

**Comment by Newcomer1989** [comment]
This seems to be a problem on your TeamSpeak server.

> 2020-12-15 19:15:21.720476   ERROR     TS3 error: 2568: insufficient client permissions (failed on servergroupaddclient 175/0xAF) ; 

The Query User of the Ranksystem needs this permission.

Have here a look for a full Query permission list
https://ts-ranksystem.com/#linux  -> ServerQuery

**Comment by caiobiondi** [comment]
Thank you very much. Do you have any idea of how to solve the flooding issue?

**Comment by Newcomer1989** [comment]
You can try to add the permission "b_client_ignore_antiflood" to the Query User of the Ranksystem.

But is it still flooding, when there aren't insufficient client permissions?

**Comment by caiobiondi** [comment]
Still not solved it. This is what I get right now:https://pastebin.com/W2CRy9aT

**Comment by Newcomer1989** [comment]
There is no connection possible from our server to yours on port 10011.. Please whitelist our ip address inside your firewall or anything else!


A ping is working..
```
XXX@tsn:~# ping 198.12.225.98
PING 198.12.225.98 (198.12.225.98) 56(84) bytes of data.
64 bytes from 198.12.225.98: icmp_seq=1 ttl=50 time=78.4 ms
^C
--- 198.12.225.98 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 78.438/78.438/78.438/0.000 ms
```

Port 80 would be also fine
```
XXX@tsn:~# nc -z -v 198.12.225.98 80
Connection to 198.12.225.98 80 port [tcp/http] succeeded!

```

But **port 10011** is rejected
```
XXX@tsn:~# nc -z -v 198.12.225.98 10011
nc: connect to 198.12.225.98 port 10011 (tcp) failed: No route to host
```
