### ISSUE TITLE
V1.00 / TimeZone is not saved.

### ISSUE THREAD

**Issue by Spazmic** [Newcomer1989/TSN-Ranksystem#8]
Hello,

The new TimeZone option is not saved in the database when updating to 1.00.

Thank you

**Comment by Newcomer1989** [comment]
Thats true.. Thats why it stand in the HowTo for the update.

> 8. Check/configurate new parameter "Timezone" and "Default Channel" in webinterface.php.

You have to set the timezone manual inside the webinterface.

Or this error came, where you want to save this value about the webinterface?

**Comment by Spazmic** [comment]
When I say is not saved in the database,  its when I actually press the save button in the webinterface. When I go back to the webinterface page it defaults to  europe

**Comment by Newcomer1989** [comment]
I have to check this.. I will give a feedback here, if I did it.

**Comment by Newcomer1989** [comment]
should be emended with release 1.01
(enable the update check inside the webinterface to get notified when it gets published)
