### ISSUE TITLE
setup bot centos7

### ISSUE THREAD

**Issue by caiobiondi** [Newcomer1989/TSN-Ranksystem#800]
Hey, I have been trying to setup the bot on my vps. I installed apache, php and mysql. These are the modules for php: https://prnt.sc/w4umj9. I created a mysql user and granted all permissions. I also change max_execution_time to 0 and changed the owner of /var/www from root to apache. However, after I run install.php the bot won't join the server and this is what I get: https://pastebin.com/PTTu9EqX. Also when I go into rank - rank definition it won't save any changes (https://prnt.sc/w4uoo3). In adittion the bot won't get the information of the users in the server to setup bot admin. This is what I have for the teamspeak page: https://prnt.sc/w4upd5. I am unexperienced with linux so any help is welcome.

thank you

**Comment by Newcomer1989** [comment]
This is related to #797 

You can fix it with updating the following and restarting the bot after.

file: `jobs/server_usage.php`

row 8

old:
`if(key($db_cache['max_timestamp_server_usage']) == 0 || ($nowtime - key($db_cache['max_timestamp_server_usage'])) > 898) { // every 15 mins`

new:
`if(key($db_cache['max_timestamp_server_usage']) === '' || ($nowtime - key($db_cache['max_timestamp_server_usage'])) > 898) { // every 15 mins`

**Comment by caiobiondi** [comment]
OMG it finally worked. Thank you very much. One last question, is there anything I need to do for the Assign Servergroups function to work? Once again, thank you.

**Comment by Newcomer1989** [comment]
> One last question, is there anything I need to do for the Assign Servergroups function to work?

What is the problem? Is there any error message you want to share with us?

**Comment by caiobiondi** [comment]
What happens is that when I go into the assign servergrpup page in the interface, set it up and hit save, it does not apply. When I refresh the page nothing is there. I don't get any errors on the log and all the other functions work perfect except this one. Thank you.

**Comment by caiobiondi** [comment]
I am getting the error message for https

**Comment by Newcomer1989** [comment]
The problem is, you are getting the HTTPS warning message. This prevents the saving operation.

We changed the process. The HTTPS message will only appear on the login page.

This is done with release 1.3.15, which is out now.
You will get the update automatically within the next 24 hours or you can force the update-check with the command `!update` (as text message to the Ranksystem bot).

**Comment by caiobiondi** [comment]
Thank you very much man. It worked.

**Comment by Newcomer1989** [comment]
Ok, nice.
