### ISSUE TITLE
crash bot

### ISSUE THREAD

**Issue by LeiToH** [Newcomer1989/TSN-Ranksystem#801]
`2020-12-18 21:12:48.068931   NONE      
  thrown in /var/www/html/jobs/bot.php on line 359
#1 {main}
#0 /var/www/html/jobs/bot.php(515): run_bot(Array)
Stack trace:
[18-Dec-2020 17:26:34 America/Argentina/Buenos_Aires] PHP Fatal error:  Uncaught Error: Call to a member function fetchAll() on bool in /var/www/html/jobs/bot.php:359
2020-12-18 17:26:34.096473   NOTICE    2: PDO::query(): Error reading result set's header on line 359 in /var/www/html/jobs/bot.php
2020-12-18 17:26:34.096369   NOTICE    2: PDO::query(): MySQL server has gone away on line 359 in /var/www/html/jobs/bot.php`

**Comment by Newcomer1989** [comment]
> MySQL server has gone away

That might happen, when you turn off the MySQL database.

Start the MySQL and after start the Ranksystem

**Comment by LeiToH** [comment]
`2020-12-19 10:41:14.746653   NOTICE    2: PDO::query(): Error reading result set's header on line 34 in /var/www/html/jobs/calc_userstats.php
2020-12-19 10:41:14.746545   NOTICE    2: PDO::query(): MySQL server has gone away on line 34 in /var/www/html/jobs/calc_userstats.php`

the database is on a webhost, I can't turn it off. If the connection with the database is possible, it does not reconnect?

**Comment by Newcomer1989** [comment]
and again..

> MySQL server has gone away

This hasn't to do with an update of the Ranksystem. When your database isn't reachable, the bot can't read/write data into it. Offline databases are a problem for each web application!
The Ranksystem bot trys to reconnect in some cases, which we enabled with the last versions. Currently we are not catching each situation to handle the reconnect. In this case the Ranksystem bot stops and you need to restart it manually or by shedule. It should work normally after, when your database is working fine.

If the bot isn't working correctly, while the database is doing it, we would need more information! Then please use our template issue and answers the things [there](https://github.com/Newcomer1989/TSN-Ranksystem/issues/new?assignees=&labels=&template=bug-report--en-.md&title=). With posting only one error line and nothing else we are not able to help you!

When you have problems with multiple database offline times, you should contact your hosting provider.
