### ISSUE TITLE
keien verifizierungsmail

### ISSUE THREAD

**Issue by DSDV** [Newcomer1989/TSN-Ranksystem#802]
Hallo,

habe auf der Website versucht eine Botinstanz zu beantragen. 
leider kommt die automatische verifizierungsmail nicht an.

Mailanbieter: GMX
Spamfilter: geprüft und auch auf aus gestellt
- (habe auch direkt spam mails bekommen -.-)

donate auch gerne wenn man damit schneller zu einer instanz kommt ;)

lg

**Comment by Newcomer1989** [comment]
Das kann immer ein paar Minuten dauern, bis die Mails geprüft und zugestellt wurden.

Wann genau wurde dieser denn beantragt und mit welchem Nicknamen? Der Nickname kann gerne zu teilen unkenntlich gemacht werden. Wenn wir 2-3 Zeichen erkennen, dürfte es für eine Zuordnung ausreichen.

**Comment by DSDV** [comment]
hi,
gute frage wann das erste mal gestern/heute waren auf jedenfall die letzen Versuche.
+DS_DV+ ist mein Nickname ;) (wie auf dem Avatar bzw soweit es github zuließ halt auch hier

**Comment by Newcomer1989** [comment]
Einen solchen Request kann ich nicht finden.

Wo wurde dieser denn abgeschickt? hier?
https://ts-ranksystem.com/#hosting

Was erhälst / hast du denn als Nachricht beim Abschicken deiner Anfrage auf der Webseite erhalten?

Bei mir sieht das dann wie folgt aus
https://imgur.com/5XzmGyU

Die E-Mail kommt auch direkt an. Betreff "TSN Ranksystem - Verification" vom Absender "TSN Ranksystem - admin@ts-n.net"

**Comment by DSDV** [comment]
öhm gute frage ich kann versuchen eine neue zu erstellen. 
wäre es möglich das ihr manuel einen accoutn erstellt ? (ich donate so oder so gern eine tasse kaffee :D)
