### ISSUE TITLE
Undefined index: last_snapshot_id

### ISSUE THREAD

**Issue by c0mputern1k** [Newcomer1989/TSN-Ranksystem#807]
Beschreibung | unterhalb ausfüllen
-- | --
Ranksystem Version | 1.3._15_
Nutzt du TeamSpeak oder TeaSpeak? | TeamSpeak
Link zu deiner Ranksystem Statistik Seite | _http://ranking.c0mputern1k.de/stats/_
Pastebin Link zu deiner Ranksystem Log *¹ | https://pastebin.com/iYTx8bvr

---

### 1) Was hast du getan?

Ich habe das System ausgesetzt und auch die Verbindung vom Bot in meiner ServerQuery gefunden.

### 2) Was war deine Erwartung?

Das die Stats geladen werden.

### 3) Was ist stattdessen passiert?

Sobald ich auf die Stats-Seite klicke raucht der Bot ab und ich bekomme die gezeigten Fehler aus dem Pastebin.

---

#### *¹ Ranksystem Log - HOW-TO
- Wechsel den Log-Level zu `6 - Debug` (-> Webinterface -> Anderes -> Log-Level).
- Wechsel die Sprache zu `EN english` (-> Webinterface -> Anderes -> Sprache).
- Starte den Ranksystem Bot neu und lasse ihn für mind. 10 Minuten laufen (-> Webinterface -> Start / Stop Bot -> Bot neu starten).
- Kopiere einen Auszug aus der Ranksystem Log, welche mindestens auch den letzten Neustart enthält (-> Webinterface -> Start / Stop Bot -> unten).
- Bitte nutze https://pastebin.com/ um die Log zu teilen.

**Comment by Newcomer1989** [comment]
Es sieht so aus, als würde es sich um eine frische Installation handelt.

Es wurden aber wohl nicht die offiziellen Sourcen benutzt.

Bitte das Ranksystem noch einmal neu installieren. Den Download bitte von hier mit Version 1.3.15 durchführen https://ts-ranksystem.com/#download

**Comment by c0mputern1k** [comment]
Im using this image for the docker env https://hub.docker.com/r/kourgiantakis/docker-teamspeak-ranksystem

**Comment by c0mputern1k** [comment]
2021 with a great start! I did it :)
http://ranking.c0mputern1k.de/

I will try to make a pr if you want the docker.compose.yml

**Comment by Newcomer1989** [comment]
Nice to hear, it is working.
