### ISSUE TITLE
Opt-In for submitting data to ts-n.net 

### ISSUE THREAD

**Issue by JVMerkle** [Newcomer1989/TSN-Ranksystem#811]
***1) I am referring to the following existing feature:***
Retrieving the latest rank system version via calc_serverstats() (calc_serverstats.php) from `ts-n.net`.

***2) What do you want to add or change on it?***
I want an opt-in process to enable or disable the submission of data to `ts-n.net`.
This includes:
- Current rank system version
- Operating system
- Operating system version
- PHP version
- Database type
- Teamspeak host address
- Teamspeak voice port
- Absolute path of the rank system
- Total user count
- Daily user count
- Weekly user count
- Monthly user count
- Quaterly user count
- Weekly online time
- Monthly online time
- Total active time
- Total inactive time
- Teamspeak server version
- Database server version

Furthermore I recommend you to shrink this data to the the absolute minimum of required data (runtime information only, not rank system statistics...)
 
***3) What would be the benefit?***
Transparency. I understand that you want/need runtime information, but you should write that down somewhere visible at least.

**Comment by DSDV** [comment]
isnt hat data only sent to the host of the rank system? 
if you dont want it sent to a third party you can selfhost it. 
Also if you selfhost you can run more advanced cleanup jobs on your database ;)

**Comment by JVMerkle** [comment]
This data is sent to the `ts-n.net` server regardless of self hosting (I am self hosting the rank system). I want the possibility to disable this behavior.

**Comment by DSDV** [comment]
There i agree with you. 
Especialy since at least we in the EU should care about data privacy (:

**Comment by DSDV** [comment]
> 
> 
> This data is sent to the `ts-n.net` server regardless of self hosting (I am self hosting the rank system). I want the possibility to disable this behavior.

as workaround you could try to block the domain on your server via UFW or other firewall solutions

**Comment by Newcomer1989** [comment]
We will check the information sent to the update server and as the case may be reduce it with an upcoming release.

However, some information such as version levels are inevitably required to ensure the functionality of the bot. We will therefore not be able to implement an opt-in variant.
The bot is completely open-source, so it is not a secret what information will be send.

Also, this does not violate the EU GDPR. No personal information is requested or transmitted here. It is public information, which is also displayed on the statistics page.

What information do you consider critical and for what reason?

With the next update we will delete the following position, because it is no longer needed:
- Absolute path of the rank system

**Comment by DSDV** [comment]
@Newcomer1989 
an Option to hide the "Overall statistics" Module from the Webinterface would be highly apreciated!

**Comment by Newcomer1989** [comment]
@DSDV
Please stay by topic of this thread.

**Comment by DSDV** [comment]
"Opt-In for submitting data" is literally in the title ... even tho its to the world and not only a specific domain.

**Comment by JVMerkle** [comment]
**I am fine with:**
-   Current rank system version
-   Operating system
-   Operating system version
-   PHP version
-   Database type
-   Database server version
-   Teamspeak server version
because it is useful information for development.

**I don't like:**
-   Total user count
-   Daily user count
-   Weekly user count
-   Monthly user count
-   Quaterly user count
-   Weekly online time
-   Monthly online time
-   Total active time
-   Total inactive time
because it is data "nice to have" but not essential for operating/developing your rank system.

**I very much dislike:**
-   Teamspeak host address
-   Teamspeak voice port
-   Absolute path of the rank system
because they compromise private data worth of protection to your 3rd party server, which are basically:
- a domain and thus the IP address or a potentially public IP address
- other potentially private information originating from the absolute path of the rank system (e.g. `/var/www/m_zuckerberg/ranksystem`)

The argument of the software being open source does not cut any ice here, because you can not expect people/administrators to read the source code. Put a clearly visible note in the installer or something and you are fine.

In addition I think you should give people the possibility to gain insight on the aggregation of you collected data (e.g. on your website).

**Comment by Newcomer1989** [comment]
Thx for your feedback. As already said, we will remove the root path of the Ranksystem.

Since all other information, which you named, are public on the statistics page, I can't see any problem here.

**Comment by DSDV** [comment]
@Newcomer1989 as @JVMerkle said this information dosnt have to be on the public statistics page. 
Nobdoy needs to be forced to show anything. Just let the users decide what they wont. 
If you think exposing anything is a good path than make it the default (sice you are the dev). But give your users a choice!
(a simple on off toggle would be a really good start [if you ask me everything non essential should have toogles - like cookie banners have])

**Comment by Newcomer1989** [comment]
> as @JVMerkle said this information dosnt have to be on the public statistics page.

That wasn't what JVMerkle wrote. The topic is still sending data to the update server, not the statistics page!

> But give your users a choice!

Sure.. This what you describe is a new function, which needs to be coded. This costs time. Before I code new functions, I always want to understand the profit of it.
In your case I still don't get it, why you want to hide this... and still, stop this here, please. It is off-topic! Please open a new thread for other topics.
