### ISSUE TITLE
userfriendly channel selection

### ISSUE THREAD

**Issue by Stetinac** [Newcomer1989/TSN-Ranksystem#814]
**Existing Feature**

***1) I am referring to the following existing feature:***
 Webinterface > TeamSpeak > Default Channel select

***2) What do you want to add or change on it?***
 Change Default Channel from form with channel ID to drop down menu with list of channel names.
![issue_fr](https://user-images.githubusercontent.com/63617235/104134839-6762ff00-538c-11eb-96ab-210391eba980.png)

***3) What would be the benefit?***
A simple way to select the channel where Bot connects.

**Comment by Newcomer1989** [comment]
Thx for posting this here.. This is still on our huge ToDo-list ;-)
