### ISSUE TITLE
PHP command run error: It seems the request came not from the command line! Shutting down!

### ISSUE THREAD

**Issue by Hembi** [Newcomer1989/TSN-Ranksystem#817]
Description |

This is a known error of the rank system. There are some closed issue about this error message, but no one solved.
The error message is caused by this condition in jobs/bot.php:
`if(isset($_SERVER['HTTP_HOST']) || isset($_SERVER['REMOTE_ADDR'])) {`

I run the bot with the default PHP command "php". (other/phpcommand.php).

System info:
Linux Debian
PHP 7.4.13 (alt-php74)
Apache
Behind Cloudflare

-- | --
Ranksystem Version | 1.3.15
Are you using TeamSpeak or TeaSpeak? | TeamSpeak
Pastebin Link to your Ranksystem Log *¹ | 
https://pastebin.pl/view/5f06fb3b

---

### 1) What did you do?
Try to start the bot from the webinterface with the start bot button. (URL: /ts/webinterface/bot.php)

### 2) What result did you get?
CRITICAL error message. The bot won't start.

### 3) What result did you expect?
The bot start and connect to the server.

---

**Comment by Newcomer1989** [comment]
We will add a function to the next version (1.3.18) to disable the security check (start request comes from command line).
