### ISSUE TITLE
All Down [Webinterface/Bot/TSN TS/...]

### ISSUE THREAD

**Issue by DSDV** [Newcomer1989/TSN-Ranksystem#820]
Description | Fill out below
-- | --
Ranksystem Version | 1.3._XX_
Are you using **TeamSpeak** or TeaSpeak? |
Link to your Ranksystem Stats page | https://tsn.ovh/hosted/689
Pastebin Link to your Ranksystem Log *¹ | 

---

### 1) What did you do?

nothing

### 2) What result did you get?

unhappy users 

### 3) What result did you expect?

happy users?

---

**Comment by Pepreal** [comment]
Mine is working fine https://ts-n.net/host/rs/96/stats/

**Comment by DSDV** [comment]
> 
> 
> Mine is working fine https://ts-n.net/host/rs/96/stats/

mine isn't:
https://ts-ranksystem.com/hosted/689/webinterface/
https://ts-ranksystem.com/hosted/689/stats/
https://ts-n.net/host/rs/689/webinterface/
https://ts-n.net/host/rs/689/stats/
https://tsn.ovh/hosted/689/webinterface/
https://tsn.ovh/hosted/689/stats/

**Comment by Pepreal** [comment]
Try sending email overhere to get support https://ts-n.net/en/contact.php

**Comment by DSDV** [comment]
> 
> 
> Mine is working fine https://ts-n.net/host/rs/96/stats/

thanks for the hint. but already done also replied to the automated system deletion email. 
Sadly all without respons.

**Comment by Pepreal** [comment]
They are moving servers `! We will relocate our servers to a new host in the middle of January 2021; Be sure to allow a network connection to our new IP address 193.70.102.252 (TCP port 443) to be able to receive future Ranksystem updates; the old IP address (164.132.201.2) will be reachable until the end of January 2021`

**Comment by DSDV** [comment]
yep i know they send an announcement mail back in December 2020. 
Relocation day was the 10th of January. 

anyways my instance is broken ...

**Comment by Newcomer1989** [comment]
We fixed it.. You should got a private message.

**Comment by DSDV** [comment]
Hi,

vielen dank für den Fix!

kann es sein das sich irgendetwas mit den IDs geändert hat? 

2021-01-18 19:32:03.382659   ERROR     TS3 error: 2568: insufficient client permissions (failed on i_group_member_remove_power) ; Affected user: 'V00D00' (unique Client-ID: 49qBT+GEQfCw6UWSl7y+WqxHXwE=; Client-database-ID 39705) and server group 'Level 12' (ID: 137).

dieser fehler steht 10 000 + Mal im log. 

das kam vorher nicht.

lg 

PS: noch geht mein altes Passwort.

**Comment by DSDV** [comment]
Database error: Array ( [0] => 42000 [1] => 1064 [2] => You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''97bf37fc246ccc537708f19a2618c2b96f702c6f851c42bf61821280c4b40086' at line 1 )

Das kommt beim Selbstsetzen von servergruppen oder ein CSRF error. Irgendwas scheint da noch nciht ganz rund zu laufen,
