### ISSUE TITLE
ERROR Executing SQL commands failed: Array

### ISSUE THREAD

**Issue by XeruTec** [Newcomer1989/TSN-Ranksystem#821]
*Edit: Hey! Ich habe das Problem, dass die Seite nicht richtig geladen wird. Jedes mal wenn ich versuche die Statistiken oder eine andere Seite zu öffnen wird mir bloß der Klartext ausgegeben. Leider komme ich selbst nicht drauf woran es liegt. 
```
2021-01-21 04:10:38.382632   ERROR     Executing SQL commands failed: Array
(
    [0] => 08S01
    [1] => 1053
    [2] => Server shutdown in progress
)

[21-Jan-2021 04:10:38 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to a member function fetchAll() on bool in /var/www/ranksystem/jobs/bot.php:371
Stack trace:
#0 /var/www/ranksystem/jobs/bot.php(527): run_bot()
#1 {main}
  thrown in /var/www/ranksystem/jobs/bot.php on line 371
```

Problemlösung: 
```
apt-get install php8.0-zip libapache2-mod-php php8.0-curl php8.0-xml php8.0-mysql php8.0-common php8.0-ssh2 php8.0-mbstring

apt-get install libapache2-mod-php8.0
a2enmod php8.0
systemctl restart apache2
```

Ranksystem Version | 1.3.16
Nutzt du TeamSpeak oder TeaSpeak? | Teamspeak
Link zu deiner Ranksystem Statistik Seite |
Pastebin Link zu deiner Ranksystem Log *¹ |

---

### 1) Was hast du getan?
Auf PHP 8 upgedatet. Also update und Upgrade ausgeführt. Danach habe ich das System neu booten lassen.

### 2) Was war deine Erwartung?
Dass der Bot so wie immer neu startet nachdem ich einen Reboot mache.

### 3) Was ist stattdessen passiert?
Alles ist wie gewohnt hochgefahren nur der Ranksystem Bot nicht. Als ich ins Webinterface schauen wollte, war plötzlich der Quellcode zu sehen.

**Comment by XeruTec** [comment]
Der Bot läuft nun wieder, aber ich hab immer noch das Problem, dass die Seite nicht mehr läd, sondern nur den Klartext ausgibt. Ich hab bereits Dinge probiert wie nach den PHP Modulen zu schauen, ob alles korrekt vergeben ist. Ebenso habe ich ausprobiert den Apache2 Service neuzustarten, ein reinstallieren von PHP half auch nicht… Dennoch besteht dieses Problem.

**Comment by JVMerkle** [comment]
Mit "Klartext" meinst du, das einfach der PHP Quellcode ausgegeben wird?
Du benötigst die passende `libapache2-mod-phpX.X` und muss das Apache Modul auch laden (`a2enmod phpX`)

**Comment by XeruTec** [comment]
Danke für deine Antwort!
Ich war im Teamspeak und habe dort Unterstützung bekommen. Mein Problem wurde mit folgenden Befehlen gelöst:

Um zu schauen, ob alle Pakete richtig installiert wurden, wurde diese Zeile ausgeführt
`apt-get install php8.0-zip libapache2-mod-php php8.0-curl php8.0-xml php8.0-mysql php8.0-common php8.0-ssh2 php8.0-mbstring`

Als klar war, dass alle Pakete richtig installiert wurden, kamen folgende Befehle in dieser Reihenfolge hinzu:
```
apt-get install libapache2-mod-php8.0
a2enmod php8.0
systemctl restart apache2
```
Das Paket war bereits installiert aber durch den Sprung von php7.4.14 auf php8.0 wurde php8.0 nicht mit aktiviert und das hat mir Probleme bereitet. Scheinbar gabs vorher auch schon jemanden mit dem selben Problem und deshalb ergänze ich das hier nochmal! :)
