### ISSUE TITLE
Error:  8: Undefined index: SERVER_PORT (line 123 and line 126)

### ISSUE THREAD

**Issue by freakexeuLow** [Newcomer1989/TSN-Ranksystem#822]
Ranksystem Version - 1.3.16
Nutzt du TeamSpeak oder TeaSpeak? - TeamSpeak
Pastebin Link zu deiner Ranksystem Log - [https://pastebin.com/h8XM31aZ](https://pastebin.com/h8XM31aZ)

System Infos: 
Debian 10 (Buster)
Php Version 7.4.14
MariaDB 10.3
Caddy (Webserver)
---

### 1) Was hast du getan?
Wollte ein anderen Webserber testen und habe nun Caddy. Alles andere läuft auf der Seite, nur das gespamme von dem Error der oben angehangen ist geht auf die nerven und konnte den Fehler nicht finden.

### 2) Was war deine Erwartung?
Das alles laufen tut ohne Probleme :P 

### 3) Was ist stattdessen passiert?
Beim Starten oder nicht starten wird der Error:  8: Undefined index: SERVER_PORT on line 123 in /var/www/html/****************/webinterface/_nav.php permanent im Webinterface angezeigt.

Sollte noch was fehlen an Information, werde ich Sie noch hinzufügen

**Edit:** Das kam noch dazu: 2021-01-24 15:09:53.957733   NOTICE    8: Trying to access array offset on value of type null on line 361 in /var/www/html/****************/stats/index.php

Mit freundlichen Grüßen

**Comment by JVMerkle** [comment]
It seems like Caddy does not provide the SERVER_PORT to PHP FPM. You can try to set in manually in your Caddy configuration:
https://github.com/caddyserver/caddy/issues/2952#issuecomment-689798448

**Comment by freakexeuLow** [comment]
> It seems like Caddy does not provide the SERVER_PORT to PHP FPM. You can try to set in manually in your Caddy configuration:
> [caddyserver/caddy#2952 (comment)](https://github.com/caddyserver/caddy/issues/2952#issuecomment-689798448)

Thanks for the Info...I am trying to find the file where this should be in it

**Comment by freakexeuLow** [comment]
I was able to fix the other error, now I have a white page with a bit of text (normal stats text but without header and more) on the stats page and the error is displayed.
```
2021-02-04 00:23:56.375729   NOTICE    8: Trying to access array offset on value of type null on line 361 in /var/www/html/****************/stats/index.php
2021-02-04 00:23:56.375595   NOTICE    8: Undefined offset: 0 on line 361 in /var/www/html/****************/stats/index.php
2021-02-04 00:23:51.129202   NOTICE    8: Trying to access array offset on value of type null on line 361 in /var/www/html/****************/stats/index.php
2021-02-04 00:23:51.129107   NOTICE    8: Undefined offset: 0 on line 361 in /var/www/html/****************/stats/index.php
```

**Comment by Newcomer1989** [comment]
This isn't a bad error. It is only a warning.
Seems to be, you were opening the statistics page before running the bot for the first time.
