### ISSUE TITLE
DB Export crashes the bot and produces endless loop

### ISSUE THREAD

**Issue by Timoms** [Newcomer1989/TSN-Ranksystem#823]
Description | Fill out below
-- | --
Ranksystem Version | 1.3.17
Are you using TeamSpeak or TeaSpeak? | TeamSpeak
Link to your Ranksystem Stats page | -
---

### 1) What did you do?
DB Export

### 2) What result did you get?
Endless loop trying to backup the database

### 3) What result did you expect?
Rank System should check if it has enough permissions to store the exported files

13G     /var/log/TSN <- high usage caused by the backup loop

TSN Backup -> Error -> Bot is down -> CRON starts the bot again -> database_export (val 2) restarts the backup -> crashes again -> loop

```
md5_file(/var/log/TSN/db_export_2021-02-07_19-15-13.sql.zip.HY7HY2): failed to open stream: Permission denied on line 147 in /opt/tsn/webinterface/export.php
PHP Fatal error:  Uncaught Error: Call to undefined method ZipArchive::setEncryptionName() in /opt/tsn/jobs/db_ex_imp.php:110

```
I know this issue is caused by the wrong folder permissions, nevertheless the bot should never go into an endless loop - maybe check the file / folder permissions before creating the backup and warn the user with a hint on how to fix the issue?

**Comment by Meshiikun** [comment]
Same issue here, need an urgent fix

**Comment by AlessandroPlace** [comment]
Same here, the bot is endlessly producing database exports.
The big problem is that the bot now is stopped.... So ranks are not going up.
I restarted it while it was doing his things, because it was taking 10 mins and more for a 60 users database, maybe that's the problem.
I also saw a permission error in the logs.
I need a solution for this asap.

Thanks in advance.

**Comment by Timoms** [comment]
> EDIT: In the ranksystem database i edited the timestamp of "database_export" from 2 to 0, and now it stopped the loop and it's working fine.

Thats exactly my fix too, sorry for not making it clear in the issue.
> database_export (val 2)

**Comment by Newcomer1989** [comment]
We will add a "cancel" option with the next version (1.3.18). Then it is possible to interupt the endless loop in case of problems.
