### ISSUE TITLE
Update schlägt fehl

### ISSUE THREAD

**Issue by Whitetex** [Newcomer1989/TSN-Ranksystem#824]
Beschreibung | unterhalb ausfüllen
-- | --
Ranksystem Version | 1.3._16_
Nutzt du TeamSpeak oder TeaSpeak? | Teamspeak
Link zu deiner Ranksystem Statistik Seite | _optional_
Pastebin Link zu deiner Ranksystem Log *¹ | https://pastebin.com/2kRG05g4

---

### 1) Was hast du getan?
das system wurde installiert und gestartet und sollte updaten

### 2) Was war deine Erwartung?
das system sollte normal laufen und updaten

### 3) Was ist stattdessen passiert?
der bot fällt ständig aus und das update schlägt fehl

---

#### *¹ Ranksystem Log - HOW-TO
- Wechsel den Log-Level zu `6 - Debug` (-> Webinterface -> Anderes -> Log-Level).
- Wechsel die Sprache zu `EN english` (-> Webinterface -> Anderes -> Sprache).
- Starte den Ranksystem Bot neu und lasse ihn für mind. 10 Minuten laufen (-> Webinterface -> Start / Stop Bot -> Bot neu starten).
- Kopiere einen Auszug aus der Ranksystem Log, welche mindestens auch den letzten Neustart enthält (-> Webinterface -> Start / Stop Bot -> unten).
- Bitte nutze https://pastebin.com/ um die Log zu teilen.

**Comment by JVMerkle** [comment]
`file_get_contents(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0`
In deiner PHP-Konfiguration ist `allow_url_fopen` wohl ausgeschaltet. Dadurch kann das Update nicht heruntergeladen werden.

**Comment by Whitetex** [comment]
leider bringt es nicht wirklich was allow_url_fopen zu aktivieren aber ich werde es beobachten ob eine mögliche verzögerte Reaktion möglich ist
