### ISSUE TITLE
Bot disconnected

### ISSUE THREAD

**Issue by 7quit** [Newcomer1989/TSN-Ranksystem#825]
Hallo,

der Bot stürzt ab und zu einfach ab, es kommen Undefined index Errors.
-- | --
Ranksystem Version | 1.3.17
Nutzt du TeamSpeak oder TeaSpeak? | TeamSpeak
Link zu deiner Ranksystem Statistik Seite | https://www.7quit.de/ranksystem/
Pastebin Link zu deiner Ranksystem Log *¹ | https://pastebin.com/ZLw8mZSU
                                                            **edit:** https://pastebin.com/yf8hz4nP

---

**Comment by Shad86** [comment]
Sind der Teamspeak und das ranksystem auf dem selben Server?

denn hier:

`2021-02-16 12:17:31.961806   NOTICE    2: Error while sending QUERY packet. PID=1110 on line 371 in /var/www/vhosts/7quit.de/sites/7quit/main/ranksystem/jobs/bot.php`

sieht man dass das wohl fehlschlägt (eventuell einem Verbindungsabbruch geschuldet)

Wenn das ganze sich auf dem selben Server befindet und du per Domain Verbindest, ändere das ganze auf eine lokale Verbindung (in den meisten fällen - 127.0.0.1)

Das könnte eventuell Abhilfe schaffen.

Die Notices sind erstmal nicht weiter schlimm, wir sind dabei das loggin umzustellen und hier und da fangen wir noch nicht alle unnötigen logeinträge ab.

MfG

Shad86

**Comment by 7quit** [comment]
> Sind der Teamspeak und das ranksystem auf dem selben Server?
> 
> denn hier:
> 
> `2021-02-16 12:17:31.961806 NOTICE 2: Error while sending QUERY packet. PID=1110 on line 371 in /var/www/vhosts/7quit.de/sites/7quit/main/ranksystem/jobs/bot.php`
> 
> sieht man dass das wohl fehlschlägt (eventuell einem Verbindungsabbruch geschuldet)
> 
> Wenn das ganze sich auf dem selben Server befindet und du per Domain Verbindest, ändere das ganze auf eine lokale Verbindung (in den meisten fällen - 127.0.0.1)
> 
> Das könnte eventuell Abhilfe schaffen.
> 
> Die Notices (Undefined index) sind erstmal nicht weiter schlimm, wir sind dabei das log-system umzustellen und hier und da fangen wir noch nicht alle unnötigen logeinträge ab.

Die Webseite hoste ich auf einem Webspace, also der TS und die Seite sind nicht auf einen Server.
Ich habe aber gestern Mal die IP von dem Webspace bei der TS Whitelist hinzugefügt. - Mal schauen, ob es immer noch passiert.

**Comment by 7quit** [comment]
Hallo?

**Comment by Newcomer1989** [comment]
> 2021-02-23 06:26:32.147988   NOTICE    8: PDO::query(): send of 44 bytes failed with errno=32 Broken pipe on line 371 in [..]jobs/bot.php

Auch hier liegt es an der Verbindung zur Datenbank, welche wohl verloren gegangen ist. Refers to #840
