### ISSUE TITLE
Call to undefined function get_rspath()

### ISSUE THREAD

**Issue by 201508876PMH** [Newcomer1989/TSN-Ranksystem#826]
Description | Fill out below
-- | --
Ranksystem Version | 1.3.7
Are you using TeamSpeak or TeaSpeak? | TeamSpeak 
Link to your Ranksystem Stats page | _optional_
Pastebin Link to your Ranksystem Log *¹ | https://pastebin.com/gRhu0eb0

---

### 1) What did you do?
Created new TSN bot, configured it, restarted my container 2-3 times and now i cant access the WEB UI. I've wiped the db and created the bot 4 times, but always seems to happen.

### 2) What result did you get?
WEB UI not loading. loading the webpage i get the following: 
**Fatal error**: Uncaught Error: Call to undefined function get_rspath() in /app/other/config.php:4 Stack trace: #0 /app/stats/index.php(14): require_once() #1 {main} thrown in /app/other/config.php on line 4

### 3) What result did you expect?
WEB UI loading

---

#### *¹ Ranksystem Log - HOW-TO
- Change the Log-Level to `6 - Debug` (-> Webinterface -> Other -> Log-Level).
- Change the default language to `EN english` (-> Webinterface -> Other -> Language).
- Restart the Ranksystem Bot and let it run for at least 10 minutes (-> Webinterface -> Start / Stop bot -> Restart bot).
- Add a Ranksystem-Log extract which contains all since the last restart (-> Webinterface -> Start / Stop bot -> at bottom).
- Please use https://pastebin.com/ for sharing the log.

**Comment by JVMerkle** [comment]
If you want to use the rank system with a more recent version in Docker, check this out: https://github.com/JVMerkle/TS3-Ranksystem. Please note that this solution has no automatic updates, you have to pull/update the container manually (depending on your setup).

**Comment by 201508876PMH** [comment]
@JVMerkle Thank you, ill give yours a shot ;)

**Comment by 201508876PMH** [comment]
I tried your docker repo, which im dying to get to work, but im getting the following error logs:
`AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.11. Set the 'ServerName' directive globally to suppress this message
(13)Permission denied: AH00072: make_sock: could not bind to address 0.0.0.0:80
no listening sockets available, shutting down
AH00015: Unable to open logs`

**Comment by JVMerkle** [comment]
How do you start the docker container? Do you have another application running on port 80 already?

**Comment by 201508876PMH** [comment]
I've mapped the container port (8080) to a self defined one (8765). My domain is https://tsrank.pmh-unraid.dk/, which i've set to the BASE_HREF env

**Comment by JVMerkle** [comment]
Please retry with `jvmerkle/ts3-ranksystem:v1.0.5` or `jvmerkle/ts3-ranksystem:latest`.
Your `BASE_HREF` should however be `/`. Also note that the container is exposing port 80, so you have to map port 8765 to port 80.

**Comment by 201508876PMH** [comment]
That *kinda *worked! I managed to create my db and from that i closed the
container and removed the INSTALL_MODEenv. When i launch the container
again and access (https://tsrank.pmh-unraid.dk/webinterface/bot.php) i get
the following error:
[image: error.png]
[image: logs.PNG]


Den ons. 17. feb. 2021 kl. 16.53 skrev Julian Merkle <
notifications@github.com>:

**Comment by JVMerkle** [comment]
Weird. You successfully completed the installation (and thus reached the database server)? The connection to the database should work regardless of `INSTALL_MODE`. Are you deploying with docker-compose? `DB_HOST` must match the database server host, that's usually either `localhost` or the container name in a docker-compose setup.

**Comment by 201508876PMH** [comment]
hmm no i'm not using docker compose. Would this be the correct data? The ip
is the container ip (which i know changes), but what would i write?
[image: Capture.PNG]


Den ons. 17. feb. 2021 kl. 17.20 skrev Julian Merkle <
notifications@github.com>:

**Comment by JVMerkle** [comment]
Unfortunately I can not see your screenshot.

**Comment by 201508876PMH** [comment]
Den ons. 17. feb. 2021 kl. 17.28 skrev Julian Merkle <
notifications@github.com>:

**Comment by 201508876PMH** [comment]
Furthermore, i dont know if this has any effect:

Den ons. 17. feb. 2021 kl. 17.32 skrev Peter Hoveling <
201508876pmh@gmail.com>:

**Comment by JVMerkle** [comment]
I can still see no screenshots. Please upload them on https://github.com/Newcomer1989/TSN-Ranksystem/issues/826 directly.

**Comment by 201508876PMH** [comment]
![Capture](https://user-images.githubusercontent.com/42763743/108236076-c9124800-7146-11eb-9d38-bbef3489d50f.PNG)
![website](https://user-images.githubusercontent.com/42763743/108236093-cc0d3880-7146-11eb-97d5-0269bd0161c1.PNG)

**Comment by JVMerkle** [comment]
On which machine is your database running? On the same machine? If so use DB host address `localhost`.

**Comment by 201508876PMH** [comment]
ye fixed the host address. Its not my local machine port 3306..which works.
But i still get the same error as shown before :/

Den ons. 17. feb. 2021 kl. 17.42 skrev Julian Merkle <
notifications@github.com>:

**Comment by 201508876PMH** [comment]
![error](https://user-images.githubusercontent.com/42763743/108237239-fad7de80-7147-11eb-8bec-cf792eef9e6c.png)
![logs](https://user-images.githubusercontent.com/42763743/108237246-fc090b80-7147-11eb-8e36-da37a84cce89.PNG)

**Comment by 201508876PMH** [comment]
And boom it works! If your image is better than the last, i should now be able to close the different containers and have them working on reboot :D. I'lll write back in moment

**Comment by 201508876PMH** [comment]
@JVMerkle it seems to be working! Thank you for taking the time to help me. You made my day 🥇

**Comment by JVMerkle** [comment]
Glad to hear that. You're welcome :)
