### ISSUE TITLE
Bot startet und beendet sich direkt wieder

### ISSUE THREAD

**Issue by SgtDino** [Newcomer1989/TSN-Ranksystem#827]
Beschreibung | unterhalb ausfüllen
-- | --
Ranksystem Version | 1.3.17
Nutzt du TeamSpeak oder TeaSpeak? | Teamspeak
Link zu deiner Ranksystem Statistik Seite | _optional_
Pastebin Link zu deiner Ranksystem Log *¹ | https://pastebin.com/R0zZzdcm

---

### 1) Was hast du getan?
Den Bot mit den Teamspeak Daten gestartet

### 2) Was war deine Erwartung?
Das der Bot sich mit dem TS verbindet und ich von dort aus den Admin setzen kann

### 3) Was ist stattdessen passiert?
Der Bot ist nach 3-4 Sekunden wieder Offline weil er sich selbständig Heruntergefahren hat.

---

**Comment by Newcomer1989** [comment]
Das Ranksystem legt in das Verzeichnis `logs/` eine Datei namens `pid`. Dafür benötigt der Prozess entsprechende Berechtigung.
In diese Datei wird die Prozess-ID des Ranksystem Bots abgelegt. 

Fehlt diese Datei oder wird der Prozess nicht mehr gefunden, stoppt der Bot mit der Meldung wie in beiliegender Log zu sehen.
