### ISSUE TITLE
Bot Stürzt Täglich zur selben Zeit ab

### ISSUE THREAD

**Issue by Whitetex** [Newcomer1989/TSN-Ranksystem#828]
Beschreibung | unterhalb ausfüllen
-- | --
Ranksystem Version | 1.3._17_
Nutzt du TeamSpeak oder TeaSpeak? | Teamspeak
Link zu deiner Ranksystem Statistik Seite | _optional_
Pastebin Link zu deiner Ranksystem Log *¹ | https://pastebin.com/3ikpsycr

---

### 1) Was hast du getan?
Keine Besondere Interaktion

### 2) Was war deine Erwartung?
Bot sollte normal laufen

### 3) Was ist stattdessen passiert?
Jeden Tag gegen 00:00Uhr Stürzt der Bot ab uns Startet nicht automatisch neu

---

#### *¹ Ranksystem Log - HOW-TO
- Wechsel den Log-Level zu `6 - Debug` (-> Webinterface -> Anderes -> Log-Level).
- Wechsel die Sprache zu `EN english` (-> Webinterface -> Anderes -> Sprache).
- Starte den Ranksystem Bot neu und lasse ihn für mind. 10 Minuten laufen (-> Webinterface -> Start / Stop Bot -> Bot neu starten).
- Kopiere einen Auszug aus der Ranksystem Log, welche mindestens auch den letzten Neustart enthält (-> Webinterface -> Start / Stop Bot -> unten).
- Bitte nutze https://pastebin.com/ um die Log zu teilen.

**Comment by Shad86** [comment]
Wenn dies jeden Tag zur selben Zeit passiert klingt mir das sehr nach einer systemseitigen Geschichte

Wir haben zwar ein paar checks im bot selbst inzwischen drin aber das hier, sollte eig. Abhilfe schaffen:

**User muss eventuell angepasst werden, wenn nicht der Standart-User verwendet wird**

> A cronjob is good for keep the bot alive:
> 
> */10 * * * * sudo -u www-data php /path/to/your/ranksystem/worker.php check >/dev/null 2>&1
> 

(Quelle):https://github.com/Newcomer1989/TSN-Ranksystem/wiki/%5BLinux%5D-Install-Requirements-and-Instructions#hints

Dieser Cronjob führt dazu das alle 10min. überprüft wird ob der bot läuft und falls nicht, wird dieser dann gestartet

MfG

Shad86

**Comment by Whitetex** [comment]
ok danke ich werde es beobachten und mich nochmal melden falls es nicht funktioniert
