### ISSUE TITLE
Ranksystem Bot stoppt automatisch

### ISSUE THREAD

**Issue by GGON187** [Newcomer1989/TSN-Ranksystem#829]
Beschreibung | unterhalb ausfüllen
-- | --
Ranksystem Version | 1.3.17
Nutzt du TeamSpeak oder TeaSpeak? | Teamspeak
Link zu deiner Ranksystem Statistik Seite | http://c-shark.de/rank/stats/
Pastebin Link zu deiner Ranksystem Log *¹ | https://pastebin.com/h0EJhqSx

---

### 1) Was hast du getan?
Das Ranksystem gestartet

### 2) Was war deine Erwartung?
Das der Bot auf dem TS-Server die Ranks ändert

### 3) Was ist stattdessen passiert?
Nach einer unbestimmten Zeit geht der bot einfach aus, ohne irgendwelche error Nachrichten

---

#### *¹ Ranksystem Log - HOW-TO
- Wechsel den Log-Level zu `6 - Debug` (-> Webinterface -> Anderes -> Log-Level).
- Wechsel die Sprache zu `EN english` (-> Webinterface -> Anderes -> Sprache).
- Starte den Ranksystem Bot neu und lasse ihn für mind. 10 Minuten laufen (-> Webinterface -> Start / Stop Bot -> Bot neu starten).
- Kopiere einen Auszug aus der Ranksystem Log, welche mindestens auch den letzten Neustart enthält (-> Webinterface -> Start / Stop Bot -> unten).
- Bitte nutze https://pastebin.com/ um die Log zu teilen.

**Comment by Rungne** [comment]
Richte am besten ein Cronjob als Root ein der den Bot alle Stunde neu startet dann hast du dass Problem nicht mehr.

Beispiel : `1 * * * * sudo -u www-data php /var/www/html/tsranking/worker.php restart >/dev/null 2>&1`

Cheers.

**Comment by Newcomer1989** [comment]
Auf Windows wäre das natürlich dann ein Task, kein Cronjob. Genau das hilft aber natürlich.

Ansonsten kann man natürlich auch noch nach der Ursache forschen. Es sich so aus, als ob das beenden des Bots von außen kommt. Hier am besten mal beobachten, ob man eine bestimmte Systematik erkennen kann. Z.B. erfolgt das Beenden zu einer bestimmten Uhrzeit oder nach einer bestimmten Laufzeit, etc.
