### ISSUE TITLE
Bot disconnects after exactly 10 mins

### ISSUE THREAD

**Issue by mightyBroccoli** [Newcomer1989/TSN-Ranksystem#83]
I just upgraded my bot and changed nothing I just followed the steps for upgrading on your page. The bot connects and everything works fine. Nothing in the Bot log file or the server protocoll from teamspeak.
```
2016-08-21 02:22:19.729849   INFO      Initialize Bot...
2016-08-21 02:22:19.737542   INFO      Check Ranksystem database for updates.
2016-08-21 02:22:19.737723   INFO        No newer version detected; Database check finished.
2016-08-21 02:22:19.738127   INFO        Ranksystem Version: 1.1.0
2016-08-21 02:22:19.738214   INFO      Connect to TS3 Server (Address: ".de" Voice-Port: "9987" Query-Port: "10011").
2016-08-21 02:22:19.767746   INFO        Conenction to TS3 Server established.
2016-08-21 02:22:19.771587   NOTICE      No channel defined where the Ranksystem should be entered.
2016-08-21 02:22:19.771752   INFO      Bot starts now his work!
```
```
21.08.2016 02:22:19	VirtualServer	Info	query client connected 'serveradmin from '(id:1)	
21.08.2016 02:32:19	VirtualServerBase	Info	query client disconnected 'RankBot'(id:1) reason 'reasonmsg=connection lost'	
```

Every time exactly 10 minutes.

**Comment by Shad86** [comment]
> 21.08.2016 02:32:19 VirtualServerBase   Info    query client disconnected 'RankBot'(id:1) reason 'reasonmsg=connection lost'

if its exactly 10 min. do you have a cronjob running? and how does this cronjob look like?

**Comment by mightyBroccoli** [comment]
Yes i do have a cronjob running.
`*/5 * * * * php /var/www/.de/ranksystem/worker.php check >/dev/null 2>&1`
The instruction had this cronjob recommended. Now after the bot disconnects every 10 mins I just added 
`*/9 * * * * php /var/www/.de/ranksystem/worker.php restart >/dev/null 2>&1` to compensate for the disconnect.

I am runnning Debian Jessie with 
> PHP 5.6.24-0+deb8u1 (cli) (built: Jul 26 2016 08:17:07)
> Copyright (c) 1997-2016 The PHP Group
> Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
>     with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

**Comment by Shad86** [comment]
Hm... Maybe this helps you:

http://ts-n.net/ranksystem.php scroll a little bit down

there is a line with "Installation Linux:"

and its not directly a thing about starting it just with "another user" you have to start it with the webuser if you didnt really have created one but apache is installed you have to chown the ranksystem folder to the webuser

for example (in most case if all is on standart this should usually work):

[AS AN SECOND ADVISE THATS JUST AN EXAMPLE PLS EDIT THE THINGS TO YOUR RIGHT PATHS]

go to your webfolder

cd /var/www OR cd /var/www/html

then

chown www-data:www-data -Rf ranksystem/

after that you can start the bot in the right way with following command:

sudo -u www-data php /path/to/your/websever/path/to/ranksystem/worker.php start

cronjob:

(In vim you have to press "i" to be able to edit the text) (on nano you just can paste the following at the end)

[PLS Change all things to your right paths!!!!]

crontab -e

*/10 * * * * sudo -u www-data php /path/to/your/websever/path/to/ranksystem/worker.php check >/dev/null 2>&1

If Sudo isnt installed:

Debian: apt-get install sudo
CentOS 6.5: yum install sudo

i hope that helps

regards

Shad86

**Comment by Shad86** [comment]
> Edit:
> The funny part ist the bot is running even when he supposedly is not running. The bot disconnects but the process is still running. When you issue worker.php status you get The Bot seems to be running. Thats why the worker.php check command is not restarting the bot.
> 
> I hope I made my point clear :8ball:

Didnt know when you edit it but just follow my instructions Seen on my answer, dont start this service as root it will cause problems (bot is not right starting,dc, and so on)

Pls always use a webuser

**Comment by mightyBroccoli** [comment]
I installed it correctly and all the files are owned by the webuser. The cronjob is copied from the crontab of my webuser.

**Comment by mightyBroccoli** [comment]
Ok possibly I got it fixed.
My system informed my that the update is ready. I did the update and everything. I updated to commit `17aa492893abeef3dc18d6fb5d92d6630bd4ec15` which is the first 1.1.0 release.
The problem starts when 1.1.0 got re-released with changed files, and after that another re-release with changed files. Those version numbers are there for a reason. You could have possibly changed the release title to 1.1.0.1 or something.
Now with latest 1.1.0 `e20f08f8b3f64e5f3c958d470739b849acd087b8` the bot is working and everything is fine. 
I dug into the php files and some bootstrap was not there anymore and the bot tried to call it until after 10 mins the bot gave up and lost the connection.
