### ISSUE TITLE
NOTICE    8: Undefined index: i2162908975 on line 102 /public_html/rank/jobs/update_groups.php

### ISSUE THREAD

**Issue by Bealze** [Newcomer1989/TSN-Ranksystem#832]
Description | Fill out below
-- | --
Ranksystem Version | 1.3._17_
- TeamSpeak 
Link to your Ranksystem Stats page | _optional_  https://rank.nafigg.com/stats/
Pastebin Link to your Ranksystem Log *¹ | https://pastebin.com/ARDc0XuF
---

### 2) What result did you get? this also on top of addon top section add server group setup section
 Array ( [0] => 42000 [1] => 1064 [2] => You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''a5fff1072d51f1044d7cc130bf45b293b91132db96879eeb7177522d1472cebd' at line 1 )

### 3) What result did you expect? not this

---

#### *¹ Ranksystem Log - HOW-TO
- Change the Log-Level to `6 - Debug` (-> Webinterface -> Other -> Log-Level).
- Change the default language to `EN english` (-> Webinterface -> Other -> Language).
- Restart the Ranksystem Bot and let it run for at least 10 minutes (-> Webinterface -> Start / Stop bot -> Restart bot).
- Add a Ranksystem-Log extract which contains all since the last restart (-> Webinterface -> Start / Stop bot -> at bottom).
- Please use https://pastebin.com/ for sharing the log.

**Comment by Newcomer1989** [comment]
Will be fixed with upcoming release 1.3.20
