### ISSUE TITLE
Parse data from user table into channel's description.

### ISSUE THREAD

**Issue by rackieMods** [Newcomer1989/TSN-Ranksystem#837]
**New Feature**
Hey, so I wanted to ask if it's possible to get data from user table (specifically count column) and parse it to some channel's description every x minutes. I wanted to create a channel with top 10 in description, but I'm not familiar with php.

EDIT: Or rewrite existing function that parses data into database to also write it in channel's description in same interval.

**Comment by Newcomer1989** [comment]
This could be done as 3rd party application with the API of the Ranksystem. 

An API request could looks like

https://ts-n.net/ranksystem_dev/api/?apikey=t8c6wvpi9cjc4k1bj9y42t0dtpedfsadtcyjt2xxbybdgg04l1dogxywwvoegsn5&userstats&all&sort=(count_month-idle_month)&order=desc&limit=10

| URL Parameter  | Description |
| ------------- | ------------- |
| &apikey | Your individual API key, which do you create inside the webinterface |
| &userstats  | Output user and their statistics |
| &all | Do not filter user; output all |
| &sort=(count_month-idle_month) | Sort the output by the active time of the last month |
| &order=desc | Sort the output by descending to get the biggest ones |
| &limit=10 | Limit the entries by 10 |

Here you get the 10 user with the biggest active time in the last month.<br><br><br>

We could also imagine to build something like this as an addon. It is added to our Wish/ToDo-list. Not ETA yet!

**Comment by Newcomer1989** [comment]
an add-on 'Channelinfo Toplist' is still part since release 1.3.18.. should be done, I guess
