### ISSUE TITLE
NOTICE    8: Undefined index: i1341897266 on line 102 in /var/www/html/rankyhh/jobs/update_groups.php

### ISSUE THREAD

**Issue by Le4ft** [Newcomer1989/TSN-Ranksystem#838]
Description | Fill out below
-- | --
Ranksystem Version | 1.3.17
Are you using TeamSpeak or TeaSpeak? | TeaSpeak
Link to your Ranksystem Stats page | http://le4ft.eu/rankyhh/stats/
Pastebin Link to your Ranksystem Log *¹ | https://pastebin.com/U9QPwFQE

---

**Comment by Newcomer1989** [comment]
There are missing important log parts and also a few more side notes.

When the bot is running, you can try the bot command "!reloadicons". Send this to the query user of the Ranksystem. It should also be fine, when you send this message to the same channel chat.
