### ISSUE TITLE
Installation des neuen Ranksystem

### ISSUE THREAD

**Issue by PsychoMonster** [Newcomer1989/TSN-Ranksystem#84]
Hallo Leute

Ich habe mit das neue Ranksystem neu Installiert. Habe meinen VPS Server reinstalliert und das neue Ranksystem wie auf 'http://ts-n.net/ranksystem.php' installiert. Habe die Install.php geöffnet und alles nach Anleitung eingebaut. Nach dem ich die Datenbank installiert habe und einen WebInterface User eingetragen hab bleibt bei punkt 3 alles schwarz, ich kann es nicht weiter Konfigurieren. Hoffe das mir jemand helfen kann. 

Freundliche Grüße

Psychomonster

**Comment by Shad86** [comment]
Hast du die neueste Version? Es gab ein "Re-release" gestern da ein paar Dateien gefehlt hatten (da ich nicht weiß wann du es runtergeladen hast)

schau mal im ranksystem ordner nach ob dort alle Ordner vorhanden sind (avatars, icons and logs)

Falls nicht sollte es schon reichen die Ordner manuell anzulegen.

(Falls es dennoch nicht klappt mit ner Neuinstallation vom ranksystem versuchen).


Dann wäre noch gut zu wissen welche php Version auf deinem system installiert ist.

`php -v` (php cli muss dafür installiert sein) falls dies nicht der fall ist versuch es  hiermit `php -i | grep 'PHP Version'` oder dpkg -l | grep php

5.5.0 muss es mindestens sein

**Comment by PsychoMonster** [comment]
Danke Shad86 hat leider nichts gebracht, Punkt 3 bei der Installation blieb immer noch schwarz. Habe dann die Version 1.0.2 wieder installiert sie lief auch und aufeinmal bekam ich die 'Fehler 0 invalid reply from the server' Was sie bedeutet weiß ich aber ich weiß nicht was ich machen soll. ich habe alles richtig eingetragen im Webinterface. Hoffe mir kann einer helfen.

**Comment by Newcomer1989** [comment]
Das klingt sehr danach, dass die PHP Version kleiner 5.5.0 ist!

Nochmals die Frage von Shad86 wiederholt: Welche PHP Version ist bei dir im Einsatz?

**Comment by PsychoMonster** [comment]
5.5.0

**Comment by Newcomer1989** [comment]
Problem behoben via Remote Session.

Es waren zwei PHP Versionen auf dem Server installiert. Über die Shell wurde die Version 5.5.38 genutzt, über die Webseite allerdings eine 5.3.X Version. Also eine im Ranksystem 1.1.0 nicht mehr unterstützte Version. Ermitteln ließ sich dies mit einer PHP Datei mit folgendem Inhalt und Aufruf via Browser:
```
<?PHP
phpinfo();
?>
```

Das Problem 'Fehler 0 invalid reply from the server' war ein ban. Aufgrund der Flood Protection wurde die IP Adresse des Webhosts gebannt. Ermittelbar war dieses mit einem TCP-Dump auf dem Webhost:
`tcpdump -nXvvv "src host xxx.xxx.xxx.xxx"`
xxx.xxx.xxx.xxx zu ersetzen mit der IP des TS3 Servers.

Ein whitelisting der Webhost IP hatte geholfen.
