### ISSUE TITLE
Ranksystem Bot crasht dauernd

### ISSUE THREAD

**Issue by 7quit** [Newcomer1989/TSN-Ranksystem#840]
-- | --
Ranksystem Version | 1.3._17_
Nutzt du TeamSpeak oder TeaSpeak? | TeamSpeak
Link zu deiner Ranksystem Statistik Seite | _https://www.7quit.de/ranksystem_
Pastebin Link zu deiner Ranksystem Log *¹ | https://pastebin.com/nJv9vFLS

---

### 1) Was hast du getan?
Ich habe den Bot gestartet

### 2) Was war deine Erwartung?
Dass der Bot nicht ab und zu crasht...

### 3) Was ist stattdessen passiert?
Der Bot crasht ab und zu....

Das Webinterface läuft auf einem Webspace und der TeamSpeak auf einen anderen Rootserver.
Jedoch habe ich die IP-Adresse vom Webspace zur Whitelist hinzugefügt...

---

**Comment by Newcomer1989** [comment]
> 2021-05-11 06:26:50.189156   NOTICE    8: PDO::query(): send of 44 bytes failed with errno=32 Broken pipe on line 371 in [..]

Genau, wie JVMerkle schon sagte, scheint die Datenbankverbindung weg zu sein.

Bei einem Webspace kann es damit zusammen hängen, dass der Hoster zyklisch die Dienste neu staret.

Lösung ist entweder der Cronjob, welcher bei Installation sowieso empfohlen wird oder sofern möglich das Ranksystem auf den Rootserver legen, wo auch der TeamSpeak bereits läuft.
