### ISSUE TITLE
Rangup Message bei jedem Connect?

### ISSUE THREAD

**Issue by blakedj012** [Newcomer1989/TSN-Ranksystem#843]
Ich bin schon Rang 1 und jedes Mal wenn ich auf mein Teamspeak Server connecte erhalte ich die Rang Up Nachricht? Kann man das irgendwo deaktivieren?

**Comment by Newcomer1989** [comment]
Der Bot schreibt die Nachricht nur beim Vergeben der Gruppe. Hast du diese Gruppe also nicht mehr auf dem TS (z.B. weil die Rang Gruppen als temporäre Gruppen eingestellt sind), wird das Ranksystem diese erneut vergeben.

Die Nachrichten können generell deaktiviert werden -> Webinterface -> Rank -> Nachrichten -> Rangsteigerung-Info

Ich vermute aber, dass die Gruppen die TS Permission `b_group_is_permanent` benötigen, damit sollte das Problem behoben sein.
