### ISSUE TITLE
Problem SGID

### ISSUE THREAD

**Issue by amommd** [Newcomer1989/TSN-Ranksystem#844]
Hello . I'm from Iran
Here we have to pay to get ts3 rank system
I bought a ts3 rank system panel
It was good for a while and it worked great
Some time ago I had to run the ts server backup
Now the SGID or id of the ranks in the ts server is changed and shows another number, but inside the ts3 rank system it still displays the same SG ID or the previous rank ID of the ranks.
Is there a solution to this problem?

**Comment by amommd** [comment]
Hello . I'm from Iran
Here we have to pay to get ts3 rank system
I bought a ts3 rank system panel
It was good for a while and it worked great
Some time ago I had to run the ts server backup
Now the SGID or id of the ranks in the ts server is changed and shows another number, but inside the ts3 rank system it still displays the same SG ID or the previous rank ID of the ranks.
Is there a solution to this problem?

**Comment by Newcomer1989** [comment]
> Here we have to pay to get ts3 rank system

The Ranksystem is open source (=free). We also offer a free hosting for the Ranksystem on our servers.
https://ts-ranksystem.com/#hosting


> Now the SGID or id of the ranks in the ts server is changed and shows another number, but inside the ts3 rank system it still displays the same SG ID or the previous rank ID of the ranks.
> Is there a solution to this problem?

Have a look to our Wiki in this case -> https://github.com/Newcomer1989/TSN-Ranksystem/wiki#changed-teamspeak-host--server---mitigation-old-ranksystem

To reload the groups (ID, name, icons..) you can try the bot command `!reloadgroups`. Write this to the Ranksystem query bot on your TS server; a channel chat should be fine.
This cleans the group cache. All server groups will be reloaded from the TS3 server.
