### ISSUE TITLE
Rank System Permantente Gruppen

### ISSUE THREAD

**Issue by serberer** [Newcomer1989/TSN-Ranksystem#845]
Beschreibung | unterhalb ausfüllen
-- | --
Ranksystem Version | 1.3.17
Nutzt du TeamSpeak oder TeaSpeak? |  Teamspeak
Link zu deiner Ranksystem Statistik Seite | _optional_
Pastebin Link zu deiner Ranksystem Log *¹ | 

---

### 1) Was hast du getan?
Ich habe in den Rank Definitionen Permanente Gruppen hinterlegt.

### 2) Was war deine Erwartung?
Der Server soll diese wie eine art Prestige Gruppen hinterlegen.

### 3) Was ist stattdessen passiert?
Der Bot entfernt den User aus der Gruppe, sobald der nächste Rang erricht ist.

---

#### *¹ Ranksystem Log - HOW-TO
- Wechsel den Log-Level zu `6 - Debug` (-> Webinterface -> Anderes -> Log-Level).
- Wechsel die Sprache zu `EN english` (-> Webinterface -> Anderes -> Sprache).
- Starte den Ranksystem Bot neu und lasse ihn für mind. 10 Minuten laufen (-> Webinterface -> Start / Stop Bot -> Bot neu starten).
- Kopiere einen Auszug aus der Ranksystem Log, welche mindestens auch den letzten Neustart enthält (-> Webinterface -> Start / Stop Bot -> unten).
- Bitte nutze https://pastebin.com/ um die Log zu teilen.

**Comment by Newcomer1989** [comment]
Wie genau sehen denn die Einstellungen in der Rank Definition aus?

Können wir auch eine Log zu dem Sachverhalt bekommen, damit wir es besser nachvollziehen können? Vielen Dank!

**Comment by Newcomer1989** [comment]
Leider kam hier keine Rückmeldung mehr -> Closed
