### ISSUE TITLE
password_hash algo change

### ISSUE THREAD

**Issue by TFWIsaac** [Newcomer1989/TSN-Ranksystem#846]
https://github.com/Newcomer1989/TSN-Ranksystem/blob/cf8b029a3f55d99cd9dc6135720deb5c4660ea7b/webinterface/changepassword.php#L21

Its not a Bug but its a suggestion to use the `PASSWORD_BCRYPT` option with a salt option. Maybe in further versions it could be changed.

**Comment by Newcomer1989** [comment]
We are using the algo parameter "PASSWORD_DEFAULT". This is always using the best algorithm.

Currently in this case PHP is automatically uses the bcrypt algorithm.
https://www.php.net/manual/en/function.password-hash.php

There are no changes needed or am I wrong?
