### ISSUE TITLE
Installationsproblem

### ISSUE THREAD

**Issue by DZMGBlade** [Newcomer1989/TSN-Ranksystem#849]
Beschreibung | unterhalb ausfüllen
-- | --
Ranksystem Version | 1.3._17_
Nutzt du TeamSpeak oder TeaSpeak? | Teamspeak
Link zu deiner Ranksystem Statistik Seite | nicht vorhanden
Pastebin Link zu deiner Ranksystem Log *¹ | nicht vorhanden

---

### 1) Was hast du getan?
Habe das TSN Ranksystem ganz normal installiert, jedoch bei easyname bricht er mir die verbindung zur Datenbank ab. Und bei Strato hab ichs ebenfalls probiert. Hier erscheint kein Installationsbildschirm. Es hängt bei " 1. Install database " und hab nur grauen Hintergrund.
Bei Nitrado welcher jedoch den Dienst Webspace einstellt klappte es immer wieder ohne probleme.

### 3) Was ist stattdessen passiert?

---

#### *¹ Ranksystem Log - HOW-TO
- Wechsel den Log-Level zu `6 - Debug` (-> Webinterface -> Anderes -> Log-Level).
- Wechsel die Sprache zu `EN english` (-> Webinterface -> Anderes -> Sprache).
- Starte den Ranksystem Bot neu und lasse ihn für mind. 10 Minuten laufen (-> Webinterface -> Start / Stop Bot -> Bot neu starten).
- Kopiere einen Auszug aus der Ranksystem Log, welche mindestens auch den letzten Neustart enthält (-> Webinterface -> Start / Stop Bot -> unten).
- Bitte nutze https://pastebin.com/ um die Log zu teilen.

**Comment by Shad86** [comment]
Hallo,

ich gehe jetzt mal davon aus dass das ganze auf Linux läuft,

da es ständig abbricht oder "hängt" falls du webspaces nutzt ist immer darauf zu achten das diese auch folgendes unterstützen:

 PHP 5.5.0 or higher (PHP 8 ready!)
 PHP with privileges for the command "exec"
 PHP with unlimited script execution time; especially you should check this on a webhosting

 required PHP extensions:
- PHP PDO extension
- PHP PDO MySQL driver
- PHP cURL extension
- PHP Zip extension
- PHP OpenSSL extension
- PHP SSH2 extension
- PHP mbstring extension

 network connection to the TS3 ServerQuery of your TS3 server on TCP; default port 10011
 network connection to ts-ranksystem.com (IP: 193.70.102.252 + 145.239.130.173) on TCP port 443
 optional: job scheduler (for automatically restart the Bot) like a cronjob
