### ISSUE TITLE
 failed to establish secure shell connection to server

### ISSUE THREAD

**Issue by MesoSource** [Newcomer1989/TSN-Ranksystem#850]
Beschreibung | unterhalb ausfüllen
-- | --
Ranksystem Version | 1.3.17
Nutzt du TeamSpeak oder TeaSpeak? | TeamSpeak
Link zu deiner Ranksystem Statistik Seite | _optional_
Pastebin Link zu deiner Ranksystem Log *¹ | https://hastebin.com/utuyimiciy.yaml

---

### 1) Was hast du getan?
TS Rank Installieren

### 2) Was war deine Erwartung?
Das der Bot korrekt connected

### 3) Was ist stattdessen passiert?
2021-08-25 21:53:50.824950   ERROR     Error : [0]: failed to establish secure shell connection to server '51.75.86.61:10022'
PHP SSH ist installiert und wird erkannt, Teamspeak Ini wurde auch bearbeitet.

**Comment by Newcomer1989** [comment]
Klingt danach, dass die Adresse (IP oder Port) bzw. die TS Query Zugangsdaten (User oder Passwort) falsch sind. Bitte mal prüfen.

Alternativ kann auch mal getestet werden, ob eine Verbindung ohne SSH möglich ist. Dafür natürlich den Query Port entsprechend anpassen und "TS3 Query encryption" deaktivieren.
