### ISSUE TITLE
Zeitvergabe für Offline-User

### ISSUE THREAD

**Issue by Holt31** [Newcomer1989/TSN-Ranksystem#851]
Unterscheide, ob es sich um ein bestehendes oder ein neues Feature handelt....
 
**Vorhandenes Feature**
 
***1) Ich beziehe mich auf das folgende bestehende Feature:*****
Die Zeitvergabe/abnahme von Usern
(Administration -> Zeit hinzufügen/entfernen)

***2) Was möchtest du hinzufügen oder ändern?*****
Eine Checkbox hinzufügen (o.ä.) welche erlaubt alle im Rangsystem verfügbaren User im Userfilter zu finden und nicht nur die, die gerade online sind. Ähnlich wie "unterdrücke ausgeschl. User". Allerdings geht's hier darum, dass alle User angezeigt werden.
 
***3) Was wäre der Vorteil?*****
Wenn User nicht online sind, aber eine Zeiteinstellung bekommen sollen, dann ist dies derzeit nicht möglich. Deshalb macht dieses Feature Sinn. Wenn der User online kommen würde, dann wird ihm (evtl.) der jeweilige Rang gesetzt bzw. die Zeit hinzugefügt. 

Ich habe gesehen, dass das für einige User geht, aber nicht für alle, obwohl dies in der Datenbank vorhanden sind.

**Comment by Newcomer1989** [comment]
> Eine Checkbox hinzufügen (o.ä.) welche erlaubt alle im Rangsystem verfügbaren User im Userfilter zu finden und nicht nur die, die gerade online sind. 

Ich verstehe nicht ganz. Das Ranksystem zeigt doch jetzt schon alle User an, auch die, die gerade offline sind.
Ein neues Feature wäre es, wenn wir mit einer Checkbox nur die online User anzeigen lassen würden^^

Die Zeitvergabe für Offline-User müsste auch funktionieren. Habe es eben mal getestet.

Zeit vor der Vergabe von Zeit:
![grafik](https://user-images.githubusercontent.com/11364569/147860317-e3f92b2c-fe2e-455f-9319-41c2c5959057.png)

Dann über die Admin-Funktion 6 Tage hinzugefügt. User ist und war seither offline:
![grafik](https://user-images.githubusercontent.com/11364569/147860321-3a4fedcc-4826-4c86-9b2c-2befe77e667f.png)

Die Zeit wurde hinzugefügt. Aber noch nicht abschließend bewertet, da der User nicht online war - also folglich keine Gruppe vergeben.

Sobald der User online kommt, wird instant die neue Ranggruppe vergeben.
![grafik](https://user-images.githubusercontent.com/11364569/147860345-834a1d8b-a770-4241-a564-8dab8ffb0c8c.png)

![grafik](https://user-images.githubusercontent.com/11364569/147860365-367dd0f0-0ccd-4ffc-9221-e9d7dc22f3b3.png)

**Comment by Holt31** [comment]
Ich hatte das Phänomen, dass mir am Anfang die nicht angezeigt wurden. Das hatte sich aber dann beim nächsten Restart des Bots erledigt.
Danke dir noch einmal für die Hilfe und für das Überprüfen.
