### ISSUE TITLE
API help

### ISSUE THREAD

**Issue by dracula66** [Newcomer1989/TSN-Ranksystem#853]
Hello,
i want to ask how to use api to get top users all time into php file

**Comment by Newcomer1989** [comment]
Have a look to our wiki https://github.com/Newcomer1989/TSN-Ranksystem/wiki/API

Here an example on our Dev Instance for the Top 10 User by active time (all time):

https://ts-n.net/ranksystem_dev/api/?apikey=t8c6wvpi9cjc4k1bj9y42t0dtpedfsadtcyjt2xxbybdgg04l1dogxywwvoegsn5&userstats&all&sort=(count-idle)&order=desc&limit=10&removed=0
