### ISSUE TITLE
Possible TeaSpeak missing value prevents TSN from starting

### ISSUE THREAD

**Issue by GameTech101** [Newcomer1989/TSN-Ranksystem#854]
Description | Fill out below
-- | --
Ranksystem Version | 1.3.17
Are you using TeamSpeak or TeaSpeak? | TeaSpeak
Link to your Ranksystem Stats page | (Offline for Setup and Server Changes)
Pastebin Link to your Ranksystem Log *¹ |  https://pastebin.com/1AzBicNk

---

### 1) What did you do?
New install of TSN RankSystem on Ubuntu 20.04 using mariaDB and Nginx. Followed normal setup procedure and connected to TeaSpeak server.

### 2) What result did you get?
NOTICE    8: Undefined index: virtualserver_weblist_enabled on line 339 in /var/www/html/associate/jobs/calc_serverstats.php
Repeated constantly numerous times per second, with the system unable to function as it normally does. Ranks do not propagate, users are not listed and functions do not work.

### 3) What result did you expect?
Working install connecting to TeaSpeak server.

---

**Comment by GameTech101** [comment]
I am by no means and expert and my knowledge of languages (programming and human communications) is limited so what I am going to provide may be obvious or useless information and I apologize ahead o time for it.

Since I like digging in the grave of my own issues, TeaServer does not seem to have the property virtualserver_weblist_enabled in the output when the "serverinfo" query command is run. This gives the unidentified index error as the code is looking for it to add to the SQL table record. 

After MANY hours, I went to sleep and it was still not done, but was once I returned from work, the server groups and other data has shown up in the system so I am going to assume that this error is not a show stopper and will simply be a nuisance until fixed.

If there is a known "fix" for the few people using TeaSpeak instead of TeamSpeak if someone could kindly point me in the right direction it would be very nice. Otherwise I will continue to dig my grave deeper and try to find the "correct" solution.

**Comment by Hoerli1337** [comment]
Fresh install:
```
2021-10-31 14:31:12.822733   ERROR     Executing SQL commands failed: Array
2021-10-31 14:31:12.728614   NOTICE    8: Undefined index: virtualserver_weblist_enabled on line 339 in /var/www/teaspeak-stats/jobs/calc_serverstats.php

)
    [2] => You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '`server_version`='TeaSpeak 1.5.6 [Build: 1622026409]',`user_today`=4,`user_we...' at line 1
    [1] => 1064
    [0] => 42000
```

**Comment by Newcomer1989** [comment]
It looks like the TeaSpeak server does not give a value for the `virtualserver_weblist_enabled` parameter of the server statistics.

With the next version we will check, if this value is set or not. On empty result it will set to 0 (weblist disabled).
This will be part of 1.3.18-beta-2 or the release 1.3.19 (no ETA yet).

**Comment by Newcomer1989** [comment]
Should be solved with Release 1.3.18

**Comment by Hoerli1337** [comment]
Yep works!
Have TSN also freshly installed and everything worked fine.

**Comment by Newcomer1989** [comment]
@Hoerli1337 Thx for your feedback!
