### ISSUE TITLE
Responsible disclosure policy

### ISSUE THREAD

**Issue by zidingz** [Newcomer1989/TSN-Ranksystem#855]
Hey there!

I belong to an open source security research community, and a member (@hitisec) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by JVMerkle** [comment]
Hey,

I am the maintainer of a fork at https://github.com/JVMerkle/TS3-Ranksystem. Good hint on the SECURITY.md, I'll look into that later. My contact is me {{at}} jvmerkle {{dot}} de.

If you do not intend to disclose the security issue to me that's fine. However I am highly interested in severity and the possible impact on me and my users, so I can decide on shutting down this service (temporarily).

Responses in this project vary between days and several months.
