### ISSUE TITLE
:shield: Security vulnerabilities

### ISSUE THREAD

**Issue by hitisec** [Newcomer1989/TSN-Ranksystem#856]
Hi, 
Some potential security vulnerabilities has been identified in this repository.
Please Validate reports submitted on huntr and if are valid please mark them valid there.
The report links are the following:  

https://huntr.dev/bounties/117648cc-ae46-470a-a351-ab3d91acdbba/
https://huntr.dev/bounties/55deaa9c-7ffd-49dd-bc4a-38f7fccf1644/
https://huntr.dev/bounties/aaf226b3-7138-4e2d-8340-11e05154fe7a/
https://huntr.dev/bounties/ab768b60-d52f-4b35-adc6-363294ee0f63/

**Comment by Newcomer1989** [comment]
All things are solved with Release 1.3.19. Thx for reporting them!
