### ISSUE TITLE
Teamspeak-Servergruppe(n) werden beim Ausschluss aus dem Rang-System nicht entfernt

### ISSUE THREAD

**Issue by Marcel1802** [Newcomer1989/TSN-Ranksystem#857]
Ranksystem Version 1.3.17
TeamSpeak Server v3.13.6

### Fehler rekonstruieren:

- eine Servergruppe (z.B. "Rangsystem ignorieren") erstellen
- Servergruppe zu den Rangsystem-Ausnahmen hinzufügen
- (Bot neu starten)
- Servergruppe "Rangsystem ignorieren" vergeben (ggf. auch sich selbst über das Weboverlay mithilfe des vorinstallierten Addons "Servergruppen vergeben", so habe ich das Ganze getestet)

### Verhalten

- der Benutzer wird in der Liste auf der Website nicht mehr angezeigt (wie erwartet)
- der Benutzer behält seine Servergruppe(n) im Teamspeak

### Erwartetes Verhalten

- der Benutzer erscheint auf der Website nicht mehr in der Liste **_und_** verliert seine Gruppen auf dem Teamspeak-Server

**Comment by Newcomer1989** [comment]
Es wird mit dem nächsten Release hierzu eine Option im Bereich "Rank -> Ausnahmen" geben.

**Comment by Newcomer1989** [comment]
Die Funktion ist Teil der aktuellen Beta, falls du das vorab mal probieren magst
`1.3.22-beta-1`

In die Beta kommst du über das `Webinterface -> Anderes -> Update-Channel`.

Das Update erfolgt nach Botneustart dann nach einiger Zeit automatisch. Ansonsten kann man es mit dem Bot Command `!update` beschleunigen.

Zu finden ist die neue Option unter `Webinterface -> Rank -> Ausnahmen -> entferne Gruppe`.

Gebe gerne mal Feedback, ob es passt oder wenn noch was zu ändern / verbessern wäre.

**Comment by Marcel1802** [comment]
Ich habe das Feature soweit getestet.

Der Rang wird, falls der Client online ist, direkt entfernt.
Ansonsten passiert das, sobald der Client das nächste Mal dem Server beitritt.

So habe ich mir das vorgestellt, danke.
