### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by ErfaniCeWizarD** [Newcomer1989/TSN-Ranksystem#858]
Hello.
I get this error when installing on Windows server " PHP COM and .NET (Windows only) is needed but seems not to be installed. Install PHP COM and .NET (Windows only) and try it again!
Path to your PHP config file, if one is defined and loaded: C:\xampp\php\php.ini " What's the problem ??

**Comment by Newcomer1989** [comment]
Have a look to the following wiki for Windows.
https://github.com/Newcomer1989/TSN-Ranksystem/wiki/Windows---Checklist---Bot-not-starting

You need to install the PHP COM extension, like described on point 2.

**Comment by ErfaniCeWizarD** [comment]
Error again ..

**Comment by ErfaniCeWizarD** [comment]
Fixed! Tnx!
