### ISSUE TITLE
Bot startet nicht mehr. Uncaught PDOException: SQLSTATE[42S01]

### ISSUE THREAD

**Issue by BielefeldJ** [Newcomer1989/TSN-Ranksystem#860]
Bot startet nicht. 
Ich habe heute festgestellt, dass der Bot seit dem 21.12 nicht mehr lief. Keine Ahnung wieso er offline war. Wollte den Bot dann ganz normal wieder starten, funktioniert aber nicht.

Ranksystem Version | 1.3.18
Teamspeak
mysql  Ver 8.0.25 (MySQL Community Server - GPL)
Log: https://pastebin.com/8hVBW6th

**Comment by Newcomer1989** [comment]
Mit der Version 1.3.19 wurde der Fehler gefixt. Allerdings hängt es hier schon zuvor am Update.

In der Datenbank wurde eine Tabelle `Channel` angelegt. Diese einfach komplett löschen. Danach sollte der Bot starten und auch das Update auf 1.3.19 vollziehen.

Bitte die zugehörige Datenbank aufrufen. Mit folgenden SQL Befehl kann die Tabelle gelöscht werden:
`DROP TABLE channel;`

**Comment by BielefeldJ** [comment]
Nachdem ich die Tabelle gelöscht habe, kam dieser Fehler: https://pastebin.com/DghCBaSM
Nun ist der "tabel already exists" wieder da.

Würde es Reichen, wenn ich nur die check_db.php von der neuen Version runterlade und austausche?
btw wenn ich ein Manuelles Update mache, welche Datein sollte nicht überschrieben werden?

**Comment by Newcomer1989** [comment]
Sorry, mein Fehler! Der Bot hat immer noch die alten Sourcen und rennt daher in den gleichen Fehler wieder rein, bevor er updated.

1) Bitte ändere in der Datei `jobs/check_db.php` Zeile 3 zu Version 1.3.18
`	$cfg['version_latest_available'] = '1.3.18';`

2) Starte dann den Bot neu.

Der Bot sollte somit erst einmal wieder starten ohne DB Updates durchzuführen. Er stellt dann fest, dass es eine neue Version gibt und müsste sich eigentlich auch direkt updaten. Falls nicht, kann das Update mit dem [Bot Command](https://ts-ranksystem.com/#commands) `!update` forciert werden.

Theoretisch sollte er in keinen weiteren Fehler laufen.

Du kannst uns auch gerne auf dem TS erreichen, falls noch weiter Fragen / Probleme entstehen!
TS: ts-ranksystem.com

**Comment by BielefeldJ** [comment]
Okay.
Ich habe jetzt die check_db.php von der neuen Version runtergeladen, in den jobs Ordner gelegt und die Version auf 1.3.18 geändert. Jetzt funktioniert alles. Danke!
