### ISSUE TITLE
Ranksystem negative Zahlen

### ISSUE THREAD

**Issue by TheChaosToast** [Newcomer1989/TSN-Ranksystem#861]
Hallo liebes TSN Team,

Ich habe einen User bei mir im System der schon sehr lange online ist. Leider wurde dieser User durch einen Fehler auf komplett 0 zurückgesetzt. Nun zeigt mir das Ranksystem seit 2 Tagen bei Top User des Monats und Top User der Woche negative Zahlen an. Meine Frage ist, normalisiert sich das wieder oder wie kann man das beheben?

Ich habe den Userrang wiederhergestellt. Also quasi seine alte Zeit.

Danke

**Comment by Shad86** [comment]
Ja, das ganze wird sich aber spätesten erst nach dem jeweiligen Zyklus wieder anpassen - Monat / Woche

**Comment by Newcomer1989** [comment]
Wir fangen eigentlich schon programmseitig die meisten Konstellationen ab, damit die Wochen- und Monats-stats nicht beeinflusst werden. Wenn es sich reproduzieren lässt, gerne noch einmal bescheid geben:
- wie es aussah (Ausgangslage)
- was geändert wurde
- und wie es auswirkte (Ergebnis)

Ansonsten bereinigt sich das natürlich, wie vorgenannt von Shad86, immer von alleine.
