### ISSUE TITLE
Base Table or view already exists

### ISSUE THREAD

**Issue by DerRene97** [Newcomer1989/TSN-Ranksystem#862]
Ich habe das TSN Ranksystem nun schon länger in Betrieb, auch immer ohne Probleme.
Auch jetzt lief es Wochen ohne Probleme bis plötzlich Fehler auftraten und der Bot gestoppt wurde.
Laut Log ist das ganze wohl passiert als die Datenbank auf eine neuere Version geupdatet werden sollte (?), das habe ich selber aber nicht aktiv gestartet.

Seitdem lässt sich der Bot auch nicht mehr starten.

Hier ein Auszug aus der Log:
https://pastebin.com/JbWvEspt

Wie lässt sich das beheben?

**Comment by Newcomer1989** [comment]
Mit der Version 1.3.19 wurde der Fehler gefixt.

Allerdings hängt es hier schon zuvor am Update. Der Bot hat immer noch die alten Sourcen und rennt daher in den gleichen Fehler wieder rein, bevor er updated.

1) Bitte ändere in der Datei `jobs/check_db.php` Zeile 3 zu Version `1.3.18`
`    $cfg['version_latest_available'] = '1.3.18';`

2) Starte dann den Bot neu.

Der Bot sollte somit erst einmal wieder starten ohne DB Updates durchzuführen. Er stellt dann fest, dass es eine neue Version gibt und müsste sich eigentlich auch direkt updaten. Falls nicht, kann das Update mit dem Bot Command `!update` forciert werden.

Theoretisch sollte er in keinen weiteren Fehler laufen.

Du kannst uns auch gerne auf dem TS erreichen, falls noch weiter Fragen / Probleme entstehen!
TS: ts-ranksystem.com

**Comment by DerRene97** [comment]
Leider scheint das ändern der Versionsnummer nichts zu bewirken - es werden nach wie vor die gleichen Fehler ausgegeben und er lässt sich komplett nicht starten...
Was könnte ich noch versuchen?

**Comment by Newcomer1989** [comment]
Probiere mal die Sourcen von unserer Website zu laden. -> https://ts-ranksystem.com/#download

Daraus benötigst du nur die Datei `jobs/check_db.php`. Diese einfach aus den Sourcen entnehmen und in deiner Installation überschreiben.

Damit die restlichen Dateien noch sauber aktualisiert werden, bitte wie oben beschrieben die Version auf 1.3.18 ändern und dann den Bot neu starten.

**Comment by DerRene97** [comment]
Scheint leider nichts zu bewirken, die Problematik bleibt bestehen mit gleicher Fehlermeldung

**Comment by Newcomer1989** [comment]
Das kann eigentlich nicht möglich sein. Die `jobs/check_db.php` ist die Ursache des DB-Updates, welches auf den Fehler läuft.

Wird diese mit der aktuellen Version von dem o.g. Download getauscht, tritt der Fehler nicht mehr auf. Wurde bei einem anderen User schon erfolgreich getestet.

Bitte darauf achten, dass die check_db.php vom 01.01.2022 ist.

**Comment by DerRene97** [comment]
Ich habe es nochmal probiert und tatsächlich hat es dann funktioniert.
Auch wenn ich der Meinung bin, dass ich zuvor auch bereits alles richtig gemacht haben sollte, hat sich wohl ein Fehler eingeschlichen.

Vielen Dank für die Hilfe :)
