### ISSUE TITLE
Need help - Channelinfo Toplist

### ISSUE THREAD

**Issue by NordHol** [Newcomer1989/TSN-Ranksystem#867]
There were problems with this Addon, everything works as it should, with the exception of two points, namely:

1) All users are always offline ([screenshot](https://i.imgur.com/SMxAeXG.png))
2) Does not show the channel in which the person is currently sitting ([screenshot](https://i.imgur.com/NmLBXZv.png))

Everything else works fine, what could I have done wrong or what should I do? I would be glad if someone could explain or help.

**Comment by Bealze** [comment]
for me to fix mine i had to go back  and replace the part that say domain.com with the actual domain where rank was installed.

**Comment by NordHol** [comment]
> for me to fix mine i had to go back and replace the part that say domain.com with the actual domain where rank was installed.

I tried to set the default text that was presented there in the example, this does not solve my problem

**Comment by Newcomer1989** [comment]
Is this problem still existing with the Ranksystem version 1.3.21?

**Comment by Newcomer1989** [comment]
Closed, while no response came.. feel free to answer and reopen the issue
