### ISSUE TITLE
Autostart aktivieren und cronjob per Plesk einrichten

### ISSUE THREAD

**Issue by 7quit** [Newcomer1989/TSN-Ranksystem#868]
Beschreibung | unterhalb ausfüllen
-- | --
Ranksystem Version | 1.3._19_
Nutzt du TeamSpeak oder TeaSpeak? | TeamSpeak
Link zu deiner Ranksystem Statistik Seite | _[optional](https://ts-lounge.de/stats/)_
Pastebin Link zu deiner Ranksystem Log *¹ | 

---

### 1) Was hast du getan?
Ich habe einen Cronjob per Plesk eingerichtet, damit der Bot beim crashen oder wenn er gestoppt ist, dann gestartet wird.

### 2) Was war deine Erwartung?
Ich habe gedacht, dass der Cronjob von Plesk den Bot direkt startet, sobald er aus ist oder gecrasht ist.

### 3) Was ist stattdessen passiert?
Ich bekomme eine Fehlermeldung vom Plesk Cronjob und weiß nicht, wie man den Autostart aktivieren kann.
![cea18b75f6](https://user-images.githubusercontent.com/45004106/156799591-19039d5d-f429-496a-97b1-653d4274381d.png)

---

**Comment by Newcomer1989** [comment]
Der Ranksystem Bot wurde vorher wohl über den "Stop" Befehl gestoppt. Z.B. über das Webinterface oder mit `worker.php stop`. Dabei soll genau das verhindert werden, dass der Bot "versehentlich" durch einen Job gestartet wird.

Als Startbefehl kann `worker.php start` genommen werden, damit wird ein Start immer durchgeführt, außer der Bot läuft bereits. Mit `worker.php check` wird wie zuvor beschrieben der Bot nur dann gestartet, wenn er nicht läuft und zuvor nicht mit dem Stop Befehl gestoppt wurde.
