### ISSUE TITLE
Change command prefix

### ISSUE THREAD

**Issue by caio-biondi** [Newcomer1989/TSN-Ranksystem#869]
Hi, I have two bots in my server and both use the "!" prefix. Is there anyway I could change Ranksystem's prefix? 
Thank you

**Comment by Newcomer1989** [comment]
Will be part of the next release version.

**Comment by Newcomer1989** [comment]
This function is part of the current beta release, if you want to try it out
`1.3.22-beta-1`

You can join the beta channel about `Webinterface -> Other -> Update-Channel`.

The update will be done after some time after a bot restart. You can force it with the bot command `!update`.

The new function you will find inside the `Webinterface -> TeamSpeak -> Prefix Bot-command`.

Please let us know, if it fits or there is something we could change/ improve.

**Comment by Newcomer1989** [comment]
Release 1.3.22 is out
