### ISSUE TITLE
Error on Webinterface after update to 1.1.0 - Unknown column 'last_access' in 'field list'

### ISSUE THREAD

**Issue by NothingTV** [Newcomer1989/TSN-Ranksystem#87]
Hi!

How can I import the users and configs from 1.0.2 to 1.1.0?

regards

**Comment by Shad86** [comment]
make a backup from all files (webserver and database) [just for sure]

Stop the ranksystem (also stop cronjob)

then move out dbconfig.cfg from your webserver (ranksystem) and pull all new files in the ranksystem folder

after that move the dbconfig.cfg back and start your ranksystem

regards

Shadow86

**Comment by Newcomer1989** [comment]
What Shad86 described is an regular update, like described on the official Ranksystem page.
http://ts-n.net/ranksystem.php

An Export / Import is not designated.

**Comment by NothingTV** [comment]
I tried it that way, but I receive this error when I try to open the webinterface: "Array ( [0] => 42S22 [1] => 1054 [2] => Unknown column 'last_access' in 'field list' )"

**Comment by Newcomer1989** [comment]
You started the Ranksystem before you logged in to the webinterface?

**Comment by NothingTV** [comment]
Okay, I reupload it, give the right permission and started the bot again and it works now. Thanks!
