### ISSUE TITLE
Arbeitsspeicher Auslastung hoch

### ISSUE THREAD

**Issue by Eintausendeins** [Newcomer1989/TSN-Ranksystem#870]
Beschreibung | unterhalb ausfüllen
-- | --
Ranksystem Version | 1.3.19
Nutzt du TeamSpeak oder TeaSpeak? | TeamSpeak
Link zu deiner Ranksystem Statistik Seite | _optional_
Pastebin Link zu deiner Ranksystem Log *¹ | https://pastebin.com/bUwYJfs9

---

### 1) Was hast du getan?
TSN-Bot gestartet, worker.php cronjob angelegt

### 2) Was war deine Erwartung?
/

### 3) Was ist stattdessen passiert?
Nach Sichtung der Übersicht der Prozesse in htop wurde angezeigt, dass /php /..../ranking/jobs/bot.php eine Auslastung von ~45% des Arbeitsspeichers hat. Das tritt nach ein paar (5-6) Stunden auf. Nach einem Neustart des Bots ist die Auslastung wieder gering.
Das ist im Vergleich zu dem Virenschutzprogramm clamd mit 15% gigantisch. 
Ist das normal oder liegt das an bestimmten Addons, wie "Channelinfo Topliste"?

**Comment by TheChaosToast** [comment]
Kann ich auch bestätigen. Allerdings erst nachdem unser Webserver auf PHP 8.0.1 umgestellt wurde. Unter PHP 7.4.23 lief es mit wenig RAM.

**Comment by TheChaosToast** [comment]
> Beschreibung 	unterhalb ausfüllen
> Ranksystem Version 	1.3.19
> Nutzt du TeamSpeak oder TeaSpeak? 	TeamSpeak
> Link zu deiner Ranksystem Statistik Seite 	_optional_
> Pastebin Link zu deiner Ranksystem Log *¹ 	https://pastebin.com/bUwYJfs9
> ### 1) Was hast du getan?
> 
> TSN-Bot gestartet, worker.php cronjob angelegt
> ### 2) Was war deine Erwartung?
> 
> /
> ### 3) Was ist stattdessen passiert?
> 
> Nach Sichtung der Übersicht der Prozesse in htop wurde angezeigt, dass /php /..../ranking/jobs/bot.php eine Auslastung von ~45% des Arbeitsspeichers hat. Das tritt nach ein paar (5-6) Stunden auf. Nach einem Neustart des Bots ist die Auslastung wieder gering. Das ist im Vergleich zu dem Virenschutzprogramm clamd mit 15% gigantisch. Ist das normal oder liegt das an bestimmten Addons, wie "Channelinfo Topliste"?

Versuch mal folgendes: Wenn Du die Möglichkeit hast verwende PHP Version 7.3.33. Damit ist die Last bei ca. 136 MB. Hatte nämlich das gleiche Problem. Alles was höher als PHP 7.4.X oder gar 8.X.X macht Probleme.

**Comment by Eintausendeins** [comment]
Alles klar, tatsächlich hat es das Problem (erstmal) gelöst. Vielen Dank!

**Comment by TheChaosToast** [comment]
Nicht dafür :). Freut mich das ich helfen konnte ;)
