### ISSUE TITLE
PHP Fatal error:  Uncaught TypeError: Return value of TeamSpeak3_Helper_String::offsetGet()

### ISSUE THREAD

**Issue by dakeeper** [Newcomer1989/TSN-Ranksystem#873]
Beschreibung | unterhalb ausfüllen
Ranksystem crashed. Manuelles starten geht nicht mehr.
Bot crashes
Ranksystem 1.3.20-beta-1
Nutzt du TeamSpeak oder TeaSpeak? Teamspeak
Link zu deiner Ranksystem Statistik Seite https://dakeeper.de/ts3rank/stats/
Pastebin Link zu deiner Ranksystem Log *¹ [https://pastebin.com/kktyzR7s](url)
](url)
---

### 1) Was hast du getan?
Nichts. Das Ranksystem lief jahrelang ohne probleme.

### 2) Was war deine Erwartung?
Kein Crash.

### 3) Was ist stattdessen passiert?
Crash...

---

#### *¹ Ranksystem Log - HOW-TO
- Wechsel den Log-Level zu `6 - Debug` (-> Webinterface -> Anderes -> Log-Level).
- Wechsel die Sprache zu `EN english` (-> Webinterface -> Anderes -> Sprache).
- Starte den Ranksystem Bot neu und lasse ihn für mind. 10 Minuten laufen (-> Webinterface -> Start / Stop Bot -> Bot neu starten).
- Kopiere einen Auszug aus der Ranksystem Log, welche mindestens auch den letzten Neustart enthält (-> Webinterface -> Start / Stop Bot -> unten).
- Bitte nutze https://pastebin.com/ um die Log zu teilen.

**Comment by Newcomer1989** [comment]
Das war ein Problem der Beta-1.

Zwei Lösungsmöglichkeiten:

1) PHP auf Version 8.0 oder höher aktualisieren und der Bot sollte direkt wieder laufen.

2) Die aktuellste Version von unserer Seite herunterladen (https://ts-ranksystem.com) und das Verzeichnis `libs/ts3_lib` auf dem Webspace vollständig ersetzen mit der heruntergeladenen Version.

In beiden Fällen wird der Bot nach dem erfolgreichem Neustart innerhalb weniger Stunden (ggfs. sofort) ein Update auf die Release Version von 1.3.20 ziehen.

**Comment by dakeeper** [comment]
Hallo Newcomer1989,

ich habe die 2. Variante gewählt.
Nach dem Starten des Bots bekomme ich:

  thrown in /var/www/vhosts/*****.de/httpdocs/ts3rank/jobs/db_ex_imp.php on line 123
#2 {main}
#1 /var/www/vhosts/*****.de/httpdocs/ts3rank/jobs/bot.php(547): run_bot()
#0 /var/www/vhosts/*****.de/httpdocs/ts3rank/jobs/bot.php(474): db_ex_imp()
Stack trace:
[04-Jul-2022 15:31:58 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to undefined method ZipArchive::setEncryptionName() in /var/www/vhosts/*****.de/httpdocs/ts3rank/jobs/db_ex_imp.php:123
2022-07-04 15:31:58.327926   NOTICE      Started job 'Datenbank Export'

**Comment by Newcomer1989** [comment]
PHP Zip muss installiert sein, sonst kann die genannte Fehlermeldung auftreten.

https://www.php.net/manual/en/book.zip.php

Bite mal schauen, ob die für das Ranksystem verwendete PHP Version die nötige PHP extension hat.
