### ISSUE TITLE
Channelinfo Toplist - cant turn OFF 

### ISSUE THREAD

**Issue by doman991** [Newcomer1989/TSN-Ranksystem#874]
Description | Fill out below
-- | --
Ranksystem Version | 1.3.20-hosted
Are you using TeamSpeak or TeaSpeak? | TeamSpeak 
Link to your Ranksystem Stats page | _optional_
Pastebin Link to your Ranksystem Log *¹ | https://pastebin.com/RcYZcMqm

---

### 1) What did you do?
tried new add-ons then Tried to switch off and reboot bot

### 2) What result did you get?
add-ons still ON

### 3) What result did you expect?
switch off add-ons
---

#### *¹ Ranksystem Log - HOW-TO
- Change the Log-Level to `6 - Debug` (-> Webinterface -> Other -> Log-Level).
- Change the default language to `EN english` (-> Webinterface -> Other -> Language).
- Restart the Ranksystem Bot and let it run for at least 10 minutes (-> Webinterface -> Start / Stop bot -> Restart bot).
- Add a Ranksystem-Log extract which contains all since the last restart (-> Webinterface -> Start / Stop bot -> at bottom).
- Please use https://pastebin.com/ for sharing the log.

**Comment by Newcomer1989** [comment]
What happened on saving the change on the webinterface? Which message appeared there?

For me it says, successfully saved and the switch is off after.

![grafik](https://user-images.githubusercontent.com/11364569/177873228-e3c9a9bb-db56-453d-b9c5-07b8fcef5ba2.png)

**Comment by doman991** [comment]
Sorry for making this issue and bothering you. It works as it should and i was the problem. 
Thank you for work you do.
