### ISSUE TITLE
Critical TS3 error on core function! Shutting down!

### ISSUE THREAD

**Issue by LuftigerLuca** [Newcomer1989/TSN-Ranksystem#875]
Beschreibung | unterhalb ausfüllen
-- | --
Ranksystem Version | 1.3.19
Nutzt du TeamSpeak oder TeaSpeak? | TeamSpeak
Link zu deiner Ranksystem Statistik Seite | https://ts-stats.luftiger.eu
Pastebin Link zu deiner Ranksystem Log *¹ | https://pastebin.com/3JqbG8V4

---

### 1) Was hast du getan?
Ich hab das Panel nach den Docs installiert und kann dies auch einwandfrei erreichen. 

### 2) Was war deine Erwartung?
Das ich problemlos den Bot mit meinem TeamSpeak-Server verbinden kann.

### 3) Was ist stattdessen passiert?
Der Bot hat sich kurz verbunden, ist dann aber wieder disconnected.

---

#### *¹ Ranksystem Log - HOW-TO
- Wechsel den Log-Level zu `6 - Debug` (-> Webinterface -> Anderes -> Log-Level).
- Wechsel die Sprache zu `EN english` (-> Webinterface -> Anderes -> Sprache).
- Starte den Ranksystem Bot neu und lasse ihn für mind. 10 Minuten laufen (-> Webinterface -> Start / Stop Bot -> Bot neu starten).
- Kopiere einen Auszug aus der Ranksystem Log, welche mindestens auch den letzten Neustart enthält (-> Webinterface -> Start / Stop Bot -> unten).
- Bitte nutze https://pastebin.com/ um die Log zu teilen.

**Comment by Newcomer1989** [comment]
`2022-07-07 23:09:52.587407   ERROR     Error : [0]: connection to server &#039;node.luftiger.eu:10011&#039; lost`

Das ist meist verbunden mit einem Query Ban.

Bitte die IP Adresse des Host-Systems des Bots für den TS3 Server whitelisten bzw. wenn beides auf dem gleichen System liegt, am besten per "localhost" verbinden.
