### ISSUE TITLE
Installation problem - exec function disabled

### ISSUE THREAD

**Issue by Robert08020** [Newcomer1989/TSN-Ranksystem#878]
Hello,

when I want to start the installation, above comes this exec error message.

![TS3rankingproblem](https://user-images.githubusercontent.com/51743742/188821719-dfb95a2d-3ddc-4c4a-b82b-1d3db4b10f85.png)

In the file itself it is not disabled, but when you query the function it is disabled.

**Comment by Newcomer1989** [comment]
You can create a file on your webserver to check the PHP config, which is loaded.
