### ISSUE TITLE
Can't start the ranksystem bot

### ISSUE THREAD

**Issue by QuoHun** [Newcomer1989/TSN-Ranksystem#879]
Description | Fill out below
-- | --
Ranksystem Version | 1.3._XX_
I am using TeamSpeak |
Link to your Ranksystem Stats page | _optional_
Pastebin Link to your Ranksystem Log *¹ | 

---

### 1) What did you do?

i tried to install the database on default settings

### 2) What result did you get?
![kép_2022-09-09_120651663](https://user-images.githubusercontent.com/113177074/189326295-96f2e40a-fca4-4306-9c06-db2b909c3103.png)

### 3) What result did you expect?

A working webpage? 
---

#### *¹ Ranksystem Log - HOW-TO
- Change the Log-Level to `6 - Debug` (-> Webinterface -> Other -> Log-Level).
- Change the default language to `EN english` (-> Webinterface -> Other -> Language).
- Restart the Ranksystem Bot and let it run for at least 10 minutes (-> Webinterface -> Start / Stop bot -> Restart bot).
- Add a Ranksystem-Log extract which contains all since the last restart (-> Webinterface -> Start / Stop bot -> at bottom).
- Please use https://pastebin.com/ for sharing the log.

**Comment by QuoHun** [comment]
+info i orderes a hosting from you

**Comment by Newcomer1989** [comment]
Please try it again, it should be working now 👍
