### ISSUE TITLE
Rankingsystem verbindet sich nicht mehr mit Teamspeak

### ISSUE THREAD

**Issue by UselessGeld** [Newcomer1989/TSN-Ranksystem#880]
Beschreibung | unterhalb ausfüllen
-- | --
Ranksystem Version | 1.3._20_
Ich nutze Teamspeak | 
Link zu deiner Ranksystem Statistik Seite | _optional_
Pastebin Link zu deiner Ranksystem Log *¹ | 

---

### 1) Was hast du getan?
Am Ranksystem selbst wurde nichts geändert. Das Ranksystem war plötzlich nicht mehr mit dem Teamspeak verbunden.
Meine Vermutung war, dass das Problem durch einen IP Change des Teamspeaks ausgelöst wurde, da das auch vom Zeitpunkt ungefähr hinkommt. IP wurde eigentlich überall angepasst.

### 3) Was ist stattdessen passiert?
Im Log kommen Folgende Fehlermeldungen. Hatte bei diesen Zeilen im Code nichts auffälliges gefunden.
Log: https://pastebin.com/VuVQJbfM

---

#### *¹ Ranksystem Log - HOW-TO
- Wechsel den Log-Level zu `6 - Debug` (-> Webinterface -> Anderes -> Log-Level).
- Wechsel die Sprache zu `EN english` (-> Webinterface -> Anderes -> Sprache).
- Starte den Ranksystem Bot neu und lasse ihn für mind. 10 Minuten laufen (-> Webinterface -> Start / Stop Bot -> Bot neu starten).
- Kopiere einen Auszug aus der Ranksystem Log, welche mindestens auch den letzten Neustart enthält (-> Webinterface -> Start / Stop Bot -> unten).
- Bitte nutze https://pastebin.com/ um die Log zu teilen.

**Comment by Newcomer1989** [comment]
Was steht denn als TeamSpeak Host drin? Die IP Adresse, ein DNS Name?

Am besten mal einen Screen von der Eingabe im Webinterface machen. Auf den ersten Blick sieht es so aus, als könnte da irgendein falsches Zeichen sich eingeschlichen haben.

**Comment by UselessGeld** [comment]
Als Host steht die IP drinnen
![image](https://user-images.githubusercontent.com/52463739/194727332-e5662f0f-f09c-4784-b241-87b2a6b51317.png)
