### ISSUE TITLE
$target = $_SERVER['HTTP_HOST'].rtrim(dirname($_SERVER['PHP_SELF']), '/\\').'/stats/'; sehr unschön

### ISSUE THREAD

**Issue by Timon0586** [Newcomer1989/TSN-Ranksystem#881]
Ranksystem Version | 1.3.20
Nutzt du TeamSpeak oder TeaSpeak? | TeamSpeak
Link zu deiner Ranksystem Statistik Seite | https://konoha.mirwayne.de/
Pastebin Link zu deiner Ranksystem Log *¹ | /

---

Hallöchen, ich habe das Ranksystem mal installiert. Ich bin mir nicht sicher aber ich glaube aufgrund von $target = $_SERVER['HTTP_HOST'].rtrim(dirname($_SERVER['PHP_SELF']), '/\\').'/stats/'; in der index.php sieht die URL ein wenig komisch aus. ( https://konoha.mirwayne.de/subdomains/konoha.mirwayne.de/stats/ )

Ich habe also wie gewohnt eine Subdomain erstellt und diese auch korrekt konfiguriert so dass der Ordner nicht sichtbar sein sollte (genau das gleiche tat ich bei bisher jeder subdomain die ich konfigurierte)

Nun geht aber das  Ranksystem her und macht die URL komplett kaputt. Ich hab schon versucht das  rtrim(dirname($_SERVER['PHP_SELF']) zu entfernen, aber irgendwie ohne richtigen erfolg.

Was kann ich tun damit die URL auch beim Ranksystem so aussieht wie sie aussehen sollte?

Liebe Grüße

**Comment by Newcomer1989** [comment]
Wie schon damals besprochen, dürfte das an der Webserver Konfiguration liegen. Ich wüsse nicht, was wir hier anpassen sollten/müssten.

Habe mal folgendes unter Nginx getestet.

Config des Nginx

```
server {
    server_name game.domain.de www.game.domain.de;
    root /var/www/pterodactyl/public;
[..]
```

Unter dem root-Verzeichnis gibt es folgende Struktur
```
/var/www/pterodactyl/public/test.php
/var/www/pterodactyl/public/subfolder/test.php
/var/www/pterodactyl/public/game.domain.de/test.php
```

Die test.php sieht wie folgt aus:
```
<?PHP
echo "host : ". $_SERVER['HTTP_HOST'];
echo "<br>self : ".$_SERVER['PHP_SELF'];
$target = $_SERVER['HTTP_HOST'].rtrim(dirname($_SERVER['PHP_SELF']), '/\\').'/stats/';
echo "<br>target : ".$target;
?>
```

https://game.domain.de/test.php
```
host : game.domain.de
self : /test.php
target : game.domain.de/stats/
```


https://game.domain.de/subfolder/test.php
```
host : game.domain.de
self : /subfolder/test.php
target : game.domain.de/subfolder/stats/
```


https://game.domain.de/game.domain.de/test.php
```
host : game.domain.de
self : /game.domain.de/test.php
target : game.domain.de/game.domain.de/stats/
```

D.h. der Code in der /index.php sollte eigentlich völlig in Ordnung sein und einen korrekten Redirect auf die Stats-Page machen.
