### ISSUE TITLE
View top of the week BUG

### ISSUE THREAD

**Issue by cataalin** [Newcomer1989/TSN-Ranksystem#883]
The top of the week in the index has suddenly bugged without any change, I tried to restore the DB but ranksystem autocorrects the table again for some reason, any suggestions where to look to have what happened?

![dsadada](https://user-images.githubusercontent.com/28767431/211174085-eec35316-3fdd-442b-a427-1ad8b95cf0a2.jpg)

**Comment by Shad86** [comment]
Hello,

Without any change, negative values cannot occur, so I think you have deducted time from a user, which is then resulting in negative values.

How it comes:

The rank system generates several timestamps per day, week and month, so that a statistic can be obtained at all. 

Conclusion:

The negative value should therefore normalize again after 7 days from the last point of change.

Depending on how much time you have removed, this could also occur once in the monthly statistics.

regards

Shad86

**Comment by cataalin** [comment]
> Hello,
> 
> Without any change, negative values cannot occur, so I think you have deducted time from a user, which is then resulting in negative values.
> 
> How it comes:
> 
> The rank system generates several timestamps per day, week and month, so that a statistic can be obtained at all.
> 
> Conclusion:
> 
> The negative value should therefore normalize again after 7 days from the last point of change.
> 
> Depending on how much time you have removed, this could also occur once in the monthly statistics.
> 
> regards
> 
> Shad86

oh ok, I was doing tests with myself creating groups increasing and reducing but that was 2 weeks ago or so that's why I put it to you that it happened without any change, the bot has not restarted since then, I restarted it yesterday and that is when I realized that .

**Comment by Newcomer1989** [comment]
We tried to do a fix for this values. Perhaps you can test, it helps in your case.

This function is part of the current beta release, if you want to try it out
`1.3.22-beta-3`

You can join the beta channel about `Webinterface -> Other -> Update-Channel`.

The update will be done after some time after a bot restart. You can force it with the bot command `!update`.

The new function you will find inside the `Webinterface -> TeamSpeak -> Prefix Bot-command`.

Please let us know, if it fits or there is something we could change/ improve.

After the udpate you need to wait 15 Minutes, till this values will be recalculated.

**Comment by cataalin** [comment]
> Intentamos hacer una corrección para estos valores. Tal vez puedas probar, ayuda en tu caso.
> 
> Esta función es parte de la versión beta actual, si desea probarla `1.3.22-beta-3`
> 
> Puedes unirte al canal beta sobre `Webinterface -> Other -> Update-Channel`.
> 
> La actualización se realizará después de un tiempo después de que se reinicie el bot. Puedes forzarlo con el comando bot `!update`.
> 
> La nueva función que encontrarás dentro del `Webinterface -> TeamSpeak -> Prefix Bot-command`.
> 
> Háganos saber si encaja o si hay algo que podamos cambiar/mejorar.
> 
> Después de la actualización, debe esperar 15 minutos, hasta que se vuelvan a calcular estos valores.
> 
> Y una nota al margen... Agregamos también una opción para admitir estilos individuales. Puede crear sus propios archivos de estilo (CSS) y colocarlos en la carpeta de estilos. Después de eso, puede elegirlos dentro de la interfaz web -> Otro -> estilo personalizado.
> 
> Cuando esté utilizando su propio archivo CSS, se guardará para las próximas actualizaciones.

I would try but I have a question, I have made a lot of modifications, even the totally different css, is everything going to default if I update or anything?

**Comment by Newcomer1989** [comment]
Yes, it will overwrite all files, which are part of our installation image.

**Comment by cataalin** [comment]
> Sí, sobrescribirá todos los archivos que forman parte de nuestra imagen de instalación.

there is no way to avoid that?  Taking advantage of the question, is there no way to disable automatic updating?  A button or something would be nice because I lost all my work in an update and since then I always make a backup but if, for example, you change something in other versions, the backup would no longer work.

**Comment by Newcomer1989** [comment]
> there is no way to avoid that? Taking advantage of the question, is there no way to disable automatic updating? A button or something would be nice because I lost all my work in an update and since then I always make a backup but if, for example, you change something in other versions, the backup would no longer work.

https://github.com/Newcomer1989/TSN-Ranksystem/wiki#automatically-update-function---why-is-there-no-option-to-disable-it

**Comment by Newcomer1989** [comment]
should be done with release 1.3.22
