### ISSUE TITLE
Undefined array key "uuid" Error

### ISSUE THREAD

**Issue by doman991** [Newcomer1989/TSN-Ranksystem#886]
I have 10k lines of same error. I have not change anything for few months except running !update command a month or 2 ago.
I can paste everything from log file because all 10k lines are almost triple of pastebin maximum size

Description | Fill out below
-- | --
Ranksystem Version | 1.3.22
Are you using TeamSpeak or TeaSpeak? | TeamSpeak 
Link to your Ranksystem Stats page | 304 hosted
Pastebin Link to your Ranksystem Log *¹ | pastebin.com/uWysDMnD

---

### 1) What did you do?
Nothing.
 
### 2) What result did you get?
N/A

### 3) What result did you expect?
N/A

---

#### *¹ Ranksystem Log - HOW-TO
- Change the Log-Level to `6 - Debug` (-> Webinterface -> Other -> Log-Level).
- Change the default language to `EN english` (-> Webinterface -> Other -> Language).
- Restart the Ranksystem Bot and let it run for at least 10 minutes (-> Webinterface -> Start / Stop bot -> Restart bot).
- Add a Ranksystem-Log extract which contains all since the last restart (-> Webinterface -> Start / Stop bot -> at bottom).
- Please use https://pastebin.com/ for sharing the log.

**Comment by doman991** [comment]
Sorry forgot to tag as bug :( i dont use github that often

**Comment by froland20** [comment]
@doman991 what version of php are you running?

**Comment by doman991** [comment]
> @doman991 what version of php are you running?

It`s hosted by TSN-Ranksystem not me so i dont know.

**Comment by Newcomer1989** [comment]
It should be already fixed in the current beta (1.3.23-beta-1).

So, it will be fixed with the next release. Thx for reporting 👍
