### ISSUE TITLE
How to reset time for users without reseting all time achieved

### ISSUE THREAD

**Issue by majcoooo** [Newcomer1989/TSN-Ranksystem#889]
Hi, 
I want to ask if it is possible to reset the time in the top of the month section without deleting everything, including the top of all time? Thank you for your response.

**Comment by Newcomer1989** [comment]
The time of the top month section is calculated every few hours new. It will be calculated against a snapshot table with values a month ago.

Don't know what exactly you want to reset at this point. Currently, there is no such option. Perhaps you can describe it a bit more.
