### ISSUE TITLE
User time check

### ISSUE THREAD

**Issue by peralta00** [Newcomer1989/TSN-Ranksystem#89]
The ranksystem could run the time check every minute to reduce logs created when connecting, because connecting every second is too fast, increases cpu usage and creates large log files. also you could make the ranksystem in java so the bot stays always connected to the server creating less logs and to reduce cpu usage.

**Comment by Newcomer1989** [comment]
> connecting every second is too fast, increases cpu usage

You can activate the slowmode to reduce the needed ressources. This will save much cpu time.


>  and creates large log files

Large log files will only be created, if something is wrong with your installation or configuration.


> also you could make the ranksystem in java so the bot stays always connected to the server creating less logs and to reduce cpu usage.

You are really funny.. The Ranksystem hast thousands of code lines. I will not change this right now to java. If you want, you are free to do this.
Also the Ranksystem establish a continuous connection to the TS3 server.
