### ISSUE TITLE
Public stats page takes sometimes up to 10 seconds to load

### ISSUE THREAD

**Issue by Sebbo94BY** [Newcomer1989/TSN-Ranksystem#891]
Description | Fill out below
-- | --
Ranksystem Version | 1.3.23 (latest, as you can't have an older version unfortunately: #818)
Are you using TeamSpeak or TeaSpeak? | TeamSpeak
Link to your Ranksystem Stats page | N/A
Pastebin Link to your Ranksystem Log | N/A

---

### 1) What did you do?

I've opened the public `/stats/` page of my TSN Ranksystem. The start page (`/stats/index.php`).

### 2) What result did you get?

The page opened as usual without any issues, but sometimes it takes up to ~10 seconds to load the page initially until I can even see any content:

![image](https://github.com/Newcomer1989/TSN-Ranksystem/assets/5154682/7f6a12c9-28ba-4155-8334-71e348414346) ![image](https://github.com/Newcomer1989/TSN-Ranksystem/assets/5154682/030de38c-bef4-4c2c-b14a-276c261d09f8)

All following page refreshes are super fast (max. 1 second) afterwards.

### 3) What result did you expect?

Loading the page should not take longer than 2-3 seconds in any case as some clients otherwise run in timeouts and it also causes a bad user experience, such long loading times.

### 4) How to reproduce

This issue is in 9 of 10 cases reproducible in a new private browser window. So it looks like as it only affects new sessions.

### 5) Additional information

All other web applications on the same web server have an average response time of 100ms. Only this project has an average response time of multiple seconds.

Following a figure from my monitoring, which shows how flacky the response time of the TSN Ranksystem is:

![image](https://github.com/Newcomer1989/TSN-Ranksystem/assets/5154682/a6361bdf-1f0d-4797-9c16-86b1673a0f01)

Please note, that it has a timeout of 5 seconds, so the graph won't show values higher than 5 seconds.

**Comment by Newcomer1989** [comment]
Tried it with different browser. I can't reproduce this issue.

Let's have a try on our instance, if you want:
https://ts-n.net/ranksystem_dev/stats/index.php

What mode of 'hash IP addresses' are you using (webinterface -> other)? This affects the loading time for new sessions.

Check also, you have set the following index on your database, which is important for loading times on the index page.
```
MariaDB [ts3_ranksystem]> show indexes from server_usage;
+--------------+------------+-----------------------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+---------+
| Table        | Non_unique | Key_name              | Seq_in_index | Column_name | Collation | Cardinality | Sub_part | Packed | Null | Index_type | Comment | Index_comment | Ignored |
+--------------+------------+-----------------------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+---------+
| server_usage |          1 | serverusage_timestamp |            1 | timestamp   | A         |       34861 |     NULL | NULL   |      | BTREE      |         |               | NO      |
+--------------+------------+-----------------------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+---------+
1 row in set (0.001 sec)
```
If it is missing, you can set it with the following SQL command - (this is also be set during an update of the Ranksystem):

``CREATE INDEX `serverusage_timestamp` ON `server_usage` (`timestamp`);``

**Comment by Sebbo94BY** [comment]
Hi @Newcomer1989,
On this specific instance, the `hash IP addresses` is set to `secure hashing` to be GDPR conform.

The database index was already there:
```mysql
MariaDB [tsnranksystem]> show indexes from server_usage;
+--------------+------------+-----------------------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+---------+
| Table        | Non_unique | Key_name              | Seq_in_index | Column_name | Collation | Cardinality | Sub_part | Packed | Null | Index_type | Comment | Index_comment | Ignored |
+--------------+------------+-----------------------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+---------+
| server_usage |          1 | serverusage_timestamp |            1 | timestamp   | A         |       32959 |     NULL | NULL   |      | BTREE      |         |               | NO      |
+--------------+------------+-----------------------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+---------+
1 row in set (0.001 sec)
```

I've quickly and temporary tested it with `fast hashing`: With this, the page is immediately super fast.

But based on the features description, I have to use `secure hashing` as only this is GDPR conform and this is important for this TSN Ranksystem installation.

So it seems like as the GDPR conform hashing setting has a performance issue, which needs to be fixed.

**Comment by Newcomer1989** [comment]
Then it is due to the hashing of the IP address for the respective session. However, this works as described. Performance issues are explicitly pointed out!

> secure hashing: IP addresses will be hashed. Each user will get his own salt, which makes it hard to decrypt the IP (=secure). This parameter is conforming with the EU-GDPR. Contra: This variation affects the performance, especially on bigger TeamSpeak servers, it will slow down the statistics page on first site load very much. Also, it increases the needed resources.

The procedure is as follows:

1) All online clients are read from the database, with encrypted IP.
2) The one of the website visitor is checked against the hash values out of 1). This is a complex calculation operation. This is the only way to ensure high security.

The more clients are online, the more calculations have to be done, which affects the runtime. We are using the password_verify function of PHP here. In the most secure variant, this is the only way it works. It also works faster, but then it is no longer Fort Knox, but 'fast hashing'. All options are available and can be used. But 'secure hashing' has exactly the described disadvantages in this case.

We do not know whether only the 'secure hashing' variant is GDPR-compliant. But this one it is in any case!
The extent to which an IP address is personal information at all is debatable. We are not aware of any current law in this regard. According to the interpretation of the GDPR, we have offered this option for security, to at least provide the option.
As a rule, however, data protection should already be satisfied with 'fast hashing'. The salt is formed individually for each instance.
