### ISSUE TITLE
Latest version 1.3.23 is not released on Github

### ISSUE THREAD

**Issue by Sebbo94BY** [Newcomer1989/TSN-Ranksystem#898]
The latest available version 1.3.23 is currently not released / tagged here on Github: https://github.com/Newcomer1989/TSN-Ranksystem/releases

But the auto-updater sees this newer version as it is available at the official TSN Ranksystem page at https://ts-n.net/ranksystem/stable .

Can you please release this version on Github as well?

I would like to update my TSN Ranksystems to the latest version using Git.

**Comment by Newcomer1989** [comment]
You are right.. We added this last release to Github also 👍
