### ISSUE TITLE
TS-N.net webpage error

### ISSUE THREAD

**Issue by Spazmic** [Newcomer1989/TSN-Ranksystem#9]
Hello,

In the cronjob specified on the installation page of the ranksystem, it is set to 10 minute when what I think you want is actually 1 minute.

Thanks

**Comment by Sqveeze** [comment]
No.

1.00 has changed and the bot is now always stay connected. Meaning the cronjob is just a "check" like the new arg says it in the command.

The new cronjob is just check if the bot is on or not. If not then start it. Thats why its every 10 minute

**Comment by Spazmic** [comment]
`*/10 * * * * php /path/to/your/websever/path/to/ranksystem/worker.php check >/dev/null 2>&1

If you want, you can edit the connection time.. Here it is every minute. (the lower the time, the more accurate the script works)`

This is what confused me.

**Comment by Newcomer1989** [comment]
Sorry, there I forgot to change the description. Its like Sqveeze said, its only to check the Ranksystem still runs. The desciption has to be:

>  */10 * * * * sudo -u www-data php /path/to/your/websever/path/to/ranksystem/worker.php check >/dev/null 2>&1
> 
> Replace www-data with your webuser! If you want, you can edit the connection time.. Here it is every 10 minutes.

I changed it on the official site. Thx for the hint!
