### ISSUE TITLE
Schlechte Performance vom TS, wenn der  Bot läuft 

### ISSUE THREAD

**Issue by Assassins88** [Newcomer1989/TSN-Ranksystem#90]
Hi,

ich hab festgestellt, dass wenn der Bot aktiv ist, mein TS extrem langsam reagiert. Sobald ich den Bot stoppe, läuft der TS wieder normal.

Kann es daran liegen, dass der Bot viel in der Datenbank schreibt / ließt, da mein TS-Server auch über die MySQL- Datenbank läuft?

**Comment by Shad86** [comment]
Das kommt nun drauf an, lässt du den Rankbot mit "Realtime" laufen?

Denn da kann es durchaus sein das die cpu last recht hoch ist.

Dem ganzen kannst du etwas entgegenwirken indem du per Webinterface im Reiter "Teamspeak" rechts unten "Slowmode" umstellst ("Low / Middle / High Delay" sind dort auswählbar).

Dadurch wird die Berechnung zwar ungenauer aber die Auslastung geht dabei auch um einiges runter.

Ich hoffe ich konnte dir damit helfen.

Grüße

Shad86

**Comment by Assassins88** [comment]
@Shad86 

Naja, die CPU Auslastung ist nicht das Problem. Der ist recht gechillt. Ich werd es mal versuchen mit slowmode. Was würdest du empfehlen.

**Comment by Shad86** [comment]
Hm also wenn du wirklich trotz "ruhigem" system Probleme hast ist das merkwürdig das du dann eine schlechte ts3 Performance bekommen solltest.

Eventuell mal so auch das system beobachten ob die Ressourcen an anderen Stellen knapp wird.

aber nunja "empfehlen" kann ich dir da nichts außer das du eben jede Slowmode Variante mal beobachtest ob sie eine Verbesserung bringt.

Um so weniger Delay um so genauer der Wert um so mehr Delay um so ungenauer der Wert aber dafür ressourcen schonender.

**Comment by Shad86** [comment]
Was sagt den uptime und wieviele cpus sind vorhanden? (einfach in die Konsole reinschreiben und enter drücken)

**Comment by Assassins88** [comment]
Das nächste Problem an der Sache ist, Sobald der Ranksystembot läuft ist der TS auf allen Serverlisten offline.

`18:28:05 up 6 days,  7:27,  1 user,  load average: 1,53, 2,05, 1,89`

**Comment by Shad86** [comment]
> und wieviele cpus sind vorhanden?

**Comment by Assassins88** [comment]
Oh, srry. 1 CPU 4 Kerne 8 Threads. Es ist ziemlich genau dieser Server:

https://www.soyoustart.com/de/angebote/sys-ip-2.xml

**Comment by Shad86** [comment]
Das System ist eig. dann mehr als ausreichend  - der Rankbot ist auch richtig installiert? Denn das wäre jetzt meine einzige Idee warum es eventuell rumzickt. Zwar in englisch aber siehe hier:

> ...there is a line with "Installation Linux:"

_its not directly a thing about starting it just with "another user" you have to start it with the webuser if you didn't really have created one but apache is installed you have to chown the ranksystem folder to the webuser.

for example (in most case if all is on standart this should usually work):

**[AS AN SECOND ADVISE THATS JUST AN EXAMPLE PLS EDIT THE THINGS TO YOUR RIGHT PATHS]**

go to your webfolder

`cd /var/www` OR `cd /var/www/html`

then

`chown www-data:www-data -Rf ranksystem/`

after that you can start the bot in the right way with following command:

`sudo -u www-data php /path/to/your/websever/path/to/ranksystem/worker.php start`

cronjob:

(In vim you have to press "i" to be able to edit the text after that press escpace then :wq) (on nano you just can paste the following at the end)

**[PLS Change all things to your right paths!!!!]**

`crontab -e`

`*/10 * * * * sudo -u www-data php /path/to/your/websever/path/to/ranksystem/worker.php check >/dev/null 2>&1`

**If Sudo isnt installed:**

Debian: `apt-get install sudo`
CentOS 6.5: `yum install sudo`

**Comment by Assassins88** [comment]
Der ist schon für den www-data Nutzer gesetzt (doofes Deutsch aber ich denke du weißt was gemeint ist :)).
Ich geh mal davon aus, dass er richtig installiert ist. Gut, beim dritten Schritt der Installation wurde nix angezeigt außer das der Benutzer angelegt wurde (wenn ich das noch richtig im Kopf hab.)

**Comment by Shad86** [comment]
Ja das sollte soweit richtig sein.

Was du mal noch überprüfen könntest wäre die php version

mit einer `info.php` datei mit folgendem Inhalt

`<?PHP
phpinfo();
?>`

Da mal schauen ob alles nur einmal vorhanden ist. (vor kurzem hatten wir einen mit 2 unterschiedlichen php versionen)

und stell sicher das es php 5.5.0 oder höher ist

auch sollte PDO vorhanden sein weiß eigentlich mit

`apt-get install php5-mysql`

mitgeliefert werden sollte

**Comment by Newcomer1989** [comment]
Bitte mal die MySQL Einstellungen überprüfen. Vermutlich ist der Server falsch konfiguriert, sodass die MySQL ins Schnaufen kommt, sobald noch weitere Dinge neben dem TS darauf zugreifen.

Stichworte sollten hier sein: Worker, Cache, Max Connections

Hilfe bei den Einstellungen der SQL kann und will ich auch gar nicht geben. 

Ansonsten kann die Last wie Shad86 schon angesprochen hat über den Slowmode reduziert werden. Dennoch wird mit der Datenbank kommuniziert, sodass das Problem vermutlich weiterhin bestehen bleibt nur mit kleinere Pausen dazwischen.

**Comment by Assassins88** [comment]
PHP liegt in der Version 7 bei mir vor. Da brauch ich nicht schauen. Das weiß ich. Hab es ja schließlich installiert. :P 

> Ansonsten kann die Last wie Shad86 schon angesprochen hat über den Slowmode reduziert werden. Dennoch wird mit der Datenbank kommuniziert, sodass das Problem vermutlich weiterhin bestehen bleibt nur mit kleinere Pausen dazwischen.

Ist auch so. Na muss ich mal non bissl rum experimentieren.

**Comment by Assassins88** [comment]
So, hab mal bissl rumexperimentiert und den MySQL-Server bissl eingestellt. Leider ist das Problem immer noch da. Das einzige, was ich noch nicht probiert hab, ist die Umstellung des TS von MySQL auf SQLite aber das ist ja nicht so einfach, da es wohl schwierig ist, die Datenbank zu convertieren und Lust darauf, alles neu zu erstellen hab ich auch nicht.

So kann ich es leider nicht verwenden, weshalb ich wohl darauf verzichten muss. Schade. :'(

**Comment by Newcomer1989** [comment]
Das Ranksystem unterstützt PDO und damit theoretisch verschiedene Datenbanken. Getestet ist zunächst nur die MySQL.
Eine Konvertierung zu SQLite wird nicht unterstützt. D.h. wenn müsste manuell konvertiert werden oder mit SQLite neu gestartet werden.
Empfehlen würde ich, dass in einer Test-Umgebung zunächst parallel auszuprobieren.

Ansonsten ist da Prinzip das Gleiche. Die Datenbank muss eingerichtet werden (egal ob MySQL, MSSQL, SQLite). Installation des Ranksystems nach Anleitung, usw.

**Comment by Assassins88** [comment]
Hab ich versucht. Hab auch mittlerweile PostgreSQL probiert aber da bekomme ich beim einrichten diverse Fehler. Entweder kommt, dass die angegebene Datenbank schon existiert und darunter noch mehr Fehler oder, wenn ich die Datenbank nicht vorher anlege, dass die Datenbank nicht existiert.

Bei SQLite gibt es ja keinen Datenbankserver und Benutzer mit PW auch nicht, wodurch die Einrichtung so nicht funktioniert. SQLite ist ja nur eine Datei auf der Festplatte die dann genutzt wird.

Irgend will eine höhere Macht nicht, dass ich das Ranksystem nutze. :'(

**Comment by Shad86** [comment]
Es ist für mich auch wahnsinnig seltsam das du solche Probleme hast mit so einem doch so relativ starkem system.

Was mir aber gerade auffällt an deinem geposteten system.

(und ich habe jetzt zwischenzeitlich 4 Seiten durchgesichtet)

Der Max Ram für diese CPU ist mit 24GB angegeben. Stellt sich also die Frage ob eventuell das System selbst das Problem ist weil wenn die CPU eben max. 24 GB Ram verarbeiten kann würde sich meiner Logik nach ein "Stau" bilden weil eben nur 24 GB durchpassen

**Comment by Assassins88** [comment]
Mhm, dass könnte sein. Auf dem Root läuft noch ein MC-Server, der so um die 20 GB verballert und der Swp Speicher liegt auch immer so bei 700-800 von 1024 MB.

**Comment by Shad86** [comment]
Werden denn die 20 GB voll ausgeschöpft? weil 20 klingt schon recht hoch, wenn möglich versuch es mal mit 15 GB und schau dann mal wie sich das System verhält mit dem ranksystem verhält.

**Comment by Assassins88** [comment]
Derzeit liegt er bei 19,1 GB. Naja, ist ein extrem gemoddeter Server (nicht meiner). Soweit ich weiß, sind da mehr als 200 Mods + Plugins drin. Mal schauen, ob der auch mit weniger auskommt.

Oder ne, ich werde ihn mal aus machen und dann einfach mal so testen, wenn er aus ist. Läuft es da, kann man es ja immer noch mit weniger RAM versuchen.

Danke dir auch schon mal für deine Geduld mit mir. :)

**Comment by Assassins88** [comment]
So, hab es jetzt mal ohne den MC-Server probiert. Ist immer noch das gleiche Problem. *grrrr*

**Comment by Newcomer1989** [comment]
Wenn du magst, hoste ich dir das Ranksystem auch. Das wäre kein Problem.
Hierfür bitte eine kurze Nachricht über das Kontaktformular schicken, sofern Interesse besteht.
http://ts-n.net/contact.php

**Comment by Assassins88** [comment]
Ja, besteht, hab ich auch schon gelesen aber es steht ja auch da, dass es nur für eine geringe Anzahl von Usern ist. Ich hab nen Public TS, der so ca. ne Woche alt ist und wir haben jetzt schon bis zu 60 User drauf und hoffen natürlich, dass es noch mehr werden.

**Comment by Assassins88** [comment]
So, hab dir ne Anfrage geschickt über das Kontaktformular. :)
