### ISSUE TITLE
Cronjob issues

### ISSUE THREAD

**Issue by ryanmemer** [Newcomer1989/TSN-Ranksystem#92]
So I have the ranksystem in my webspace all setup completely fine. I have the cronjob running every 1 minute. The user that has full privileges in the web space is 'ryan'. I will include the cronjob here. 

` */1 * * * * sudo -u ryan php /var/www/vhosts/serverofmanykeks.online/httpdocs/rank/worker.php check >/dev/null 2>&1`

The problem I'm experiencing is that there's 10+ rank bots connecting to my server query at any one time. I imagine it's something to do with my cronjob so that's why I included it. Every 1 minute an extra rank bot connects.

**Comment by Newcomer1989** [comment]
Why opened a new issue? Its already known and you know this also, cause you posted your problem there...
issues 86

**Comment by ryanmemer** [comment]
Yes little do I know that it didn't solve it
