### ISSUE TITLE
Function to add time to an user

### ISSUE THREAD

**Issue by juvcrafter** [Newcomer1989/TSN-Ranksystem#94]
When Comes the function back, which could add a couple of time to any/one user?
I Need it :)

**Comment by Newcomer1989** [comment]
You can do this actually with a boost group.

Define a boost with the wished time as result. I would distribute this on for example 30 seconds (makes it more precise)
wished time / 30 seconds = factor

So an example would looks like
servergroup ID => factor => 30 (seconds)

Then give your user on the ts3 the above defined servergroup. Be sure the user is active in this 30 seconds and didn't idle.

Independ thereof the function "add time to user" will come back. But I cannot give you a date for this. I think it will not happened with release 1.1.1.

**Comment by juvcrafter** [comment]
But how can I give an offline user his Server time?

**Comment by Newcomer1989** [comment]
This is not possible now. There you have to wait the feature is back.

The only way would actual to edit this directly inside the database. Table user, column count.
If you know, what you do there ok, but I will not support this way. So I will also not answer any question how to do this or anything else!

**Comment by Newcomer1989** [comment]
release 1.1.2 is out and the function "add time to user" is part of them
