### ISSUE TITLE
Adding time

### ISSUE THREAD

**Issue by juvcrafter** [Newcomer1989/TSN-Ranksystem#95]
Hey,
Why can I only add online time to users, which are online? Can you Change?
P.S. I use the old Version for this and after this, I will upgrade.

**Comment by Newcomer1989** [comment]
This is an enhancement to feature, which doesn't exits any more. I am not willing to fix this in an older version, provided that it was at all wrong there.

**Comment by juvcrafter** [comment]
But how can I give someone online-time on the newest Version, If he is offline?

**Comment by Newcomer1989** [comment]
Actual there is no feature. If you ask with the newest version, your question will be dublicated https://github.com/Newcomer1989/TSN-Ranksystem/issues/94
