### ISSUE TITLE
Bot don't hold the connection - Error 0: invalid reply from the server

### ISSUE THREAD

**Issue by eZaY** [Newcomer1989/TSN-Ranksystem#96]
Hey, I have a problem.
My Bot don't stay at my Server (Newest bot version).
The Error in Line is `2016-09-05 17:35:08.447072   ERROR     Error 0: invalid reply from the server`.
Why I try it on another Linux 14.04 server and the thing is with a fresh (the same TS3 server version (Server 32-bit 3.0.13.3 ) ) the bot works fine.
Before I made a new direction, I use the old 1.0.2 version. Now I have update my Ts version to 3.0.13.3 and update my bot to 1.1.0 and now the bot connect for 1 second and leave then. 
Ps: I use a new Database and a new direction.

Sorry for my bad english I'm german :)

**Comment by Newcomer1989** [comment]
It could be the bot get banned from the TS3 server.

Please check the following things:

1) **Whitelist** the IP address of your webhost (where the webserver/PHP runs) to your TS3 server. You should find a `query_ip_whitelist.txt` inside the TS3 server root directory. Add the IP of the webhost here.

2) Be sure your query user is not restricted with command limitation. Give the query user the TS3 permission **b_client_ignore_antiflood**. This should prefer a blocking due flood protection.


If your are not be able to change the two points above, you can try to use the **Slowmode**. This function you can activate inside the webinterface inside the TeamSpeak options. In this case use the "High delay (1,0 seconds)".
For this stop the Bot, activate the slowmode and wait 10-15 min. before restarting the Bot.



How you could check its really a problem due a ban or flood?

On linux there is an easy way to scan the tcp traffic. You need the packed tcpdump (apt-get install tcpdump).
There you could snip the traffic between the webserver and the TS3 server.
Run the following command on your webhost.

`tcpdump -nXvvv "src host xxx.xxx.xxx.xxx"`

Replace xxx.xxx.xxx.xxx with the IP address of your TS3 server.

**Comment by eZaY** [comment]
Thanks It works now :) :+1:
